### ISSUE TITLE
Example with lazy loading modules doesn't install correctly

### ISSUE THREAD

**Issue by Dynkin** [vercel/next.js#10067]
# Examples bug report

## Example name

Lazy loading modules: https://nextjs.org/learn/excel/lazy-loading-modules/setup 

## Describe the bug

The result of `npm install` has 2 errors:

```
2 errors generated.
make: *** [Release/obj.target/grpc_node/ext/call.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.2.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1023:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc
node-pre-gyp ERR! node -v v13.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/13.2.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/r.dynkin/Projects/playground/next-learn-demo/E2-lazy-loading-modules/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
```

Then `npm run dev` simply doesn't work too.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
git clone https://github.com/zeit/next-learn-demo.git
cd next-learn-demo
cd E2-lazy-loading-modules
npm install
```

Then see errors

## Expected behavior

Installation is successful. App starts without problems and works correctly.

## Screenshots

![image](https://user-images.githubusercontent.com/4177911/72254501-49e24480-3615-11ea-81dd-cce964ecb0d2.png)

## System information

- OS: macOS Catalina v10.15.2
- Version of Next.js: resolved from https://registry.npmjs.org/next/-/next-9.1.7.tgz
- Version of NodeJS: v13.2.0
- Version of NPM: v6.13.6

**Comment by Timer** [comment]
Closing as stale. Please let us know if you still have this problem.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
