### ISSUE TITLE
With-react-relay-network-modern example throws error on second load onwards

### ISSUE THREAD

**Issue by greasematic** [vercel/next.js#10821]
# Bug report

## Describe the bug
Tried to setup the example at https://github.com/zeit/next.js/tree/canary/examples/with-react-relay-network-modern as instructed. On `npm run dev`, accessing http://localhost:3000 works great the first time. However, on reload of the page, following error is thrown on the server side (during SSR)
```
TypeError: Cannot read property ‘edges’ of undefined
    at BlogPosts (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/.next/server/static/HKHYBLn01M_y5-cA4O5c8/pages/index.js:141:104)
    at c (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:496)
    at Ga (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:31:1)
    at a.render (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:367)
    at a.read (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:450)
    at renderToString (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:82)
    at render (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/next/dist/next-server/server/render.js:81:16)
    at Object.renderPage (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/next/dist/next-server/server/render.js:346:16)
    at Function.getInitialProps (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/.next/server/static/HKHYBLn01M_y5-cA4O5c8/pages/_document.js:287:19)
    at Object.loadGetInitialProps (/Users/raghu/work/next.js/examples/with-react-relay-network-modern/node_modules/next/dist/next-server/lib/utils.js:59:29)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. run `npm init next-app --example with-react-relay-network-modern with-react-relay-network-modern-app`
2. run `npm install`
3. run `npm run schema`
4. run `npm run dev`
5. Check http://localhost:3000/ on your browser (all ok!)
6. Reload/refresh the page (above error)
7. Stop and run `npm run dev` again. Check http://localhost:3000/ on your browser again (all ok). Refresh again => reproduces error

## Expected behavior
Shouldn't throw the error on reload

## System information
- OS: macOS
- Version of Next.js: 9.2.3

**Comment by Timer** [comment]
This example has been updated multiple times since this issue was opened. Please try again!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
