### ISSUE TITLE
next@9.3.1 cause `@hapi/hapi` throw warning

### ISSUE THREAD

**Issue by 1846689910** [vercel/next.js#11270]
# Bug report

## Describe the bug

Hi Next.js team, 

I am having an issue after updating next from `9.3.0` -> `9.3.1`. It seems the new `next` does not get along well with `@hapi/hapi`19.1.1. There will be a warning after I run the hapi server with `yarn run hapi` in my project

```
(node:71453) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:535:11)
    at Object.internals.writeHead (/Users/eriche/Documents/projects/type-18-next/node_modules/@hapi/hapi/lib/transmit.js:328:21)
    at Object.internals.transmit (/Users/eriche/Documents/projects/type-18-next/node_modules/@hapi/hapi/lib/transmit.js:107:15)
    at Object.internals.fail (/Users/eriche/Documents/projects/type-18-next/node_modules/@hapi/hapi/lib/transmit.js:70:22)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:418:9)
    at async Request._reply (/Users/eriche/Documents/projects/type-18-next/node_modules/@hapi/hapi/lib/request.js:443:9)
(node:71453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:71453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

related [PR](https://github.com/1846689910/type-18-next/pull/33) for updating dependencies

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `yarn add next@^9.3.1`
2. `yarn run hapi`

## Expected behavior

no warning throw out if I use `9.3.0`

## System information

- OS: macOS
- Browser chrome
- Version of Next.js: `9.3.1`

**Comment by leerob** [comment]
Related to https://github.com/vercel/next.js/issues/14186, which was fixed 🙏

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
