### ISSUE TITLE
Error: Cannot find module '/path/.next/build-manifest.json'

### ISSUE THREAD

**Issue by 0livare** [vercel/next.js#11377]
# Bug report

## Describe the bug

When a SASS error happens, the Next CLI properly tells me about the SASS error, but then it prints this error to the console every few seconds until I fix the SASS error:

```
{ Error: Cannot find module '/Users/zach/dev/test/next-module-not-found-bug/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadComponents (/Users/zach/dev/test/next-module-not-found-bug/node_modules/next/dist/next-server/server/load-components.js:29:9)
    at DevServer.findPageComponents (/Users/zach/dev/test/next-module-not-found-bug/node_modules/next/dist/next-server/server/next-server.js:529:60)
    at DevServer.renderErrorToHTML (/Users/zach/dev/test/next-module-not-found-bug/node_modules/next/dist/next-server/server/next-server.js:829:33)
    at DevServer.renderErrorToHTML (/Users/zach/dev/test/next-module-not-found-bug/node_modules/next/dist/server/next-dev-server.js:15:811)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```

## To Reproduce

I've created a reproduction repository [here](https://github.com/zposten/next-module-not-found-bug).

> Note: The SASS error in this repository is intentional to demonstrate this Next.js issue

1. Run the following in a terminal:

```bash
git clone https://github.com/zposten/next-module-not-found-bug.git
cd next-module-not-found-bug
yarn
yarn start
```
2. See error

## Expected behavior

The SASS error should be printed a single time.  This other error should not be printed to the terminal continuously.

## System information

- OS: macOS 10.15.3
- Version of Next.js: 9.3.2

## Additional Context

Both of the apps that I've seen this issue in have 
  - Used typescript
  - Had a custom `_app.tsx`
  - Used the new [built in SASS support for global stylesheets](https://nextjs.org/blog/next-9-3#built-in-sass-support-for-global-stylesheets)

I have not exhaustively tested various configurations to figure out the precise cause of this issue.

This issue seems similar to:

- #7839
- #4660
- #6287

...but all these issues are closed

**Comment by AZIMAT** [comment]
Hi

I had some edits on your example.

change your _app.tx to

```
import React from "react";
import App from "next/app";

import "./_app.scss";

export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
```

will run your example without any issue, can you just check it again and send your feedback?

**Comment by trusktr** [comment]
This is a weird bug. I'm on an older version of Next (6.1.1, I should try updating!) but the error is weird.  As mentioned in #4660, creating a blank `build-manifest.json` with the content `{}` fixes the issue (at least temporarily) and causes other more sensible errors to appear.

**Comment by mubarakshow** [comment]
Had the same issue. Got it fixed by upgrading yarn
`yarn upgrade`

As soon as that was done, the `build-manifest.json` appeared.

Cheers!

**Comment by hx-gh** [comment]
Same issue here, i'm using NPM.

**Comment by Kay2dan** [comment]
Just encountered this bug as well. Tried solutions from the other thread, to no success.

**Comment by illiabakunovskyi** [comment]
run into same bug

**Comment by sahebmohammadi** [comment]
i also faced the same error whene I add new component to the pages! 
what is your approach ?

**Comment by illiabakunovskyi** [comment]
i have this issue, when installing new project with typescript and adding aliases to folders in .babelrc and tsconfig

**Comment by shadowwalker** [comment]
I tried install `sass` on my own with `yarn add -D sass`, the issue is resolved.

**Comment by mrgnou** [comment]
> I tried install `sass` on my own with `yarn add -D sass`, the issue is resolved.

Not working for me (using npm).

**Comment by chaydan9xtb** [comment]
> I tried install `sass` on my own with `yarn add -D sass`, the issue is resolved.

I have tried it and it doesn't work

**Comment by BrunoQuaresma** [comment]
I tried to upgrade yarn and no success.

**Comment by saadbinsaeed** [comment]
I upgraded from 9 to 10 and went into this problem. [
![image](https://user-images.githubusercontent.com/21288440/103231141-eaca2c80-4958-11eb-8f6c-9f251df0884b.png)
](url)

**Comment by kriscarle** [comment]
I resolved this error by removing the `.next` folder and `node_modules` and reinstalling with yarn. 

```sh
rm -rf .next
rm -rf node_modules
yarn
```

**Comment by warent** [comment]
If anyone is encountering this in Vercel deployments, my problem was that I had a custom output directory. I don't think you can customize this in Vercel so you'll have to remove it. i.e.

next.config.js should not have `distDir: "(whatever)",`

**Comment by jlison** [comment]
I would recommend making sure you are on an active node js version by running `node --version`

**Comment by bclausi** [comment]
If anyone is still having this issue, I've found that you can rebuild the dependency with `npm rebuild node-sass`.  That should fix the build errors going forward.

**Comment by Showrin** [comment]
I faced the same issue. I tried the following steps and got it resolved ✅.

- [x] Add `sass` as dev dependency, Run **`yarn add -D sass`**
- [x] Remove the `node-sass` as it's older and does as same as `sass`. Run **`yarn remove node-sass`**

**Comment by ziedHamdi** [comment]
For me this happens in a very weired manner: I have a function in my client.js

```
function createIsomorphLink() {
  if (isSSR()) {
    const { SchemaLink } = require('@apollo/client/link/schema')
    const { schema } = require('./schema')
    return new SchemaLink({ schema })
  } else {
    const { HttpLink } = require('@apollo/client/link/http')
      return new HttpLink({
      uri: '/api/graphql',
      credentials: 'same-origin',
    })
  }
}

```

in util.js
```
export function isSSR() {
    return typeof window === 'undefined'
}
```

With the code like this I get the error:
```
./node_modules/apollo-server-core/dist/ApolloServer.js:28:0
Module not found: Can't resolve 'net'
null
```

When I replace the isSSR method by it content, the error disappears:
  `if (typeof window === 'undefined') {`

The server really complains about not finding the 'net' module since when I install it, it starts asking for another module.

I understand this can seem unbelievable: I found it because I had commit that was working fine, so I checked line by line what causes the issue, and now I can reproduce this consistently (even though I find it frightening because I can't predict what line of code could break my project)

**Comment by aaron5670** [comment]
I upgraded from 10.2.1 to 11.0.1 and went into this problem. Still found no fix :(

**Comment by dieuit07** [comment]
I encountered this issue when create a new cms-wordpress with this command 

```npx create-next-app --example cms-wordpress cms-wordpress-app```

my project's next.js version is "11.0.1"

**Comment by halchester** [comment]
`yarn upgrade` or `npm upgrade` does solve this issue.

**Comment by dimuska139** [comment]
How to fix it? Any news?

**Comment by codeGTI** [comment]
Anyone got solution this issue. I stucked on this issue from last 8 Hours. 

- [ ]

**Comment by codeGTI** [comment]
> I upgraded from 9 to 10 and went into this problem. [ ![image](https://user-images.githubusercontent.com/21288440/103231141-eaca2c80-4958-11eb-8f6c-9f251df0884b.png) ](url)
> 
> Usin NPM

Did it solved your Proble,?

**Comment by codeGTI** [comment]
Hello All,

Last 24 Hours i was stocked on this issue. i solved this problem removing the non page component from the page folder in the project.

**Comment by HarshaDW** [comment]
Issue still persist for me! While moving babel to swc

**Comment by davidtheclark** [comment]
This issue is blocking me from upgrading from 12.0.7 to 12.0.9 (or 12.0.10). As long as I stay on 12.0.7 I'm fine, but if I try to upgrade to 12.0.9 (or 12.0.10), I hit this error. I have tried deleting `.next`.

I'm using Node 16.13.1 and pnpm 6.29.1.

**Comment by Biboswan** [comment]
I'm too facing the error on `next:12.1.14` It is trying to require `.next/build-manifest.json` but there is no such manifest file inside `.next`. Any clue on the significance of the that file.
It tries to require 
 `/.next/react-loadable-manifest.json`
`/.next/server/middleware-flight-manifest.json`

**Comment by weykon** [comment]
![image](https://github.com/vercel/next.js/assets/36456814/8941daad-3940-4ae5-867d-0c156ade892d)
let look the "_page.tsx" when I use this name is no error , Its original name was "page.tsx".
if it call page.tsx will cause Error: Cannot find module '******/.next/server/app/page_client-reference-manifest.js'.

So this may be related to the resolution of the routing group.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
