### ISSUE TITLE
SSG constantly results in etaddrinfo ENOTFOUND with +2500 pages

### ISSUE THREAD

**Issue by Aleksion** [vercel/next.js#12494]
# Bug report

## Describe the bug
After the SSG build went above 2000 pages, the whole build process starts failing with ENOTFOUND errors. My guess is that it has to do with hitting a limit on the maximum number of HTTP connections (I read somewhere it might be the internal dns resolver in node).

Has anyone else encountered this?

```
Error occurred prerendering page "/de/city/philadelphia/chinatown". Read more: https://err.sh/next.js/prerender-error:
Error: Failed to render serverless page
Automatically optimizing pages ...FetchError: request to https://bounce.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=50&orderings=%5Bmy.press_items.priority%20desc%5D&ref=XrCLmBAAACEAWAw3&q=%5B%5Bat(document.type%2C%20%22press_items%22)%5D%5D failed, reason: getaddrinfo ENOTFOUND bounce.cdn.prismic.io
    at ClientRequest.<anonymous> (/Users/aleks/projects/bounce/v2/app/apps/marketing/.next/serverless/pages/[lang]/blog.js:11522:11)
    at ClientRequest.emit (events.js:305:20)
    at TLSSocket.socketErrorListener (_http_client.js:423:9)
    at TLSSocket.emit (events.js:305:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://bounce.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=50&orderings=%5Bmy.press_items.priority%20desc%5D&ref=XrCLmBAAACEAWAw3&q=%5B%5Bat(document.type%2C%20%22press_items%22)%5D%5D failed, reason: getaddrinfo ENOTFOUND bounce.cdn.prismic.io',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9.4.6
- Version of Node.js: 13.5.0

**Comment by Aleksion** [comment]
The issue seems to stem from the fact that I was doing the following in a lot of my `getStaticProps` functions:
```ts
const [promise1, promises2, promise3, promise4, promise5, promise6] = await Promise.all([fn1, fn2,fn3,fn4,fn5,fn6])
```
This made for a LOT of parallel requests which it couldn't handle

**Comment by timneutkens** [comment]
Please add a complete reproduction.

**Comment by Timer** [comment]
Closing as stale.

**Comment by iam4x** [comment]
I was running the same issue, when building 150+ pages and was doing the same `Promise.all` switching to external APIs call in series did fix the issue.

Thank's for the hint @Aleksion :+1:

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
