### ISSUE TITLE
Development server has a flash of unstyled content (FOUC)

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#13058]
# Bug report

## Describe the bug

When using Next.js, it appears that the CSS isn't fully hydrated into the `<head>` when the `<div id="__next">` element first becomes visible.

This causes a flash of unstyled content (or FOUC) when running our development server. It seems like it's fine in production though (which seems strange to me).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone [this repository](https://github.com/tutorbookapp/covid-tutoring) by running:
```
$ git clone https://github.com/tutorbookapp/covid-tutoring
```
2. Install our dependencies (more details in our `README.md`) by running:
```
$ npm i && lerna bootstrap --hoist
```
3. Start a development server by running:
```
$ npm run dev
```
4. Notice the FOUC when first loading the page.

## Expected behavior

The `<div id="__next">` element should only be visible **after** the necessary above-the-fold stylesheets (i.e. the style sheets that are included in the React components that are visible above-the-fold) are inserted into `<head>`. The remaining stylesheets can then be loaded with the `<div id="__next">` element visible.

## Screenshots

See the FOUC visible on our development server:

![fouc](https://user-images.githubusercontent.com/20798889/82243201-09ad0e80-98f4-11ea-9b09-c00c7897e85e.gif)

Notice that it's gone on [our production website](https://tutorbook.org):

![no-fouc](https://user-images.githubusercontent.com/20798889/82243247-1df10b80-98f4-11ea-9ad9-01275a97a448.gif)

## System information

- OS: Ubuntu 18.04.2
- Browser: Firefox 76.0.1
- Version of Next.js: 9.4.0
- Version of Node.js: 12.16.1

**Comment by avijitelu** [comment]
I am also facing this problem when I use css modules but when I use styled-jsx then It works fine.

**Comment by robgraeber** [comment]
I notice a similar issue that global css in _app.js doesn't seem to be loaded with javascript off while it's in dev mode. It makes SSR harder to test since there could be missing styles.

**Comment by derskeal** [comment]
@robgraeber I have the exact issue you do. The CSS is being compiled into _app.js instead of a separate css file.

**Comment by dnaranjo89** [comment]
Same issue here. 
I've created a minimum example reproducing this issue: https://github.com/dnaranjo89/next-css-ssr

**Comment by robgraeber** [comment]
Also sometimes I'll edit some css in inspector and any change causes the whole page's css to be wrecked somehow. Has anyone experienced that?

**Comment by robgraeber** [comment]
@derskeal a workaround is to use this sass plugin and import your stylesheets via sass in your Layout component: https://github.com/giuseppeg/styled-jsx-plugin-sass

**Comment by yanv1991** [comment]
@Timer I could reproduce this issue in this repo https://github.com/yanv1991/demo-react-dom, this is not loading the styles using built in sass modules with a dynamic loaded component for ssr in prod mode

**Comment by Timer** [comment]
This project cannot be ran:
```
error - Error [FirebaseError]: projectId must be a string in FirebaseApp.options
    at new FirestoreError (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/firestore/dist/index.node.cjs.js:1223:28)
    at Function.Firestore.databaseIdFromApp (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/firestore/dist/index.node.cjs.js:21018:19)
    at new Firestore (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/firestore/dist/index.node.cjs.js:20850:42)
    at /Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/firestore/dist/index.node.cjs.js:22871:66
    at Component.instanceFactory (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/firestore/dist/index.node.cjs.js:22410:16)
    at Provider.getOrInitializeService (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/component/dist/index.cjs.js:219:39)
    at Provider.getImmediate (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/component/dist/index.cjs.js:120:33)
    at FirebaseAppImpl._getService (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/app/dist/index.node.cjs.js:228:49)
    at FirebaseAppImpl.firebaseAppImpl.<computed> [as firestore] (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/app/dist/index.node.cjs.js:440:39)
    at Object.serviceNamespace [as firestore] (/Users/joe/Desktop/scratch2/covid-tutoring/node_modules/@firebase/app/dist/index.node.cjs.js:420:45)
    at eval (webpack-internal:///./src/firebase/db.tsx:19:124)
    at Module../src/firebase/db.tsx (/Users/joe/Desktop/scratch2/covid-tutoring/.next/server/static/development/pages/_app.js:128:1)
    at __webpack_require__ (/Users/joe/Desktop/scratch2/covid-tutoring/.next/server/static/development/pages/_app.js:23:31)
    at eval (webpack-internal:///./src/firebase/user.tsx:12:61)
    at Module../src/firebase/user.tsx (/Users/joe/Desktop/scratch2/covid-tutoring/.next/server/static/development/pages/_app.js:152:1)
    at __webpack_require__ (/Users/joe/Desktop/scratch2/covid-tutoring/.next/server/static/development/pages/_app.js:23:31) {
  code: 'invalid-argument',
  toString: [Function]
}
```

**Comment by Timer** [comment]
This should be fixed in `next@^9.4.5-canary.15`! Please upgrade and let us know.

**Comment by showell215** [comment]
Thanks @Timer! 🎉  I tested and the fix works for me.

**Comment by jimbuck** [comment]
I was experiencing this in both dev mode and production mode in a custom server (incrementally converting pages on enterprise site). `^9.4.5-canary.15` fixed it for me!

**Comment by casperle** [comment]
Hi guys. Checked the problem with the canary release, it fixes the issue in dev mode but in production it still remains. Does somebody experiences the same issue?

**Comment by ozthekoder** [comment]
I am also still experiencing this in production after the update to the canary release.

> Hi guys. Checked the problem with the canary release, it fixes the issue in dev mode but in production it still remains. Does somebody experiences the same issue?
> 
> In the production build there is missing the `<style data-next-hide-fouc="true">body{display:none}</style>`.

Same here, is this a different issue when it happens in prod or related, does anyone know?

**Comment by showell215** [comment]
> Same here, is this a different issue when it happens in prod or related, does anyone know?

For me this issue was only occurring in dev mode, not production mode. So given that, I'd assume the prod issue may have a different cause.

**Comment by BlakeBrown** [comment]
> Hi guys. Checked the problem with the canary release, it fixes the issue in dev mode but in production it still remains. Does somebody experiences the same issue?
> 
> In the production build there is missing the `<style data-next-hide-fouc="true">body{display:none}</style>`.

Was anyone able to fix this in production? Canary release fixed our dev build, but production is still broken.

**Comment by jimmynames** [comment]
so is canary latest version of next then?

**Comment by nicholaschiang** [comment]
Yes @jimmynames, canary is the WIP latest version (the term originated from miners using canary birds to test for toxic fumes... The canary version of Next.js could be sketch).

**Comment by Timer** [comment]
This fix is on the stable release of Next.js 9.5.0 and 9.5.1, or newer!

**Comment by florianmatz** [comment]
What about production? I'm still experiences the FOUC with StyledComponents + Material UI

**Comment by praveen7557** [comment]
Did anybody find any solution for this?

**Comment by casperle** [comment]
Actually as a quick fix you can do the following:

1. Add the following css to your page
```css
.no-fouc {
  visibility: hidden;
  opacity: 0;
}

.fouc {
  visibility: visible;
  opacity: 1;
}
```

2. Set the `no-fouc` class to the html element in your app
```html
<html className="no-fouc">
...
</html>
```

3. Add this functionality to your App component
```jsx
...
componentDidMount() {
  const removeFouc = (foucElement) => {
    foucElement.className = foucElement.className.replace('no-fouc', 'fouc');
  };

  removeFouc(document.documentElement);
}
...
```

This will hide the content of the page until the App component gets fully loaded. At that time all the CSS is parsed already.

**Comment by AlexTechNoir** [comment]
Until this issue's fixed, I'm using [dynamic import without SSR](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) on component containing MUI to avoid FOUC.

Note that in this case you have to handle Layout Shift, the solutions to which may be a trade-offs depending on your situation.

**Comment by ElegantSoft** [comment]
I happen's to me with latest version

**Comment by osequi** [comment]
It's happening to me both in production and dev.

**Comment by tgrassl** [comment]
Same for me in production with scss modules and next 10.0.8

**Comment by anatolzak** [comment]
I am still getting the same problem of unstyled content showing when the page loads in production.

Is anyone working on fixing this?

> Actually as a quick fix you can do the following:
> 
>     1. Add the following css to your page
> 
> 
> ```css
> .no-fouc {
>   visibility: hidden;
>   opacity: 0;
> }
> 
> .fouc {
>   visibility: visible;
>   opacity: 1;
> }
> ```
> 
>     1. Set the `no-fouc` class to the html element in your app
> 
> 
> ```
> <html className="no-fouc">
> ...
> </html>
> ```
> 
>     1. Add this functionality to your App component
> 
> 
> ```js
> ...
> componentDidMount() {
>   const removeFouc = (foucElement) => {
>     foucElement.className = foucElement.className.replace('no-fouc', 'fouc');
>   };
> 
>   removeFouc(document.documentElement);
> }
> ...
> ```
> 
> This will hide the content of the page until the App component gets fully loaded. At that time all the CSS is parsed already.

This is a great solution, but the problem though is that one of the reasons to use nextjs is because it prerenders the page the user is trying to load, which allows the user to see the page way faster because they don't have to wait for the javascript to both load and finish running. This solution is counterproductive to that.

Please fix this

**Comment by jamesryan-dev** [comment]
I found I was getting this FOUC because I had miscorrectly used `next/head` so I can only suggest to anyone experiencing this issue - to try running your code/environment with a stable, starter _document and _app.js to see if this resolves your issue

**Comment by peps** [comment]
I'm running into this issue in production only using styled-components with a custom .babelrc in SSR mode.

```
{
	"presets": ["next/babel"],
	"plugins": [["styled-components", { "ssr": true }]]
}
```

**Comment by anatolzak** [comment]
I was getting FOUC on Firefox in production. 

I found out it was a Firefox bug which can be solved by adding a dummy `<script>` tag right after `<body>`, like this:

```javascript
// _document.js

import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
	static async getInitialProps(ctx) {
		const initialProps = await Document.getInitialProps(ctx)
		return { ...initialProps }
	}

	render() {
		return (
			<Html>
				<Head />
				<body>
					<script>0</script>
					<Main />
					<NextScript />
				</body>
			</Html>
		)
	}
}

export default MyDocument
```

Sounds weird but it did indeed solve the FOUC problem! 🎉

**Comment by coultonluke** [comment]
> I found I was getting this FOUC because I had miscorrectly used `next/head` so I can only suggest to anyone experiencing this issue - to try running your code/environment with a stable, starter _document and _app.js to see if this resolves your issue

Please can you tell me how you mis-correctly used it?

**Comment by jamesryan-dev** [comment]
from what I can remember I believe I was importing it incorrectly as a standalone item rather than `'next/document'`

**Comment by coultonluke** [comment]
> from what I can remember I believe I was importing it incorrectly as a standalone item rather than `'next/document'`

Thank you for that. I'm relatively new to nextjs so thanks for that. I'm using the MUI nextjs example and I can see that the document.tsx (or .js in the template) uses `Head` from `next/document` and I was using it from `next/head`. I'm going to test that now so that I confirm the FOUC is no longer happening for me.

The nextjs documentation shows the use of `next/head` but for a custom document to use `Head` component from `next/document`.

Here's some related links in case it helps anyone:
https://github.com/vercel/next.js/discussions/12290
https://nextjs.org/docs/advanced-features/custom-document

**Comment by jamesryan-dev** [comment]
I think as Next.js has evolved maybe the correct use / implementation of `Head` might of changed.. I would always follow / go with whatever next.js examples [most up to date] use as to avoid any issues.. =}

**Comment by coultonluke** [comment]
I'm still getting FOUC when using the official MUI example.

Their example shows the `Head` in `_document.js` from `next/document`, then the use of `next/head` in the _app.js, links below:
https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/_document.js
https://github.com/mui-org/material-ui/blob/master/examples/nextjs/pages/_app.js

Then I'm using the `Head` from `next/head` in one of my own components in `/pages`. Strange that it only happens in production though.

**Comment by jamesryan-dev** [comment]
could be something else then - I copied a fresh instance of `_document.js` and `_app.js` and it resolved my issue.. this might not mean that your issue is the same.. when it comes to high level issues like this I GCSE science it and remove all the pieces and then slowly add again.. good luck I hope this strategy or further googling/comms may help

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
