### ISSUE TITLE
npm run dev fails on next@9.4.4

### ISSUE THREAD

**Issue by rohan-deshpande** [vercel/next.js#13889]
# Bug report

## Describe the bug

Running the `npm run dev` command produces the following error

```
> nebula-web@1.2.9 dev /Users/rohan/Projects/nebula-web
> next

ready - started server on http://localhost:3000
TypeError: Cannot read property 'access' of undefined
    at fileExists (/Users/rohan/Projects/nebula-web/node_modules/next/dist/lib/file-exists.js:1:211)
    at verifyTypeScriptSetup (/Users/rohan/Projects/nebula-web/node_modules/next/dist/lib/verifyTypeScriptSetup.js:1:3167)
    at DevServer.prepare (/Users/rohan/Projects/nebula-web/node_modules/next/dist/server/next-dev-server.js:10:1908)
    at then (/Users/rohan/Projects/nebula-web/node_modules/next/dist/cli/next-dev.js:21:369)
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
```

## To Reproduce

```
git clone https://github.com/creativelifeform/nebula-web.git
cd nebula-web 
npm install 
npm run dev
```

## Expected behavior

The development environment loads without error 

## System information

- OS: macOS Mojave v10.14.5
- Browser: N/A
- Version of Next.js: [9.4.4]
- Version of Node.js: [10.0.0]

## Additional context

Everything is working at a previous commit in the repo `77f222f`, if you check this commit out and `npm run dev` it all works fine. This was using `next@9.2.1`

**Comment by sagar-gavhane** [comment]
@rohan-deshpande Next.js v9.4.4 has a minimum requirement for node.js is **v10.13 or later**. Upgrade you're node.js version and try again.

https://nextjs.org/docs/getting-started#system-requirements

**Comment by rohan-deshpande** [comment]
Okay yep sorry, that fixed it. Didn't realise the change in requirements. Thanks!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
