### ISSUE TITLE
Throws ERR_HTTP_HEADERS_SENT on the server in the fallback mode

### ISSUE THREAD

**Issue by arunoda** [vercel/next.js#13948]
# Bug report

## Describe the bug

* Has a static page with fallback mode enabled.
* When I trying to access a page which generated via the fallback
* Server is throwing a `ERR_HTTP_HEADERS_SENT`

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at DevServer.sendHTML (/Users/arunoda/data/arunoda/nextjs-issg-example/node_modules/next/dist/server/next-dev-server.js:23:5)
    at DevServer.render (/Users/arunoda/data/arunoda/nextjs-issg-example/node_modules/next/dist/next-server/server/next-server.js:49:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.fn (/Users/arunoda/data/arunoda/nextjs-issg-example/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/Users/arunoda/data/arunoda/nextjs-issg-example/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/Users/arunoda/data/arunoda/nextjs-issg-example/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/Users/arunoda/data/arunoda/nextjs-issg-example/node_modules/next/dist/next-server/server/next-server.js:13:133) {
  code: 'ERR_HTTP_HEADERS_SENT'
```

This only happens when we reload a page via the hard refresh.

I found this when I was wring a blog post about [Next.js Incremental  Static Regeneration](https://arunoda.me/blog/what-is-nextjs-issg) support.

## To Reproduce

* Clone this repo: https://github.com/arunoda/nextjs-issg-example
* Run with `yarn dev`
* Open the http://localhost:3000
* Click the first link titled "Sri Lanka"
* Check the server for the above error.

## Expected behavior

There should be no error on the server.

## Screenshots

-

## System information

- OS: MacOS
- Browser (if applies) Chrome.
- Version of Next.js: 9.4.4
- Version of Node.js: v12.14.1

## Additional context

-

**Comment by arunoda** [comment]
Oh! found the same error here: https://github.com/vercel/next.js/issues/13868
Will try the canary release now.

**Comment by arunoda** [comment]
Yep. it worked.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
