### ISSUE TITLE
SSG + CSR + dynamic pathing support

### ISSUE THREAD

**Issue by chaddjohnson** [vercel/next.js#13989]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be extremely useful to be able to statically generate and export a Next app while also having CSR functionality. For example, some apps have paths which don't need to be static generated such as `/products/783fdd81ca7da6845a0881ee716adc44` in an internal admin application. It's certainly possible to rebuild the app each time a new product is published, but this is impractical with tens of thousands of products, and a dynamic URL parameter would be preferable.

## Describe the solution you'd like

Something along the lines of `getStaticPaths` but for client-side only.

## Describe alternatives you've considered

Create React App, but no this does not come with SSG...and Next.js is so much better.

SSR, but this requires a server. Hosting purely on a CDN is ideal.

## Additional context

Here is [a prototype](https://github.com/chaddjohnson/next-static-csr) that uses both Next.js and React Router. Routes are defined in [_app.js](https://github.com/chaddjohnson/next-static-csr/blob/master/src/pages/_app.js) with `Component` as the default route. [This page](https://github.com/chaddjohnson/next-static-csr/blob/master/src/pages/products/%5Bslug%5D.js) can render given a dynamic URL parameter such as `/products/5695088daab72366267e348ebc125e01`. Here is [a hosted example](http://next-ssg-csr.s3-website-us-east-1.amazonaws.com/products/783fdd81ca7da6845a0881ee716adc44).

Note that Index Document and Error Document are set to `index.html` for the S3 bucket static website hosting settings. So when visiting `/products/783fdd81ca7da6845a0881ee716adc44`, it falls back to the root /index.html file which picks up routing on the client side.

It would be really, really great if there was built-in support for client-side only routes with statically-generated and exported Next apps hosted via CDN. I feel this is a big thing missing from Next.js.

**Comment by braveforest** [comment]
@chaddjohnson  I was facing the same issue and ur prototype just save my day. Thanks

**Comment by feychenie** [comment]
Hello @chaddjohnson and @braveforest, I have trouble understanding your exact issue using what nextJs already provides.

For SSG routes, you don't need to "rebuild the app each time a new product is published", the `fallback: true` param is there for that:
https://nextjs.org/docs/basic-features/data-fetching#the-fallback-key-required
You might also look into this:
https://nextjs.org/blog/next-9-4#incremental-static-regeneration-beta

And for pure CSR routes... well if you don't use getStaticProps or getServerProps and do everything in the lifecycle of the component, it is a pure CSR route then, no?

Does this answer the question? Is there something in your needs that I did not understand?

**Comment by chaddjohnson** [comment]
Please note I had a typo in my example and meant to use `slug` instead of `id`. This is fixed.

@feychenie Next.js does not provide CSR functionality out of the box for static site generation. When running `next build && next build` the following error occurs (see [here in this branch](https://github.com/chaddjohnson/next-ssg-csr/blob/no-react-router/src/pages/products/%5Bid%5D.js#L26)):

```
hyperion:next-static-csr chad$ yarn export
yarn run v1.21.1
warning ../package.json: No license field
$ NODE_ENV=production next build && next export
Creating an optimized production build  

Compiled successfully.

Automatically optimizing pages ...
Error occurred prerendering page "/products/[id]". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'match' of undefined

> Build error occurred
Error: Export encountered errors on following paths:
        /products/[id]
    at exportApp (/Users/chad/development/sandbox/next-static-csr/node_modules/next/dist/export/index.js:22:1166)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async build (/Users/chad/development/sandbox/next-static-csr/node_modules/next/dist/build/index.js:36:218)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And the [documentation](https://nextjs.org/docs/basic-features/data-fetching#fallback-true) says

    `fallback: true` is not supported when using `next export`.

This is despite doing everything in the lifecycle of the component (as in [the example](https://github.com/chaddjohnson/next-ssg-csr/blob/master/src/pages/products/%5Bslug%5D.js)).

The problem I am trying to solve is:

1. Host a site 100% statically on a CDN with no server.
1. `/products/[slug]` (e.g., `/products/some-cat-product`, `/products/some-dog-product`, `/products/any-dynamic-product-slug`, etc.) should be accessible while hosting the site statically without having to generate actual pages for every possible slug (`products/some-cat-product.html` should not have to be generated).

If I run `next build && next export`, a literal `products/[slug]/index.html` file is generated, and the dynamic paths noted in the steps above are inaccessible via CDN hosting. The only way to make them accessible is to add in React Router and set the CDN to fallback to `index.html` (the root `index.html`) whereby when `/products/some-slug` is visited, a 404 occurs, things fall back to `index.html`, and client-side React Router routing kicks in.

So, unless I am mistaken, Next.js does not provide an option for CSR with dynamic pathing for SSG out of the box. CSR definitely works, but not with dynamic pathing.

**Comment by feychenie** [comment]
Ok got it, I did not pay attention enough the "exported to CDN" part of your initial message, and you are right.

The issue with a static exported website is that URLs have to match actual file paths, and that there is no universal way to handle redirects on 404 among all available hosting providers, so this is something you would always have to implement on your own depending on where you host it.

I found an old discussion about this exact subject https://github.com/vercel/next.js/issues/2542

Not really related to this very subject, but the `Cannot read property 'match' of undefined` error you have in your build comes from the `useParams` hook of `react-router-dom`

**Comment by chaddjohnson** [comment]
@feychenie Thank you! No worries, I miss things too when reading sometimes. And thank you for the pointer on the error.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
