### ISSUE TITLE
NextJS build fails on specific error

### ISSUE THREAD

**Issue by episage** [vercel/next.js#14025]
# Bug report

## Describe the bug

I use `superstruct` pkg. It throws an error during schema validation using `assert`. NextJS tries to clone the error and it fails.

Offending method: `assert`

```
yarn build
```
```
(node:9443) UnhandledPromiseRejectionWarning: DataCloneError: function* failures() {
      yield failure;
      yield* iterable;
    } could not be cloned.
    at reportError (/Users/epi/projects/appoint.space/frontend4/packages/forms/node_modules/jest-worker/build/workers/threadChild.js:113:32)
    at reportClientError (/Users/epi/projects/appoint.space/frontend4/packages/forms/node_modules/jest-worker/build/workers/threadChild.js:97:10)
(node:9443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## To Reproduce

Minimal sample code:
```
const {  struct , assert } = require('superstruct');

const User = struct({
  id: 'number',
})

const data = {
  id: 'invalid',
}

assert(data, User) // this will fail in NextJS during yarn build
```

## Expected behavior

`yarn build` should build the project

## Screenshots

-

## System information

- OS: macOS Catlina
- Browser (if applies) N/A
- Version of Next.js: 9.4.4
- Version of Node.js: 12.16.0

## Additional context

-

**Comment by jamesmosier** [comment]
Wouldn't catching the error solve it via a `try/catch`? What would you expect Next to do in a situation an exception is thrown from a library?

**Comment by episage** [comment]
Right

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
