### ISSUE TITLE
installing `nextjs` behind a proxy takes a long time and prints errors in the console

### ISSUE THREAD

**Issue by portenez** [vercel/next.js#14070]
# Bug report

## Describe the bug

```gherkin
Given I am behind a proxy
When I install nextjs
Then it succeeds # this is ✅ good
And it prints an error to the console # ❌ this is bad, but npm succeeds
And it takes a long time to succeed # 🔶 
```

```
npm install nextjs

@ampproject/toolbox-optimizer@2.4.0 postinstall /home/suprauser/workspace/wss_wss_nextjs-demo_PR-39/node_modules/@ampproject/toolbox-optimizer

AMP Optimizer ERROR Could not fetch validator rules { FetchError: request to https://cdn.ampproject.org/v0/validator.json failed, reason: connect ETIMEDOUT 172.217.169.33:443
     at ClientRequest.<anonymous> (/home/suprauser/workspace/node_modules/node-fetch/lib/index.js:1455:11)
     at ClientRequest.emit (events.js:189:13)
     at TLSSocket.socketErrorListener (_http_client.js:392:9)
     at TLSSocket.emit (events.js:189:13)
     at emitErrorNT (internal/streams/destroy.js:82:8)
     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
     at process._tickCallback (internal/process/next_tick.js:63:19)

   message:
    'request to https://cdn.ampproject.org/v0/validator.json failed, reason: connect ETIMEDOUT 172.217.169.33:443',
   type: 'system',
   errno: 'ETIMEDOUT',
   code: 'ETIMEDOUT' }

```

## Expected behavior

```gherkin
Given I am behind a proxy
When I install nextjs
Then it succeeds 
And it prints no error to the console
And it completes withing a reasonable time 
```

## System information

- OS: mac
- Version of Next.js: 9.4.4
- Version of Node.js:  10.16.3

## Additional context

See issue with [@amp-project/toolbox](https://github.com/ampproject/amp-toolbox/issues/832)

**Comment by raphaelpc** [comment]
I can confirm that i'm having this same error on version 9.4.4 of Next.js (was previously using version 9.3.1 without any problems)!
I'm using lerna with yarn workspaces. To see the erros, i used "yarn install --verbose" instead of "lerna bootstrap".
In can this can help to find the origin of the problem, this is step 4 of yarn install with next 9.3.1:
 `
[4/4] Building fresh packages...
verbose 93.297113135 
verbose 94.341567674 
verbose 94.361146575 info looking for cached prebuild @ /home/jenkins/.cache-npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
info found cached prebuild 
info unpacking @ /home/jenkins/.cache-npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
info unpack resolved to /home/jenkins/root/workspace/ggov_siev_siev-frontend_develop/node_modules/iltorb/build/bindings/iltorb.node
info unpack required /home/jenkins/root/workspace/ggov_siev_siev-frontend_develop/node_modules/iltorb/build/bindings/iltorb.node successfully
info install Successfully installed iltorb binary!
verbose 94.386986667 
verbose 94.416262636 
Done in 94.76s.
`

And this is step 4 of yarn install with next 9.4.4:
`
[4/4] Building fresh packages...
verbose 118.221453879 
verbose 119.165985805 
verbose 119.695579788 
verbose 119.717008661 info looking for cached prebuild @ /home/jenkins/.cache-npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
info found cached prebuild 
info unpacking @ /home/jenkins/.cache-npm/_prebuilds/36154e-iltorb-v2.4.5-node-v72-linux-x64.tar.gz
info unpack resolved to /home/jenkins/root/workspace/ggov_siev_siev-frontend_develop/node_modules/iltorb/build/bindings/iltorb.node
info unpack required /home/jenkins/root/workspace/ggov_siev_siev-frontend_develop/node_modules/iltorb/build/bindings/iltorb.node successfully
info install Successfully installed iltorb binary!
verbose 119.745845807 
verbose 501.932993929 [7mAMP Optimizer[0m [31mERROR Could not fetch validator rules[0m FetchError: request to https://cdn.ampproject.org/v0/validator.json failed, reason: connect ETIMEDOUT 172.217.29.33:443
    at ClientRequest.<anonymous> (/home/jenkins/root/workspace/ggov_siev_siev-frontend_develop/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

[7mAMP Optimizer[0m [31mERROR Could not fetch AMP runtime CSS[0m FetchError: request to https://cdn.ampproject.org/rtv/undefined/v0.css failed, reason: connect ETIMEDOUT 172.217.29.33:443
    at ClientRequest.<anonymous> (/home/jenkins/root/workspace/ggov_siev_siev-frontend_develop/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

[7mAMP Optimizer AutoExtensionImporter[0m [31mERROR Missing validation rules, cannot auto import extensions[0m

[7mAMP Optimizer AmpBoilerplateTransformer[0m [31mERROR Missing parameters both ampRuntimeVersion and ampRuntimeStyles need to be present[0m

[7mAMP Optimizer[0m Downloading latest AMP runtime data
Done in 502.25s.
`

Thanks in advance!

**Comment by raphaelpc** [comment]
Note: i updated do Next version 9.4.0 and had no problems, so this is a problem from version 9.4.4.
Thanks.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
