### ISSUE TITLE
Cannot run "with-aws-amplify-typescript" example, receiving "TypeError: Cannot read property 'code' of undefined"

### ISSUE THREAD

**Issue by sakhmedbayev** [vercel/next.js#14440]
# Bug report

## Describe the bug

I am trying to run ["with-aws-amplify-typescript"](https://github.com/vercel/next.js/tree/canary/examples/with-aws-amplify-typescript) by following its instruction. 

on `yarn dev`, receiving the following error:

```
TypeError: Cannot read property 'code' of undefined
    at renderToHTML (/Users/username/myProject/node_modules/next/dist/next-server/server/render.js:29:8)
    at async /Users/username/myProject/node_modules/next/dist/next-server/server/next-server.js:68:285
    at async __wrapper (/Users/username/myProject/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/Users/username/myProject/node_modules/next/dist/next-server/server/next-server.js:91:254)
    at async DevServer.renderToHTML (/Users/username/myProject/node_modules/next/dist/next-server/server/next-server.js:92:254)
    at async DevServer.renderToHTML (/Users/username/myProject/node_modules/next/dist/server/next-dev-server.js:22:539)
    at async DevServer.render (/Users/username/myProject/node_modules/next/dist/next-server/server/next-server.js:48:236)
    at async Object.fn (/Users/username/myProject/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/Users/username/myProject/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/Users/username/myProject/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/Users/username/myProject/node_modules/next/dist/next-server/server/next-server.js:13:133)
^C⏎               
```

## System information

- OS: iOS
- Browser Chrome
- Version of Next.js: 9.4.4
- Version of Node.js: v14.2.0

@todortotev, can you please look at it?

**Comment by sakhmedbayev** [comment]
I think I found where the issue is. It is in the fact that I used AWS cognito as auth mode instead of API KEY one.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
