### ISSUE TITLE
Next.js 9.4 Absolute Imports Break Jest Tests

### ISSUE THREAD

**Issue by mulholio** [vercel/next.js#14443]
# Bug report

## Describe the bug

When using absolute imports (as announced [here](https://nextjs.org/blog/next-9-4#absolute-imports-and-aliases)), Jest tests break as absolute imports do not work in this env.

```
❯ yarn test
yarn run v1.22.4
warning package.json: No license field
$ jest
 FAIL  __tests__/Button.test.js
  ● Test suite failed to run

    Cannot find module 'components/Button' from 'Button.test.js'

      1 | import { render } from "@testing-library/react";
    > 2 | import Button from "components/Button";
        | ^
      3 | // The following import works but we would like to use the line above instead
      4 | // import Button from "../components/Button";
      5 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:299:11)
      at Object.<anonymous> (__tests__/Button.test.js:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.966s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

Reproduction repo here: https://github.com/mulholio/next-9-4-test-fail/blob/master/README.md

## Expected behavior

Imports behave the same in test and non-test environments.

## System information

- OS: MacOS
- Version of Next.js: 9.4.4
- Version of Node.js: 12.14.1

## Additional context

The app runs fine; it is only tests that are broken.

**Comment by mulholio** [comment]
Using Jest's `moduleDirectories` option fixed this for me https://github.com/mulholio/next-9-4-test-fail/commit/ac3e9284e071fef973bf5f51c984b0a3ec481749#diff-2d0cd5d10b9604941c38c6aac608178aR2

Hope this is useful to someone.

**Comment by webdevelukas** [comment]
@mulholio thanks for the hint. It would be useful if you could please share your solution/commit again. Would be great. :-)

**Comment by mulholio** [comment]
Here's my jest config:

```
module.exports = {
  moduleDirectories: ["node_modules", "."], // <-- Relevant line
  collectCoverageFrom: [
    "**/*.{js,jsx,ts,tsx}",
    "!**/*.d.ts",
    "!**/node_modules/**",
  ],
  setupFilesAfterEnv: ["<rootDir>/setupTests.js"],
  testPathIgnorePatterns: ["/node_modules/", "/.next/"],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/babel-jest",
    "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
  },
  transformIgnorePatterns: [
    "/node_modules/",
    "^.+\\.module\\.(css|sass|scss)$",
  ],
  moduleNameMapper: {
    "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy",
  },
};
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
