### ISSUE TITLE
CSS transform: translate3d fails to parse

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14632]
# Bug report

## Describe the bug

See upstream report: https://github.com/cssnano/cssnano/issues/920

```
Failed to compile.

TypeError: Cannot read property 'type' of undefined
    at /Users/joe/Documents/Development/Work/zeit/next.js/static/css/83f915061ddb4839a422.css:21:3
    at stringifyNode (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss-value-parser/lib/stringify.js:2:19)
    at stringify (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss-value-parser/lib/stringify.js:41:16)
    at stringifyNode (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss-value-parser/lib/stringify.js:19:11)
    at stringify (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss-value-parser/lib/stringify.js:41:16)
    at ValueParser.toString (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss-value-parser/lib/index.js:14:38)
    at /Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss-reduce-transforms/dist/index.js:213:82
    at /Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:198:18
    at /Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:131:17)
    at /Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:131:17)
    at Root.walkDecls (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss/lib/container.js:196:19)
    at /Users/joe/Documents/Development/Work/zeit/next.js/node_modules/postcss-reduce-transforms/dist/index.js:204:13
    at initializePlugin (/Users/joe/Documents/Development/Work/zeit/next.js/node_modules/cssnano/dist/index.js:31:51) {
  postcssNode: Declaration {
    raws: { before: '\n  ', between: ':' },
    type: 'decl',
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      parent: [Root],
      source: [Object],
      selector: '.transform-parsing',
      lastEach: 6,
      indexes: [Object]
    },
    source: { start: [Object], input: [Input], end: [Object] },
    prop: 'transform',
    value: 'translate3d(0px, 0px)'
  }
}
```

## To Reproduce

```css
.transform-parsing {
  transform: translate3d(0px, 0px);
}
```
## Expected behavior

Should compile successfully.

**Comment by Timer** [comment]
As reported by @pacocoursey! 🙏

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
