### ISSUE TITLE
Add special behavior for `next export` (auto export) running out of disk space

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14677]
Can we catch errors from the `next export` workers and add a special case for "No space left on device" that gives a friendlier error message about their build machine running out of disk space?

Right now, the console gets spammed with "No space left on device" messages.

**Comment by rhetoricalraj** [comment]
Can I pick up this? But I am new to this.

**Comment by Timer** [comment]
Sure!

**Comment by cascandaliato** [comment]
@Timer, how would the following output change with the new behavior?
```
$ npx next export
> using build directory: X:\foo\.next
  copying "static build" directory
> No "exportPathMap" found in "next.config.js". Generating map from "./pages"
  launching 7 workers
Exporting (0/2)
  copying "public" directory

Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
Error: ENOSPC: no space left on device, write
Exporting (1/2)

Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
Error: ENOSPC: no space left on device, write
Exporting (2/2)
Error: Export encountered errors on following paths:
        /
        /404
    at exportApp (X:\foo\node_modules\next\dist\export\index.js:24:1103)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by DanielCender** [comment]
Been looking for a good first issue, going to build off the changes introduced in #18226 and implement testing ideally in the next few days.
