### ISSUE TITLE
experimental optional catch all route not working 

### ISSUE THREAD

**Issue by BernardA** [vercel/next.js#14682]
# Bug report
It's a small ads app with an enormous amount of possible search routes ( 200 categories and about 20,000 cities), where the search page can have the following configuration:

`/search` => main search page
`/search/city/rootCategory/parentCategory`
`/search/city/rootCategory/parentCategory/category`

It would seem possible to have it work like below, using the 'regular' dynamic route, but it does not look neat:
`/search/0/0/0/0` => main search page
`/search/city/rootCategory/parentCategory/0`
`/search/city/rootCategory/parentCategory/category`

It throws a couple of errors:
1 - `pageProps` is INITIALLY passed empty to `_app.js` causing errors due to missing props
2 - `pageProps` is subsequently populated but then, on top of the error caused by the missing props, it throws error of headers already sent.

## Describe the bug
Initial output of `console.log` on `_app.js`:

    my app props {
    Component: [Function: Search] { propTypes: {} },
    router: ServerRouter {
    route: '/search/[[...query]]',
    pathname: '/search/[[...query]]',
    query: { query: [Array] },
    asPath: '/search/curitiba/produtos/ferramentas/mecanica',
    basePath: '',
    events: undefined,
    isFallback: true
    },
    __N_SSG: true,
     pageProps: {}
    }

And likewise on `/search/[[...query]]].js`

     search props {}

Then, it runs again, all by itself,  populating the props but throwing the following error on the terminal (while the browser shows the missing prop ( category ) error:

     Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at DevServer.sendHTML (/Users/bernardo/Sites/next-app/node_modules/next/dist/server/next-dev-server.js:23:5)
    at DevServer.render (/Users/bernardo/Sites/next-app/node_modules/next/dist/next-server/server/next-server.js:49:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/Users/bernardo/Sites/next-app/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/Users/bernardo/Sites/next-app/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/Users/bernardo/Sites/next-app/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/Users/bernardo/Sites/next-app/node_modules/next/dist/next-server/server/next-   server.js:13:133) {
    code: 'ERR_HTTP_HEADERS_SENT'
    }

## To Reproduce

`/pages/search/[[...query]].js`

      import axios from 'axios';
     import { useRouter } from 'next/router';
     import getCategories from '../../lib/getCategories';
     import getCities from '../../lib/getCities';
     import { urlWriter } from '../../tools/functions';

    const Search = (props) => {
    console.log('search props', props);

    const router = useRouter();
    if (router.isFallback) {
        return <div>Loading...</div>;
    }
    return <div>Search</div>;
    };

    export default Search;

     ... graphql query removed for brevity....

     export async function getStaticPaths() {
    let categories = await getCategories();
    let cities = await getCities();
    categories = categories.data.categories;
    cities = cities.data.collectionQueryAddresses;
    const paths = [];
    // main /search route
    paths.push({
        params: { query: ['0', '0', '0', '0'] },
    });
    cities.forEach((city) => {
        categories.forEach((cat) => {
            if (cat.root && cat.root.title === cat.parent.title) {
                paths.push({
                    params: {
                        query: [
                            urlWriter(city.city),
                            urlWriter(cat.root.title),
                            urlWriter(cat.title),
                            '0',
                        ],
                    },
                });
            }
            if (cat.root && cat.root.title !== cat.parent.title) {
                paths.push({
                    params: {
                        query: [
                            urlWriter(city.city),
                            urlWriter(cat.root.title),
                            urlWriter(cat.parent.title),
                            urlWriter(cat.title),
                        ],
                    },
                });
            }
        });
    });

    return {
        paths,
        fallback: true,
    };
    }

    export async function getStaticProps({ params }) {
    let categories = await getCategories();
    let cities = await getCities();
    categories = categories.data.categories;
    cities = cities.data.collectionQueryAddresses;
    console.log('params', params);
    let variables = {
        city: null,
        categoryParent: null,
        categoryId: null,
    };
    const { query } = params;
    console.log('query 00', query[0]);
    console.log('CITIES', cities);
    if (query.length > 0) {
        // get city as in data bank
        const city = cities.filter((c) => {
            return urlWriter(c.city) === query[0];
        })
        console.log('CITY', city[0].city);
        if (query[3] === '0') {
            const parentCategory = categories.filter((cat) => {
                return urlWriter(cat.title) === query[2];
            });
            variables = {
                city: city[0].city,
                categoryParent: parentCategory[0].id,
                categoryId: null,
            }
        } else {
            const category = categories.filter((cat) => {
                return cat.parent && urlWriter(cat.parent.title) === query[2] && 
                urlWriter(cat.title) === query[3];
            });
            variables = {
                city: city[0].city,
                categoryParent: null,
                categoryId: category[0].id,
            };
        }
    }
    console.log('VARIABLES', variables);
    const data = await apiQl(queryQl, variables);

    return {
        props: {
            ads: data.data.ads || [],
            categories,
            params,
        },
    };
    }

And on `/pages//_app.js`

     import withReduxSaga from 'next-redux-saga';
     import PropTypes from 'prop-types';
     import Head from 'next/head';
     import { ThemeProvider } from '@material-ui/core/styles';
     import CssBaseline from '@material-ui/core/CssBaseline';
     import wrapper from '../store/reduxWrapper';
     import theme from '../styles/theme';
     import styles from '../styles/layout.css';
     import 'react-quill/dist/quill.snow.css';
     import Layout from '../components/layout';

    function MyApp(props) {
    console.log('my app props', props);
    const { Component, pageProps } = props;
    React.useEffect(() => {
        const jssStyles = document.querySelector('#jss-server-side');
        if (jssStyles) {
            jssStyles.parentElement.removeChild(jssStyles);
        }
    }, []);

    return (
        <>
            <Head>
                <title>My page</title>
                <meta
                    name="viewport"
                    content="minimum-scale=1, initial-scale=1, width=device-width"
                />
            </Head>
            <ThemeProvider theme={theme}>
                <CssBaseline />
                <Layout categories={pageProps.categories}>
                    <Component {...pageProps} />
                </Layout>
            </ThemeProvider>
        </>
    );
    }

    MyApp.propTypes = {
     Component: PropTypes.elementType.isRequired,
     pageProps: PropTypes.object,
    };

     export default wrapper.withRedux(withReduxSaga((MyApp)));

## System information

- OS: macOS 
- Version of Next.js: 9.4.4
- Version of Node.js: 12.16.0

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
