### ISSUE TITLE
Namespace import is not defined during next build (likely webpack ModuleConcatenation error)

### ISSUE THREAD

**Issue by dvakatsiienko** [vercel/next.js#14800]
# Bug report

## Describe the bug

We use namespace approach to import `Material-UI` and other components across entire app like so:

```js
/* Core */
import * as mui from '@material-ui/core';

export const Progress: React.FC<ProgressProps> = props => {
    return <mui.LinearProgress { ...props } />;
};
Progress.defaultProps = {
    color: 'secondary',
};

/* Types */
type ProgressProps = mui.LinearProgressProps;

```

Recently a `next build` command started to produce the following output:

```sh
$ next build
info  - Loaded env from /Users/furthur/Projects/temy/react-marketplace/.env.production
info  - Loaded env from /Users/furthur/Projects/temy/react-marketplace/.env
info  - Using external babel configuration from /Users/furthur/Projects/temy/react-marketplace/babel.config.js
Creating an optimized production build

Compiled successfully.


> Build error occurred
ReferenceError: mui is not defined
    at Object.Nhdc (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:8181:65)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
    at Object.T0wj (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:12217:18)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
    at Object.a0Wt (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:13839:65)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
    at Object.woEc (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:15878:79)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
    at Object.V4Lr (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:12745:15)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
    at Object.Pw9j (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:10486:15)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
    at Module.hUgY (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:15282:13)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
    at Object.1 (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:7071:18)
    at __webpack_require__ (/Users/furthur/Projects/temy/react-marketplace/.next/server/pages/_app.js:29:31)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Entire application is stitched with this kind of imports, and the build output does not give any trails to look where.
**Important**: the issue appeared occasionally.

## To Reproduce

A not defined `mui` namespace variable is in build file: `.next/server/pages/_app.js:8181:65`

![Image 2020-07-02 at 7 02 50 PM](https://user-images.githubusercontent.com/15727958/86383585-d9001900-bc96-11ea-9a0d-c766d5c1e08e.png)

Here is the source file that contains the use of that namespace variable **along** with the **import** statement.
So the import is there.
So it is not a missed variable issue — the import is present there.

![Image 2020-07-02 at 7 03 27 PM](https://user-images.githubusercontent.com/15727958/86384000-faf99b80-bc96-11ea-9846-143620cde021.png)

Looks like that compiled `_app` file uses webpack's module concatenation feature but that drops that namespace module variable at some point.

## Expected behavior

Next.js build must handle all namespace imports and do not have to drop them randomly.

## System information

- OS: **macOS Catalina 10.15.5 (19F101)**
- Version of Next.js: **9.4.4**
- Version of Node.js: **12.18.1**

## Additional context

After ongoing testing I found that this happens to other vendor packages that imported as namespace **randomly.**
Yet I didn't found any pattern that causes this issue.

At some point in random file can produce `ReferenceError: formik | eva is not defined` error during **next build** process.

```js
import * as formik from 'formik';
```

```js
import * as eva from '@styled-icons/evaicons-solid';
```

Indeed issue is somehow related to module concatenation resolution process — at some point a namespace variable gets lost its connection to `__webpack_require__`-d in the scope of a `_app` built file.

**Comment by vladk96** [comment]
Agrees with @dvakatsiienko. We have noticed the same problem in our project.

**Comment by dvakatsiienko** [comment]
Update: today this happened again for `@styled-icons/evaicons-outline` package.

This import caused an error:

```js
import * as EvaOutline from '@styled-icons/evaicons-outline';
```js

This cases no error:
```js
import { OptionsOutline } from '@styled-icons/evaicons-outline';
```js

**Comment by osequi** [comment]
The same here:

```
s@cs-swift:~/osequi/osequi$ y build
yarn run v1.9.4
$ next build
(node:115498) ExperimentalWarning: The fs.promises API is experimental
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
ReferenceError: scales_scale is not defined
    at Object.FYhG (/home/cs/osequi/osequi/.next/server/pages/_app.js:5642:10)
    at __webpack_require__ (/home/cs/osequi/osequi/.next/server/pages/_app.js:23:31)
    at Object.Nhdc (/home/cs/osequi/osequi/.next/server/pages/_app.js:7790:14)
    at __webpack_require__ (/home/cs/osequi/osequi/.next/server/pages/_app.js:23:31)
    at Module.hUgY (/home/cs/osequi/osequi/.next/server/pages/_app.js:11456:69)
    at __webpack_require__ (/home/cs/osequi/osequi/.next/server/pages/_app.js:23:31)
    at Object.0 (/home/cs/osequi/osequi/.next/server/pages/_app.js:4662:18)
    at __webpack_require__ (/home/cs/osequi/osequi/.next/server/pages/_app.js:23:31)
    at /home/cs/osequi/osequi/.next/server/pages/_app.js:91:18
    at Object.<anonymous> (/home/cs/osequi/osequi/.next/server/pages/_app.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
cs@cs-swift:~/osequi/osequi$ 
```

**Comment by osequi** [comment]
The fix is also very strange / makes no sense:

```ts
// Before
import { TToken, TScale, scale, tokenPrivate } from "../..";

export const headingSizes: THeadingSizes = {
  values: [1, 2, 3, 4, 5, 6],
  scale: scale
};
```

```ts
// After
import { TToken, TScale, tokenPrivate } from "../..";

export const headingSizes: THeadingSizes = {
  values: [1, 2, 3, 4, 5, 6],
  /**
   * // NOTE When `scale` is imported from `scales` it gives a build error  
   */
  scale: {
    variant: "linear",
    value: 1,
  },
};
```

**Comment by timneutkens** [comment]
Please try using the webpack 5 support: https://nextjs.org/docs/messages/webpack5

**Comment by GiancarlosIO** [comment]
I have the same error 🤔 , I'm importing an enum from a ts-types npm library and it giving me the following error 😢 
````js
import type { CountryPrefix, MembershipTypeMethod } from '@my-org/ts-types';
console.log({ MembershipTypeMethod });

// nextjs server logs
event - compiled successfully
event - build page: /404
wait  - compiling...
event - compiled successfully
ReferenceError: MembershipTypeMethod is not defined
````

**Comment by JanKaifer** [comment]
This issue is quite old could someone check if it's still relevant in `next@canary`?

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
