### ISSUE TITLE
Confusing Next.js build output

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#15071]
# Bug report

## Describe the bug

```js
error - ./pages/_app.js:5:37
Syntax error: Unexpected token, expected ";"

  3 | 
  4 | export default function App({ Component, pageProps }) {
> 5 |   return <Component {...pageProps} />!;
    |                                      ^
  6 | }
  7 | 
Error: Syntax error: Unexpected token, expected ";"

  3 | 
  4 | export default function App({ Component, pageProps }) {
> 5 |   return <Component {...pageProps} />!;
    |                                      ^
  6 | }
  7 | 
    at getBabelError (/Users/joe/Documents/Blog/www/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseBabel.js:4:91)
    at getModuleBuildError (/Users/joe/Documents/Blog/www/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2469)
    at /Users/joe/Documents/Blog/www/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:549
    at Array.map (<anonymous>)
    at /Users/joe/Documents/Blog/www/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:478
    at SyncHook.eval [as call] (eval at create (/Users/joe/Documents/Blog/www/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/joe/Documents/Blog/www/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/joe/Documents/Blog/www/node_modules/webpack/lib/Compilation.js:1284:19)
    at /Users/joe/Documents/Blog/www/node_modules/webpack/lib/Compiler.js:675:18
    at /Users/joe/Documents/Blog/www/node_modules/webpack/lib/Compilation.js:1261:4
```

## To Reproduce

Introduce a syntax error and refresh the page.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
