### ISSUE TITLE
Fix new flaking test

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#15585]
## Failing test suites 
Commit: aa5d9f71b38da90b1597e571dd50703de69fa91b

**test/integration/error-is-clickable/test/index.test.js** 
- Clickable error link > Shows error which is clickable and redirects

<details>
<summary>Expand output</summary>

  ● Clickable error link › Shows error which is clickable and redirects

    JavascriptError: javascript error: Cannot read property 'click' of null
      (Session info: headless chrome=84.0.4147.89)

      22 |     const browser = await webdriver(appPort, '/first')
      23 | 
    > 24 |     await browser.eval(`(function () {
         |     ^
      25 |           document.querySelector("nextjs-portal")
      26 |           .shadowRoot
      27 |           .querySelector("#nextjs__container_errors_desc > a").click()

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:565:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:491:26)
      at thenableWebDriverProxy.execute (../node_modules/selenium-webdriver/lib/webdriver.js:700:17)
      at Object.<anonymous> (integration/error-is-clickable/test/index.test.js:24:5)

  ● Clickable error link › Shows error which is clickable and redirects

    thrown: "Exceeded timeout of 300000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      19 |   afterAll(() => killApp(app))
      20 | 
    > 21 |   it('Shows error which is clickable and redirects', async () => {
         |   ^
      22 |     const browser = await webdriver(appPort, '/first')
      23 | 
      24 |     await browser.eval(`(function () {

      at integration/error-is-clickable/test/index.test.js:21:3
      at Object.<anonymous> (integration/error-is-clickable/test/index.test.js:12:1)

</details>

_Originally posted by @ijjk in https://github.com/vercel/next.js/pull/14197#issuecomment-665085730_

**Comment by darshkpatel** [comment]
Just checked on my local machine on `canary`, the test seemed to fail initially but doing ` yarn && yarn dev` seemed to fix the test fixed the issue. 
The test should certainly not time out though.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
