### ISSUE TITLE
Dynamic imports in node_modules cause 500 in dev

### ISSUE THREAD

**Issue by ScriptedAlchemy** [vercel/next.js#15597]
# Bug report

## Describe the bug

When using `dynamic(()=>import('./somthing'))` in a npm package,like a component library.  I get a `500` error when in development mode. If I reload the previously crashed page again, it works accordingly. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1) Create an npm package that dynamically imports something
2) sync import that component out of the npm package, in dev mode - the server will 500

```js
/* eslint-disable import/no-cycle */
import dynamic from 'next/dynamic';
import { mapFieldsToProps as CTABlockMapFieldsToProps } from '../components/beta/cta-block';

const CTABlock = dynamic(() => import('../components/beta/cta-block'));
CTABlock.mapFieldsToProps = CTABlockMapFieldsToProps;
CTABlock.componentName = 'CTABlock';

const GridContainer = dynamic(() =>
  import('../components/beta/grid-container')
);
GridContainer.componentName = 'GridContainer';

const contentfulContentModelMap = {
  samPlaygroundCtaBlock: CTABlock,
  container: GridContainer,
};

export default contentfulContentModelMap;

```

elsewhere
```js
import contentfulContentModelMap from '@company/repo/content-models.js
```

## Expected behavior

Next should render without issue

## System information

Mac OS
Next 9.5
Webpack 4 and Webpack 5 both suffer from this issue

## Additional context

The issue looks similar to issues we ran into with my initial PR for webpack 5, code attempts to render before its actually been emitted. 

When debugging `Loadable` internally inside of next - it received a rejected promise immediately. 

```sh
Error: Not supported
    at /Users/zjackson/wae-coco/node_modules/@company/ecom-pattern-library/lib/utils/content-models.js:21:3
    at LoadableSubscription.load [as _loadFn] (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/lib/loadable.js:22:111)
    at LoadableSubscription.retry (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/lib/loadable.js:24:1303)
    at new LoadableSubscription (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/lib/loadable.js:24:1213)
    at init (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/lib/loadable.js:22:1262)
    at flushInitializers (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/lib/loadable.js:24:2630)
    at /Users/zjackson/wae-coco/node_modules/next/dist/next-server/lib/loadable.js:24:2828
    at new WrappedPromise (/Users/zjackson/wae-coco/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at Function.Loadable.preloadAll (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/lib/loadable.js:24:2785)
    at renderToHTML (/Users/zjackson/wae-coco/node_modules/next/dist/next-server/server/render.js:20:324)
event - build page: /_error
```
And the client side error
![image](https://user-images.githubusercontent.com/25274700/88725204-99cfb700-d0e0-11ea-9345-c746136d869e.png)

**Comment by timneutkens** [comment]
Please add a complete repository so that we can have a look.

**Comment by ScriptedAlchemy** [comment]
Reproducible Repo 

https://github.com/ScriptedAlchemy/sample-next-9-5

Async package

https://github.com/ScriptedAlchemy/sample-async-package

When booting in dev mode, it will 500, refreshing the page will create a successful render. This is using stock standard create-next-app and webpack 4

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
