### ISSUE TITLE
The `redirect` function allows to avoid a parameter for the `Location`

### ISSUE THREAD

**Issue by AndyBitz** [vercel/next.js#15594]
# Bug report

## Describe the bug
The [`redirect` function](https://github.com/vercel/next.js/blob/d19c34353da47cca5044e3726e900a978dcf0309/packages/next/next-server/server/api-utils.ts#L222-L240) added in https://github.com/vercel/next.js/pull/14705 allows to set a status code or URL as second argument, and an optional third argument for the URL if the second argument was used for the status code.

However, the function signature allows setting a status code without providing a URL. In those cases the `Location` header would be set to `undefined`, which throws an error.

## To Reproduce

- Create a Next.js project with TypeScript
- Create `pages/api/index.ts` with this content:
```typescript
import { NextApiRequest, NextApiResponse } from 'next';
export default (req: NextApiRequest, res: NextApiResponse) => res.redirect(307);
```

- Run `next dev` and execute `curl localhost:300/api`
- 500 Status code is returned and error is logged

```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Location"
    at ServerResponse.setHeader (_http_outgoing.js:521:3)
    at setHeadersFromObject (/private/tmp/nextjs/node_modules/next/dist/compiled/compression/index.js:1:145242)
    at ServerResponse.setWriteHeadHeaders (/private/tmp/nextjs/node_modules/next/dist/compiled/compression/index.js:1:145476)
    at ServerResponse.writeHead (/private/tmp/nextjs/node_modules/next/dist/compiled/compression/index.js:1:144683)
    at redirect (/private/tmp/nextjs/node_modules/next/dist/next-server/server/api-utils.js:32:114)
    at ServerResponse.apiRes.redirect (/private/tmp/nextjs/node_modules/next/dist/next-server/server/api-utils.js:6:340)
    at __webpack_exports__.default (webpack-internal:///./pages/api/index.js:2:82)
    at apiResolver (/private/tmp/nextjs/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

## Expected behavior

TypeScript should have caught the error upfront.

Personally I think it'd make more sense to have a signature like this:
```typescript
function redirect(url: string, status: number = 307);
```
so that no matter what, the `Location` will always be set and won't depend on the type. But this might be impossible to change now. I'm not sure if it'd make sense to throw a custom error if the URL parameter was forgotten.

Maybe it'd also be enough to rely on the number of arguments instead of their type.

## System information

- OS: macOS
- Version of Next.js: 9.5.0
- Version of Node.js: v12.18.3

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
