### ISSUE TITLE
Crashes deploying to Vercel using Next.js 9.5.0/9.5.1

### ISSUE THREAD

**Issue by jknight12882** [vercel/next.js#15713]
# Bug report

## Describe the bug

Getting the following crash deploying to Vercel using Next.js 9.5.0 and 9.5.1. This works as expected using Next.js 9.4.4. Also, 9.5.0 and 9.5.1 work fine locally. 
```
12:06:01.769 | TypeError: Cannot read property 'filter' of undefined
-- | --
12:06:01.769 | at NextScript.getPolyfillScripts (/vercel/5c3be1a5/packages/sh-www/.next/serverless/pages/_error.js:649:26)
12:06:01.769 | at NextScript.render (/vercel/5c3be1a5/packages/sh-www/.next/serverless/pages/_error.js:750:75)
12:06:01.769 | at d (/vercel/5c3be1a5/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
12:06:01.769 | at $a (/vercel/5c3be1a5/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
12:06:01.769 | at a.b.render (/vercel/5c3be1a5/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
12:06:01.770 | at a.b.read (/vercel/5c3be1a5/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
12:06:01.770 | at renderToStaticMarkup (/vercel/5c3be1a5/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:462)
12:06:01.770 | at renderDocument (/vercel/5c3be1a5/node_modules/next/dist/next-server/server/render.js:3:594)
12:06:01.770 | at renderToHTML (/vercel/5c3be1a5/node_modules/next/dist/next-server/server/render.js:47:72)
12:06:01.770 | at async renderReqToHTML (/vercel/5c3be1a5/packages/sh-www/.next/serverless/pages/_error.js:2188:22)
12:06:01.771 | Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
```

## To Reproduce

Deploy to Vercel using Next.js 9.5.0 or 9.5.1

## Expected behavior

Deploy succeeds

**Comment by ijjk** [comment]
Hi, can you provide additional details/a link to a repo with a reproduction where this is occurring so we can investigate? We have tests running against the latest version of Next.js on Vercel and aren't seeing any deploy failures currently.

**Comment by jknight12882** [comment]
Yup, here you gohttps://github.com/jknight12882/vercel-crash-demo

**Comment by ijjk** [comment]
Thanks for the reproduction it appears this is an edge case with how `next build` is being executed on Vercel which was changed recently, I opened a PR [here](https://github.com/vercel/vercel/pull/4956) to correct this.

**Comment by ijjk** [comment]
The [above fix](https://github.com/vercel/vercel/pull/4956) has now been shipped and is available in the latest `@vercel/next`

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
