### ISSUE TITLE
react-intl not working in WITH-REACT-INTL-APP example

### ISSUE THREAD

**Issue by nguyenvannghi** [vercel/next.js#15725]
# Bug report

Hi guys, When I run ` WITH-REACT-INTL-APP` and had issue:

`$ node  server.js
(node:25154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'concat' of undefined
    at Object.webpack (/home/nghinv/work/with-react-intl-app/node_modules/next-transpile-modules/src/next-transpile-modules.js:102:73)
    at getBaseWebpackConfig (/home/nghinv/work/with-react-intl-app/node_modules/next/dist/build/webpack-config.js:117:489)
    at async Promise.all (index 0)
    at async HotReloader.start (/home/nghinv/work/with-react-intl-app/node_modules/next/dist/server/hot-reloader.js:14:2171)
    at async DevServer.prepare (/home/nghinv/work/with-react-intl-app/node_modules/next/dist/server/next-dev-server.js:11:378)
(node:25154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Please help me! Thanks all guys!

**Comment by jonespen** [comment]
Seems like the latest Next.js release broke something in next-transpile-modules (https://github.com/martpie/next-transpile-modules/issues/88), I'll have a look.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
