### ISSUE TITLE
TypeError: document.querySelector is not a function on production build

### ISSUE THREAD

**Issue by dcsan** [vercel/next.js#15883]
# Bug report
I can run a dev server, but whenever doing a production build I'll get the error:

`TypeError: document.querySelector is not a function`

## To Reproduce

➜  client git:(380-schemas) npm run build

```
> @considr-it/inq-client@2.0.0 build /Users/dc/dev/inq/inQ/client
> next build

info  - Loaded env from .env.production.local
info  - Loaded env from .env.local
info  - Loaded env from .env
Creating an optimized production build

Compiled successfully.


> Build error occurred
TypeError: document.querySelector is not a function
    at new StyleSheet (/Users/dc/dev/inq/inQ/client/node_modules/styled-jsx/dist/lib/stylesheet.js:42:44)
    at new StyleSheetRegistry (/Users/dc/dev/inq/inQ/client/node_modules/styled-jsx/dist/stylesheet-registry.js:28:33)
    at Object.<anonymous> (/Users/dc/dev/inq/inQ/client/node_modules/styled-jsx/dist/style.js:15:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/dc/dev/inq/inQ/client/node_modules/styled-jsx/style.js:1:18) {
  type: 'TypeError'
}
Automatically optimizing pages .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @considr-it/inq-client@2.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @considr-it/inq-client@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dc/.npm/_logs/2020-08-04T21_56_46_991Z-debug.log
➜  client git:(380-schemas) node -v
v12.18.0
```

a dev build works fine
```
➜  client git:(380-schemas) ✗ npm run dev

> @considr-it/inq-client@2.0.0 dev /Users/dc/dev/inq/inQ/client
> next dev -p 4001

ready - started server on http://localhost:4001
info  - Loaded env from /Users/dc/dev/inq/inQ/client/.env.local
info  - Loaded env from /Users/dc/dev/inq/inQ/client/.env
event - compiled successfully
```

## Expected behavior
can build

## System information
building on mac, latest darwin

➜  client git:(380-schemas) ✗ npx next -v
Next.js v9.5.1
➜  client git:(380-schemas) ✗ node -v
v12.18.0

**Comment by jamesmosier** [comment]
Hi @dcsan. Do you have a repository you could share to help reproduce this?

**Comment by dcsan** [comment]
thanks for the response. unfortunately it's not a public repo. 

Is there anything else I could provide? any ideas what might be the source of `querySelector` issues? 
what main differences are there with production and dev builds? perhaps its SSR stuff?
is there a way to disable the SSR, since we're not really using it.

We do have one slightly tricky thing as a shared repo for typescript types, but this is working fine with the dev server:

```
  "dependencies": {
    "@considr-it/inq-server": "file:/../server",
```

package.json

```
{
  "name": "@considr-it/inq-client",
  "version": "2.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 4001",
    "build": "next build",
    "start": "next start -p 8080",
    "gcp-build": "npm run build",
    "gcp-deploy": "gcloud app deploy --project inq-clientnext-dev2 -q"
  },
  "dependencies": {
    "@considr-it/inq-server": "file:/../server",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "@types/node": "^14.0.27",
    "@types/react": "^16.9.43",
    "axios": "^0.19.2",
    "file-saver": "^2.0.2",
    "framer-motion": "^2.3.0",
    "msr": "^1.3.4",
    "next": "^9.5.1",
    "next-connect": "^0.8.1",
    "next-iron-session": "^4.1.7",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-easy-emoji": "^1.4.0",
    "react-google-login": "^5.1.21",
    "react-multi-carousel": "^2.5.5",
    "react-spring": "^9.0.0-rc.3",
    "react-spring-modal": "^1.0.8",
    "react-styled-carousel": "^0.5.1",
    "socket.io-client": "^2.3.0",
    "socket.io-stream": "^0.9.1",
    "swr": "^0.3.0",
    "typescript": "^3.9.7",
    "use-timer": "^1.3.0"
  },
  "devDependencies": {
    "@types/socket.io-client": "^1.4.33"
  }
}
```

**Comment by jamesmosier** [comment]
Could you create a new repository with a minimal example that shows this being an issue? It doesn't **have** to be your exact repo if the problem is reproducible. Maybe try to migrate page by page over to a new project and see if/when the issue presents itself.

You can disabled SSR on a component by component basis using [dynamic imports](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr)

**Comment by dcsan** [comment]
the problem is 100% reproducible for us, different team members in different locations get it.

ripping apart and rebuilding the project would be a lot of work though...

any other ideas where we could look? I think this just started happening recently.

what else is different between prod and dev builds?

**Comment by Timer** [comment]
Closing as no reproduction provided and it's been a month with no activity!

**Comment by dvalle-nearsoft** [comment]
Found a way to reproduce this, just use `target: 'serverless'` when building this theme: https://github.com/creativetimofficial/ct-nextjs-material-dashboard-pro

Issue reported on https://github.com/creativetimofficial/ct-nextjs-material-dashboard-pro/issues/2

**Comment by labedal** [comment]
I had the problem with another project. My way to solve this was:

_app.tsx -> add following after your imports:

`if (typeof document === 'undefined') {
  // @ts-ignore
  global.document = {
    querySelector: function () {},
  };
}`

**Comment by thanh90** [comment]
> I had the problem with another project. My way to solve this was:
> 
> _app.tsx -> add following after your imports:
> 
> `if (typeof document === 'undefined') { // @ts-ignore global.document = { querySelector: function () {}, }; }`

thank bro, that fixed my problem when using window.navigator

**Comment by Shpota** [comment]
@jamesmosier @Timer the issue probably has something to do with the environment the build is running on. I have it locally, but it is not reproducible in CI with exactly the same code base and exactly the same commands. At the same time, none of my attempts to solve it helped.

**Comment by mnfgul** [comment]
I am getting this error while deploying my app on Versel. On local, build works fine. What might cause this?

```
00:26:11 | > Build error occurred
-- | --
00:26:11 | TypeError: document.querySelector is not a function
00:26:11 | at new StyleSheet (/vercel/workpath0/node_modules/styled-jsx/dist/lib/stylesheet.js:40:44)
00:26:11 | at new StyleSheetRegistry (/vercel/workpath0/node_modules/styled-jsx/dist/stylesheet-registry.js:26:33)
00:26:11 | at Object.<anonymous> (/vercel/workpath0/node_modules/styled-jsx/dist/style.js:15:26)
00:26:11 | at Module._compile (internal/modules/cjs/loader.js:1063:30)
00:26:11 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
00:26:11 | at Module.load (internal/modules/cjs/loader.js:928:32)
00:26:11 | at Function.Module._load (internal/modules/cjs/loader.js:769:14)
00:26:11 | at Module.require (internal/modules/cjs/loader.js:952:19)
00:26:11 | at require (internal/modules/cjs/helpers.js:88:18)
00:26:11 | at Object.<anonymous> (/vercel/workpath0/node_modules/styled-jsx/dist/server.js:9:14) {
00:26:11 | type: 'TypeError'
00:26:11 | }

```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
