### ISSUE TITLE
Bump terser to 5.0.0

### ISSUE THREAD

**Issue by JakubKoralewski** [vercel/next.js#16000]
# Feature request

Terser is currently `4.4.2`, it should be at `5.0.0`.

## Is your feature request related to a problem? Please describe.

For a few days I've been hopelessly struggling with terser not minifying a `const` object created by `babel-plugin-const-enum`. I tried to stupidly fix `babel-plugin-const-enum`, but it turns out the issue is resolved by just updating terser to `5.0.0`.

## Describe the solution you'd like

Bump to 5.0.0.

## Additional context

I ran the same options with both `4.4.2` and `5.0.0` and the size seems the same (to clarify: the default options - unaltered by the changes shown below). Just checked the hash of both files is the same.
I got the options by hooking into webpack config inside `next.config.js` in the `webpack` function as follows:
```js
const terserPlugin = config.optimization.minimizer.find(x => Boolean(x.options.terserOptions));
if(terserPlugin) {
  // Modify config here, for example:
  terserPlugin.options.terserOptions.compress.unsafe = true;
  console.log('terser plugin: ', JSON.stringify(terserPlugin));
}
```
I need the above change for my object to get minified.
<details><summary>
This may be unrelated:
</summary>

Also by hooking into the `/dist/compiled/terser-webpack-plugin/worker.js` I `console.log`ged the `options.terserOptions`, and run this config both in  `5.0.0` `terser` version as well as `4.4.2`, and looks like the `sourceMap` property is being set to `null` for some reason:
https://github.com/vercel/next.js/blob/60f1d58c837ac604ce8fa475bf592457119f82cc/packages/next/compiled/terser-webpack-plugin/minify.js#L38
This throws an error in both `5.0.0` and `4.4.2`:
```
        if (options.sourceMap.url !== "inline" && result.map) {
                              ^
TypeError: Cannot read property 'url' of null
    at run (C:\Users\Admin\AppData\Roaming\npm\node_modules\terser\bin\terser:297:31)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\terser\bin\terser:175:5)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
I don't know how this is handled exactly.
</details>

**Comment by timneutkens** [comment]
Looks like this just needs an upgrade of terser-webpack-plugin: https://github.com/webpack-contrib/terser-webpack-plugin/commits/master

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
