### ISSUE TITLE
9.5.2 + Webpack 5 fails to build

### ISSUE THREAD

**Issue by anmonteiro** [vercel/next.js#16061]
# Bug report

## Describe the bug

Running `next build` in a project with a Webpack 5 beta resolution fails to build with the following error. It doesn't happen in 9.5.1, or if I remove the resolution (thus defaulting to Webpack 4)

```
Failed to compile.

TypeError: Cannot read property 'startsWith' of undefined


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/home/anmonteiro/projects/my_project/node_modules/next/dist/build/index.js:15:918)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## System information

- OS: Linux
- Version of Next.js: 9.5.2
- Version of Node.js: 14.7.0

**Comment by anmonteiro** [comment]
Disregard, this seems to be a problem with next-transpile-modules.

**Comment by nnennajohn** [comment]
How were you able to track down this problem. It shows up for me. But not really sure why, as I don't have next transpile modules. 

<img width="1372" alt="Screen Shot 2021-01-16 at 7 05 02 AM" src="https://user-images.githubusercontent.com/1761197/104815415-486bcf00-57c9-11eb-9d2f-e60ca835fa52.png">

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
