### ISSUE TITLE
Error when dependabot bumps to next-9.5.2

### ISSUE THREAD

**Issue by nblthree** [vercel/next.js#16087]
# Bug report

```
Running "yarn run build"
--
17:30:32.843 | yarn run v1.22.4
17:30:32.856 | warning package.json: No license field
17:30:32.866 | $ next build
17:30:33.453 | info  - Loaded env from /vercel/372b6b00/.env
17:30:33.455 | info  - Creating an optimized production build...
17:30:42.814 | > Build error occurred
17:30:42.816 | ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
17:30:42.816 | - configuration.optimization has an unknown property 'emitOnErrors'. These properties are valid:
17:30:42.816 | object { checkWasmTypes?, chunkIds?, concatenateModules?, flagIncludedChunks?, innerGraph?, mangleExports?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, noEmitOnErrors?, nodeEnv?, portableRecords?, providedExports?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
17:30:42.816 | -> Enables/Disables integrated optimizations.
17:30:42.817 | at validate (/vercel/372b6b00/node_modules/schema-utils/dist/validate.js:96:11)
17:30:42.817 | at validateSchema (/vercel/372b6b00/node_modules/webpack/lib/validateSchema.js:38:2)
17:30:42.817 | at webpack (/vercel/372b6b00/node_modules/webpack/lib/webpack.js:100:2)
17:30:42.817 | at f (/vercel/372b6b00/node_modules/webpack/lib/index.js:31:15)
17:30:42.817 | at /vercel/372b6b00/node_modules/next/dist/build/compiler.js:4:172
17:30:42.817 | at new Promise (<anonymous>)
17:30:42.817 | at runCompiler (/vercel/372b6b00/node_modules/next/dist/build/compiler.js:4:106)
17:30:42.817 | at build (/vercel/372b6b00/node_modules/next/dist/build/index.js:12:71) {
17:30:42.817 | name: 'ValidationError',
17:30:42.817 | errors: [
17:30:42.817 | {
17:30:42.817 | keyword: 'additionalProperties',
17:30:42.817 | dataPath: '.optimization',
17:30:42.817 | schemaPath: '#/additionalProperties',
17:30:42.817 | params: [Object],
17:30:42.817 | message: 'should NOT have additional properties',
17:30:42.817 | schema: false,
17:30:42.817 | parentSchema: [Object],
17:30:42.817 | data: [Object]
17:30:42.817 | }
17:30:42.817 | ],
17:30:42.817 | schema: {
17:30:42.817 | definitions: {
17:30:42.817 | Amd: [Object],
17:30:42.817 | AssetModuleFilename: [Object],
17:30:42.817 | AuxiliaryComment: [Object],
17:30:42.817 | Bail: [Object],
17:30:42.817 | CacheOptions: [Object],
17:30:42.817 | CacheOptionsNormalized: [Object],
17:30:42.817 | ChunkCallbackName: [Object],
17:30:42.817 | ChunkFilename: [Object],
17:30:42.817 | ChunkLoadTimeout: [Object],
17:30:42.818 | CompareBeforeEmit: [Object],
17:30:42.818 | Context: [Object],
17:30:42.818 | CrossOriginLoading: [Object],
17:30:42.818 | Dependencies: [Object],
17:30:42.818 | DevServer: [Object],
17:30:42.818 | DevTool: [Object],
17:30:42.818 | DevtoolFallbackModuleFilenameTemplate: [Object],
17:30:42.818 | DevtoolModuleFilenameTemplate: [Object],
17:30:42.818 | DevtoolNamespace: [Object],
17:30:42.818 | EcmaVersion: [Object],
17:30:42.818 | EnabledLibraryTypes: [Object],
17:30:42.818 | Entry: [Object],
17:30:42.818 | EntryDescription: [Object],
17:30:42.818 | EntryDescriptionNormalized: [Object],
17:30:42.818 | EntryDynamic: [Object],
17:30:42.818 | EntryDynamicNormalized: [Object],
17:30:42.818 | EntryItem: [Object],
17:30:42.818 | EntryNormalized: [Object],
17:30:42.818 | EntryObject: [Object],
17:30:42.818 | EntryStatic: [Object],
17:30:42.818 | EntryStaticNormalized: [Object],
17:30:42.818 | EntryUnnamed: [Object],
17:30:42.818 | Experiments: [Object],
17:30:42.818 | ExternalItem: [Object],
17:30:42.818 | Externals: [Object],
17:30:42.818 | ExternalsType: [Object],
17:30:42.818 | FileCacheOptions: [Object],
17:30:42.818 | Filename: [Object],
17:30:42.818 | FilterItemTypes: [Object],
17:30:42.818 | FilterTypes: [Object],
17:30:42.818 | GlobalObject: [Object],
17:30:42.818 | HashDigest: [Object],
17:30:42.818 | HashDigestLength: [Object],
17:30:42.818 | HashFunction: [Object],
17:30:42.818 | HashSalt: [Object],
17:30:42.818 | HotUpdateChunkFilename: [Object],
17:30:42.818 | HotUpdateFunction: [Object],
17:30:42.818 | HotUpdateMainFilename: [Object],
17:30:42.818 | Iife: [Object],
17:30:42.818 | ImportFunctionName: [Object],
17:30:42.819 | InfrastructureLogging: [Object],
17:30:42.819 | JsonpFunction: [Object],
17:30:42.819 | Library: [Object],
17:30:42.819 | LibraryCustomUmdCommentObject: [Object],
17:30:42.819 | LibraryCustomUmdObject: [Object],
17:30:42.819 | LibraryExport: [Object],
17:30:42.819 | LibraryName: [Object],
17:30:42.819 | LibraryOptions: [Object],
17:30:42.819 | LibraryType: [Object],
17:30:42.819 | Loader: [Object],
17:30:42.819 | MemoryCacheOptions: [Object],
17:30:42.819 | Mode: [Object],
17:30:42.819 | ModuleOptions: [Object],
17:30:42.819 | Name: [Object],
17:30:42.819 | Node: [Object],
17:30:42.819 | NodeOptions: [Object],
17:30:42.819 | Optimization: [Object],
17:30:42.819 | OptimizationRuntimeChunk: [Object],
17:30:42.819 | OptimizationRuntimeChunkNormalized: [Object],
17:30:42.819 | OptimizationSplitChunksCacheGroup: [Object],
17:30:42.819 | OptimizationSplitChunksGetCacheGroups: [Object],
17:30:42.819 | OptimizationSplitChunksOptions: [Object],
17:30:42.819 | OptimizationSplitChunksSizes: [Object],
17:30:42.819 | Output: [Object],
17:30:42.819 | OutputModule: [Object],
17:30:42.819 | OutputNormalized: [Object],
17:30:42.819 | Parallelism: [Object],
17:30:42.819 | Path: [Object],
17:30:42.819 | Pathinfo: [Object],
17:30:42.819 | Performance: [Object],
17:30:42.819 | PerformanceOptions: [Object],
17:30:42.819 | Plugins: [Object],
17:30:42.819 | Profile: [Object],
17:30:42.819 | PublicPath: [Object],
17:30:42.819 | RecordsInputPath: [Object],
17:30:42.819 | RecordsOutputPath: [Object],
17:30:42.819 | RecordsPath: [Object],
17:30:42.819 | Resolve: [Object],
17:30:42.819 | ResolveLoader: [Object],
17:30:42.820 | ResolveOptions: [Object],
17:30:42.820 | ResolvePluginInstance: [Object],
17:30:42.820 | RuleSetCondition: [Object],
17:30:42.820 | RuleSetConditionAbsolute: [Object],
17:30:42.820 | RuleSetConditionOrConditions: [Object],
17:30:42.820 | RuleSetConditionOrConditionsAbsolute: [Object],
17:30:42.820 | RuleSetConditions: [Object],
17:30:42.820 | RuleSetConditionsAbsolute: [Object],
17:30:42.820 | RuleSetLoader: [Object],
17:30:42.820 | RuleSetLoaderOptions: [Object],
17:30:42.820 | RuleSetRule: [Object],
17:30:42.820 | RuleSetRules: [Object],
17:30:42.820 | RuleSetUse: [Object],
17:30:42.820 | RuleSetUseItem: [Object],
17:30:42.820 | ScriptType: [Object],
17:30:42.820 | SourceMapFilename: [Object],
17:30:42.820 | SourcePrefix: [Object],
17:30:42.820 | StatsOptions: [Object],
17:30:42.820 | StatsValue: [Object],
17:30:42.820 | StrictModuleExceptionHandling: [Object],
17:30:42.820 | Target: [Object],
17:30:42.820 | UmdNamedDefine: [Object],
17:30:42.820 | UniqueName: [Object],
17:30:42.820 | Watch: [Object],
17:30:42.820 | WatchOptions: [Object],
17:30:42.820 | WebassemblyModuleFilename: [Object],
17:30:42.820 | WebpackOptionsNormalized: [Object],
17:30:42.820 | WebpackPluginFunction: [Object],
17:30:42.820 | WebpackPluginInstance: [Object]
17:30:42.820 | },
17:30:42.820 | description: 'Options object as provided by the user.',
17:30:42.820 | type: 'object',
17:30:42.820 | additionalProperties: false,
17:30:42.820 | properties: {
17:30:42.820 | amd: [Object],
17:30:42.820 | bail: [Object],
17:30:42.822 | cache: [Object],
17:30:42.822 | context: [Object],
17:30:42.822 | dependencies: [Object],
17:30:42.822 | devServer: [Object],
17:30:42.822 | devtool: [Object],
17:30:42.822 | entry: [Object],
17:30:42.822 | experiments: [Object],
17:30:42.822 | externals: [Object],
17:30:42.822 | externalsType: [Object],
17:30:42.822 | infrastructureLogging: [Object],
17:30:42.822 | loader: [Object],
17:30:42.822 | mode: [Object],
17:30:42.822 | module: [Object],
17:30:42.822 | name: [Object],
17:30:42.822 | node: [Object],
17:30:42.822 | optimization: [Object],
17:30:42.822 | output: [Object],
17:30:42.822 | parallelism: [Object],
17:30:42.822 | performance: [Object],
17:30:42.822 | plugins: [Object],
17:30:42.822 | profile: [Object],
17:30:42.822 | recordsInputPath: [Object],
17:30:42.822 | recordsOutputPath: [Object],
17:30:42.823 | recordsPath: [Object],
17:30:42.823 | resolve: [Object],
17:30:42.823 | resolveLoader: [Object],
17:30:42.823 | stats: [Object],
17:30:42.823 | target: [Object],
17:30:42.823 | watch: [Object],
17:30:42.823 | watchOptions: [Object]
17:30:42.823 | }
17:30:42.823 | },
17:30:42.823 | headerName: 'Webpack',
17:30:42.823 | baseDataPath: 'configuration',
17:30:42.823 | postFormatter: [Function: postFormatter],
17:30:42.823 | message: 'Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.\n' +
17:30:42.823 | " - configuration.optimization has an unknown property 'emitOnErrors'. These properties are valid:\n" +
17:30:42.823 | '   object { checkWasmTypes?, chunkIds?, concatenateModules?, flagIncludedChunks?, innerGraph?, mangleExports?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, noEmitOnErrors?, nodeEnv?, portableRecords?, providedExports?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }\n' +
17:30:42.823 | '   -> Enables/Disables integrated optimizations.'
17:30:42.823 | }
17:30:42.841 | error Command failed with exit code 1.
```

## Describe the bug

build fail

## To Reproduce

Unknown

## Expected behavior

Build succeed

## System information

Vercel

## Additional context

Nothing

**Comment by Timer** [comment]
Sounds like you're using the experimental webpack 5 beta and are on too old of a webpack 5 version. Please upgrade.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
