### ISSUE TITLE
Link without href throws error

### ISSUE THREAD

**Issue by todortotev** [vercel/next.js#16107]
# Bug report

Server Error
TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined.

## Describe the bug

Link without passed href results in this bug

## To Reproduce

Use Link without href.

## Expected behavior

Even though that typescript indicates the error, maybe a more helpful error message would be better?
## Screenshots

![Screenshot 2020-08-12 at 12 17 00](https://user-images.githubusercontent.com/51530311/89998078-bb5ea000-dc95-11ea-9fa7-d1c3e7c58aeb.png)

![Screenshot 2020-08-12 at 12 19 19](https://user-images.githubusercontent.com/51530311/89998330-0f698480-dc96-11ea-9d5d-30e68fb01362.png)

**Comment by todortotev** [comment]
If you feel this is considered a bug, I'll be happy to submit a PR with the fix.

**Comment by dodiameer** [comment]
I don't think this should be considered a bug because I don't see why you need a link without an ```href```.

If you're getting external data and some parts don't have a link but most do, you can add a condition and if the data doesn't have a link just render it as regular text.

**Comment by maerzhase** [comment]
While i agree with @dodiameer that a link without href is not need, the error message could be more clear about the error being cause because the href provided to the link is invalid and/or empty.

**Comment by Kumagor0** [comment]
Why is this closed? Cryptic error message is still there, if not for this issue I'd never figure what was the problem for me:

```
Error occurred prerendering page "/login". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot destructure property `auth` of 'undefined' or 'null'.
    at formatUrl (/home/gleb/kespa/kespa/projects/nicolas-landing/.next/server/pages/givental.js:481:7)
    at formatWithValidation (/home/gleb/kespa/kespa/projects/nicolas-landing/.next/server/pages/givental.js:2383:35)
    at resolveHref (/home/gleb/kespa/kespa/projects/nicolas-landing/.next/server/pages/givental.js:1502:89)
    at /home/gleb/kespa/kespa/projects/nicolas-landing/.next/server/pages/givental.js:1212:64
    at Object.useMemo (/home/gleb/kespa/kespa/projects/nicolas-landing/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:30:366)
    at Object.exports.useMemo (/home/gleb/kespa/kespa/projects/nicolas-landing/node_modules/react/cjs/react.production.min.js:25:113)
    at Link (/home/gleb/kespa/kespa/projects/nicolas-landing/.next/server/pages/givental.js:1211:22)
    at d (/home/gleb/kespa/kespa/projects/nicolas-landing/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/home/gleb/kespa/kespa/projects/nicolas-landing/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/home/gleb/kespa/kespa/projects/nicolas-landing/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)

```

**Comment by RemLampa** [comment]
We experienced this error and it brought our sites down.

The thing is that our hrefs come from a CMS, with a dozen or so content editors creating them.

We could handle this on our side of course. But a warning could have been more helpful for our use case, instead of an outright error, which proved to be fatal.

**Comment by nareshNishad** [comment]
Can anybody help me with how to solve this problem?
Any guidance will be helpful.
Using Next 10.0.0

**Comment by maerzhase** [comment]
@nareshNishad not sure whats your problem but in this issue we are discussing that an error is thrown when a link has no valid `href` provided. if thats your case provide a valid `href` prop to you `Link` component.

**Comment by jserrao** [comment]
@Timer 

What we need from Next is to surface precisely **what part of a link resolution is missing**, that's where the errors usually are. For example, something like:

"Component A passed Payload X to <Link> in `/src/components/component-a.js` and caused an error"

Something like that would give me the context to go dig in the right place. I'm not sure how we can stack trace all the permutations of badly resolved/queried links, but that tends to be what blows up my Next sites.

For others dealing with this: what I've done to this is build a giant `link` fragment for all my GraphQL queries to share, so any link request can essentially handle any content-type. Your queries quickly grow to insane sizes. A nice workaround to checkout is actually inside of the GraphQL library itself, called [`stripIgnoredCharacters()`](https://github.com/graphql/graphql-js/blob/main/src/utilities/stripIgnoredCharacters.ts) - a function that eliminates all the white space in your GQL queries.

**Comment by dangerousdan** [comment]
I agree that the error message wasn't clear (I'm here via a google search), but I think it is the wrong decision to throw an error here:

You've mentioned that devs should add a condition if the href is empty, but it would be very easy for `<Link />` to contain the conditional.
It's literally just 
```js
if (! props.href) {
  // maybe a console.warn here if you deem this bad practice
  return props.children 
}
```

Rendering an anchor tag without a href attribute is still valid HTML (even passes W3C validation). It's fine to do this in react.

Create-react-app provides [this warning](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md) via jsx-eslint if the href is missing. If the href is set by an empty prop then there is no warning.

You even do it on the [next/link documentation page](https://nextjs.org/docs/api-reference/next/link) (`document.querySelectorAll('a:not([href])')` in the console to see).

Whilst it's not really semantically correct, and probably indicates a mistake, this should only be a warning at most.

This error can occur after build if a site is driven by CMS content. This results in ISR failing and the whole page (or pages) becoming stale. It breaks the site unnecessarily (which other frameworks don't do).

@Timer can we reopen this?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
