### ISSUE TITLE
getStaticProps not waiting for props.

### ISSUE THREAD

**Issue by daveteu** [vercel/next.js#16200]
getStaticProps is generating page before props is returned. It's generating the pages 7-8 pages all with empty props.

It is not waiting for the database to return the promise.

If I followed https://err.sh/next.js/prerender-error and set initial props in the page, all the props are also not filled with my data from mongoose call.

This happens in next ^9.5.2 .

**Tested on**
Mac OS Catalina
Ubuntu 18.04
Vercel.com Hosting

```
export async function getStaticPaths() {
    return {
        paths: [ { params: { pid: '5f34c9f2c2158d17c3d68644' } }], //my paths are more than just these.
      fallback: true
    };
  }

export async function getStaticProps({ params }) {

        await mongoose() //Connection to mongodb
        await Model.findById(params.pid).populate({ path: 'owner', select: 'displayName mobile'}).lean().exec((err, doc) => {

            let property =  JSON.parse(JSON.stringify(doc)); //
           console.log('property', property); //this is called after page (7/8) rendered
            return {    //I moved the return call into the callback, I tried returning outside after await too.
                props: {
                    property,
                },
                revalidate: 100, // In seconds
            }
        })
}
```

> info  - Loaded env from /home/ubuntu/project/.env.local
> info  - Creating an optimized production build  
> info  - Compiled successfully
> info  - Collecting page data  
> [   =] info  - Generating static pages (0/7)hasMounted false
> router.query.pid undefined
> currentUser null
> [=== ] info  - Generating static pages (1/7)profile undefined
> [==  ] info  - Generating static pages (3/7)data undefined
> [=   ] info  - Generating static pages (5/7)props on single page undefined
> 
> Error occurred prerendering page "/single/[pid]". Read more: https://err.sh/next.js/prerender-error
> TypeError: Cannot read property 'address_line_1' of undefined
>     at Single (/home/ubuntu/project/.next/server/pages/single/[pid].js:1270:35)
>     at d (/home/ubuntu/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
>     at $a (/home/ubuntu/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
>     at a.b.render (/home/ubuntu/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
>     at a.b.read (/home/ubuntu/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
>     at renderToString (/home/ubuntu/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
>     at renderPage (/home/ubuntu/project/node_modules/next/dist/next-server/server/render.js:48:686)
>     at Object.ctx.renderPage (/home/ubuntu/project/.next/server/pages/_document.js:820:30)
>     at Function.getInitialProps (/home/ubuntu/project/.next/server/pages/_document.js:290:19)
>     at Function.getInitialProps (/home/ubuntu/project/.next/server/pages/_document.js:824:87)
>     at loadGetInitialProps (/home/ubuntu/project/node_modules/next/dist/next-server/lib/utils.js:5:101)
>     at renderToHTML (/home/ubuntu/project/node_modules/next/dist/next-server/server/render.js:48:977)
>     at async Object.exportPage [as default] (/home/ubuntu/project/node_modules/next/dist/export/worker.js:25:6)
> info  - Generating static pages (7/7)
> 
> > Build error occurred
> Error: Export encountered errors on following paths:
>         /single/[pid]
>     at exportApp (/home/ubuntu/project/node_modules/next/dist/export/index.js:24:1103)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async build (/home/ubuntu/project/node_modules/next/dist/build/index.js:37:212)
>

**Comment by Danetag** [comment]
You're returning the props within your `await Model.findById(params.pid)...` which likely causes the issue. Maybe try something like

```.ts
export async function getStaticProps({ params }) {
        await mongoose();
        const { doc, err } =  await Model.findById(params.pid).populate({ path: 'owner', select: 'displayName mobile'}).lean().exec((err, doc) => {
               return { doc, err }
        });
        
        if (err) {
            return {} // handle 500
        }

        let property =  JSON.parse(JSON.stringify(doc));
        console.log('property', property);

        return { 
                props: {
                    property,
                },
                revalidate: 100, // In seconds
            }
        })
}
```

**Comment by daveteu** [comment]
> You're returning the props within your `await Model.findById(params.pid)...` which likely causes the issue. Maybe try something like
> You also probably need more try/catch in case the connection to the DB fail, etc.

Thank you for replying. Yes I've also put return outside the Model.find called back with the same results. 

> 1. === ] info  - Generating static pages (1/8)profile undefined
> 2. [=   ] info  - Generating static pages (4/8)data undefined
> 3. props on single page undefined
> 
> 4 .Error occurred prerendering page "/single/[pid]". Read more: https://err.sh/next.js/prerender-error
> 5. TypeError: Cannot read property 'address_line_1' of undefined
> 6.   at SinglePage (/home/ubuntu/project/.next/server/pages/single/[pid].js:705:35)
> 7.     at d (/home/ubuntu/goreal2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
> 8.    at $a (/home/ubuntu/goreal2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
> 9.     at a.b.render (/home/ubuntu/goreal2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
> 10.     at a.b.read (/home/ubuntu/goreal2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
> 11.     at renderToString (/home/ubuntu/goreal2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
> 12.     at renderPage (/home/ubuntu/goreal2/node_modules/next/dist/next-server/server/render.js:48:686)
> 13.     at Object.ctx.renderPage (/home/ubuntu/goreal2/.next/server/pages/_document.js:820:30)
> 14.     at Function.getInitialProps (/home/ubuntu/goreal2/.next/server/pages/_document.js:290:19)
> 15.     at Function.getInitialProps (/home/ubuntu/goreal2/.next/server/pages/_document.js:824:87)
> 16.     at loadGetInitialProps (/home/ubuntu/goreal2/node_modules/next/dist/next-server/lib/utils.js:5:101)
> 17.     at renderToHTML (/home/ubuntu/goreal2/node_modules/next/dist/next-server/server/render.js:48:977)
> 18.     at async Object.exportPage [as default] (/home/ubuntu/goreal2/node_modules/next/dist/export/worker.js:25:6)
> 19. [Mongoose] Creating New Connection warning
> 20. [    ] info  - Generating static pages (6/8)[ MONGOOSE ] OPEN(1) info
> 21.  [=   ] info  - Generating static pages (6/8)props on single page {
> 22.  _id: '5f34c9f2c2158d17c3d68644',
> 23.  location: { coordinates: [ 103.8549872038, 1.2796257989 ], type: 'Point' },
> 24.  address_line_1: 'this is address line 1',

on Line 3,  "props on single page" undefined 
on Line 5. TypeError: Cannot read property 'address_line_1' of undefined

on line 19, my db connected.
on line 24, you can see my props address_line_1 printing after next build throws error.

PS: somehow the (build) process.std of the page building overwriting console.log line makes it hard to see.

I have added condition **if (!property) return null** inside my page function to fix above issues, but it shouldn't have been an issue in the first place.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
