### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve module

### ISSUE THREAD

**Issue by Pasoul** [vercel/next.js#16582]
# Bug report

`npm run build` fail in server
```
ModuleNotFoundError: Module not found: Error: Can't resolve '../../components/input' in '/var/jenkins_home/workspace/test-lukou-h5/pages/login'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (/var/jenkins_home/workspace/test-lukou-h5/node_modules/next/dist/build/index.js:15:918)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lukou-next@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lukou-next@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-26T04_14_15_204Z-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

## Describe the bug

1. npm run build can be successfully executed locally
2. Executing npm run build on the server will report an error

## To Reproduce

1. Create a new input file in components
![image](https://user-images.githubusercontent.com/22902187/91264604-3e5a1d00-e7a3-11ea-8130-ac43feb02b56.png)
2. Reference it in login.tsx
![image](https://user-images.githubusercontent.com/22902187/91264897-529e1a00-e7a3-11ea-94a4-430f17e7429b.png)
3. custom .babelrc file
```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "components": "./components",
          "api": "./api",
          "pages": "./pages",
          "stores": "./stores",
          "styles": "./styles",
          "utils": "./utils",
          "typings": "./typings",
        }
      }
    ]
  ]
}
```
4. Execute npm run build on the server
5. See error
```
ModuleNotFoundError: Module not found: Error: Can't resolve '../../components/input' in '/var/jenkins_home/workspace/test-lukou-h5/pages/login'
```

## Expected behavior

can build success in server

## System information

- OS: linux
- Version of Next.js: 9.5.2
- Version of Node.js: 12.9.1

**Comment by Pasoul** [comment]
可能是git忽略文件大小写所致

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
