### ISSUE TITLE
Serverless build fails with: ModuleNotFoundError: Module not found: Error: Can't resolve 'aws-sdk'

### ISSUE THREAD

**Issue by mikecao** [vercel/next.js#16618]
# Bug report

## Describe the bug

When doing a `serverless` build, the build fails with `ModuleNotFoundError: Module not found: Error: Can't resolve 'aws-sdk'`
I've trace it down to the `bcrypt` module being used in an api function. I assume since this module a server function running on the server side it should work. Running a normal `server` build does not produce any errors.

Here is the full error:
```
> next build

info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'aws-sdk' in '/home/mike/test/nextjs-serverless-build/node_modules/node-pre-gyp/lib'


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/home/mike/test/nextjs-serverless-build/node_modules/next/dist/build/index.js:15:918)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mike/.npm/_logs/2020-08-27T03_25_35_982Z-debug.log
```

## To Reproduce

I've created a repo from a barebones `create-next-app` example. The only change is `pages/api/hello.js` uses the `bcrypt` module and the `next.config.js` is set to `serverless`.

https://github.com/mikecao/nextjs-serverless-build

## Expected behavior

Should not produce an error.

## System information

- OS: Ubuntu 20.04
- Version of Next.js: 9.5.2
- Version of Node.js: 14.8.0

**Comment by lednhatkhanh** [comment]
I got the same error with serverless build, it works fine with normal build.

**Comment by dakshshah96** [comment]
@mikecao Check this issue: #4940

**Comment by mikecao** [comment]
@dakshshah96 That issue was due to people using node-only modules on the client side. That's why I created the repo example to show it still fails in the simplest case.

**Comment by lednhatkhanh** [comment]
Does anybody have a workaround for this? Thank you.

**Comment by CryogenicPlanet** [comment]
Any updates on this?

**Comment by thiskevinwang** [comment]
Just a +1:
You can expect this error to occur when creating a serverless build with say, a NextJS + MDX app that uses `remark-prism`
- it'll complain about `'canvas'`, in `jsdom`
- if you go through your `yarn.lock`, you can see that `jsdom` is used by `remark-prism`

**Comment by josteph** [comment]
Yeah `canvas` is declared as `peerDependencies` in `jsdom`, so that bounds to be expected to happen.

**Comment by MaxAst** [comment]
Hi @thiskevinwang, I've actually just run into this issue with `remark-prism`, which I use in `getStaticProps`. After deploying to Vercel it works fine at first, but throws this error once the revalidate interval passes:

`Error: Cannot find module 'prismjs/components/prism-markup`

which is not exactly the same error as you had, but probably related? Adding `prismjs` to webpack externals in next.config.js as described in @CryogenicPlanet 's comment didn't work for me. Would love to hear how you fixed your error

**Comment by JanKaifer** [comment]
Please verify that your issue can be recreated with `next@canary`.

### **Why was this issue marked with the `please verify canary` label?**

We noticed the provided reproduction was using an older version of Next.js, instead of `canary`.

The canary version of Next.js ships daily and includes all features and fixes that have not been released to the stable version yet. You can think of canary as a _public beta_. Some issues may already be fixed in the canary version, so please verify that your issue reproduces by running `npm install next@canary` and test it in your project, using your reproduction steps.

If the issue does not reproduce with the `canary` version, then it has already been fixed and this issue can be closed.

### **How can I quickly verify if my issue has been fixed in `canary`?**

The safest way is to install `next@canary` in your project and test it, but you can also search through [closed Next.js issues](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aclosed) for duplicates or check the [Next.js releases](https://github.com/vercel/next.js/releases).

### **My issue has been open for a long time, why do I need to verify `canary` now?**

Next.js does not backport bug fixes to older versions of Next.js. Instead, we are trying to introduce only a minimal amount of breaking changes between major releases.

### **What happens if I don't verify against the canary version of Next.js?**

An issue with the `please verify canary` that receives no meaningful activity (e.g. new comments that acknowledge verification against `canary`) will be automatically closed and locked after 30 days.

If your issue has not been resolved in that time and it has been closed/locked, please open a new issue, with the required reproduction, using `next@canary`.

### **I did not open this issue, but it is relevant to me, what can I do to help?**

Anyone experiencing the same issue is welcome to provide a minimal reproduction (following the above steps). Furthermore, you can upvote the issue (using the :+1: reaction on the topmost comment, instead of commenting "I have the same issue" etc.). Then, we can sort issues by engagement to prioritize.

### **I think my reproduction is good enough, why aren't you looking into it quicker?**

We look into every Next.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### **Useful Resources**

- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)
- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a Next.js bug](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml)
- [Next.js Triaging issues](https://github.com/vercel/next.js/blob/canary/contributing/repository/triaging.md)

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
