### ISSUE TITLE
getServerSideProps can not set headers from ctx.res. How to set cookies in server side?

### ISSUE THREAD

**Issue by thinksource** [vercel/next.js#16764]
# Bug report

## Describe the bug

Can not write response header in getServerSideProps function

## To Reproduce

I have simple logout page which is just for clear cookie and logout.
```
const logout = ()=>{
   return (<div/>)
}


export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const auth_cookie = cookie.serialize('auth', '', {
        maxAge: -1,
        httpOnly: true,
        path: '/',
      })
    const header = {'Locaiton': '/','Set-Cookie': auth_cookie}
    ctx.res.writeHead(302, header)
    return { props: { names: ['john', 'doe', 'michael', 'bruno'] } };
};

export default logout
```
and the error is:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:536:11)
    at DevServer.sendHTML (C:\workgit\tslogin\node_modules\next\dist\server\next-dev-server.js:31:5)
    at DevServer.render (C:\workgit\tslogin\node_modules\next\dist\next-server\server\next-server.js:56:37)
    at async Object.fn (C:\workgit\tslogin\node_modules\next\dist\next-server\server\next-server.js:32:107)
    at async Router.execute (C:\workgit\tslogin\node_modules\next\dist\next-server\server\router.js:38:67)
    at async DevServer.run (C:\workgit\tslogin\node_modules\next\dist\next-server\server\next-server.js:49:494)
    at async DevServer.handleRequest (C:\workgit\tslogin\node_modules\next\dist\next-server\server\next-server.js:18:101) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

## Expected behavior

For above code expect logout and redirect to  '/'

## System information

- OS: Windows
- Browser chrome
- Next.js: 9.5.3
- Node.js: 14.9.0

## Additional context

I think it need to place set headers in server side initialization

**Comment by jamesmosier** [comment]
I believe you also need to do `ctx.res.end();` after `ctx.res.writeHead(302, header)`

**Comment by thinksource** [comment]
@jamesmosier 
I change code to:

```
export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const auth_cookie = cookie.serialize('auth', '', {
        maxAge: -1,
        httpOnly: true,
        path: '/',
      })
    const header = {'Locaiton': '/','Set-Cookie': auth_cookie}
    
    ctx.res.writeHead(302, header).end()

    return { props: { names: ['john', 'doe', 'michael', 'bruno'] } };
};
```

and the problem is still there:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:533:11)
    at DevServer.sendHTML (D:\workspaces\tslogin\node_modules\next\dist\server\next-dev-server.js:35:5)
    at DevServer.render (D:\workspaces\tslogin\node_modules\next\dist\next-server\server\next-server.js:56:37)
    at async Object.fn (D:\workspaces\tslogin\node_modules\next\dist\next-server\server\next-server.js:31:107)
    at async Router.execute (D:\workspaces\tslogin\node_modules\next\dist\next-server\server\router.js:23:67)
    at async DevServer.run (D:\workspaces\tslogin\node_modules\next\dist\next-server\server\next-server.js:49:494)
    at async DevServer.handleRequest (D:\workspaces\tslogin\node_modules\next\dist\next-server\server\next-server.js:17:101) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:643:15)
    at ServerResponse.end (_http_outgoing.js:763:7)
    at ServerResponse.end (D:\workspaces\tslogin\node_modules\next\dist\compiled\compression\index.js:1:148805)
    at DevServer.handleRequest (D:\workspaces\tslogin\node_modules\next\dist\next-server\server\next-server.js:17:189)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:702:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
```

**Comment by SelvinM** [comment]
This is a bug that has been around for a while now. Here is a workaround that you can use until a fix is released:

https://github.com/vercel/next.js/discussions/14547#discussioncomment-55556

**Comment by sa3dany** [comment]
Using v11.0.1, I am able to set headers in `getServerSideProps()` while using redirects like so:

```js
res.setHeader("Set-Cookie", "foo=bar");

return {
    redirect: {
      destination: "/",
    },
};
```

So I believe this issue can be closed.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
