### ISSUE TITLE
document not defined in page-loader.js

### ISSUE THREAD

**Issue by bouteillerAlan** [vercel/next.js#16816]
# Bug report

## Describe the bug

When i launch the project with `yarn dev` (`"dev": "next dev",`) the following error is throw :
```
ReferenceError: document is not defined
    at Object.<anonymous> (P:\Developer_Tools\laragon\www\aiSite\node_modules\next\dist\client\page-loader.js:5:131)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (P:\Developer_Tools\laragon\www\aiSite\node_modules\next\dist\client\index.js:1:1302)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
```

The `page-loader.js:5:131` is `const hasNoModule=('noModule'in document.createElement('script'))`.

## To Reproduce

It's hard to tell how the problem appear. Yesteday i have no problem and this morning i have this error; without any change.

1. `yarn dev`
2. See error

## Expected behavior

Launch with no error.

## System information

- OS: Windows 10
- Version of Next.js: 9.5.3
- Version of Node.js: 14.5.0

## Additional context

[The github repo.](https://github.com/bouteillerAlan/ai-website)

**Comment by timneutkens** [comment]
https://github.com/bouteillerAlan/ai-website/blob/master/src/pages/index.tsx#L2

You're importing Next.js internals here. It should be `import Router from 'next/router`.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
