### ISSUE TITLE
API routes: redirect errror

### ISSUE THREAD

**Issue by szomolanyi** [vercel/next.js#16810]
# Bug report

## Describe the bug

API handler with res.redirect('/') successfully redirects browser, but prints error message to console :
`TypeError: Cannot read property 'end' of undefined
    at redirect (C:\Users\432015\work\web\redirect-test\node_modules\next\dist\next-server\server\api-utils.js:32:394)
    at ServerResponse.apiRes.redirect (C:\Users\432015\work\web\redirect-test\node_modules\next\dist\next-server\server\api-utils.js:6:340)
    at module.exports../pages/api/tst.js.__webpack_exports__.default (C:\Users\432015\work\web\redirect-test\.next\server\pages\api\tst.js:107:7)
    at apiResolver (C:\Users\432015\work\web\redirect-test\node_modules\next\dist\next-server\server\api-utils.js:8:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

## To Reproduce

1. Create simple API route (tst.js):

`export default (req, res) => {
  res.redirect('https://www.google.com');
}
`

2. Then call: http://localhost:3000/api/tst.

3. Browser will be redirected to http://google.com, and error message will be printed to console.

## Expected behavior

No error message is printed to the console.

## System information

- OS: Windows
- Version of Next.js: 9.5.3
- Version of Node.js: v10.15.3

## Additional context

In more complex routes res.redirect has other strange behaviors, for example, the response is never sent to the browser

**Comment by timneutkens** [comment]
Based on the reproduction steps provided this works fine and has the intended result. Most likely you have something in your project that is causing this issue, maybe you're using a custom server?

Going to close based on the reproduction having the correct result.

**Comment by szomolanyi** [comment]
I am not using custom server. I have created next skeleton project using
`npx create-next-app`
and then only added api route pages/api/tst.js.

I tried to reproduce the issue on Linux (WSL)  with node v12 and it works correctly : browser was redirected and no error was printed.

It is definitely caused in my environment/setup, maybe invalid node version ?

**Comment by szomolanyi** [comment]
After upgrading Nodejs to v14.9.0, the problem is gone. Redirect works correctly and error mesage is not displayed.

**Comment by dhmacs** [comment]
I'm having the same issue. In development redirect works fine, in production even a simple api route like this fails:
```ts
import { NextApiRequest, NextApiResponse } from "next";

const handler = async (req: NextApiRequest, res: NextApiResponse<any>) => {
    res.redirect("/");
};

export default handler;
```

The error is `Cannot read property 'end' of undefined`. And I'm running this on Node 12.x

**Comment by dhmacs** [comment]
For anyone searching this issue, in my case the error was generated by a serverless integration layer that I use ti deploy Next.js on AWS

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
