### ISSUE TITLE
Custom server with TypeScript: error with spreading Set

### ISSUE THREAD

**Issue by tuomokar** [vercel/next.js#17094]
# Bug report

## Describe the bug

When having set up Next.js with a custom server and TypeScript, after having started up the custom server and going to localhost:3000 in the browser, there happens this error `RangeError: Invalid array length` on the server.

## To Reproduce

Repository to reproduce the issue can be found here: https://github.com/tuomokar/simple-next-express-typescript

Clone the repo, run `npm i` and `npm run dev` and go to localhost:3000. In the command line, you should see the error mentioned above.

## Expected behavior

The error shouldn't happen.

## System information

- OS: Windows, but should happen on any OS
- Version of Next.js:  9.5.3
- Version of Node.js: 12.18.3

## Additional context

Full stack trace:

```
RangeError: Invalid array length
    at __spreadArrays (C:\test\simple-next-express-typescript\.next\server\pages\_document.js:52:18)
    at getDocumentFiles (C:\test\simple-next-express-typescript\.next\server\pages\_document.js:277:13)
    at Head.module.exports../node_modules/next/dist/pages/_document.js.Head.render (C:\test\simple-next-express-typescript\.next\server\pages\_document.js:553:19)
    at processChild (C:\test\simple-next-express-typescript\node_modules\react-dom\cjs\react-dom-server.node.development.js:3293:18)    at resolve (C:\test\simple-next-express-typescript\node_modules\react-dom\cjs\react-dom-server.node.development.js:3124:5)      
    at ReactDOMServerRenderer.render (C:\test\simple-next-express-typescript\node_modules\react-dom\cjs\react-dom-server.node.development.js:3598:22)
    at ReactDOMServerRenderer.read (C:\test\simple-next-express-typescript\node_modules\react-dom\cjs\react-dom-server.node.development.js:3536:29)
    at renderToStaticMarkup (C:\test\simple-next-express-typescript\node_modules\react-dom\cjs\react-dom-server.node.development.js:4261:27)
    at renderDocument (C:\test\simple-next-express-typescript\node_modules\next\next-server\server\render.tsx:216:5)
    at renderToHTML (C:\test\simple-next-express-typescript\node_modules\next\next-server\server\render.tsx:768:14)
```

The error seems to be caused by the spread done [here](https://github.com/vercel/next.js/blob/7203f500916d336f4e1cbcd162baff624c9cd969/packages/next/pages/_document.tsx#L64) (introduced [here](https://github.com/vercel/next.js/pull/16184/files#diff-038a496f54bcbe216b7304af084328cfR53)), specifically by the attempted spread of the Set. This breaks because by default TypeScript does not support iterables on arrays.

A couple of ways to fix this would be:
- Add `downlevelIteration: true` to the tsconfig generated by Next.js
- Change that line to `Array.from(new Set([...sharedFiles, ...pageFiles]))` (funnily this works as the `Array.from` is transpiled a little differently than the spread)

I can make a PR to fix it but first I'd like to hear any opinions on the preferred way to fix it.

The first one of those, the `downlevelIteration` flag, introduces some other things to take into account regarding the emitted code (see for example https://mariusschulz.com/articles/downlevel-iteration-for-es3-es5-in-typescript)

The second one is a very simple but might be again very error prone in the future, because `[...new Set()]` is very concise and simple to use.

**Comment by rjerue** [comment]
Any updates? I have this occurring, but only when dev is false in the `next` function.

**Comment by VadimOnix** [comment]
> {
>   "compilerOptions": {
>     ...
>     "downlevelIteration": true
>   },
>   ...
> }

This configuration helped solve the same problem! Thanks!

P.S.  [A blog from 2017](https://mariusschulz.com/blog/downlevel-iteration-for-es3-es5-in-typescript) mentions using additional configuration `"importHelpers": true` with `downlevelIteration` for reduce amount of helper functions . But i didn't see difference file size in production build now without this parameter. Maybe it's not important in actual typescript version (4.x+)

**Comment by rjerue** [comment]
I'd encourage @tuomokar to put up a fix for a PR. It would be a good start to rectifying and would serve as a better place for implementation comments from maintainers.

**Comment by tuomokar** [comment]
Yeah I'll see if I have time on weekend to make a PR about it.

**Comment by wyantb** [comment]
For what it's worth, I'm not using typescript today, instead I'm using the nextjs precompiled `dist` build of next and I also see this error - sam root cause from spreading the Set though.

Is anyone on the next side of things looking at this error? I'm not especially keen on pulling typescript into my project just to configure it as a workaround for this issue but that might be the easiest way at this point.

**Comment by JLarky** [comment]
This is slightly unrelated, but I had the same issues with arrays instead of Set, and thanks to things mentioned here I changed it from
```ts
[...Array(10).keys()]
```
to
```ts
Array.from(Array(10).keys())
```

**Comment by tgrassl** [comment]
We had the same problem with a Custom Server + Typescript + Revalidate. As soon as the page was rebuilt the CSS+JS files were missing in the head tag. There was no error or warning message so we had to debug into the compiled next code.
The reason was that in [getDocumentFiles ](https://github.com/vercel/next.js/blob/ca2921fca362cd61ecde5acbcf4d03943dbd519c/packages/next/pages/_document.tsx#L48) the spreaded Set for allFiles always returned an empty array. 

@rjerue "downlevelIteration": true fixed it.

**Comment by JanKaifer** [comment]
This issue is quite old and might not be relevant anymore.
Could someone verify that it's still reproducible with `next@canary`?

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
