### ISSUE TITLE
Webpack 5 Release Candidate fails to build

### ISSUE THREAD

**Issue by ConsoleTVs** [vercel/next.js#17293]
# Bug report

## Describe the bug

Using Release Candidate 0 of Webpack 5 fails to build

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Use version `5.0.0-rc.0` of webpack.

## Expected behavior

The same behaviour as the mentioned `5.0.0-beta.28` version.

## System information

- OS: macOS
- Version of Next.js: 9.5.3
- Version of Node.js: 14.4.0

**Comment by ConsoleTVs** [comment]
For the context, I also get: `warning Resolution field "webpack@5.0.0-beta.28" is incompatible with requested version "webpack@4.44.1"` When forcing a specific beta version.

**Comment by ConsoleTVs** [comment]
For further reference, the following fails as well with the canary build and fresh install:

```
{
  "name": "erik",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "resolutions": {
    "webpack": "5.0.0-beta.28"
  },
  "dependencies": {
    "next": "9.5.4-canary.20",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
}
```

```
➜  erik git:(master) ✗ yarn build
yarn run v1.22.5
$ next build

> Build error occurred
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].output has an unknown property 'environment'. These properties are valid:
   object { assetModuleFilename?, auxiliaryComment?, charset?, chunkCallbackName?, chunkFilename?, chunkLoadTimeout?, compareBeforeEmit?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolModuleFilenameTemplate?, devtoolNamespace?, ecmaVersion?, enabledLibraryTypes?, filename?, globalObject?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, iife?, importFunctionName?, jsonpFunction?, library?, libraryExport?, libraryTarget?, module?, path?, pathinfo?, publicPath?, scriptType?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine?, uniqueName?, webassemblyModuleFilename? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
 - configuration[1].output has an unknown property 'environment'. These properties are valid:
   object { assetModuleFilename?, auxiliaryComment?, charset?, chunkCallbackName?, chunkFilename?, chunkLoadTimeout?, compareBeforeEmit?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolModuleFilenameTemplate?, devtoolNamespace?, ecmaVersion?, enabledLibraryTypes?, filename?, globalObject?, hashDigest?, hashDigestLength?, hashFunction?, hashSalt?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, iife?, importFunctionName?, jsonpFunction?, library?, libraryExport?, libraryTarget?, module?, path?, pathinfo?, publicPath?, scriptType?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine?, uniqueName?, webassemblyModuleFilename? }
   -> Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
    at validate (/Users/erik/Code/Projects/erik/node_modules/schema-utils/dist/validate.js:98:11)
    at validateSchema (/Users/erik/Code/Projects/erik/node_modules/webpack/lib/validateSchema.js:40:2)
    at webpack (/Users/erik/Code/Projects/erik/node_modules/webpack/lib/webpack.js:100:2)
    at f (/Users/erik/Code/Projects/erik/node_modules/webpack/lib/index.js:31:15)
    at /Users/erik/Code/Projects/erik/node_modules/next/dist/build/compiler.js:4:172
    at new Promise (<anonymous>)
    at runCompiler (/Users/erik/Code/Projects/erik/node_modules/next/dist/build/compiler.js:4:106)
    at build (/Users/erik/Code/Projects/erik/node_modules/next/dist/build/index.js:13:348) {
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '[0].output',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    },
    {
      keyword: 'additionalProperties',
      dataPath: '[1].output',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ],
  schema: {
    definitions: {
      Amd: [Object],
      AssetModuleFilename: [Object],
      AuxiliaryComment: [Object],
      Bail: [Object],
      CacheOptions: [Object],
      CacheOptionsNormalized: [Object],
      Charset: [Object],
      ChunkCallbackName: [Object],
      ChunkFilename: [Object],
      ChunkLoadTimeout: [Object],
      CompareBeforeEmit: [Object],
      Context: [Object],
      CrossOriginLoading: [Object],
      Dependencies: [Object],
      DevServer: [Object],
      DevTool: [Object],
      DevtoolFallbackModuleFilenameTemplate: [Object],
      DevtoolModuleFilenameTemplate: [Object],
      DevtoolNamespace: [Object],
      EcmaVersion: [Object],
      EnabledLibraryTypes: [Object],
      Entry: [Object],
      EntryDescription: [Object],
      EntryDescriptionNormalized: [Object],
      EntryDynamic: [Object],
      EntryDynamicNormalized: [Object],
      EntryItem: [Object],
      EntryNormalized: [Object],
      EntryObject: [Object],
      EntryRuntime: [Object],
      EntryStatic: [Object],
      EntryStaticNormalized: [Object],
      EntryUnnamed: [Object],
      Experiments: [Object],
      ExternalItem: [Object],
      Externals: [Object],
      ExternalsType: [Object],
      FileCacheOptions: [Object],
      Filename: [Object],
      FilterItemTypes: [Object],
      FilterTypes: [Object],
      GlobalObject: [Object],
      HashDigest: [Object],
      HashDigestLength: [Object],
      HashFunction: [Object],
      HashSalt: [Object],
      HotUpdateChunkFilename: [Object],
      HotUpdateFunction: [Object],
      HotUpdateMainFilename: [Object],
      Iife: [Object],
      ImportFunctionName: [Object],
      InfrastructureLogging: [Object],
      JsonpFunction: [Object],
      Library: [Object],
      LibraryCustomUmdCommentObject: [Object],
      LibraryCustomUmdObject: [Object],
      LibraryExport: [Object],
      LibraryName: [Object],
      LibraryOptions: [Object],
      LibraryType: [Object],
      Loader: [Object],
      MemoryCacheOptions: [Object],
      Mode: [Object],
      ModuleOptions: [Object],
      Name: [Object],
      Node: [Object],
      NodeOptions: [Object],
      Optimization: [Object],
      OptimizationRuntimeChunk: [Object],
      OptimizationRuntimeChunkNormalized: [Object],
      OptimizationSplitChunksCacheGroup: [Object],
      OptimizationSplitChunksGetCacheGroups: [Object],
      OptimizationSplitChunksOptions: [Object],
      OptimizationSplitChunksSizes: [Object],
      Output: [Object],
      OutputModule: [Object],
      OutputNormalized: [Object],
      Parallelism: [Object],
      Path: [Object],
      Pathinfo: [Object],
      Performance: [Object],
      PerformanceOptions: [Object],
      Plugins: [Object],
      Profile: [Object],
      PublicPath: [Object],
      RecordsInputPath: [Object],
      RecordsOutputPath: [Object],
      RecordsPath: [Object],
      Resolve: [Object],
      ResolveLoader: [Object],
      ResolveOptions: [Object],
      ResolvePluginInstance: [Object],
      RuleSetCondition: [Object],
      RuleSetConditionAbsolute: [Object],
      RuleSetConditionOrConditions: [Object],
      RuleSetConditionOrConditionsAbsolute: [Object],
      RuleSetConditions: [Object],
      RuleSetConditionsAbsolute: [Object],
      RuleSetLoader: [Object],
      RuleSetLoaderOptions: [Object],
      RuleSetRule: [Object],
      RuleSetRules: [Object],
      RuleSetUse: [Object],
      RuleSetUseItem: [Object],
      ScriptType: [Object],
      SourceMapFilename: [Object],
      SourcePrefix: [Object],
      StatsOptions: [Object],
      StatsValue: [Object],
      StrictModuleExceptionHandling: [Object],
      Target: [Object],
      UmdNamedDefine: [Object],
      UniqueName: [Object],
      Watch: [Object],
      WatchOptions: [Object],
      WebassemblyModuleFilename: [Object],
      WebpackOptionsNormalized: [Object],
      WebpackPluginFunction: [Object],
      WebpackPluginInstance: [Object]
    },
    description: 'Options object as provided by the user.',
    type: 'object',
    additionalProperties: false,
    properties: {
      amd: [Object],
      bail: [Object],
      cache: [Object],
      context: [Object],
      dependencies: [Object],
      devServer: [Object],
      devtool: [Object],
      entry: [Object],
      experiments: [Object],
      externals: [Object],
      externalsType: [Object],
      infrastructureLogging: [Object],
      loader: [Object],
      mode: [Object],
      module: [Object],
      name: [Object],
      node: [Object],
      optimization: [Object],
      output: [Object],
      parallelism: [Object],
      performance: [Object],
      plugins: [Object],
      profile: [Object],
      recordsInputPath: [Object],
      recordsOutputPath: [Object],
      recordsPath: [Object],
      resolve: [Object],
      resolveLoader: [Object],
      stats: [Object],
      target: [Object],
      watch: [Object],
      watchOptions: [Object]
    }
  },
  headerName: 'Webpack',
  baseDataPath: 'configuration',
  postFormatter: [Function: postFormatter]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lfades** [comment]
You need to be on the latest `canary` and using `webpack@5.0.0-beta.30`. Also notice that this is very experimental and the versions will keep changing.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
