### ISSUE TITLE
Redirect does not work with "https://" in a destination query parameter

### ISSUE THREAD

**Issue by djmarland** [vercel/next.js#17440]
# Bug report

## Describe the bug

When trying to redirect to an external URL which contains query parameters, one cannot have "https://" in the parameter.

For example if I wish to redirect `/set-password` to `https://authserver.example.com/set-password?returnUrl=https://www.example.com/login`. This results in an "Internal Server Error". It is also the case when urlencoded: `https://authserver.example.com/set-password?returnUrl=https%3A%2F%2Fwww.example.com%2Flogin`

## To Reproduce

Add the following code to next.config.js

```
async redirects() {
        return [
            {
                source: '/set-password',
                destination: 'https://authserver.example.com/set-password?returnUrl=https%3A%2F%2Fwww.example.com/login',
                permanent: true,
            },
        ]
    },
```

Start the nextJS dev server:  e.g.`next -p 3000`
Visit `http://127.0.0.1:3000/set-password

## Expected behavior

Browser should redirect to https://authserver.example.com/set-password?returnUrl=https://www.example.com/login

## Actual behaviour

Browser shows "Internal Server Error". Terminal console reads:

```
$ next -p 3000
ready - started server on http://localhost:3000
info  - Using external babel configuration from /project/package.json
event - compiled successfully
TypeError: Missing parameter name at 6
    at lexer (/project/node_modules/next/dist/compiled/path-to-regexp/index.js:47:23)
    at parse (/project/node_modules/next/dist/compiled/path-to-regexp/index.js:97:18)
    at compile (/project/node_modules/next/dist/compiled/path-to-regexp/index.js:181:29)
    at prepareDestination (/project/node_modules/next/dist/next-server/server/router.js:10:64)
    at Object.fn (/project/node_modules/next/dist/next-server/server/next-server.js:31:821)
    at Router.execute (/project/desktop_front_end/node_modules/next/dist/next-server/server/router.js:38:83)
    at async DevServer.run (/project/desktop_front_end/node_modules/next/dist/next-server/server/next-server.js:44:494)
```

## System information

- OS: Docker linux
- Version of Next.js: 9.5.3
- Version of Node.js: [e.g. 10.10.0]

**Comment by ijjk** [comment]
Hi, this should be corrected in the latest canary of Next.js `v10.0.2-canary.4`, please upgrade and try it out!

**Comment by djmarland** [comment]
I can confirm it is fixed. Thank you

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
