### ISSUE TITLE
Next.js production build doesn't prevent process exiting due to unhandled exceptions

### ISSUE THREAD

**Issue by maxproske** [vercel/next.js#17574]
# Bug report

## Describe the bug

Next.js process exits with code 1 when API route throws exception in production mode.

A common mistake that could easily lay dormant causes Next.js to exit the PRODUCTION server when it eventually gets run. Yes, I understand pragmatically you shouldn't be masking response errors, but I don't feel very confident using Next.js in production, when a simple race condition that's almost never triggered can bring down the server.

## To Reproduce

```bash
$ npx create-next-app production-process-exits
```
```js
// pages/api/hello.js

export default (req, res) => {
  res.end().write()
}
```
Or
```js
// pages/api/hello.js

export default (req, res) => {
  setTimeout(() => res.write(), 1000)
  res.end()
}
```
```bash
$ yarn build
$ yarn start
```
Visit http://localhost:3000/api/hello, see process exit with the following stack trace:
```
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:637:17)
    at ServerResponse.write (_http_outgoing.js:629:15)
    at ServerResponse.write (/home/max/production-process-exits/node_modules/next/dist/compiled/compression/index.js:1:148632)
    at Timeout.eval [as _onTimeout] (webpack-internal:///./pages/api/hello.js:4:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:692:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
error Command failed with exit code 1.
```

## Expected behavior

Error should be output without exiting the process.

## System information

- OS: Ubuntu 20.04
- Version of Next.js: 9.5.3
- Version of Node.js: 12.16.3

## Additional Context

Short of wrapping my entire API in a try/catch block, I am using the following workaround at the entrypoint of my app:

```js
// pages/_app.js

if (process.env.NODE_ENV === 'production') {
  process.on('uncaughtException', (error) => {
    console.error(error.stack)
    // Don't run process.exit(1)
  })
}

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default MyApp
```

**Comment by HaNdTriX** [comment]
### Let it crash!

From my point of view this is the wanted behaviour. 

Keeping the node process running on uncaught exceptions may lead to new errors (e.g. Memory Leaks, CPU peaks, etc.) that may be very hard to debug.

Your production setup should handle these crashes. Check out the following links if you want to know how:

- [forever](https://www.npmjs.com/package/forever) 
- [Docker restart policy](https://docs.docker.com/config/containers/start-containers-automatically/#:~:text=Use%20a%20restart%20policy&text=Restart%20the%20container%20if%20it,a%20non%2Dzero%20exit%20code.&text=Similar%20to%20always%20%2C%20except%20that,even%20after%20Docker%20daemon%20restarts.)
- [pm2 watch](https://pm2.keymetrics.io/docs/usage/watch-and-restart/)
- [kubernetes restart](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)

**Comment by Zauberfisch** [comment]
@HaNdTriX that is a philosophy I can normally get behind. Though I'd perhaps let `systemd` handle the restarting

however, the rest of next seems to be built to catch exceptions globally and render an error page.  
So saying "We'll handle errors except on that one route" is inconsistent and will lead to (some) developers not handling exceptions and expecting node to just show an error instead of crashing.

If it is decided that "let it crash when it's an api route" is the way to go, then at least we need documentation for this behaviour in both the api route docs and the custom error page docs.

**Comment by timneutkens** [comment]
This has been fixed a while ago, we now `process.exit(0)` at the end of the build process when there are no errors

**Comment by Zauberfisch** [comment]
@maxproske I haven't tested this, but can you confirm that this has been fixed?
From the comment of timneutkens I feel like he is talking about errors during build process, not errors that happen in a deployed production system.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
