### ISSUE TITLE
Missing Err.sh document for Sharp installation

### ISSUE THREAD

**Issue by keegandonley** [vercel/next.js#18347]
# Bug report

## Describe the bug

The err.sh link given by Next 10 goes to a 404: `https://err.sh/next.js/install-sharp` links to `https://github.com/vercel/next.js/blob/master/errors/install-sharp.md` 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upgrade to Next 10
2. Don't have Sharp installed
3. Use the image component

## Expected behavior

This link should link to the correct document

## System information

- OS: macOS
- Version of Next.js: 10
- Version of Node.js: 10.15.3

**Comment by ijjk** [comment]
Hi, thanks for the report! The mentioned link should now be available

**Comment by timneutkens** [comment]
The doc should be updated as sharp is installed by default, seemingly the installation failed on your device though 🤔

**Comment by keegandonley** [comment]
Thanks @timneutkens! Yeah this was kind of a weird case for me. The XCode command line tools seemed corrupted or partially missing so building and installing sharp failed until I removed them and re-installed.

**Comment by luknl** [comment]
Had the same error on Mac:
```
{ Error: Cannot find module 'sharp'

Learn more: https://err.sh/next.js/install-sharp
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at imageOptimizer (...../app/node_modules/next/dist/next-server/server/image-optimizer.js:4:7)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
```

Tried to uninstall and re-install XCode command line tools but that didn't work.
Tried to fix it with the upcoming updated doc [here](https://github.com/vercel/next.js/pull/18508/files), and option 1 worked!
I was using node v10.13.0, so I [did this](https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version) to update to latest stable version (currently v14.15.0).
Then after a `npm i sharp`, the error was gone   🎉.

**Comment by pedromagalhaes** [comment]
This happens because you are using a wrong Node version. Check your warnings when building the app. In my case I got the following:
`sharp@0.26.2: The engine "node" is incompatible with this module. Expected version ">=10.16.0"`

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
