### ISSUE TITLE
Upgrading to Next.js 10 and React 17 - Webpack build fails with `pragma has been set but pragmaFrag has not been set`

### ISSUE THREAD

**Issue by Vadorequest** [vercel/next.js#18461]
# Bug report

## Describe the bug

```
error - ./src/components/errors/ErrorDebug.tsx
Error: /Users/vadorequest/dev/next-right-now/src/components/errors/ErrorDebug.tsx: transform-react-jsx: pragma has been set but pragmaFrag has not been set
Error: Cannot find module '/Users/vadorequest/dev/next-right-now/.next/server/pages-manifest.json'
Require stack:
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/require.js
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/load-components.js
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/api-utils.js
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/next-server.js
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/server/next.js
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/server/lib/start-server.js
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/cli/next-dev.js
- /Users/vadorequest/dev/next-right-now/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at getPagePath (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at DevServer.findPageComponents (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/next-server.js:71:296)
    at DevServer.renderErrorToHTML (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/next-server.js:127:120)
    at DevServer.renderErrorToHTML (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/server/next-dev-server.js:34:974) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/require.js',
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/server/next.js',
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/server/lib/start-server.js',
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/cli/next-dev.js',
    '/Users/vadorequest/dev/next-right-now/node_modules/next/dist/bin/next'
  ]

```

Related to:
- https://github.com/babel/babel/issues/12208
- https://github.com/emotion-js/emotion/issues/2041#issuecomment-718245427
- https://github.com/emotion-js/emotion/issues/1969
- https://github.com/emotion-js/emotion/pull/1970

The issue isn't related with Next.js 10 directly, but between Babel, React 17 and Emotion.

## To Reproduce

Clone this branch:

[`a7cb72f` (#189)](https://github.com/UnlyEd/next-right-now/pull/189/commits/a7cb72f3d98f63830f609cd43811adde69c68629)

Run `yarn start`

## Additional context

I'm not sure if Next.js can do anything about this, it probably can't.
**I wonder if upgrading to Next.js 10 while staying on React 16 is an advised workaround until the issue is fixed.**

**Comment by karlhorky** [comment]
Next.js 10 + React 17 + Emotion doesn't need the JSX pragma comment.

Try this technique in the new example with the Babel plugin:

https://github.com/vercel/next.js/tree/canary/examples/with-emotion

I just recently did this in a project:

- Add Emotion to Next.js 10: https://github.com/upleveled/next-js-example-sep-2020/commit/363f56fff058b81003e61d6836f5e6836d82dc7a
- Upgrade to React 17: https://github.com/upleveled/next-js-example-sep-2020/commit/6e9a42316f8646ce89a084ab5d1ab4a143e58451

Some gotchas:

1. Remove all of the `/** @jsx jsx */` and `/** @jsxFrag React.Fragment */` pragma comments
2. I had to use `<React.Fragment>` instead of `<>` (seems to be an issue with Emotion's CSS Babel preset, see https://github.com/emotion-js/emotion/issues/1303)

**Comment by Vadorequest** [comment]
Thank you @karlhorky very much!

Following your advices worked fine, see [`a9df25e` (#189)](https://github.com/UnlyEd/next-right-now/pull/189/commits/a9df25e62a77cadb4976741325ca0ff7cb8e40cc)

I also had to add a `babel.config.js` file and install `@emotion/babel-preset-css-prop`, or it would compile successfully, but all CSS would break. Your code examples were very useful!

**Comment by karlhorky** [comment]
Great, glad it worked for you! So can this issue be closed?

**Comment by Vadorequest** [comment]
I'm doing a bit of trying around, my `<>` seem to work still and wanna understand why 😄 
I'll close it once everything seems alright 😉

**Comment by karlhorky** [comment]
Oh, that would be great if you could figure that out - would be awesome to avoid having to import `Fragment`!

**Comment by Vadorequest** [comment]
Well, it definitely seems to work. [`6838ed3` (#189)](https://github.com/UnlyEd/next-right-now/pull/189/commits/6838ed355034fe062cb205e62d6c52251bbbb9ab)

Got deployed on Vercel successfully: https://nrn-v2-mst-aptd-at-lcz-sty-c1-aydh0quhd.vercel.app/fr/examples/native-features/example-with-ssr

**Comment by karlhorky** [comment]
Ah maybe because I'm using TypeScript? https://github.com/emotion-js/emotion/issues/1046

**Comment by karlhorky** [comment]
Ahh, it's because of the missing import at the top of my code. Your code has this line where mine did not:

```jsx
import React from 'react';
```

**Comment by karlhorky** [comment]
Feel free to close this now @Vadorequest :)

**Comment by Vadorequest** [comment]
So, you mean there is no point importing `import React from 'react';` if not using Fragments (or any React "element") anymore? While it was a requirement before React 17?

**Comment by karlhorky** [comment]
Mostly right, although the requirement to import React has also been removed from the versions 0.14.x, 15.x and 16.x

Here's a blog post about the new JSX transform: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by karlhorky** [comment]
Looks like the new version of `@emotion/core` and `@emotion/babel-preset-css-prop` (`>=10.1.0`) will allow opting into [the new JSX runtimes](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) by using such configuration:

**.babelrc**

```json
{
  "presets": [["@emotion/babel-preset-css-prop", { "runtime": "automatic" }]]
}
```

Reference: https://github.com/emotion-js/emotion/pull/2063

**Comment by karlhorky** [comment]
@Vadorequest new version is out! No need to import `React` anymore!!

Example upgrade here: https://github.com/upleveled/next-js-example-sep-2020/commit/f46407e345d3a00e99066d0276acb768f11ad02e

**Comment by Vadorequest** [comment]
Thank you @karlhorky, I've upgraded and there doesn't seem to be any issue. https://github.com/UnlyEd/next-right-now/pull/197

Although, I didn't encounter issues before, but that may be because most of my pages import `React`. 🤔

**Comment by Vadorequest** [comment]
Well, looks like I spoke too fast! It works fine locally, but fails on Vercel with `ReferenceError: _jsx is not defined`. https://github.com/UnlyEd/next-right-now/pull/197#issuecomment-720347051

**Comment by karlhorky** [comment]
Yeah, I ran into something similar (although the error on my side was `_jsxs is not defined`).

Seems to be an issue with how the Babel presets for Next.js and Emotion play together:

https://github.com/vercel/next.js/issues/18096

There is a stopgap workaround, but I think it's probably better to wait for a proper solution:

https://github.com/emotion-js/emotion/issues/2064#issuecomment-720110955

**Comment by eric-burel** [comment]
@Vadorequest can you please reopen until we have a more robust fix? Experiencing this as well with MDX content and I can't find a solution yet

**Comment by karlhorky** [comment]
If anyone else is running into the issue with MDX, more discussion over here: https://github.com/mdx-js/mdx/pull/1014#issuecomment-731024397

**Comment by sgmheyhey** [comment]
> Looks like the new version of `@emotion/core` and `@emotion/babel-preset-css-prop` (`>=10.1.0`) will allow opting into [the new JSX runtimes](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) by using such configuration:
> 
> **.babelrc**
> 
> ```json
> {
>   "presets": [["@emotion/babel-preset-css-prop", { "runtime": "automatic" }]]
> }
> ```
> 
> Reference: [emotion-js/emotion#2063](https://github.com/emotion-js/emotion/pull/2063)

```
Error: [BABEL] **...**-mdx/pages/_app.js: The `runtime` option has been removed. If you want to configure `runtime: "automatic"`, replace `@emotion/babel-preset-css-prop` with `@babel/preset-react` and `@emotion/babel-plugin`. You can find out how to configure things properly here: https://emotion.sh/docs/css-prop#babel-preset (While processing: "**...**-mdx/node_modules/@emotion/babel-preset-css-prop/dist/emotion-babel-preset-css-prop.cjs.js")
```
now, it's not.

**Comment by karlhorky** [comment]
> now, it's not.

You're right, sorry - this comment of mine above is outdated. I've marked it as such.

The latest version of the configuration is here: https://github.com/vercel/next.js/issues/18096#issuecomment-729868888

**Comment by Vadorequest** [comment]
@karlhorky I'm encountering a similar issue with Cypress `pragma and pragmaFrag cannot be set when runtime is automatic` as the one you encountered with MDX. I'm thinking about reverting to old behaviour too. I hadn't understood libs (like MDX, Cypress) needed extra work to support the new `automatic`, this was clearer after reading your above comments.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
