### ISSUE TITLE
Redirecting to correct URL when generating a page gives error

### ISSUE THREAD

**Issue by vladfulgeanu** [vercel/next.js#18783]
I want to have a dynamic route with `id` and `slug` and be able to redirect to correct URL when the slug is wrong.
So from `/post/123/correct-slugXYZ` redirect to `/post/123/correct-slug`.
I also use SSG and I've implemented the redirects from `getStaticProps` that came with version 10.
The problem is that when a wrong slug is typed in the URL I'm getting the following error in Next:
```
TypeError: Cannot read property 'length' of null
    at LRUCache.length (/home/node_modules/next/dist/next-server/server/incremental-cache.js:5:17)
    at LRUCache.set (/home/node_modules/next/dist/compiled/lru-cache/index.js:1:2467)
    at IncrementalCache.set (/home/node_modules/next/dist/next-server/server/incremental-cache.js:14:117)
    at Server.renderToHTMLWithComponents (/home/node_modules/next/dist/next-server/server/next-server.js:127:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.renderToHTML (/home/node_modules/next/dist/next-server/server/next-server.js:127:711)
    at async Server.render (/home/node_modules/next/dist/next-server/server/next-server.js:70:236)
    at async Object.fn (/home/node_modules/next/dist/next-server/server/next-server.js:54:264)
    at async Router.execute (/home/node_modules/next/dist/next-server/server/router.js:24:67)
    at async Server.run (/home/node_modules/next/dist/next-server/server/next-server.js:64:722)
```

## To Reproduce

Dynamic route: `/post/<id>/<slug>`

```js
export const getStaticPaths: GetStaticPaths = async () => {
  return {
    fallback: 'blocking',
    paths: [],
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!params) return { notFound: true };

  const id = Number(params.id);
  const slug = params.slug;

  const data = await getContent(insightId).catch(_ => undefined);

  if (!data) return { notFound: true };

  const correctSlug = slugify(data.title);

  if (correctSlug !== slug) {
    return {
      redirect: {
        destination: `/post/${id}/${correctSlug}`,
        permanent: true,
      },
    };
  }

  return {
    props: {
      data
    },
  };
};
```

**First try** of accessing an URL will work (regardless whether the slug is ok or not), because this is when the page is generated:
`/post/123/correct-slug` would work
`/post/123/correct-slugXY` would work
The files `correct-slug.html` and `correct-slug.json` would be generated correctly in `.next`.

But the error appears when trying to access new wrong URLs like `/post/123/correct-slugXYZ` and `/post/123/correct-slugXYZZZ` and so on. All would make the error appear.

I want to know whether I'm doing something wrong, or if this is really a bug that can be confirmed.

## Expected behavior

Redirect without getting the error.

## System information

- OS: Ubuntu 20.04.1 LTS
- Browser: Chrome 86.0.4240.111
- Version of Next.js: 10.0.1
- Version of Node.js: 12.11.1

**Comment by balazsorban44** [comment]
I wonder if #18735 and this issue is related.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
