### ISSUE TITLE
Since v10 storybook in yarn workspaces causes build error.

### ISSUE THREAD

**Issue by vavra7** [vercel/next.js#18800]
## Describe the bug
After upgrading to Next.js 10 I can not build app.
```
yarn run v1.22.10
warning package.json: No license field
$ next build
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[=   ] info  - Generating static pages (0/2)
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/home/vavra/Projects/test/packages/client/node_modules/react/cjs/react.production.min.js:18:327)
    at exports.useContext (/home/vavra/Projects/test/packages/client/node_modules/react/cjs/react.production.min.js:22:269)
    at Head (/home/vavra/Projects/test/packages/client/node_modules/next/dist/next-server/lib/head.js:15:66)
    at d (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/home/vavra/Projects/test/packages/client/node_modules/next/dist/next-server/server/render.js:50:851)
    at Function.getInitialProps (/home/vavra/Projects/test/packages/client/.next/server/pages/_document.js:273:19)

Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/home/vavra/Projects/test/packages/client/node_modules/react/cjs/react.production.min.js:18:327)
    at exports.useContext (/home/vavra/Projects/test/packages/client/node_modules/react/cjs/react.production.min.js:22:269)
    at Head (/home/vavra/Projects/test/packages/client/node_modules/next/dist/next-server/lib/head.js:15:66)
    at d (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/home/vavra/Projects/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/home/vavra/Projects/test/packages/client/node_modules/next/dist/next-server/server/render.js:50:851)
    at Function.getInitialProps (/home/vavra/Projects/test/packages/client/.next/server/pages/_document.js:273:19)

> Build error occurred
Error: Export encountered errors on following paths:
        /
        /404
    at exportApp (/home/vavra/Projects/test/packages/client/node_modules/next/dist/export/index.js:25:1103)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async build (/home/vavra/Projects/test/packages/client/node_modules/next/dist/build/index.js:39:69)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After little bit of research I found out that Next.js 10 can not work with storybook in yarn workspaces.

treeview:
```
.
├── package.json
└── packages
    └── client
        ├── package.json
        ├── pages
        │   ├── api
        │   │   └── hello.js
        │   ├── _app.js
        │   └── index.js
        ├── public
        │   ├── favicon.ico
        │   └── vercel.svg
        ├── README.md
        └── styles
            ├── globals.css
            └── Home.module.css

```

root - package.json
```
{
  "name": "test-project",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "scripts": {},
  "dependencies": {},
  "devDependencies": {}
}
```

packages -> client (Next.js) - package.json:
```
{
  "name": "@test-project/next-js",
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "10.0.1",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.0.28",
    "@storybook/addon-essentials": "^6.0.28",
    "@storybook/addon-links": "^6.0.28",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/react": "^6.0.28"
  }
}
```

## To Reproduce

1. init yarn workspaces
2. create next.js app
3. install storybook
4. try to build next.js

## Expected behavior

It is possible to use storybook with yarn workspaces like in Next 9.

**Comment by timneutkens** [comment]
Tried to reproduce based on the reproduction provided but there's not much to work with in the reproduction steps. The build runs fine while following the reproduction steps:

```
Page                                                           Size     First Load JS
┌ ○ /                                                          282 B          62.4 kB
└ ○ /404                                                       3.42 kB        65.5 kB
+ First Load JS shared by all                                  62.1 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.008f4d.js  11.5 kB
  ├ chunks/framework.87b1eb.js                                 41.8 kB
  ├ chunks/main.cc0e6b.js                                      7.05 kB
  ├ chunks/pages/_app.369962.js                                1 kB
  └ chunks/webpack.e06743.js                                   751 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
```
