### ISSUE TITLE
Example[fast-refresh-demo] with DevDeps webpack5.4 started failed

### ISSUE THREAD

**Issue by heisonyee** [vercel/next.js#18830]
# Bug report

## Describe the bug
Example[fast-refresh-demo] with DevDeps webpack5.4 started failed

## Steps To Reproduce
1. Copy offical examples [fast-refresh-demo]
2. npm i -D webpack && npm i
3. run "npm run dev"
Error occurs as blow
```
heisonyee@MBP2017-Heison-275 fast-refresh-demo % npm run dev

> fast-refresh-demo@1.0.0 dev /Users/heisonyee/Labs/fast-refresh-demo
> next

ready - started server on http://localhost:3000
TypeError: Cannot read property 'tap' of undefined
    at /Users/heisonyee/Labs/fast-refresh-demo/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js:100:61
    at SyncHook.eval [as call] (eval at create (/Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/heisonyee/Labs/fast-refresh-demo/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fast-refresh-demo@1.0.0 dev: `next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fast-refresh-demo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/heisonyee/.npm/_logs/2020-11-05T09_29_16_133Z-debug.log
```

package.json showed as below:
```
{
  "name": "fast-refresh-demo",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "license": "MIT",
  "devDependencies": {
    "webpack": "^5.4.0"
  }
}
```

## System information

- OS: macOS
- Version of Next.js:  v10.0.1
- Version of Node.js: v14.15.0

**Comment by timneutkens** [comment]
If you want to use webpack 5 you have to use yarn resolutions. Next.js will then correctly apply the changes needed for webpack 5 support.

**Comment by heisonyee** [comment]
@timneutkens ,ok, thank your very much!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
