### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined - @next/react-refresh-utils

### ISSUE THREAD

**Issue by gregegan** [vercel/next.js#19081]
# Bug report

## Describe the bug

While trying to upgrade `@apollo/react-hooks` to `@apollo/client` it appears that I am now getting issues on `Cannot read property 'tap' of undefined`. This error occurs when running `next dev`

```
TypeError: Cannot read property 'tap' of undefined
    at /Users/gregegan/repos/the-landing/client/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js:100:61
    at SyncHook.eval [as call] (eval at create (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
```

## Screenshots

![image](https://user-images.githubusercontent.com/6665100/98877101-90225300-2434-11eb-9f5a-64b045d6de74.png)

```
gregegan@Gregs-MacBook-Pro client % npm run dev

> the-landing@0.1.0 dev
> next dev

Loaded env from /Users/gregegan/repos/the-landing/client/.env
ready - started server on http://localhost:3000
TypeError: Cannot read property 'tap' of undefined
    at /Users/gregegan/repos/the-landing/client/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js:100:61
    at SyncHook.eval [as call] (eval at create (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/gregegan/repos/the-landing/client/node_modules/next/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
npm ERR! code 1
npm ERR! path /Users/gregegan/repos/the-landing/client
npm ERR! command failed
npm ERR! command sh -c next dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gregegan/.npm/_logs/2020-11-11T23_40_58_534Z-debug.log
```

## System information

- OS: Mac
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 15.0.1]

## Additional context

Here is the package.json
https://gist.github.com/gregegan/91793416b5b2b70e17501497ee9a2839

Here is the package-lock.json
https://gist.github.com/gregegan/acbdf34718350b630dc30dbb4e9a3bfc

**Comment by chunghsien** [comment]
#Next.js v10.0.1 with webpack v5.4.0 bugs

$ cd <project_folder>node_modules/next/node_modules

#Modify package.json file`
#Replace "webpack-sources": "1.4.3" => "webpack-sources": "^1.4.3"
#Replace "pnp-webpack-plugin": "1.6.4" => "pnp-webpack-plugin": "^1.6.4"
#Replace "webpack": "4.44.2" => "webpack": "^4.44.2"
#Replace "webpack-sources": "1.4.3" => "webpack": "^1.4.3"

$ npm update`

**Comment by gregegan** [comment]
Thanks @chunghsien - Should this fix be going into the next.js repo rather then me forking it and updating it manually?

**Comment by chunghsien** [comment]
Yes, this error is because Next.js v10.0.1 uses webpack 4.x instead of version 5.

**Comment by gregegan** [comment]
Thank you @chunghsien.

Is someone already addressing this? Is this a known issue? Seems like it would be critical for @apollo/client to work with nextjs

**Comment by gregegan** [comment]
@chunghsien - does nextjs v10.0.1 have plans to support the latest webpack? Or should I stop trying to upgrade to the latest @apollo/client

**Comment by chunghsien** [comment]
I suggest using webpack 4.44.2.
