### ISSUE TITLE
With-apollo-and-redux - Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by LemonJuicer** [vercel/next.js#19093]
# Bug report

## Can't build or run page, throws error

Log:
```
C:\Users\Nizomidin\Desktop\with-apollo-and-redux>yarn build
yarn run v1.22.10
$ next build
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[  ==] info  - Generating static pages (2/4)
Error occurred prerendering page "/apollo". Read more: https://err.sh/next.js/prerender-error
Error: Unexpected token < in JSON at position 0
    at new ApolloError (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\errors\errors.cjs.js:31:28)
    at C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\core\core.cjs.js:1457:19
    at C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\utilities\utilities.cjs.js:936:69
    at new Promise (<anonymous>)
    at Object.error (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\utilities\utilities.cjs.js:936:21)
    at notifySubscription (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\zen-observable\lib\Observable.js:140:18)
    at onNotify (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.error (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\zen-observable\lib\Observable.js:240:7)
    at C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\utilities\utilities.cjs.js:924:68
    at Array.forEach (<anonymous>)

Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
Error: Unexpected token < in JSON at position 0
    at new ApolloError (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\errors\errors.cjs.js:31:28)
    at C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\core\core.cjs.js:1457:19
    at C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\utilities\utilities.cjs.js:936:69
    at new Promise (<anonymous>)
    at Object.error (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\utilities\utilities.cjs.js:936:21)
    at notifySubscription (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\zen-observable\lib\Observable.js:140:18)
    at onNotify (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\zen-observable\lib\Observable.js:179:3)
    at SubscriptionObserver.error (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\zen-observable\lib\Observable.js:240:7)
    at C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\@apollo\client\utilities\utilities.cjs.js:924:68
    at Array.forEach (<anonymous>)
info  - Generating static pages (4/4)

> Build error occurred
Error: Export encountered errors on following paths:
        /
        /apollo
    at exportApp (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\next\dist\export\index.js:25:1103)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async build (C:\Users\Nizomidin\Desktop\with-apollo-and-redux\node_modules\next\dist\build\index.js:39:69)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

1. Open terminal
2. Run `create-next-app with-apollo-and-redux -e with-apollo-and-redux`
3. Run `yarn build`

## Expected behavior

Builded page

## System information

- OS: Windows 10 - 2004 (build20185.1000)
- Version of Next.js: 10.0.1
- Version of Node.js: 14.15.0

**Comment by kobars** [comment]
I counter this issue even when running on dev mode

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
