### ISSUE TITLE
Cant run dev after upgrading to 10.0.1

### ISSUE THREAD

**Issue by PierreVelluet** [vercel/next.js#19147]
# Bug report
after upgrading next to 10.0.1, npm run dev throw this error : 

`> cars_pro@0.1.0 dev /Users/zotcar/Documents/Dev/cars_pro
> next dev

Loaded env from /Users/zotcar/Documents/Dev/cars_pro/.env
ready - started server on http://localhost:3000
warn  - Your project has both `sass` and `node-sass` installed as dependencies, but should only use one or the other. Please remove the `node-sass` dependency from your project.  Read more: https://err.sh/next.js/duplicate-sass
TypeError: Cannot read property 'concat' of undefined
    at Object.webpack (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next-transpile-modules/src/next-transpile-modules.js:102:73)
    at getBaseWebpackConfig (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/build/webpack-config.js:136:360)
    at async Promise.all (index 0)
    at async HotReloader.start (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/server/hot-reloader.js:14:2403)
    at async DevServer.prepare (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/server/next-dev-server.js:15:414)
    at async /Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/cli/next-dev.js:22:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cars_pro@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cars_pro@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zotcar/.npm/_logs/2020-11-13T14_09_51_774Z-debug.log`

## Describe the bug
I just upgraded to next js 10.0.1 and can no longer start my app with npm run dev.

What i tried : delete node_modules, package.lock, then run npm install and npm run dev.

## Expected behavior

Project start on localhost:3000

## System information

- OS: [MacOS 10.13.6]
- Browser  [chrome]
- Version of Next.js: [10.0.1]
- Version of Node.js: [17.0.1]

**Comment by kachkaev** [comment]
From your error log:

> Your project has both sass and node-sass installed as dependencies, but should only use one or the other. Please remove the node-sass dependency from your project. Read more: https://err.sh/next.js/duplicate-sass

**Comment by PierreVelluet** [comment]
@kachkaev i indeed removed node-sass dependency from my project, but i still have the same error message when i npm run dev :
`> cars_pro@0.1.0 dev /Users/zotcar/Documents/Dev/cars_pro
> next dev

Loaded env from /Users/zotcar/Documents/Dev/cars_pro/.env
ready - started server on http://localhost:3000
TypeError: Cannot read property 'concat' of undefined
    at Object.webpack (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next-transpile-modules/src/next-transpile-modules.js:102:73)
    at getBaseWebpackConfig (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/build/webpack-config.js:136:360)
    at async Promise.all (index 0)
    at async HotReloader.start (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/server/hot-reloader.js:14:2403)
    at async DevServer.prepare (/Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/server/next-dev-server.js:15:414)
    at async /Users/zotcar/Documents/Dev/cars_pro/node_modules/next/dist/cli/next-dev.js:22:1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cars_pro@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cars_pro@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zotcar/.npm/_logs/2020-11-16T05_32_12_352Z-debug.log`

I ran => rm -rf node_modules && rm ./package-lock.json && npm install
I also restarted my computer and MAMP servers.

Any suggestion ?
