### ISSUE TITLE
example with-tailwindcss not working

### ISSUE THREAD

**Issue by fabmade** [vercel/next.js#19408]
i tried to install the current version of this example but i have a lot of errors if i start it:

`
npx create-next-app --example with-tailwindcss with-tailwindcss-app
cd with-tailwindcss-app
npm run dev

Output:

npm run dev

> with-tailwindcss@1.0.0 dev /home/projects/with-tailwindcss-app
> next

ready - started server on http://localhost:3000
error - ./styles/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/index.css)
TypeError: Object.entries(...).flatMap is not a function
    at Array.forEach (<anonymous>)
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./styles/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/index.css)
TypeError: getProcessedPlugins is not a function
{ Error: Cannot find module '/home/with-tailwindcss-app/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at loadComponents (/home/with-tailwindcss-app/node_modules/next/dist/next-server/server/load-components.js:1:1035)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
error - ./styles/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/index.css)
TypeError: getProcessedPlugins is not a function

`

**Comment by fabmade** [comment]
Problem was a to old node version, i updated it, delete the modules and install it again. After that it worked!

**Comment by larrybahr** [comment]
Thanks @fabmade! Following a tutorial and this saved me a lot of trouble shooting. Updating from node 10.16.2 to 14.7.0 and re-installing node_modules fixed the issue

**Comment by MelMacaluso** [comment]
Basically use node version > 14 and delete / reinstall node_modules

**Comment by tafelito** [comment]
trying to run an example con codesanbox and I'm getting the same error. I added node as a dependency but still getting the same error. Codesandbox uses node v10. Is there anyway to force nextjs to use local node instead?

**Comment by brahmendernchary** [comment]
i solve this error install node 14 version

**Comment by kodcanlisi** [comment]
My old node version was 10.15.3 and i upgrade to 14.6.0 and problem was solved

**Comment by krupupakku** [comment]
I solved installing node 11, deleting node_modules and re-creating it

**Comment by santoshge-nirva** [comment]
Note working with node 16

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
