### ISSUE TITLE
Stopped compiling in dev and prod

### ISSUE THREAD

**Issue by dortonway** [vercel/next.js#19505]
# Next.js stopped compiling in dev and prod

## Description

I've been working with a new recent version of Next.js for a few days. Everything was working, but now during the writing of the adapter for next-auth, I got a few strange errors with models loading via require and then got these strange compilation errors.

When I do **npm run dev**:

```
> server@0.1.0 dev /bank/dev/socialcomm/server
> next dev

Loaded env from /bank/dev/socialcomm/server/.env
ready - started server on http://localhost:3000
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /api/auth/[...nextauth]
wait  - compiling...
Failed to parse source map: TypeError: Cannot read property 'start' of undefined
    at getNotFoundError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:810)
    at getModuleBuildError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:568
    at Array.map (<anonymous>)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:482
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:17)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
    at /bank/dev/socialcomm/server/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
Failed to parse source map: TypeError: Cannot read property 'start' of undefined
    at getNotFoundError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:810)
    at getModuleBuildError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:568
    at Array.map (<anonymous>)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:482
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:17)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
    at /bank/dev/socialcomm/server/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
error - ./node_modules/abort-controller/polyfill.mjs
Can't import the named export 'AbortController' from non EcmaScript module (only default export is available)
wait  - compiling...
(node:1226585) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/initrd.img'
(node:1226585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1226585) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1226585) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/initrd.img.old'
(node:1226585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:1226585) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz'
(node:1226585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:1226585) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/vmlinuz.old'
(node:1226585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
Failed to parse source map: TypeError: Cannot read property 'start' of undefined
    at getNotFoundError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:810)
    at getModuleBuildError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:568
    at Array.map (<anonymous>)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:482
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:17)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
    at /bank/dev/socialcomm/server/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
Failed to parse source map: TypeError: Cannot read property 'start' of undefined
    at getNotFoundError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:1:810)
    at getModuleBuildError (/bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:1:2479)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:568
    at Array.map (<anonymous>)
    at /bank/dev/socialcomm/server/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:1:482
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:17)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
    at /bank/dev/socialcomm/server/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/bank/dev/socialcomm/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/bank/dev/socialcomm/server/node_modules/tapable/lib/Hook.js:154:20)
error - ./node_modules/abort-controller/polyfill.mjs
Can't import the named export 'AbortController' from non EcmaScript module (only default export is available)
event - compiled successfully
^C
```
When I do **npm run build**:
```
> server@0.1.0 build /bank/dev/socialcomm/server
> next build

Loaded env from /bank/dev/socialcomm/server/.env
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'https://unpkg.com/yargs-parser@19.0.0/browser.js' in '/bank/dev/socialcomm/server/node_modules/yargs/lib/platform-shims'


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/bank/dev/socialcomm/server/node_modules/next/dist/build/index.js:15:918)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/i/.npm/_logs/2020-11-25T01_09_07_896Z-debug.log
i@w:/bank/dev/socialcomm/server$ 
```

## Expected behavior

I expect the project to be compiled so I could continue developing.

## System information

- OS: Ubuntu 20.04.1
- Browser (if applies) chrome
- Version of Next.js: 10.0.2
- Version of Node.js: 12.18.0

**Comment by marcmaceira** [comment]
Also getting the error in production.
```
Failed to compile.
--
Error: Expected an opening square bracket.
| > Build error occurred
| Error: > Build failed because of webpack errors
| at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)
```

Version of Next.js: 10.0.3
Host: Vercel

**Comment by jamesmosier** [comment]
Hi! Could you please provide a complete reproduction of this issue including a repository? Thanks!

**Comment by marcmaceira** [comment]
@jamesmosier In my case, I fixed the issue. After upgrading from Next.js 10.0.1 to 10.0.3 I had to update my postcss config and tailwindcss config to match the one in the updated Next.js documentation and was able to deploy successfully.

**Comment by dortonway** [comment]
It seems like the problem was that I had some modules in CommonJS format. I've changed them to ES6 imports/exports.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
