### ISSUE TITLE
Page with url `/developments` causes issues with `stripNextDataPath()`

### ISSUE THREAD

**Issue by berndartmueller** [vercel/next.js#19520]
# Bug report

## Describe the bug

A page with URL `/developments` causes a server error when rendered.

## To Reproduce

Repl.it:
https://repl.it/@berndartmueller/nextjs10xx-stripNextDataPath-bug

1. Click on "CLICK HERE TO SEE ERROR" link
2. Error `TypeError: Cannot read property 'toLowerCase' of undefined` is thrown on SSR in terminal

OR 

1. npx create-next-app --example i18n-routing i18n-app
2. `cd i18n-app/pages`
3. `mkdir developments`
4. Create index.js with following demo content (does not really matter):
```
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function DevelopmentsPage(props) {
  const router = useRouter()
  const { defaultLocale } = router

  return (
    <div>
      <h1>getStaticProps page</h1>
      <p>Current locale: {props.locale}</p>
      <p>Default locale: {defaultLocale}</p>
      <p>Configured locales: {JSON.stringify(props.locales)}</p>

      <Link href="/gsp/first">
        <a>To dynamic getStaticProps page</a>
      </Link>
      <br />

      <Link href="/gssp">
        <a>To getServerSideProps page</a>
      </Link>
      <br />

      <Link href="/">
        <a>To index page</a>
      </Link>
      <br />
    </div>
  )
}

export const getStaticProps = ({ locale, locales }) => {
  return {
    props: {
      locale,
      locales,
    },
  }
}
```

4. `yarn dev`
5. Navigate in browser to /developments page
6. Error on server:

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:3:91
    at Array.some (<anonymous>)
    at normalizeLocalePath (PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/lib/i18n/normalize-locale-path.js:3:57)
    at stripNextDataPath (PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/server/next-server.js:84:555)
    at DevServer.renderToHTMLWithComponents (PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/server/next-server.js:86:35)
    at DevServer.renderToHTML (PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/server/next-server.js:124:484)
    at async DevServer.renderToHTML (PROJECT_PATH/i18n-app/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/server/next-server.js:71:236)
    at async Object.fn (PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/server/next-server.js:46:704)
    at async Router.execute (PROJECT_PATH/i18n-app/node_modules/next/dist/next-server/server/router.js:24:67)
```

## Expected behavior

Successfully rendered /developments page

## System information

- OS: macOS
- Version of Next.js: 10.0.4 (<=10.0.4)
- Version of Node.js: 12.19.0
- Deployment: next dev

## Additional context

This line causes the issue: https://github.com/vercel/next.js/blob/f4bf8a4696af6f9a0b64636205356ba207fb1ea9/packages/next/next-server/server/next-server.ts#L1315

It's because this custom created page `/developments` causes an issue when the string is split by the `this.buildId` (="development")

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
