### ISSUE TITLE
Next/Link with Preact and Typescript fails to build

### ISSUE THREAD

**Issue by rschristian** [vercel/next.js#19645]
# Bug report

## Describe the bug

It seems that the typechecker or something involved in the process of building a TS NextJS app is overly strict with the definitions. I'm not super familiar with the NextJS source so take that guess with a huge grain of salt.

As the title says, I am a Preact user, trying to use NextJS with Preact and TS. I bootstrapped the project using the [next-plugin-preact](https://github.com/preactjs/next-plugin-preact/) so I should have everything correctly set up and aliased (hopefully). 

So the issue begins with using `Link` from `next/link`. The type definitions apparently don't line up for Preact, which is common enough of an occurrence and usually just means an overwrite of the type is necessary. No big deal. So I created the following definition: 

```
declare module 'next/link' {
    import { ReactNode } from 'react';
    import { UrlObject } from 'url';
    type Url = string | UrlObject;

    interface LinkProps {
        href: Url;
        as?: Url;
        replace?: boolean;
        scroll?: boolean;
        shallow?: boolean;
        passHref?: boolean;
        prefetch?: boolean;
    }
    function Link(props: LinkProps & { children?: ReactNode }): any;
    export = Link;
}
```

Nothing particularly fancy, just copying the prop types that didn't cause any issues and having it return `any` as that should get around the issue. I believe I've typed this correctly, let me know if something is wrong. This satisfies TS as far as I can tell.

However, after doing this, I cannot build the project properly. I run into the following issue:

```
yarn run v1.22.10
$ next build
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[==  ] info  - Generating static pages (0/3)
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
undefined
[=== ] info  - Generating static pages (0/3)
Error occurred prerendering page "/login". Read more: https://err.sh/next.js/prerender-error
undefined
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
	/
	/login
    at exportApp (/home/xxx/Projects/github-notes/node_modules/next/dist/export/index.js:30:1103)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async build (/home/xxx/Projects/github-notes/node_modules/next/dist/build/index.js:39:69)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have a `Header` component used in both of those pages, and it contains the usage of `Link`. If I comment out that usage of `Link`, everything builds and is peachy. Using it causes this issue which isn't exactly clear.

`Link` does work just fine in JS as the [usingPreact example project](https://github.com/vercel/next.js/tree/canary/examples/using-preact) can show. So this seems to just be limited to TS and not an underlying problem with Preact vs React. 

## To Reproduce

1. Go to https://codesandbox.io/s/dreamy-turing-se6wc
2. Try to run `yarn build` in a terminal
3. It should fail
4. Go to `src/components/Header/index.tsx`
5. Comment out the usage of `<Link>`
6. Try to build again. It should succeed

Not a fan of codesandbox so some items may be weird there, not sure I'm using it 100% properly. Sorry in advance if I haven't set something correctly but you should be able to follow the steps.

## Expected behavior

The application should build even if `<Link>` is used.

## Screenshots

N/A I believe, just terminal output messages that have been mentioned above.

## System information

- OS: Manjaro Linux
- Browser (if applies): N/A
- Version of Next.js: 10.0.3
- Version of Node.js: 14.15.0
- Deployment: N/A? Just using `next build` and `next dev`

## Additional context

Not 100% related, but I am using a library called Oceanwind, which is sort of like Tailwind. It throws some warnings in the demo as I normally used a locally linked version of the lib while I'm waiting for a new update to be released. These warnings look like `No translation for "bg-opacity-75" t (/sandbox/node_modules/preact-render-to-string/dist/index.js:1:2567)` and can be ignored. They're not a problem.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
