### ISSUE TITLE
Clear up error message when production build is missing during `next export`

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#19788]
From @jlongster:

**Problem #3: static export**

I ran:

```jsx
$ next export
```

I got this error:

```jsx
Error: ENOENT: no such file or directory, open '/Users/james/tmp/devii/.next/BUILD_ID'
    at Object.openSync (fs.js:440:3)
    at readFileSync (fs.js:342:35)
    at exportApp (/Users/james/tmp/devii/node_modules/next/dist/export/index.js:2:919) {
```

Again you need to do `next build` first. Not clear at all.

When the export finally worked I got this output:

```jsx
info  - using build directory: /Users/james/tmp/devii/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
info  - Launching 7 workers
info  - Copying "public" directory
info  - undefined (2/2)
Export successful
```

It doesn't tell me where it put the static export, and the `undefined` is off-putting ([tweet](https://twitter.com/jlongster/status/1331721963081961472)). Turns out it puts it in the `out` folder

--- 

Notes from me:

Had a look at this and it turns out there's an edge case where it would throw this error when there is a `.next` folder but no production build (`BUILD_ID` missing).

The `undefined` part has been solved already in the latest version of Next.js (as replied on the tweet too).

The location not being available can be easily fixed 👍 Added it to #19777 as well

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
