### ISSUE TITLE
API JS absolute imports not working when also using python

### ISSUE THREAD

**Issue by alex-cory** [vercel/next.js#20401]
I've seen the [documentation](https://vercel.com/docs/runtimes#advanced-usage/advanced-python-usage) on how to use python and I noticed it's in beta. Does it not support absolute imports when moving the `/pages/api` directory to `/api`?

I tried a few different approaches to try and make it work.
1. my original way
```js
// jsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/my-alias/*": ["my-alias/*"]
    }
  }
}
```
2. tried adding the following to my `package.json`, then running `yarn` to add them to my `node_modules`
```js
// package.json
{
  "dependencies": {
    "my-alias": "file: ./my-alias"
  }
}
```
which gave me an error on the server for using `imports`
```
error - ./node_modules/libs/index.js 91:206
Module parse failed: Unexpected token (91:206)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // this isSafari sometimes doesn't work :/
> export const isSafari = /constructor/i.test(isBrowser && window.HTMLElement) || (function (p) { return p.toString() === '[object SafariRemoteNotification]' })(isBrowser && (!window.safari || (typeof window?.safari !== 'undefined' && window?.safari.pushNotification)))
| export const isMobileSafari = isSafari && isMobile
| export const canShowAndroid = isMobile && isAndroid
/Users/alex/code/proj/node_modules/libs/index.js:1
import { createContext } from 'react'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1172:16)
    at Module._compile (internal/modules/cjs/loader.js:1220:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at eval (webpack-internal:///libs:1:18)
    at Object.libs (/Users/alex/code/proj/.next/server/pages/_app.js:634:1)
```
3. tried updating `next.config.js` via this [so answer](https://stackoverflow.com/a/59542342/2782583) but it didn't do anything, same error saying no module found.
```js
const path = require('path')

module.exports = {
  webpack: config => {
    config.resolve.modules.push(path.resolve('./'))
    return config
  }
}
```
4. tried [`babel-plugin-module-resolver`](https://www.npmjs.com/package/babel-plugin-module-resolver) from this [so answer](https://stackoverflow.com/a/52909518/2782583) but it gave me errors about can't use `imports`, so I added `@babel/plugin-transform-modules-commonjs` to `.babelrc` which then gave me
```js
error - Error: Cannot create styled-component for component: undefined.
    at N (/Users/alex/code/proj/node_modules/styled-components/dist/styled-components.cjs.js:1:5450)
    at e (/Users/alex/code/proj/node_modules/styled-components/dist/styled-components.cjs.js:1:20357)
    at je (/Users/alex/code/proj/node_modules/styled-components/dist/styled-components.cjs.js:1:20594)
    at eval (webpack-internal:///./components/AddCreditCardSheet.js:356:45)
    at Module../components/AddCreditCardSheet.js (/Users/alex/code/proj/.next/server/pages/_app.js:115:1)
    at __webpack_require__ (/Users/alex/code/proj/.next/server/pages/_app.js:23:31)
    at eval (webpack-internal:///./pages/_app.js:47:50)
    at Module../pages/_app.js (/Users/alex/code/proj/.next/server/pages/_app.js:412:1)
    at __webpack_require__ (/Users/alex/code/proj/.next/server/pages/_app.js:23:31)
    at Object.0 (/Users/alex/code/proj/.next/server/pages/_app.js:470:18)
```
5. so then I tried adding `type: "module"` to `package.json` which gave me this
```js
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/alex/code/proj/next.config.js
require() of ES modules is not supported.
require() of /Users/alex/code/proj/next.config.js from /Users/alex/code/proj/node_modules/next/dist/next-server/server/config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename next.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/alex/code/proj/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1273:13)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at loadConfig (/Users/alex/code/proj/node_modules/next/dist/next-server/server/config.js:7:100)
    at new Server (/Users/alex/code/proj/node_modules/next/dist/next-server/server/next-server.js:1:4199)
    at new DevServer (/Users/alex/code/proj/node_modules/next/dist/server/next-dev-server.js:1:2964)
    at createServer (/Users/alex/code/proj/node_modules/next/dist/server/next.js:2:607)
    at start (/Users/alex/code/proj/node_modules/next/dist/server/lib/start-server.js:1:323) {
  code: 'ERR_REQUIRE_ESM'
}
```
Not quite sure what to do. I'll give it another stab tomorrow, but would suck to have to import libs from apis like `../../../ugh.js` everywhere.
@Timer

**Comment by jamesmosier** [comment]
Next API routes must be contained in the `pages/api` folder, so anything outside of that would be out of Next's control. The documentation you referenced is for non-Next projects deployed to Vercel I believe.
