### ISSUE TITLE
Improve stacktrace for wrong webpack 5 version

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#20576]
```
❯ yarn next build                                                                                                  ✘ 1 
yarn run v1.22.5
$ /Users/joe/Documents/Development/Work/zeit/front/node_modules/.bin/next build
(node:45037) UnhandledPromiseRejectionWarning: Error: webpack 5 version must be greater than v5.11.1 to work properly with Next.js, please upgrade to continue!
See more info here: https://err.sh/next.js/invalid-webpack-5-version
    at Object.<anonymous> (/Users/joe/Documents/Development/Work/zeit/front/node_modules/next/dist/build/webpack-config.js:1:3644)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/joe/Documents/Development/Work/zeit/front/node_modules/next/dist/build/index.js:1:2150)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/joe/Documents/Development/Work/zeit/front/node_modules/next/dist/cli/next-build.js:2:287)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
(node:45037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 1.51s.
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
