### ISSUE TITLE
[examples, react-intl] npm run build fails

### ISSUE THREAD

**Issue by nbouvrette** [vercel/next.js#20713]
# Bug report
I was trying to run this example (on Windows) and when I try to build it, the build fails.

## Describe the bug
Following the `README.md` instructions, when running `npm run build` I get the following result:

```
C:\Projects\with-react-intl-app>npm run build

> with-react-intl@1.0.0 build C:\Projects\with-react-intl-app
> npm run extract:i18n && npm run compile:i18n && next build && tsc -p tsconfig.server.json


> with-react-intl@1.0.0 extract:i18n C:\Projects\with-react-intl-app
> formatjs extract '{pages,components}/*.{js,ts,tsx}' --format simple --id-interpolation-pattern '[sha512:contenthash:base64:6]' --out-file lang/en.json


> with-react-intl@1.0.0 compile:i18n C:\Projects\with-react-intl-app
> formatjs compile-folder --ast --format simple lang/ compiled-lang/

Error: No JSON file found in lang/
    at Object.<anonymous> (C:\Projects\with-react-intl-app\node_modules\@formatjs\cli\src\cli.js:113:39)
    at step (C:\Projects\with-react-intl-app\node_modules\tslib\tslib.js:140:27)
    at Object.next (C:\Projects\with-react-intl-app\node_modules\tslib\tslib.js:121:57)
    at C:\Projects\with-react-intl-app\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Projects\with-react-intl-app\node_modules\tslib\tslib.js:110:16)
    at Command.<anonymous> (C:\Projects\with-react-intl-app\node_modules\@formatjs\cli\src\cli.js:106:77)
    at Command.listener [as _actionHandler] (C:\Projects\with-react-intl-app\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\Projects\with-react-intl-app\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (C:\Projects\with-react-intl-app\node_modules\commander\index.js:953:18)
```

I also noticed that it deletes all the strings from the `lang/en.json` file.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. run `npx create-next-app --example with-react-intl with-react-intl-app`
2. run `npm run build`
3. See error

## Expected behavior

I would expect the build to work and to be able to use the example.

## System information

- OS: Windows 10
- Version of Next.js: 10.0.4
- Version of Node.js: 14.15

## Additional context

Also, might be good to update packages on this example. I tried that too but it did not resolve the issue.

**Comment by kaykdm** [comment]
I created PR to fix this.

**Comment by mhhegazy** [comment]
remve last slash from `lang/` in command 
```js
formatjs compile-folder --ast --format simple lang/ compiled-lang/
```
to be:
```
formatjs compile-folder --ast --format simple lang compiled-lang/
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
