### ISSUE TITLE
When i'm using the image component the image is rendered perfectly on the browser but in my console it throws a module not found error for sharp

### ISSUE THREAD

**Issue by NewtonBishal** [vercel/next.js#20724]
Error: Cannot find module 'sharp'
Require stack:
- C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\next-server\server\image-optimizer.js
- C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\next-server\server\next-server.js
- C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\server\next.js
- C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\server\lib\start-server.js
- C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\cli\next-dev.js
- C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\bin\next

Learn more: https://err.sh/next.js/install-sharp
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at imageOptimizer (C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\next-server\server\image-optimizer.js:4:7)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Router.execute (C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\next-server\server\router.js:23:67)
    at async DevServer.run (C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\next-server\server\next-server.js:66:1042)
    at async DevServer.handleRequest (C:\Users\BeN\Desktop\he\my-app\node_modules\next\dist\next-server\server\next-server.js:34:1081) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\BeN\\Desktop\\he\\my-app\\node_modules\\next\\dist\\next-server\\server\\image-optimizer.js',
    'C:\\Users\\BeN\\Desktop\\he\\my-app\\node_modules\\next\\dist\\next-server\\server\\next-server.js',
    'C:\\Users\\BeN\\Desktop\\he\\my-app\\node_modules\\next\\dist\\server\\next.js',
    'C:\\Users\\BeN\\Desktop\\he\\my-app\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'C:\\Users\\BeN\\Desktop\\he\\my-app\\node_modules\\next\\dist\\cli\\next-dev.js',
    'C:\\Users\\BeN\\Desktop\\he\\my-app\\node_modules\\next\\dist\\bin\\next'
  ]
}

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
