### ISSUE TITLE
blog-starter-typescript: PostCSS plugin postcss-nested requires PostCSS 8

### ISSUE THREAD

**Issue by angristan** [vercel/next.js#20812]
**What example does this report relate to?**

blog-starter-typescript

**What version of Next.js are you using?**

10.0.4

**What version of Node.js are you using?**

14.15.4

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next build / next dev

**Describe the Bug**

```
➜  blog-starter-typescript-app git:(main) yarn build
yarn run v1.22.5
$ next build
info  - Creating an optimized production build
Failed to compile.

./styles/index.css
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users


> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/stanislas/lab/blog-starter-typescript-app/node_modules/next/dist/build/index.js:15:918
    at async /Users/stanislas/lab/blog-starter-typescript-app/node_modules/next/dist/build/tracer.js:1:525
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected Behavior**

Working example

**To Reproduce**

```
npx create-next-app --example blog-starter-typescript blog-starter-typescript-app
cd blog-starter-typescript-app
yarn build
```

**Comment by timneutkens** [comment]
https://github.com/vercel/next.js/pull/20813#issuecomment-766919391

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
