### ISSUE TITLE
Building fails with webpack problem

### ISSUE THREAD

**Issue by seven-deuce** [vercel/next.js#21008]
**What version of Next.js are you using?**

10.0.4

**What version of Node.js are you using?**

12.18

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows 10

**How are you deploying your application?**

Other platform

**Describe the Bug**

When I want to build my project, it fails with webpack error. But there is no issue running it in dev mode. 
Here is the complete log:
-------------------

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle universities@0.1.0~prebuild: universities@0.1.0
6 info lifecycle universities@0.1.0~build: universities@0.1.0
7 verbose lifecycle universities@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle universities@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\code\GeorgianUniversityDima\app\node_modules\.bin;C:\Users\Shaman\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Shaman\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\PuTTY;C:\Program Files\nodejs;C:\Users\Shaman\AppData\Local\Microsoft\WindowsApps;C:\Users\Shaman\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle universities@0.1.0~build: CWD: C:\code\GeorgianUniversityDima\app
10 silly lifecycle universities@0.1.0~build: Args: [ '/d /s /c', 'next build' ]
11 silly lifecycle universities@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle universities@0.1.0~build: Failed to exec build script
13 verbose stack Error: universities@0.1.0 build: `next build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid universities@0.1.0
15 verbose cwd C:\code\GeorgianUniversityDima\app
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error universities@0.1.0 build: `next build`
22 error Exit status 1
23 error Failed at the universities@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Expected Behavior**

The building to complete successfully. At least give me a clue where to look for possible issues.

**To Reproduce**

If this information is not enough, let me know and I will create a repo and give you access to see it.
many thanks

**Comment by seven-deuce** [comment]
problem fixed!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
