### ISSUE TITLE
Storybook: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Sharcoux** [vercel/next.js#21031]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.20.0

**What browser are you using?**

Whatever

**What operating system are you using?**

Ubuntu 20.04

**How are you deploying your application?**

npm run storybook

**Describe the Bug**

When using `npm run storybook` after moving to next, I get:

```
ERR! TypeError: Cannot read property 'length' of undefined
ERR!     at getBaseWebpackConfig (/home/fbillioud/Projects/cantoo-web/node_modules/next/dist/build/webpack-config.js:8:570)
ERR!     at Object.webpackFinal (/home/fbillioud/Projects/cantoo-web/.storybook/main.js:20:35)
```

Here is my config

```javascript
const path = require('path');
const { PHASE_PRODUCTION_BUILD } = require('next/constants')
const { findPagesDir } = require('next/dist/lib/find-pages-dir')
const loadConfig = require('next/dist/next-server/server/config').default
const getWebpackConfig = require('next/dist/build/webpack-config').default

const CWD = process.cwd()


module.exports = {
  addons: ['@storybook/addon-storysource'],
  stories: ['../stories/**/*.stories.js'],
  webpackFinal,
};

// extracted from next-plugin-storybook
async function webpackFinal(config) {
  const pagesDir = findPagesDir(CWD)
  const nextConfig = await loadConfig(PHASE_PRODUCTION_BUILD, CWD)
  const nextWebpackConfig = await getWebpackConfig(CWD, {
    pagesDir,
    entrypoints: {},
    isServer: false,
    target: 'server',
    config: nextConfig,
    buildId: 'storybook',
  })

  config.plugins = [...config.plugins, ...nextWebpackConfig.plugins]

  config.resolve = {
    ...config.resolve,
    ...nextWebpackConfig.resolve,
  }

  config.module.rules = [
    ...config.module.rules,
    ...nextWebpackConfig.module.rules.map(rule => {
      // we need to resolve next-babel-loader since it's not available
      // relative with storybook's config
      if (rule.use && rule.use.loader === 'next-babel-loader') {
        rule.use.loader = require.resolve(
          'next/dist/build/webpack/loaders/next-babel-loader'
        )
      }
      return rule
    }),
  ]

  return config
}
```

**Expected Behavior**

Storybook should run

**To Reproduce**

A project with next and storybook installed using this config should reproduce the issue:

```javascript
const path = require('path');
const { PHASE_PRODUCTION_BUILD } = require('next/constants')
const { findPagesDir } = require('next/dist/lib/find-pages-dir')
const loadConfig = require('next/dist/next-server/server/config').default
const getWebpackConfig = require('next/dist/build/webpack-config').default

const CWD = process.cwd()


module.exports = {
  addons: ['@storybook/addon-storysource'],
  stories: ['../stories/**/*.stories.js'],
  webpackFinal,
};

// extracted from next-plugin-storybook
async function webpackFinal(config) {
  const pagesDir = findPagesDir(CWD)
  const nextConfig = await loadConfig(PHASE_PRODUCTION_BUILD, CWD)
  const nextWebpackConfig = await getWebpackConfig(CWD, {
    pagesDir,
    entrypoints: {},
    isServer: false,
    target: 'server',
    config: nextConfig,
    buildId: 'storybook',
  })

  config.plugins = [...config.plugins, ...nextWebpackConfig.plugins]

  config.resolve = {
    ...config.resolve,
    ...nextWebpackConfig.resolve,
  }

  config.module.rules = [
    ...config.module.rules,
    ...nextWebpackConfig.module.rules.map(rule => {
      // we need to resolve next-babel-loader since it's not available
      // relative with storybook's config
      if (rule.use && rule.use.loader === 'next-babel-loader') {
        rule.use.loader = require.resolve(
          'next/dist/build/webpack/loaders/next-babel-loader'
        )
      }
      return rule
    }),
  ]

  return config
}
```

**Comment by timneutkens** [comment]
You're using Next.js internals which is not supported.

**Comment by williaster** [comment]
@Sharcoux  I think you're not supplying a full webpack config shape, I had a similar issue and after looking at types more closely this worked for me

```js
const base = await getWebpackConfig(__dirname, {
  config: {
    devIndicators: {},
    distDir: happoTmpDir,
    experimental: { plugins: [] },
    future: {},
    env: {},
    // pageExtensions: [],
    sassOptions: {},
    ...nextConfig,
  },
  rewrites: [],
  entrypoints: {},
  pagesDir: findPagesDir(process.cwd()),
});
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
