### ISSUE TITLE
Failed to launch editor.

### ISSUE THREAD

**Issue by youngvform** [vercel/next.js#21330]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.16.2

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

local next dev

**Describe the Bug**

If an app crashes in development after set up REACT_EDITOR=code in .env.local, i will see an error overlay with clickable file name and stack trace. 
When i click on it, it won't open an editor and throw an error like this
```
Failed to launch editor: TypeError: editor.toLowerCase is not a function
    at Object.launchEditor (/node_modules/@next/react-dev-overlay/lib/internal/helpers/launchEditor.js:310:16)
    at /node_modules/@next/react-dev-overlay/lib/middleware.js:320:61
    at step (/node_modules/@next/react-dev-overlay/lib/middleware.js:33:23)
    at Object.next (/node_modules/@next/react-dev-overlay/lib/middleware.js:14:53)
    at fulfilled (/node_modules/@next/react-dev-overlay/lib/middleware.js:5:58)
```

I think this line https://github.com/vercel/next.js/blob/0bd175264b000895cccd75f4499bdf55daad4882/packages/react-dev-overlay/src/internal/helpers/launchEditor.ts#L216 return string array and toLowerCase is undefined in string array so throw error.

**Expected Behavior**

When i click an error overlay, it open an editor that i set up in env file.

**To Reproduce**

1. Set up REACT_EDITOR in .env.local file
2. Crash an app and click file name on error overlay

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
