### ISSUE TITLE
ISG not working properly when page route has spaces and deployed through Vercel

### ISSUE THREAD

**Issue by thiniulian** [vercel/next.js#21354]
**What version of Next.js are you using?**

10.0.4

**What version of Node.js are you using?**

14.3.0

**What browser are you using?**

not relevant

**What operating system are you using?**

vercel's os

**How are you deploying your application?**

vercel

**Describe the Bug**

The incremental static generation is not working if the page route has white spaces in the name, like `/news/head to head`.
Looking in vercel function logs we can see that the revalidation request fails with the error.

```
ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"Request path contains unescaped characters","code":"ERR_UNESCAPED_CHARACTERS","stack":["TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters","    at new ClientRequest (_http_client.js:148:13)","    at Object.request (http.js:46:10)","    at /var/task/now__bridge.js:125:32","    at new Promise (<anonymous>)","    at Bridge.launcher (/var/task/now__bridge.js:123:16)"]}
```

The funny thing is that at build time works just fine and loading the page afterwards works fine  as well, but remains stale.
The actual error is coming from the `request` function from the `http` module which is used in the vercel node_bridge, but the actual request seems to start from next.js.

**Expected Behavior**

Revalidation should work as the build time process and revalidate the page.

**To Reproduce**

1. Deploy https://github.com/thiniulian/nextjs-whitespace-bug to vercel
2. Access the page `<deployment>/page one`
3. Refresh the page a few times
4. Observe the date not changing after all the refreshes
5. Go to functions log in vercel dashboard, refresh the deployed page and see the error

![image](https://user-images.githubusercontent.com/15338310/105088876-10081180-5aa5-11eb-865c-58d93c95bac5.png)

**Comment by illusionconnect** [comment]
This is still relevant with the current version 11.0

**Comment by seeARMS** [comment]
This is happening to me with v12, but it's occurring with Mandarin characters (for example, this is a URL path: /橘子哥的故事). This is the error:

![image](https://user-images.githubusercontent.com/3957773/141702703-56740eb3-c1b6-4d0c-97ec-24ddf0415836.png)

**Comment by ijjk** [comment]
Hi, the initial issue is working now, example deployment using the provided reproduction available here https://nextjs-whitespace-bug-bkf88xwjj-ijjk-testing.vercel.app/page%20one

**Comment by ijjk** [comment]
@seeARMS your error looks unrelated to Next.js and seems to be caused by a request being done with `axios` with an unencoded path

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
