### ISSUE TITLE
Failed to proxy/rewrite self-signed https url

### ISSUE THREAD

**Issue by oyzhen** [vercel/next.js#21537]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.20.0

**What browser are you using?**

Edge 88.0.705.50

**What operating system are you using?**

MacOS 11.0.1

**How are you deploying your application?**

next dev

**Describe the Bug**

Setting environment variable NODE_TLS_REJECT_UNAUTHORIZED=0 does nothing to do with the "rewrites" configuration of next.config.js

**Expected Behavior**

When NODE_TLS_REJECT_UNAUTHORIZED=0 is set, proxies should not be rejected by "self signed certificate"

**To Reproduce**

1. Set rewrites to proxy an self-signed certificated url
```js
// next.config.js
module.exports = {
    // ...
    rewrites: () => [
        {
            source: '/SOME_PATH/:path*',
            destination: 'https://self-signed-url:port/SOME_PATH/:path*',
            basePath: false,
        }
    ]
    //...
}
```
2. Start next dev 
```
export NODE_TLS_REJECT_UNAUTHORIZED=0 && npx next dev
```

3. Visit `http://localhost:3000/SOME_PATH/` and error occurs:
Error occurred proxying https://self-signed-url:port/SOME_PATH/ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}

![image](https://user-images.githubusercontent.com/52534412/105807949-dde53b00-5fe1-11eb-9f2d-c0f899fa530e.png)
![image](https://user-images.githubusercontent.com/52534412/105807963-e3db1c00-5fe1-11eb-9275-a7cea30e8b51.png)

**Comment by timneutkens** [comment]
This is expected behavior. It's a security bad practice to use self-signed certificates for handling https as well.

**Comment by illiakovalenko** [comment]
@timneutkens In this case we can't have any workarounds with this issue? I have case when I use
<script /> tag which should be loaded from localhost:3000, and I want rewrite it to `https://myhost.com' (I need to request script from localhost:3000 because of visitor identification).
So I used NODE_EXTRA_CA_CERTS, NODE_TLS_REJECT_UNAUTHORIZED, used this package: https://www.npmjs.com/package/win-ca
So, no solution for this case?

**Comment by geongeorge** [comment]
@illiakovalenko Where you able to get this fixed on dev server? I've been looking for a while

**Comment by batazor** [comment]
@timneutkens This is quite relevant for local development. Any ideas how to solve this?

**Comment by NgyAnthony** [comment]
Getting the same issue in my production environment on all pages with getServerSideProps, even though my development environment doesn't trigger the error while pointing to my production backend...
My endpoints are properly encrypted with Let's encrypt.

What is the reasoning behind _not_ being able to node env variables ?
While I understand it's not secure I wish I had access to those variables to at least debug this thing...

**Comment by lucax88x** [comment]
@timneutkens I feel you should reconsider to reopen this..

That's pretty common case to have a self-signed certificate in a localhost environment.

Right now I have a image server that provides images, and using <Image> from Next package will give the DEPTH_ZERO_SELF_SIGNED_CERT and we cannot do anything to prevent this. I had to revert to <img>, sadly.

If anyone is using self-signed certificate in production, its his problem.

**Comment by cstolli** [comment]
@timneutkens +1 for reopening and reconsidering
this is common dev practice in trusted containerized environments and easily avoided in production

**Comment by cryptic-ai** [comment]
This should be re-opened honestly. There shouldn't be a reason you can't override this in development.

**Comment by zaclem01** [comment]
Agree that this should be re-opened. I need to do a local rewrite of a url for testing, and being unable to do so with a self-signed cert is really limiting the utility of even running this locally.

**Comment by aslamj** [comment]
What I wonder is that if I'm writing an API using NextJS rules and any handler method where I do a fetch to another API with a non trusted CA cert (may be self-signed one), then having an environment variable ERR_CERT_AUTHORITY_INVALID=0, skips the cert checking totally. So why not use the same for the rewrite runtime code and make it work for us in dev mode at least.

**Comment by mythz** [comment]
Can you please respect `NODE_TLS_REJECT_UNAUTHORIZED=0` when `NODE_ENV == 'development'`, if that's still not restrictive enough then just allow it for `localhost`.

Using a self-signed certificate during development is the sole reason we need to use the rewrites feature, which has to be one of its most popular use-cases. Disallowing it just forces us to host our localhost development servers on an additional plain-text http endpoint (we shouldn't need), which is self-defeating.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
