### ISSUE TITLE
Error create alias with babel.config.json

### ISSUE THREAD

**Issue by asih2489** [vercel/next.js#21618]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.19.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu

**How are you deploying your application?**

next build

**Describe the Bug**

I created an alias using babel-plugin-module-resolver and created a babel.config.json configuration file. I use babel.config.json because the alias is used in the published package as well.

files: babel.config.json

````
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "module-resolver",
            {
                "root": [
                    "."
                ],
                "alias": {
                    "@root": "./",
                    "@core": "./core",
                    "@core_modules": "swift-pwa-core/core/modules",
                    "@common_button": "swift-pwa-core/core/modules/commons/button",
                }
            }
        ]
    ]
}
````

I import the components in this way

````import Button from '@commons_button'````

if I run with npm run dev it runs normally, but when I build with yarn build / npm run build, it will get an error package not found, because the path of the resolver alias is not correct.

````
 ModuleNotFoundError: Module not found: Error: Can't resolve '../Buttons' in '/home/arfa/Icube/swift-pwa'
 
 
 > Build error occurred
 Error: > Build failed because of webpack errors
     at /home/arfa/Icube/swift-pwa/node_modules/next/dist/build/index.js:15:918
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async /home/arfa/Icube/swift-pwa/node_modules/next/dist/build/tracer.js:1:525

````

**Expected Behavior**

I wish I could use babel.config.json

**To Reproduce**

1. create 1 sample component
2. create alias configuration file ````babel.config.json``` with babel-plugin-module-resolver
3. import component to pages with alias
4. run next build

**Comment by timneutkens** [comment]
You don't have to use babel plugins for this. Path aliasing is a built-in feature: https://nextjs.org/docs/advanced-features/module-path-aliases

**Comment by yosefkurniawan** [comment]
> You don't have to use babel plugins for this. Path aliasing is a built-in feature: https://nextjs.org/docs/advanced-features/module-path-aliases

hi @timneutkens 
i am @asih2489 's project team mate.
i got question here before we have to switch the aliases from babel.config.json into jsconfig.json.

if we use this nextjs built-in path aliasing (jsconfig.json), is it possible to create alias for any file/module inside node_modules just like we do while using bable.config.json?
we have alias for our own components which we serve as a package named `swift-pwa-core` under node_modules
so for example:
as mentioned in the babel.config.json, we have an alias  `"@common_button": "swift-pwa-core/core/modules/commons/button"`
then we can just call alias @common_button in any file in our code.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
