### ISSUE TITLE
Next 10.0.6 with webpack 5 & custom server throws `Cannot read property 'replace' of undefined`

### ISSUE THREAD

**Issue by felixmosh** [vercel/next.js#21703]
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

12.18.3

**What browser are you using?**

Chrome 88

**What operating system are you using?**

macOS

**How are you deploying your application?**

other

**Describe the Bug**

I have a custom express server.
I'm using webpack 5 (via yarn resolutions)

I've updated to next 10.0.6, and starting in dev mode throws

```
info  - Using external babel configuration from /Users/****/Projects/node/****/packages/renderers/front/babel.config.js
HookWebpackError: Cannot read property 'replace' of undefined
at makeWebpackError (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:51903:9)
at /Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:37857:12
at eval (eval at create (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:27150:10), <anonymous>:10:1)
  at fn (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:36026:17)
  at Hook.eval [as callAsync] (eval at create (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:27150:10), <anonymous>:8:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:26952:14)
    at cont (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:37854:34)
    at /Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:37900:10
    at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9438
    at done (/Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9750)
    at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9380
    at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9438
    at done (/Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9750)
    at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9380
    at /Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:39195:10
    at /Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:31649:34
    -- inner error --
    TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (/Users/****/Projects/node/****/node_modules/next/build/webpack/plugins/pages-manifest-plugin.ts:48:34)
    at /Users/****/Projects/node/****/node_modules/next/build/webpack/plugins/pages-manifest-plugin.ts:67:18
    at fn (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:36024:10)
    at Hook.eval [as callAsync] (eval at create (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:27150:10), <anonymous>:8:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:26952:14)
      at cont (/Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:37854:34)
      at /Users/****/Projects/node/****/node_modules/next/dist/compiled/webpack/bundle5.js:37900:10
      at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9438
      at done (/Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9750)
      at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9380
      at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9438
      at done (/Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9750)
      at /Users/****/Projects/node/****/node_modules/next/dist/compiled/neo-async/async.js:1:9380
```

**Expected Behavior**

It should start normally

**To Reproduce**

1. Clone custom server example, 
2. Enable webpack (via `  future: { webpack5: true }`)
3. Start the server

**Comment by jhlym** [comment]
I have a same issue....

**Comment by jhenriquevissotto** [comment]
`future: { webpack5: true }` doesn't work for me too.

```

(node:8932) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

(node:8932) UnhandledPromiseRejectionWarning: ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does
 not match the API schema.
 - configuration[0].node has an unknown property 'fs'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
    at validate (D:\code\github\quantamentus\node_modules\next\dist\compiled\schema-utils3\index.js:1:153657)
    at validateSchema (D:\code\github\quantamentus\node_modules\next\dist\compiled\webpack\bundle5.js:126352:2)
    at create (D:\code\github\quantamentus\node_modules\next\dist\compiled\webpack\bundle5.js:129931:3)
    at webpack (D:\code\github\quantamentus\node_modules\next\dist\compiled\webpack\bundle5.js:129968:31)
    at f (D:\code\github\quantamentus\node_modules\next\dist\compiled\webpack\bundle5.js:90191:15)
    at HotReloader.start (D:\code\github\quantamentus\node_modules\next\dist\server\hot-reloader.js:16:415)
    at async DevServer.prepare (D:\code\github\quantamentus\node_modules\next\dist\server\next-dev-server.js:15:414)
(node:8932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```

**Comment by ScriptedAlchemy** [comment]
@Timer this is a problem at lululemon as well

**Comment by HartS** [comment]
@felixmosh does pinning webpack to version 4 (4.44.1 e.g.) resolve this issue? I was seeing something similar running nextein with next 10.0.6 and webpack 5 (which npm installs by default)

**Comment by felixmosh** [comment]
@HartS I want to use webpack 5, 
I didn't tried to pinning webpack version

**Comment by timneutkens** [comment]
> To Reproduce
Clone custom server example,
Enable webpack (via future: { webpack5: true })
Start the server

This works fine with `npm run dev` `npm run build` and `npm run start`. Can you provide a complete reproduction?

**Comment by felixmosh** [comment]
Looks like v10.0.7 solved it

**Comment by markbecker-work** [comment]
I am still seeing this issue running Next version 11.0.1, copy-webpack-plugin version 9.0.0

**Comment by yy523697597** [comment]
> I am still seeing this issue running Next version 11.0.1, copy-webpack-plugin version 9.0.0

Hi, do you solve this issue? I have the same issue too

**Comment by TheBotlyNoob** [comment]
Same issue, started when I tried using `SCSS`

**Comment by kauecastro** [comment]
Same issue.

**Comment by TheBotlyNoob** [comment]
Sorry, got it when I used absolute imports with webpack, solved it by using [jsconfig.json](https://nextjs.org/docs/advanced-features/module-path-aliases)

**Comment by sunpietro** [comment]
Have you managed to solve the issue? Here's my custom webpack config:
```
/* eslint-disable @typescript-eslint/no-var-requires */
const { normalModuleReplacement, verifySiteCode } = require('./bin/webpackCustomConfig');
const LoadablePlugin = require('@loadable/webpack-plugin');

const withBundleAnalyzer = require('@next/bundle-analyzer')({
    enabled: false, // enable to generate report
});

const SITECODE = process.env.SITECODE;

verifySiteCode(SITECODE);

module.exports = withBundleAnalyzer({
    env: {
        NEXT_PUBLIC_SITECODE: SITECODE,
    },
    distDir: 'build',
    assetPrefix: process.env.NEXT_STATICS_PREFIX,
    future: {
        webpack5: true,
    },

    webpack: (config, { isServer }) => {
        if (!isServer) {
            config.resolve.fallback = {
                ...(config.resolve.fallback || {}),
                fs: false,
                path: false,
            };
            // more info: https://github.com/vercel/next.js/issues/8106
            config.resolve.alias['@sentry/node'] = '@sentry/browser';
        }

        config.mode = isServer ? 'development' : 'production';

        config.plugins.push(new LoadablePlugin());

        config.module.rules.push({
            test: /\.svg$/,
            issuer: {
                and: [/\.(js|ts)x?$/],
            },
            type: 'javascript/auto',
            use: ['@svgr/webpack', 'url-loader'],
        });

        config.plugins.push(normalModuleReplacement(SITECODE));

        return config;
    },
    webpackDevMiddleware: (config) => {
        config.watchOptions = {
            poll: 1000, // Check for changes every second
            aggregateTimeout: 300, // delay before rebuilding
            ignored: /node_modules/,
        };

        return config;
    },
});
```

**Comment by TheBotlyNoob** [comment]
Try updating next.js

**Comment by w3ichen** [comment]
I got mine to work by being more specific about the values in the `config `being changed and by spreading out the pre-existing values of the `config`

This did not work
```
module.exports = {
  webpack(config, {}) {
    config.resolve = {
      fallback:{
        fs: false,
        child_process: false,
        net: false,
        crypto: false,
      }
    };
    return config;
  },
};
```

Whereas this did work:
```
module.exports = {
  webpack(config, {}) {
    config.resolve.fallback = {
      ...config.resolve.fallback,
      fs: false,
      child_process: false,
      net: false,
      crypto: false,
    };
    return config;
  },
};
```

**Comment by buesing** [comment]
Hey, this broke my svg setup. I use typescript. Relevant `next.config.js`:
```
        config.module.rules.push({
          test: /\.svg$/,
          use: [
            {
              loader: "@svgr/webpack",
              options: {
                svgoConfig: {
                  plugins: {
                    removeViewBox: false,
                    removeDimensions: true,
                  },
                },
              },
            },
          ],
        })
```
and my `next-env.d.ts` used to look like this:
```
/// <reference types="next" />
/// <reference types="next/types/global" />

declare module "*.svg" {
  const content: any
  export default content
}
```
But after upgrading to next@11.0.1, the `svg` block is automatically removed during build, and I'm getting the error:
```
Type error: Cannot find module '@assets/illustrations/icon.svg' or its corresponding type declarations.
```
 Any ideas?

**Comment by pranavwani** [comment]
The is regarding `@babel/runtime` path, which will fix by resolving it

```js
const NextConfig = {
  webpack: (config, {}) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      // Resolve to use common @babel/runtime for local linked libs
      // Which not consider for linked libs linked via `yarn link`
      '@babel/runtime': path.resolve('../../node_modules/@babel/runtime')
    };

    // Important: return the modified config
    return config;
  }
};
```

**Comment by pranavwani** [comment]
@w3ichen :+1:

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
