### ISSUE TITLE
Prerender error on next build since 10.0.6 - with node canvas

### ISSUE THREAD

**Issue by skylus** [vercel/next.js#21702]
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

12.16.1

**What browser are you using?**

chrome but does not matter (build time)

**What operating system are you using?**

macOS + linux on vercel

**How are you deploying your application?**

vercel

**Describe the Bug**

While building nextjs project with statically generated page with node canvas - it fails on prerendering since 10.0.6.
does not happen in 10.0.5 and below.
Happens both on vercel and locally.

This is the error:
Error occurred prerendering page "/pt-pt/editor". Read more: https://err.sh/next.js/prerender-error
Error: Module did not self-register: '/Users/tom/code/project/node_modules/canvas/build/Release/canvas.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/tom/project/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

**Expected Behavior**

Build should succeed.

**To Reproduce**

(My react version:     "react": "^16.14.0",)

1. Create next 10.0.6 project
2.Install fabric js (for canvas) - this is my version (from package-lock):
      "version": "3.6.6",
      "resolved": "https://registry.npmjs.org/fabric/-/fabric-3.6.6.tgz",
      "requires": {
        "canvas": "^2.6.1",
        "jsdom": "^15.1.0"
      }

3.create a next js statically generated file with the canvas object.
4.run next build.

**Comment by daneden** [comment]
Also experiencing this issue under the same conditions!

**Comment by beac0n** [comment]
I'm having the EXACT same issue. It also does not happen on 10.0.5 as OP stated correctly.

**Comment by nandorojo** [comment]
Yeah same exact thing for me, upgraded from `10.0.0` -> `10.0.6` and my app won't build.

**Comment by ndrsllwngr** [comment]
**UPDATE** `10.0.7` is affected, too.

```js
[ ===] info  - Generating static pages (0/9)
Error occurred prerendering page "/profile". Read more: https://err.sh/next.js/prerender-error
Error: Module did not self-register: '/Users/<USERNAME>/projects/<PROJECT>/node_modules/canvas/build/Release/canvas.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/<USERNAME>/projects/<PROJECT>/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

- At the moment next.js versions `10.0.6` & `10.0.7` fail during build (`next build`) when using e.g. [fabric.js](http://fabricjs.com/).
- Versions `10.0.5` or lower are working fine.

**Comment by naayaghan27** [comment]
I didn’t like GitHub

**Comment by daneden** [comment]
Still present in 10.0.8 🙃

**Comment by TheAlemazing** [comment]
FIY, Node-canvas doesn't work with worker threads yet. 
Source: https://github.com/Automattic/node-canvas/issues/1536#issuecomment-600739090

**Comment by nandorojo** [comment]
Is there any way around this? Surely these versions don't break builds for everyone. Does anyone know what causes this?

**Comment by balazsorban44** [comment]
I wasn't sure how to interpret your reproduction, but I ran `next build` with this code, and it worked correctly:

```js
import { fabric } from "fabric"
import { useEffect } from "react"

export default function Home() {
  useEffect(() => {
    new fabric.Canvas()
  }, [])
  return null
}

export function getStaticProps() {
  new fabric.Canvas()
  return { props: {} }
}

```

**Comment by beac0n** [comment]
@balazsorban44 If I'm not mistaken, the issue is with node-canvas. Not with fabric.js. node-canvas is being used in tests. So it's no surprise to me, that "next build" works. So this issue is not closed imho

**Comment by balazsorban44** [comment]
If you still think this is an issue, please open a bug report with a minimal reproduction I can run locally. 🙏

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
