### ISSUE TITLE
run dev and run build failed with progressive-web-app example

### ISSUE THREAD

**Issue by sugar3103** [vercel/next.js#21767]
**What example does this report relate to?**

progressive-web-app

**What version of Next.js are you using?**

latest 10.0.1

**What version of Node.js are you using?**

14.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu

**How are you deploying your application?**

next dev

**Describe the Bug**

I have upgrade the packages version to latest :
 "dependencies": {
    "next": "latest",
    "next-pwa": "^5.0.5",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "sass": "^1.32.6",
    "webpack": "^5.19.0"
  }
after i updated them npm run dev or yarn run dev show these error :

> [PWA] Compile server

> Build error occurred
TypeError: Cannot read property 'tapPromise' of undefined
    at /home/sugar/g1-fe-nextjs/node_modules/workbox-webpack-plugin/build/generate-sw.js:242:41
    at SyncHook.eval [as call] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47168:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
    at Compiler.newCompilation (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56889:30)
    at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56926:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
    at Compiler.compile (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56921:28)
    at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56580:11
    at Compiler.readRecords (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56788:11)
    at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56577:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
    at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56574:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)

**Expected Behavior**

The service run without error and start the localhost:3000

**To Reproduce**

First run : 
npx create-next-app --example progressive-web-app progressive-web-app 
cd to progressive-web-app/
npm install -g npm-check-updates
ncu -u (to update all the package to latest version)
npm run dev
--- now show error

**Comment by sugar3103** [comment]
> **What example does this report relate to?**
> 
> progressive-web-app
> 
> **What version of Next.js are you using?**
> 
> latest 10.0.1
> 
> **What version of Node.js are you using?**
> 
> 14.15.1
> 
> **What browser are you using?**
> 
> Chrome
> 
> **What operating system are you using?**
> 
> Ubuntu
> 
> **How are you deploying your application?**
> 
> next dev
> 
> **Describe the Bug**
> 
> I have upgrade the packages version to latest :
> "dependencies": {
> "next": "latest",
> "next-pwa": "^5.0.5",
> "react": "^17.0.1",
> "react-dom": "^17.0.1"
> },
> "devDependencies": {
> "sass": "^1.32.6",
> "webpack": "^5.19.0"
> }
> after i updated them npm run dev or yarn run dev show these error :
> 
> > [PWA] Compile server
> 
> > Build error occurred
> > TypeError: Cannot read property 'tapPromise' of undefined
> > at /home/sugar/g1-fe-nextjs/node_modules/workbox-webpack-plugin/build/generate-sw.js:242:41
> > at SyncHook.eval [as call] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47168:10), :9:1)
> > at SyncHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
> > at Compiler.newCompilation (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56889:30)
> > at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56926:29
> > at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), :6:1)
> > at AsyncSeriesHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
> > at Compiler.compile (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56921:28)
> > at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56580:11
> > at Compiler.readRecords (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56788:11)
> > at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56577:10
> > at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), :6:1)
> > at AsyncSeriesHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
> > at /home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:56574:19
> > at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), :15:1)
> > at AsyncSeriesHook.lazyCompileHook (/home/sugar/g1-fe-nextjs/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
> 
> **Expected Behavior**
> 
> The service run without error and start the localhost:3000
> 
> **To Reproduce**
> 
> First run :
> npx create-next-app --example progressive-web-app progressive-web-app
> cd to progressive-web-app/
> npm install -g npm-check-updates
> ncu -u (to update all the package to latest version)
> npm run dev
> --- now show error

**Comment by sugar3103** [comment]
I have found the exact problem occur on Webpack > 5.0.0, with lower version of Webpack < 5.0.0 with no problem. So here is the working enviroment : 
next-pwa > 5.0.0 
webpack < 5.0.0

**Comment by sugar3103** [comment]
it work with yarn start (that's production stage to have to service worker to work), webpack version < 5 .
Hope you can make it support webpack >= 5 
Thank you very much

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
