### ISSUE TITLE
worker-loader support with webpack inlined

### ISSUE THREAD

**Issue by ramasilveyra** [vercel/next.js#21972]
**What version of Next.js are you using?**

10.0.7-canary.6

**What version of Node.js are you using?**

v12

**What browser are you using?**

Chrome

**What operating system are you using?**

macOs

**How are you deploying your application?**

Other platform

**Describe the Bug**

Latest next.js version with webpack inlined breaks worker-loader.

Build throws an exception.

Example:
```
➜  bug-repro-next-w5-inline-worker git:(main) ✗ yarn build
yarn run v1.22.5
$ next build
info  - Creating an optimized production build
Failed to compile.

./lib/hello.worker.js
TypeError: Cannot read property 'version' of undefined


> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/ramirosilveyra/dev/personal/bug-repro-next-w5-inline-worker/node_modules/next/dist/build/index.js:15:918
    at async /Users/ramirosilveyra/dev/personal/bug-repro-next-w5-inline-worker/node_modules/next/dist/build/tracer.js:1:1450
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected Behavior**

build to succeed

**To Reproduce**

Bug repro: https://github.com/ramasilveyra/bug-repro-next-w5-inline-worker

**Comment by BayanBennett** [comment]
Whether inlined or not, I'm getting the same error. I'm using TypeScript

Using a JS file with `new Worker(new URL(/* ... */), import.meta.url)` works fine.

```js
module.exports = {
  future: {
    webpack5: true,
  },
  reactStrictMode: true,
  webpack: (config) => {
    config.module.rules.unshift({
      test: /\.worker\.ts$/,
      loader: "worker-loader",
    });
    return config;
  },
};
```

**Comment by thoo1** [comment]
Did anyone manage to fix this or have a workaround?

**Comment by BayanBennett** [comment]
> Did anyone manage to fix this or have a workaround?

Are you using Next v11?

I ended up continuing with the `new Worker(...)` syntax above.

**Comment by prvnsmpth** [comment]
@BayanBennett Could you please share an example of how you got it working using `new Worker(...)`? I tried that and got the exact same error (`TypeError: Cannot read property 'version' of undefined`).

**Comment by BayanBennett** [comment]
@prvnsmpth https://github.com/BayanBennett/reference.bayanbennett.com/blob/6d3cb61e76db78d080b82c6c46ae6cd14ee6aaf0/src/contexts/code-runner/index.tsx#L42-L51

**Comment by prvnsmpth** [comment]
Thanks a lot!

**Comment by timneutkens** [comment]
The example https://github.com/vercel/next.js/tree/canary/examples/with-web-worker has been updated to use `new Worker` which is supported in Next.js 11 + webpack 5.

**Comment by prvnsmpth** [comment]
@timneutkens Is there any support for `SharedWorker` in Next.js 11? I was able to get `Worker` running, but not `SharedWorker`.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
