### ISSUE TITLE
WORKS LOCALLY - ERROR IN CI : Global CSS cannot be imported from files other than your Custom <App>

### ISSUE THREAD

**Issue by nenadfilipovic** [vercel/next.js#22059]
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

14.15.4

**What browser are you using?**

Firefox

**What operating system are you using?**

Ubuntu 20.04

**How are you deploying your application?**

next build, next start

**Describe the Bug**

I have empty Next.js project with _app.tsx with this content:

```
import '../styles/globals.css';

import type { AppProps } from 'next/app';

const App = ({ Component, pageProps }: AppProps): JSX.Element => {
  return <Component {...pageProps} />;
};

export default App;
```

styles/globals.css is empty.

When I build app locally with next build, next start it works ok.

When I build app on CI I get this error:

```
info  - Creating an optimized production build...
| application    | Attention: Next.js now collects completely anonymous telemetry regarding usage.
| application    | This information is used to shape Next.js' roadmap and prioritize features.
| application    | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
| application    | https://nextjs.org/telemetry
| application    | 
| application    | info  - Using external babel configuration from /app/test/.babelrc
| application    | Failed to compile.
| application    | 
| application    | ./src/styles/globals.css
| application    | Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
| application    | Read more: https://err.sh/next.js/css-global
| application    | Location: src/pages/_app.tsx
| application    | 
| application    | 
| application    | > Build error occurred
| application    | Error: > Build failed because of webpack errors
| application    |     at /app/test/node_modules/next/dist/build/index.js:15:918
| application    |     at async /app/test/node_modules/next/dist/build/tracer.js:1:1441
| application    | npm ERR! code ELIFECYCLE
| application    | npm ERR! errno 1
| application    | npm ERR! ***@0.0.1 build: `next build`
| application    | npm ERR! Exit status 1
| application    | npm ERR! 
| application    | npm ERR! Failed at the ***@0.0.1 build script.
| application    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This is my .babelrc:

```
{
  "presets": ["next/babel"]
}
```

tsconfig.json :

```
{
  "compilerOptions": {
    "target": "ES2015",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "types": ["jest"],
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": ["src/**/*", "next-env.d.ts"],
  "exclude": []
}
```

Pretty much same problem as this guy https://stackoverflow.com/questions/64553711/cant-build-next-js-app-with-typescript-and-sass

If I remove part where I import css or if I put `import "tailwindcss/tailwind.css";` application builds without problem.

**Expected Behavior**

It should build app during CI same as it is locally.

**To Reproduce**

.

**Comment by nenadfilipovic** [comment]
It was a file ownership problem.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
