### ISSUE TITLE
[Regression] - ModuleNotFoundError: when running production build (and eating underlying error)

### ISSUE THREAD

**Issue by jasonwilliams** [vercel/next.js#22200]
**What version of Next.js are you using?**

10.0.7 (Issue looks like it was introduced in 10.0.6)

**What version of Node.js are you using?**

15

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOS

**How are you deploying your application?**

next start

**Describe the Bug**

Updating to  Webpack 5.21.2 alongside Next 10.0.6 causes ModuleNotFound errors when using ignorePlugin.
We don't get the error when rolling back to 10.0.5

When building in development `next` we have no issues with our pages.
however when running `next build` we get an error:
```
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: TypeError: Cannot read property 'request' of null


> Build error occurred
Error: > Build failed because of webpack errors
    at home/project/node_modules/next/dist/build/index.js:15:929
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async home/project/node_modules/next/dist/build/tracer.js:1:1596
``` 

#### Issue 1: underlying error was eaten
The above wasn't very helpful as it doesn't tell me what caused it or what was trying to be loaded.
I managed to search for the `ModuleNotFoundError` class and log out the error before it.
It was in `/node_modules/next/dist/compiled/webpack/bundle4.js`

Now i can see:
```
null
TypeError: Cannot read property 'request' of null
    at IgnorePlugin.checkIgnore (/home/project/node_modules/webpack/lib/IgnorePlugin.js:50:49)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/project/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:21:16)
    at NormalModuleFactory.create (/home/project/node_modules/next/dist/compiled/webpack/bundle4.js:67799:28)
    at /home/project/node_modules/next/dist/compiled/webpack/bundle4.js:54821:14
    at Semaphore._continue (/home/project/node_modules/next/dist/compiled/webpack/bundle4.js:93245:5)
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

#### Issue 2:  null being passed to webpack/ignorePlugin
It looks like in production next passes `null` to ignorePlugin, specifically [here](https://github.com/webpack/webpack/blob/master/lib/IgnorePlugin.js#L37-L41).
Im not sure why this only happens on production builds but it seems to have only happened since updating to webpack 5

**Expected Behavior**

production builds should work

**To Reproduce**

- Clone https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example
- Checkout `moduleNotFound` branch
- yarn install
- Run next build or `yarn next build` (fails)
- install next "10.0.5"
- Run next build - (works, or at least you get a different error)

**Comment by gfortaine** [comment]
It looks like that this error is a regression coming from webpack : https://github.com/webpack/webpack/issues/8538

**Comment by jasonwilliams** [comment]
@gfortaine im sure it’s related to this https://github.com/vercel/next.js/issues/21679#issuecomment-771941447

**Comment by gfortaine** [comment]
@jasonwilliams Many thanks 👍 We do confirm that by setting the following in `next.config.js`:

```js
// next.config.js
module.exports = {
  future: { webpack5: true }
}
```

the bug disappears with next 10.0.6 in your test repo : https://github.com/gfortaine/nextjs9-typescript-server-vscode-example/tree/moduleNotFound

**Comment by jasonwilliams** [comment]
@timneutkens I understand webpack 5 support is “beta” but was there a reason to make such a breaking change on a patch release? The documentation hasn’t been updated to mention the change in how you opt in (it still only mentions resolutions) so this would have broken for anyone using webpack 5 with plugins. I only found that fix by chance on another issue.

https://nextjs.org/blog/next-9-5#webpack-5-support-beta

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
