### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client in getServerSideProps()

### ISSUE THREAD

**Issue by binajmen** [vercel/next.js#22377]
**What version of Next.js are you using?**

10.0.8-canary.5

**What version of Node.js are you using?**

14.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

yarn dev

**Describe the Bug**

I receive the `ERR_HTTP_HEADERS_SENT` and `ERR_STREAM_WRITE_AFTER_END` errors (see console output below) followed by a fatal error with an exit code 1

**Expected Behavior**

I'm testing the value of `typeof window` prior to `writeHead` on `res` in the `getServerSideProps()` function body to ensures I will write on `res` at server-side only. Unless I misunderstood something, I would expect a redirection without error as I'm still in the server, and therefore I should be able to write on the response.

**To Reproduce**

1. Visit localhost:3000/admin
2. Redirected to /signin
3. Sign in
4. Redirected to /user (with custom claim admin set to `false`)
5. Click on the /admin link <-- error

Console output:
```shell
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:558:11)
    at DevServer.sendHTML (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/server/next-dev-server.js:35:5)
    at DevServer.render (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/next-server/server/next-server.js:73:37)
    at async Object.fn (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/next-server/server/next-server.js:47:704)
    at async Router.execute (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/next-server/server/next-server.js:34:504) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ServerResponse.end (_http_outgoing.js:788:7)
    at ServerResponse.end (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/compiled/compression/index.js:1:141519)
    at DevServer.handleRequest (/Users/benjamin/Projects/sandbox/next-with-firebase-auth/node_modules/next/dist/next-server/server/next-server.js:34:624)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:727:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've also received this error at some point in the chrome console after trying tons of solution. It might be the beginning of an explanation but I'm not sure how to interpret that:
```
react-dom.development.js?61bb:67 Warning: Did not expect server HTML to contain a <div> in <div>.
    at a
    at Link (webpack-internal:///./node_modules/next/dist/client/link.js:88:19)
    at div
    at MyApp (webpack-internal:///./pages/_app.js:21:24)
```
I suppose we can insert `<div>` and stuff in the `_app` to share a common layout across an app, isn't it?

Code is available here: https://github.com/binajmen/next-with-firebase-auth/blob/main/pages/admin/index.js#L40

**Comment by binajmen** [comment]
Here is a reduced sandbox without the need to setup firebase & co.

https://codesandbox.io/s/quirky-almeida-bvgvd?file=/pages/_app.js

1. Go to /
2. Click on /admin
3. Check error in console

**Comment by timneutkens** [comment]
For the case that you're describing the `redirect` option that can be returned from getServerSideProps/getStaticProps would work fine ([docs](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)). `getServerSideProps` always runs on the Node.js environment so window will never be available in that method. In the example below the component would never be rendered because it'll always redirect (even on client-side navigation).

```jsx
// admin/index.js

import * as React from "react";
import { useRouter } from "next/router";

function AdminPage({ redirect }) {
    return (
      <div>
        <p>You are on an admin page !</p>
        <p>You are logged and your email is XXX</p>
      </div>
    );
}

export default AdminPage;

export const getServerSideProps = ({ res }) => {
    return { 
      redirect: {
        destination: '/'
        permanent: false,
      } 
    };
};
```

**Comment by binajmen** [comment]
Thank you @timneutkens, I forgot the `redirect` option. Issue solved!

Nevertheless, I'm still puzzled by the error message, as I believed from the SS perspective, writing on `res` should work without issues as the content should not be written yet.

**Comment by ypresto** [comment]
I'm still using getInitialProps() for authentication, and calling `ctx.res.writeHead(307, { Location: path })`, then got ERR_HTTP_HEADERS_SENT.
Anyway to solve this..?

**Comment by Alex01d** [comment]
> I'm still using global getInitialProps() in`_app.tsx` for authentication, and calling `ctx.res.writeHead(307, { Location: path })`, then got ERR_HTTP_HEADERS_SENT.
> Stucked at getInitialProps() while tried to migrate to getSeverSideProps(), because my page components have static properties which used by _app.tsx render logic (`Page.noDefaultToolbar = true` etc.).
> Anyway to solve this..?

```
ctx.res.setHeader('Location', path);
ctx.res.statusCode = 307;
return {};
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
