### ISSUE TITLE
Custom error page can't have SSR-only modules in getInitialProps

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#22505]
**What version of Next.js are you using?**

10.0.8-canary.6

**What version of Node.js are you using?**

12.18.3

**What browser are you using?**

Firefox 85.0.1 (64-bit)

**What operating system are you using?**

Pop_OS! 20.04 (Ubuntu 20.04)

**How are you deploying your application?**

Vercel

**Describe the Bug**

I have a data fetching requirement for the footer of my website (I need to fetch a list of organizations to display). Thus, I've added a `getStaticProps` export to every page in the app and they're all working great (I love it)!

But, to add that same data to [my custom `pages/_error.tsx`](https://github.com/tutorbookapp/tutorbook/blob/develop/pages/_error.tsx#L41), I have to use `getInitialProps` instead of `getStaticProps`:

```typescript
// pages/_error.tsx
function ErrorPage({ status, message, ...props }: ErrorPageProps): JSX.Element {
  const { t } = useTranslation();
  const header = useMemo(() => {
    if (typeof status === 'number' && [404, 400, 405, 500].includes(status))
      return t(`error:${status}-header`);
    return t('error:header');
  }, [t, status]);

  return (
    <Page title={`${header} - Tutorbook`} intercom {...props}>
      <EmptyHeader />
      <Notification header={header}>
        <p>{message || t('error:body')}</p>
      </Notification>
    </Page>
  );
}

ErrorPage.getInitialProps = async (
  ctx: NextPageContext
): Promise<ErrorPageProps> => {
  const props = await getPageProps();
  const status = ctx.res?.statusCode || ctx.err?.statusCode;
  return { status, message: ctx.err?.message, ...props };
};

export default withI18n(ErrorPage, { common, error });
```

I can't fetch the needed data client-side (as I'm using an SSR-only module in `getInitialProps` that [isn't included in the client-side bundle](https://arunoda.me/blog/ssr-and-server-only-modules)). This shows an error when the page is compiled because no data is given to [my `<Footer />` component](https://github.com/tutorbookapp/tutorbook/blob/develop/components/footer/index.tsx#L35):

```
event - build page: /_error
event - compiled successfully
TypeError: Cannot read property 'map' of undefined
    at Footer (webpack-internal:///./components/footer/index.tsx:68:24)
    at processChild (/home/nchiang/repos/tutorbook/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/nchiang/repos/tutorbook/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/nchiang/repos/tutorbook/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/nchiang/repos/tutorbook/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/nchiang/repos/tutorbook/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/nchiang/repos/tutorbook/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:135:19)
    at loadGetInitialProps (/home/nchiang/repos/tutorbook/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/nchiang/repos/tutorbook/node_modules/next/dist/next-server/server/render.js:54:1142)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/nchiang/repos/tutorbook/node_modules/next/dist/next-server/server/next-server.js:109:97
    at async __wrapper (/home/nchiang/repos/tutorbook/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/home/nchiang/repos/tutorbook/node_modules/next/dist/next-server/server/next-server.js:134:387)
    at async DevServer.renderToHTML (/home/nchiang/repos/tutorbook/node_modules/next/dist/next-server/server/next-server.js:135:923)
```

I've added the SSR-only module to my [`package.json`](https://github.com/tutorbookapp/tutorbook/blob/develop/package.json#L169) to prevent it from being included client-side:

```json
  "browser": {
    "firebase-admin": false
  },
```

While this prevents compilation errors (because `firebase-admin` depends on Node.js server-only modules like `child_process`), it results in the error message shown above (when my `<Footer />` component doesn't have the props it needs).

**Expected Behavior**

Next.js should automatically extract code from `getInitialProps` so that it's only ever run server-side. I'm not sure if this is the expected behavior of `getInitialProps`, but I assumed it would be (because `getInitialProps` results in server-side rendered pages just like `getServerSideProps`).

Even better, replace the required `getInitialProps` method in the custom error page with the newer `getServerSideProps` method.

**To Reproduce**

Create any Next.js project that uses a SSR-only module in the `getInitialProps` of a custom error page (`pages/_error.tsx`).

**Comment by TommySorensen** [comment]
I'm not sure how to fix the issue. But NextJS has something they call `dynamic`you can use to lazy load client only code. Its pretty easy to set up, and you dont need the stuff you mentioned in the package file.
Example here: https://nextjs.org/docs/advanced-features/dynamic-import#basic-usage

You can even set it to `ssr: false` [like this](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr)
```js
const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/hello3'),
  { ssr: false }
)
```

Maybe it helps 🤷‍♂️

**Comment by timneutkens** [comment]
> Create any Next.js project that uses a SSR-only module in the getInitialProps of a custom error page (pages/_error.tsx).

This is not a bug, `getInitialProps` is not tree-shaken like `getStaticProps`/`getServerSideProps`.

**Comment by TrustyTechSG** [comment]
> > Create any Next.js project that uses a SSR-only module in the getInitialProps of a custom error page (pages/_error.tsx).
> 
> This is not a bug, `getInitialProps` is not tree-shaken like `getStaticProps`/`getServerSideProps`.

Hi, So is there any way for us to include server side only code in getInitialProps and get it removed from client side bundle? In our case we need to do server side only firebase-admin call to prepare some data shared by all pages for once, it seems App getInitialProps is the only place to do it.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
