### ISSUE TITLE
Next-Auth: Suddenly deployments have started failing

### ISSUE THREAD

**Issue by sami-tin** [vercel/next.js#22667]
### What version of Next.js are you using?

10.0.7

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

We are getting errors like these for the last 3 hours on all deployments:

```
[GET] /api/auth/providers
13:21:48:05
2021-03-02T08:21:49.251Z eedb719c-b3f4-4474-9792-053e7643ef93 WARN [next-auth][warn][nextauth_url]
https://next-auth.js.org/warnings#nextauth_url NEXTAUTH_URL environment variable not set
2021-03-02T08:21:49.348Z eedb719c-b3f4-4474-9792-053e7643ef93 ERROR TypeError: Cannot read property 'replace' of undefined
at Object.qvzy (/var/task/.next/server/pages/api/auth/[...nextauth].js:1704:52)
at __webpack_require__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:23:31)
at Module.Y/DP (/var/task/.next/server/pages/api/auth/[...nextauth].js:638:21)
at __webpack_require__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:23:31)
at Object.5 (/var/task/.next/server/pages/api/auth/[...nextauth].js:201:18)
at __webpack_require__ (/var/task/.next/server/pages/api/auth/[...nextauth].js:23:31)
at /var/task/.next/server/pages/api/auth/[...nextauth].js:91:18
at Object.<anonymous> (/var/task/.next/server/pages/api/auth/[...nextauth].js:94:10)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
RequestId: eedb719c-b3f4-4474-9792-053e7643ef93 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

We pushed a commit 3-4 hours ago that had nothing to do with Next JS's config. It was a simple UI commit. However, it gives a 500 [here](https://swanvo.com/) (`FUNCTION_INVOCATION_FAILED`).

It is quite surprising and confusing how the *Functions Log* now suddenly tell us that they can't find `NEXTAUTH_URL` although we've quite specifically and clearly mentioned in the `.env` files for many weeks now. We even tried by hardcoding a value to `env` variable in the `next.config.js` file but to no avail.

### Expected Behavior

A simple landing page to appear.

### To Reproduce

We have no idea how to reproduce it as we never changed anything regarding config. There is a possibility there's an issue on Vercel's end.

**Comment by balazsorban44** [comment]
Not sure why this is reported in this repo, instead of in https://github.com/nextauthjs/next-auth (The repositories are managed by different organizations.)

Would be interesting to see some kind of a reproduction (or at least your .env and [...nextauth].js file) though and some verification that you correctly set the `NEXTAUTH_URL`. The above error occurs when the value is `undefined`:

https://github.com/nextauthjs/next-auth/blob/d86609a2dc93c1757f1bbfc0bdec1ba2dec73c2a/src/server/index.js#L20-L22

**Comment by sami-tin** [comment]
@balazsorban44 Here's our `.env.production` file:

```
NEXTAUTH_URL = "https://swanvo.com"

NEXT_PUBLIC_FIREBASE_API_KEY = "AI..yc"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "sw..om"
NEXT_PUBLIC_FIREBASE_DATABASE_URL = "ht..om"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "sw..sh"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "sw..om"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "21..58"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:..23"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-..DD"
NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL = "fi..om"
FIREBASE_PRIVATE_KEY = "--..\n"
GOOGLE_CLIENT_ID = "21..om"
GOOGLE_CLIENT_SECRET = "CG..h-"

COOKIE_SECRET = "5i..91"

SENDGRID_API_KEY = "SG..TE"

NEXT_PUBLIC_SENTRY_DSN = "ht..47"
NEXT_PUBLIC_SENTRY_ENV = "pr..on"
SENTRY_ORG = "ti..ce"
SENTRY_PROJECT = "sw..vo"
SENTRY_AUTH_TOKEN = "50..40"
```

And here's our `next.config.js` file:
```
/* eslint-disable */
const isProduction = process.env.NODE_ENV === 'production';
const path = require('path');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const SentryWebpackPlugin = require('@sentry/webpack-plugin');

const {
	NEXT_PUBLIC_SENTRY_DSN: SENTRY_DSN,
	SENTRY_ORG,
	SENTRY_PROJECT,
	SENTRY_AUTH_TOKEN,
	VERCEL_GITHUB_COMMIT_SHA,
	VERCEL_GITLAB_COMMIT_SHA,
	VERCEL_BITBUCKET_COMMIT_SHA
} = process.env;

const COMMIT_SHA = VERCEL_GITHUB_COMMIT_SHA || VERCEL_GITLAB_COMMIT_SHA || VERCEL_BITBUCKET_COMMIT_SHA;

process.env.SENTRY_DSN = SENTRY_DSN;

const BASE_PATH = '';

module.exports = {
	env: {
		NEXT_PUBLIC_WEBSITE_URL: process.env.NEXTAUTH_URL
	},

	pageExtensions: ['jsx', 'js', 'ts', 'tsx'],
	poweredByHeader: false,
	serverRuntimeConfig: {
		PROJECT_ROOT: __dirname
	},

	sassOptions: {
		includePaths: [path.join(__dirname, '/src/assets/styles')],
		minified: true
	},

	productionBrowserSourceMaps: true,
	webpack: (config, options) => {
		if (!options.isServer) {
			config.resolve.alias['@sentry/node'] = '@sentry/browser';
		}

		// Define an environment variable so source code can check whether or not
		// it's running on the server so we can correctly initialize Sentry
		config.plugins.push(
			new options.webpack.DefinePlugin({
				'process.env.NEXT_IS_SERVER': JSON.stringify(options.isServer.toString())
			})
		);

		if (isProduction) {
			config.optimization.minimizer = [];
			config.optimization.minimizer.push(new OptimizeCSSAssetsPlugin({}));

			// When all the Sentry configuration env variables are available/configured
			// The Sentry webpack plugin gets pushed to the webpack plugins to build
			// and upload the source maps to sentry.
			// This is an alternative to manually uploading the source maps
			// Note: This is disabled in development mode.
			if (SENTRY_DSN && SENTRY_ORG && SENTRY_PROJECT && SENTRY_AUTH_TOKEN && COMMIT_SHA) {
				config.plugins.push(
					new SentryWebpackPlugin({
						include: '.next',
						ignore: ['node_modules'],
						stripPrefix: ['webpack://_N_E/'],
						urlPrefix: `~${BASE_PATH}/_next`,
						release: COMMIT_SHA
					})
				);
			}
		}

		return config;
	},
	basePath: BASE_PATH
};
```

As you can see, it's hard to believe how `NEXTAUTH_URL` keeps going undefined OR there's another issue. We only updated Firebase's Firestore rules since it was gonna expire but I doubt that's ever gonna cause this. Apart from that we only pushed an updated `.env` file with different Sendgrid keys.
