### ISSUE TITLE
Cannot use NODE_OPTIONS='--inspect' with Next.js 10.0.8

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#22835]
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Firefox 85.0.1 (64-bit)

### What operating system are you using?

Pop_OS! 20.04 (Ubuntu 20.04)

### How are you deploying your application?

Vercel

### Describe the Bug

In Next.js 10.0.7 (and every earlier version of Next.js), I was able to add a debugger to the Next.js development server by adding the following script to my [`package.json`](https://github.com/nicholaschiang/inspect-nextjs/blob/main/package.json#L6):
```bash
cross-env NODE_OPTIONS='--inspect' next dev
```

With Next.js 10.0.8, however, this command doesn't seem to work:
```bash
nchiang@eevee ~/repos/inspect-nextjs (main) $ yarn dev
Debugger listening on ws://127.0.0.1:9229/e06483eb-3a52-4986-a428-6d07e31b253b
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/nchiang/repos/inspect-nextjs/.yarn/$$virtual/next-virtual-c508287e46/0/cache/next-npm-10.0.8-d5fe169183-de3d89d01a.zip/node_modules/next/dist/bin/next'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Expected Behavior

Running `yarn dev` should start the development server with an option to attach a debugger.

### To Reproduce

1. Clone [this repro](https://github.com/nicholaschiang/inspect-nextjs): `git clone https://github.com/nicholaschiang/inspect-nextjs`
2. Install dependencies using Yarn: `yarn`
3. Try to run the development server: `yarn dev`
4. See error.

Running `yarn run --inspect next dev` seems to work as expected (related to #21270), but I can't figure out how to add it to my `package.json` so that I can run it as a Yarn script. These all fail:
```json
"dev": "--inspect next dev"
"dev": "NODE_OPTIONS='--inspect' next dev"
"dev": "cross-env NODE_OPTIONS='--inspect' next dev"
```

**Comment by vacas** [comment]
Yep, same thing is happening using `npm run dev`. I'll include specs here:

### What version of Next.js are you using?

10.0.8
### What version of Node.js are you using?

12.18.3
### What browser are you using?

Firefox 86.0 (64-bit)
### What operating system are you using?

macOS Big Sur (v11.2.1)
### How are you deploying your application?

Vercel
### Describe the Bug
Same as above, we've used the `NODE_OPTIONS='--inspect'` in version from 10.0.7 and below to debug, but now in version 10.0.8, the command doesn't work; here's what I get using `npm run dev`:
```
current-repo git:(updating-next) ✗ npm run dev

> current-repo@1.0.0 dev /Users/mfjvacas/Documents/Dev/team/current-repo
> NODE_OPTIONS='--inspect --max-old-space-size=8192' NODE_ENV=development next

Debugger listening on ws://127.0.0.1:9229/28c60ffa-6d61-4e81-915a-b5e7c109b243
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at ChildProcessWorker.send (/Users/mfjvacas/Documents/Dev/team/current-repo/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:286:17)
    at WorkerPool.send (/Users/mfjvacas/Documents/Dev/team/current-repo/node_modules/next/node_modules/jest-worker/build/WorkerPool.js:32:34)
    at Farm._process (/Users/mfjvacas/Documents/Dev/team/current-repo/node_modules/next/node_modules/jest-worker/build/Farm.js:129:10)
    at Farm._enqueue (/Users/mfjvacas/Documents/Dev/team/current-repo/node_modules/next/node_modules/jest-worker/build/Farm.js:152:10)
    at Farm._push (/Users/mfjvacas/Documents/Dev/team/current-repo/node_modules/next/node_modules/jest-worker/build/Farm.js:159:12)
    at /Users/mfjvacas/Documents/Dev/team/current-repo/node_modules/next/node_modules/jest-worker/build/Farm.js:90:14
    at new Promise (<anonymous>)
    at Farm.doWork (/Users/mfjvacas/Documents/Dev/team/current-repo/node_modules/next/node_modules/jest-worker/build/Farm.js:56:12)
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! current-repo@1.0.0 dev: `NODE_OPTIONS='--inspect --max-old-space-size=8192' NODE_ENV=development next`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the current-repo@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mfjvacas/.npm/_logs/2021-03-09T18_27_47_747Z-debug.log
```

The dev script in `package.json` looks like this: `"dev": "NODE_OPTIONS='--inspect --max-old-space-size=8192' NODE_ENV=development next"`

Important to note that removing `--inspect` from the dev script runs next as expected.
### Expected Behavior

Running `npm run dev` should start the development server with an option to attach a debugger.

**Comment by kyuwoo-choi** [comment]
same here. setting NODE_OPTIONS='--inspect=0.0.0.0:9229' errors EPIPE

**Comment by ospireon** [comment]
@nicholaschiang whats the status of this bug, what release version will this fix be tied to?

**Comment by ijjk** [comment]
Hi, this appears to be working alright in the latest version of Next.js `v11.1.2`, please update and give it a try! Feel free to respond with additional info if you're still having issues with this.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
