### ISSUE TITLE
Why are majority of the error stacks so miserably vague?

### ISSUE THREAD

**Issue by lacrox22** [vercel/next.js#22909]
### What version of Next.js are you using?

10

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next dev (with TypeScript)

### Describe the Bug

A lot of errors created or funneled by Next.js are not helpful, most frameworks i've used will go the extra mile to prioritize my own projects source file over dist files of a node module which is extremely important in actually making the trace useful. Sometimes if I dig through the trace I can find the original reference but a lot of times I get errors like this that make my development experience incredibly frustrating.

"
Error: Objects are not valid as a React child (found: object with keys {current}). If you meant to render a collection of children, use an array instead.
    at mapIntoArray (/project/node_modules/react/cjs/react.development.js:1037:17)
    at mapIntoArray (/project/node_modules/react/cjs/react.development.js:1004:23)
    at mapChildren (/project/node_modules/react/cjs/react.development.js:1066:3)
    at toArray (/project/node_modules/react/cjs/react.development.js:1116:10)
    at ReactDOMServerRenderer.renderDOM (/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:4264:18)
    at ReactDOMServerRenderer.render (/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3802:21)
    at ReactDOMServerRenderer.read (/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/project/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:135:19)
    at loadGetInitialProps (/project/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/project/node_modules/next/dist/next-server/server/render.js:54:1142)
    at async /project/node_modules/next/dist/next-server/server/next-server.js:107:97
    at async /project/node_modules/next/dist/next-server/server/next-server.js:100:142
    at async DevServer.renderToHTMLWithComponents (/project/node_modules/next/dist/next-server/server/next-server.js:132:387)
    at async DevServer.renderToHTML (/project/node_modules/next/dist/next-server/server/next-server.js:133:522)
"

What am I supposed to do with this message besides spend an hour trying to uncomment out everything one by one. Is it assumed I just need to run the chrome debugger at all times?

### Expected Behavior

To have better stack traces. In the one example I provided at the very least can we have the name of the reference or parent component name.

### To Reproduce

Try to accidentally render a ref as a element

**Comment by MonstraG** [comment]
While this error should be improved, main body gives a hint that you tried to render ref:
> Objects are not valid as a React child (found: object with keys {current})
Ref does, in fact, have "current".

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
