### ISSUE TITLE
error deploy on vercel

### ISSUE THREAD

**Issue by Manonicu** [vercel/next.js#23233]
### What version of Next.js are you using?

10

### What version of Node.js are you using?

14

### What browser are you using?

none

### What operating system are you using?

linux

### How are you deploying your application?

vercel

### Describe the Bug

17:30:29.881  	Cloning github.com/Manonicu/site (Branch: master, Commit: fa2fe5b)
17:30:30.567  	Cloning completed: 685.577ms
17:30:30.606  	Analyzing source code...
17:30:32.278  	Installing build runtime...
17:30:36.852  	Build runtime installed: 4573.424ms
17:30:41.381  	Looking up build cache...
17:30:41.920  	Build cache not found
17:30:43.176  	Installing dependencies...
17:30:43.657  	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
17:30:53.673  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
17:30:53.673  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:30:53.678  	added 507 packages from 606 contributors in 10.054s
17:30:53.835  	81 packages are looking for funding
17:30:53.835  	  run `npm fund` for details
17:30:53.867  	Detected Next.js version: 10.0.10-canary.0
17:30:53.868  	Running "npm run build"
17:30:54.079  	> site@0.1.0 build /vercel/path0
17:30:54.080  	> next build
17:30:55.133  	info  - Creating an optimized production build...
17:30:55.155  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
17:30:55.155  	This information is used to shape Next.js' roadmap and prioritize features.
17:30:55.155  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
17:30:55.155  	https://nextjs.org/telemetry
17:31:06.313  	Failed to compile.
17:31:06.313  	ModuleNotFoundError: Module not found: Error: Can't resolve 'fbjs/lib/warning' in '/vercel/path0/node_modules/gitalk/node_modules/react-dom/lib'
17:31:06.313  	> Build error occurred
17:31:06.314  	Error: > Build failed because of webpack errors
17:31:06.314  	    at /vercel/path0/node_modules/next/dist/build/index.js:15:918
17:31:06.314  	    at runMicrotasks (<anonymous>)
17:31:06.314  	    at processTicksAndRejections (internal/process/task_queues.js:93:5)
17:31:06.315  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
17:31:06.342  	npm ERR! code ELIFECYCLE
17:31:06.342  	npm ERR! errno 1
17:31:06.345  	npm ERR! site@0.1.0 build: `next build`
17:31:06.345  	npm ERR! Exit status 1
17:31:06.345  	npm ERR! 
17:31:06.345  	npm ERR! Failed at the site@0.1.0 build script.
17:31:06.345  	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
17:31:06.355  	npm ERR! A complete log of this run can be found in:
17:31:06.355  	npm ERR!     /vercel/.npm/_logs/2021-03-20T09_31_06_346Z-debug.log
17:31:06.366  	Error: Command "npm run build" exited with 1

### Expected Behavior

none

### To Reproduce

none

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
