### ISSUE TITLE
Adding NODE_OPTIONS='--inspect' Causes Next Dev Server to Fail in 10.0.9

### ISSUE THREAD

**Issue by ospireon** [vercel/next.js#23323]
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

v12.14.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug
Turns out when we upgraded from 9.5.5 to 10.0.9 it broke this advanced debugging feature for me
Following the procedure from the official guide: https://nextjs.org/docs/advanced-features/debugging
When I run npm run dev with the following script in my package.json

  "scripts": {
    "dev": "NODE_OPTIONS='--inspect' next dev",

I get an error (see below). But when I set the 
  "scripts": {
    "dev": "next dev",
I do not get the error below.

events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at ChildProcessWorker.send (/Users/o/projects/project/node_modules/jest-worker/build/workers/ChildProcessWorker.js:286:17)
    at WorkerPool.send (/Users/o/projects/project/node_modules/jest-worker/build/WorkerPool.js:32:34)
    at Farm._process (/Users/o/projects/project/node_modules/jest-worker/build/Farm.js:129:10)
    at Farm._enqueue (/Users/o/projects/project/node_modules/jest-worker/build/Farm.js:152:10)
    at Farm._push (/Users/o/projects/project/node_modules/jest-worker/build/Farm.js:159:12)
    at /Users/o/projects/project/node_modules/jest-worker/build/Farm.js:90:14
    at new Promise (<anonymous>)
    at Farm.doWork (/Users/o/projects/project/node_modules/jest-worker/build/Farm.js:56:12)
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:76:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}

### Expected Behavior

When I run with next dev, the development server does start. Its only that the inspect tag is causing it to fail.

### To Reproduce

To reproduce Im not sure. This used to work fine for me. Then a colleague added server side rendering, I pulled his changes, then changed the script tag, and this issue appeared.

**Comment by ospireon** [comment]
https://github.com/vercel/next.js/issues/22835

This is a duplicate, self-closing

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
