### ISSUE TITLE
'yarn add next' failing with fsevents error: Cannot apply hunk #1

### ISSUE THREAD

**Issue by danroberts** [vercel/next.js#23398]
### What version of Next.js are you using?

N/A

### What version of Node.js are you using?

14.4.0

### What browser are you using?

N/A

### What operating system are you using?

macOs

### How are you deploying your application?

N/A

### Describe the Bug

When running `yarn add next` or running `npx create-next-app` it fails to install with an error that seems to be related to yarn-berry. 

### Expected Behavior

`yarn add next` should work

### To Reproduce

Not sure if this is related to my local computer, but for me, the steps are run 'yarn add next' in a new folder 

extjs-apollo-starter-app % yarn add next
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0000: └ Completed in 3.74s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ isarray@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ isexe@npm:2.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ isobject@npm:2.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ isstream@npm:0.1.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ jest-worker@npm:24.9.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0001: │ Error: fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=495457: Cannot apply hunk #1
    at c (/Users/droberts/.yarn/releases/yarn-berry.js:56:62123)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/droberts/.yarn/releases/yarn-berry.js:56:64265
    at async o (/Users/droberts/.yarn/releases/yarn-berry.js:56:61406)
    at async Object.t.applyPatchFile (/Users/droberts/.yarn/releases/yarn-berry.js:56:64238)
    at async t.PatchFetcher.patchPackage (/Users/droberts/.yarn/releases/yarn-berry.js:56:61161)
    at async E (/Users/droberts/.yarn/releases/yarn-berry.js:42:91151)
    at async /Users/droberts/.yarn/releases/yarn-berry.js:42:91735
    at async /Users/droberts/.yarn/releases/yarn-berry.js:42:92865
➤ YN0013: │ wide-align@npm:1.1.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ xtend@npm:4.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0.62s
➤ YN0000: Failed with errors in 4.36s

**Comment by danroberts** [comment]
Doing a bit more investigation, this is maybe a bug with yarn 2.

**Comment by danroberts** [comment]
I can get around it by doing npx create-next-app --use-npm

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
