### ISSUE TITLE
Jest example does not work with Yarn 2

### ISSUE THREAD

**Issue by brandonchinn178** [vercel/next.js#23413]
### What example does this report relate to?

with-jest

### What version of Next.js are you using?

latest

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

When running the `with-jest` example with Yarn 2, you get errors like
```
  ● Test suite failed to run

    Your application tried to access @babel/runtime, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

    Required package: @babel/runtime (via "@babel/runtime/helpers/interopRequireDefault")
    Required by: .../with-jest-app/__tests__/

      13070 |     enumerable: false
      13071 |   };
    > 13072 |   return Object.defineProperties(new Error(message), {
            |                                  ^
      13073 |     code: { ...propertySpec,
      13074 |       value: code
      13075 |     },

      at internalTools_makeError (.pnp.js:13072:34)
      at resolveToUnqualified (.pnp.js:14031:23)
      at resolveRequest (.pnp.js:14129:29)
      at Object.resolveRequest (.pnp.js:14207:26)
```

I was getting this in my project too when upgrading from Next 10.0.1 => 10.0.9 (probably due to https://github.com/vercel/next.js/pull/18768; see https://github.com/vercel/next.js/pull/18921). It would be nice to see documentation somewhere for what you need to have installed for yarn 2

### Expected Behavior

The example should work for yarn 2

### To Reproduce

1. `yarn create next-app --example with-jest with-jest-app`
2. `yarn set version berry`
3. `yarn`
4. Edit `jest.config.js`, change `<rootDir>/node_modules/babel-jest` to `babel-jest`
5. `yarn test`

**Comment by balazsorban44** [comment]
The`with-jest` example doesn't have the line you are referring to anymore.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
