### ISSUE TITLE
Importing and using `{ Link } from 'next/link'` gives a non-specific, unhelpful error message

### ISSUE THREAD

**Issue by jthistle** [vercel/next.js#23451]
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chromium

### What operating system are you using?

Ubuntu 20.04.2 LTS

### How are you deploying your application?

next dev

### Describe the Bug

If I import the Link component incorrectly:

```js
import { Link } from 'next/link';  // should be just   import Link from ...
```

and then use it:

```jsx
export default Test = () => (
  <Link href="/" />
)
```

I get a non-specific error which does little to help diagnose the problem:

```
Check your code at index.js:29.
    at Test (webpack-internal:///./src/components/Test/index.js:46:7)
    [...]
    at AppContainer (/[removed]/node_modules/next/dist/next-server/server/render.js:28:907)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at ReactDOMServerRenderer.render (/[removed]/node_modules/react-dom/cjs/react-dom-server.node.development.js:4053:17)
    at ReactDOMServerRenderer.read (/[removed]/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/[removed]/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/[removed]/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:141:19)
    at loadGetInitialProps (/[removed]/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/[removed]/node_modules/next/dist/next-server/server/render.js:54:1142)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

This sort of tells me where it's going wrong, but doesn't tell me why. Only through trial and error did I figure it out.

### Expected Behavior

Maybe, don't export  `Link` as a named export at all, so that I get an error when trying to import it as such. Or, provide a specific warning when this is done. 

### To Reproduce

To reproduce, see **Describe the Bug**.

**Comment by sk91** [comment]
@jthistle according to https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx there is no named export for `Link`

as far as I've seen there is a convention in next to alway export main modules as default exports

**Comment by jthistle** [comment]
closing because I realise this is actually not an issue - it _does_ give a specific error, I just can't read:

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**`you might have mixed up default and named imports.`**

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
