### ISSUE TITLE
ESLint integration broken under Yarn 2 Plug'n'Play

### ISSUE THREAD

**Issue by jacobwgillespie** [vercel/next.js#23510]
### What version of Next.js are you using?

10.1.0

### What version of Node.js are you using?

14.15.5

### What browser are you using?

N/A

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

It appears that the ESLint integration introduced in #22437 breaks `next build` when using Yarn 2 Plug'n'Play (PnP). When PnP is enabled, accessing a dependency that is not listed in `package.json` as a dependency (regular dep or peer dep) is considered an error, and Next attempts to resolve `@next/eslint-plugin-next` as a dependency in the user's app project context. 

This means that unless users explicitly install `@next/eslint-plugin-next` alongside `next` in their projects, or Next changes how it attempts to resolve that dependency, `next build` will fail.

### Expected Behavior

I would expect `next build` to succeed if the user only has `next` installed.

### To Reproduce

1. Create a new blank project with `next` 10.1.0
2. Use Yarn 2 + Plug'n'Play
3. Run `yarn next build`

👉 Here is a repo demonstrating the issue: https://github.com/jacobwgillespie/nextjs-eslint-issue

Example output:

```console
$ yarn build
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://nextjs.org/docs/messages/react-version
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types ...
info  - No ESLint configuration was detected, but checks from the Next.js ESLint plugin were included automatically (see https://nextjs.org/docs/basic-features/eslint).

> Build error occurred
Error: Failed to load plugin '@next/next' declared in 'BaseConfig': Your application tried to access @next/eslint-plugin-next, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @next/eslint-plugin-next (via "@next/eslint-plugin-next")
Required by: /Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/

Require stack:
- /Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/__placeholder__.js
Referenced from: BaseConfig
    at internalTools_makeError (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.pnp.js:9845:34)
    at resolveToUnqualified (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.pnp.js:10804:23)
    at resolveRequest (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.pnp.js:10902:29)
    at Object.resolveRequest (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.pnp.js:10980:26)
    at Function.external_module_.Module._resolveFilename (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.pnp.js:10078:34)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.resolve (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.yarn/cache/eslint-npm-7.9.0-d45daba7d6-295fe8c442.zip/node_modules/eslint/lib/shared/relative-module-resolver.js:40:50)
    at ConfigArrayFactory._loadPlugin (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.yarn/cache/eslint-npm-7.9.0-d45daba7d6-295fe8c442.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:1010:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.yarn/cache/eslint-npm-7.9.0-d45daba7d6-295fe8c442.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:830:29)
    at ConfigArrayFactory._loadExtends (/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction/.yarn/cache/eslint-npm-7.9.0-d45daba7d6-295fe8c442.zip/node_modules/eslint/lib/cli-engine/config-array-factory.js:774:29) {
  type: 'Error',
  messageTemplate: 'plugin-missing',
  messageData: {
    pluginName: '@next/eslint-plugin-next',
    resolvePluginsRelativeTo: '/Users/jacobwgillespie/Code/jacobwgillespie/nextjs-issue-reproduction',
    importerName: 'BaseConfig'
  }
}
```

**Comment by housseindjirdeh** [comment]
Thanks for flagging this! We've [reverted](https://github.com/vercel/next.js/pull/23521) the ESLint integration and I'm rolling out some changes in a new [PR](https://github.com/vercel/next.js/pull/22437) that would require developers to have all required dependencies installed locally in their application in order to use the default ESLint setup. 

That should ensure this doesn't happen anymore :)

**Comment by jacobwgillespie** [comment]
Perfect, thank you so much @housseindjirdeh!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
