### ISSUE TITLE
TypeError: _jestWorker.default is not a constructor

### ISSUE THREAD

**Issue by felixmosh** [vercel/next.js#23528]
### What version of Next.js are you using?

10.1.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome 88

### What operating system are you using?

macOS

### How are you deploying your application?

other

### Describe the Bug

When enabling webpack 5 with `next-pwa` it throws

```js
ERROR in worker-7d0pvWarcI3nxcmEFPPS9.js from Terser
TypeError: _jestWorker.default is not a constructor
    at getWorker (/Users/***/Projects/oss/next-pwa/examples/custom-worker/node_modules/next/dist/compiled/webpack/bundle5.js:28270:9)
    at /Users/***/Projects/oss/next-pwa/examples/custom-worker/node_modules/next/dist/compiled/webpack/bundle5.js:28367:41
    at /Users/***/Projects/oss/next-pwa/examples/custom-worker/node_modules/next/dist/compiled/webpack/bundle5.js:26276:31
    at run (/Users/***/Projects/oss/next-pwa/examples/custom-worker/node_modules/next/dist/compiled/webpack/bundle5.js:26276:43)
    at /Users/***/Projects/oss/next-pwa/examples/custom-worker/node_modules/next/dist/compiled/webpack/bundle5.js:26298:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)

webpack 5.28.0 compiled with 1 error in 955 ms
```

### Expected Behavior

It should not throw

### To Reproduce

https://github.com/felixmosh/next-v10.1.1-pwa-bug

**Comment by davidpfahler** [comment]
This seems to have [happened before](https://github.com/vercel/next.js/issues/24027#issuecomment-841131151). I have the same issue currently and cannot continue development. :(

**Comment by eric-burel** [comment]
It happens when you have 2 versions of webpack installed, Webpack 4 might be still around when this happens.

**Comment by balazsorban44** [comment]
I could not reproduce this. Next.js now uses Webpack 5 by default BTW.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
