### ISSUE TITLE
build fails when optimizeFonts is enabled

### ISSUE THREAD

**Issue by fpahl** [vercel/next.js#23555]
### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

15.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Wenn optimizeFonts is enabled, the build fails with the following error:
```
> test-optimize-fonts@0.1.0 build
... 
[==  ] info  - Generating static pages (0/3)
Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'type' of null
    at /Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:952:13
    at aa (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:19:58)
    at T (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:17:222)
    at V (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:18:229)
    at X (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:19:321)
    at Object.map (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:20:205)
    at Head.makeStylesheetInert (/Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:951:36)
    at Head.render (/Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:1006:23)
    at d (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
    at $a (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'type' of null
    at /Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:952:13
    at aa (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:19:58)
    at T (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:17:222)
    at V (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:18:229)
    at X (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:19:321)
    at Object.map (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:20:205)
    at Head.makeStylesheetInert (/Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:951:36)
    at Head.render (/Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:1006:23)
    at d (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
    at $a (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'type' of null
    at /Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:952:13
    at aa (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:19:58)
    at T (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:17:222)
    at V (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:18:229)
    at X (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:19:321)
    at Object.map (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react/cjs/react.production.min.js:20:205)
    at Head.makeStylesheetInert (/Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:951:36)
    at Head.render (/Users/florian.pahl/test/test-optimize-fonts/.next/server/pages/_document.js:1006:23)
    at d (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:38:231)
    at $a (/Users/florian.pahl/test/test-optimize-fonts/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
        /
        /404
        /500
    at /Users/florian.pahl/test/test-optimize-fonts/node_modules/next/dist/export/index.js:31:1106
    at async Span.traceAsyncFn (/Users/florian.pahl/test/test-optimize-fonts/node_modules/next/dist/telemetry/trace/trace.js:5:584)
    at async /Users/florian.pahl/test/test-optimize-fonts/node_modules/next/dist/build/index.js:43:49
    at async Span.traceAsyncFn (/Users/florian.pahl/test/test-optimize-fonts/node_modules/next/dist/telemetry/trace/trace.js:5:584)
    at async /Users/florian.pahl/test/test-optimize-fonts/node_modules/next/dist/build/index.js:25:1475
    at async Span.traceAsyncFn (/Users/florian.pahl/test/test-optimize-fonts/node_modules/next/dist/telemetry/trace/trace.js:5:584)
npm ERR! code 1
npm ERR! path /Users/florian.pahl/test/test-optimize-fonts
npm ERR! command failed
npm ERR! command sh -c next build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/florian.pahl/.npm/_logs/2021-03-30T15_38_52_029Z-debug.log
```

### Expected Behavior

Build should finish without exception.

### To Reproduce

This happens, when there is an empty node in the header in a custom _document.js.
Example repo: https://github.com/fpahl/optimize-fonts-test

Suggestion: compare to `c === null` in [_document.js](https://github.com/vercel/next.js/blob/canary/packages/next/pages/_document.tsx) line 347.

**Comment by janicklas-ralph** [comment]
Fixed in this PR - https://github.com/vercel/next.js/pull/21676
