### ISSUE TITLE
webpack 5: (node:132331) UnhandledPromiseRejectionWarning: ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by geryit** [vercel/next.js#23554]
### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

nodemon server.js

### Describe the Bug

I have the latest next.js and added webpack flag: 
```
module.exports = {
  future: {
    webpack5: true,
  },
}
```
started to see this error when I run dev on local:
```
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
Defining routes from exportPathMap
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://nextjs.org/docs/messages/built-in-css-disabled

(node:132331) UnhandledPromiseRejectionWarning: ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].node has an unknown property 'fs'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
 - configuration[1].node has an unknown property 'fs'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
    at validate (/home/goksel/Sites/carbon-website-next/node_modules/next/dist/compiled/schema-utils3/index.js:1:153657)
    at validateSchema (/home/goksel/Sites/carbon-website-next/node_modules/next/dist/compiled/webpack/bundle5.js:130667:2)
    at create (/home/goksel/Sites/carbon-website-next/node_modules/next/dist/compiled/webpack/bundle5.js:134089:4)
    at webpack (/home/goksel/Sites/carbon-website-next/node_modules/next/dist/compiled/webpack/bundle5.js:134126:32)
    at f (/home/goksel/Sites/carbon-website-next/node_modules/next/dist/compiled/webpack/bundle5.js:92375:15)
    at HotReloader.start (/home/goksel/Sites/carbon-website-next/node_modules/next/dist/server/hot-reloader.js:16:415)
    at async DevServer.prepare (/home/goksel/Sites/carbon-website-next/node_modules/next/dist/server/next-dev-server.js:15:453)
    at async /home/goksel/Sites/carbon-website-next/server.js:107:3
(Use `node --trace-warnings ...` to show where the warning was created)
(node:132331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:132331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I remove the flag, dev works.

### Expected Behavior

run dev with no error

### To Reproduce

add webpack 5 flag to next config and run yarn `node server.js`

**Comment by geryit** [comment]
I had `config.node = {fs: "empty"}` in `next.config.js`. removing that fixed it

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
