### ISSUE TITLE
Requested and resolved page mismatch when building using SSG with fallback on Vercel

### ISSUE THREAD

**Issue by Vadorequest** [vercel/next.js#23657]
### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

Vercel

### Describe the Bug

I'm building a back-office where a user can create projects. Because I don't know ahead-of-time which projects pages to create, and because I prefer to do it on-demand, I've configured `getStaticPaths` to use an empty `projectId`, with fallback `true`.

```tsx
export const getCoreStaticPaths: GetStaticPaths<CommonServerSideParams> = async (context: GetStaticPathsContext): Promise<StaticPathsOutput> => {
  const paths: StaticPath[] = map(supportedLocales, (supportedLocale: I18nLocale): StaticPath => {
    return {
      params: {
        locale: supportedLocale.name,
        projectId: '', // We don't generate all pages for all projects ahead of time, so we use an empty projectId with fallback: true to generate pages dynamically on-demand
      },
    };
  });

  return {
    fallback: true,
    paths,
  };
};
```

The path of the failing file is `src/pages/[locale]/builder/[projectId]/settings.tsx`.

```
10:35:24.386  	info  - Using external babel configuration from /vercel/workpath0/babel.config.js
10:36:40.348  	info  - Compiled successfully
10:36:40.348  	info  - Collecting page data...
10:36:42.619  	> Build error occurred
10:36:42.621  	Error: Requested and resolved page mismatch: /en/builder//settings /en/builder/settings
10:36:42.621  	    at normalizePagePath (/vercel/workpath0/node_modules/next/dist/next-server/server/normalize-page-path.js:4:78)
10:36:42.621  	    at /vercel/workpath0/node_modules/next/dist/export/index.js:23:151
10:36:42.621  	    at Array.map (<anonymous>)
10:36:42.621  	    at /vercel/workpath0/node_modules/next/dist/export/index.js:23:58
10:36:42.621  	    at async Span.traceAsyncFn (/vercel/workpath0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
10:36:42.621  	    at async /vercel/workpath0/node_modules/next/dist/build/index.js:43:49
10:36:42.621  	    at async Span.traceAsyncFn (/vercel/workpath0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
10:36:42.621  	    at async /vercel/workpath0/node_modules/next/dist/build/index.js:25:1475
10:36:42.621  	    at async Span.traceAsyncFn (/vercel/workpath0/node_modules/next/dist/telemetry/trace/trace.js:5:584)
10:36:42.701  	error Command failed with exit code 1.
10:36:42.701  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:36:42.711  	Error: Command "yarn run build" exited with 1
```

### Expected Behavior

Maybe I'm misusing the SSG mode, but my understanding is that it shouldn't try to generate pages because `fallback: true`.

It works locally, but it doesn't work when building on Vercel.

### To Reproduce

Use a page with `getStaticPaths` returning paths with `projectId: ''` and a file like `src/pages/[locale]/builder/[projectId]/settings.tsx`

**Comment by Vadorequest** [comment]
I've fixed the issue by using `projectId: '0'` in `getStaticPaths` but this really feels like monkey-patching. Next.js shouldn't try to generate those pages in the first place.

Here is the output log:

```

11:02:54.060 | info  - Creating an optimized production build...
-- | --
11:02:54.269 | [webpack] Building release "v5.1.x-rc-dashboard" using NODE_ENV="production" with IS_SERVER_INITIAL_BUILD="1"
11:02:54.559 | info  - Using external babel configuration from /vercel/workpath0/babel.config.js
11:04:09.906 | info  - Compiled successfully
11:04:09.906 | info  - Collecting page data...
11:04:12.314 | info  - Generating static pages (0/17)
11:04:13.505 | info  - Generating static pages (4/17)
11:04:13.643 | info  - Generating static pages (8/17)
11:04:15.574 | pageProps.serializedDataset length (bytes) 56
11:04:15.626 | pageProps.serializedDataset length (bytes) 56
11:04:15.652 | pageProps.serializedDataset length (bytes) 56
11:04:15.680 | pageProps.serializedDataset length (bytes) 56
11:04:15.689 | info  - Generating static pages (12/17)
11:04:15.698 | pageProps.serializedDataset length (bytes) 56
11:04:15.715 | pageProps.serializedDataset length (bytes) 56
11:04:15.755 | pageProps.serializedDataset length (bytes) 56
11:04:15.756 | pageProps.serializedDataset length (bytes) 56
11:04:15.913 | pageProps.serializedDataset length (bytes) 56
11:04:15.923 | userSession {
11:04:15.923 | mutate: [Function (anonymous)],
11:04:15.923 | refresh: [Function: refresh],
11:04:15.923 | sessionEphemeralId: '8f792c70-945b-11eb-945a-bd447249145d',
11:04:15.923 | isSessionReady: false
11:04:15.923 | }
11:04:15.952 | info  - Generating static pages (17/17)
11:04:15.953 | info  - Finalizing page optimization...
11:04:15.966 | Page                                                           Size     First Load JS
11:04:15.966 | ┌   /_app                                                      0 B             540 kB
11:04:15.966 | ├ ● /[locale]                                                  29 kB           727 kB
11:04:15.966 | ├   └ /en
11:04:15.966 | ├ ● /[locale]/builder/[projectId]                              531 kB         1.23 MB
11:04:15.966 | ├   └ /en/builder/0
11:04:15.966 | ├ ● /[locale]/builder/[projectId]/settings                     616 B           698 kB
11:04:15.966 | ├   └ /en/builder/0/settings
11:04:15.966 | ├ ● /[locale]/builder/[projectId]/theme                        613 B           698 kB
11:04:15.967 | ├   └ /en/builder/0/theme
11:04:15.967 | ├ ● /[locale]/builder/[projectId]/user-journey                 619 B           698 kB
11:04:15.967 | ├   └ /en/builder/0/user-journey
11:04:15.967 | ├ ● /[locale]/builder/[projectId]/variables-set                622 B           698 kB
11:04:15.967 | ├   └ /en/builder/0/variables-set
11:04:15.967 | ├ ● /[locale]/builder/dashboard                                227 B           698 kB
11:04:15.967 | ├   └ /en/builder/dashboard
11:04:15.967 | ├ ● /[locale]/pageTemplateSSG                                  840 B           699 kB
11:04:15.967 | ├   └ /en/pageTemplateSSG
11:04:15.967 | ├ λ /[locale]/pageTemplateSSR                                  1.03 kB         699 kB
11:04:15.967 | ├ ○ /404                                                       1.05 kB         699 kB
11:04:15.967 | ├ λ /api/autoRedirectToLocalisedPage                           0 B             540 kB
11:04:15.967 | ├ λ /api/error                                                 0 B             540 kB
11:04:15.967 | ├ λ /api/login                                                 0 B             540 kB
11:04:15.967 | ├ λ /api/logout                                                0 B             540 kB
11:04:15.967 | ├ λ /api/preview                                               0 B             540 kB
11:04:15.967 | ├ λ /api/startVercelDeployment                                 0 B             540 kB
11:04:15.967 | ├ λ /api/status                                                0 B             540 kB
11:04:15.967 | ├ λ /api/user                                                  0 B             540 kB
11:04:15.967 | └ λ /api/webhooks/deploymentCompleted                          0 B             540 kB
11:04:15.967 | + First Load JS shared by all                                  540 kB
11:04:15.967 | ├ chunks/0a301732.544596.js                                  19.4 kB
11:04:15.967 | ├ chunks/5f9fef99.2633a8.js                                  20.5 kB
11:04:15.967 | ├ chunks/95bf7d1f8e18bb1c7c4cb6268b64a55ec90344e8.181f24.js  323 kB
11:04:15.967 | ├ chunks/a9a7754c.541d65.js                                  834 B
11:04:15.967 | ├ chunks/cb1608f2.271fcd.js                                  6.1 kB
11:04:15.967 | ├ chunks/commons.343ffe.js                                   36.3 kB
11:04:15.967 | ├ chunks/ee1a1621f0a39b58ac2f2174bdea64728e2deab1.8fd05f.js  4.14 kB
11:04:15.967 | ├ chunks/framework.6fff95.js                                 42.2 kB
11:04:15.967 | ├ chunks/main.dae9cc.js                                      6.85 kB
11:04:15.967 | ├ chunks/pages/_app.d697e7.js                                79.7 kB
11:04:15.967 | ├ chunks/webpack.245f04.js                                   800 B
11:04:15.967 | └ css/f11b9bb1e016129f8af3.css                               29 kB
11:04:15.968 | λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
11:04:15.968 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
11:04:15.968 | ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
11:04:15.968 | (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
11:04:16.159 | Done in 118.52s.
11:04:32.938 | Traced Next.js server files in: 16743.623ms
11:04:48.346 | Created all serverless functions in: 15403.582ms
11:04:50.480 | Uploading build outputs...
11:04:52.668 | Deploying build outputs...
11:05:01.893 | Build completed. Populating build cache...


```

**Comment by ijjk** [comment]
Hi, an empty string shouldn't be provided as a value for a param from `getStaticPaths`, only paths you want prerendered should be returned from `getStaticPaths`, with `fallback: true` new paths are already created on-demand see the related documentation for this feature here https://nextjs.org/docs/basic-features/data-fetching#fallback-true

**Comment by Vadorequest** [comment]
I think that's what I did in the first place but then the build failed for another reason. I'll try again by removing the `projectId` in `getStaticPaths` and let you know.

**Comment by Vadorequest** [comment]
@ijjk Here is what happens then:
![image](https://user-images.githubusercontent.com/3807458/113780652-c89e3280-972f-11eb-9377-739b51207123.png)

Using:

```tsx
export const getBuilderLayoutStaticPaths: GetStaticPaths<CommonServerSideParams> = async (context: GetStaticPathsContext): Promise<StaticPathsOutput> => {
  const paths: StaticPath[] = map(supportedLocales, (supportedLocale: I18nLocale): StaticPath => {
    return {
      params: {
        locale: supportedLocale.name,
      },
    };
  });

  return {
    fallback: true,
    paths,
  };
};
```

I suppose it's because I try to pre-render pages while providing only part of the variables.

I guess I shouldn't specify any path then, and simply use `fallback: true` in such case.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
