### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined in next v10

### ISSUE THREAD

**Issue by tar-aldev** [vercel/next.js#23720]
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When using next js with react 16 I am getting 
```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (webpack-internal:///../../node_modules/next/dist/next-server/lib/router/router.js:591)
    at eval (webpack-internal:///../../node_modules/next/dist/next-server/lib/router/router.js:961)
    at Object.eval (webpack-internal:///../../node_modules/next/dist/next-server/lib/router/router.js:1541)
    at eval (webpack-internal:///../../node_modules/next/dist/next-server/lib/router/router.js:1601)
    at Object.../../node_modules/next/dist/next-server/lib/router/router.js (main.js:871)
    at __webpack_require__ (webpack.js:873)
    at fn (webpack.js:151)
    at Object.eval (webpack-internal:///../../node_modules/next/dist/client/index.js:67)
    at eval (webpack-internal:///../../node_modules/next/dist/client/index.js:903)
    at Object.../../node_modules/next/dist/client/index.js (main.js:670)
```
I am using @nrwl/nx to setup react and next applications.
Here is an extract from my package.json and versions.
We migrated to next js 10, but react is at v16.
```
"dependencies": {
    "@babel/runtime": "^7.13.10",
    "core-js": "^3.6.5",
    "document-register-element": "1.13.1",
    "next": "10.0.9",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-router-dom": "5.2.0",
    "regenerator-runtime": "^0.13.7",
    "tslib": "^2.0.0"
  },

"devDependencies": {
    "@babel/core": "7.9.6",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "7.9.4",
    "@babel/preset-typescript": "7.9.0",
    "@nrwl/cli": "11.6.1",
    ...
```
You can notice that react app is working just fine while nextjs app crashes.

### Expected Behavior

Nextjs app should work fine.
If there are some incompatible versions of next and react it should be noted somewhere in the docs. Some useful warnings in the console would be much appreciated.
(it is quite strange that reactjs can work with babel versions mentioned above, but nextjs fails to do so)

### To Reproduce

create new workspace with nextjs
`npx create-nx-workspace --preset=next`
`nx g @nrwl/react:application plain-react` 

Downgrade react and react-dom to 16.14.0

Here is a minimal repo where this issue can be seen
https://github.com/tar-aldev/regenerator-error-next

Just clone it run 
`npm i`
`npm run plain-react`
`npm run next-react`

Go to localhost:4200 and you'll see blank screen and error in console
Go to localhost:3000 and you'll see react app is working fine

**Comment by alecwhittington** [comment]
I am seeing the same issue, using NX like you as well.

**Comment by emcfarlane** [comment]
I'm seeing the same issue but with react 17.03:

```
ReferenceError: regeneratorRuntime is not defined
    at create (//app/node_modules/zustand/index.js:156:31)
    at eval (webpack-internal:///./pages/something.tsx:14:64)
    at Object../pages/something.tsx (//app/.next/server/pages/something.js:22:1)
    at __webpack_require__ (//app/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (//app/.next/server/pages/something.js:54:52)
    at //app/.next/server/pages/something.js:55:28
    at Object.<anonymous> (//app/.next/server/pages/something.js:58:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at requirePage (//app/node_modules/next/dist/next-server/server/require.js:1:1184)
    at loadComponents (//app/node_modules/next/dist/next-server/server/load-components.js:1:948)
    at async DevServer.findPageComponents (//app/node_modules/next/dist/next-server/server/next-server.js:77:257)
 ```
 Testcase is a simple Zustand state store.

**Comment by balazsorban44** [comment]
Hi, could you verify if this is still the case with the `latest` of Next.js?

**Comment by imdavidmin** [comment]
@balazsorban44  I have jut seen this running Next 12.0.4. I'm not able to test newer versions because of issues with yarn PnP support bug.

**Comment by balazsorban44** [comment]
`12.0.8` just came out with a few fixes, and also there is an open PR that would help further https://github.com/vercel/next.js/pull/33236

**Comment by imdavidmin** [comment]
@balazsorban44  Am still running into PnP issues with 12.0.8 but seems to be having the same issue now with 12.0.4... Trying to diagnose the issue my end right now.

**Comment by imdavidmin** [comment]
@balazsorban44  The issue with PnP in 12.0.8 is opened as another issue #33282

**Comment by imdavidmin** [comment]
@balazsorban44  Seems like the regeneratorRuntime issue is triggered by having a webpack config as follows: 
```
module.exports = {
    experimental: {
        swcFileReading: false,
    },
    webpack: (config, options) => {
        config.module.rules.push({
            test: /\.[tj]sx?$/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-typescript']
                }
            },
        })
        return config
    }
};
```

Not sure if I'm doing anything particularly wrong here or if this is a bug.
```
"babel-loader": "^8.2.3",
"@babel/core": "^7.16.7",
"@babel/preset-env": "^7.16.8",
"@babel/preset-react": "^7.16.7",
"@babel/preset-typescript": "^7.16.7",
```

**Comment by balazsorban44** [comment]
After some research, this seems to be a reoccurring issue with Nx, I suggest you post this there to get help.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
