### ISSUE TITLE
Cookie locale detection is broken if cookie name is similar with NEXT_COOKIE

### ISSUE THREAD

**Issue by timbset** [vercel/next.js#23787]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.14.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I renamed cookie name from NEXT_COOKIE to NEXT_COOKIE2 and rendering is permanently the the following error:
```
message=Cannot read property 'toLowerCase' of undefined, stack=TypeError: Cannot read property 'toLowerCase' of undefined
    at find (<path>/node_modules/next/next-server/lib/i18n/detect-locale-cookie.ts:7:39)
    at Array.find (<anonymous>)
    at detectLocaleCookie (<path>/node_modules/next/next-server/lib/i18n/detect-locale-cookie.ts:6:20)
    at DevServer.requestHandler [as handleRequest] (<path>/node_modules/next/next-server/server/next-server.ts:436:28)
    at <path>/node_modules/next/server/next.ts:38:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Expected Behavior

I expect that all the similar names will be ignored and check will go to the step with accept-language header.

### To Reproduce

Just name some cooke NEXT_COOKIE2 or something that contain NEXT_COOKIE and any page will be failed.

**Comment by timbset** [comment]
#23788

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
