### ISSUE TITLE
Error: Next build is returning error with jest

### ISSUE THREAD

**Issue by LeonelV22** [vercel/next.js#24027]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.14.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I'm getting this error when I do a _next build_ or _next start_

```
TypeError: _jestWorker.Worker is not a constructor
at loadWebpackHook (/node_modules/next/dist/next-server/server/config-utils.js:24:554)
at loadConfig (/node_modules/next/dist/next-server/server/config.js:7:595)
at async Span.traceAsyncFn (/node_modules/next/dist/telemetry/trace/trace.js:5:584)
at async /node_modules/next/dist/build/index.js:2:127
at async Span.traceAsyncFn (/node_modules/next/dist/telemetry/trace/trace.js:5:584)
```

### Expected Behavior

Build or start the server

### To Reproduce

I'm just doing a _next build_ or _next start_

**Comment by davidpfahler** [comment]
@LeonelV22 How did you manage to fix this? I am running into the same error all of a sudden.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
