### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]

### ISSUE THREAD

**Issue by saftsoppa** [vercel/next.js#24047]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.14.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

While redirecting, application responds with Internal Server Error when sending request with invalid characters in query key.

### Expected Behavior

Normal redirect is performed

### To Reproduce

1. Send the request. 
If `trailingSlash` is enabled, `curl "http://localhost:3000/anypath?%E2%80%9D"`
If `trailingSlash` is **not** enabled, `curl "http://localhost:3000/anypath/?%E2%80%9D"`

2. `Internal Server Error` is returned
https://nodejs.org/api/http.html#http_response_setheader_name_value
> Attempting to set a header field name or value that contains invalid characters will result in a TypeError being thrown.

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    at ServerResponse.setHeader (node:_http_outgoing:576:3)
    at Object.fn (/node_modules/next/next-server/server/next-server.ts:893:19)
    at Router.execute (/node_modules/next/next-server/server/router.ts:342:40)
    at DevServer.run (/node_modules/next/next-server/server/next-server.ts:1227:41)
    at DevServer.run (/node_modules/next/server/next-dev-server.ts:419:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at DevServer.handleRequest (/node_modules/next/next-server/server/next-server.ts:573:14) {
  code: 'ERR_INVALID_CHAR'
}
```

**Comment by ryok90** [comment]
Hello!
Is there any word on this issue?
