### ISSUE TITLE
TypeError: e.on is not a function when using example with-zones

### ISSUE THREAD

**Issue by niklasgrewe** [vercel/next.js#24177]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.14.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When i run the [with-zones](https://github.com/vercel/next.js/tree/canary/examples/with-zones) example and serving `http://localhost:3000/blog` i get the following error:

```
TypeError: e.on is not a function
    at Array.stream (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/compiled/http-proxy/index.js:1:15064)
    at ProxyServer.<anonymous> (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/compiled/http-proxy/index.js:1:12072)
    at Object.fn (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/next-server.js:58:278)
    at Router.execute (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/router.js:25:83)
    at async DevServer.run (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/next-server.js:69:1042)
    at async DevServer.handleRequest (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/next-server.js:34:504)
    at async imageOptimizer (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/image-optimizer.js:3:4266)
    at async Router.execute (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/next-server.js:69:1042)
    at async DevServer.handleRequest (/Users/niklas/DEV/with-zones-app/home/node_modules/next/dist/next-server/server/next-server.js:34:504)
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at connResetException (node:internal/errors:642:14)
    at TLSSocket.socketOnEnd (node:_http_client:496:23)
    at TLSSocket.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketOnEnd (node:_http_client:496:9)
    at TLSSocket.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ECONNRESET'
}
error Command failed with exit code 1.
```
i noticed that the image from `/blog/static/nextjs.png` can't be loaded.

### Expected Behavior

When i serve `http://localhost:3000/blog` the image from the url `/blog/static/nextjs.png` should be loaded, the error `TypeError: e.on is not a function` should disappear and the dev server should not hang up

### To Reproduce

1. create a new next app with the multi-zones example

```
yarn create next-app --example with-zones with-zones-app
```

2. install all dependencies in `home` and `blog`

```
cd home
yarn
cd ..
cd blog
yarn
```

3. start the `/home`

```
cd home
yarn dev
```

4. visit `http://localhost:3000/blog`

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
