### ISSUE TITLE
Local Build working but Vercel build failing

### ISSUE THREAD

**Issue by sauloquirino** [vercel/next.js#24664]
### What version of Next.js are you using?

10.1.1

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

yarn build (local) vercel --prod (remote)

### Describe the Bug

My build works fine locally but fails in the remote deployment to vercel.

Here's the error message:
`2021-04-30T17:45:00.245Z  > Build error occurred
2021-04-30T17:45:00.252Z  TypeError: Cannot read property 'javascript' of undefined
2021-04-30T17:45:00.252Z      at /vercel/path0/node_modules/terser-webpack-plugin/dist/index.js:572:38
2021-04-30T17:45:00.252Z      at SyncHook.eval [as call] (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43421:10), <anonymous>:71:1)
2021-04-30T17:45:00.252Z      at SyncHook.lazyCompileHook (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43372:20)
2021-04-30T17:45:00.252Z      at Compiler.newCompilation (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:53143:26)
2021-04-30T17:45:00.252Z      at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:53179:29
2021-04-30T17:45:00.252Z      at AsyncSeriesHook.eval [as callAsync] (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43435:10), <anonymous>:6:1)
2021-04-30T17:45:00.252Z      at AsyncSeriesHook.lazyCompileHook (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43372:20)
2021-04-30T17:45:00.252Z      at Compiler.compile (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:53174:28)
2021-04-30T17:45:00.252Z      at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:52833:11
2021-04-30T17:45:00.252Z      at Compiler.readRecords (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:53041:11)
2021-04-30T17:45:00.252Z      at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:52830:10
2021-04-30T17:45:00.253Z      at AsyncSeriesHook.eval [as callAsync] (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43435:10), <anonymous>:6:1)
2021-04-30T17:45:00.253Z      at AsyncSeriesHook.lazyCompileHook (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43372:20)
2021-04-30T17:45:00.253Z      at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:52827:19
2021-04-30T17:45:00.253Z      at AsyncSeriesHook.eval [as callAsync] (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43435:10), <anonymous>:15:1)
2021-04-30T17:45:00.253Z      at AsyncSeriesHook.lazyCompileHook (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle4.js:43372:20)
2021-04-30T17:45:00.272Z  error Command failed with exit code 1.
2021-04-30T17:45:00.272Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-04-30T17:45:00.298Z  Error: Command "yarn run build" exited with 1` 

### Expected Behavior

Consistent behavior in both deployments

### To Reproduce

yarn build
vercel --prod

**Comment by krychaxp** [comment]
can you show code of your app?
