### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by maximegheraille** [vercel/next.js#24723]
### What example does this report relate to?

with-typescript

### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying your application?

none

### Describe the Bug

Hi,

I am getting problem with creating a build version via `npm run build` with the typescript example. My personal project fails at every build. So I made a clean copy from the typescript example but even without changing the code it fails.

this is the error
```
[=   ] info  - Generating static pages (0/9)npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! with-typescript@1.0.0 build: `next build`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the with-typescript@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

this is from the logs.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle with-typescript@1.0.0~prebuild: with-typescript@1.0.0
6 info lifecycle with-typescript@1.0.0~build: with-typescript@1.0.0
7 verbose lifecycle with-typescript@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle with-typescript@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Projects\nextjsbug\with-typescript-app\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Maxime\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Maxime\AppData\Local\Programs\Python\Python39\;C:\Users\Maxime\AppData\Local\Microsoft\WindowsApps;C:\Users\Maxime\AppData\Local\GitHubDesktop\bin;D:\Microsoft VS Code\bin;C:\Users\Maxime\AppData\Roaming\npm;D:\Pycharm\PyCharm Community Edition 2020.3.3\bin;
9 verbose lifecycle with-typescript@1.0.0~build: CWD: D:\Projects\nextjsbug\with-typescript-app
10 silly lifecycle with-typescript@1.0.0~build: Args: [ '/d /s /c', 'next build' ]
11 silly lifecycle with-typescript@1.0.0~build: Returned: code: 3221225477  signal: null
12 info lifecycle with-typescript@1.0.0~build: Failed to exec build script
13 verbose stack Error: with-typescript@1.0.0 build: `next build`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid with-typescript@1.0.0
15 verbose cwd D:\Projects\nextjsbug\with-typescript-app
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.15.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 3221225477
22 error with-typescript@1.0.0 build: `next build`
22 error Exit status 3221225477
23 error Failed at the with-typescript@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]
```

### Expected Behavior

I expect it to build without error

### To Reproduce

1. `npx create-next-app --example with-typescript with-typescript-app`
2. `npm run dev`
3. `npm run build `

**Comment by charliematters** [comment]
I'll add myself here too. Upgraded from 10.1 to 10.2 on a windows dev machine and it won't run `yarn dev` any more

**Comment by thomasledoux1** [comment]
I'm getting the same error.
Using 10.2, node v14.15.5. 
`Npm run dev`  works fine, `npm run build` throws this error:
```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle with-typescript@1.0.0~prebuild: with-typescript@1.0.0
6 info lifecycle with-typescript@1.0.0~build: with-typescript@1.0.0
7 verbose lifecycle with-typescript@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle with-typescript@1.0.0~build: PATH: C:\Users\tledoux\AppData\Roaming\nvm\v14.15.5\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Projects\sdworx-corporate-nextjs\src\node_modules\.bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Dell\Dell Data Protection\Encryption\;C:\Program Files (x86)\dotnet\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Users\tledoux\AppData\Local\Android\Sdk\platform-tools;C:\Users\tledoux\Documents\windows\bin;C:\Program Files\OpenSSL-Win64\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Git\cmd;C:\Users\tledoux\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\tledoux\AppData\Local\Microsoft\WindowsApps;C:\Users\tledoux\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\tledoux\AppData\Roaming\npm;C:\Users\tledoux\AppData\Roaming\npm\;C:\Users\tledoux\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\GitHub CLI\;C:\Users\tledoux\.dotnet\tools
9 verbose lifecycle with-typescript@1.0.0~build: CWD: C:\Projects\sdworx-corporate-nextjs\src
10 silly lifecycle with-typescript@1.0.0~build: Args: [ '/d /s /c', 'next build' ]
11 silly lifecycle with-typescript@1.0.0~build: Returned: code: 3221225477  signal: null
12 info lifecycle with-typescript@1.0.0~build: Failed to exec build script
13 verbose stack Error: with-typescript@1.0.0 build: `next build`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\tledoux\AppData\Roaming\nvm\v14.15.5\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\tledoux\AppData\Roaming\nvm\v14.15.5\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid with-typescript@1.0.0
15 verbose cwd C:\Projects\sdworx-corporate-nextjs\src
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.15.5
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 3221225477
22 error with-typescript@1.0.0 build: `next build`
22 error Exit status 3221225477
23 error Failed at the with-typescript@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]
```

**Comment by stpch** [comment]
Same for me after updating to `v10.2.0` using node `v14.15.5` on Windows 10.

**Comment by stpch** [comment]
Update: Upgrading to node `v14.16.1` (latest LTS) fixed the issue for me.

**Comment by maximegheraille** [comment]
as pointed out by @stpch, upgrading to v14.16.1 fixed the problem for him and also worked for me.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
