### ISSUE TITLE
turboMode and babelMultiThread experimentals can't be used at the same time

### ISSUE THREAD

**Issue by Aviortheking** [vercel/next.js#24767]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.15.4

### What browser are you using?

not related

### What operating system are you using?

Windows

### How are you deploying your application?

next build

### Describe the Bug

When I tried playing with the experimental I was not able to build my application when bother turboMode and babelMultiThread were enabled

I have a basic custom App (only changing the render method)

```
Error occurred prerendering page "/***". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: (0 , jsx_dev_runtime_.jsxDEV) is not a function
    at MyApp.render (D:\git\***\website\.next\server\pages\_app.js:1077:58)
    at d (D:\git\***\website\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:35:231)
    at bb (D:\git\***\website\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (D:\git\***\website\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (D:\git\***\website\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (D:\git\***\website\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (D:\git\**\website\node_modules\next\dist\next-server\server\render.js:54:854)
    at Function.getInitialProps (D:\git\***\website\.next\server\pages\_document.js:491:19)
    at loadGetInitialProps (D:\git\***\website\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at renderToHTML (D:\git\***\website\node_modules\next\dist\next-server\server\render.js:54:1145)
```

### Expected Behavior

next build should successfully build the application

### To Reproduce

- create a NextJS application that have static prerendered pages
- set both turboMode and babelMultiThread to true
- run `next build`
- see the error

**Comment by timneutkens** [comment]
This is correct, you shouldn't use `babelMultiThread` as it's an experiment.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
