### ISSUE TITLE
Error with Jest test running

### ISSUE THREAD

**Issue by tilvan** [vercel/next.js#24790]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Chrome

### What operating system are you using?

MacOS Catalina

### How are you deploying your application?

Other platform

### Describe the Bug

Hi everyone! I'm sorry if it duplicate.
Having errors when trying to run test with Jest.

```
Test suite failed to run
    /Users/ivantilikin/work/Evrone/eacademie_front/components/icons/favicons/favicon.ico:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){
    SyntaxError: Invalid or unexpected token
       8 | }
       9 |
    > 10 | import favicon from 'components/icons/favicons/favicon.ico';
         | ^
      11 | import appleTouchIcon from 'components/icons/favicons/apple-touch-icon.png';
      12 | import appleTouchIcon57 from 'components/icons/favicons/apple-touch-icon-57x57.png';
      13 | import appleTouchIcon72 from 'components/icons/favicons/apple-touch-icon-72x72.png';
      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (components/blocks/HtmlHead/HtmlHead.tsx:10:1)
```

### Expected Behavior

Expected to successful test running

### To Reproduce

`index.test.tsx`
```
import React from 'react';
import { render } from '../testUtils';
import HomePage from '../../components/pages/HomePage';
describe('HomePage', () => {
  it('matches snapshot', () => {
    const { asFragment } = render(<HomePage />, {});
    expect(asFragment()).toMatchSnapshot();
  });
});
```

`jest.config.js`
```
module.exports = {
  roots: ['<rootDir>'],
  setupFilesAfterEnv: ['./jest.setup.ts'],
  moduleFileExtensions: ['js', 'ts', 'tsx', 'json'],
  testPathIgnorePatterns: ['<rootDir>[/\\\\](node_modules|.next)[/\\\\]'],
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(ts|tsx)$'],
  transform: {
    '^.+\\.(ts|tsx)$': 'babel-jest',
  },
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
  moduleNameMapper: {
    '^public/(.*)$': '<rootDir>/public/$1',
    '^pages/(.*)$': '<rootDir>/pages/$1',
    '^components/(.*)$': '<rootDir>/components/$1',
    '^helpers/(.*)$': '<rootDir>/helpers/$1',
    '^parts/(.*)$': '<rootDir>/parts/$1',
    '^data/(.*)$': '<rootDir>/data/$1',
    '^styles/(.*)$': '<rootDir>/styles/$1',
    '^config/(.*)$': '<rootDir>/config/$1',
    '^utils/(.*)$': '<rootDir>/utils/$1',
    '^services/(.*)$': '<rootDir>/services/$1',
    '^hooks/(.*)$': '<rootDir>/hooks/$1',
    '^stores/(.*)$': '<rootDir>/stores/$1',
    '^modals/(.*)$': '<rootDir>/modals/$1',
    '^interfaces/(.*)$': '<rootDir>/interfaces/$1',
    '^vendors/(.*)$': '<rootDir>/vendors/$1',
    '^test/(.*)$': '<rootDir>/test/$1',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    '\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/test/__mocks__/fileMock.js',
  },
};
```

**Comment by ljosberinn** [comment]
sounds exclusively related to jest, not next, as the error is jest not understanding ESModules
