### ISSUE TITLE
TypeORM Module Not Found with Webpack 5 (as default in Next.js 10.2.0) + Serverless Target

### ISSUE THREAD

**Issue by jonioni** [vercel/next.js#24826]
### What version of Next.js are you using?

10.2.0 (with Webpack 5)

### What version of Node.js are you using?

15.10.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next build

### Describe the Bug

The Webpack 5 (as default by Next.js 10.2.0) doesn't work with packages using TypeORM (e.g. `next-auth`) under `serverless` deployment target. `next build` failed with error report on `Module not found: Error: Can't resolve 'xxx' in '<PROJECT>/node_modules/typeorm/platform'`.

```bash
...
info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'hdb-pool' in '<PROJECT>/node_modules/typeorm/platform'

> Build error occurred
Error: > Build failed because of webpack errors
    at <PROJECT>/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (<PROJECT>/node_modules/next/dist/telemetry/trace/trace.js:5:584)
```

The [How to use Webpack for the backend?](https://github.com/typeorm/typeorm/blob/master/docs/faq.md#how-to-use-webpack-for-the-backend) solution has been tried using `next.config.js` webpack config but the issue remains.

The `server` deployment target works fine.

### Expected Behavior

Next.js 10.2.0 + Webpack 5 + `serverless` target should build (`next build`) with TypeORM without error.

### To Reproduce

1. Checkout <https://github.com/nextauthjs/next-auth-example>
2. Update Next.js to `10.2.0` in `package.json`.
3. Add `next.config.js` with:
   ```js
   module.exports = {
     target: "serverless"
   };
   ```
4. `npm install` and `npm run build`.

Error:

```bash
info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'hdb-pool' in 'next-auth-example/node_modules/typeorm/platform'


> Build error occurred
Error: > Build failed because of webpack errors
    at next-auth-example/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (next-auth-example/node_modules/next/dist/telemetry/trace/trace.js:6:584)
npm ERR! code 1
npm ERR! path next-auth-example
npm ERR! command failed
npm ERR! command sh -c next build
```

**Comment by ocgames2021** [comment]
Got same issue when build NextJs + NextAuth application on Netlify :(

`7:46:01 AM: $ npm run build
7:46:01 AM: > public-website@0.5.15 build /opt/build/repo
7:46:01 AM: > next build
7:46:02 AM: info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
7:46:02 AM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
7:46:02 AM: info  - Checking validity of types...
7:46:02 AM: info  - Creating an optimized production build...
7:46:37 AM: Failed to compile.
7:46:37 AM: 
7:46:37 AM: ModuleNotFoundError: Module not found: Error: Can't resolve 'hdb-pool' in '/opt/build/repo/node_modules/typeorm/platform'
7:46:37 AM: > Build error occurred
7:46:37 AM: Error: > Build failed because of webpack errors
7:46:37 AM:     at /opt/build/repo/node_modules/next/dist/build/index.js:17:924
7:46:37 AM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
7:46:37 AM: npm ERR! code ELIFECYCLE
7:46:37 AM: npm ERR! errno 1
7:46:37 AM: npm ERR! public-website@0.5.15 build: `next build`
7:46:37 AM: npm ERR! Exit status 1
7:46:37 AM: npm ERR!
7:46:37 AM: npm ERR! Failed at the public-website@0.5.15 build script.
7:46:37 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
7:46:37 AM: npm ERR! A complete log of this run can be found in:
7:46:37 AM: npm ERR!     /opt/buildhome/.npm/_logs/2021-06-03T04_46_37_529Z-debug.log`

**Comment by balazsorban44** [comment]
This might help: https://github.com/nextauthjs/next-auth/discussions/1611#discussioncomment-795110

Don't think this needs to be reported in the Next.js repo though.

Maybe report it in next-auth, and include a complete reproduction of the issue.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
