### ISSUE TITLE
Vercel build failed because ModuleNotFoundError in node_modules package

### ISSUE THREAD

**Issue by danboyle8637** [vercel/next.js#24916]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.4.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I upload my code to my repo and Vercel kicks off a build but it always fails with this error: 

`Failed to compile.
--
16:11:43.678 | ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/vercel/path0/node_modules/styled-components/dist'
16:11:43.678 | > Build error occurred
16:11:43.679 | Error: > Build failed because of webpack errors
16:11:43.679 | at /vercel/path0/node_modules/next/dist/build/index.js:17:924
16:11:43.679 | at runMicrotasks (<anonymous>)
16:11:43.679 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
16:11:43.679 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)`

It's coming from node_modules and styled components. 

My project runs in development and I can successfully build the project locally. But I can't get by this error. 

Plus I'm confused because of the webpack errors.

I deleted my node_modules and reinstalled my packages but that is not working.

I also cleared my git cache because of a renamed directory in my project that was producing an error, but that seems to be fixed.

### Expected Behavior

For my project to build on the Vercel platform like it does locally. 

### To Reproduce

I don't know how to reproduce because there seems to be a code issue with a package and not my own code.

Every other issue I found that was similar was due to code written by the user... not a package. In my case this is pointing to styled components and the react-is package.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
