### ISSUE TITLE
[Example Bug] | MDB-React | Can't use create-next-app

### ISSUE THREAD

**Issue by John4266** [vercel/next.js#24925]
### What example does this report relate to?

with-mdbreact-app

### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

15.8.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying your application?

create-next-app

### Describe the Bug

Whenever i try to run the example of mdbreact using `npx create-next-app --example with-mdbreact with-mdbreact-app`,
i receive the following output:
```
Creating a new Next.js app in D:\Users\Win10\Desktop\Visual Studio\Visual Studio Code\Projects\Testings\test-nextjs\with-mdbreact-app.

Downloading files for example with-mdbreact. This might take a moment.

Installing packages. This might take a couple of minutes.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@"*" from mdbreact@5.0.2
npm ERR!   node_modules/mdbreact
npm ERR!     mdbreact@"^5.0.0" from the root project
npm ERR!   2 more (react-dom, next)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from @material-ui/core@3.9.3
npm ERR! node_modules/mdbreact/node_modules/@material-ui/core
npm ERR!   @material-ui/core@"3.9.3" from mdbreact@5.0.2
npm ERR!   node_modules/mdbreact
npm ERR!     mdbreact@"^5.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Win10\AppData\Local\npm-cache\_logs\2021-05-09T06_32_12_044Z-debug.log

Aborting installation.
  npm install --loglevel error has failed.
```

### Expected Behavior

It should just install the dependencies i guess with no errors.

### To Reproduce

Just run `npx create-next-app --example with-mdbreact with-mdbreact-app`

**Comment by insivika** [comment]
@John4266 did you figure this out?

**Comment by John4266** [comment]
> 
> 
> @John4266 did you figure this out?

I just tried again and ended up with different results.
Unfortunately, this is still not working properly.

```
$ npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /
wait  - compiling...
event - build page: /next/dist/pages/_error
event - compiled successfully
error - Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by ScottJr** [comment]
Same here

**Comment by John4266** [comment]
Just tried again, can confirm it still happens.

![](https://i.imgur.com/6GuWZOQ.png)

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\mdbreact\node_modules\react\cjs\react.development.js:1476:13)
    at Object.useState (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\mdbreact\node_modules\react\cjs\react.development.js:1507:20)
    at Ze (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\mdbreact\dist\mdbreact.js:1:110690)
    at renderWithHooks (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5732:15)
    at renderElement (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6087:14)
    at renderNode (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6270:12)
    at renderChildrenArray (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6222:7)
    at renderNodeDestructiveImpl (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6152:7)
    at renderNodeDestructive (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6087:14)
    at renderNode (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6270:12)
    at renderHostElement (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (file://C:\[REDACTED]\test-npx\with-mdbreact-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5963:5)
```

**Comment by bgub** [comment]
Re-testing on modern Next.js (v16 / Turbopack), this example is still broken, but I think it's for reasons external to Next.js.

There are multiple independent issues in mdbreact:
- `mdbreact/dist/css/mdb.css` ships with a UTF-8 BOM before `@import`, which causes Turbopack to fail CSS parsing (`Unexpected token AtKeyword("import")`).
- `mdbreact` bundles its own copy of React (node_modules/mdbreact/node_modules/react), leading to multiple React instances and the well-known “Invalid hook call” runtime error.

Both are upstream library problems. The with-mdbreact example relies on a dependency that is not compatible with modern React / Next.js tooling.

This does not appear to be a Next.js bug; the example likely needs to be updated or removed.
