### ISSUE TITLE
Cannot find module 'next-plugin-loader?middleware=on-init-server!' 

### ISSUE THREAD

**Issue by nishant-dani** [vercel/next.js#24970]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

10.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

AWS

### Describe the Bug

While trying to following the instructions to debug the nextjs app using --inspect and chrome://inspect the debugger breaks at this exception.

{
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/../node_modules/next/dist/build/webpack-config.js",
        "/../node_modules/next/dist/server/hot-reloader.js",
        "/../node_modules/next/dist/server/next-dev-server.js",
        "/../node_modules/next/dist/server/next.js",
        "/../node_modules/next/dist/server/lib/start-server.js",
        "/../node_modules/next/dist/cli/next-dev.js",
        "/../node_modules/next/dist/bin/next"
    ]
}

Cannot find module 'next-plugin-loader?middleware=on-init-server!'

Error: Cannot find module 'next-plugin-loader?middleware=on-init-server!'
Require stack:
- /yeticlient/node_modules/next/dist/build/webpack-config.js
- /yeticlient/node_modules/next/dist/server/hot-reloader.js
- /yeticlient/node_modules/next/dist/server/next-dev-server.js
- /yeticlient/node_modules/next/dist/server/next.js
- /yeticlient/node_modules/next/dist/server/lib/start-server.js
- /yeticlient/node_modules/next/dist/cli/next-dev.js
- /yeticlient/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.mod._resolveFilename (/yeticlient/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at /yeticlient/node_modules/next/dist/build/webpack-config.js:82:257
    at new Promise (<anonymous>)
    at /yeticlient/node_modules/next/dist/build/webpack-config.js:82:220
    at handleExternals (/yeticlient/node_modules/next/dist/build/webpack-config.js:51:23)
    at Array.webpackConfig.externals (/yeticlient/node_modules/next/dist/build/webpack-config.js:82:149)
    at webpackConfig.externals (/yeticlient/node_modules/next-plugin-antd-less/overrideWebpackConfig.js:267:24)
    at handleExternals (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57292:17)
    at next (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57280:9)
    at handleExternals (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57285:7)
    at /yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:57315:5
    at /yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:64070:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:43435:10), <anonymous>:4:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/yeticlient/node_modules/next/dist/compiled/webpack/bundle4.js:43372:20)

### Expected Behavior

Should be able to move ahead to debug and set breakpoints on the application code.

### To Reproduce

Start the application with npm run debug; 

In package.json, use this script:
    "debug": "NODE_OPTIONS='--inspect=0.0.0.0:9229' next dev",

Attach to the application with chrome://inspect

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
