### ISSUE TITLE
next build produces unhandled error "Error: write EPIPE" from worker sporadically

### ISSUE THREAD

**Issue by cdaringe** [vercel/next.js#25309]
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

14.16.1

### What browser are you using?

n/a

### What operating system are you using?

centos

### How are you deploying your application?

n/a

### Describe the Bug

`next build`, inconsistently and rarely, emits an unhandled exception from the worker with the following stack:

```
01:10:27 Error: write EPIPE
01:10:27     at ChildProcess.target._send (internal/child_process.js:832:20)
01:10:27     at ChildProcess.target.send (internal/child_process.js:703:19)
01:10:27     at ChildProcessWorker.initialize (/opt/app/node_modules/.pnpm/jest-worker@24.9.0/node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:11)
01:10:27     at new (/opt/app/node_modules/.pnpm/jest-worker@24.9.0/node_modules/jest-worker/build/workers/ChildProcessWorker.js:127:10)
01:10:27     at WorkerPool.createWorker (/opt/app/node_modules/.pnpm/jest-worker@24.9.0/node_modules/jest-worker/build/WorkerPool.js:44:12)
01:10:27     at new (/opt/app/node_modules/.pnpm/jest-worker@24.9.0/node_modules/jest-worker/build/base/BaseWorkerPool.js:82:27)
01:10:27     at new (/opt/app/node_modules/.pnpm/jest-worker@24.9.0/node_modules/jest-worker/build/WorkerPool.js:30:1)
01:10:27     at new (/opt/app/node_modules/.pnpm/jest-worker@24.9.0/node_modules/jest-worker/build/index.js:131:26)
01:10:27     at Object.build (/opt/app/node_modules/.pnpm/next@10.0.1_ecdac188bf3643049dbebc2b4993f561/node_modules/next/build/index.ts:501:30)
01:10:32  ERROR  Command failed with exit code 1.
```

The [call to initialize the worker is here](https://github.com/vercel/next.js/blob/3c3379412eeb0f877cef54bd6fe7afa9512c8ee5/packages/next/build/index.ts#L501). In master@latest, it more or less looks the same [here](https://github.com/vercel/next.js/blob/master/packages/next/build/index.ts#L668).

### Expected Behavior

- On worker failure, human friendly error messaging provided, or
- Design updated to assert healthy conditions before stream writing

### To Reproduce

That's the catch. We _rarely_ see this in the wild. Ad-hoc, I'd suggest maybe 1 in `<a couple of hundred>` builds. I would love to create a reproduction, but unfortunately I'm flying blind. It may be worth chatting first about the conditions which could lead to an `EPIPE`, and see what could be done to prevent the error, which may allow for some other problematic symptom to surface.

**Comment by JanKaifer** [comment]
Please verify that your issue can be recreated with `next@canary`.

### **Why was this issue marked with the `please verify canary` label?**

We noticed the provided reproduction was using an older version of Next.js, instead of `canary`.

The canary version of Next.js ships daily and includes all features and fixes that have not been released to the stable version yet. You can think of canary as a _public beta_. Some issues may already be fixed in the canary version, so please verify that your issue reproduces by running `npm install next@canary` and test it in your project, using your reproduction steps.

If the issue does not reproduce with the `canary` version, then it has already been fixed and this issue can be closed.

### **How can I quickly verify if my issue has been fixed in `canary`?**

The safest way is to install `next@canary` in your project and test it, but you can also search through [closed Next.js issues](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aclosed) for duplicates or check the [Next.js releases](https://github.com/vercel/next.js/releases).

### **My issue has been open for a long time, why do I need to verify `canary` now?**

Next.js does not backport bug fixes to older versions of Next.js. Instead, we are trying to introduce only a minimal amount of breaking changes between major releases.

### **What happens if I don't verify against the canary version of Next.js?**

An issue with the `please verify canary` that receives no meaningful activity (e.g. new comments that acknowledge verification against `canary`) will be automatically closed and locked after 30 days.

If your issue has not been resolved in that time and it has been closed/locked, please open a new issue, with the required reproduction, using `next@canary`.

### **I did not open this issue, but it is relevant to me, what can I do to help?**

Anyone experiencing the same issue is welcome to provide a minimal reproduction (following the above steps). Furthermore, you can upvote the issue (using the :+1: reaction on the topmost comment, instead of commenting "I have the same issue" etc.). Then, we can sort issues by engagement to prioritize.

### **I think my reproduction is good enough, why aren't you looking into it quicker?**

We look into every Next.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### **Useful Resources**

- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)
- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a Next.js bug](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml)
- [Next.js Triaging issues](https://github.com/vercel/next.js/blob/canary/contributing/repository/triaging.md)

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
