### ISSUE TITLE
Custom Server bug

### ISSUE THREAD

**Issue by gokulmhegde** [vercel/next.js#25579]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

Custom server caching mentioned in this example

**https://github.com/vercel/next.js/tree/canary/examples/ssr-caching**

wont work any more 

if we use **getServerSideProps** in the **js** file under **Pages**

**Getting this error**

(node:20872) UnhandledPromiseRejectionWarning: TypeError: argument entity is required
at etag (C:\xampp\htdocs\next-app\node_modules\etag\index.js:72:11)
at C:\xampp\htdocs\next-app\node_modules\cacheable-response\index.js:93:32
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:20872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected Behavior

It should render page as expected without any error

### To Reproduce

Use this link

https://github.com/vercel/next.js/tree/canary/examples/ssr-caching

create **getServerSideProps** in **js** file under **pages**

**console log query params**

and do **npm run dev**

you should see the above error in console at server side which i mentioned in the issue

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
