### ISSUE TITLE
TypeError: Cannot read property 'identifier' of undefined [Build issue]

### ISSUE THREAD

**Issue by AhmedBHameed** [vercel/next.js#25585]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

v12.16.3

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

next start

### Describe the Bug

I was using next v9 and return back to the project again so I just updated my package dependencies using another plugin `ncu -u`.

The project is running fine in development environment but while building, I'm getting this error

```bash
> Build error occurred
TypeError: Cannot read property 'identifier' of undefined
    at Compilation.addModule (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:72393:29)
    at /home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:72857:35
    at /home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:85658:25
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:64:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
    at NormalModuleFactory.create (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:85646:28)
    at /home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:72835:18
    at Semaphore.acquire (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:111074:4)
    at Compilation._addModuleChain (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:72834:18)
    at Compilation.addEntry (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:72936:8)
    at /home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:90690:17
    at AsyncParallelHook.eval [as callAsync] (eval at create (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:11:1)
    at AsyncParallelHook.lazyCompileHook (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
    at /home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:74776:20
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:128919:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ahmed/Desktop/WWW/next_ahmedhameed/node_modules/next/dist/compiled/webpack/bundle4.js:128856:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I would love to see some suggestions of where to look to track down this issue.

### Expected Behavior

I would expect to see kind of error source or at least a tail to track down the issue but with this information above, I'm not sure from where to start and where to look? I even don't know what that error is.

### To Reproduce

The project repo is [this](https://github.com/AhmedBHameed/next_ahmedhameed)

Running `yarn build` whill trigger the issue.

**Comment by AhmedBHameed** [comment]
I guess I found a solution.

I moved `setupTest.ts` into folder `test`.
Then i ignored this file completely via webpack config as follow.

```js
module.exports = {
  publicRuntimeConfig: {
    mapboxApiAccessToken:
      'pk.eyJ1IjoiYWhtZWRiaGFtZWVkIiwiYSI6ImNrNmNpd3M3ZzExZXMza21neGoxNHJoeDcifQ.07EbC691qPVJ86uLhJyfWA',
    domain: `${
      process.env.NODE_ENV === 'production'
        ? 'https://www.ahmedhameed.dev'
        : 'http://localhost:5000'
    }`,
    graphqlApi: '/nodeys/v1/graphql',
    uploadApi: '/nodeys/api/upload',
    localeSubpaths:
      typeof process.env.LOCALE_SUBPATHS === 'string'
        ? process.env.LOCALE_SUBPATHS
        : 'none',
  },
  i18n: {
    locales: ['en', 'ar'],
    defaultLocale: 'en',
    localeDetection: false,
  },
  images: {
    domains: ['assets.vercel.com'],
  },
  webpackDevMiddleware: (config) => {
    config.watchOptions = {
      poll: 1000,
      aggregateTimeout: 300,
    };

    return config;
  },
  webpack: (config, {webpack}) => {
    config.plugins.push(new webpack.IgnorePlugin(/\/__tests__\//));
    config.plugins.push(new webpack.IgnorePlugin(/\/test\//));   // <<<<<<<<<==== This line solved the issue

    config.node = {
      fs: 'empty',
    };
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });

    return config;
  },
};

```

Closing my own issue.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
