### ISSUE TITLE
Invalid pageProps passed to <App> (_app.js) component (Right side of assignment cannot be destructured)

### ISSUE THREAD

**Issue by feross** [vercel/next.js#25766]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

16.2.0

### What browser are you using?

Safari 14.1

### What operating system are you using?

iPhone/macOS

### How are you deploying your application?

next build && next start

### Describe the Bug

We're seeing an invalid pageProps value passed to our `<App>` component in `_app.js`. The error message is `Right side of assignment cannot be destructured`. This happens in production on various versions of Safari 14 and 14.1 on iOS and macOS.

Here's a code snippet:

```js
export default function MyApp ({ Component, pageProps, err }) {
  let {
    title,
    description = siteDescription,
    socialImage = siteSocialImage,
    initialContext,
    initialLanguage,
    preloadedI18nResources,
    ...props
  } = pageProps  // THROWS ON THIS LINE

  // ... rest of class
}
```

The exact exception is:

```
TypeError: Right side of assignment cannot be destructured
  at MyApp(./pages/_app.js:45:19)
  at Ch(./node_modules/react-dom/cjs/react-dom.production.min.js:157:137)
  at li(./node_modules/react-dom/cjs/react-dom.production.min.js:180:154)
  at bk(./node_modules/react-dom/cjs/react-dom.production.min.js:250:347)
  at ak(./node_modules/react-dom/cjs/react-dom.production.min.js:250:278)
  at Tj(./node_modules/react-dom/cjs/react-dom.production.min.js:250:138)
  at Lj(./node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
  at vi([native code])
  at b(./node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
  at gg(./node_modules/scheduler/cjs/scheduler.production.min.js:18:343)
  at jg(./node_modules/react-dom/cjs/react-dom.production.min.js:123:61)
  at ig(./node_modules/react-dom/cjs/react-dom.production.min.js:122:428)
  at Jg(./node_modules/react-dom/cjs/react-dom.production.min.js:237:203)
  at lk(./node_modules/react-dom/cjs/react-dom.production.min.js:285:27)
  at tk(./node_modules/react-dom/cjs/react-dom.production.min.js:289:150)
  at renderReactElement(../client/index.tsx:527:7)
  at doRender(../client/index.tsx:793:3)
  at ? (../client/index.tsx:425:11)
  at asyncFunctionResume([native code])
  at ? (../next-server/lib/router/router.ts:930:7)
  at asyncFunctionResume([native code])
  at apply(../next-server/lib/router/router.ts:727:5)
  at r(./node_modules/@sentry/browser/esm/helpers.js:72:23)
```

Other pertinent details of our app:

- We use `_error.js` but do not use a custom `404.js` or `500.js` page.
	- When we add `404.js` and `500.js` pages, the error stops happening.
- We notice that Next.js seems to do 3 client-side navigations before throwing this exception.
- The `_error.js` page is being asked to render a 404 page (`statusCode` is 404`) when the exception happens.

### Expected Behavior

`pageProps` should never be `undefined`, `null`, or whatever the value is that cannot be restructured here.

### To Reproduce

We don't have a reproduction handy at the moment. Help is welcome from others facing this issue.

**Comment by pooooriya** [comment]
hi , if you want to change name during using destructuring In Javascript You Have To Use This Format 
`
  let {
    title,
    description :  siteDescription,
    socialImage : siteSocialImage,
    initialContext,
    initialLanguage,
    preloadedI18nResources,
    ...props
  } = pageProps  
`

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
