### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by SimonSiefke** [vercel/next.js#26061]
### What version of Next.js are you using?

10.2.4-canary.15

### What version of Node.js are you using?

16.3.0

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu 21.04

### How are you deploying your application?

next export

### Describe the Bug

I'm trying to upgrade a project from webpack 4 to webpack 5. With webpack 4, everything works fine, but with webpack 5 there is a build error:

```sh

> my-app@0.1.0 build
> next build

info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build ./home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:118429
                                fn: str => str.startsWith(condition)
                                               ^

TypeError: Cannot read property 'startsWith' of null
    at Object.fn (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:118429:20)
    at execRule (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:118301:22)
    at execRule (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:118326:10)
    at execRule (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:118321:6)
    at Object.exec (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:118340:6)
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:66672:34
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:66348:11
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:66885:8
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:67035:5
    at finishResolved (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:22422:11)
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:22486:25
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:22553:24
    at eval (eval at create (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:27:1)
    at done (/home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:78183:12)
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:78130:28
    at /home/simon/Documents/nextjs-bug/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:58396:3
```

After lots of debugging I think it has to do with the usage of raw loader:

```sh
const styles = require(`!!raw-loader!../styles/${name}`).default;
```

However I found the error message very confusing, I was thinking that the error message in nextjs can be improved to make upgrading to webpack 5 easier.

### Expected Behavior

No error

### To Reproduce

Github repo: https://github.com/SimonSiefke/nextjs-cannot-read-property-startsWith-of-null

![error](https://user-images.githubusercontent.com/23744935/121870065-f5a82c00-cd02-11eb-9e75-90184cc89462.png)

**Comment by imdavidmin** [comment]
Having same error, as long as I add `require("google-closure-library");` into the `index.js` of the learner-starter template

**Comment by brancooo1** [comment]
Having same error when using `await import("./file.tsx")` in `getStaticProps()` when doing [dynamic routes](https://nextjs.org/learn/basics/dynamic-routes) example

```
fn: str => str.startsWith(condition)
TypeError: Cannot read property 'startsWith' of null
```
