### ISSUE TITLE
Extracting CSS to a single file causes the build to fail

### ISSUE THREAD

**Issue by swashcap** [vercel/next.js#26100]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

16.3.0

### What browser are you using?

n/a

### What operating system are you using?

macOS 11.5 Beta

### How are you deploying your application?

next start

### Describe the Bug

👋 Hello! I'm experimenting with some Next.js build optimizations, and I wanted to try mini-css-extract-plugin's
[instructions for "Extracting all CSS in a single file"](https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file). After adding these to `next.config.js` I'm finding that `next build` fails with this error:

```shell
Error: Cannot find module for page: /_app
    at pageNotFoundError (/Users/dudeman/next-css-modules-single-file/node_modules/next/dist/next-server/server/require.js:1:454)
    at getPagePath (/Users/dudeman/next-css-modules-single-file/node_modules/next/dist/next-server/server/require.js:1:1263)
    at requirePage (/Users/dudeman/next-css-modules-single-file/node_modules/next/dist/next-server/server/require.js:1:1397)
    at loadComponents (/Users/dudeman/next-css-modules-single-file/node_modules/next/dist/next-server/server/load-components.js:1:1365)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.hasCustomGetInitialProps (/Users/dudeman/next-css-modules-single-file/node_modules/next/dist/build/utils.js:26:1276) {
  type: 'Error',
  code: 'ENOENT'
}
```

### Expected Behavior

I would expect `next build` to build the app.

**Note:** Enabling `webpack5: true` or updating to `next@10.2.4-canary.15` appears to address this bug: issue only appears to happen with versions <= `next@10.2.3`. I'm currently working on a large production app where these changes/updates aren't possible at the moment, so I'm wondering is something can be done when Next.js uses `webpack@^4`.

### To Reproduce

I've created an example project to reproduce this bug: https://github.com/swashcap/next-css-modules-single-file

1. Clone repository
2. `nvm use && npm i`
3. `npm run build`
4. Observe the error: `Error: Cannot find module for page: /_app`

**Comment by timneutkens** [comment]
It's recommended to not customize the webpack configuration for cases like these. The default configuration is correctly optimized for Next.js and already extracts CSS.

**Comment by swashcap** [comment]
@timneutkens Thanks for the comment. Makes sense.

> The default configuration is correctly optimized for Next.js and already extracts CSS.

Do you have documentation on this design? Why does Next.js extract CSS—especially CSS Modules—in its current manner?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
