### ISSUE TITLE
Module not found: Error: Can't resolve 'next/experimental-script'

### ISSUE THREAD

**Issue by JoseGarciaM** [vercel/next.js#26148]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Safari, Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

`Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules

> [PWA] Compile server
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /*/node_modules/next-pwa/register.js
> [PWA] Service worker: /*/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'next/experimental-script' in '/*/pages'

> Build error occurred
Error: > Build failed because of webpack errors
    at /*/node_modules/next/dist/build/index.js:15:924
    at async Span.traceAsyncFn (/*/node_modules/next/dist/telemetry/trace/trace.js:6:584)`

### Expected Behavior

Let use Script

### To Reproduce

-

**Comment by JoseGarciaM** [comment]
Added `import Script from 'next/script'`

https://nextjs.org/docs/basic-features/script

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
