### ISSUE TITLE
next build fails while linting code

### ISSUE THREAD

**Issue by roberta-racco** [vercel/next.js#26272]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

running `next build` error below occurs:
```
(node:75087) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Node'
    |     property 'object' -> object with constructor 'Node'
    --- property 'parent' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (internal/child_process/serialization.js:117:20)
    at process.target._send (internal/child_process.js:805:17)
    at process.target.send (internal/child_process.js:703:19)
    at reportError (/<my_project_path>/node_modules/jest-worker/build/workers/processChild.js:87:11)
    at reportClientError (/<my_project_path>/node_modules/jest-worker/build/workers/processChild.js:71:10)
```
I figured out its about the check of eslint because adding `eslint.ignoreDuringBuilds: true` to next.config.js desn't emit the error.

### Expected Behavior

i expect build lints my code and fails if has some errors

### To Reproduce

my .eslintrc is:
```
{
  "root": true,
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "airbnb/hooks"
  ],
  "rules": {
    "import/prefer-default-export": 0,
    "react/jsx-one-expression-per-line": 0,
    "react/jsx-props-no-spreading": 0,
    "object-curly-newline": ["error", {
      "ObjectExpression": {
        "multiline": true,
        "consistent": true
      },
      "ObjectPattern": {
        "multiline": true,
        "consistent": true
      }
    }]
  },
  "settings": {
    "import/resolver": {
      "alias": {
        "map": [
          ["components", "./src/components"],
          ["containers", "./src/containers"],
          ["pages", "./src/pages"],
          ["utils", "./src/utils"],
          ["i18n", "./i18n"]
        ],
        "extensions": [".js", ".jsx", ".json"]
      }
    }
  }
}
```
```
"babel-eslint": "^10.1.0",
"eslint": "^7.28.0",
"eslint-config-airbnb": "^18.2.1",
"eslint-config-next": "^11.0.0",
"eslint-import-resolver-alias": "^1.1.2",
"eslint-plugin-import": "^2.23.4",
"eslint-plugin-jsx-a11y": "^6.4.1",
"eslint-plugin-react": "^7.24.0",
"eslint-plugin-react-hooks": "^4.2.0"
```

**Comment by glenarama** [comment]
Seeing same...

**Comment by housseindjirdeh** [comment]
@roberta-racco @glenarama  Are you seeing any errors running `next lint`, or only with `next build`? Could you also share the repo if it's public, because I just tried using your same eslint configuration and I can't reproduce the issue you're seeing 🤔 

![Screen Shot 2021-06-17 at 3 39 11 PM](https://user-images.githubusercontent.com/12476932/122462103-2ba71380-cf82-11eb-9096-5c00346f515d.png)

**Comment by glenarama** [comment]
Well - this seems to have cleared itself up for me without a single change :-/ 

I'd note that this also caused Vercel build to hang (Not fail) I had to cancel the deployment after 15 minutes.

Here's my error in case you want to look any further
<img width="721" alt="image" src="https://user-images.githubusercontent.com/511285/122463322-64101700-cfad-11eb-8585-8ea80e34a788.png">

**Comment by housseindjirdeh** [comment]
> Well - this seems to have cleared itself up for me without a single change :-/

Haha are you not seeing the error anymore? That's great to hear :)

Thanks for sharing a screenshot of the error, if I get the chance to reproduce it will keep you posted.

**Comment by glenarama** [comment]
> Haha are you not seeing the error anymore? That's great to hear :)

Thats right - it went as quick as it came - Local AND Vercel build working fine for me now.....

**Comment by roberta-racco** [comment]
Thank you guys for the quick response. I tried running next lint and the linter returned this error
```
Cannot read property 'value' of null
Occurred while linting /<my_project_path>/src/pages/api/proxy.js:9
```
validating that line of code
```
Authorization: `Bearer ${JWT_TOKEN}`,
```
with a quick search i found that issues https://github.com/eslint/eslint/issues/13394 and https://github.com/babel/babel/issues/10904.
Following the solutions reported i replaced `babel-eslint` with `@babel/eslint-parser`.
Now `next lint` and `next build` works without any errors.

Thanks!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
