### ISSUE TITLE
Fatal error when using css files and require.context 

### ISSUE THREAD

**Issue by pomber** [vercel/next.js#26404]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.15.3

### What operating system are you using?

Linux

### Describe the Bug

Using 

```js
const ctx = require.context("./raw");
```

where `raw` is a folder that contains a CSS file, throws this error:

```error
wait  - compiling...
next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:118508
				fn: str => str.startsWith(condition)
				               ^

TypeError: Cannot read property 'startsWith' of null
    at Object.fn (next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:118508:20)
    at execRule (next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:118380:22)
    at execRule (next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:118405:10)
    at execRule (next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:118400:6)
    at Object.exec (next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:118419:6)
    at next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:66675:34
    at next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:66350:11
    at next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:66889:8
    at next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:67039:5
    at finishResolved (next-require-context-issue/node_modules/next/dist/compiled/webpack/bundle5.js:22422:11)
error Command failed with exit code 1.
```

It only happens with CSS files.

### Expected Behavior

CSS files should work as other files.

### To Reproduce

Minimal repro: https://github.com/pomber/next-require-context-issue

### Use Case

I use `require.context()` to import raw files as [source assets](https://webpack.js.org/guides/asset-modules/#source-assets), basically importing each file in the folder as a string.

### Related

It May be related to #25077

**Comment by LXSMNSYC** [comment]
I think one of the reasons of this is because of how a dynamic import with a dynamic string and require.context loading an arbitrary number of files makes it impossible for static analysis to be performed during runtime.

![image](https://user-images.githubusercontent.com/4783372/122790319-c8531380-d2ea-11eb-9e98-0065ab9acfe9.png)

I'm not sure, however, if this behavior was supported before.

**Comment by pomber** [comment]
Not sure if it's supposed to be supported, but it works fine with files that don't end with `.css`. I think it may be related to something specific to how nextjs imports css files.

**Comment by JanKaifer** [comment]
Please verify that your issue can be recreated with `next@canary`.

### **Why was this issue marked with the `please verify canary` label?**

We noticed the provided reproduction was using an older version of Next.js, instead of `canary`.

The canary version of Next.js ships daily and includes all features and fixes that have not been released to the stable version yet. You can think of canary as a _public beta_. Some issues may already be fixed in the canary version, so please verify that your issue reproduces by running `npm install next@canary` and test it in your project, using your reproduction steps.

If the issue does not reproduce with the `canary` version, then it has already been fixed and this issue can be closed.

### **How can I quickly verify if my issue has been fixed in `canary`?**

The safest way is to install `next@canary` in your project and test it, but you can also search through [closed Next.js issues](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aclosed) for duplicates or check the [Next.js releases](https://github.com/vercel/next.js/releases).

### **My issue has been open for a long time, why do I need to verify `canary` now?**

Next.js does not backport bug fixes to older versions of Next.js. Instead, we are trying to introduce only a minimal amount of breaking changes between major releases.

### **What happens if I don't verify against the canary version of Next.js?**

An issue with the `please verify canary` that receives no meaningful activity (e.g. new comments that acknowledge verification against `canary`) will be automatically closed and locked after 30 days.

If your issue has not been resolved in that time and it has been closed/locked, please open a new issue, with the required reproduction, using `next@canary`.

### **I did not open this issue, but it is relevant to me, what can I do to help?**

Anyone experiencing the same issue is welcome to provide a minimal reproduction (following the above steps). Furthermore, you can upvote the issue (using the :+1: reaction on the topmost comment, instead of commenting "I have the same issue" etc.). Then, we can sort issues by engagement to prioritize.

### **I think my reproduction is good enough, why aren't you looking into it quicker?**

We look into every Next.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### **Useful Resources**

- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)
- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a Next.js bug](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml)
- [Next.js Triaging issues](https://github.com/vercel/next.js/blob/canary/contributing/repository/triaging.md)

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
