### ISSUE TITLE
Next.js 11 and `create-next-app` broken on Termux

### ISSUE THREAD

**Issue by thunder-coding** [vercel/next.js#26484]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Not applicable

### What operating system are you using?

Android [Termux](https://termux.org/)

### How are you deploying your application?

next dev

### Describe the Bug

`create-next-app` and `next dev` return runtime JS errors instead of working fine.

### Expected Behavior

Everything should work fine

### To Reproduce

Run `yarn create next-app`
Output: 
```
$ yarn create next-app
yarn create v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-next-app@11.0.0" with binaries:
      - create-next-app
✔ What is your project named? … my-app
The directory my-app contains files that could conflict:

  package.json

Either try using a new directory name, or remove the files listed above.

error Command failed.
Exit code: 1
Command: /data/data/com.termux/files/usr/bin/create-next-app
Arguments:
Directory: /data/data/com.termux/files/home
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

Also running `npx next dev` on existing Next.js project:
```
$ yarn dev
yarn run v1.22.10
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - automatically enabled Fast Refresh for 1 custom loader
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at PrebuildWebpackPlugin.getChangedFile (/data/data/com.termux/files/home/CodingThunder/node_modules/prebuild-webpack-plugin/index.js:60:32)
    at /data/data/com.termux/files/home/CodingThunder/node_modules/prebuild-webpack-plugin/index.js:115:32
    at Hook.eval [as callAsync] (eval at create (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:31736:14)
    at run (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72937:33)             at /data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72932:6
    at Compiler.readRecords (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:46175:11)
    at run (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72928:26)
    at Watching._go (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72987:3)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at PrebuildWebpackPlugin.getChangedFile (/data/data/com.termux/files/home/CodingThunder/node_modules/prebuild-webpack-plugin/index.js:60:32)
    at /data/data/com.termux/files/home/CodingThunder/node_modules/prebuild-webpack-plugin/index.js:115:32
    at Hook.eval [as callAsync] (eval at create (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:31934:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:31736:14)
    at run (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72937:33)
    at /data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72932:6
    at Compiler.readRecords (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:46175:11)
    at run (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72928:26)
    at Watching._go (/data/data/com.termux/files/home/CodingThunder/node_modules/next/dist/compiled/webpack/bundle5.js:72987:3)
```

**Comment by timneutkens** [comment]
The message already includes why `create-next-app` bailed out in the directory you're running it on:

```
The directory my-app contains files that could conflict:

  package.json

Either try using a new directory name, or remove the files listed above.
```

The other issue is not related to Next.js, you've likely customized the webpack configuration as `prebuild-webpack-plugin` is not part of Next.js.
