### ISSUE TITLE
Spread Operators do not work in _document.js when applied to JSX

### ISSUE THREAD

**Issue by ScriptedAlchemy** [vercel/next.js#26547]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.18.1

### What browser are you using?

N/A

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

If i use spread operators to pass props into something in _document, like a `<link` component, the build fails. 

I was able to replicate this on stackblitz as well as in my own applications. 

```js
import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    const things = { className: 'test' };
    return (
      <Html>
        <Head />
        <link {...things} />
        <body>
        <Main />
        <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

Get the following error

```
Failed to compile.

./pages/_document.js
Module parse failed: Cannot read property 'forEach' of undefined
File was processed with these loaders:
 * ./node_modules/next/dist/build/babel/loader/index.js
You may need an additional loader to handle the result of these loaders.
TypeError: Cannot read property 'forEach' of undefined


> Build error occurred
Error: > Build failed because of webpack errors
    at eval (/home/projects/nextjs-hn64hn/node_modules/next/dist/build/index.js:15:924)
    at async Span.traceAsyncFn (/home/projects/nextjs-hn64hn/node_modules/next/dist/telemetry/trace/trace.js:6:584)
```

### Expected Behavior

The build should pass

### To Reproduce

Use a spread operator on a html element in _document

**Comment by leerob** [comment]
I just took your code snippet and pasted into StackBlitz and I am unable to reproduce: https://stackblitz.com/edit/vercel-next-js-3fttnx?devtoolsheight=33&file=pages/_document.js

Could you share a repro?

**Comment by bmathews** [comment]
@leerob The error only occurs when running `yarn build` .  Here's an example from that stackblitz link:

![image](https://user-images.githubusercontent.com/848347/123200831-58699800-d466-11eb-8ffe-9c812ade898b.png)

**Comment by awareness481** [comment]
FWIW, spreading props to body works

```jsx
import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    const things = { className: 'test' };
    return (
      <Html>
        <Head />
        <body {...things}>
        <Main  />
        <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

But trying the same with `link` element (as in the example from @ScriptedAlchemy ) breaks the build

**Comment by ScriptedAlchemy** [comment]
> I just took your code snippet and pasted into StackBlitz and I am unable to reproduce: [stackblitz.com/edit/vercel-next-js-3fttnx?devtoolsheight=33&file=pages/_document.js](https://stackblitz.com/edit/vercel-next-js-3fttnx?devtoolsheight=33&file=pages/_document.js)
> 
> Could you share a repro?

yeah run yarn build on that stackblitz link and it'll crash

**Comment by timneutkens** [comment]
Full error is this:
```
"Module parse failed: Cannot read property 'forEach' of undefined\n" +
      'File was processed with these loaders:\n' +
      ' * ./node_modules/next/dist/build/babel/loader/index.js\n' +
      'You may need an additional loader to handle the result of these loaders.\n' +
      "TypeError: Cannot read property 'forEach' of undefined\n" +
      '    at jsxNodeHandler (/Users/timneutkens/projects/my-app/node_modules/next/dist/build/webpack/plugins/font-stylesheet-gathering-plugin.js:15:71)\n' +
      '    at Hook.eval [as call] (eval at create (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:31920:10), <anonymous>:7:16)\n' +
      '    at JavascriptParser.callHooksForInfoWithFallback (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104896:24)\n' +
      '    at JavascriptParser.callHooksForInfo (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104845:15)\n' +
      '    at JavascriptParser.walkCallExpression (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104646:26)\n' +
      '    at JavascriptParser.walkExpression (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104163:10)\n' +
      '    at JavascriptParser.walkExpressions (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104140:10)\n' +
      '    at JavascriptParser.walkArrayExpression (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104233:9)\n' +
      '    at JavascriptParser.walkExpression (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104148:10)\n' +
      '    at JavascriptParser.walkProperty (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104267:9)\n' +
      '    at JavascriptParser.walkObjectExpression (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104250:9)\n' +
      '    at JavascriptParser.walkExpression (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104196:10)\n' +
      '    at JavascriptParser.walkExpressions (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104140:10)\n' +
      '    at /Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:91185:22\n' +
      '    at Hook.eval [as call] (eval at create (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:31920:10), <anonymous>:7:16)\n' +
      '    at JavascriptParser.callHooksForInfoWithFallback (/Users/timneutkens/projects/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:104880:26)'
```

I've already identified a fix and will open a PR, just finishing up the tests for it.

**Comment by timneutkens** [comment]
Fixed the issue in #26608, it's related to how font optimization traverses `<link>` tags.

**Comment by ScriptedAlchemy** [comment]
Thanks Tim!

**Comment by ScriptedAlchemy** [comment]
@timneutkens can this be retroactively applied to next 10.2.4/4

the bug exists there as well I believe

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
