### ISSUE TITLE
Using strategy="beforeInteractive" with the new next/script Script component triggers: Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by xenostar** [vercel/next.js#26618]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.18.2

### What browser are you using?

Firefox

### What operating system are you using?

MacOS Big Sur 11.04

### How are you deploying your application?

npm run dev

### Describe the Bug

When using the new `next/script` `<Script />` component to load scripts, it will trigger the following warning in the dev server console when loading the page in the browser for the first time:

```bash
➜ npm run dev

> learn-starter@0.1.0 dev /Users/xenostar/Git/nextjs-blog
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (webpack-internal:///./node_modules/next/dist/pages/_document.js:252:5)
    at html
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:241:29)
    at Document (webpack-internal:///./node_modules/next/dist/pages/_document.js:198:1)
```

It _seems_ that `strategy="beforeInteractive"` may be the culprit, as removing that will remove the warning. This warning will be triggered even if there is only one script called using `strategy="beforeInteractive"`.

### Expected Behavior

There should be no warning when using `strategy="beforeInteractive"` with a `<Script />` component.

### To Reproduce

Using the finished [nextjs-blog demo](https://nextjs.org/learn/basics/create-nextjs-app/setup) from the official docs will allow you to reproduce the behavior.

To reproduce, modify the finished demo `_app.js` file like so by adding new `<Script />` tags:

```jsx
import Script from "next/script";
import "../styles/global.css";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Script src="https://js.stripe.com/v3/" strategy="beforeInteractive" />
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.1/underscore-min.js" />
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" />
      <Component {...pageProps} />
    </>
  );
}
```

I've used CDN scripts so anyone can reproduce.

Using the new `next/script` `<Script />` components to load scripts with `strategy="beforeInteractive"` with at least one of the scripts will trigger the following Warning in the dev server console when loading the page in the browser for the first time:

```bash
➜ npm run dev

> learn-starter@0.1.0 dev /Users/xenostar/Git/nextjs-blog
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (webpack-internal:///./node_modules/next/dist/pages/_document.js:252:5)
    at html
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:241:29)
    at Document (webpack-internal:///./node_modules/next/dist/pages/_document.js:198:1)
```

Removing the `strategy="beforeInteractive"` will get rid of the warning when the page renders.

This warning is also observable when building the app, as there is a warning for each page:

```bash
➜ npm run build

> learn-starter@0.1.0 build /Users/xenostar/Git/nextjs-blog
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[ ===] info  - Generating static pages (0/6)Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:549:5)
    at html
    at Html (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:538:29)
    at Document (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:495:1)
[  ==] info  - Generating static pages (1/6)Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:549:5)
    at html
    at Html (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:538:29)
    at Document (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:495:1)
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:549:5)
    at html
    at Html (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:538:29)
    at Document (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:495:1)
[  ==] info  - Generating static pages (2/6)Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:549:5)
    at html
    at Html (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:538:29)
    at Document (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:495:1)
postData {
  id: 'pre-rendering',
  contentHtml: '<p>Next.js has two forms of pre-rendering: <strong>Static Generation</strong> and <strong>Server-side Rendering</strong>. The difference is in <strong>when</strong> it generates the HTML for a page.</p>\n' +
    '<ul>\n' +
    '<li><strong>Static Generation</strong> is the pre-rendering method that generates the HTML at <strong>build time</strong>. The pre-rendered HTML is then <em>reused</em> on each request.</li>\n' +
    '<li><strong>Server-side Rendering</strong> is the pre-rendering method that generates the HTML on <strong>each request</strong>.</li>\n' +
    '</ul>\n' +
    '<p>Importantly, Next.js lets you <strong>choose</strong> which pre-rendering form to use for each page. You can create a "hybrid" Next.js app by using Static Generation for most pages and using Server-side Rendering for others.</p>\n',
  title: 'Two Forms of Pre-rendering',
  date: '2020-01-01'
}
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:549:5)
    at html
    at Html (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:538:29)
    at Document (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:495:1)
postData {
  id: 'ssg-ssr',
  contentHtml: '<p>We recommend using <strong>Static Generation</strong> (with and without data) whenever possible because your page can be built once and served by CDN, which makes it much faster than having a server render the page on every request.</p>\n' +
    '<p>You can use Static Generation for many types of pages, including:</p>\n' +
    '<ul>\n' +
    '<li>Marketing pages</li>\n' +
    '<li>Blog posts</li>\n' +
    '<li>E-commerce product listings</li>\n' +
    '<li>Help and documentation</li>\n' +
    '</ul>\n' +
    `<p>You should ask yourself: "Can I pre-render this page <strong>ahead</strong> of a user's request?" If the answer is yes, then you should choose Static Generation.</p>\n` +
    "<p>On the other hand, Static Generation is <strong>not</strong> a good idea if you cannot pre-render a page ahead of a user's request. Maybe your page shows frequently updated data, and the page content changes on every request.</p>\n" +
    '<p>In that case, you can use <strong>Server-Side Rendering</strong>. It will be slower, but the pre-rendered page will always be up-to-date. Or you can skip pre-rendering and use client-side JavaScript to populate data.</p>\n',
  title: 'When to Use Static Generation v.s. Server-side Rendering',
  date: '2020-01-02'
}
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at script
    at Head (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:549:5)
    at html
    at Html (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:538:29)
    at Document (/Users/xenostar/Git/nextjs-blog/.next/server/pages/_document.js:495:1)
info  - Generating static pages (6/6)
info  - Finalizing page optimization

Page                              Size     First Load JS
┌ ● /                             1.5 kB         78.1 kB
├   /_app                         0 B            63.7 kB
├ ○ /404                          278 B            64 kB
├ λ /api/hello                    0 B            63.7 kB
├ ● /posts/[id]                   1.34 kB        77.9 kB
├   ├ /posts/pre-rendering
├   └ /posts/ssg-ssr
└ ○ /posts/first-post             1.16 kB        70.8 kB
+ First Load JS shared by all     63.7 kB
  ├ chunks/framework.c5113a.js    42 kB
  ├ chunks/main.a3a79a.js         20.2 kB
  ├ chunks/pages/_app.6bb013.js   721 B
  ├ chunks/webpack.61095c.js      810 B
  └ css/cc846a79cae462a6667f.css  267 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
```

**Things I've Tried / Notes**
- Adding a `key` or `data-key` prop to each `<Script />` component doesn't seem to resolve the warning.
- Removing `strategy="beforeInteractive"` from a `<Script />` seems to be the culprit of the warning.
- The warning appears even if there is a single `<Script />` with `strategy="beforeInteractive"`

**Comment by LetItRock** [comment]
@xenostar the `key` property is not passed with the `props` to the `Script` component. Underneath when looping over `scripts` with the `beforeInteractive` strategy the Next passed all the rest props to the `script`, but it doesn't set the `key` prop. 

Hint: `getPreNextScripts` function in the `packages/next/pages/_document.tsx`

**Comment by xenostar** [comment]
> @xenostar the `key` property is not passed with the `props` to the `Script` component. Underneath when looping over `scripts` with the `beforeInteractive` strategy the Next passed all the rest props to the `script`, but it doesn't set the `key` prop. 
> 
> Hint: `getPreNextScripts` function in the `packages/next/pages/_document.tsx`

Good to know.

Components used outside of a mapped list or array of components shouldn't require a key prop at all in the first place, so even if adding a key was the solution for this bug I'd find it a bit odd. And as mentioned, it happens even with a _single_ Script component that has the `beforeInteractive` strategy set.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
