### ISSUE TITLE
NextJs with Firebase Hosting example not work

### ISSUE THREAD

**Issue by ooVictorFranco** [vercel/next.js#26620]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Edge - 91.0.864.54

### What operating system are you using?

Windows 10

### How are you deploying your application?

firebase

### Describe the Bug

When attempting to deploy to the original version of the cloned repository, it has no effect directly on Firebase. The `yarn deploy` command runs but when `deploying functions, hosting` appears the following line to be displayed. `Running command: npm --prefix "$PROJECT_DIR" install` starts local installation and not on the designated project.

### Expected Behavior

The expected deployment would be completed and the site updated. 

### To Reproduce

The full excerpt of what happens is below:

```
$ yarn deploy

yarn run v1.22.10
$ firebase deploy --only functions,hosting

=== Deploying to 'oovictorfranco'...

i  deploying functions, hosting
Running command: npm --prefix "$PROJECT_DIR" install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\esparse -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\esprima\bin\esparse.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\esvalidate -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\esprima\bin\esvalidate.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\he -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\he\bin\he
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\is-ci -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\is-ci\bin.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\loose-envify -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\loose-envify\cli.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\marked -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\marked\bin\marked
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\miller-rabin -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\miller-rabin\bin\miller-rabin
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\mime -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\mime\cli.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\json5 -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\json5\lib\cli.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\mkdirp -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\mkdirp\bin\cmd.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\nanoid -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\nanoid\bin\nanoid.cjs
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\gp12-pem -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\google-p12-pem\build\src\bin\gp12-pem.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\browserslist -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\browserslist\cli.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\printj -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\printj\bin\printj.njs
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\crc32 -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\crc-32\bin\crc32.njs
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\pbjs -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\protobufjs\bin\pbjs
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\pbts -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\protobufjs\bin\pbts
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\image-size -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\image-size\bin\image-size.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\cdl -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cardinal\bin\cdl.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\semver -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\semver\bin\semver.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\sha.js -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\sha.js\bin.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\js-yaml -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\js-yaml\bin\js-yaml.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\rc -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\rc\cli.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\JSONStream -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\JSONStream\bin.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\sshpk-sign -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\sshpk\bin\sshpk-sign
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\sshpk-conv -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\sshpk\bin\sshpk-conv
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\sshpk-verify -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\sshpk\bin\sshpk-verify
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\uuid -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\uuid\dist\bin\uuid
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\which -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\which\bin\which
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\cross-env -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cross-env\dist\bin\cross-env.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\cross-env-shell -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cross-env\dist\bin\cross-env-shell.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\esgenerate -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\escodegen\bin\esgenerate.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\escodegen -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\escodegen\bin\escodegen.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\rimraf -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\rimraf\bin.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\csv-streamify -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\csv-streamify\cli.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\gcs-upload -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\gcs-resumable-upload\build\src\cli.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\superstatic -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\superstatic\bin\server
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\proto-loader-gen-types -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\@grpc\proto-loader\build\bin\proto-loader-gen-types.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\compileProtos -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\google-gax\build\tools\compileProtos.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\firebase -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\firebase-tools\lib\bin\firebase.js
D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\next -> D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\next\dist\bin\next

> protobufjs@6.11.2 postinstall D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\protobufjs
> node scripts/postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: re2@1.16.0 (node_modules\re2):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, unlink 'D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\.re2.DELETE\build\Release\re2.node'

added 892 packages from 558 contributors in 117.553s
Running command: npm --prefix "$PROJECT_DIR" run build

> with-firebase-hosting@5.0.0 build D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app
> next build src/

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup

> Build error occurred
Error [BrowserslistError]: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:6305)
    at D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:7392
    at Array.reduce (<anonymous>)
    at resolve (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:6686)
    at browserslist (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:8128)
    at cleanBrowsersList (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:28882)
    at setBrowserScope (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:26831)
    at Object.8390 (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:27812)
    at __nccwpck_require__ (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:376423)
    at Object.5512 (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cssnano-preset-simple\dist\index.js:1:254257) {
  browserslist: true
}
info  - Creating an optimized production build .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! with-firebase-hosting@5.0.0 build: `next build src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the with-firebase-hosting@5.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\victo\AppData\Roaming\npm-cache\_logs\2021-06-26T02_10_03_236Z-debug.log
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix "%PROJECT_DIR%" run build ENOENT
    at notFoundError (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm --prefix "%PROJECT_DIR%" run build',
  path: 'npm --prefix "%PROJECT_DIR%" run build',
  spawnargs: []
}

Error: functions predeploy error: Command terminated with non-zero exit code1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ooVictorFranco** [comment]
The complete log of this run:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--prefix',
1 verbose cli   'D:\\victo\\Desenvolvimento\\VictorFranco\\with-firebase-hosting-app',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle with-firebase-hosting@5.0.0~prebuild: with-firebase-hosting@5.0.0
6 info lifecycle with-firebase-hosting@5.0.0~build: with-firebase-hosting@5.0.0
7 verbose lifecycle with-firebase-hosting@5.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle with-firebase-hosting@5.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\.bin;C:\Users\victo\AppData\Local\Temp\yarn--1624673275888-0.21912738957709244;D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app\node_modules\.bin;C:\Users\victo\AppData\Local\Yarn\Data\link\node_modules\.bin;C:\Users\victo\AppData\Local\Yarn\bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\PowerShell\7;C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\PowerShell\7\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\victo\AppData\Local\Microsoft\WindowsApps;C:\Users\victo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\victo\AppData\Roaming\npm
9 verbose lifecycle with-firebase-hosting@5.0.0~build: CWD: D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app
10 silly lifecycle with-firebase-hosting@5.0.0~build: Args: [ '/d /s /c', 'next build src/' ]
11 silly lifecycle with-firebase-hosting@5.0.0~build: Returned: code: 1  signal: null
12 info lifecycle with-firebase-hosting@5.0.0~build: Failed to exec build script
13 verbose stack Error: with-firebase-hosting@5.0.0 build: `next build src/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid with-firebase-hosting@5.0.0
15 verbose cwd D:\victo\Desenvolvimento\VictorFranco\with-firebase-hosting-app
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "D:\\victo\\Desenvolvimento\\VictorFranco\\with-firebase-hosting-app" "run" "build"
18 verbose node v14.17.1
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error with-firebase-hosting@5.0.0 build: `next build src/`
22 error Exit status 1
23 error Failed at the with-firebase-hosting@5.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ooVictorFranco** [comment]
**Please, can someone help with this?**

**Comment by chwan1** [comment]
Seem an issue related to `RESOURCE_DIR` mentioned [here](https://github.com/firebase/firebase-tools/issues/610). 

I just use the following in `firebase.json` instead
.`
``
    "predeploy": [
      "yarn",
      "yarn build"
    ],
```
