### ISSUE TITLE
Getting TypeError: Cannot set property 'styles' of undefined     at module.exports (...\node_modules\@zeit\next-css\css-loader-config.js:25:56) in npm run dev  after upgrading from NEXT 10 to NEXT 11

### ISSUE THREAD

**Issue by abiswas529** [vercel/next.js#26669]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

@sls-next/serverless-component@1.18.0

### Describe the Bug

Unable to run "npm run dev" after upgrading from next 10 to 11. The application was working fine in NEXT 10. Below is the error I'm getting now.

```
TypeError: Cannot set property 'styles' of undefined
    at module.exports (...\node_modules\@zeit\next-css\css-loader-config.js:25:56)
```
 Below is my **next.config.js** which was working previously 

```
const withPlugins = require("next-compose-plugins");
const withImages = require("next-images");
const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");
const webpack = require("webpack");
const withFonts = require("next-fonts");
const path = require("path");
const redirects = {
  async redirects() {
    return [
      { source: "/sitemap.xml", destination: "/api/sitemap", permanent: true },
    ];
  },
};
module.exports = withPlugins(
  [[withCSS], [withSass], [withImages], [redirects]],
  {
    webpack(config, options) {
      config.module.rules.push({
        test: /\.(eot|otf|ttf|woff|woff2)$/,
        use: {
          loader: "url-loader",
          options: {
            limit: 8192,
            publicPath: "./",
            outputPath: "./",
            name: "[name].[ext]",
          },
        },
      });
      config.resolve.modules.push(path.resolve("./"));
      return config;
    },
  }
);

```
This is package.json that I am using 

```
{
  "name": "backgorund-knockout",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "author": "Arindam Biswas",
  "dependencies": {
    "@aws-cdk/aws-dynamodb": "1.105.0",
    "@aws-cdk/core": "^1.106.1",
    "@material-ui/core": "4.9.13",
    "@material-ui/icons": "4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.57",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "1.0.1",
    "aws-sdk": "^2.917.0",
    "axios": "^0.21.1",
    "classnames": "2.2.6",
    "cookie": "^0.4.1",
    "cross-env": "^7.0.3",
    "file-saver": "^2.0.5",
    "moment": "2.25.3",
    "next": "^11.0.1",
    "next-compose-plugins": "2.2.0",
    "next-fonts": "^1.5.1",
    "next-images": "1.3.1",
    "nextjs-redirect": "2.0.2",
    "node-sass": "4.14.1",
    "nouislider": "14.4.0",
    "nprogress": "^0.2.0",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-datetime": "2.16.3",
    "react-dom": "17.0.2",
    "react-dropzone": "^11.3.2",
    "react-slick": "0.25.2",
    "react-swipeable-views": "0.13.9",
    "sitemap": "^7.0.0",
    "store": "^2.0.12",
    "streamsaver": "^2.0.5",
    "styled-components": "5.1.0",
    "url-loader": "^4.1.1",
    "uuid": "^8.3.2",
    "web-streams-polyfill": "^3.0.3",
    "webpack": "4.43.0",
    "yargs": "^16.2.0"
  },
  "devDependencies": {
    "aes-js": "^3.1.2",
    "aws-cdk": "^1.106.1",
    "react-multi-carousel": "^2.6.2",
    "ua-parser-js": "^0.7.28"
  }
}

```

### Expected Behavior

It should run as it was running in NEXT 10.

### To Reproduce

Upgrade the application from NEXT 10 to NEXT 11. Application must use "@zeit/next-css": "^1.0.1",

**Comment by timneutkens** [comment]
As part of webpack 5 rollout `@zeit/next-css` and `@zeit/next-sass` are no longer supported: https://nextjs.org/docs/messages/webpack5#custom-webpack-configuration

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
