### ISSUE TITLE
with-webpack-bundle-size-analyzer no longer works

### ISSUE THREAD

**Issue by d3lm** [vercel/next.js#26715]
### What example does this report relate to?

with-webpack-bundle-size-analyzer

### What version of Next.js are you using?

latest

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

/

### Describe the Bug

I have noticed that `with-webpack-bundle-size-analyzer` no longer works. When I added some StackBlitz buttons this one definitely worked. Here's the error I am seeing:
```
TypeError: compiler.plugin is not a function
    at WebpackBundleSizeAnalyzerPlugin.apply (/home/projects/jvmikmakp.github/node_modules/webpack-bundle-size-analyzer/build/src/plugin.js:15:18)
    at createCompiler (/home/projects/jvmikmakp.github/node_modules/next/dist/compiled/webpack/bundle5.js:141349:12)
    at create (/home/projects/jvmikmakp.github/node_modules/next/dist/compiled/webpack/bundle5.js:141402:16)
    at webpack (/home/projects/jvmikmakp.github/node_modules/next/dist/compiled/webpack/bundle5.js:141426:32)
    at f (/home/projects/jvmikmakp.github/node_modules/next/dist/compiled/webpack/bundle5.js:98978:16)
    at eval (/home/projects/jvmikmakp.github/node_modules/next/dist/build/compiler.js:4:172)
    at new Promise (<anonymous>)
    at runCompiler (/home/projects/jvmikmakp.github/node_modules/next/dist/build/compiler.js:4:106)
    at eval (/home/projects/jvmikmakp.github/node_modules/next/dist/build/index.js:12:128)
    at Span.traceAsyncFn (/home/projects/jvmikmakp.github/node_modules/next/dist/telemetry/trace/trace.js:6:590)
```

Here's a [reproduction](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-webpack-bundle-size-analyzer?file=package.json&terminal=).

### Expected Behavior

The example should work.

### To Reproduce

1. Open reproduction
2. Run `npm run analyze`

**Comment by balazsorban44** [comment]
https://github.com/vercel/next.js/tree/canary/examples/analyze-bundles is the up-to-date version, and `with-webpack-bundle-size-analyzer` is going to be removed.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
