### ISSUE TITLE
Encoded slashes at build time

### ISSUE THREAD

**Issue by tw1t611** [vercel/next.js#27437]
### What version of Next.js are you using?

11.0.2-canary.20

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

firefox, chrome

### What operating system are you using?

fedora

### How are you deploying your application?

vercel

### Describe the Bug

Like in #24775  slashes are encoded.
This happens using `yarn build` locally too.

**[[...slug]].js**
```js
import Main from "/components/main/Main.js";
import queries from "/components/main/queries";
import fetch from "/utils/fetch";

export async function getStaticPaths() {
  const pathsData = await fetch(queries().pathsQuery);
  const paths = pathsData.pages.map((page) => ({
    params: { slug: [page.path.substring(1)] },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps(context) {
  const pageData = await fetch(
    queries(`/${context.params?.slug || ""}`).pageQuery
  );
  const page = pageData.pages && pageData.pages[0];

  if (!page) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      page,
    },
  };
}

export default function MainPage(props) {
  return <Main page={props.page} />;
}
```

**Error**
```bash
> Build error occurred
Error: Export encountered errors on following paths:
	/
	/elektro-kleintransporter%2Fari-458%2Ffood-truck
	/elektro-kleintransporter%2Fari-458%2Fpritsche
	/elektro-kleintransporter%2Fari-458%2Fpritsche-mit-plane
	/elektroautos
	/elektrotransporter
	/elektrotransporter%2Fari-901%2Fkastenwagen
	/elektrotransporter%2Fari-901%2Fkipper
	/elektrotransporter%2Fari-901%2Fkofferaufbau
	/elektrotransporter%2Fari-901%2Fpritsche
	/es
	/fr
	/fr%2Fscooter-electrique%2Fari-345%2Fplateau
	/fr%2Futilitaire-electrique%2Fari-901%2Fplateau
	/fr%2Futilitaire-electrique-leger
	/fr%2Futilitaire-electrique-leger%2Fari-458%2Ffoodtruck
	/fr%2Futilitaire-electrique-leger%2Fari-458%2Ffrigorifique
	/kontakt
	/lastenmopeds%2Fari-145
	/lastenmopeds%2Fari-345%2Fkoffer
	/magazin
	/unternehmen%2Fagb
	/unternehmen%2Fdatenschutz
    at /home/user/Projects/ari-motors-v2/node_modules/next/dist/export/index.js:471:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Span.traceAsyncFn (/home/user/Projects/ari-motors-v2/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /home/user/Projects/ari-motors-v2/node_modules/next/dist/build/index.js:752:17
    at async Span.traceAsyncFn (/home/user/Projects/ari-motors-v2/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /home/user/Projects/ari-motors-v2/node_modules/next/dist/build/index.js:630:13
    at async Span.traceAsyncFn (/home/user/Projects/ari-motors-v2/node_modules/next/dist/telemetry/trace/trace.js:60:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Does not encode slashes.

### To Reproduce

1. Create the files above
2. Mock paths containing slashed e.g. `/fr/some/thing`
3. yarn build

**Comment by tw1t611** [comment]
Here is my workaround for now.
[[...slug]].js
```js
export async function getStaticPaths() {
  const pathsData = await fetch(queries().pathsQuery, true);
  const pages = pathsData.pages.filter(
    (page) => page.path.substring(0, 8) !== "/kontakt"
  );
  const paths = pages.map((page) => ({
    params: { slug: [...page.path.substring(1).split("/")] },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps(context) {
  const slug = context.params.slug?.join("/");
  const path = `/${slug ? slug : ""}`
  ...
```

**Comment by balazsorban44** [comment]
From the docs:

> If the page name uses catch-all routes, for example pages/[...slug], then params should contain slug which is an array. For example, if this array is ['foo', 'bar'], then Next.js will statically generate the page at /foo/bar.

https://nextjs.org/docs/basic-features/data-fetching#the-paths-key-required

So the expected behavior is that you return an array separated on the `/` characters in your slug. Your workaround is the correct solution.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
