### ISSUE TITLE
Tailwinds Build error occurred

### ISSUE THREAD

**Issue by coderdix** [vercel/next.js#27577]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Firefox

### What operating system are you using?

Linux (ubuntu) 

### How are you deploying your application?

other platform

### Describe the Bug

After starting my build 

> NODE_ENV=production STAGING=1 next build

info  - Loaded env from .env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Skipping validation of types
info  - Creating an optimized production build
Failed to compile.

./node_modules/tailwindcss/tailwind.css.webpack[javascript/auto]!=!./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[5].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[5].use[2]!./node_modules/tailwindcss/tailwind.css
Error: Can't resolve 'undefined' in '../node_modules/tailwindcss'

> Build error occurred
Error: > Build failed because of webpack errors
    at ../node_modules/next/dist/build/index.js:15:924
    at async Span.traceAsyncFn (../node_modules/next/dist/telemetry/trace/trace.js:6:584)

### Expected Behavior

completed build

### To Reproduce

npm run build

**Comment by leerob** [comment]
@coderdix Please add a complete reproduction and we can open and investigate this 🙏

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
