### ISSUE TITLE
Next.js custom server doesn't work if the server imports `aysnc-listener` and uses Webpack 5

### ISSUE THREAD

**Issue by danoc** [vercel/next.js#27792]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

12.18.3 (also fails on 14.17.0)

### What browser are you using?

N/A

### What operating system are you using?

Latest macOS

### How are you deploying your application?

N/A

### Describe the Bug

[Importing `aysnc-listener` in a custom Next.js server](https://github.com/danoc/next.js-async-listener-reproduction/blob/fe0ec92bdc64b1449257ff7c3410aa3327eeceec/server.js#L2) on a project that uses Webpack 5 will throw the following error:

```
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
(node:6406) UnhandledPromiseRejectionWarning: Error: Unexpected lazy element in stream
    at readU8 (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:121549:11)
    at BinaryMiddleware._deserialize (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:121842:20)
    at BinaryMiddleware.deserialize (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:121454:15)
    at Serializer.deserialize (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:123401:26)
    at PackFileCacheStrategy._openPack (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:77661:5)
    at new PackFileCacheStrategy (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:77633:27)
    at WebpackOptionsApply.process (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:73976:9)
    at createCompiler (~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:141356:28)
    at ~/next-repro/node_modules/next/dist/compiled/webpack/bundle5.js:141319:48
    at Array.map (<anonymous>)
(node:6406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6406) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '~/next-repro/.next/cache/webpack/client-development/index.pack'
(node:6406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

I stumbled upon this when trying to integrate Next.js into a codebase that uses `zipkin-context-cls`. `zipkin-context-cls` depends on `continuation-local-storage` which itself depends on `async-listener`.

This fails with both Node 12 and 14.

### Expected Behavior

Error message doesn't appear.

### To Reproduce

1. Clone the minimal reproduction: https://github.com/danoc/next.js-async-listener-reproduction
2. `yarn install`
3. `node server.js`

Notice that commenting out [the problematic line](https://github.com/danoc/next.js-async-listener-reproduction/blob/aa9adc171aa03c38acede2a2f69a73e9f5204ce5/server.js#L2) or [using Webpack 4](https://github.com/danoc/next.js-async-listener-reproduction/blob/1e318279dbf25a61822e1195a0728571ae7bf72b/next.config.js#L3) makes the error go away. Also, this error only appears when `next({ dev: true })`. The issue does not appear in production builds.

---

Potential related issues:

* https://github.com/webpack/webpack/issues/11661
* https://github.com/webpack/webpack/issues/13440

**Comment by danoc** [comment]
Potential related issues:

* https://github.com/webpack/webpack/issues/11661
* https://github.com/webpack/webpack/issues/13440

**Comment by Miikis** [comment]
I ran into [this error](https://github.com/webpack/webpack/issues/11661) when using zipkin to generate sleuth-ids for aws-xray. Resolved it by switching from using [zipkin-context-cls](https://www.npmjs.com/package/zipkin-context-cls) to the zipkin module's `ExplicitContext` instead. That setup was working fine before w/ webpack v4, for what it's worth.

**Comment by danoc** [comment]
Thanks, @Miikis! Did you also run into the issue only during local development (`next dev`)? I found that `next build && next start` was fine. My workaround was to only `import` the Zipkin on production builds.

**Comment by Miikis** [comment]
Interesting. I don't think I tried to build it — just assumed if it was causing an issue locally, it would be problematic in production. Good to know dynamically importing the module is a valid workaround tho. Thanks 😎

**Comment by JanKaifer** [comment]
Please verify that your issue can be recreated with `next@canary`.

### **Why was this issue marked with the `please verify canary` label?**

We noticed the provided reproduction was using an older version of Next.js, instead of `canary`.

The canary version of Next.js ships daily and includes all features and fixes that have not been released to the stable version yet. You can think of canary as a _public beta_. Some issues may already be fixed in the canary version, so please verify that your issue reproduces by running `npm install next@canary` and test it in your project, using your reproduction steps.

If the issue does not reproduce with the `canary` version, then it has already been fixed and this issue can be closed.

### **How can I quickly verify if my issue has been fixed in `canary`?**

The safest way is to install `next@canary` in your project and test it, but you can also search through [closed Next.js issues](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aclosed) for duplicates or check the [Next.js releases](https://github.com/vercel/next.js/releases).

### **My issue has been open for a long time, why do I need to verify `canary` now?**

Next.js does not backport bug fixes to older versions of Next.js. Instead, we are trying to introduce only a minimal amount of breaking changes between major releases.

### **What happens if I don't verify against the canary version of Next.js?**

An issue with the `please verify canary` that receives no meaningful activity (e.g. new comments that acknowledge verification against `canary`) will be automatically closed and locked after 30 days.

If your issue has not been resolved in that time and it has been closed/locked, please open a new issue, with the required reproduction, using `next@canary`.

### **I did not open this issue, but it is relevant to me, what can I do to help?**

Anyone experiencing the same issue is welcome to provide a minimal reproduction (following the above steps). Furthermore, you can upvote the issue (using the :+1: reaction on the topmost comment, instead of commenting "I have the same issue" etc.). Then, we can sort issues by engagement to prioritize.

### **I think my reproduction is good enough, why aren't you looking into it quicker?**

We look into every Next.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### **Useful Resources**

- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)
- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a Next.js bug](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml)
- [Next.js Triaging issues](https://github.com/vercel/next.js/blob/canary/contributing/repository/triaging.md)

**Comment by danoc** [comment]
Closing this since its low priority, I found a workaround, and Next.js is moving away from Webpack eventually.
