### ISSUE TITLE
Module parse failed: Unexpected character '!' (1:1)

### ISSUE THREAD

**Issue by ctjlewis** [vercel/next.js#27806]
### What version of Next.js are you using?

Next.js v11.0.1

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome (Not relevant)

### What operating system are you using?

Ubuntu (Not relevant)

### How are you deploying your application?

next

### Describe the Bug

The shebang in an entry point is breaking the Next CLI. It seems nondeterministic and I actually have no idea where to start.

```none
wait  - compiling...
error - ./node_modules/react-spotify-embed/dist/index.mjs
Module parse failed: Unexpected character '!' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node
| 
| export { default } from './react-spotify-embed.min.mjs';
```

Full `next build` output:

```none
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./node_modules/react-spotify-embed/dist/index.mjs
Module parse failed: Unexpected character '!' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node
| 
| export { default } from './react-spotify-embed.min.mjs';


> Build error occurred
Error: > Build failed because of webpack errors
    at /home/christian/PersonalProjects/shebang-repro/node_modules/next/dist/build/index.js:15:924
    at async Span.traceAsyncFn (/home/christian/PersonalProjects/shebang-repro/node_modules/next/dist/telemetry/trace/trace.js:6:584)
error Command failed with exit code 1.
```

### Expected Behavior

A shebang should not break Next's Webpack integration.

### To Reproduce

https://github.com/ctjlewis/shebang-repro/runs/3258759224?check_suite_focus=true

**Comment by ctjlewis** [comment]
See also:

https://stackoverflow.com/questions/67442212/next-js-webpack-failure-on-files-with-shebang-module-parse-failed-unexpected-c

**Comment by ctjlewis** [comment]
I have worked around this temporarily by shimming the Webpack config, and adding the `shebang-loader` or `shebang2-loader` at the front of the stack:

```js
// next.config.js
module.exports = {
  webpack: (config) => {
    config.module.rules.unshift({
      test: /.+\.(js|cjs|mjs)/,
      loader: 'shebang-loader'
    });
    return config;
  }
}
```

Where all `shebang-loader` does is discard the shebang line. `shebang2-loader` has more complicated behavior but either works.

#### My impression is that this is related to Next's shebang logic not firing for `.mjs`, `.cjs`, packages with `exports` fields in package.json, or some combination thereof.

**Comment by ctjlewis** [comment]
It looks like `.mjs` is being ignored by Webpack completely. We will want to make sure that all entry points are checked for shebangs.

From https://github.com/GoogleChrome/workbox/issues/1894:

> > I'm pretty sure Next will take the `.mjs` version, it just won't transpile it
> 
> That's exactly what's happening. Webpack takes .mjs and throws it into the bundle along with "exports xxx" expression which doesn't work when bundled among other js files into single file.

**Comment by ctjlewis** [comment]
If anyone can point to the relevant part of the codebase, I can send a PR in. The only references to "shebang" that I could find were in `packages/next/compiled`, which I did not understand at all as it appeared to be already-transpiled source code (?).

**Comment by timneutkens** [comment]
Looks like the root of the problem is that acorn is not configured to parse it:
https://astexplorer.net/#/gist/91f04094198bb34bfbebdc05b82328ac/9b93bd21ca0213017a39ede4a3cbacde0acddd87

and can be configured to support it: https://github.com/acornjs/acorn/issues/629#issuecomment-350722805

**Comment by ctjlewis** [comment]
Thank you very much Tim. I will revisit this today.

**Comment by ctjlewis** [comment]
This is where I start to draw a blank, @timneutkens - the only references to "acorn" are in compiled output that exists in `packages/next/compiled`. Is there documentation on what's going on here, and where the source is for the compiled output in `packages/next/compiled`?

**Comment by timneutkens** [comment]
webpack uses acorn to parse the imports/exports and a few other things, so this would have to be changed in webpack. Generally packages don't expose their library code as the CLI as well, you might want to move it to a separate file instead either way 🤔

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
