### ISSUE TITLE
Dynamic route page doesn't work

### ISSUE THREAD

**Issue by rtritto** [vercel/next.js#27861]
### What version of Next.js are you using?

11.0.2-canary.28

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Package manager

yarn: 2.4.2 or 3.0.0 or 3.0.1-rc.2

### Describe the Bug

After I run `yarn next`, I get this log with Watchpack error message:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled successfully
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
Watchpack Error (initial scan): TypeError: Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
```
Navigating to dynamic route `pages/post/:pid`, page `/next/dist/pages/_error` is builded.
It should be caused when dependency `which-typed-array` (dependency of `util`) is updated from 1.1.4 to newest version (currently it does not work with versions 1.1.5 and 1.1.6).

<details><summary>yarn.lock diff</summary>

```diff
---
-"available-typed-arrays@npm:^1.0.2":
+"available-typed-arrays@npm:^1.0.4":
  version: 1.0.4
  resolution: "available-typed-arrays@npm:1.0.4"
  checksum: 9474a48bed7a4bfa5ea9389acc73da5e321fac5fc299b9ba58ee9fd41d6489b6f92663a76d1b723e80c06dfe340c6b3b9f2b08762db009c53ce891e68fb0a61c
  languageName: node
  linkType: hard
---
"is-arguments@npm:^1.0.4":
-  version: 1.1.0
-  resolution: "is-arguments@npm:1.1.0"
+  version: 1.1.1
+  resolution: "is-arguments@npm:1.1.1"
  dependencies:
-    call-bind: ^1.0.0
-  checksum: 967bf47b472eba6c07685a0a2c59724c5a2f3ecc9183ebbf3d33989906e2353d0d669ca7e06b0482f31cc8e6f1785b4a2775cb9506acb48cadd0e1d5c5cf12ad
+    call-bind: ^1.0.2
+    has-tostringtag: ^1.0.0
+  checksum: 51b8bf285540cca90e49a712910d9a35f3dea61bd0bee4db04d5c4ebacbce2f493725191ab56846bce5fbc496fcc122fa8cc387c08b3cf75478a0a0b1c502bde
  languageName: node
  linkType: hard
---
-"is-typed-array@npm:^1.1.3":
-  version: 1.1.5
-  resolution: "is-typed-array@npm:1.1.5"
+"is-typed-array@npm:^1.1.3, is-typed-array@npm:^1.1.5":
+  version: 1.1.6
+  resolution: "is-typed-array@npm:1.1.6"
  dependencies:
-    available-typed-arrays: ^1.0.2
+    available-typed-arrays: ^1.0.4
    call-bind: ^1.0.2
-    es-abstract: ^1.18.0-next.2
+    es-abstract: ^1.18.5
    foreach: ^2.0.5
-    has-symbols: ^1.0.1
-  checksum: 35b216dba19e3005bf14d3b46b2a20de244818e2bd726c344a011f89673d9b50ba35b0ace81f8dfd870d96f82763389bb5cc00cd7718ac317076b6f06479c03d
+    has-tostringtag: ^1.0.0
+  checksum: 7eade5a0805e0ff4561a173858f7857a1c3cd1ced1253a2140b5a314eae95c2a20ed376bc9ae282b8968c40b23bbbff3bd33cd28732c8aa16bc04f51554597a8
  languageName: node
  linkType: hard
---
"which-typed-array@npm:^1.1.2":
-  version: 1.1.4
-  resolution: "which-typed-array@npm:1.1.4"
+  version: 1.1.5
+  resolution: "which-typed-array@npm:1.1.5"
  dependencies:
-    available-typed-arrays: ^1.0.2
-    call-bind: ^1.0.0
-    es-abstract: ^1.18.0-next.1
+    available-typed-arrays: ^1.0.4
+    call-bind: ^1.0.2
+    es-abstract: ^1.18.5
    foreach: ^2.0.5
-    function-bind: ^1.1.1
-    has-symbols: ^1.0.1
-    is-typed-array: ^1.1.3
-  checksum: aa89770be09f62f8836f2334080513f8de82ec6e9a503eb9b8867775ac47db72c0a75ac8ac7e5f71825a7b8e5eb6ef0b65dd66cea54709cf73f2ae81b722d5ec
+    has-tostringtag: ^1.0.0
+    is-typed-array: ^1.1.5
+  checksum: 6d01c9c899f8e59bfd80722738aff97659180bbec17faf8dfd983155a446b6b79cd0b692fe97cb8e01c021d412e2dd969408b55cd7f45ad2fa32ec81da05aadc
  languageName: node
  linkType: hard
---
```

</details>
I have no error message only with yarn 1 version but not with berry versions (2.x.x or 3.x.x).

Result of log that I added to get stacktrace:
```
TypeError: Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
    at URLFS.readdirPromise (.\dynamic-route-test\.pnp.cjs:9741:5)
    at .\dynamic-route-test\.pnp.cjs:12937:20
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

<details><summary>.pnp.cjs (yarn 3.0.0)</summary>

```js
...
9740  async readdirPromise(p, {
9741    withFileTypes
9742  } = {}) {
9743    return this.baseFs.readdirPromise(this.mapToBase(p), {
9744      withFileTypes: withFileTypes
9745    });
9746  }
...
12927    for (const fnName of ASYNC_IMPLEMENTATIONS) {
12928      const origName = fnName.replace(/Promise$/, ``);
12929      if (typeof patchedFs[origName] === `undefined`) continue;
12930      const fakeImpl = fakeFs[fnName];
12931      if (typeof fakeImpl === `undefined`) continue;
12932
12933      const wrapper = (...args) => {
12934        const hasCallback = typeof args[args.length - 1] === `function`;
12935        const callback = hasCallback ? args.pop() : () => {};
12936        process.nextTick(() => {
12937          fakeImpl.apply(fakeFs, args).then(result => {
12938            callback(null, result);
12939          }, error => {
12940            callback(error);
12941          });
12942        });
12943      };
12944
12945      setupFn(patchedFs, origName, wrapper);
12946    }
---
```

</details>

### Expected Behavior

No Watchpack error message in log.

### To Reproduce

1. `yarn init -y`
2. `yarn set version berry`
3. `yarn add next@canary react react-dom`
4. Create `pages/post/[pid].js` (from [example](https://nextjs.org/docs/routing/dynamic-routes) in documentation):
```js
import { useRouter } from 'next/router'

const Post = () => {
  const router = useRouter()
  const { pid } = router.query

  return <p>Post: {pid}</p>
}

export default Post
```
5. `yarn next`

**Comment by rtritto** [comment]
https://github.com/yarnpkg/berry/issues/3234

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
