### ISSUE TITLE
no-html-link-for-pages: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by AriPerkkio** [vercel/next.js#28030]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.4

### What browser are you using?

None

### What operating system are you using?

Github CI Ubuntu

### How are you deploying your application?

None

### Describe the Bug

Hello, `no-document-import-in-page` ESLint rule seems to crash in certain cases. This issue was spotted by automated CI run - it is not blocking my development or anything.

https://github.com/AriPerkkio/eslint-remote-tester/issues/246#issue-968772907

### Expected Behavior

ESLint should not crash in case of accidental imports. I'm not sure about the use case of the rule but I guess it should report since rule condition is met?

### To Reproduce

```
@next/eslint-plugin-next@11.1.0
```

```js
module.exports = {
    root: true,
    env: {
        es6: true,
        node: true,
    },
    parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
    },
    extends: ['plugin:@next/next/recommended', 'eslint:recommended'],
    rules: {
        '@next/next/no-html-link-for-pages': 'off',
    },
};

```

### Minimal repro:

Import `next/document` in any file which is not under `/pages` directory. ESLint should not crash in case of accidental imports.

```js
import Document from 'next/document'
```

```
Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/<removed>/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/<removed>/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/<removed>/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/<removed>/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/<removed>/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/<removed>/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/<removed>/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

https://github.com/vercel/next.js/blob/27ccd3cb38e39a1dbfa0d9b8935063814c1f9803/packages/eslint-plugin-next/lib/rules/no-document-import-in-page.js#L18-L19

<details>
  <summary>Crash reports from real projects</summary>

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/toomuchdesign/next-page-tester/src/_document/fetchDocumentData.ts:2`
-   Path: `toomuchdesign/next-page-tester/src/_document/fetchDocumentData.ts`
-   [Link](https://github.com/toomuchdesign/next-page-tester/blob/HEAD/src/_document/fetchDocumentData.ts)

```ts

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/toomuchdesign/next-page-tester/src/_document/render.tsx:18`
-   Path: `toomuchdesign/next-page-tester/src/_document/render.tsx`
-   [Link](https://github.com/toomuchdesign/next-page-tester/blob/HEAD/src/_document/render.tsx)

```tsx

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/voodoocreation/react-redux-boilerplate/src/components/connected/Document/Document.tsx:5`
-   Path: `voodoocreation/react-redux-boilerplate/src/components/connected/Document/Document.tsx`
-   [Link](https://github.com/voodoocreation/react-redux-boilerplate/blob/HEAD/src/components/connected/Document/Document.tsx)

```tsx

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/ilhammeidi/luxi-starter/components/head.js:2`
-   Path: `ilhammeidi/luxi-starter/components/head.js`
-   [Link](https://github.com/ilhammeidi/luxi-starter/blob/HEAD/components/head.js)

```js

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/blitz-js/blitz/packages/core/src/blitz-script.tsx:1`
-   Path: `blitz-js/blitz/packages/core/src/blitz-script.tsx`
-   [Link](https://github.com/blitz-js/blitz/blob/HEAD/packages/core/src/blitz-script.tsx)

```tsx

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/blitz-js/blitz/recipes/secureheaders/templates/core/secureheaders.ts:2`
-   Path: `blitz-js/blitz/recipes/secureheaders/templates/core/secureheaders.ts`
-   [Link](https://github.com/blitz-js/blitz/blob/HEAD/recipes/secureheaders/templates/core/secureheaders.ts)

```ts

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/relay-tools/relay-hooks/examples/relay-hook-example/pagination-nextjs-ssr/relay/withData.tsx:1`
-   Path: `relay-tools/relay-hooks/examples/relay-hook-example/pagination-nextjs-ssr/relay/withData.tsx`
-   [Link](https://github.com/relay-tools/relay-hooks/blob/HEAD/examples/relay-hook-example/pagination-nextjs-ssr/relay/withData.tsx)

```tsx

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/relay-tools/relay-hooks/examples/suspense/nextjs-ssr/relay/withData.tsx:5`
-   Path: `relay-tools/relay-hooks/examples/suspense/nextjs-ssr/relay/withData.tsx`
-   [Link](https://github.com/relay-tools/relay-hooks/blob/HEAD/examples/suspense/nextjs-ssr/relay/withData.tsx)

```tsx

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

## Rule: no-document-import-in-page

-   Message: `The "path" argument must be of type string. Received undefined Occurred while linting /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-remote-tester/.cache-eslint-remote-tester/DeSigaar/desigaar.com/components/Head/index.tsx:2`
-   Path: `DeSigaar/desigaar.com/components/Head/index.tsx`
-   [Link](https://github.com/DeSigaar/desigaar.com/blob/HEAD/components/Head/index.tsx)

```tsx

```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.parse (path.js:1422:5)
    at ImportDeclaration (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/@next/eslint-plugin-next/lib/rules/no-document-import-in-page.js:19:36)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

</details>

**Comment by dohomi** [comment]
I have the same issue, the problem is that I purposely use document data outside of the pages folder to easily share code

**Comment by fabb** [comment]
Same issue here, i just import `DocumentContext` from `next/document` for a helper type in a helper file that i use in _document. I could move it to _document, but i'd like to have the type separated. It doesn't even work when using `import type { DocumentContext } from 'next/document'`, would be nice if that was allowed in the rule.

**Comment by fabb** [comment]
Also the rule should just result in a linter error, and not crash eslint.

**Comment by fabb** [comment]
My temporary fix is to use `overrides` in .eslintrc (since just using an `// eslint-disable-next-line` comment did not help):
```
    overrides: [
        {
            // fix for next.js linter bug: https://github.com/vercel/next.js/issues/28030
            files: ['**/types/nextJS.ts'],
            rules: {
                '@next/next/no-document-import-in-page': 'off',
            },
        },
    ],
```

**Comment by tettoffensive** [comment]
I'm getting this `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined` when I include `"plugin:@next/next/recommended"`. I don't know that it's in relation to this rule (I get no other information from `next lint`). My guess is that it's another error since the only place I import `next/document` is in `_document.tsx`

Any clues as to what's going on or how I could debug?

**Comment by makedirectory** [comment]
> I'm getting this `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined` when I include `"plugin:@next/next/recommended"`. I don't know that it's in relation to this rule (I get no other information from `next lint`). My guess is that it's another error since the only place I import `next/document` is in `_document.tsx`
> 
> Any clues as to what's going on or how I could debug?

Try `yarn add -D eslint-config-next` or `npm install eslint-config-next --save-dev`
