### ISSUE TITLE
When use next/image for import external image, always return typeError

### ISSUE THREAD

**Issue by KimPinot** [vercel/next.js#28145]
### What example does this report relate to?

next/image

### What version of Next.js are you using?

11.1.0, 11.0.1

### What version of Node.js are you using?

14.16.1

### What browser are you using?

safari, firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next (development)

### Describe the Bug

The error 'TypeError: undefined is not available (cannot read property Symbol (Symbol.iterator)') always occurs whenever I add next/image, with nothing installed any packages.

I tried next version 11.0.1 and 11.1  but always error displayed.

You can see the issues in the codesandbox below.

[codesandbox](https://codesandbox.io/s/dank-hooks-j4d8v?file=/pages/index.js)

### Expected Behavior

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at eval (webpack-internal:///./node_modules/next/dist/client/image.js:124:18)
    at Object../node_modules/next/dist/client/image.js (/sandbox/.next/server/pages/index.js:22:1)
    at __webpack_require__ (/sandbox/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./node_modules/next/image.js:1:18)
    at Object../node_modules/next/image.js (/sandbox/.next/server/pages/index.js:142:1)
    at __webpack_require__ (/sandbox/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:7:68)
    at Object../pages/index.js (/sandbox/.next/server/pages/index.js:55:1)
    at __webpack_require__ (/sandbox/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/sandbox/.next/server/pages/index.js:174:52)
```

### To Reproduce

```javascript
import Image from "next/image";

export default function IndexPage() {
  return (
    <Image
      width="300"
      height="300"
      src="https://static1.squarespace.com/static/5b475b2c50a54f54f9b4e1dc/t/5b5a3938562fa764113169a6/1532639559620/DSCF3338.jpg"
    />
  );
}
```

**Comment by KimPinot** [comment]
However, there is no error when importing local images.

[codesandbox](https://codesandbox.io/s/amazing-fermat-ty98k?file=/pages/index.js)
