### ISSUE TITLE
with-sentry next export does not work

### ISSUE THREAD

**Issue by talaikis** [vercel/next.js#28409]
### What example does this report relate to?

with-sentry

### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next build && next export

### Describe the Bug

Same for pages that have no serverSideProps:

```
Error occurred prerendering page "/ssr/test1". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error for page /ssr/test1: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export
    at \with-sentry-app\node_modules\next\dist\export\worker.js:228:27
    at async Span.traceAsyncFn (with-sentry-app\node_modules\next\dist\telemetry\trace\trace.js:60:20)
```

### Expected Behavior

`next export` should work

### To Reproduce

```bash
npx create-next-app --example with-sentry with-sentry-app
cd with-sentry-app
npm run build
npx next export
```

**Comment by leerob** [comment]
The Sentry example is showing client _and_ server, so it won't work with `next export`. I would recommend using `next start` 👍

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
