### ISSUE TITLE
Updating to ESM modules like remark-slug etc fails build due to cache in .next folder

### ISSUE THREAD

**Issue by marcofranssen** [vercel/next.js#28567]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

16.7.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When bumping some modules like `remark-slug` and a whole bunch of other `remark-*` libraries to the latest ESM ones next build sometimes fails. 

I think it caused by some caching inside `.next` folder.

See here an abstract of the log from Vercel.

```bash
19:53:50.278 | > Build error occurred
-- | --
19:53:50.280 | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /vercel/path0/node_modules/remark-slug/index.js
19:53:50.280 | require() of ES modules is not supported.
19:53:50.280 | require() of /vercel/path0/node_modules/remark-slug/index.js from /vercel/path0/.next/server/pages/[slug].js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
19:53:50.281 | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /vercel/path0/node_modules/remark-slug/package.json.
19:53:50.281 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
19:53:50.282 | at Module.load (internal/modules/cjs/loader.js:937:32)
19:53:50.282 | at Function.Module._load (internal/modules/cjs/loader.js:778:12)
19:53:50.282 | at Module.require (internal/modules/cjs/loader.js:961:19)
19:53:50.282 | at require (internal/modules/cjs/helpers.js:92:18)
19:53:50.282 | at Object.4674 (/vercel/path0/.next/server/pages/[slug].js:464:46)
19:53:50.282 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
19:53:50.282 | at /vercel/path0/.next/server/pages/[slug].js:570:78
19:53:50.283 | at Function.__webpack_require__.a (/vercel/path0/.next/server/webpack-runtime.js:98:13)
19:53:50.283 | at Object.1103 (/vercel/path0/.next/server/pages/[slug].js:545:21) {
19:53:50.283 | type: 'NodeError',
19:53:50.283 | code: 'ERR_REQUIRE_ESM'
19:53:50.283 | }
19:53:50.310 | error Command failed with exit code 1.
19:53:50.310 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:53:50.340 | Error: Command "yarn run build" exited with 1
```

Running same on local works if I delete he `.next` directory.

### Expected Behavior

When switching to ESM implementations of dependencies and replacing the code as explained [here](https://nextjs.org/docs/messages/import-esm-externals) `yarn dev` and `yarn build` work, no matter what.

### To Reproduce

Take an existing project that depends on an older `remark-*` dependency and run `yarn build`. Then update the module and code for that dependency to the ESM approach and run `yarn build`.

You will see the build failes with some ESM error.

Then delete the `.next` folder.

Run `yarn build` again. ✅ all works

**Comment by JanKaifer** [comment]
Please verify that your issue can be recreated with `next@canary`.

### **Why was this issue marked with the `please verify canary` label?**

We noticed the provided reproduction was using an older version of Next.js, instead of `canary`.

The canary version of Next.js ships daily and includes all features and fixes that have not been released to the stable version yet. You can think of canary as a _public beta_. Some issues may already be fixed in the canary version, so please verify that your issue reproduces by running `npm install next@canary` and test it in your project, using your reproduction steps.

If the issue does not reproduce with the `canary` version, then it has already been fixed and this issue can be closed.

### **How can I quickly verify if my issue has been fixed in `canary`?**

The safest way is to install `next@canary` in your project and test it, but you can also search through [closed Next.js issues](https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aclosed) for duplicates or check the [Next.js releases](https://github.com/vercel/next.js/releases).

### **My issue has been open for a long time, why do I need to verify `canary` now?**

Next.js does not backport bug fixes to older versions of Next.js. Instead, we are trying to introduce only a minimal amount of breaking changes between major releases.

### **What happens if I don't verify against the canary version of Next.js?**

An issue with the `please verify canary` that receives no meaningful activity (e.g. new comments that acknowledge verification against `canary`) will be automatically closed and locked after 30 days.

If your issue has not been resolved in that time and it has been closed/locked, please open a new issue, with the required reproduction, using `next@canary`.

### **I did not open this issue, but it is relevant to me, what can I do to help?**

Anyone experiencing the same issue is welcome to provide a minimal reproduction (following the above steps). Furthermore, you can upvote the issue (using the :+1: reaction on the topmost comment, instead of commenting "I have the same issue" etc.). Then, we can sort issues by engagement to prioritize.

### **I think my reproduction is good enough, why aren't you looking into it quicker?**

We look into every Next.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### **Useful Resources**

- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)
- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a Next.js bug](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml)
- [Next.js Triaging issues](https://github.com/vercel/next.js/blob/canary/contributing/repository/triaging.md)

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
