### ISSUE TITLE
ReferenceError when using next/script in  beforeInteractive strategy 

### ISSUE THREAD

**Issue by zero734kr** [vercel/next.js#28593]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Google Chrome 92.0.4515.159

### What operating system are you using?

Linux Mint 20.2

### How are you deploying your application?

Vercel

### Describe the Bug

(Error only when I use ``yarn build``.)

Since I updated next.js to v11.1.0, the following error is causing the build to fail.

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: document is not defined
    at loadScript (<MY_PROJECT>/node_modules/next/dist/client/script.js:94:16)
    at Script (<MY_PROJECT>/node_modules/next/dist/client/script.js:181:13)
    at d (<MY_PROJECT>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (<MY_PROJECT>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (<MY_PROJECT>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (<MY_PROJECT>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToStaticMarkup (<MY_PROJECT>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at renderDocument (<MY_PROJECT>/node_modules/next/dist/server/render.js:111:47)
    at renderToHTML (<MY_PROJECT>/node_modules/next/dist/server/render.js:664:16)
    at async <MY_PROJECT>/node_modules/next/dist/export/worker.js:276:36
```

It is throwing this error on all files that are pages when use ``next/script`` with beforeInteractive strategy in ``_document.tsx``.

In the afterInteractive strategy, the error will not appear.

### Expected Behavior

Success on production build without errors.

### To Reproduce

``_document.tsx``:
```tsx
import Document, { Html, Main, NextScript } from 'next/document'
import Script from 'next/script'

export default class MyDocument extends Document {
  render() {
    return (
      <Html>
        <body>
          <Main />
          <NextScript />

          <Script strategy="beforeInteractive" async src='/js/webp-modernizr.js' />
        </body>
      </Html>
    )
  }
}
```

``/js/webp-modernizr.js``:
```js
/*! modernizr 3.6.0 (Custom Build) | MIT *
 * https://modernizr.com/download/?-webp-setclasses ! */
!(function (e, n, A) { function o (e, n) { return typeof e === n } function t () { let e, n, A, t, a, i, l; for (const f in r) if (r.hasOwnProperty(f)) { if (e = [], n = r[f], n.name && (e.push(n.name.toLowerCase()), n.options && n.options.aliases && n.options.aliases.length)) for (A = 0; A < n.options.aliases.length; A++)e.push(n.options.aliases[A].toLowerCase()); for (t = o(n.fn, 'function') ? n.fn() : n.fn, a = 0; a < e.length; a++)i = e[a], l = i.split('.'), l.length === 1 ? Modernizr[l[0]] = t : (!Modernizr[l[0]] || Modernizr[l[0]] instanceof Boolean || (Modernizr[l[0]] = new Boolean(Modernizr[l[0]])), Modernizr[l[0]][l[1]] = t), s.push((t ? '' : 'no-') + l.join('-')) } } function a (e) { let n = u.className; const A = Modernizr._config.classPrefix || ''; if (c && (n = n.baseVal), Modernizr._config.enableJSClass) { const o = new RegExp('(^|\\s)' + A + 'no-js(\\s|$)'); n = n.replace(o, '$1' + A + 'js$2') }Modernizr._config.enableClasses && (n += ' ' + A + e.join(' ' + A), c ? u.className.baseVal = n : u.className = n) } function i (e, n) { if (typeof e === 'object') for (const A in e)f(e, A) && i(A, e[A]); else { e = e.toLowerCase(); const o = e.split('.'); let t = Modernizr[o[0]]; if (o.length == 2 && (t = t[o[1]]), typeof t !== 'undefined') return Modernizr; n = typeof n === 'function' ? n() : n, o.length == 1 ? Modernizr[o[0]] = n : (!Modernizr[o[0]] || Modernizr[o[0]] instanceof Boolean || (Modernizr[o[0]] = new Boolean(Modernizr[o[0]])), Modernizr[o[0]][o[1]] = n), a([(n && n != 0 ? '' : 'no-') + o.join('-')]), Modernizr._trigger(e, n) } return Modernizr } var s = []; var r = []; const l = { _version: '3.6.0', _config: { classPrefix: '', enableClasses: !0, enableJSClass: !0, usePrefixes: !0 }, _q: [], on: function (e, n) { const A = this; setTimeout(function () { n(A[e]) }, 0) }, addTest: function (e, n, A) { r.push({ name: e, fn: n, options: A }) }, addAsyncTest: function (e) { r.push({ name: null, fn: e }) } }; var Modernizr = function () {}; Modernizr.prototype = l, Modernizr = new Modernizr(); let f; var u = n.documentElement; var c = u.nodeName.toLowerCase() === 'svg'; !(function () { const e = {}.hasOwnProperty; f = o(e, 'undefined') || o(e.call, 'undefined') ? function (e, n) { return n in e && o(e.constructor.prototype[n], 'undefined') } : function (n, A) { return e.call(n, A) } }()), l._l = {}, l.on = function (e, n) { this._l[e] || (this._l[e] = []), this._l[e].push(n), Modernizr.hasOwnProperty(e) && setTimeout(function () { Modernizr._trigger(e, Modernizr[e]) }, 0) }, l._trigger = function (e, n) { if (this._l[e]) { const A = this._l[e]; setTimeout(function () { let e, o; for (e = 0; e < A.length; e++)(o = A[e])(n) }, 0), delete this._l[e] } }, Modernizr._q.push(function () { l.addTest = i }), Modernizr.addAsyncTest(function () { function e (e, n, A) { function o (n) { const o = n && n.type === 'load' ? t.width == 1 : !1; const a = e === 'webp'; i(e, a && o ? new Boolean(o) : o), A && A(n) } var t = new Image(); t.onerror = o, t.onload = o, t.src = n } const n = [{ uri: 'data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoBAAEAAwA0JaQAA3AA/vuUAAA=', name: 'webp' }, { uri: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAABBxAR/Q9ERP8DAABWUDggGAAAADABAJ0BKgEAAQADADQlpAADcAD++/1QAA==', name: 'webp.alpha' }, { uri: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4WAoAAAASAAAAAAAAAAAAQU5JTQYAAAD/////AABBTk1GJgAAAAAAAAAAAAAAAAAAAGQAAABWUDhMDQAAAC8AAAAQBxAREYiI/gcA', name: 'webp.animation' }, { uri: 'data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAAAAAAfQ//73v/+BiOh/AAA=', name: 'webp.lossless' }]; const A = n.shift(); e(A.name, A.uri, function (A) { if (A && A.type === 'load') for (let o = 0; o < n.length; o++)e(n[o].name, n[o].uri) }) }), t(), a(s), delete l.addTest, delete l.addAsyncTest; for (let p = 0; p < Modernizr._q.length; p++)Modernizr._q[p](); e.Modernizr = Modernizr }(window, document))
```

**Comment by bastienrobert** [comment]
I'm getting the same issue with polyfill.io:

```
<Script
            strategy="beforeInteractive"
            src={`https://polyfill.io/v3/polyfill.min.js?features=${[
              'Intl',
              'IntersectionObserver',
              'ResizeObserver',
              'Intl.DisplayNames.~locale.en',
              'Intl.DisplayNames.~locale.fr',
              'Intl.NumberFormat.~locale.en',
              'Intl.NumberFormat.~locale.fr',
              'Intl.DateTimeFormat.~locale.en',
              'Intl.DateTimeFormat.~locale.fr',
            ].join(',')}`}
          />
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
