### ISSUE TITLE
experimental-serverless-trace causes components to be loaded as promises

### ISSUE THREAD

**Issue by m50** [vercel/next.js#28595]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

15.5.0

### What browser are you using?

Vivaldi

### What operating system are you using?

macOs

### How are you deploying your application?

Netlify

### Describe the Bug

If I have target set to `experimental-serverless-trace`, then `next build` fails with:
```
> Build error occurred
Error: Build optimization failed: found pages without a React Component as default export in 
pages/portfolio/instagram
pages/portfolio/[slug]

See https://nextjs.org/docs/messages/page-without-valid-component for more info.

    at /Users/marisaclardy/src/github.com/m50/lydiamichelle.com/node_modules/next/dist/build/index.js:597:19
    at async Span.traceAsyncFn (/Users/marisaclardy/src/github.com/m50/lydiamichelle.com/node_modules/next/dist/telemetry/trace/trace.js:60:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

However if I set it `serverless`, then `next build` succeeds without issue.

When digging through it, I noticed that when it loaded the component, it loaded them as a Promise for some reason.

Additionally, this started to happen after updating to Next 11.1.0. When I was on Next 10.X.X (don't know exact version anymore, sorry), it built just fine on `experimental-serverless-trace`.

Both files default export react components correctly, and neither is particularly strange with regards to how they are built.

The only thing of importance, I suppose (though when going through the source, it never makes it to this), is that I use cwebp to process some images (as when I originally built this, next/image wasn't supported on Netlify) in the `getStaticPaths` and `getStaticProps` for at least one of those pages. Again, not sure that is relevant though, because it never even gets to calling those before it dies. cwebp only seems to consistantly work in github actions if the target is set to `experimental-serverless-trace` though, which is why I switched to it in the first place.

### Expected Behavior

Build should succeed in `experimental-serverless-trace` in Next 11, just like it did in Next 10, and just like it does with target set to `serverless`.

### To Reproduce

Not sure how to reproduce, but you can reproduce it with this github repo: https://github.com/m50/lydiamichelle.com

Changing the config between the two, you can see the behaviour.

Not sure what exactly is causing it though.

I narrowed it down to the three lines at `src/templates/Series/index.tsx:31`:

```tsx
      {series.body && <Body content={series.body} />}
      <ImageGrid images={series.images} onImageClick={onImageClick} />
      {selectedImage && <ImageModal onClickAway={onOutsideClick} image={selectedImage} />}
```

If I comment all three of those lines out, it builds. But if any of them are there, it fails to load. Not sure what it is about those three that are problematic though....

**Comment by balazsorban44** [comment]
Hi, the target option has been deprecated  https://nextjs.org/blog/next-12#breaking-changes

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
