### ISSUE TITLE
`@next/next/next-script-for-ga` Eslint rule crashing

### ISSUE THREAD

**Issue by mrtnzlml** [vercel/next.js#28635]
### What version of Next.js are you using?

11.1.1

### What version of Node.js are you using?

16.8.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Hi, I am trying a new Eslint rule `@next/next/next-script-for-ga`, however, it's crashing with the following error:

```text
Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read property '0' of undefined
Occurred while linting /Users/martinzlamal/Work/adeira/universe/src/abacus-kochka/pages/_document.js:43
    at JSXOpeningElement (/Users/martinzlamal/Work/adeira/universe/node_modules/@next/eslint-plugin-next/lib/rules/next-script-for-ga.js:56:54)
    at /Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/martinzlamal/Work/adeira/universe/node_modules/eslint/lib/linter/linter.js:960:32
    at Array.forEach (<anonymous>)
```

The exact file where you can try it is here: https://github.com/adeira/universe/blob/591be278911ea24f22be6f151d2399fe98d56492/src/abacus-kochka/pages/_document.js

I understand that it would be welcomed to fix the file according to the new Eslint rule. But, I believe it should not be failing like this regardless.

### Expected Behavior

The `@next/next/next-script-for-ga` Eslint rule should not fail unexpectedly.

### To Reproduce

Try to run the mentioned Eslint rule on this file: https://github.com/adeira/universe/blob/591be278911ea24f22be6f151d2399fe98d56492/src/abacus-kochka/pages/_document.js

**Comment by rgabs** [comment]
Thank you for creating the issue. I am working on fixing this issue.

**Comment by mrtnzlml** [comment]
Awesome, thanks @rgabs!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
