### ISSUE TITLE
unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by pgrodrigues** [vercel/next.js#28693]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

After upgrading to `next` 11.1.0, I started getting this error:

```js
error - unhandledRejection: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined    at Function.byteLength (buffer.js:727:11)
    at ServerResponse.apiRes.end (C:\path-to-project\node_modules\next\dist\server\api-utils.js:73:41)
    at writeend (C:\path-to-project\node_modules\express-session\index.js:262:22)
    at ontouch (C:\path-to-project\node_modules\express-session\index.js:353:11)
    at C:\path-to-project\node_modules\connect-mongo\build\main\lib\MongoStore.js:339:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
```

The code below found in `server/api-utils.ts` is not accounting for the possibility of the first parameter `args[0]` being `undefined`. Since the if condition does not cover such scenario, calling `Buffer.byteLength` with `undefined` will result in an error because `args[0]` type is not a supported type ([supported types are: `String`, `Buffer`, `TypedArray`, `DataView`, `ArrayBuffer`](https://nodejs.org/dist./v6.3.0/docs/api/buffer.html#buffer_class_method_buffer_bytelength_string_encoding)).

```js
  apiRes.end = (...args: any[2]) => {
    if (args.length && typeof args[0] !== 'function') {
      contentLength += Buffer.byteLength(args[0])
    }
```

### Expected Behavior

No error should happen

### To Reproduce

I was able to reproduce this in my app in development that uses:
- `next` 11.1.0
- `express-session` 
- `connect-mongo` session store
- `passport`
- `next-connect`

After logging in and navigating around.

With `next` 11.0.1, this error does not occur.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
