### ISSUE TITLE
next export fails Error: Minified React error #321; (Object.exports.useContext)

### ISSUE THREAD

**Issue by simplenotezy** [vercel/next.js#29115]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

v16.6.2 (also tried v12.22.1, and v14.17.1)

### What browser are you using?

Chrome

### What operating system are you using?

macOS (M1 - ARM)

### How are you deploying your application?

next export

### Describe the Bug

Build is failing when running `next export`, even with a very simple setup

```
[me:~/Projects/nextjs-build-error]$ rm -rf node_modules && rm -rf .next && npm install && NODE_ENV=development next build && next export                                       (main)
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 504 packages, and audited 505 packages in 3s

82 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
info  - Loaded env from /Users/me/Projects/nextjs-build-error/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Detected next.config.js, no exported configuration found. https://nextjs.org/docs/messages/empty-configuration
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/3)
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.development.js:1476:13)
    at Object.useContext (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.development.js:1484:20)
    at Head (/Users/me/Projects/nextjs-build-error/node_modules/next/dist/shared/lib/head.js:170:34)
    at processChild (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/opt/homebrew/lib/node_modules/next/dist/server/render.js:596:45)
    at Function.getInitialProps (/Users/me/Projects/nextjs-build-error/.next/server/chunks/303.js:602:19)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.development.js:1476:13)
    at Object.useContext (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.development.js:1484:20)
    at Head (/Users/me/Projects/nextjs-build-error/node_modules/next/dist/shared/lib/head.js:170:34)
    at processChild (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/opt/homebrew/lib/node_modules/next/dist/server/render.js:596:45)
    at Function.getInitialProps (/Users/me/Projects/nextjs-build-error/.next/server/chunks/303.js:602:19)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.development.js:1476:13)
    at Object.useContext (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.development.js:1484:20)
    at Head (/Users/me/Projects/nextjs-build-error/node_modules/next/dist/shared/lib/head.js:170:34)
    at processChild (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/opt/homebrew/lib/node_modules/next/dist/server/render.js:596:45)
    at Function.getInitialProps (/Users/me/Projects/nextjs-build-error/.next/server/chunks/303.js:602:19)
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
	/
	/404
	/500
    at /opt/homebrew/lib/node_modules/next/dist/export/index.js:487:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Span.traceAsyncFn (/opt/homebrew/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /opt/homebrew/lib/node_modules/next/dist/build/index.js:833:17
    at async Span.traceAsyncFn (/opt/homebrew/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /opt/homebrew/lib/node_modules/next/dist/build/index.js:707:13
    at async Span.traceAsyncFn (/opt/homebrew/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/opt/homebrew/lib/node_modules/next/dist/build/index.js:77:25)
```

### To Reproduce

https://github.com/simplenotezy/nextjs-export-error

1) Pull down,
2) Run npm install
3) Run `next build`
4) Run `next export` here's the error.

**Comment by simplenotezy** [comment]
OK, so a follow up here. After hours of trying different things, it seems to make the difference if I do `npm run build` instead of `next build`. Here's an example:

```
[me:~/Projects/nextjs-build-error]$ next build                                                                                                                                                     (main✱)
info  - Loaded env from /Users/me/Projects/nextjs-build-error/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Detected next.config.js, no exported configuration found. https://nextjs.org/docs/messages/empty-configuration
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/3)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.production.min.js:18:327)
    at Object.exports.useContext (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.production.min.js:22:269)
    at Html (/Users/me/Projects/nextjs-build-error/.next/server/chunks/303.js:624:19)
    at d (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToStaticMarkup (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at renderToHTML (/opt/homebrew/lib/node_modules/next/dist/server/render.js:711:41)
    at async /opt/homebrew/lib/node_modules/next/dist/export/worker.js:273:36

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.production.min.js:18:327)
    at Object.exports.useContext (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.production.min.js:22:269)
    at Html (/Users/me/Projects/nextjs-build-error/.next/server/chunks/303.js:624:19)
    at d (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToStaticMarkup (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at renderToHTML (/opt/homebrew/lib/node_modules/next/dist/server/render.js:711:41)
    at async /opt/homebrew/lib/node_modules/next/dist/export/worker.js:273:36

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.production.min.js:18:327)
    at Object.exports.useContext (/Users/me/Projects/nextjs-build-error/node_modules/react/cjs/react.production.min.js:22:269)
    at Html (/Users/me/Projects/nextjs-build-error/.next/server/chunks/303.js:624:19)
    at d (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToStaticMarkup (/opt/homebrew/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at renderToHTML (/opt/homebrew/lib/node_modules/next/dist/server/render.js:711:41)
    at async /opt/homebrew/lib/node_modules/next/dist/export/worker.js:273:36
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
	/
	/404
	/500
    at /opt/homebrew/lib/node_modules/next/dist/export/index.js:487:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Span.traceAsyncFn (/opt/homebrew/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /opt/homebrew/lib/node_modules/next/dist/build/index.js:833:17
    at async Span.traceAsyncFn (/opt/homebrew/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async /opt/homebrew/lib/node_modules/next/dist/build/index.js:707:13
    at async Span.traceAsyncFn (/opt/homebrew/lib/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/opt/homebrew/lib/node_modules/next/dist/build/index.js:77:25)
[me:~/Projects/nextjs-build-error]$ npm run build                                                                                                                                                  (main✱)

> nextjs@0.1.0 build
> next build

info  - Loaded env from /Users/me/Projects/nextjs-build-error/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Detected next.config.js, no exported configuration found. https://nextjs.org/docs/messages/empty-configuration
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (3/3)
info  - Finalizing page optimization

Page                             Size     First Load JS
┌ ○ /                            265 B          65.7 kB
├   /_app                        0 B            65.5 kB
└ ○ /404                         1.36 kB        66.8 kB
+ First Load JS shared by all    65.5 kB
  ├ chunks/framework.923004.js   42 kB
  ├ chunks/main.c03421.js        20.2 kB
  ├ chunks/pages/_app.2d4e5c.js  2.49 kB
  └ chunks/webpack.672781.js     766 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
```

**Comment by ijjk** [comment]
Hi, it sounds like you have next installed globally which isn't supported, please make sure you uninstall it from the global `node_modules` with `npm remove -g next` and then run it inside of the project with `npm run build`

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
