### ISSUE TITLE
Rewrites error with Query Matching : "invalid field: has for route"

### ISSUE THREAD

**Issue by raphaelchalicarne** [vercel/next.js#29171]
### What version of Next.js are you using?

10.0.6

### What version of Node.js are you using?

15.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

yarn run dev

### Describe the Bug

I want to rewrite a route using [Query Matching](https://nextjs.org/docs/api-reference/next.config.js/rewrites#header-cookie-and-query-matching).

### Expected Behavior

I have a url `/r/:route?flavor=homepage`, and I want my route to be written as `/r/:route/homepage`.

### To Reproduce

In my next.config.js file, the `rewrites` function is set to :
```
  rewrites: async () => {
    return [
      {
        source: '/r/:route',
        has: [
          {
            type: 'query',
            key: 'flavor',
            value: 'homepage',
          },
        ],
        destination: '/r/:route/homepage',
      }
    ]
  },
```

My page name is set to [repo_path]/pages/r/[...route].js.

When I start my server, I have the following error :
```
https://github.com/browserslist/browserslist#browsers-data-updating
 invalid field: has for route {"source":"/r/:route","has":[{"type":"query","key":"flavor","value":"homepage"}],"destination":"/r/:route/homepage"}

Error: Invalid rewrite found
    at checkCustomRoutes ([repo_path]/node_modules/next/dist/lib/load-custom-routes.js:8:1575)
    at loadRewrites ([repo_path]/node_modules/next/dist/lib/load-custom-routes.js:8:3466)
    at async Promise.all (index 1)
    at async loadCustomRoutes ([repo_path]/node_modules/next/dist/lib/load-custom-routes.js:8:3829)
    at async DevServer.prepare ([repo_path]/node_modules/next/dist/server/next-dev-server.js:14:669)
    at async [repo_path]/node_modules/next/dist/cli/next-dev.js:22:1
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
