### ISSUE TITLE
Router.back() and history.back() is not working (`popstate` event triggered but `event.state`.....)

### ISSUE THREAD

**Issue by aslanon** [vercel/next.js#29177]
### What version of Next.js are you using?

9.3.5

### What version of Node.js are you using?

v10.18.0

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

other platform

### Describe the Bug

I am using Router.push. And when using this method page is opening. It's working. But when use browser back button, Router.back or history.push() is updating URL but not navigating to it in browser and page is not opening. But page URL is updating.

![image](https://user-images.githubusercontent.com/304654/133779591-eb599cf7-acb2-43c4-b412-5c74fb9d0333.png)

`"next-routes": "^1.4.2",`

### Expected Behavior

Changing the URL, opening the page 

### To Reproduce

use browser back button

**Comment by ijjk** [comment]
Hi, this should be working correctly in the latest version of Next.js `v11.1.2`, please upgrade and give it a try! Note: we also have tests covering this behavior [here](https://github.com/vercel/next.js/blob/2333f7c1b882dff09b944967a29162f9aca42e7d/test/e2e/basepath.test.ts#L100) which are passing.

**Comment by aslanon** [comment]
I'm upgrade my next version to v11.1.2 but I have new error in console.  @ijjk 

output 
`Error [ERR_METHOD_NOT_IMPLEMENTED]: The _write() method is not implemented
    at Writable._write (_stream_writable.js:566:6)
    at doWrite (_stream_writable.js:415:12)
    at clearBuffer (_stream_writable.js:545:7)
    at Writable.uncork (_stream_writable.js:319:7)
    at /Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1346:11
    at /Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1330:7
    at rhs (/Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1330:44)
    at /Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1348:5
    at /Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1330:7
    at Promise (/Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1361:5)
    at new Promise (<anonymous>)
    at piperToString (/Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1353:10)
    at Object.renderToHTML (/Users/aslanon/xxx/xxx.web/node_modules/next/server/render.tsx:1187:22)`

**Comment by ijjk** [comment]
Hmm are you seeing the same error in the latest canary `v11.1.3-canary.26`? Note this error is unrelated to the original so if persists might be good to open a new issue with minimal reproduction.

**Comment by aslanon** [comment]
I don't know canary. But package.json has this package. @ijjk 
![image](https://user-images.githubusercontent.com/304654/134182060-7dc5a58f-64a9-4250-9386-7d25785c7529.png)

**Comment by ijjk** [comment]
Can you share the contents of the page you are seeing this error on?

**Comment by aslanon** [comment]
it doesn't say which page is causing. But I suspect this page.

![image](https://user-images.githubusercontent.com/304654/134183931-a0a5f6a0-72f7-47c5-a5cb-e7e5e2f3bb02.png)

**Comment by ijjk** [comment]
Oh this does look related to https://github.com/vercel/next.js/issues/28423

I would recommend against returning `notFound: true` there. If you are wanting to redirect in `getStaticProps`/`getServerSideProps` you can use the `redirect` field instead, related documentation https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering

**Comment by aslanon** [comment]
I updated to the latest version of Next.Js. Currently there is no error in the console (browser and terminal), but the browser's back button does not work. The URL is updated but the content does not change. :( @ijjk

**Comment by ijjk** [comment]
Hi, can you provide a repo with a minimal reproduction? This is most like related to user code and will require more information to provide further assistance.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
