### ISSUE TITLE
Errors lost in `next dev` when using PnP in Yarn v3

### ISSUE THREAD

**Issue by monotykamary** [vercel/next.js#29344]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next dev

### Describe the Bug

Normally when Next.js catches an error on the server-side, both the navigated page and server console will return a stack trace regarding the error. When using yarn v3 in PnP mode, neither of these occur and will simply just log the event that an error page was created:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.2.4
event - compiled successfully
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
info  - Using external babel configuration from /home/sherry/VCS/working-remote/with-typescript-styled-components-app/.babelrc
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
```

### Expected Behavior

With npm, yarn v1, or yarn v3 with `nodeLinker: node_modules`, both the navigated page and console will return a stack trace concerning the error:

![image](https://user-images.githubusercontent.com/1130103/134600564-88cbe4cf-dd60-4e6a-891c-d4d9f7c0102d.png)

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - Minimum recommended TypeScript version is v4.3.2, older versions can potentially be incompatible with Next.js. Detected: 4.2.4
info  - Using external babel configuration from /home/sherry/VCS/working-remote/with-typescript-styled-components-app/.babelrc
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - build page: /
event - compiled successfully
error - Error: ReactDOMServer does not yet support Suspense.
    at ReactDOMServerRenderer.render (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3844:25)
    at ReactDOMServerRenderer.read (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/server/render.js:596:45)
    at Object.ctx.renderPage (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/.next/server/pages/_document.js:1157:30)
    at Function.getInitialProps (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/.next/server/pages/_document.js:621:19)
    at Function.getInitialProps (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/.next/server/pages/_document.js:1165:87)
    at Object.loadGetInitialProps (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/shared/lib/utils.js:69:29)
    at renderDocument (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/server/render.js:609:48)
    at Object.renderToHTML (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/server/render.js:647:34) {
  page: '/'
}
error - Error: ReactDOMServer does not yet support Suspense.
    at ReactDOMServerRenderer.render (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3844:25)
    at ReactDOMServerRenderer.read (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/server/render.js:596:45)
    at Object.ctx.renderPage (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/.next/server/pages/_document.js:1157:30)
    at Function.getInitialProps (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/.next/server/pages/_document.js:621:19)
    at Function.getInitialProps (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/.next/server/pages/_document.js:1165:87)
    at Object.loadGetInitialProps (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/shared/lib/utils.js:69:29)
    at renderDocument (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/server/render.js:609:48)
    at Object.renderToHTML (/home/sherry/VCS/working-remote/with-typescript-styled-components-app/node_modules/next/dist/server/render.js:647:34) {
  page: '/'
}
```

### To Reproduce

I took a nextjs typescript + styled-components starter example and simply added React Suspense to invoke the error:

```
$ yarn create next-app --example with-typescript-styled-components with-typescript-styled-components-app
$ cd with-typescript-styled-components-app
$ rm -rf node_modules
$ yarn set version 3.0.2
```

Edit `.yarnrc.yml` to make sure `pnp` is used:
```
# .yarnrc.yml

nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.0.2.cjs
```

Edit `pages/index.tsx` to include React Suspense to invoke error `ReactDOMServer does not yet support Suspense`:
```
// pages/index.tsx

import { Suspense } from 'react';
import styled from 'styled-components';

const Title = styled.h1`
  color: red;
  font-size: 50px;
`;

export default function Home() {
  return (
    <Suspense fallback={<h1>...Loading</h1>}>
      <Title>My page</Title>
    </Suspense>
  );
}

```

Install packages, run the server, and visit `http://localhost:3000`:
```
$ yarn install
$ yarn dev
```

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
