### ISSUE TITLE
Eslint with "next lint --fix --dir src" does not work in the latest Next 11.1.2

### ISSUE THREAD

**Issue by tiavina-mika** [vercel/next.js#29352]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

These following eslint configuration working since I upgraded Next.js to the latest v11.1.2.
The `next lint --fix --dir src` does not fix the code anymore.

### .babelrc
```

{
  "presets": [
    [
      "next/babel",
      {
        "preset-react": {
          "runtime": "automatic",
          "importSource": "@emotion/react"
        }
      }
    ]
  ],
  "plugins": ["@emotion/babel-plugin"]
}
```

### package.json
```
  "scripts": {
    "lint": "next lint --fix --dir src",
  },
  "dependencies": {
    "@ant-design/icons": "^4.6.4",
    "@emotion/css": "^11.1.3",
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "next": "^11.1.2",
  },
  "devDependencies": {
    "@emotion/babel-plugin": "^11.3.0",
    "eslint": "^7.31.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-next": "^11.1.2",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prefer-arrow": "^1.2.3",
  }
```

### eslintrc.json
```
{
  "extends": ["airbnb", "next"],
  "plugins": [
    "prefer-arrow"
  ],
  "rules": {
    "semi": [2, "always"],
    "react/jsx-one-expression-per-line": "off",
    "react/jsx-indent": [2, 2],
    "react/jsx-indent-props": [2, 2],
    "react/jsx-curly-newline": [
      "error",
      {
        "multiline": "consistent",
        "singleline": "consistent"
      }
    ],
    "quotes": [
      2,
      "single",
      { "avoidEscape": true, "allowTemplateLiterals": false }
    ],
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": true
      }
    ],
    "no-tabs": ["error", { "allowIndentationTabs": true }],
    "jsx-a11y/click-events-have-key-events": "off",
    "linebreak-style": "off",
    "no-undef": "off",
    "react/react-in-jsx-scope": "off",
    "react/jsx-props-no-spreading": "off",
    "react/require-default-props": "off",
    "react/prop-types": "off",
    "import/prefer-default-export": "off",
    "no-underscore-dangle": "off",
    "import/no-cycle": "off",
    "react/no-array-index-key": "off",
    "jsx-a11y/label-has-associated-control": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off",
    "consistent-return": "off",
    "no-plusplus": "off",
    "no-param-reassign": "off",
    "no-restricted-syntax": "off",
    "no-prototype-builtins": "off",
    "no-restricted-globals": "off",
    "@next/next/no-img-element": "off",
    "no-console": "off",
    "prefer-template": "off",
    "arrow-body-style": "off",
    "indent": "off",
    "react/forbid-prop-types": "off",
    "no-await-in-loop": "off",
    "prefer-arrow/prefer-arrow-functions": [
      "warn",
      {
        "disallowPrototype": true,
        "singleReturnOnly": true,
        "classPropertiesAllowed": false
      }
   ],
   "import/order": [
    "error",
    {
      "groups": ["builtin", "external", "internal", ["parent", "sibling"] ],
      "pathGroups": [
        {
          "pattern": "react",
          "group": "external",
          "position": "before"
        }
      ],
      "pathGroupsExcludedImportTypes": ["react"],
      "newlines-between": "always",
      "alphabetize": {
        "order": "asc",
        "caseInsensitive": true
      }
    }
  ]
  }
}

```

### Expected Behavior

    const selectPhotoData = {
      title: product.name,
      button: "Validation finale",
    };

### To Reproduce

    const selectPhotoData = {
      title: product.name,
      button: 'Validation finale',
    };

**Comment by leosuncin** [comment]
I got another error, `next lint` fails when it used with a file path

Example:
```sh
npx next lint --fix src/setupTests.ts
```

<details>
<summary>Error</summary>
<pre>
error - Failed to load env from .env.production.local Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production.local'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production.local'
}
error - Failed to load env from .env.local Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.local'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.local'
}
error - Failed to load env from .env.production Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production'
}
error - Failed to load env from .env Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env'
}
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Error: > No `pages` directory found. Did you mean to run `next` in the parent (`../`) directory?
</pre>
</details>

Repository with the error: https://github.com/leosuncin/next-vanilla-extract-example

**Comment by niteshseram** [comment]
> I got another error, `next lint` fails when it used with a file path
> 
> Example:
> 
> ```shell
> npx next lint --fix src/setupTests.ts
> ```
> 
> Error
> Repository with the error: https://github.com/leosuncin/next-vanilla-extract-example

This specific error **Error:> No `pages` directory found. Did you mean to run `next` in the parent (`../`) directory?** might be solved by running the below command I hope so.
`npx next lint --fix --dir src`
I guess the other errors are related to your setupTests.ts file and have nothing to do with running the ESLint

**Comment by leosuncin** [comment]
@niteshseram same error, the file I'm testing does not have any error, I discovered the error when I tried to use in `lint-staged`

```json
{
  "*.{js,ts,tsx}": ["next lint --fix", "prettier --write"],
  "*.{json,md,yml}": ["prettier --write"]
}
```

To avoid the error [I switched to `eslint`](https://github.com/leosuncin/next-vanilla-extract-example/commit/bc2fce803d07cf4f48dfec45c99d6661fce532ff), but still this is a bug

<details>
<summary>Error in the terminal</summary>
<pre>
error - Failed to load env from .env.production.local Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production.local'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production.local'
}
error - Failed to load env from .env.local Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.local'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.local'
}
error - Failed to load env from .env.production Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env.production'
}
error - Failed to load env from .env Error: ENOTDIR: not a directory, stat '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env'
    at Object.statSync (node:fs:1536:3)
    at Module.loadEnvConfig (/home/user/next-vanilla-extract-example/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/home/user/next-vanilla-extract-example/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/home/user/next-vanilla-extract-example/node_modules/next/dist/cli/next-lint.js:162:50)
    at /home/user/next-vanilla-extract-example/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/home/user/next-vanilla-extract-example/src/setupTests.ts/.env'
}
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Error: > No `pages` directory found. Did you mean to run `next` in the parent (`../`) directory?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</pre>
</summary>

Also, I don't use any `.env` file

**Comment by LinnJS** [comment]
Getting the same kind of issues when trying to fix my listing with NextJS and Turborepo 😢

**Comment by balazsorban44** [comment]
Has this been tested with `canary`? Could you verify if that's still an issue @tiavina-mika?

From others, I would like to ask for reproduction, so we can investigate.

**Comment by leosuncin** [comment]
It works for me

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think this was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
