### ISSUE TITLE
Error with server-side redirect with `getStaticProps`

### ISSUE THREAD

**Issue by chipit24** [vercel/next.js#29554]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

16.2.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

When performing a server-side redirect in the custom App component's (`pages/_app.js`) `getInitialProps` on a page that is SSG'ed (contains `getStaticProps`), the server crashes and throws an error.

### Expected Behavior

I expect the redirect to successfully occur and the server to not crash.

### To Reproduce

1. Run the following to set up a new Next.js project:
   ```terminal
   npx create-next-app redirect-bug
   cd redirect-bug
   ```

2. Add the following to `pages/_app.js`:
   ```js
   import App from 'next/app'

   /* ... */

   MyApp.getInitialProps = async (appContext) => {
     const appProps = await App.getInitialProps(appContext);
     const { asPath, res } = appContext.ctx;
   
     if (res && asPath === '/?redirect=yes') {
       res.writeHead(302, { Location: '?redirected=yes' });
       res.end();
     }
   
     return { ...appProps };
   }
   ```

3. Add the following to `pages/index.js`:
   ```js
   export async function getStaticProps() {
     return {
       props: {}
     };
   }
   ```

4. In your browser, visit `localhost:3000?redirect=yes`. You should see the URL update to `/?redirected=yes`, but the server crashes with the following error:
   ```terminal
   Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
       at new NodeError (node:internal/errors:363:5)
       at ServerResponse.setHeader (node:_http_outgoing:574:11)
       at DevServer.sendHTML (/[...]/redirect-bug/node_modules/next/dist/server/next-dev-server.js:37:5)
       at DevServer.render (/[...]/redirect-bug/node_modules/next/dist/next-server/server/next-server.js:76:37)
       at async Object.fn (/[...]/redirect-bug/node_modules/next/dist/next-server/server/next-server.js:58:672)
       at async Router.execute (/[...]/redirect-bug/node_modules/next/dist/next-server/server/router.js:25:67)
       at async DevServer.run (/[...]/redirect-bug/node_modules/next/dist/next-server/server/next-server.js:68:1042)
       at async DevServer.handleRequest (/[...]/redirect-bug/node_modules/next/dist/next-server/server/next-server.js:32:504) {
     code: 'ERR_HTTP_HEADERS_SENT'
   }
   node:events:342
         throw er; // Unhandled 'error' event
         ^
   
   Error [ERR_STREAM_WRITE_AFTER_END]: write after end
       at new NodeError (node:internal/errors:363:5)
       at ServerResponse.end (node:_http_outgoing:844:15)
       at ServerResponse.end (/[...]/redirect-bug/node_modules/next/dist/compiled/compression/index.js:1:141519)
       at DevServer.handleRequest (/[...]/redirect-bug/node_modules/next/dist/next-server/server/next-server.js:32:624)
   Emitted 'error' event on ServerResponse instance at:
       at emitErrorNt (node:_http_outgoing:724:9)
       at processTicksAndRejections (node:internal/process/task_queues:84:21) {
     code: 'ERR_STREAM_WRITE_AFTER_END'
   }
   ```

This prevents redirects from working on our production app. I was able to reproduce this with `next@10.2.4-canary.19` and node v14 as well.

**Comment by chipit24** [comment]
Aaaand it seems I already found my solution: https://github.com/vercel/next.js/issues/22377#issuecomment-824295138. Changing the redirect to use the following (and omitting `res.end()`) seemed to make this work:

```js
res.setHeader('Location', updatedPath);
res.statusCode = 302;
```

Omitting `res.end` wasn't enough. It seems I have to set the status and header separately like above as well.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
