### ISSUE TITLE
TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined

### ISSUE THREAD

**Issue by vinamelody** [vercel/next.js#30028]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

 v14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

vercel

### Describe the Bug

Getting these errors when `yarn build` 
When seeing previous issues #16107 , my href has set url from the beginning, for example: `<Link href="/our-programs">Programs</Link>`

Error occurred prerendering page "/our-programs". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'auth' of 'urlObj' as it is undefined.
    at Object.formatUrl (/Users/.../github.com/techladies/website/node_modules/next/dist/shared/lib/router/utils/format-url.js:32:11)
at Object.formatWithValidation (/Users/.../github.com/techladies/website/node_modules/next/dist/shared/lib/utils.js:109:28)
at Object.resolveHref (/Users/.../github.com/techladies/website/.next/server/chunks/664.js:875:67)
at /Users/.../github.com/techladies/website/.next/server/chunks/664.js:89:53
at Object.Ja [as useMemo] (/Users/.../github.com/techladies/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:27:240)
at Object.exports.useMemo (/Users/.../github.com/techladies/website/node_modules/react/cjs/react.production.min.js:23:113)
at Link (/Users/.../github.com/techladies/website/.next/server/chunks/664.js:88:22)
at d (/Users/.../github.com/techladies/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
at bb (/Users/.../github.com/techladies/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
at a.b.render (/Users/.../github.com/techladies/website/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)

### Expected Behavior

The build should be successful

### To Reproduce

Checkout my branch https://github.com/TechLadies/website/tree/upgrade-next
`yarn install`
`yarn build`

If you can see the build log https://vercel.com/techladiessg/techladies-website/HzAvmQqCkcpZpsLWffTiLMmjGiyF
![Screenshot 2021-10-18 at 6 29 54 PM](https://user-images.githubusercontent.com/990511/137714554-c081527d-4721-40a6-b732-970e27d7dbfd.png)

**Comment by balazsorban44** [comment]
https://github.com/TechLadies/website/blob/6b58609cf5b908c2b6fabcac5070c06441f971ff/src/pages/index.js#L151

https://github.com/TechLadies/website/blob/6b58609cf5b908c2b6fabcac5070c06441f971ff/src/components/Footer/index.js#L54

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
