### ISSUE TITLE
fastify.next is not a function

### ISSUE THREAD

**Issue by sbfkcel** [vercel/next.js#30098]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

v14.18.1

### What browser are you using?

chrome

### What operating system are you using?

Linux（Docker：Alpine v3.14）

### How are you deploying your application?

next dev

### Describe the Bug

file:///www/web/server/server.js:52
        fastify.next(`/${item.routerPath}`);
                ^

TypeError: fastify.next is not a function
    at file:///www/web/server/server.js:52:17
    at Object._encapsulateThreeParam (/www/web/node_modules/avvio/boot.js:533:13)
    at Boot.timeoutCall (/www/web/node_modules/avvio/boot.js:447:5)
    at Boot.callWithCbOrNextTick (/www/web/node_modules/avvio/boot.js:428:19)
    at Boot._after (/www/web/node_modules/avvio/boot.js:273:26)
    at Plugin.exec (/www/web/node_modules/avvio/plugin.js:132:19)
    at Boot.loadPlugin (/www/web/node_modules/avvio/plugin.js:267:10)
    at Task.release (/www/web/node_modules/fastq/queue.js:149:16)
    at worked (/www/web/node_modules/fastq/queue.js:201:10)
    at /www/web/node_modules/avvio/plugin.js:270:7

### Expected Behavior

Start the service normally

### To Reproduce

```json
dependencies": {
    "fastify": "3.22.0",
    "fastify-nextjs": "^6.0.0",
    "fastify-static": "^4.4.2",
    "next": "11.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
```

```js
fastify.register(fastifyNextjs,{dev:true}).after(()=>{
    fastify.next(`/hello`);
});
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
