### ISSUE TITLE
Can't build with imagemin-svgo 

### ISSUE THREAD

**Issue by olegKusov** [vercel/next.js#30307]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.18.1

### What browser are you using?

safari

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

If imagemin-svgo installed with yarn add then when start building with next build it throws error

```> Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/olegkusov/projects/landing/node_modules/imagemin-svgo/index.js
require() of ES modules is not supported.
require() of /Users/olegkusov/projects/landing/node_modules/imagemin-svgo/index.js from /Users/olegkusov/projects/landing/node_modules/next-optimized-images/lib/loaders/img-loader.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/olegkusov/projects/landing/node_modules/imagemin-svgo/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at requireImageminPlugin (/Users/olegkusov/projects/landing/node_modules/next-optimized-images/lib/loaders/img-loader.js:21:10)
    at getImgLoaderOptions (/Users/olegkusov/projects/landing/node_modules/next-optimized-images/lib/loaders/img-loader.js:50:11)
    at applyImgLoader (/Users/olegkusov/projects/landing/node_modules/next-optimized-images/lib/loaders/img-loader.js:96:28)
    at appendLoaders (/Users/olegkusov/projects/landing/node_modules/next-optimized-images/lib/loaders/index.js:137:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Expected Behavior

No error

### To Reproduce

Install imagemin-svgo

**Comment by timneutkens** [comment]
`esmExternals` is enabled by default in Next.js 12 @kevva 🎉

**Comment by JBaczuk** [comment]
I'm on next 12 and the issue persists. The only way I was able to get it to work was by renaming the `index.js` file in `imagemin-svgo` to `index.cjs`.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
