### ISSUE TITLE
getStaticProps with revalidate silently swallowing errors

### ISSUE THREAD

**Issue by mirkonasato** [vercel/next.js#30375]
### What version of Next.js are you using?

12.0.0

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Starting with Next.js 11.1.0, any uncaught errors thrown by `getStaticProps` while running with `next start` are silently swallowed and not logged to the server output.

### Expected Behavior

Up to Next.js 11.0.1, the same errors were logged to the server output. I don't see anything in the 11.1.0 release notes about this changing, and swallowing errors is generally not a good idea.

### To Reproduce

Create a new project with `create-next-app`, put this in `pages/index.js`

```js
export async function getStaticProps() {
  if (process.env.SIMULATE_ERROR) {
    console.log('[getStaticProps] throwing an error')
    throw new Error('Oops')
  }
  return {
    props: { title: 'Test Page' },
    revalidate: 5,
  }
}

export default function Home({ title }) {
  return (
    <div>{title}</div>
  )
}
```

Build with `npm run build`, start with `SIMULATE_ERROR=true npm start`, open the home page, wait 5 seconds and reload.

With Next.js 11.0.1 this logs the following

```
[getStaticProps] throwing an error
Error: Oops
    at getStaticProps (/Users/mirko/Projects/Next/new-app/.next/server/pages/index.js:22:11)
    at renderToHTML (/Users/mirko/Projects/Next/new-app/node_modules/next/dist/next-server/server/render.js:27:1786)
    ...
```

With Next.js 11.1.0 it just logs

```
[getStaticProps] throwing an error
```

but the uncaught error thrown by `getStaticProps` is nowhere to be seen.

**Comment by bencmbrook** [comment]
I'm getting the same issue, and furthermore, my dev server just hangs. The only indication of an error is "compiling /_error" but that error page does not render. So, continuing with your example:

```
[getStaticProps] throwing an error
wait  - compiling /_error...
event - compiled successfully in 70 ms (245 modules)
```

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.8-canary.18` of Next.js, please update and give it a try!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
