### ISSUE TITLE
Unable to successfully run a test for a component that uses next.js <Link/> component

### ISSUE THREAD

**Issue by sethreidnz** [vercel/next.js#30411]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

v16.5.0

### What browser are you using?

Chrome

### What operating system are you using?

Mac

### How are you deploying your application?

This is just an example with minumal reproduction

### Describe the Bug

When I create a brand new next.js application project and then follow the [testing](https://nextjs.org/docs/testing) intructions I am able to get tests running. However if I write a component uses the `next/link` component such as:

```ts
import Link from "next/link";

type ArticleListProps = {
  articles: Article[];
};

type Article = {
  filePath: string;
  metadata: {
    title: string;
  };
};

export const ArticleList = ({ articles }: ArticleListProps) => (
  <>
    {articles.length > 0 ? (
      <ul className="py-4">
        {articles.map((article: Article) => (
          <li key={article.filePath} className="pb-8">
            <article>
              <Link href={article.metadata.title}>
                <a>{article.metadata.title}</a>
              </Link>
            </article>
          </li>
        ))}
      </ul>
    ) : (
      <>Sorry there are no articles matching your query</>
    )}
  </>
);
```

With a test like:

```ts
import { render, screen } from "@testing-library/react";
import { ArticleList } from "./ArticleList";
describe("<ArticleList/>", () => {
  it("should render no articles correctly", () => {
    render(<ArticleList articles={[]} />);
    screen.findByText("Sorry there are no articles matching your query");
  });

  it("should display a list of articles", () => {
    const articles = [
      {
        filePath: "string",
        metadata: {
          title: "string",
        },
      },
    ];
    render(<ArticleList articles={articles} />);

    // get each article list item
    const articleList = screen.getByRole("list");
    expect(articleList).toBeInTheDocument();
  });
});

```

I get the error:

```
/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom.development.js:3905
      var evt = document.createEvent('Event');
                         ^

TypeError: Cannot read property 'createEvent' of null
    at Object.invokeGuardedCallbackDev (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom.development.js:3905:26)
    at invokeGuardedCallback (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom.development.js:23543:11)
    at unstable_runWithPriority (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at Object.<anonymous>.flushWork (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
    at Immediate.<anonymous> (/Users/seth.reid/dev/nextjs/next-link-jest-issue/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1003:11)
    at processImmediate (node:internal/timers:464:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But if remove the `Link` from the component and make it like this:

```ts
type ArticleListProps = {
  articles: Article[];
};

type Article = {
  filePath: string;
  metadata: {
    title: string;
  };
};

export const ArticleList = ({ articles }: ArticleListProps) => (
  <>
    {articles.length > 0 ? (
      <ul className="py-4">
        {articles.map((article: Article) => (
          <li key={article.filePath} className="pb-8">
            <article>
              <a>{article.metadata.title}</a>
            </article>
          </li>
        ))}
      </ul>
    ) : (
      <>Sorry there are no articles matching your query</>
    )}
  </>
);

```

It passes

### Expected Behavior

I would expect that I can write components with a Link and they won't make my tests fail and throw errors that are very hard to understand or google.

### To Reproduce

Got to this repository and run:

https://github.com/sethreidnz/next-link-jest-test-issue

```
yarn test
```

**Comment by sethreidnz** [comment]
I am not sure why but this issue seems to have resolved itself. Perhaps there was an update in next.js that solved it because I did update recently when I came back to this. But I'm going to close it for now since I am no longer having the issue with latest.
