### ISSUE TITLE
Various crashes after upgrading to 12.0.1: RangeError, the request of a dependency is an expression, peer_dep_not_installed

### ISSUE THREAD

**Issue by verekia** [vercel/next.js#30423]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

16.5.0

### What browser are you using?

Brave

### What operating system are you using?

macOS 11.2.3 (20D91) - M1

### How are you deploying your application?

next dev, next build, next start

## Context

I upgraded from `11.1.2` to `12.0.1`.
It automatically added `"incremental": true` to my tsconfig.json file.
In my project, Next defaults to Webpack because I have a custom `.babelrc` file (containing only `"presets": ["next/babel"]`).

I do not have any of those problems with `11.1.2`.
I tried to reproduce the bugs on a Hello World project with `12.0.1` and wasn't able to reproduce.

## next dev

```
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
    at AsyncHook.init (node:domain:75:15)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at Promise.then (<anonymous>)
    at Object.obj.<computed> (/Users/verekia/Local/Code/revisit/.next/server/webpack-runtime.js:70:93)
    at /Users/verekia/Local/Code/revisit/.next/server/webpack-runtime.js:91:52
    at Array.map (<anonymous>)
    at whenAll (/Users/verekia/Local/Code/revisit/.next/server/webpack-runtime.js:91:19)
    at Promise.promise.<computed> (/Users/verekia/Local/Code/revisit/.next/server/webpack-runtime.js:101:31)
    at /Users/verekia/Local/Code/revisit/.next/server/webpack-runtime.js:91:52
```

## next build

The build phase (`Creating an optimized production build`) is noticeably slower than on `11.1.2` (takes maybe 2 times longer) and it makes my terminal choppy with small freezes when the "..." cycle through. This animation is usually smooth.

```
info  - Creating an optimized production build  
warn  - Compiled with warnings

vvvvvvv Never had this before vvvvvvvv

./node_modules/nexus-prisma/dist-esm/generator/models/javascript.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/nexus-prisma/dist-esm/generator/models/index.js
./node_modules/nexus-prisma/dist-esm/runtime/index.js
./node_modules/nexus-prisma/dist-esm/entrypoints/main.js
./src/api/topics.ts
./src/api/index.ts
./src/api/schema.ts
./src/pages/api/graphql.ts

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

info  - Collecting page data  
info  - Generating static pages (13/13)
info  - Finalizing page optimization  
```

## next start

I get a runtime server crash:

```
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/verekia/Local/Code/revisit/.env.local
info  - Loaded env from /Users/verekia/Local/Code/revisit/.env
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
ERROR: Peer dependency validation check failed.

REASON: @prisma/client is a peer dependency required by nexus-prisma. But you have not installed it into this project yet.

CONSEQUENCE: Your project may not work correctly.

SOLUTION: Please run `yarn add @prisma/client`.

HOW TO DISABLE: 

You can disable this peer dependency check by setting one of two environment variables. Their specs are:

  NO_PEER_DEPENDENCY_CHECK = 'true' | '1'
  PEER_DEPENDENCY_CHECK    = 'false' | '0'

Examples:

  NO_PEER_DEPENDENCY_CHECK='true'
  NO_PEER_DEPENDENCY_CHECK='1'
  PEER_DEPENDENCY_CHECK='false'
  PEER_DEPENDENCY_CHECK='0'

CODE: peer_dep_not_installed
error Command failed with exit code 1.
```

Note that I **do** have `@prisma/client` installed.

### Expected Behavior

Not crashing.

### To Reproduce

I tried to reproduce the bugs on a Hello World project with `12.0.1` and wasn't able to reproduce. There is something about my project that made it work fine in `11.1.2` but not in version 12.

**Comment by timneutkens** [comment]
Could you provide more information like the `next.config.js`, but ideally a full reproduction as we're not able to investigate based on the information provided.

**Comment by verekia** [comment]
My `next.config.js` is:
```js
const { withSentryConfig } = require('@sentry/nextjs')
const withPWA = require('next-pwa')
const runtimeCaching = require('next-pwa/cache')

const SentryWebpackPluginOptions = { silent: true }

const withSentryIfEnabled =
  process.env.SENTRY_AUTH_TOKEN && process.env.NEXT_PUBLIC_SENTRY_DSN ? withSentryConfig : x => x

module.exports = withSentryIfEnabled(
  withPWA({
    pwa: { dest: 'public', runtimeCaching, disable: process.env.NODE_ENV === 'development' },
  }),
  SentryWebpackPluginOptions
)
```
Judging by the thumbs up it seems like a few other people had similar issues. I will try to provide a reproduction by stripping down my project, but might take a week or two to find the time for it. In the meantime if anyone else is able to reproduce the bug on a smaller project, please do share :)

**Comment by timneutkens** [comment]
In order to investigate this further we'd definitely need to have a reproduction, I'd start by removing the next.config.js as a starting point 🤔

**Comment by verekia** [comment]
With Next `12.0.4` the problems seem resolved. If they happen again I'll make a reproduction. Thank you!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
