### ISSUE TITLE
MDX v2 fails with Next.js v12

### ISSUE THREAD

**Issue by michaeloliverx** [vercel/next.js#30436]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I am not sure if this is a Next.js or mdx issue. The current Next.js example found on the v2 mdx docs at https://v2.mdxjs.com/docs/getting-started/#nextjs doesn't work for Next.js v12. I can confirm it **does** work for v11.

I get errors:

Console:

```
info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled successfully in 3.7s (172 modules)
wait  - compiling /...
event - compiled successfully in 400 ms (190 modules)
wait  - compiling /_error...
event - compiled successfully in 117 ms (191 modules)
wait  - compiling /test...
thread '<unnamed>' panicked at 'not yet implemented: proper error reporting for wrong `@jsxRuntime`', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_react-0.55.0/src/jsx/mod.rs:289:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'not yet implemented: proper error reporting for wrong `@jsxRuntime`', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_react-0.55.0/src/jsx/mod.rs:289:25
error - ./pages/test.mdx
Error: failed to process not yet implemented: proper error reporting for wrong `@jsxRuntime`
(node:26740) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Broswer:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/55017335/139054245-623134b3-4c7f-4f00-bb32-c9a8de951b1c.png">

I assume this is because of the [new Rust compiler](https://nextjs.org/blog/next-12#faster-builds-and-fast-refresh-with-rust-compiler).

### Expected Behavior

Page should load successfully.

### To Reproduce

I created a repo to reproduce it. https://github.com/michaeloliverx/mdx-v2-nextjs-v12-bug

These are the steps I followed

1. Create a fresh next.js project with `npx create-next-app@latest --typescript`
2. Run `npm add @mdx-js/loader@2.0.0-rc.1`
3. Add the r[equired config](https://v2.mdxjs.com/docs/getting-started/#nextjs) to `next.config.js`
4. Create an `test.mdx` file underneath `/pages`
5. Start the dev server
6. Navigate to `/test`
7. View error in console

### References
I have also opened this issue in the mdx repo: https://github.com/mdx-js/mdx/issues/1783

**Comment by michaeloliverx** [comment]
Confirming that this is now working in [v12.0.2](https://github.com/vercel/next.js/releases/tag/v12.0.2), closing issue!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
