### ISSUE TITLE
"getStaticPaths is only allowed for dynamic SSG pages" when concurrentFeatures=true

### ISSUE THREAD

**Issue by mmiszy** [vercel/next.js#30520]
### What version of Next.js are you using?

12.0.2-canary.2

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Safari 15.1 (17612.2.9.1.20)

### What operating system are you using?

macOS 12.0.1 (21A559)

### How are you deploying your application?

next dev

### Describe the Bug

After setting `config.concurrentFeatures = true` the app won't run and instead an error is thrown:

```
[www] ready - started server on 0.0.0.0:3000, url: http://localhost:3000
[www] info  - Loaded env from /Users/typeofweb/htdocs/@typeofweb/polskifrontend/.env
[www] warn  - You have enabled experimental feature(s).
[www] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
[www] 
[www] warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[www] info  - Using the experimental web runtime.
[www] info  - Using the createRoot API for React
[www] warn  - You are using an unsupported prerelease of 'react-dom' which may cause unexpected or broken application behavior. Continue at your own risk.
[www] wait  - compiling...
[www] event - compiled successfully in 2.8s (977 modules)
[www] warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
[www] wait  - compiling /[displayStyle]...
[www] wait  - compiling...
[www] event - compiled successfully in 2.2s (2578 modules)
[www] error - unhandledRejection: Error: getStaticPaths is only allowed for dynamic SSG pages and was found on '/grid'.
[www] Read more: https://nextjs.org/docs/messages/non-dynamic-getstaticpaths-usage
```

This error is gone after setting `config.concurrentFeatures = false`. The page I'm trying to open is dynamic.

### Expected Behavior

It works.

### To Reproduce

1. Clone https://github.com/typeofweb/polskifrontend/tree/next-12
2. Follow `CONTRIBUTING.md` to start the app
3. See that it's not working
4. Edit `next.config.js` and set `concurrentFeatures: false`, and restart
5. Now it works.

**Comment by bennettdams** [comment]
This is easily reproducable with a fresh Next.js app, even for Next.js `v12.0.8`:

1. Create Next.js app `npx create-next-app@latest --use-npm --ts`
2. Install React 18 deps `npm install next@latest react@rc react-dom@rc`
3. Add `getStaticPaths` to `index.tsx`

    ```ts
    import type { GetStaticPaths, NextPage } from 'next'
    ...
    export const getStaticPaths: GetStaticPaths = async () => {
      return {
        paths: [],
        fallback: "blocking",
      };
    };
    ```
4. Run the app `npm run dev`

Result:

![image](https://user-images.githubusercontent.com/29319414/149203250-f7f0cf23-6bb9-444b-ae95-ea3780d55eb8.png)

<details>
  <summary>Click to expand for text</summary>
  
```
event - compiled client and server successfully in 170 ms (248 modules)
An error occurred while rendering the initial result: Error: getStaticPaths is only allowed for dynamic SSG pages and was found on '/'.
Read more: https://nextjs.org/docs/messages/non-dynamic-getstaticpaths-usage
    at Object.renderToHTML (webpack://_N_E/./node_modules/next/dist/server/render.js?:276:15)
    at Object.render [as handler] (webpack://_N_E/./node_modules/next/dist/build/webpack/loaders/next-middleware-ssr-loader/render.js?:78:41)
    at adapter (webpack://_N_E/./node_modules/next/dist/server/web/adapter.js?:29:35)
    at Module.rscMiddleware (webpack://_N_E/?./node_modules/next/dist/build/webpack/loaders/next-middleware-ssr-loader/index.js?page=%252F&absoluteAppPath=private-next-pages%252F_app&absoluteDocumentPath=private-next-pages%252F_document&absoluteErrorPath=private-next-pages%252F_error&absolute404Path=&absolutePagePath=%252Fhome%252Fbennett%252Fcode%252Fcon%252Fmy-app%252Fpages%252Findex.tsx&isServerComponent=false&buildId=development&basePath=&assetPrefix=&generateEtags=true&poweredByHeader=true&canonicalBase=&i18n=&previewProps=:43:83)
    at Object.run (/home/bennett/code/con/my-app/node_modules/next/dist/server/web/sandbox/sandbox.js:28:65)
    at DevServer.runMiddleware (/home/bennett/code/con/my-app/node_modules/next/dist/server/base-server.js:445:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.runMiddleware (/home/bennett/code/con/my-app/node_modules/next/dist/server/dev/next-dev-server.js:399:28)
    at async Object.fn (/home/bennett/code/con/my-app/node_modules/next/dist/server/base-server.js:829:34)
    at async Router.execute (/home/bennett/code/con/my-app/node_modules/next/dist/server/router.js:222:32)
```
</details>



I know it's experimental, but this is blocking every app that is using `getStaticPaths` from working/testing out concurrent features.

**Comment by vanpham981986** [comment]
NarutoslugfestX

**Comment by balazsorban44** [comment]
This is intended behavior since `getStaticPaths` is not planned to be supported in the edge runtime. However, we are working on a per-page runtime configuration to handle these cases in the future.
