### ISSUE TITLE
Data URIs in CSS not working when enabling URL imports

### ISSUE THREAD

**Issue by marcbouchenoire** [vercel/next.js#30522]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

16.12.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

After enabling `experimental.urlImports` in `next.config.js`, Webpack throws an error when encountering Data URIs in CSS files.

```
[webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item
'Compilation/modules|asset/resource|data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='6' height='4'><path d='M 0.5 0.5 L 3 3.5 L 5.5 0.5 Z' stroke='hsl(0, 0%, 0%)' strokeLinecap='round' strokeLinejoin='round' /></svg>'
No serializer registered for URIError while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> URIError
```
```
data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='6' height='4'><path d='M 0.5 0.5 L 3 3.5 L 5.5 0.5 Z' stroke='hsl(0, 0%, 0%)' strokeLinecap='round' strokeLinejoin='round' /></svg>
Module build failed: URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at decodeDataURI (/Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:109894:17)
    at /Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:109920:40
    at /Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:52534:10
    at Hook.eval [as callAsync] (eval at create (/Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:140927:10), <anonymous>:9:16)
    at Object.processResource (/Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:53128:8)
    at processResource (/Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:138339:11)
    at iteratePitchingLoaders (/Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:138290:10)
    at runLoaders (/Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:138516:2)
    at NormalModule._doBuild (/Users/marc/Developer/framer/site/node_modules/next/dist/compiled/webpack/bundle5.js:53118:3)
```

### Expected Behavior

Data URIs are ignored by Webpack.

### To Reproduce

- Enable `experimental.urlImports`
- Import a CSS module with a Data URI in it

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.

**Comment by TomasHubelbauer** [comment]
@balazsorban44 I can still reproduce this even when using `next@canary`. Unfortunately this is within a proprietary codebase and it is hard to extract the configuration out to a reproduction I could share. @marcbouchenoire were you running into this in a project which could be shared for a repro?

**Comment by TomasHubelbauer** [comment]
@balazsorban44 could you reopen #30895? It is the same exact issue AFAICS. Still reproduces on `13.1.2-canary.4`.

**Comment by JanKaifer** [comment]
Hey, thanks for checking. We can't do much without reproduction.
Could you try creating a minimal reproduction to make sure it's not caused by issues in your project setup?

**Comment by JanKaifer** [comment]
Please open a new issue if you manage to reproduce it.
