### ISSUE TITLE
Cannot find module 'redux' (Deploy on Vercel w/ yarn workspace)

### ISSUE THREAD

**Issue by crossjs** [vercel/next.js#30561]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Error on Vercel:

```
2021-10-28T15:40:49.826Z	94588f63-d2d6-4c45-9656-4763b8884447	ERROR	Error: Cannot find module 'redux'
Require stack:
- /var/task/applications/studio/.next/server/pages/_app.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/load-components.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/applications/studio/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.6695 (/var/task/applications/studio/.next/server/pages/_app.js:517:18)
    at __webpack_require__ (/var/task/applications/studio/.next/server/webpack-runtime.js:25:42)
    at Object.3803 (/var/task/applications/studio/.next/server/chunks/803.js:30:23)
    at __webpack_require__ (/var/task/applications/studio/.next/server/webpack-runtime.js:25:42)
    at Object.3161 (/var/task/applications/studio/.next/server/pages/_app.js:71:13)
    at __webpack_require__ (/var/task/applications/studio/.next/server/webpack-runtime.js:25:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/applications/studio/.next/server/pages/_app.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/load-components.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/applications/studio/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
```

But it is working on local machine.

Then I try to move app to root, the Error is still:

```
2021-10-28T16:35:44.673Z	da6367a9-da39-40f5-93d9-5bd8af5714e1	ERROR	Error: Cannot find module 'redux'
Require stack:
- /var/task/.next/server/pages/_app.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/load-components.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.6695 (/var/task/.next/server/pages/_app.js:517:18)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at Object.6011 (/var/task/.next/server/chunks/11.js:30:23)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at Object.5165 (/var/task/.next/server/pages/_app.js:71:13)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/.next/server/pages/_app.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/load-components.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
```

### Expected Behavior

Should NOT output `Error: Cannot find module 'redux'`

### To Reproduce

Deploy https://github.com/crossjs/cofe/tree/main on Vercel

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.2-canary.10` of Next.js, please update and remove `outputFileTracing: false` from your `next.config.js`!

**Comment by kevva** [comment]
@ijjk , I'm still seeing the error mentioned in https://github.com/getsentry/sentry-javascript/issues/4090 with `outputFileTracing` enabled.

**Comment by ijjk** [comment]
@kevva that isn't expected to work currently as they are attempting to import all of `next` which will slow down builds and increase deployment sizes drastically (related import [here](https://github.com/getsentry/sentry-javascript/blob/115b0f3c07efa755c8f90d32cfd1783a35451eba/packages/nextjs/src/utils/instrumentServer.ts#L13)) also note the plugin is hacking around internal methods not guaranteed by semver so could break at any Next.js version change.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
