### ISSUE TITLE
Next v12 inline svg css background build failure

### ISSUE THREAD

**Issue by GrossDesignCo** [vercel/next.js#30633]
### What version of Next.js are you using?

12.0.1, 12.0.2-canary.8

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

After upgrading to v12 we started seeing the following build error:
```
info  - Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[1]!/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[2]!/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/src/styles/globals.css': No serializer registered for URIError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> URIError
info  - Creating an optimized production build  
Failed to compile.

./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[2]!./src/styles/globals.css
URIError: URI malformed
    at /Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/src/styles/globals.css:7:3
    at decodeURIComponent (<anonymous>)
    at Object.normalizeUrl (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/utils.js:43:12)
    at /Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:101:31
    at walk (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:5010)
    at ValueParser.walk (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:326)
    at parseDeclaration (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:85:12)
    at Declaration (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:206:39)
    at LazyResult.visitTick (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:456:16)
    at LazyResult.runAsync (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:372:30)
    at LazyResult.async (/Users/magross/Documents/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:205:30)

Import trace for requested module:
./src/styles/globals.css
./src/pages/_app.js
```

In our stylesheet we have some svg backgrounds defined as custom properties like so:

CSS:
```
/* src/styles/globals.css */
:root {
  --bg-minus: url("data:image/svg+xml,<svg viewBox='0 0 16 16' xmlns='http://www.w3.org/2000/svg'><path fill='hsl(218, 7%, 24%)' d='M13 8a.75.75 0 0 1-.75.75h-8.5a.75.75 0 0 1 0-1.5h8.5A.75.75 0 0 1 13 8z' /></svg>");
}
```

Import:
```
// src/pages/_app.js
import '../styles/globals.css';

function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}

export default App;
```

### Expected Behavior

Should build happily like it did in v11

### To Reproduce

I was able to reproduce this by adding a `background: url(...)` rule with an svg in it to any css file in our project.

These url patterns trigger the failure:
```
// Plain svg
background: url("data:image/svg+xml,<svg viewBox='0 0 16 16' xmlns='http://www.w3.org/2000/svg'><path fill='hsl(218, 7%, 24%)' d='M13 8a.75.75 0 0 1-.75.75h-8.5a.75.75 0 0 1 0-1.5h8.5A.75.75 0 0 1 13 8z' /></svg>");

// Escaped svg
background: url("data:image/svg+xml,&lt;svg viewBox='0 0 16 16' xmlns='http://www.w3.org/2000/svg'&gt;&lt;path fill='hsl(218, 7%, 24%)' d='M13 8a.75.75 0 0 1-.75.75h-8.5a.75.75 0 0 1 0-1.5h8.5A.75.75 0 0 1 13 8z' /&gt;&lt;/svg&gt;");
```

These do not:
```
// Generic image
background: url("https://systemuicons.com/images/icons/write.svg");

// Base64 encoded image
background: url("data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjIxIiB2aWV3Qm94PSIwIDAgMjEgMjEiIHdpZHRoPSIyMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDMgMykiPjxwYXRoIGQ9Im0xNCAxYy44Mjg0MjcxLjgyODQyNzEyLjgyODQyNzEgMi4xNzE1NzI4OCAwIDNsLTkuNSA5LjUtNCAxIDEtMy45NDM2NTA4IDkuNTAzODM3MS05LjU1MjUyMTkzYy43ODI5ODk2LS43ODcwMDA2NCAyLjAzMTIzMTMtLjgyOTQzOTY0IDIuODY0MzY2LS4xMjUwNjc4OHoiLz48cGF0aCBkPSJtNi41IDE0LjVoOCIvPjxwYXRoIGQ9Im0xMi41IDMuNSAxIDEiLz48L2c+PC9zdmc+");
```

**Comment by georapbox** [comment]
I had the same issue using version `12.0.3` but it seems to be working for me using version `12.0.4-canary.4`.
https://www.npmjs.com/package/next/v/12.0.4-canary.4

**Comment by timneutkens** [comment]
This was fixed on next@canary indeed 👍

**Comment by GrossDesignCo** [comment]
I just tried running
```bash
npm i next@12.0.4-canary.4
npm run build
```

and then
```bash
npm i next@canary # resolved to canary.13
npm run build
```

And got the same error. We've worked around this by including `postcss-encode-background-svgs` in our postcss config.

Here's the full error output for thoroughness:
```bash
% npm i && npm run build

> scaffold-javascript-website--nextjs@0.1.0 prepare /Users/magross/Repos/js/scaffold-javascript-website--nextjs
> next build

warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
info  - Checking validity of types  

./src/components/example-widget.jsx
30:11  Warning: Do not use the HTML <a> tag to navigate to /api/health-check/. Use Link from 'next/link' instead. See: https://nextjs.org/docs/messages/no-html-link-for-pages.  @next/next/no-html-link-for-pages

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Creating an optimized production build ..<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/@tesla/design-system/dist/index.css': No serializer registered for URIError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> URIError
info  - Creating an optimized production build  
Failed to compile.

./node_modules/@tesla/design-system/dist/index.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./node_modules/@tesla/design-system/dist/index.css
URIError: URI malformed
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/@tesla/design-system/dist/index.css:576:3
    at decodeURIComponent (<anonymous>)
    at Object.normalizeUrl (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/utils.js:43:12)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:101:31
    at walk (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:5010)
    at ValueParser.walk (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:326)
    at parseDeclaration (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:85:12)
    at Declaration (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:206:39)
    at LazyResult.visitTick (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:456:16)
    at LazyResult.runAsync (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:372:30)
    at LazyResult.async (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:205:30)

Import trace for requested module:
./node_modules/@tesla/design-system/dist/index.css
./src/pages/_app.js

./node_modules/@tesla/design-system/dist/index.css
URIError: URI malformed
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/@tesla/design-system/dist/index.css:576:3
    at decodeURIComponent (<anonymous>)
    at Object.normalizeUrl (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/utils.js:43:12)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:101:31
    at walk (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:5010)
    at ValueParser.walk (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:326)
    at parseDeclaration (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:85:12)
    at Declaration (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:206:39)
    at LazyResult.visitTick (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:456:16)
    at LazyResult.runAsync (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:372:30)
    at LazyResult.async (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:205:30)
    at tryRunOrWebpackError (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:47160:9)
    at __webpack_require_module__ (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32965:12)
    at __nested_webpack_require_150834__ (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32922:18)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32993:20
    at symbolIterator (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/neo-async/async.js:1:14452)
    at done (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/neo-async/async.js:1:14832)
    at Hook.eval [as callAsync] (eval at create (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:141170:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:140972:14)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32900:43
    at symbolIterator (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/neo-async/async.js:1:14410)
-- inner error --
URIError: URI malformed
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/@tesla/design-system/dist/index.css:576:3
    at decodeURIComponent (<anonymous>)
    at Object.normalizeUrl (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/utils.js:43:12)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:101:31
    at walk (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:5010)
    at ValueParser.walk (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/postcss-value-parser/index.js:1:326)
    at parseDeclaration (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:85:12)
    at Declaration (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/plugins/postcss-url-parser.js:206:39)
    at LazyResult.visitTick (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:456:16)
    at LazyResult.runAsync (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:372:30)
    at LazyResult.async (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/node_modules/postcss/lib/lazy-result.js:205:30)
    at Object.<anonymous> (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/@tesla/design-system/dist/index.css:1:7)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:91625:11
    at Hook.eval [as call] (eval at create (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:141156:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:140968:14)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32967:39
    at tryRunOrWebpackError (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:47155:7)
    at __webpack_require_module__ (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32965:12)
    at __nested_webpack_require_150834__ (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32922:18)
    at /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/webpack/bundle5.js:32993:20
    at symbolIterator (/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/compiled/neo-async/async.js:1:14452)

Generated code for /Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!/Users/magross/Repos/js/scaffold-javascript-website--nextjs/node_modules/@tesla/design-system/dist/index.css

Import trace for requested module:
./src/pages/_app.js


> Build failed because of webpack errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scaffold-javascript-website--nextjs@0.1.0 prepare: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scaffold-javascript-website--nextjs@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/magross/.npm/_logs/2021-11-15T18_08_52_572Z-debug.log
```

**Comment by naazim** [comment]
Keeping the old `.babelrc` file worked for me, after next@12 upgrade:
```
{
  "presets": ["next/babel"],
  "plugins": [
    "inline-react-svg",
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "@svgs": "./svgs"
        }
      }
    ]
  ]
}
```

**Comment by jake-tourtech** [comment]
I'm still experiencing this error on next v12.0.8 using the examples provided by @GrossDesignCo 

Using this in my `globals.scss` file

```scss
.test {
    background: url("data:image/svg+xml,<svg viewBox='0 0 16 16' xmlns='http://www.w3.org/2000/svg'><path fill='hsl(218, 7%, 24%)' d='M13 8a.75.75 0 0 1-.75.75h-8.5a.75.75 0 0 1 0-1.5h8.5A.75.75 0 0 1 13 8z' /></svg>");
}
```

```
$ npm run fe:dev

> sitestat-fe@0.1.0 fe:dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/tourtech/GitLab/sitestat/sitestat-v3/frontend/.env.local
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[9].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[2].oneOf[9].use[4]!./styles/globals.scss
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/home/tourtech/GitLab/sitestat/sitestat-v3/frontend/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[1]!/home/tourtech/GitLab/sitestat/sitestat-v3/frontend/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[9].use[2]!/home/tourtech/GitLab/sitestat/sitestat-v3/frontend/node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[9].use[3]!/home/tourtech/GitLab/sitestat/sitestat-v3/frontend/node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[2].oneOf[9].use[4]!/home/tourtech/GitLab/sitestat/sitestat-v3/frontend/styles/globals.scss': No serializer registered for URIError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> URIError
```

**Comment by OZZlE** [comment]
I have 12.0.7 no customized .babelrc (I have pretty much standard installation) and still get this problem, why was this issue closed when it doesn't work?

**Comment by OZZlE** [comment]
I noticed one potential issue my svg had a css class `<svg class="x">` which made this error be thrown, if the svg string is being read as a jsx/react object then you'd have to use `className`, I didn't need classes here so I just removed it and the error went away - I also changed `fill-rule` to `fillRule` like I would do if the svg was included directly in the component.

Even with the errors gone I couldn't get it to render anything in the browser - sometimes svgs are tricky though, but I believe that these shouldn't be read as React objects at all and these kind of strings should be just left as string
