### ISSUE TITLE
Named import of constant from aliased module fails next build with "TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by gthb** [vercel/next.js#30734]
### What version of Next.js are you using?

12.0.2 (and tried 12.0.3-canary.5 too, it fails the same way)

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Firefox (but not relevant)

### What operating system are you using?

macOS

### How are you deploying your application?

Not yet deployed

### Describe the Bug

Importing a constant object like this:

```javascript
export const FOO  = {
  bar: {
    title: 'baz',
    body: 'Xyzzy',
  },
};
```

that's defined in a module defined with an alias using `baseUrl` and `paths` in `jsconfig.json`, makes `npm run build` fail with an inscrutable error:

```
> Build error occurred
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.445 (/Users/gthb/git/next-12-bug/.next/server/pages/index.js:58:8)
    at __webpack_require__ (/Users/gthb/git/next-12-bug/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/gthb/git/next-12-bug/.next/server/pages/index.js:236:39)
    at /Users/gthb/git/next-12-bug/.next/server/pages/index.js:237:66
    at Function.__webpack_require__.X (/Users/gthb/git/next-12-bug/.next/server/webpack-runtime.js:108:21)
    at /Users/gthb/git/next-12-bug/.next/server/pages/index.js:237:47
    at Object.<anonymous> (/Users/gthb/git/next-12-bug/.next/server/pages/index.js:240:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  type: 'TypeError'
}
```

Here's that line 58 and relevant preceding lines in `pages/index.js`:
```javascript
;// CONCATENATED MODULE: external "constants"
const external_constants_namespaceObject = require("constants");
;// CONCATENATED MODULE: ./pages/index.js





const desc = {
};
Object.keys(external_constants_namespaceObject.FOO).forEach((key)=>{
```

### Expected Behavior

`npm run build` should complete without problems.

### To Reproduce

Create a fresh Next project with `create-next-app`.

Then add:

`constants/index.js`:
```javascript
export const FOO  = {
  bar: {
    title: 'baz',
    body: 'Xyzzy',
  },
};
```

`jsconfig.json`:
```javascript
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "constants": ["constants"],
    }
  },
  "exclude": [
    "node_modules",
  ]
}
```

and add this into `pages/index.js`:
```javascript
import { FOO } from 'constants';

const desc = {};
Object.keys(FOO).forEach(key => {
  desc[key] = <p>{FOO[key]?.body}</p>;
});
```

and run `npm run build`.

That fails with:

```
> Build error occurred
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.445 (/Users/gthb/git/next-12-bug/.next/server/pages/index.js:58:8)
    at __webpack_require__ (/Users/gthb/git/next-12-bug/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/gthb/git/next-12-bug/.next/server/pages/index.js:236:39)
    at /Users/gthb/git/next-12-bug/.next/server/pages/index.js:237:66
    at Function.__webpack_require__.X (/Users/gthb/git/next-12-bug/.next/server/webpack-runtime.js:108:21)
    at /Users/gthb/git/next-12-bug/.next/server/pages/index.js:237:47
    at Object.<anonymous> (/Users/gthb/git/next-12-bug/.next/server/pages/index.js:240:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  type: 'TypeError'
}
```

**Comment by gthb** [comment]
For context, I encountered this when trying to adopt SWC instead of Babel, in an existing codebase that uses Babel (and has `tsconfig.json` instead of `jsconfig.json`, but with `"allowJs": true`), with Babel config like this:
```
const tsConfig = require('./tsconfig.json');
const paths = tsConfig.compilerOptions.paths;
const aliases = {};
Object.keys(paths).forEach(key => {
  aliases[key] = `./src/${paths[key][0]}`;
});
module.exports = [
  ...
  plugins: [
    [
      'module-resolver',
      {
        root: [ './src' ],
        alias: aliases,
      },
    ],
  ...
]
```

**Comment by gthb** [comment]
Still fails in 12.0.3.

**Comment by balazsorban44** [comment]
This reproduces outside of Next.js https://github.com/microsoft/TypeScript/issues/38846#issuecomment-964832529

An easy fix is to do something like this:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@constants": ["constants"],
    }
  },
  "exclude": [
    "node_modules",
  ]
}
```

Then change your import to this:
```
import { FOO } from '@constants';
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
