### ISSUE TITLE
HookWebpackError: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by kyledecot** [vercel/next.js#30744]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

17.0.1

### What browser are you using?

N/A

### What operating system are you using?

Docker / MacOS

### How are you deploying your application?

next start

### Describe the Bug

Attempting to run `next build` from within a docker container results in:

```
 > [builder 5/5] RUN yarn build && yarn install --production --ignore-scripts --prefer-offline:
#15 0.361 yarn run v1.22.15
#15 0.387 $ next build
#15 0.879 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#15 0.880 This information is used to shape Next.js' roadmap and prioritize features.
#15 0.880 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#15 0.880 https://nextjs.org/telemetry
#15 0.880
#15 1.029 info  - Checking validity of types...
#15 2.055 info  - Creating an optimized production build...
#15 4.859 Failed to compile.
#15 4.859
#15 4.859 HookWebpackError: error:0308010C:digital envelope routines::unsupported
#15 4.859     at makeWebpackError (/website/node_modules/next/dist/compiled/webpack/bundle5.js:45539:9)
#15 4.859     at /website/node_modules/next/dist/compiled/webpack/bundle5.js:29467:12
#15 4.859     at eval (eval at create (/website/node_modules/next/dist/compiled/webpack/bundle5.js:141008:10), <anonymous>:91:1)
#15 4.859 -- inner error --
#15 4.859 Error: error:0308010C:digital envelope routines::unsupported
#15 4.859     at new Hash (node:internal/crypto/hash:67:19)
#15 4.859     at Object.createHash (node:crypto:130:10)
#15 4.859     at getHashDigest (/website/node_modules/next/dist/compiled/loader-utils/index.js:1:29141)
#15 4.859     at /website/node_modules/next/dist/compiled/loader-utils/index.js:1:31472
#15 4.859     at String.replace (<anonymous>)
#15 4.859     at Object.interpolateName (/website/node_modules/next/dist/compiled/loader-utils/index.js:1:31381)
#15 4.859     at /website/node_modules/next/dist/build/webpack/plugins/copy-file-plugin.js:41:51
#15 4.859 caused by plugins in Compilation.hooks.processAssets
#15 4.859 Error: error:0308010C:digital envelope routines::unsupported
#15 4.859     at new Hash (node:internal/crypto/hash:67:19)
#15 4.859     at Object.createHash (node:crypto:130:10)
#15 4.859     at getHashDigest (/website/node_modules/next/dist/compiled/loader-utils/index.js:1:29141)
#15 4.859     at /website/node_modules/next/dist/compiled/loader-utils/index.js:1:31472
#15 4.859     at String.replace (<anonymous>)
#15 4.859     at Object.interpolateName (/website/node_modules/next/dist/compiled/loader-utils/index.js:1:31381)
#15 4.859     at /website/node_modules/next/dist/build/webpack/plugins/copy-file-plugin.js:41:51
#15 4.859
#15 4.859
#15 4.859 > Build failed because of webpack errors
#15 4.893 error Command failed with exit code 1.
#15 4.893 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Build should exit without error

### To Reproduce

- Create a new application using `yarn create next-app`
- Add a `Dockerfile` (see https://nextjs.org/docs/deployment#docker-image).
- Run ` docker build . -t my-app`

**Comment by kyledecot** [comment]
Duplicate of https://github.com/vercel/next.js/issues/30078

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
