### ISSUE TITLE
Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

### ISSUE THREAD

**Issue by manhthepixta** [vercel/next.js#30782]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

12.22.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I experienced this error when calling in `next.config.js` then `yarn build`

`config.plugins.push(new MiniCssExtractPlugin());`

This is the error detail
```
Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered
    at Object.register (/Users/manh/deconst/node_modules/next/dist/compiled/webpack/bundle5.js:113018:10)
    at Function.getCssModule (/Users/manh/deconst/node_modules/mini-css-extract-plugin/dist/index.js:191:32)
    at MiniCssExtractPlugin.apply (/Users/manh/deconst/node_modules/mini-css-extract-plugin/dist/index.js:399:44)
    at createCompiler (/Users/manh/deconst/node_modules/next/dist/compiled/webpack/bundle5.js:132397:12)
    at create (/Users/manh/deconst/node_modules/next/dist/compiled/webpack/bundle5.js:132450:16)
    at webpack (/Users/manh/deconst/node_modules/next/dist/compiled/webpack/bundle5.js:132474:32)
    at Object.f [as webpack] (/Users/manh/deconst/node_modules/next/dist/compiled/webpack/bundle5.js:87784:16)
    at /Users/manh/deconst/node_modules/next/dist/build/compiler.js:31:40
    at new Promise (<anonymous>)
    at Object.runCompiler (/Users/manh/deconst/node_modules/next/dist/build/compiler.js:30:12)
```
My package version:
```
"next": "^12.0.2",
"mini-css-extract-plugin": "^2.4.3",
"webpack": "^5.61.0"
```

### Expected Behavior

no error

### To Reproduce

yarn build

**Comment by timneutkens** [comment]
You're editing the webpack configuration in a way that is not supported. Next.js already extracts CSS, this is not a bug in Next.js so I'll convert it to discussions.
