### ISSUE TITLE
Error while porting to v12.0.2: Uncaught DOMException: Failed to construct 'WebSocket'

### ISSUE THREAD

**Issue by neeraj3029** [vercel/next.js#30819]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

After I updated the next version from v11 to `12.0.2`, and deploy the app, the local deployment fails with the error `Uncaught DOMException: Failed to construct 'WebSocket':` in the browser console. I have referred to the [migration guide](https://nextjs.org/docs/upgrading#nextjs-hmr-connection-now-uses-a-websocket), I'm not using nginx. 

Complete error:
```
Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://localhost:3000http://localhost:3000/_next/webpack-hmr' is invalid.
    at init (webpack-internal:///../../node_modules/next/dist/client/dev/error-overlay/websocket.js:24:18)
    at Object.connectHMR (webpack-internal:///../../node_modules/next/dist/client/dev/error-overlay/websocket.js:47:5)
    at eval (webpack-internal:///../../node_modules/next/dist/client/next-dev.js:50:17)
    at Object.../../node_modules/next/dist/client/next-dev.js (http://localhost:3000/_next/static/chunks/main.js?ts=1635859762342:578:1)
    at Object.options.factory (http://localhost:3000/_next/static/chunks/webpack.js?ts=1635859762342:666:31)
    at __webpack_require__ (http://localhost:3000/_next/static/chunks/webpack.js?ts=1635859762342:37:33)
    at __webpack_exec__ (http://localhost:3000/_next/static/chunks/main.js?ts=1635859762342:1347:61)
    at http://localhost:3000/_next/static/chunks/main.js?ts=1635859762342:1348:179
    at webpackJsonpCallback (http://localhost:3000/_next/static/chunks/webpack.js?ts=1635859762342:1255:39)
    at http://localhost:3000/_next/static/chunks/main.js?ts=1635859762342:9:61```

### Expected Behavior

I'm trying to find a workaround so that the local deployment runs without error in the browser.

### To Reproduce

1. Create a next application with `create-next-app`
2. Run the local deployment with `next dev`

**Comment by Devisione** [comment]
your error says that you have the wrong path ws: // localhost: 3000http: // localhost: 3000 / _next / webpack-hmr

**Comment by ijjk** [comment]
Closing as a duplicate of https://github.com/vercel/next.js/issues/30328

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
