### ISSUE TITLE
Cannot compile blank create-next-app project. Webpack errors

### ISSUE THREAD

**Issue by OmarOmeiri** [vercel/next.js#30986]
### What example does this report relate to?

NexjJs build

### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

17.0.2 or 16.0.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

Cannot build an empty project created with `npx create-next-app@latest`.

The steps I took:

`npx create-next-app@latest --typescript`
`cd myProject`
`npm run dev`

The development server runs "OK" but with a warning:
```sh
$ npm run dev

> dev
> next dev


ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled successfully in 3.5s (172 modules)
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
wait  - compiling /...
event - compiled successfully in 296 ms (190 modules)
```

If ran with the following option in `next.config.js`

```js
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  webpack(config) {
    config.infrastructureLogging = { debug: /PackFileCache/ }
    return config;
  }
}
```

It outputs the following logs:

```sh
$ npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
    [webpack.cache.PackFileCacheStrategy] No pack exists at E:\Documents\CODE\WebDev\NextJs\vai\.next\cache\webpack\client-development.pack: Error: ENOENT: no such file or directory, stat 'E:\Documents\CODE\WebDev\NextJs\vai\.next\cache\webpack\client-development\index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 29.1154 ms
    [webpack.cache.PackFileCacheStrategy] No pack exists at E:\Documents\CODE\WebDev\NextJs\vai\.next\cache\webpack\server-development.pack: Error: ENOENT: no such file or directory, stat 'E:\Documents\CODE\WebDev\NextJs\vai\.next\cache\webpack\server-development\index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 28.6325 ms
event - compiled successfully in 3.5s (172 modules)
wait  - compiling /_error...
event - compiled successfully in 111 ms (173 modules)
wait  - compiling /...
event - compiled successfully in 285 ms (191 modules)
    [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: ResolverCachePlugin|normal|dependencyType=|esm|path=|E:\Documents\CODE\WebDev\NextJs\vai|request=|E:\Documents\CODE\WebDev\NextJs\vai\node_modules\@next\react-refresh-utils\runtime.js
    [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: ResolverCachePlugin|normal|dependencyType=|esm|path=|E:\Documents\CODE\WebDev\NextJs\vai|request=|private-next-pages/_app
    [webpack.cache.PackFileCacheStrategy] Storing pack...
    [webpack.cache.PackFileCacheStrategy] Capturing build dependencies... (E:\Documents\CODE\WebDev\NextJs\vai\next.config.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\@next\react-refresh-utils\loader.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\next-client-pages-loader.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\next-style-loader\index.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js)
    [webpack.cache.PackFileCacheStrategy] Storing pack...
    [webpack.cache.PackFileCacheStrategy] Capturing build dependencies... (E:\Documents\CODE\WebDev\NextJs\vai\next.config.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\ignore-loader\index.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js, E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js)
<t> [webpack.cache.PackFileCacheStrategy] resolve build dependencies: 869.3041 ms
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai: Error: EINVAL: invalid argument, read
<t> [webpack.cache.PackFileCacheStrategy] snapshot build dependencies: 3.4617 ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
    [webpack.cache.PackFileCacheStrategy] Error: Unable to snapshot resolve dependencies
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:65788:13        at jobError (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:42867:5)
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:42931:10        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:43798:13        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:121039:5        at Hook.eval [as callAsync] (eval at create (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:6:1)
        at AsyncQueue._handleResult (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:121009:21)
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:120992:11
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:43747:12        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:20032:16    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai\node_modules: Error: EINVAL: invalid argument, read      
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai\node_modules\@next: Error: EINVAL: invalid argument, read    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai\node_modules\@napi-rs: Error: EINVAL: invalid argument, read
<t> [webpack.cache.PackFileCacheStrategy] resolve build dependencies: 895.8821 ms
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai: Error: EINVAL: invalid argument, read
<t> [webpack.cache.PackFileCacheStrategy] snapshot build dependencies: 3.9425 ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
    [webpack.cache.PackFileCacheStrategy] Error: Unable to snapshot resolve dependencies
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:65788:13        at jobError (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:42867:5)
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:42931:10        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:43798:13        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:121039:5        at Hook.eval [as callAsync] (eval at create (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:6:1)
        at AsyncQueue._handleResult (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:121009:21)
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:120992:11
        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:43747:12        at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:20032:16    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai\node_modules\@next: Error: EINVAL: invalid argument, read    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai\node_modules: Error: EINVAL: invalid argument, read      
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\Documents\CODE\WebDev\NextJs\vai\node_modules\@napi-rs: Error: EINVAL: invalid argument, read
```

Running `npm run build` with `node@17` and a completely untouched project fails miserably with:

```sh
$ npm run build

> build
> next build

info  - Checking validity of types  
info  - Creating an optimized production build
Failed to compile.

HookWebpackError: error:0308010C:digital envelope routines::unsupported
    at makeWebpackError (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:45539:9)
    at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:29467:12    
    at eval (eval at create (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:91:1)
-- inner error --
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\loader-utils\index.js:1:29141)
    at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\loader-utils\index.js:1:31472  
    at String.replace (<anonymous>)
    at Object.interpolateName (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\loader-utils\index.js:1:31381)
    at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\plugins\copy-file-plugin.js:41:51
caused by plugins in Compilation.hooks.processAssets
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\loader-utils\index.js:1:29141)
    at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\loader-utils\index.js:1:31472  
    at String.replace (<anonymous>)
    at Object.interpolateName (E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\compiled\loader-utils\index.js:1:31381)
    at E:\Documents\CODE\WebDev\NextJs\vai\node_modules\next\dist\build\webpack\plugins\copy-file-plugin.js:41:51


> Build failed because of webpack errors
```

If ran with `node@16`, the error of the build process is:

```sh
$ npm run build

> build
> next build

info  - Checking validity of types  
info  - Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
info  - Creating an optimized production build  
Failed to compile.

Error: EISDIR: illegal operation on a directory, readlink 'E:\Documents\CODE\WebDev\NextJs\vai\pages\_app.tsx'


> Build failed because of webpack errors
```

### Expected Behavior

A clean build of a boilerplate project provided by `create-next-app`

### To Reproduce

1 - Windows 10 Pro
2 - node `17.0.1`
3 - `npx create-next-app@latest --typescript`
4 - `cd myProject`
5 - `npm run build`

**UPDATE**

I have seen the #30078 it is strongly related with trying with `node@17`, but not with `node@16`. I'm perfectly willing to use the older version of node, but cannot compile in any

**UPDATE 2**

It seems upgrading to `next@^12.0.3-canary.2` gets rid of the `HookWebpackError: error:0308010C:digital envelope routines::unsupported` error. But I still cannot compile, the errors goes back to what it was when using `node@16`:

```sh
$ npm run build

> vai@1.0.0 build
> next build

info  - Checking validity of types  
error - ESLint must be installed in order to run during builds: npm install --save-dev eslint@"<8.0.0"
info  - Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
info  - Creating an optimized production build  
Failed to compile.

Error: EISDIR: illegal operation on a directory, readlink 'E:\Documents\CODE\WebDev\NextJs\vai\pages\_app.tsx'
```

Why the heck would `_app.tsx` be considered a directory??
I ran `ls -la .` and it confirms it is not:

```sh
$ ls -la .
total 256
drwxr-xr-x 1 Omar 197121   0 Nov  4 18:48 ./
drwxr-xr-x 1 Omar 197121   0 Nov  4 18:45 ../
-rw-r--r-- 1 Omar 197121 188 Nov  4 19:00 _app.tsx
drwxr-xr-x 1 Omar 197121   0 Nov  4 18:48 api/
-rw-r--r-- 1 Omar 197121 200 Nov  4 18:50 index.tsx
```

**Comment by csm-yujinkim** [comment]
On macOS (M1 Monterey 12.0.1), same problem but with JavaScript only. My problem was however solved by using Node 16.
