### ISSUE TITLE
Next build error when use echarts/core

### ISSUE THREAD

**Issue by footman101** [vercel/next.js#31002]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

v16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

when use `import * as echarts from "echarts/core";`
then `next build`
report this:
```
> Build error occurred
/test/test-next/node_modules/echarts/core.js:20
export * from './lib/export/core';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.165 (/Users/houyuxin/test/test-next/.next/server/pages/Chart.js:89:18)
    at __webpack_require__ (/Users/houyuxin/test/test-next/.next/server/webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
```

when use `import * as echarts from 'echarts';`,  everything is ok.

when use `next dev`,  everything is ok.

I tried rto use custom babel config, non-custom  babel config, dynamic import component with `ssr` off and turn off `swcMinify` all report the same error.

### Expected Behavior

build successfully

### To Reproduce

```javascript
// import * as echarts from 'echarts';

import * as echarts from "echarts/core";

import { BarChart, LineChart, PieChart } from "echarts/charts";
import {
  GridComponent,
  LegendComponent,
  TooltipComponent,
  TitleComponent
} from "echarts/components";
import { SVGRenderer } from "echarts/renderers";
import { useEffect } from "react";

echarts.use([
  BarChart,
  LineChart,
  PieChart,
  TitleComponent,
  LegendComponent,
  TooltipComponent,
  GridComponent,
  SVGRenderer,
]);

const Chart = () => {
  useEffect(() => {
    const container = document.getElementById("echarts");
    // console.log(SVGRenderer)
    console.log(echarts);
    if (!container) return;
    const myChart = echarts.init(container);
    myChart.setOption({
      title: {
        text: "ECharts 入门示例",
      },
      tooltip: {},
      xAxis: {
        data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"],
      },
      yAxis: {},
      series: [
        {
          name: "销量",
          type: "bar",
          data: [5, 20, 36, 10, 10, 20],
        },
      ],
    });
  }, []);

  return <div id="echarts" style={{ width: 300, height: 400 }} />;
};

export default Chart;
```

**Comment by footman101** [comment]
`dynamic + ssr: false` fix my problem

**Comment by Vsion** [comment]
how import echarts v5 with dynamic + ssr: false

**Comment by wesley-jun** [comment]
@footman101 Can you give some tips ? thx!

**Comment by wesley-jun** [comment]
fixed.
```javascript
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
