### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by kakarot-dev** [vercel/next.js#31033]
### What version of Next.js are you using?

Next.js v12.0.2

### What version of Node.js are you using?

v17.0.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next build, next start

### Describe the Bug

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at getHashDigest (C:\Users\Libni\WebstormProjects\web\axel\node_modules\next\dist\compiled\loader-utils\index.js:1:29141)
    at C:\Users\Libni\WebstormProjects\web\axel\node_modules\next\dist\compiled\loader-utils\index.js:1:31472
    at String.replace (<anonymous>)
    at Object.interpolateName (C:\Users\Libni\WebstormProjects\web\axel\node_modules\next\dist\compiled\loader-utils\index.js:1:31381)
    at C:\Users\Libni\WebstormProjects\web\axel\node_modules\next\dist\build\webpack\plugins\copy-file-plugin.js:41:51

```

### Expected Behavior

There should be no errors

### To Reproduce

init a project

do next build

error occurs

**Comment by kakarot-dev** [comment]
ty!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
