### ISSUE TITLE
No `console.log` output for API routes

### ISSUE THREAD

**Issue by samuela** [vercel/next.js#31046]
### What version of Next.js are you using?

next@12.0.2

### What version of Node.js are you using?

v15.14.0

### What browser are you using?

n/a

### What operating system are you using?

macOS 11.6

### How are you deploying your application?

npm run dev

### Describe the Bug

`console.log`, `console.error`, and friends are not shown anywhere in the console logs when running `npm run dev`. 

I'm using the TypeScript `npx create-next-app ...` template. Happy to share any more detail that would be useful in debugging!

Tangentially related to https://github.com/vercel/next.js/discussions/31042.

### Expected Behavior

Logs to be shown.

### To Reproduce

Create a basic next.js 12 project, and insert a `console.log` in the template /api/hello route.

**Comment by samuela** [comment]
Narrowed it down: This happens when there's an error occurring in the handler module but not in the handler function itself, eg.
```ts
import type { NextApiRequest, NextApiResponse } from "next";

throw new Error("this is the problem");

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<{}>
) {
  console.log("HELLLOOOOOOO");
  res.status(200).json({});
}
```

It'd be nice to get a more informative error message here, esp. a stack trace.

**Comment by balazsorban44** [comment]
Your code never reached the `console.log` call. This is not a bug in Next.js

**Comment by samuela** [comment]
@balazsorban44 Could we get a stack trace for these failures? Currently the logs are totally silent.

**Comment by balazsorban44** [comment]
The API handler cannot run if there are errors thrown in the file itself. Not sure about the totally silent part.

With this code:
```js
// pages/api/hello
throw new Error("Boom! 💥")

export default function handler(_, res) {
  res.status(200).json({ name: "John Doe" })
}

```

## Development (`yarn dev`):

My terminal:
```sh
next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 386 ms (171 modules)
wait  - compiling /api/hello...
event - compiled client and server successfully in 91 ms (180 modules)
wait  - compiling /_error (client and server)...
error - pages/api/hello.js (1:6) @ eval
Error: Boom! 💥
> 1 | throw new Error("Boom! 💥")
    |      ^
  2 | 
  3 | export default function handler(_, res) {
  4 |   res.status(200).json({ name: "John Doe" })
event - compiled client and server successfully in 66 ms (181 modules)
wait  - compiling...
event - compiled successfully in 39 ms (27 modules)
```

Browser console:
```sh
Uncaught     at eval (webpack-internal:///./pages/api/hello.js:5:7)
    at Object../pages/api/hello.js (file:///.../.next/server/pages/api/hello.js:22:1)
    at __webpack_require__ (file:///.../.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (file:///.../.next/server/pages/api/hello.js:32:39)
    at <unknown> (file:///.../.next/server/pages/api/hello.js:33:28)
    at Object.<anonymous> (file:///.../.next/server/pages/api/hello.js:36:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

Browser error overlay:
![image](https://user-images.githubusercontent.com/18369201/145630179-5f198918-27ff-4e56-a661-6b0ab5c36450.png)


## Production (`yarn start`):
```
next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Boom! 💥
    at Object.677 (/.../.next/server/pages/api/hello.js:15:7)
    at __webpack_require__ (/.../.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/.../.next/server/pages/api/hello.js:31:39)
    at /.../.next/server/pages/api/hello.js:32:28
    at Object.<anonymous> (/.../.next/server/pages/api/hello.js:35:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by samuela** [comment]
Huh, interesting... I'm not sure why I wasn't seeing anything then. So I guess this is resolved, and I'll open a new issue if I come across this again with a reproduction.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
