### ISSUE TITLE
Cannot build to production in Next 12 (HookWebpackError: Expected `concurrency` to be a number from 1 and up at makeWebpackError)

### ISSUE THREAD

**Issue by geongeorge** [vercel/next.js#31095]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

16

### What browser are you using?

Chrome

### What operating system are you using?

Mac os 11.6

### How are you deploying your application?

Render.com

### Describe the Bug

I tried to upgrade my next 11 app to next 12, I have `{ esmExternals: false }` to support [react-froms](https://github.com/vercel/next.js/issues/30750#issuecomment-957237229)

Dev server works fine but the build fails on local and server

```
HookWebpackError: Expected `concurrency` to be a number from 1 and up
    at makeWebpackError (/xxx/node_modules/next/dist/compiled/webpack/bundle5.js:47100:9)
    at /xxx/node_modules/next/dist/compiled/webpack/bundle5.js:31028:12
    at eval (eval at create (/xxx/node_modules/next/dist/compiled/webpack/bundle5.js:141008:10), <anonymous>:48:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
TypeError: Expected `concurrency` to be a number from 1 and up
    at Object.pLimit [as default] (/xxx/node_modules/p-limit/index.js:6:9)
    at /xxx/node_modules/next/dist/build/webpack/plugins/terser-webpack-plugin/src/index.js:160:47
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/xxx/node_modules/next/dist/trace/trace.js:74:20)
caused by plugins in Compilation.hooks.processAssets
TypeError: Expected `concurrency` to be a number from 1 and up
    at Object.pLimit [as default] (/xxx/node_modules/p-limit/index.js:6:9)
    at /xxx/node_modules/next/dist/build/webpack/plugins/terser-webpack-plugin/src/index.js:160:47
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/xxx/node_modules/next/dist/trace/trace.js:74:20)
```

### Expected Behavior

Expected to build

### To Reproduce

Not sure, We have a huge project which was recently upgraded to next 12

next.config.js
```js
const path = require('path');

module.exports = (phase, {defaultConfig}) => {
  defaultConfig['distDir'] = '../../.next';
  defaultConfig['experimental'] = { esmExternals: false };
  

  if ('sassOptions' in defaultConfig) {
        defaultConfig['sassOptions'] = {
            includePaths: [path.resolve(__dirname, './styles')],
            prependData: `
            @use 'lib/variables' as *;
            @use 'lib/mixins' as *;`,
        }
    }
    return defaultConfig;
};
```

**Comment by timneutkens** [comment]
Tried to reproduce this based on the info provided but couldn't get the same issue to occur. Could you try to reduce it to a minimal reproduction and share a repository so that we can investigate it?

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
