### ISSUE TITLE
[Expo] [WebDocument] TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by petrbela** [vercel/next.js#31104]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

16.7.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

After updating to 12.0.3 from 12.0.2, I'm now getting a build error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
TypeError: Cannot call a class as a function
    at _classCallCheck (webpack-internal:///./node_modules/@babel/runtime/helpers/classCallCheck.js:3:11)
    at WebDocument (webpack-internal:///./pages/_document.tsx:90:85)
    at processChild (/myproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/myproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/myproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/myproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (/myproject/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (/myproject/node_modules/next/dist/server/render.js:739:41)
    at async doRender (/myproject/node_modules/next/dist/server/next-server.js:1389:38)
    at async /myproject/node_modules/next/dist/server/next-server.js:1484:28
```

### Expected Behavior

This was working correctly in 12.0.2. If I had to guess I think the culprit is the new `_document.web.tsx` file that was added in https://github.com/vercel/next.js/pull/30963/files#diff-19e859eeb1baeee864c9a093b1eda99c402b707ac813857330747f42cdfbb979 (cc @huozhi) that's being picked up instead of `_document.tsx` by RNW/Expo projects.

### To Reproduce

One way to reproduce is to add Expo to a Next.js project https://docs.expo.dev/guides/using-nextjs/#add-expo-to-nextjs-projects

This is my `pages/_document.tsx`

```tsx
import { Document, getInitialProps } from '@expo/next-adapter/document'
import React from 'react'
import { flush } from 'react-native-media-query'

export default class WebDocument extends Document {
  static getInitialProps: typeof getInitialProps = async ({ renderPage }) => {
    const initialProps = await getInitialProps({ renderPage })
    const styles = [initialProps.styles, flush()]
    return { ...initialProps, styles: React.Children.toArray(styles) }
  }
}
```

**Comment by mononoke-choi** [comment]
after update nextjs version to 12.0.3 i have same problem.
as he said above, webpack picks web prefixed file.
my react native for web project picked this function document instead of class document

**react native for web project**
```
function Document() {
  return /*#__PURE__*/_react.default.createElement(_document.Html, null, /*#__PURE__*/_react.default.createElement(_document.Head, null), /*#__PURE__*/_react.default.createElement("body", null, /*#__PURE__*/_react.default.createElement(_document.Main, null), /*#__PURE__*/_react.default.createElement(_document.NextScript, null)));
}
```

**normal nextjs project**
```
class Document extends _react.Component {
  /**
  * `getInitialProps` hook returns the context object with the addition of `renderPage`.
  * `renderPage` callback executes `React` rendering logic synchronously to support server-rendering wrappers
  */
  static getInitialProps(ctx) {
    return ctx.defaultGetInitialProps(ctx);
  }

  render() {
    return /*#__PURE__*/_react.default.createElement(Html, null, /*#__PURE__*/_react.default.createElement(Head, null), /*#__PURE__*/_react.default.createElement("body", null, /*#__PURE__*/_react.default.createElement(Main, null), /*#__PURE__*/_react.default.createElement(NextScript, null)));
  }
}
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
