### ISSUE TITLE
Dynamic Routing Example "Try on stackblitz.com" fails

### ISSUE THREAD

**Issue by needfulthing** [vercel/next.js#31215]
### What example does this report relate to?

dynamic-routing

### What version of Next.js are you using?

n/a

### What version of Node.js are you using?

n/a

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

stackblitz.com

### Describe the Bug

https://stackblitz.com/github/vercel/next.js/tree/canary/examples/dynamic-routing link in readme.md throws the following error on stackblitz.com:

```
/projects/pariqyqqm.github
❯ npm install && npx next dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 0.194s
┌ [2/3] 🚚  Fetching dependencies
│ info pruneDeps Excluding 7 dependencies. For more information use `--verbose`.
└ Completed in 7.609s
┌ [3/3] 🔗  Linking dependencies
└ Completed in 0.465s

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 8.326s
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: not implemented
    at _0x44b75c (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:11:18432)
    at process.dlopen (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:11:66528)
    at Object.Module._extensions..node (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:6:168613)
    at Module.load (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:6:166317)
    at Function.Module._load (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:6:163857)
    at Module.require (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:6:166635)
    at i (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:6:435074)
    at _0x5af2cd (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:11:119264)
    at Object.eval (/home/projects/pariqyqqm.github/node_modules/next/dist/build/swc/index.js:30:20)
    at Object.function (https://pariqyqqm--github.jw.staticblitz.com/blitz.d83b9b15484f32317787d8c7cc41da5651102bdc.js:11:119647)
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```

### Expected Behavior

The example should build on stackblitz.com

### To Reproduce

Open https://stackblitz.com/github/vercel/next.js/tree/canary/examples/dynamic-routing in browser.

**Comment by balazsorban44** [comment]
Might have been a temporary hiccup on StackBlitz, clicking the link now works.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
