### ISSUE TITLE
how use have plenty of window package in next build

### ISSUE THREAD

**Issue by LeeKz7** [vercel/next.js#31387]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

16.11.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next build

### Describe the Bug

i need encryption http request，use `jsencrypt` 。
but `jsencrypt` use plenty of `window`。

in `next dev` can use
but in `next build` :
```
ReferenceError: window is not defined
    at Object.<anonymous> (D:\a\react\my-app3\node_modules\jsencrypt\bin\jsencrypt.js:18:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.804 (D:\a\react\my-app3\.next\server\pages\login.js:132:18)
    at __webpack_require__ (D:\a\react\my-app3\.next\server\webpack-runtime.js:25:42)
    at Function.__webpack_require__.t (D:\a\react\my-app3\.next\server\webpack-runtime.js:62:38)

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (D:\a\react\my-app3\node_modules\jest-worker\build\workers\ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (D:\a\react\my-app3\node_modules\jest-worker\build\workers\ChildProcessWorker.js:275:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  type: 'WorkerError'
}
error Command failed with exit code 1.
```

### Expected Behavior

how use have plenty of `window` package in next build

i is one beginner , i want to how resolve this problem

thanks

### To Reproduce

my solution:
```javascript
// utils/encrypt.ts
export async function rsaEncrypt(aesKey: string) {

  const jsencrypt = (await import('jsencrypt')).default

  let pubKey = `xxxxxxxxxx`

  let encryptStr = new jsencrypt()

  encryptStr.setPublicKey(pubKey)

  return encryptStr.encrypt(aesKey)

}

```

use:
```javascript
// pages/key/index.tsx
const Key = () => {
  async function onFinish(values: any) {
      const encrypt = await rsaEncrypt(aesKey)
      console.log(encrypt )
  }
}
```

**Comment by LeeKz7** [comment]
maybe can‘t use in NextPage?
should in components use?
