### ISSUE TITLE
Internal Server Error 500: `Invalid regular expression: /:\/: \ at end of pattern`

### ISSUE THREAD

**Issue by Jakst** [vercel/next.js#31411]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Any

### What operating system are you using?

Any

### How are you deploying your application?

next start on Heroku

### Describe the Bug

We have an automatic security testing tool that runs on our production sites to check for common vulnerabilities. In the latest run we got a bunch of internal server errors of the type `Invalid regular expression: /:\/: \ at end of pattern` (with different patterns depending on the path visited).

Here are the paths that triggered the error:
```
/desktop/core/?.%5C
/desktop/core/?.%5C.%5C
/desktop/core/?%00
/desktop/core/?%22%27%60%2C%C3%9E~%C3%87%1FY%00
/desktop/core/?%40%5B
/desktop/core/?%5C
/desktop/core/?%5C.%5C
/desktop/core/?%5Cx%5C
/desktop/core/?%7C
/desktop/core/?bar%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/?baz%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/?file%3A%5C
/desktop/core/?foo%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/?hack%3A%5C
/desktop/core/?unix:|
/desktop/core/?uniz:|
/desktop/core/?X5O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24EICAR-STANDARD-ANTIVIRUS-TEST-FILE%21%24H%2BH%2A
/desktop/core/?Y4O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24STANDARD-EICAR-ANTIVIRUS-HACK-FILE%21%24H%2BH%2A
/desktop/core/ext-py/?.%5C
/desktop/core/ext-py/?.%5C.%5C
/desktop/core/ext-py/?%00
/desktop/core/ext-py/?%22%27%60%2C%C3%9E~%C3%87%1FY%00
/desktop/core/ext-py/?%40%5B
/desktop/core/ext-py/?%5C
/desktop/core/ext-py/?%5C.%5C
/desktop/core/ext-py/?%5Cx%5C
/desktop/core/ext-py/?%7C
/desktop/core/ext-py/?bar%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/?baz%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/?file%3A%5C
/desktop/core/ext-py/?foo%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/?hack%3A%5C
/desktop/core/ext-py/?unix:|
/desktop/core/ext-py/?uniz:|
/desktop/core/ext-py/?X5O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24EICAR-STANDARD-ANTIVIRUS-TEST-FILE%21%24H%2BH%2A
/desktop/core/ext-py/?Y4O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24STANDARD-EICAR-ANTIVIRUS-HACK-FILE%21%24H%2BH%2A
/desktop/core/ext-py/Paste-2.0.1/?.%5C
/desktop/core/ext-py/Paste-2.0.1/?.%5C.%5C
/desktop/core/ext-py/Paste-2.0.1/?%00
/desktop/core/ext-py/Paste-2.0.1/?%22%27%60%2C%C3%9E~%C3%87%1FY%00
/desktop/core/ext-py/Paste-2.0.1/?%40%5B
/desktop/core/ext-py/Paste-2.0.1/?%5C
/desktop/core/ext-py/Paste-2.0.1/?%5C.%5C
/desktop/core/ext-py/Paste-2.0.1/?%5Cx%5C
/desktop/core/ext-py/Paste-2.0.1/?%7C
/desktop/core/ext-py/Paste-2.0.1/?bar%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/?baz%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/?file%3A%5C
/desktop/core/ext-py/Paste-2.0.1/?foo%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/?hack%3A%5C
/desktop/core/ext-py/Paste-2.0.1/?unix:|
/desktop/core/ext-py/Paste-2.0.1/?uniz:|
/desktop/core/ext-py/Paste-2.0.1/?X5O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24EICAR-STANDARD-ANTIVIRUS-TEST-FILE%21%24H%2BH%2A
/desktop/core/ext-py/Paste-2.0.1/?Y4O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24STANDARD-EICAR-ANTIVIRUS-HACK-FILE%21%24H%2BH%2A
/desktop/core/ext-py/Paste-2.0.1/tests/?.%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?.%5C.%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?%00
/desktop/core/ext-py/Paste-2.0.1/tests/?%22%27%60%2C%C3%9E~%C3%87%1FY%00
/desktop/core/ext-py/Paste-2.0.1/tests/?%40%5B
/desktop/core/ext-py/Paste-2.0.1/tests/?%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?%5C.%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?%5Cx%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?%7C
/desktop/core/ext-py/Paste-2.0.1/tests/?bar%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?baz%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?file%3A%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?foo%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?hack%3A%5C
/desktop/core/ext-py/Paste-2.0.1/tests/?unix:|
/desktop/core/ext-py/Paste-2.0.1/tests/?uniz:|
/desktop/core/ext-py/Paste-2.0.1/tests/?X5O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24EICAR-STANDARD-ANTIVIRUS-TEST-FILE%21%24H%2BH%2A
/desktop/core/ext-py/Paste-2.0.1/tests/?Y4O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24STANDARD-EICAR-ANTIVIRUS-HACK-FILE%21%24H%2BH%2A
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?.%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?.%5C.%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?%00
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?%22%27%60%2C%C3%9E~%C3%87%1FY%00
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?%40%5B
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?%5C.%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?%5Cx%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?%7C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?bar%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?baz%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?file%3A%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?foo%60%3C%25%22%27%7B%24%2A%25%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?hack%3A%5C
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?unix:|
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?uniz:|
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?X5O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24EICAR-STANDARD-ANTIVIRUS-TEST-FILE%21%24H%2BH%2A
/desktop/core/ext-py/Paste-2.0.1/tests/cgiapp_data/?Y4O%21P%25%40AP%5B4%5CPZX54%28P%5E%297CC%297%7D%24STANDARD-EICAR-ANTIVIRUS-HACK-FILE%21%24H%2BH%2A
```

Here are some example error messages
```
SyntaxError: Invalid regular expression: /:.\.\/: \ at end of pattern
SyntaxError: Invalid regular expression: /:.\/: \ at end of pattern
SyntaxError: Invalid regular expression: /:@[/: Unterminated character class
SyntaxError: Invalid regular expression: /:\.\/: \ at end of pattern
SyntaxError: Invalid regular expression: /:\/: \ at end of pattern
SyntaxError: Invalid regular expression: /:\x\/: \ at end of pattern
SyntaxError: Invalid regular expression: /:bar`<%""'{$*%\/: Nothing to repeat"
SyntaxError: Invalid regular expression: /:baz`<%""'{$*%\/: Nothing to repeat"
SyntaxError: Invalid regular expression: /:file:\/: \ at end of pattern
SyntaxError: Invalid regular expression: /:foo`<%""'{$*%\/: Nothing to repeat"
SyntaxError: Invalid regular expression: /:hack:\/: \ at end of pattern
SyntaxError: Invalid regular expression: /:X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*/: Range out of order in character class
SyntaxError: Invalid regular expression: /:Y4O!P%@AP[4\PZX54(P^)7CC)7}$STANDARD-EICAR-ANTIVIRUS-HACK-FILE!$H+H*/: Range out of order in character class
```

### Expected Behavior

The server should return 404.

### To Reproduce

* Generate a new next app with `create-next-app` (v12.0.3 was latest at the time of writing)
* Start the server with either `next dev` or `next build && next start`
* Visit any of the paths listed above

The server will throw an internal server error with a regex message.

**Comment by ntkoopman** [comment]
Having the same issue:
```
SyntaxError: Invalid regular expression: /:****/: Nothing to repeat
    at new RegExp (<anonymous>)
    at escapeSegment (/usr/app/node_modules/next/dist/shared/lib/router/utils/prepare-destination.js:191:24)
    at Object.prepareDestination (/usr/app/node_modules/next/dist/shared/lib/router/utils/prepare-destination.js:99:30)
    at Object.fn (/usr/app/node_modules/next/dist/server/next-server.js:755:86)
    at Router.execute (/usr/app/node_modules/next/dist/server/router.js:222:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.run (/usr/app/node_modules/next/dist/server/next-server.js:1125:29)
    at async Server.handleRequest (/usr/app/node_modules/next/dist/server/next-server.js:320:20)
```

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.5-canary.12` of Next.js, please update and give it a try!

**Comment by Jakst** [comment]
Yes, that fixed it. Thank you!

Still having issues with https://github.com/vercel/next.js/issues/24977 on that canary version though

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
