### ISSUE TITLE
i18n: Next node server crashes when using a basePath in the URL with a string appended to it

### ISSUE THREAD

**Issue by thomasledoux1** [vercel/next.js#31423]
### What version of Next.js are you using?

12.0.3, canary

### What version of Node.js are you using?

16.11.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

next start

### Describe the Bug

We noticed our server kept restarting, and found this in our logs:

```
/app/node_modules/next/dist/shared/lib/i18n/normalize-locale-path.js:11
        if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) {
                             ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /app/node_modules/next/dist/shared/lib/i18n/normalize-locale-path.js:11:30
    at Array.some (<anonymous>)
    at Object.normalizeLocalePath (/app/node_modules/next/dist/shared/lib/i18n/normalize-locale-path.js:10:21)
    at Object.getLocaleMetadata (/app/node_modules/next/dist/shared/lib/i18n/get-locale-metadata.js:14:44)
    at Object.parseNextUrl (/app/node_modules/next/dist/shared/lib/router/utils/parse-next-url.js:18:52)
    at Server.handleRequest (/app/node_modules/next/dist/server/next-server.js:202:40)
    at /app/node_modules/next/dist/server/next.js:52:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I checked the code used in the 'normalize-locale-path.js' file, and I see there is no check to see if `pathnameParts[1]` exists.
Current code: 
```
if (pathnameParts[1].toLowerCase() === locale.toLowerCase()) 
```
Possible fix code: 
```
if (pathnameParts[1] && pathnameParts[1].toLowerCase() === locale.toLowerCase()) 
```
Easy fix would be to add a check if `pathnameParts[1]` exists?

### Expected Behavior

I would expect a check if `pathnameParts[1]` exists, so this error doesn't occur, and the server doesn't crash.

### To Reproduce
https://codesandbox.io/s/crazy-pike-zx8vu?file=/next.config.js
Surf to http://localhost:3000/fr-be/pmeeee

We are using a basePath, and we are using the following i18n config:
```js
i18n: {
    defaultLocale: 'fr',
    locales: ['fr'],
},
```
When I start my server, and go to http://localhost:3000/fr-be/pmeee the error occurs.
I'm guessing because /fr-be/pme is detected in the URL, so it gets confused about the basepath/i18n routing?

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.4-canary.14` of Next.js, please update and give it a try!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
