### ISSUE TITLE
[Next 12] Conditional render inside custom document causes error 

### ISSUE THREAD

**Issue by jackyef** [vercel/next.js#31478]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Next start

### Describe the Bug

We have a setup that passes query from the custom server into `_document` `getInitialProps`. A prop will be derived from the query and be used to conditionally render an error page. This started to fail in Next.js 12.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined

    at new NodeError (internal/errors.js:322:7)

    at Writable.write (internal/streams/writable.js:285:13)

    at /app/node_modules/next/dist/server/render.js:1123:37

    at Array.forEach (<anonymous>)

    at /app/node_modules/next/dist/server/render.js:1123:16

    at /app/node_modules/next/dist/server/render.js:1110:13

    at /app/node_modules/next/dist/server/render.js:1110:47

    at /app/node_modules/next/dist/server/render.js:1128:9

    at /app/node_modules/next/dist/server/render.js:1110:13

    at /app/node_modules/next/dist/server/render.js:1110:47 {

  code: 'ERR_INVALID_ARG_TYPE'

}
```

Minimal reproduction: https://github.com/jackyef/next-ssr-document-repro

### Expected Behavior

The server in the reproduction repo should render `<h1>This is an error page</h1>` without error.

### To Reproduce

Minimal reproduction: https://github.com/jackyef/next-ssr-document-repro

**Comment by PsykoSoldi3r** [comment]
I got the same issue using getInitialProps on _document level

**Comment by huozhi** [comment]
the `_document.tsx` should always return a valid document when status returning 404, it cannot be just a `<h1>` element.

Checkout this [error message](https://nextjs.org/docs/messages/missing-document-component) for more details. This is marked as an error in the next 12.0.5-canary.1

**Comment by ijjk** [comment]
Closing per-above as skipping the required Document tags is not supported

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
