### ISSUE TITLE
Build error using SWC: Error: TypeInfo not known for "a"

### ISSUE THREAD

**Issue by abriginets** [vercel/next.js#31650]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome 96

### What operating system are you using?

Ubuntu 20.04 WSL2

### How are you deploying your application?

Heroku

### Describe the Bug

Can't build NextJS project with [tsyringe](https://github.com/microsoft/tsyringe) dependency (decorators and dependency injection package)
```
> Build error occurred
Error: TypeInfo not known for "a"
    at InternalDependencyContainer.construct (/home/goodwin/flaut-nextjs/node_modules/tsyringe/dist/cjs/dependency-container.js:263:23)
    at InternalDependencyContainer.resolve (/home/goodwin/flaut-nextjs/node_modules/tsyringe/dist/cjs/dependency-container.js:105:33)
    at /home/goodwin/flaut-nextjs/.next/server/pages/index.js:1:389 {
  type: 'Error'
}
```

### Expected Behavior

Build should not fail

### To Reproduce

Use the following `.swcrc`:
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  }
}
```

Successfull build can be achieved with the following `.babelrc`:
```json
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "babel-plugin-parameter-decorator"
  ]
}
```

**Comment by timneutkens** [comment]
`.swcrc` is not supported. Please see https://github.com/vercel/next.js/discussions/30174 for supported features and how to enable them.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
