### ISSUE TITLE
Error Invalid character in header content ["Location"] with trailingSlash enabled

### ISSUE THREAD

**Issue by studio404pl** [vercel/next.js#31677]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

12.18.1

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When the `trailingSlash` is enabled, the redirection doesn't work properly in some of the cases.

Example URL:

```
http://localhost:3000/some-url/%E2%80%9Chttps://domain.com/analytics?pxid=111&%E2%80%9D
```

Returned error:

```
error - TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    at ServerResponse.setHeader (_http_outgoing.js:521:3)
    at Object.fn (/Library/WebServer/Documents/nextjs/node_modules/next/dist/server/next-server.js:554:25)
    at Router.execute (/Library/WebServer/Documents/nextjs/node_modules/next/dist/server/router.js:205:48)
    at DevServer.run (/Library/WebServer/Documents/nextjs/node_modules/next/dist/server/next-server.js:841:47)
    at DevServer.run (/Library/WebServer/Documents/nextjs/node_modules/next/dist/server/dev/next-dev-server.js:355:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DevServer.handleRequest (/Library/WebServer/Documents/nextjs/node_modules/next/dist/server/next-server.js:292:20) {
  code: 'ERR_INVALID_CHAR'
}
```

### Expected Behavior

All of the URLS tried to be accessed are properly redirected without any errors thrown.

### To Reproduce

1. `npm install next@11.1.2 react react-dom`
2. create a sample index page
3. create a `next.config.js` file:
```
module.exports = {
  trailingSlash: true,
};
```
4. `npm run dev`
5. Visit the below URL in the browser:
```
http://localhost:3000/some-url/%E2%80%9Chttps://domain.com/analytics?pxid=111&%E2%80%9D
```
6. See the error

**Comment by balazsorban44** [comment]
The URL is actually invalid, you have an extra `&` right after `pxid=111`. This works fine for me:

`http://localhost:3000/some-url/%E2%80%9Chttps://domain.com/analytics?pxid=111%E2%80%9D`

**Comment by tills13** [comment]
Is it invalid? 

The query is `?pxid=111&%E2%80%9D'` which is parsed into `{ 'pxid' => '111', '”' => '' }` 

Per https://url.spec.whatwg.org/#concept-urlencoded-parser (and is the behaviour of URL)

```
> const u = new URL('http://localhost:3000/some-url/%E2%80%9Chttps://domain.com/analytics?pxid=111&%E2%80%9D')
> u.search
'?pxid=111&%E2%80%9D'
> u.searchParams
URLSearchParams { 'pxid' => '111', '”' => '' }

```

At the very least, NextJS shouldn't encounter an error in this situation.

**Comment by balazsorban44** [comment]
After thinking some more about it @tills13, you are probably right, but I think this is actually not what the user wants. I needed to have another look, but

The URL
```
http://localhost:3000/some-url/%E2%80%9Chttps://domain.com/analytics?pxid=111&%E2%80%9D
```
looks like this when decoded:
```
http://localhost:3000/some-url/“https:/domain.com/analytics?pxid=111&”
```

They probably don't expect the search params to be parsed in this case, it's not part of the "outer" URL, but rather the one between `“` and `”`.

I believe encoding the "inner" URL resolves the user's problem

`http://localhost:3000/some-url/%E2%80%9Chttps%3A%2F%2Fdomain.com%2Fanalytics%3Fpxid%3D111%26%E2%80%9D`

This will redirect correctly.

@studio404pl is this what you want?:
```js
new URL(`http://localhost:3000/some-url/%E2%80%9C${encodeURIComponent("https://domain.com/analytics?pxid=111&")}%E2%80%9D`)
```

**Comment by tills13** [comment]
(I work with the original poster)

To be clear, this is something we encountered through APM, not something our app generates itself. We use ExpressJS and our own trailing slash middleware but the url in question didn't match any of our routes and so was handled by the default NextJS request handler. 

Honestly we see so much garbage come through our system ... who knows what people are doing on their machines to produce something like this. Seeing the garbage result in a 500 was new, though. Typically we'll see a 30X and then a 404.

**Comment by studio404pl** [comment]
@balazsorban44 as @tills13 already said, it should be handled gently by NextJS if we can expect any kind of input here. The problem is not about fixing the input data, just to process them properly even if they are malformed.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
