### ISSUE TITLE
Can not next export

### ISSUE THREAD

**Issue by thatcatdrout** [vercel/next.js#31739]
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Brave Browser

### What operating system are you using?

Linux

### How are you deploying your application?

Codeberg Pages

### Describe the Bug

yarn run v1.22.17
$ next export
info  - Loaded env from /home/catdrout/Desktop/ubuntu-web/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - using build directory: /home/catdrout/Desktop/ubuntu-web/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /home/catdrout/Desktop/ubuntu-web/node_modules/next/dist/export/index.js:257:23
    at async Span.traceAsyncFn (/home/catdrout/Desktop/ubuntu-web/node_modules/next/dist/telemetry/trace/trace.js:60:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected Behavior

it should just normally build the app!

### To Reproduce

git clone https://github.com/thatcatdrout/ubuntu.git
cd ubuntu
yarn
yarn build
yarn export

**Comment by thatcatdrout** [comment]
nevermind nextjs sucks. vercel suck too

**Comment by timneutkens** [comment]
```
Error: Image Optimization using Next.js' default loader is not compatible with next export.
Possible solutions:
- Use next start to run a server, which includes the Image Optimization API.
- Use any provider which supports Image Optimization (like Vercel).
- Configure a third-party loader in next.config.js.
- Use the loader prop for next/image.
Read more: nextjs.org/docs/messages/export-image-api
```

Please review: https://nextjs.org/docs/messages/export-image-api it shows the options to `next export` with image optimization disabled. E.g. using the `unoptimized` prop or providing a custom `loader` prop.

**Comment by frames75** [comment]
> Please review: https://nextjs.org/docs/messages/export-image-api it shows the options to `next export` with image optimization disabled. E.g. using the `unoptimized` prop or providing a custom `loader` prop.

The documentation listed in that link makes no reference to any `unoptimized` prop. I have tried exporting an application with it and it still crashes.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
