### ISSUE TITLE
Next 12.0.4 not working with Preact

### ISSUE THREAD

**Issue by xand3r40r93** [vercel/next.js#31878]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

17.0.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Next 12.0.4 not working with Preact, but building with 12.0.3.

### Expected Behavior

Next 12.0.4 working with Preact.

### To Reproduce

package.json:
```
{
  "dependencies": {
    "next": "12.0.4",
    "next-plugin-preact": "^3.0.6",
    "preact": "^10.6.1",
    "preact-render-to-string": "^5.1.19",
    "react": "npm:@preact/compat@^17.0.3",
    "react-dom": "npm:@preact/compat@^17.0.3",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.2.0"
  }
}
```
next build
```
info  - Checking validity of types...
info  - Creating an optimized production build...
> Build error occurred
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compat/package.json' is not defined by "exports" in ./node_modules/preact/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.mod._resolveFilename (./node_modules/.pnpm/next@12.0.4_9bfab5d69556db861da30525f2351767/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.Module._resolveFilename (./node_modules/.pnpm/module-alias@2.2.2/node_modules/module-alias/index.js:49:29)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (./node_modules/.pnpm/next@12.0.4_9bfab5d69556db861da30525f2351767/node_modules/next/dist/build/webpack-config.js:543:41) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

```

**Comment by xand3r40r93** [comment]
it was fixed in preact
https://github.com/preactjs/preact/pull/3344

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
