### ISSUE TITLE
constants.js not found

### ISSUE THREAD

**Issue by janvdhorst** [vercel/next.js#31988]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next build

### Describe the Bug

Hi,

my app works fine in development with running "next dev". But when trying to build it with "next build", it throws me this exception:

```
Build error occurred
Error: Cannot find module 'next/dist/next-server/lib/constants.js'
Require stack:
- C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js
- C:\Users\jan-v\AppData\Roaming\npm\node_modules\next\dist\next-server\server\require.js
- C:\Users\jan-v\AppData\Roaming\npm\node_modules\next\dist\build\index.js
- C:\Users\jan-v\AppData\Roaming\npm\node_modules\next\dist\cli\next-build.js
- C:\Users\jan-v\AppData\Roaming\npm\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (C:\Users\jan-v\AppData\Roaming\npm\node_modules\next\dist\build\webpack\require-hook.js:4:1784)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.UJjI (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:1721:18)
    at __webpack_require__ (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:23:31)
    at Object.59D+ (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:229:18)
    at __webpack_require__ (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:23:31)
    at Object.PUVv (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:1614:18)
    at __webpack_require__ (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:23:31)
    at Module.5w0S (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:928:71)
    at __webpack_require__ (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:23:31)
    at Object.1 (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:197:18)
    at __webpack_require__ (C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:23:31)
    at C:\Users\jan-v\Documents\richards-remise\.next\server\pages\_document.js:91:18 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jan-v\\Documents\\richards-remise\\.next\\server\\pages\\_document.js',
    'C:\\Users\\jan-v\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\next-server\\server\\require.js',
    'C:\\Users\\jan-v\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\build\\index.js',
    'C:\\Users\\jan-v\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\cli\\next-build.js',
    'C:\\Users\\jan-v\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\bin\\next'
  ]
}
```

I tried removing node_modules, package-lock.json and reinstalling all modules. Also downgrading to next version 11 did not solve this issue. What can I do?

### Expected Behavior

successfully build my app

### To Reproduce

package.json:

```
{
  "name": "richards-remise",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@artsy/fresnel": "^3.1.0",
    "@aws-amplify/ui-components": "^1.8.2",
    "@aws-amplify/ui-react": "^1.2.19",
    "@babel/core": "^7.15.5",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/preset-env": "^7.15.6",
    "@babel/preset-react": "^7.14.5",
    "@fortawesome/fontawesome-svg-core": "^1.3.0-beta2",
    "@fortawesome/free-regular-svg-icons": "^6.0.0-beta2",
    "@fortawesome/free-solid-svg-icons": "^6.0.0-beta2",
    "@fortawesome/react-fontawesome": "^0.1.15",
    "@next/bundle-analyzer": "^11.1.2",
    "aws-amplify": "^4.3.1",
    "babel-plugin-styled-components": "^1.13.2",
    "bootstrap": "^5.1.1",
    "mobx": "^6.3.3",
    "mobx-react-lite": "^3.2.1",
    "moment": "^2.29.1",
    "next": "^12.0.4",
    "react": "^17.0.2",
    "react-alert": "^7.0.3",
    "react-alert-template-basic": "^1.0.2",
    "react-bootstrap": "^2.0.0-rc.0",
    "react-burger-menu": "^3.0.6",
    "react-countdown": "^2.3.2",
    "react-dom": "^17.0.2",
    "react-moment": "^1.1.1",
    "react-responsive": "^9.0.0-beta.4",
    "react-use-websocket": "^2.8.0",
    "styled-components": "^5.3.1",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.13.15",
    "@babel/preset-env": "^7.14.1",
    "babel-plugin-styled-components": "^1.12.0",
    "webpack": "^5.36.2"
  }
}
```

**Comment by balazsorban44** [comment]
may I ask why do you have webpack installed? if you aren't sure, could you try removing and run npm install again and then build? 

Could you also try removing the `.next` folder and build again?

If none of these help, you should create a minimal reproduction and see how many packages you can remove before the issue isn't appearing anymore.

**Comment by janvdhorst** [comment]
> may I ask why do you have webpack installed? if you aren't sure, could you try removing and run npm install again and then build?
> 
> Could you also try removing the `.next` folder and build again?
> 
> If none of these help, you should create a minimal reproduction and see how many packages you can remove before the issue isn't appearing anymore.

Is webpack not Standard for next js applications? I cant remember installing it manually, but i will try your Suggestions. Thanks already :)

**Comment by balazsorban44** [comment]
It is, but you don't have to install it yourself.

**Comment by janvdhorst** [comment]
> It is, but you don't have to install it yourself.

thank you, removing the .next folder worked!

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
