### ISSUE TITLE
Running test locally always fails

### ISSUE THREAD

**Issue by mozeryansky** [vercel/next.js#32031]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

yarn test

### Describe the Bug

Everytime I try to run the tests I get the error below.

I have been running a single test using `node ./node_modules/.bin/jest -- test/development/acceptance/ReactRefreshLogBox.test.ts` and writing `.only` for a single test.

```
...
    > Loading browser with http://localhost:58844/

      at Object.webdriver [as default] (lib/next-webdriver.ts:58:13)

error - ./node_modules/next/dist/client/dev/amp-dev.js
TypeError: Cannot read property 'error' of undefined
(node:29703) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
wait  - compiling /_error (client and server)...
error - ./node_modules/next/dist/client/dev/amp-dev.js
TypeError: Cannot read property 'error' of undefined
error - Error: Cannot find module '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/.next/fallback-build-manifest.json'
Require stack:
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next
Error: Cannot find module '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/.next/fallback-build-manifest.json'
Require stack:
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.loadDefaultErrorComponents (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/dev/next-dev-server.js:679:43)
    at async DevServer.renderErrorToResponse (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/next-server.js:1730:40)
    at async pipe.req.req (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/next-server.js:1670:30)
    at async DevServer.pipe (/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/next-server.js:1148:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js',
    '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next'
  ]
}
error - Error: Cannot find module '/private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/.next/fallback-build-manifest.json'
Require stack:
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/server/load-components.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/utils.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/store.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/build/output/index.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/cli/next-dev.js
- /private/var/folders/md/c2qmk35d0j90c__dm0yn5cgw0000gn/T/next-install-1638432702733/node_modules/next/dist/bin/next
  console.log
    browser log: Failed to load resource: the server responded with a status of 500 (Internal Server Error)
...
```

### Expected Behavior

Tests to pass

### To Reproduce

> Clone rep
> yarn

> yarn test
or
> node ./node_modules/.bin/jest -- test/development/acceptance/ReactRefreshLogBox.test.ts

**Comment by balazsorban44** [comment]
As pointed out in the [`contributing.md`](https://github.com/vercel/next.js/blob/canary/contributing.md#running-tests), you should run tests with `yarn testheadless`.

You can pass the test path to that command directly, so

```sh
yarn testheadless test/development/acceptance/ReactRefreshLogBox.test.ts
```

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
