### ISSUE TITLE
ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by SangeetAgarwal** [vercel/next.js#32116]
### What version of Next.js are you using?

12.0.5

### What version of Node.js are you using?

16.13.1

### What browser are you using?

chrome

### What operating system are you using?

windows 10

### How are you deploying your application?

Not applicable

### Describe the Bug

ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.
 - options should be one of these:
   object { resourceRegExp, contextRegExp? } | object { checkResource }
   Details:
    * options misses the property 'resourceRegExp'. Should be:
      RegExp
      -> A RegExp to test the request against.
    * options misses the property 'checkResource'. Should be:
      function
      -> A filter function for resource and context.
```sh
    at validate (C:\git\RecipePuppy\node_modules\next\dist\compiled\schema-utils3\index.js:1:153662)
    at C:\git\RecipePuppy\node_modules\next\dist\compiled\webpack\bundle5.js:128039:17
    at new IgnorePlugin (C:\git\RecipePuppy\node_modules\next\dist\compiled\webpack\bundle5.js:49957:3)
    at Object.webpack (C:\git\RecipePuppy\next.config.js:3:25)
    at Object.getBaseWebpackConfig [as default] (C:\git\RecipePuppy\node_modules\next\dist\build\webpack-config.js:1389:32)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (C:\git\RecipePuppy\node_modules\next\dist\trace\trace.js:74:20)
    at async Span.traceAsyncFn (C:\git\RecipePuppy\node_modules\next\dist\trace\trace.js:74:20)
    at async HotReloader.start (C:\git\RecipePuppy\node_modules\next\dist\server\dev\hot-reloader.js:329:25)
    at async DevServer.prepare (C:\git\RecipePuppy\node_modules\next\dist\server\dev\next-dev-server.js:296:9) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '',
      schemaPath: '#/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [Array],
      parentSchema: [Object],
      data: /\/__tests__\//,
      children: [Array]
    }
  ],
  schema: { title: 'IgnorePluginOptions', anyOf: [ [Object], [Object] ] },
  headerName: 'Ignore Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run dev" terminated with exit code: 1.
```
### Expected Behavior

Should compile & run

### To Reproduce

Upgrade from  "next": "^10.1.3" to "next": "^12.0.5",

**Comment by SangeetAgarwal** [comment]
here's link to related[ issue on the gatsby platform ](https://github.com/gatsbyjs/gatsby/issues/33216)

**Comment by SangeetAgarwal** [comment]
@balazsorban44 I was able to create a fresh app using `npx create-next-app@latest --ts` & then copied over the relevant files from my previous next js app. It wasn't a very large app & all seems well so closing this issue. Thank you for taking the time to review this ticket.

**Comment by danhemerlein** [comment]
@SangeetAgarwal  @balazsorban44 I am having this exactly same issue after upgrading to "next": "12.0.7"

I'd like to not start completely over - would it be possible to reopen this issue?

**Comment by danhemerlein** [comment]
I was having this exact same issue and couldn't afford to start over. Fixed by replacing my custom webpack config in `next.config.js` with the following

`
module.exports = {
  reactStrictMode: true,
};
`

this is probably due to Next 12 using only Webpack 5 not Webpack 4

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
