### ISSUE TITLE
ESLint rule no-page-custom-font crashes when default export is an anonymous function

### ISSUE THREAD

**Issue by bryanrsmith** [vercel/next.js#32250]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

The no-page-custom-font ESLint rule assumes that default export function declarations are named, and it crashes when a file's default export is an anonymous function.

```
$ eslint ./

Oops! Something went wrong! :(

ESLint: 8.4.1

TypeError: Cannot read property 'name' of null
Occurred while linting /Users/bryan/code/spokes/99spokes/apps/og/api/_lib/templates/review.js:1
Rule: "@next/next/no-page-custom-font"
    at ExportDefaultDeclaration (/Users/bryan/code/spokes/99spokes/node_modules/@next/eslint-plugin-next/lib/rules/no-page-custom-font.js:46:56)
    at ruleErrorHandler (/Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/bryan/code/spokes/99spokes/node_modules/eslint/lib/linter/linter.js:1107:32
error Command failed with exit code 2.
```

### Expected Behavior

The crash happens because this rule uses function and class names to try to identify functions that are the default export in cases where the function or class is declared, and then later exported. e.g., `function Foo(){}; export default Foo;`. This fails to account for anonymous functions being directly exported. e.g., `export default function(){}`. The rule should handle this case without crashing.

### To Reproduce

Add a new page with the contents:

```jsx
export default function () {
	return <marquee>totally valid</marquee>;
}
```

and then run eslint.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
