### ISSUE TITLE
Next is cloning my components

### ISSUE THREAD

**Issue by nappalm** [vercel/next.js#32279]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

Next.js is cloning my main page several times at the bottom.
![image](https://user-images.githubusercontent.com/35016608/145154728-95a1536c-d36f-478b-93d6-2aaa53994f34.png)

### Expected Behavior

A single rendering of my components

### To Reproduce

I don't understand how I could reproduce this.

**Comment by balazsorban44** [comment]
Do you have a link to your project? Make sure you don't accidentally add your components as duplicate elements.

**Comment by nappalm** [comment]
> Do you have a link to your project? Make sure you don't accidentally add your components as duplicate elements.

@balazsorban44 see deploy in [Vercel app](https://humorinformatico.vercel.app/) and [Github Code](https://github.com/nappalm/humorinformatico)

**Comment by balazsorban44** [comment]
The issue seems to come from this line:

https://github.com/nappalm/humorinformatico/blob/e1e08f96fd823e5895e050d1f201ab4adb5838ad/components/navbar.js#L127

Commenting it out resolves your initial issue. Now there are quite a few warnings/errors in the console when I start the project locally, for example, double nested `a`, and `button` elements, which should be resolved.

I also saw this warning:

```sh
Warning: Prop `id` did not match. Server: "menu-button-4" Client: "menu-button-8"
    at button
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at eval (webpack-internal:///./node_modules/@chakra-ui/button/dist/chakra-ui-button.esm.js:205:15)
    at eval (webpack-internal:///./node_modules/@chakra-ui/button/dist/chakra-ui-button.esm.js:308:20)
    at eval (webpack-internal:///./node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js:763:9)
    at Menu (webpack-internal:///./node_modules/@chakra-ui/menu/dist/chakra-ui-menu.esm.js:709:24)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at eval (webpack-internal:///./node_modules/@chakra-ui/layout/dist/chakra-ui-layout.esm.js:327:94)
    at nav
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at Navbar (webpack-internal:///./components/navbar.js:77:22)
    at main
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:55:66)
    at Main (webpack-internal:///./components/layout/main.js:17:26)
    at EnvironmentProvider (webpack-internal:///./node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.esm.js:120:24)
    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.esm.js:216:21)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-699e6908.browser.esm.js:94:64)
    at ThemeProvider (webpack-internal:///./node_modules/@chakra-ui/system/dist/chakra-ui-system.esm.js:69:34)
    at eval (webpack-internal:///./node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.esm.js:319:23)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/provider/dist/chakra-ui-provider.esm.js:24:24)
    at Website (webpack-internal:///./pages/_app.js:48:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:331:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:770:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:891:27) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

You might want to report this on Chakra or Emotion and link to this issue and your repository.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
