### ISSUE TITLE
Error: connect ECONNREFUSED on Vercel using environment variables

### ISSUE THREAD

**Issue by Jonofat** [vercel/next.js#32422]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

14.4.0

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

 The last time I deployed to Vercel was a few months ago and I had no problem. I didn't actually change any code now, I just added a file to my public folder and that's all, yet the build is failing. I don't get this error locally when running npm run build, only when trying to deploy to Vercel. 

```
Error occurred prerendering page "/en-GB/gallery". Read more: https://nextjs.org/docs/messages/prerender-error
--
12:59:58.674 | Error: connect ECONNREFUSED 127.0.0.1:80
12:59:58.674 | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
13:00:00.420 |  
13:00:00.420 | Error occurred prerendering page "/en-GB". Read more: https://nextjs.org/docs/messages/prerender-error
13:00:00.420 | Error: connect ECONNREFUSED 127.0.0.1:80
13:00:00.421 | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
13:00:00.421 |  
13:00:00.421 | > Build error occurred
```

Here is my config file:

```
module.exports = {
  images: {
    domains: ["localhost", "api.mywebsite.co.uk"],
  },
  i18n: {
    locales: ["en-GB"],
    defaultLocale: "en-GB",
  },
  webpack: (config, { isServer }) => {
    if (isServer) {
      require("./scripts/generate-sitemap");
    }

    return config;
  },
  async headers() {
    return [
      {
        source: "/:all*(svg|jpg|png)",
        locale: false,
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=9999999999, must-revalidate",
          },
        ],
      },
    ];
  },
};
```

UPDATE: 

I have updated this question because changing something has resolved the issue but I don't know why. I replaced all my process.env API urls with the actual url. So, instead of:

 ` uri: process.env.NEXT_PUBLIC_API_GRAPHQL,`

I used

`uri: https://api.mywebsite.co.uk/graphql`

Using process.env was working 100% before. The ENV variables exist in my Vercel account and I have not changed them.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
