### ISSUE TITLE
Middleware Prefixing the Default Local

### ISSUE THREAD

**Issue by HT-Moh** [vercel/next.js#32499]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

v16.13.1

### What browser are you using?

firefox

### What operating system are you using?

ubuntu

### How are you deploying your application?

docker

### Describe the Bug

When I add a middleware the same as the one provided on the [doc](https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale) to prefix the default language with `en` and run `ỳarn run build`, I got the following error: 

 ```
> Build error occurred
/NextJS/node_modules/next/server.js:1
export { NextRequest } from 'next/dist/server/web/spec-extension/request'
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.6389 (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/.next/server/pages/_middlewares.js:20:32)
    at __webpack_require__ (/media/bicatalyst/Pytech/crypto-catalyst-website/NextJS/.next/server/webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
error Command failed with exit code 1.
```

when I remove the middleware everything works fine 

### Expected Behavior

It should simply build. 

### To Reproduce

Add middlware inside page folder   [ref://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale)

```
// pages/_middleware.ts

import { NextRequest, NextResponse } from 'next/server'

const PUBLIC_FILE = /\.(.*)$/

export function middleware(request: NextRequest) {
  const shouldHandleLocale =
    !PUBLIC_FILE.test(request.nextUrl.pathname) &&
    !request.nextUrl.pathname.includes('/api/') &&
    request.nextUrl.locale === 'default'

  return shouldHandleLocale
    ? NextResponse.redirect(`/en${request.nextUrl.href}`)
    : undefined
}
```
`yarn run build`

**Comment by HT-Moh** [comment]
Changing `_middlewares` to `_middleware` fixed the issue :-)

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
