### ISSUE TITLE
Next.js v12 upgrade: HMR not working properly with custom typescript server + ws

### ISSUE THREAD

**Issue by DiamondeX** [vercel/next.js#32573]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

linux, windows

### How are you deploying your application?

next start

### Describe the Bug

When using custom WebSocketServer with custom server and typescript, the following uncaught exceptions appear again and again after opening the page in the browser:

```
process uncaughtException [
  RangeError: Invalid WebSocket frame: invalid status code 54220
      at Receiver.controlMessage (/home/dev/app/node_modules/next/dist/compiled/ws/index.js:1:18895)
      at Receiver.getData (/home/dev/app/node_modules/next/dist/compiled/ws/index.js:1:17493)
      at Receiver.startLoop (/home/dev/app/node_modules/next/dist/compiled/ws/index.js:1:14331)
      at Receiver._write (/home/dev/app/node_modules/next/dist/compiled/ws/index.js:1:13671)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at Receiver.Writable.write (internal/streams/writable.js:303:10)
      at Socket.socketOnData (/home/dev/app/node_modules/next/dist/compiled/ws/index.js:1:44452)
      at Socket.emit (events.js:388:22)
      at Socket.emit (domain.js:470:12)
      at addChunk (internal/streams/readable.js:309:12) {
    code: 'WS_ERR_INVALID_CLOSE_CODE',
    [Symbol(status-code)]: 1002
  },
  'uncaughtException'
]
ws close:  [
  1002,
  <Buffer d2 dc b2 75 ea da bb 43 f1 99 80 54 ea cd bf 45 ea d5 f0 63 f7 cb bf 54>
]
```

Mentioned in the 2nd line `invalid status code` is always different.

This bug doesn't appear in firefox.

### Expected Behavior

No exceprtions

### To Reproduce

1. Use instructions from here to boilerplate the sample project: https://github.com/vercel/next.js/tree/canary/examples/custom-server-typescript
2. update typescript: `npm i typescript@latest`
3. install ws lib: `npm i -S ws && npm i -D @types/ws`
4. modify `server/index.ts` like this:

```typescript
import { createServer, IncomingMessage, Server } from 'http';
import next from 'next';
import { parse } from 'url';
import { WebSocketServer } from 'ws';

function createWsServer(server: Server): void {
  const wss = new WebSocketServer({ server });

  wss.on('connection', function connection(ws, req) {
    console.log('wss connection...', req.url);

    'message,error,close,open,unexpected-response,upgrade'.split(',').forEach(evt => {
      ws.on(evt, (...args: unknown[]) => {
        console.log('ws ' + evt + ': ', args);
      });
    });
  });

  'error,close'.split(',').forEach(evt => {
    wss.on(evt, (...args: unknown[]) => {
      console.log('wss ' + evt + ': ', args);
    });
  });

  wss.on('headers', (...args: IncomingMessage[]) => {
    console.log('wss headers... url: ', (args[1] as IncomingMessage).url);
  });
}

const port = parseInt(process.env.PORT || '3000', 10);
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  const server = createServer((req, res) => {
    const parsedUrl = parse(req.url ?? '', true);
    handle(req, res, parsedUrl);
  });

  createWsServer(server);

  server.listen(port);

  console.log(`> Server listening at http://localhost:${port} in ${dev ? 'development' : process.env.NODE_ENV} mode`);
});

process.on('uncaughtException', (...args) => {
  console.log('process uncaughtException', args);
});

```
5. modify `pages/index.tsx` like this:

```tsx
import type { NextPage } from 'next';
import React, { useState } from 'react';

let ws: WebSocket;

if (typeof window !== 'undefined') {
  ws = new WebSocket(window.location.origin.replace(/^http/i, 'ws'));
  // @ts-ignore
  window.ws = ws;

  'open,message,close,error'.split(',').forEach(evt => {
    // @ts-ignore
    ws['on' + evt] = (...args: any[]) => {
      console.log('ws.on' + evt + ': ', args);
    };
  })
}

const Home: NextPage = () => {
  const [newMessage, setNewMessage] = useState<string>('');

  return (
    <input
      value={newMessage}
      placeholder="New message"
      onChange={(e) => {
        setNewMessage(e.currentTarget.value);
      }}
      onKeyDown={(e: React.KeyboardEvent) => {
        if (e.key === 'Enter') {
          setNewMessage('');
          ws.send(newMessage);
        }
      }}
    />
  );
};

export default Home;
```
6. run dev server: `npm run dev`
7. open browser (Chrome) at http://localhost:3000

**Comment by DiamondeX** [comment]
I've just made some minor updates to the original post, but they do not change the essence of the matter

**Comment by DiamondeX** [comment]
Please, pay attention to this remark: https://github.com/websockets/ws/issues/1985#issuecomment-996459766

**Comment by DiamondeX** [comment]
There is a simple workaround:
instead of using the root server path for websocket, some other path could be used. For example, to use '/ws' path, following changes are required:
1. in `server/index.ts` replace 
```ts
const wss = new WebSocketServer({ server });
```
with 
```ts
const wss = new WebSocketServer({ server, path: '/ws' });
```

2. in `pages/index.tsx` replace
```ts
ws = new WebSocket(window.location.origin.replace(/^http/i, 'ws'));
```
with 
```ts
ws = new WebSocket(window.location.origin.replace(/^http/i, 'ws')) + '/ws';
```
