### ISSUE TITLE
Static page generation on >= 12.0.0: document is not defined in styled-jsx

### ISSUE THREAD

**Issue by goguda** [vercel/next.js#32928]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

N/A

### What operating system are you using?

Linux

### How are you deploying your application?

next start

### Describe the Bug

When running next build on an existing working project being upgraded from Next.js 11 to Next.js >= 12.0.0, the build ends by static page generation failing with the following error:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: document is not defined
    at new StyleSheet (/project-dir/node_modules/styled-jsx/dist/lib/stylesheet.js:40:35)
    at new StyleSheetRegistry (/project-dir/node_modules/styled-jsx/dist/stylesheet-registry.js:51:33)
    at Object.createStyleRegistry (/project-dir/node_modules/styled-jsx/dist/stylesheet-registry.js:227:10)
    at renderToHTML (/project-dir/node_modules/next/dist/server/render.js:292:46)
    at async /project-dir/node_modules/next/dist/export/worker.js:273:36
    at async Span.traceAsyncFn (/project-dir/node_modules/next/dist/trace/trace.js:74:20)

Error occurred prerendering page "/advertise". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: document is not defined
    at new StyleSheet (/project-dir/node_modules/styled-jsx/dist/lib/stylesheet.js:40:35)
    at new StyleSheetRegistry (/project-dir/node_modules/styled-jsx/dist/stylesheet-registry.js:51:33)
    at Object.createStyleRegistry (/project-dir/node_modules/styled-jsx/dist/stylesheet-registry.js:227:10)
    at renderToHTML (/project-dir/node_modules/next/dist/server/render.js:292:46)
    at async /project-dir/node_modules/next/dist/export/worker.js:273:36
    at async Span.traceAsyncFn (/project-dir/node_modules/next/dist/trace/trace.js:74:20)

...

Generating static pages (123/123)

> Build error occurred
Error: Export encountered errors on following paths:
        /
        /404
        /_error: /500
        /advertise
        ...
```

And every static page fails to build. The weird thing is /_error is listed even though I don't even have a custom error page, and my 404 page is super basic with just an image in a div and some text.

I've removed all css-modifying plugins from next.config.js and I've tried building with a barebones next.config.js to no avail. I've also tried commenting out all global css imports in _app.js to no avail. As far as I knew, I wasn't even using styled-jsx; the closest thing I'm doing is inline styles in some components.

Has anyone seen anything like this? I'm absolutely stumped and it's the only reason I haven't upgraded to v12 yet.

### Expected Behavior

Static pages should build successfully without styled-jsx errors.

### To Reproduce

This is a tough one since I'm not exactly sure what is causing it. On some pages I'm using Material UI v4 and antd, and I thought one of these might be the culprit, but commenting out all relevant imports the issue remains, and it's not even used on some of the more basic static pages this is happening on, so I'm stumped.

**Comment by balazsorban44** [comment]
This issue has been automatically closed after 30 days of inactivity with no reproduction. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
