### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Justice-0x** [vercel/next.js#32971]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

17.3.0

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

yarn

### Describe the Bug

I'm not sure what the bug is but i can't compile

### Expected Behavior

Well was hoping for it to compile so I can run local and work on it

### To Reproduce

justicet@crackbook VAweb % yarn run dev
yarn run v1.22.17
$ cross-env next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://nextjs.org/docs/messages/react-version
info  - Using webpack 4. Reason: future.webpack5 option disabled https://nextjs.org/docs/messages/webpack5
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports.__webpack_modules__.15660.module.exports (/Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:111680:62)
    at NormalModule._initBuildHash (/Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:85092:16)
    at handleParseError (/Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:85146:10)
    at /Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:85178:5
    at /Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:85033:12
    at /Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:51096:3
    at iterateNormalLoaders (/Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:50937:10)
    at Array.<anonymous> (/Users/justicet/va/VAweb/node_modules/next/dist/compiled/webpack/bundle4.js:50928:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0
error Command failed with exit code 1.

**Comment by brc-dd** [comment]
> In Next.js 12 webpack 4 support was removed. (https://nextjs.org/docs/messages/webpack5)

Refer: https://nextjs.org/docs/upgrading

**Comment by timneutkens** [comment]
Please upgrade to the latest version of Next.js or downgrade the Node.js version to 16.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
