### ISSUE TITLE
Build error occurred TypeError: Cannot read property 'GJ' of undefined

### ISSUE THREAD

**Issue by hemedani** [vercel/next.js#32980]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17.0

### What browser are you using?

firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next build

### Describe the Bug

when is executed `yarn build` everything ok but in the end, it's throw this error :
```
yarn run v1.22.15
$ next build
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
info  - Compiled successfully
(node:61364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'GJ' of undefined
    at Object.GJ (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:180:91)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:903:65
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.61802 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:887:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:874:63
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.64253 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:863:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:4741:71
(Use `node --trace-warnings ...` to show where the warning was created)
(node:61364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eitherby throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2233)
(node:61364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:61364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'GJ' of undefined
    at Object.GJ (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:180:91)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:903:65
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.61802 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:887:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:874:63
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.64253 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:863:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:4741:71
(node:61364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eitherby throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2234)

> Build error occurred
TypeError: Cannot read property 'GJ' of undefined
    at Object.GJ (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:180:91)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:903:65
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.61802 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:887:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:874:63
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.64253 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:863:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:4741:71 {
  type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

build it  successfully

### To Reproduce

just run `yarn build`

**Comment by hemedani** [comment]
when I disabled SWC typescript compiler it's throw this error :
```
yarn run v1.22.15
$ next build
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /Users/syd/work/newKaryan/packages/front/.babelrc
info  - Creating an optimized production build
Failed to compile.

../../node_modules/next/dist/client/next.js
SyntaxError: JSON5: invalid end of input at 1:1
    at syntaxError (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:9451)
    at invalidEOF (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:8838)
    at Object.start (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:7253)
    at Object.parse (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:319)
    at getCustomBabelConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:131:31)
    at Object.getFreshConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:142:37)
    at Object.getConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:249:40)
    at Object.transform (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/transform.js:68:44)
    at /Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/index.js:19:112
    at Span.traceFn (/Users/syd/work/newKaryan/node_modules/next/dist/trace/trace.js:67:20)

../../node_modules/next/dist/client/router.js
SyntaxError: JSON5: invalid end of input at 1:1
    at syntaxError (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:9451)
    at invalidEOF (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:8838)
    at Object.start (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:7253)
    at Object.parse (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:319)
    at getCustomBabelConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:131:31)
    at Object.getFreshConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:142:37)
    at Object.getConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:249:40)
    at Object.transform (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/transform.js:68:44)
    at /Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/index.js:19:112
    at Span.traceFn (/Users/syd/work/newKaryan/node_modules/next/dist/trace/trace.js:67:20)

../../node_modules/next/dist/pages/_error.js
SyntaxError: JSON5: invalid end of input at 1:1
    at syntaxError (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:9451)
    at invalidEOF (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:8838)
    at Object.start (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:7253)
    at Object.parse (/Users/syd/work/newKaryan/node_modules/next/dist/compiled/json5/index.js:1:319)
    at getCustomBabelConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:131:31)
    at Object.getFreshConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:142:37)
    at Object.getConfig (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/get-config.js:249:40)
    at Object.transform (/Users/syd/work/newKaryan/node_modules/next/dist/build/babel/loader/transform.js:68:44)
```

**Comment by hemedani** [comment]
when is switch node version to `16.0.0` it's throw this error :
```
yarn run v1.22.17
$ next build
info  - Checking validity of types
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data ...node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError: Cannot read properties of undefined (reading 'GJ')
    at Object.GJ (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:180:91)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:903:65
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.61802 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:887:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:874:63
    at Function.__webpack_require__.a (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:98:13)
    at Object.64253 (/Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:863:21)
    at __webpack_require__ (/Users/syd/work/newKaryan/packages/front/.next/server/webpack-runtime.js:25:42)
    at /Users/syd/work/newKaryan/packages/front/.next/server/chunks/574.js:4741:71 {
  type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hemedani** [comment]
how can add reproduction

**Comment by balazsorban44** [comment]
Try removing pages/configuration incrementally, until you are left with some code that you can share in a repository or on something like https://codesandbox.io or https://stackblitz.com and it still reproduces the issue. This way, you might even be able to find the source of the issue, realizing that it's not a problem with Next.js but something in your own code.

If the issue can be reproduced with the `canary` version of Next.js, please come back with a link to your code, and we will have a closer look! :green_heart:

**Comment by hemedani** [comment]
I'm don't have any `.babelrc` file.
but I'm trying to remove page/configuration piece by piece to find out the root cause of the problem

**Comment by balazsorban44** [comment]
This issue has been automatically closed after 30 days of inactivity with no reproduction. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
