### ISSUE TITLE
Cannot load SWC binary

### ISSUE THREAD

**Issue by idanii** [vercel/next.js#33031]
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro

Binaries:
      Node: 16.13.1
      npm: 8.3.0
      Yarn: N/A
      pnpm: N/A

Relevant packages:
      next: 12.0.8-canary.17
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8-canary.17

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Other platform

### Describe the Bug

Next.js doesn't allow me to use the new Rust based compiler in order to compile my app. (SWC)

Error:
```
Error: The specified module could not be found.
\\?\C:\Users\User\Desktop\Test\test\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadNative (C:\Users\User\Desktop\Test\test\node_modules\next\dist\build\swc\index.js:84:    at loadBindings (C:\Users\User\Desktop\Test\test\node_modules\next\dist\build\swc\index.js:41:32)
    at async Object.isWasm (C:\Users\User\Desktop\Test\test\node_modules\next\dist\build\swc\index.js:146:20)
    at async C:\Users\User\Desktop\Test\test\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js:62:178 {
  code: 'ERR_DLOPEN_FAILED'
}
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-lPS
```

Error on Canary:
```
info  - Attempted to load @next/swc-win32-x64-gnu, but it was not installed
info  - Attempted to load @next/swc-win32-x64-msvc, but an error occurred: The specified module 
could not be found.
\\?\C:\Users\Idan\Desktop\Test\test\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node
error - Failed to load SWC binary for win32/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```

### Expected Behavior

The app should function and not crash when loading a page.

### To Reproduce

1) `npx create-next-app test`
2) `cd test`
3) `npm run dev`
4) Navigate to `localhost:3000` in your browser.

**Comment by ijjk** [comment]
Hi, posting this in the thread here https://nextjs.org/docs/messages/failed-loading-swc is sufficient and a separate issue is not needed. Feel free to update your response there with the `next info` provided here.

**Comment by balazsorban44** [comment]
This issue has been automatically locked due to no recent activity. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you.
