### ISSUE TITLE
500 Error - "static responses cannot be piped. This is a bug in Next.js"

### ISSUE THREAD

**Issue by imconfused218** [vercel/next.js#33292]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.15.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

Custom server/Other platform

### Describe the Bug

Experiencing intermittent 500s in production across all SSG pages with revalidation. When checking server logs, found this errror:
```
Error: invariant: static responses cannot be piped. This is a bug in Next.js
at RenderResult.pipe (/var/app/node_modules/next/dist/server/render-result.js:18:19)
at Object.sendRenderResult (/var/app/node_modules/next/dist/server/send-payload.js:58:22)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Looking a little deeper into the render-result file it appears that the result might be an empty string.

Also the 500 errors reported from users are blank with the text "Internal Server Error" and not our custom error page.

### Expected Behavior

Expect a successfully rendered page or the custom error page.

### To Reproduce

Unfortunately, haven't been able to reproduce this issue due to it's inconsistency and can't seem to find any pattern other than all the 500s are from SSG pages.

**Comment by balazsorban44** [comment]
Could you at least share your `next.config.js` file?

**Comment by iiDestiny** [comment]
@balazsorban44 ok Thank you for your reply

```
const path = require('path')
const fs = require('fs')
const withCss = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const withPlugins = require('next-compose-plugins') //sass css
const withAntd = require('./next-antd.config')
const lessToJS = require('less-vars-to-js')
const childProcess = require('child_process')
const { nextI18NextRewrites } = require('next-i18next/rewrites')
const qs = require('url')

const localeSubpaths = {
    'zh-CN': 'zh-cn',
}

// Where your antd-custom.less file lives
const themeVariables = lessToJS(
    fs.readFileSync(
        path.resolve(__dirname, './src/css/antd-custom.less'),
        'utf8'
    )
)

function RemoveMinimizeOptionFromCssLoaders(config) {
    config.module.rules.forEach((rule) => {
        if (Array.isArray(rule.use)) {
            rule.use.forEach((u) => {
                if (u.loader === 'css-loader' && u.options) {
                    delete u.options.minimize
                }
            })
        }
    })
}

const isProd = process.env.NODE_ENV === 'production'

const nextConfig = {
    images: {
        domains: [
            qs.parse(process.env.NEXT_PUBLIC_AVATAR_SERVER_HOST).hostname,
            qs.parse(process.env.NEXT_PUBLIC_IMAGE_SERVER_HOST).hostname,
        ],
    },
    rewrites: async () =>
        nextI18NextRewrites(localeSubpaths).concat([
            {
                source: '/api/:path*',
                destination: `${process.env.NEXT_PUBLIC_BASE_API}/:path*`,
            },
            /*  {
                source: '/site_asset/_next/:path*',
                destination: '/_next/:path*',
            }, */
        ]),
    publicRuntimeConfig: {
        localeSubpaths,
    },
    assetPrefix: '/',
    // experimental: {
    //     basePath: isProd ? '' : '/api',
    // },
    webpack: (config) => {
        RemoveMinimizeOptionFromCssLoaders(config)
        if (isProd) {
  
            isProd &&
                childProcess.exec(
                    'git log --pretty="%H - %ad" --date=iso-local --since="2020-01-01"',
                    function (error, stdout) {
                        if (!error) {
                            const DIST_PATH = path.resolve(__dirname, './.next')
                            fs.appendFileSync(
                                `${DIST_PATH}/web-commit.log`,
                                '',
                                'utf-8'
                            )
                            fs.writeFileSync(
                                `${DIST_PATH}/web-commit.log`,
                                stdout,
                                'utf-8'
                            )
                        }
                    }
                )
        }
        return config
    },
    typescript: {
        ignoreBuildErrors: true,
    },
}

module.exports = withPlugins(
    [
        [
            withCss,
            // {
            //     webpack: function (config) {
            //         config.module.rules.push({
            //             test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
            //             use: {
            //                 loader: 'url-loader',
            //                 options: {
            //                     limit: 100000,
            //                     name: '[name].[ext]',
            //                 },
            //             },
            //         })
            //         return config
            //     },
            // },
        ],
        [
            withSass,
            {
                cssModules: true,
                cssLoaderOptions: {
                    importLoaders: 1,
                    localIdentName: '[local]___[hash:base64:5]',
                },
            },
        ],
        [
            withAntd,
            {
                cssModules: false,
                cssLoaderOptions: {
                    sourceMap: false,
                    importLoaders: 1,
                },
                lessLoaderOptions: {
                    lessOptions: {
                        javascriptEnabled: true,
                        modifyVars: themeVariables,
                    },
                },
            },
        ],
    ],
    nextConfig
)

```

**Comment by huozhi** [comment]
Could you also share the snippet of your custom error page with `next.config.js` together?

**Comment by imconfused218** [comment]
Sure, happy too. Thanks for the quick response. 
next.config.js
```
'use strict';

const webpack = require('webpack');
const log = require('./utils/logger');
const { formatRedirects } = require('./utils/redirects');
const redirects = require('./config/redirects.json');
const cp = require('child_process');
const config = require('./config/app');
const API_ROOT = config.get('api.host');
const appData = require('./config/appData')
const env = {
    API_ROOT: JSON.stringify(API_ROOT),
};

const APP_ENV = config.get('env');
const isProd = APP_ENV === 'production';
const CDN = config.get('application.cdn');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
    enabled: process.env.BUNDLE_ANALYZE === 'true',
});

process.env.APP_DATA = JSON.stringify(appData);
const formattedRedirects = formatRedirects(redirects);

module.exports = withBundleAnalyzer({
    assetPrefix: CDN,
    async redirects() {
        return formattedRedirects;
    },
    webpack: (config, { isServer }) => {
        // Plugins
        config.plugins.push(new webpack.DefinePlugin(env));
        config.plugins.push(new webpack.NormalModuleReplacementPlugin(/\/iconv-loader$/, 'node-noop'));
        config.plugins.push(new webpack.NormalModuleReplacementPlugin(/whatwg-fetch/, 'node-noop'));
        config.plugins.push(new webpack.NormalModuleReplacementPlugin(/promise-polyfill/, 'node-noop'));

        const minimizer = config.optimization && config.optimization.minimizer && config.optimization.minimizer[0];
        if (minimizer && minimizer.options && minimizer.options.terserOptions) {
            minimizer.options.terserOptions.keep_fnames = true;
            minimizer.options.terserOptions.keep_classnames = true;
            // Because this is a thing we still have to do in 2018 https://github.com/mishoo/UglifyJS2/issues/1753
            minimizer.options.terserOptions.safari10 = true;
        }

        log.info(`Building with env ${APP_ENV} for ${isServer ? 'server' : 'client'}`);
        if (isProd) {
            const RollbarSourceMapPlugin = require('rollbar-sourcemap-webpack-plugin');

            let codeVersion;
            try {
                codeVersion = cp
                    .execSync('git rev-parse HEAD', {
                        cwd: __dirname,
                        encoding: 'utf8',
                    })
                    .trim();
            } catch (err) {
                log.error('Error getting revision', err);
                process.exit(1);
            }

            config.devtool = 'hidden-source-map';
            log.info(`Setting code version to ${codeVersion}`);
            config.plugins.push(
                new webpack.DefinePlugin({
                    CODE_VERSION: JSON.stringify(codeVersion),
                })
            );

            if (!process.env.BUNDLE_ANALYZE) {
                config.plugins.push(
                    new RollbarSourceMapPlugin({
                        accessToken: appData.ROLLBAR_SERVER,
                        version: codeVersion,
                        publicPath: `${CDN}/_next/`,
                        silent: false,
                    })
                );
            }
        }

        config.resolve.fallback = {
            fs: false,
        };

        return config;
    },
    publicRuntimeConfig: appData,
});
```
_error.js
```
// @flow
import React, { useEffect } from 'react';
import GlobalWrapper from '../contexts/global-wrapper';
import Layout from '../layouts/static-main';
import NotFound from '../components/page/not-found';
import { CustomError } from '../utils/error/custom-error';

import type { GetInitialPropsPage } from '../types/next';

type Props = {
    statusCode: number,
    err: ?Error,
    serverLogged: boolean,
    ...
};

type Params = { ... };

const ErrorPage: GetInitialPropsPage<Props, Params> = ({ err, serverLogged, statusCode }) => {
    useEffect(() => {
        if (window.Rollbar && err && !serverLogged) {
            window.Rollbar.error(err.toString());
        }
    }, [err, serverLogged]);

    if (statusCode < 500) {
        const layoutProps = {
            noContainer: true,
            title: 'MySite',
            description:
                'MySite Description',
            proUpsell: 'TRY FOR FREE',
        };
        return (
            <GlobalWrapper>
                <Layout {...layoutProps}>
                    <NotFound title="410 - Page gone" />
                </Layout>
            </GlobalWrapper>
        );
    }

    return (
        <div className="page-not-found">
            <div>
                <div style={{ textAlign: 'center', paddingTop: '24px' }}>
                    <h2>Internal Server Error</h2>
                    <p>
                        We're sorry. Something went wrong with your request. Please try again or contact us at{' '}
                        <a href="mailto:feedback@mysite.com">feedback@mysite.com</a> if the issue
                        persists.
                    </p>
                    <img src="https://static-assets/assets/img/500.png" />
                </div>
            </div>
        </div>
    );
};

ErrorPage.getInitialProps = async ({ res, req, err }) => {
    let serverLogged = false;
    let statusCode = res?.statusCode || 500;
    if (res && err) {
        const rollbarOptions = {
            payload: {},
            level: 'error',
        };
        if (err instanceof CustomError) {
            if (err.statusCode) {
                res.statusCode = err.statusCode;
                statusCode = err.statusCode;
            }
            rollbarOptions.payload = err.options || {};
        }

        const { reportRollbar } = require('../utils/rollbar/server');

        if (req) {
            await reportRollbar(err, req, rollbarOptions);
        }

        // eslint-disable-next-line
        console.error(err);
        serverLogged = true;
    }
    return {
        err,
        serverLogged,
        statusCode,
    };
};

export default ErrorPage;
```
I'll also work on getting a reproducing example to show.

**Comment by Downchuck** [comment]
I'm seeing failures out of the box with ​npx create-next-app@latest

```
 ​"dependencies": {
   ​"next": "12.0.9",
   ​"react": "^18.0.0-rc.0",
   ​"react-dom": "^18.0.0-rc.0"
 ​},
```

Like it's just not working  -- with SSR turned off:
```
TypeError: Cannot read properties of null (reading 'useContext')
```

And then with SSR turned on, I get the invariants error.

```
module.exports = {
  reactStrictMode: true,
  experimental: {
    concurrentFeatures: true,
    serverComponents: true
  }
}
```
I didn't see if the original poster was trying to use React 18.

**Comment by huozhi** [comment]
@Downchuck you cannot use `useContext` with server components, it's not supported

**Comment by Downchuck** [comment]
@huozhi I mean to say something went wrong with just the standard create-next-app. This is off the shelf.

**Comment by Downchuck** [comment]
This was related to multiple npm library folders... Figured out when I ran "npm run dev" vs "next dev" - the latter did not work, the former did.

**Comment by morganfeeney** [comment]
I'm getting this running Nextjs 13.2.4 on Azure App Service:
```
2023-06-21T19:18:55.186542902Z 19:18:55 0|my-nextJs-site  | ready - started server on 0.0.0.0:8080, url: http://localhost:8080
2023-06-21T19:18:55.196549942Z 19:18:55 0|my-nextJs-site  | info  - Loaded env from /home/site/wwwroot/.env.production
2023-06-21T19:19:17.938867952Z 19:19:17 0|my-nextJs-site  | Error: invariant: static responses cannot be piped. This is a bug in Next.js
2023-06-21T19:19:17.939830865Z 19:19:17 0|my-nextJs-site  |     at RenderResult.pipe (/home/site/wwwroot/node_modules/next/src/server/render-result.ts:33:13)
2023-06-21T19:19:17.940760077Z 19:19:17 0|my-nextJs-site  |     at Object.sendRenderResult (/home/site/wwwroot/node_modules/next/src/server/send-payload/index.ts:103:18)
```

**Comment by morganfeeney** [comment]
It turned out that as I had zipped the app and ran it from a zip file that I got this issue ^

**Comment by rudden** [comment]
We've receiving multiple errors of this kind in our logfiles. Hosted on Azure app service (linux) and running on PM2. Do we have any more information on what might be causing this? Would be nice to have more background and what it could lead to for our end users.

**Comment by nikita-s-sauce** [comment]
Same issue

We are using **_Azure App Service + Linux + PM2_** and some short period of a time getting 5xx in logs:
`Error: invariant: static responses cannot be piped. This is a bug in Next.js` .
Last week it happened 38 times which is 0,03% of all requests

Using:
NextJS - v13.2.1
node - v18.16.1
npm - v9.6.4

getStaticProps - with revalidate option
custom server - that sends logs through pino, pino-http, pino-datadog-logger, to DataDog

**Comment by 4leite** [comment]
@nikita-s-sauce  Did you find any resolution for this?

We are also seeing this intermittently running Azure App Service + Linux + PM2 with custom server and using a revalidate end point, so it seems a similar stack.

**Comment by issam-seghir** [comment]
i have similar error in nextjs 15 

```bash
 ⨯ [Error: failed to pipe response] {
  [cause]: [Error: Expected a suspended thenable. This is a bug in React. Please file an issue.] {
    digest: '1018347596'
  }
}
```

**Comment by marcoshernanz** [comment]
Thanks for the report. Empty static render results were being treated as streams in `sendRenderResult`. #48939 fixed the check, and the change shipped in Next.js 13.4.0. The invariant is no longer present in current releases, so I’m closing this as fixed. If you see this exact error on a current version, please open a new issue with a reproduction.
