### ISSUE TITLE
Requested and resolved page mismatch returns a 500 error. If the page shouldn't exist should be a 404 error.

### ISSUE THREAD

**Issue by psoaresbj** [vercel/next.js#33912]
### Run `next info` (available from version 12.0.8 and up)

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.1
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.11

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Any

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I run a project that's targeted with some different attacks. One is the directory traverse. Since I have a catch-all page in the root of the project, when i get a request with this method, the server fires a 500 error. It should be a 404.

```
Error: Requested and resolved page mismatch: /test/../package-lock.json /package-lock.json
    at Object.normalizePagePath (/Users/me/next-test/node_modules/next/dist/server/normalize-page-path.js:35:15)
    at Object.getPagePath (/Users/me/next-test/node_modules/next/dist/server/require.js:24:84)
    at NextNodeServer.getPagePath (/Users/me/next-test/node_modules/next/dist/server/next-server.js:336:30)
    at NextNodeServer.hasPage (/Users/me/next-test/node_modules/next/dist/server/base-server.js:533:28)
    at memoizedPageChecker (/Users/me/next-test/node_modules/next/dist/server/router.js:76:33)
    at Object.fn (/Users/me/next-test/node_modules/next/dist/server/router.js:144:35)
    at Router.execute (/Users/me/next-test/node_modules/next/dist/server/router.js:228:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NextNodeServer.run (/Users/me/next-test/node_modules/next/dist/server/base-server.js:598:29)
    at async NextNodeServer.handleRequest (/Users/me/next-test/node_modules/next/dist/server/base-server.js:305:20)
Error: Requested and resolved page mismatch: /test/../package-lock.json /package-lock.json
    at Object.normalizePagePath (/Users/me/next-test/node_modules/next/dist/server/normalize-page-path.js:35:15)
    at getPagePath (/Users/me/next-test/node_modules/next/dist/server/require.js:24:84)
    at Object.requirePage (/Users/me/next-test/node_modules/next/dist/server/require.js:44:22)
    at Object.loadComponents (/Users/me/next-test/node_modules/next/dist/server/load-components.js:58:23)
    at NextNodeServer.findPageComponents (/Users/me/next-test/node_modules/next/dist/server/next-server.js:354:63)
    at NextNodeServer.renderToResponse (/Users/me/next-test/node_modules/next/dist/server/base-server.js:1019:39)
    at pipe.req.req (/Users/me/next-test/node_modules/next/dist/server/base-server.js:680:38)
    at NextNodeServer.pipe (/Users/me/next-test/node_modules/next/dist/server/base-server.js:621:31)
    at NextNodeServer.render (/Users/me/next-test/node_modules/next/dist/server/base-server.js:680:21)
    at NextNodeServer.render (/Users/me/next-test/node_modules/next/dist/server/next-server.js:408:22)
Error: Requested and resolved page mismatch: /test/../package-lock.json /package-lock.json
    at Object.normalizePagePath (/Users/me/next-test/node_modules/next/dist/server/normalize-page-path.js:35:15)
    at IncrementalCache.get (/Users/me/next-test/node_modules/next/dist/server/incremental-cache.js:63:44)
    at /Users/me/next-test/node_modules/next/dist/server/response-cache.js:46:74
    at ResponseCache.get (/Users/me/next-test/node_modules/next/dist/server/response-cache.js:86:11)
    at NextNodeServer.renderToResponseWithComponents (/Users/me/next-test/node_modules/next/dist/server/base-server.js:886:53)
    at NextNodeServer.renderToResponse (/Users/me/next-test/node_modules/next/dist/server/base-server.js:1040:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NextNodeServer.pipe (/Users/me/next-test/node_modules/next/dist/server/base-server.js:621:25)
    at async Object.fn (/Users/me/next-test/node_modules/next/dist/server/base-server.js:494:21)
    at async Router.execute (/Users/me/next-test/node_modules/next/dist/server/router.js:228:32)
```

Request
<img width="849" alt="Screenshot 2022-02-02 at 13 18 48" src="https://user-images.githubusercontent.com/7081017/152161390-e1e21603-8244-4487-b52a-0b13700003d8.png">

### Expected Behavior

Should return a 404 error code instead of a 500 error code.

### To Reproduce

- Install a new next project.
- Create a catch-all page in pages directory.
- Build and run `next start`
- Execute a request with traversal directory method, using the `../` (dot dot slash).
- Check server console.

**Comment by balazsorban44** [comment]
Hi, following your reproduction steps, I neither get a 404 nor a 500. :thinking: Could you attach a minimal reproduction repository?

According to the URI specs, `..` should be valid and I don't think 404 is needed with a catch-all route.

https://www.rfc-editor.org/rfc/rfc3986#section-2.3

What I observe instead is that a `.` or `..` does a redirect.

`http://localhost:3000/test/../package-lock.json` -> `http://localhost:3000/package-lock.json`

`http://localhost:3000/test/./package-lock.json` -> `http://localhost:3000/test/package-lock.json`

I tested this behavior in Google Chrome and Firefox, and both have the same behavior with non-Next.js sites as well:

You can try it:

1. `https://github.com/vercel/next.js/issues/./33912`  will simply omit the `./`
2. `https://github.com/vercel/next.js/issues/../33912` will end up in a 404 on `https://github.com/vercel/next.js/33912`

(In fact when I wanted to let the above URLs be as plain text without the code fence `, GitHub simply rewrote those URLs).

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think this was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
