### ISSUE TITLE
Expo create-next-app Webpack Error

### ISSUE THREAD

**Issue by josh-console** [vercel/next.js#34596]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 14.17.0
      npm: 6.14.13
      Yarn: 1.21.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.1
      react: 17.0.2
      react-dom: 17.0.2

### Which example does this report relate to?

with-expo

### Describe the Bug

Example does not build/run and produces the following error. It seems to work with Next <= 10 and Webpack 4.  It does not seem to run with Next 11+ regardless of Webpack version.

``` 
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (~/with-expo-app/node_modules/next/dist/build/webpack-config.js:661:33)
    at webpackConfig.externals (~/with-expo-app/node_modules/next/dist/build/webpack-config.js:766:24)
    at ~/with-expo-app/node_modules/@expo/webpack-config/webpack/addons/withUnimodules.js:118:54
    at ~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:36695:21
    at deprecated (internal/util.js:96:15)
    at handleExternals (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:36843:8)
    at next (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:36821:9)
    at handleExternals (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:36826:7)
    at ~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:36923:5
    at Hook.eval [as callAsync] (eval at create (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:37:1)
    at ~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:50664:25
    at Hook.eval [as callAsync] (eval at create (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:19:1)
    at NormalModuleFactory.create (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:50636:28)
    at Compilation._factorizeModule (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:24267:11)
    at ~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:121745:10
    at Hook.eval [as callAsync] (eval at create (~/with-expo-app/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:6:1)
```

### Expected Behavior

Does not currently build/run; expected to build/run.

### To Reproduce

Simply install example and `next dev` or `next build`.

**Comment by balazsorban44** [comment]
This seems to be already reported here: https://github.com/expo/expo-cli/issues/4195

The [Expo docs](https://docs.expo.dev/guides/using-nextjs) also explicitly ask to report Next.js related issues on their repo:

> Please open any issues related to Next.js with Expo at [expo-cli/issues](https://github.com/expo/expo-cli/issues).

There is a chance that Expo does not work with Next.js 12 yet, let's see what they report on that issue to verify.

From the looks of it, the `@expo/next-adapter` package still assumes webpack 4, which has been removed in Next.js 12: https://nextjs.org/blog/next-12#breaking-changes

Found this relevant thread also: https://github.com/expo/expo-cli/issues/4066

Also `@expo/next-adapter` is locked in with Next.js 11 as an acceptable peer dependency: https://github.com/expo/expo-cli/blob/c73681f811e254bfaf40e1459b62cfd3e9a15167/packages/next-adapter/package.json#L51

I think we should wait until the Expo team comes out with an official statement that Expo is compatible with Next.js 12 and updates their adapter. When that's done, we could update our example. :+1:
