### ISSUE TITLE
ReferenceError: window is not defined -- when using a file from `lib/` inside API route

### ISSUE THREAD

**Issue by Amar-Gill** [vercel/next.js#34653]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
    Binaries:
      Node: 14.11.0
      npm: 6.14.8
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

`next start`

### Describe the Bug

When using a file from my `lib/` directory inside one of my apis (`pages/api`) I get the following error:
```
error - ReferenceError: window is not defined
```

However, there is no browser code in my lib file. It is simply a class that I use to contain methods.

### Expected Behavior

I should be able to instantiate the class inside the api route, and use it's methods. Even static methods cause the error to be thrown.

### To Reproduce

Throws no error:
```ts
import { addDays, isLeapYear, startOfYear } from 'date-fns';
import SolarCalculator from 'lib/solar-calculator';
import type { NextApiRequest, NextApiResponse } from 'next';

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  const { query, method } = req;

  const { year, lat, lng } = query;

  const days = getDaysOfYear(parseInt(year));

  const labels = days.map((date) => {
    const a = date.toDateString().split(' ');
    return `${a[1]}-${a[2]}`;
  });

  res.status(200).json({ message: 'cool', labels });
}

function getDaysOfYear(year: number): Date[] {
  const startDate = startOfYear(new Date().setUTCFullYear(year));

  const numDays = isLeapYear(startDate) ? 366 : 365;

  const daysOfYear = new Array(numDays).fill(null).map((_, i) => addDays(startDate, i));

  return daysOfYear;
}
```

Throws error:
```ts
import { addDays, isLeapYear, startOfYear } from 'date-fns';
import SolarCalculator from 'lib/solar-calculator';
import type { NextApiRequest, NextApiResponse } from 'next';

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  const { query, method } = req;

  const { year, lat, lng } = query;

  // OFFENDING CODE
  const calculator = new SolarCalculator({
    lat: parseFloat(lat),
    lng: parseFloat(lng),
  });

  const days = getDaysOfYear(parseInt(year));

  const labels = days.map((date) => {
    const a = date.toDateString().split(' ');
    return `${a[1]}-${a[2]}`;
  });

  res.status(200).json({ message: 'cool', labels });
}

function getDaysOfYear(year: number): Date[] {
  const startDate = startOfYear(new Date().setUTCFullYear(year));

  const numDays = isLeapYear(startDate) ? 366 : 365;

  const daysOfYear = new Array(numDays).fill(null).map((_, i) => addDays(startDate, i));

  return daysOfYear;
}
```

Sample code from `solar-calculator.ts` - it's just a bunch of methods that crunch numbers and some use dates.
```ts
import { differenceInDays } from 'date-fns';
import { LatLng, LatLngLiteral } from 'leaflet';

class SolarCalculator {
  private baselineReferenceJD = 2415020;

  private baselineReferenceDate = new Date('January 1, 1900');

  private position: LatLng;

  constructor(position: LatLngLiteral) {
    this.position = new LatLng(position.lat, position.lng);
  }

  /**
   *
   * @param {LatLng} position The Leaflet js position associated with the calculator instance
   * @returns {number} number between -14 and 14
   * which is an approximate UTC offset based on position.
   */
  public calculateUTCOffset(position = this.position): number {
    return Math.ceil(position.lng / 15);
  }
```

**Comment by Amar-Gill** [comment]
Update -- when trying a build, it throws error because of leaflet library used in the class:
```
> Build error occurred
ReferenceError: window is not defined
    at /Users/amardeepgill/personal-projects/ifrit/node_modules/leaflet/dist/leaflet-src.js:227:19
    at /Users/amardeepgill/personal-projects/ifrit/node_modules/leaflet/dist/leaflet-src.js:7:66
```

removing this dependency for now to resolve errors. Can close this issue.

**Comment by balazsorban44** [comment]
If you are importing a browser-only library, you can create a component file that imports it then, use a dynamic import to add it to your pages with the `{ssr: false}` option:

https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by LuisEnMarroquin** [comment]
How do I import `hellosign-embedded`? I tried with `const HelloSign = dynamic(() => import("hellosign-embedded"), { ssr: false })` but it gives me an error

![image](https://user-images.githubusercontent.com/35376824/159814552-207bf853-5638-4086-b7fe-c13848cab5dd.png)

Note, I am using typescript
