### ISSUE TITLE
Invalid characters in the location header is not handled and throws error

### ISSUE THREAD

**Issue by Jonty800** [vercel/next.js#34719]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.17.3
      pnpm: 6.32.1
    Relevant packages:
      next: 12.1.1-canary.1
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Android WebView (latest)

### How are you deploying your application? (if relevant)

next start, heroku

### Describe the Bug

```
2022-02-23T12:08:23.561729+00:00 app[web.1]: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
2022-02-23T12:08:23.561732+00:00 app[web.1]: at ServerResponse.setHeader (_http_outgoing.js:533:3)
2022-02-23T12:08:23.561732+00:00 app[web.1]: at NodeNextResponse.setHeader (/app/node_modules/next/dist/server/base-http/node.js:56:19)
2022-02-23T12:08:23.561733+00:00 app[web.1]: at NodeNextResponse.redirect (/app/node_modules/next/dist/server/base-http/index.js:26:14)
2022-02-23T12:08:23.561733+00:00 app[web.1]: at handleRedirect (/app/node_modules/next/dist/server/base-server.js:801:17)
2022-02-23T12:08:23.561734+00:00 app[web.1]: at NextNodeServer.renderToResponseWithComponents (/app/node_modules/next/dist/server/base-server.js:1036:23)
2022-02-23T12:08:23.561734+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2022-02-23T12:08:23.561735+00:00 app[web.1]: at async NextNodeServer.renderToResponse (/app/node_modules/next/dist/server/base-server.js:1080:36)
2022-02-23T12:08:23.561735+00:00 app[web.1]: at async NextNodeServer.pipe (/app/node_modules/next/dist/server/base-server.js:623:25)
2022-02-23T12:08:23.561735+00:00 app[web.1]: at async Object.fn (/app/node_modules/next/dist/server/base-server.js:496:21)
2022-02-23T12:08:23.561736+00:00 app[web.1]: at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32) {
2022-02-23T12:08:23.561736+00:00 app[web.1]: code: 'ERR_INVALID_CHAR'
2022-02-23T12:08:23.561737+00:00 app[web.1]: }
```

### Expected Behavior

The URL params should be encoded to avoid this error

### To Reproduce

Use an Android WebView and set the URL to a NextJS webapp that contains these params: 
```{ name: '日本語', id: 'qbssXqRA3Rinm7zGaTPU', userId: '10584' }```

Alternatively, use my URL:
```https://events-nextjs-app.herokuapp.com/event?id=qbssXqRA3Rinm7zGaTPU&name=日本語&userId=10584```

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
