### ISSUE TITLE
unstable_revalidate errors when returning notFound: true 

### ISSUE THREAD

**Issue by musme** [vercel/next.js#34809]
### What is the improvement or update you wish to see?

Please, describe in the documentation how to remove a page that returns 404.

### Is there any context that might help us understand?

Suppose i have the page /pages/post/[slug].tsx with

getStaticProps
```
export const getStaticProps: GetStaticProps = async ({ params }) => {
  let slug = params.slug;
  const post = await getPostFromWordpress(slug);
  if (!post) {
    return {
      notFound: true
    };
  }
  return {
    props: {
      post
    }
  };
};
```
and getStaticPaths
```
export const getStaticPaths: GetStaticPaths = async () => {
  const posts = await getPostFromWordpress();

  return {
    paths: posts .map(post => `/post/${post.slug}`) || [],
    fallback: 'blocking'
  };
};
```

And also i have an api route: /api/wordpress/revalidate:

```
export default async function handler(req, res) {

  if (req.query.secret !== process.env.MY_SECRET_TOKEN) {
    return res.status(401).json({ message: 'Invalid token' })
  }

  try {
    await res.unstable_revalidate(`/post/${req.query.slug}`)
    return res.json({ revalidated: true })
  } catch (err) {
    return res.status(500).send(err.message)
  }
}
```

From client side i can click "Delete post". After clicking the button, the post is deleted in Wordpress.
When I delete a post in Wordpress I call this api route /api/wordpress/revalidate?secret=<secret>&slug=some_slug, but I am getting an error "Failed to revalidate /post/some_slug".

This happens because {notFound: true } is returned from getStaticProps

https://github.com/vercel/next.js/blob/3d5dd58251a9ffd47741a7c81061fc71a9246621/packages/next/server/api-utils/node.ts#L310-L324

and res.ok = false

Please, describe in the documentation how to delete /pages/post/some_slug?

### Does the docs page already exist? Please link to it.

https://nextjs.org/blog/next-12-1#on-demand-incremental-static-regeneration-beta

**Comment by ijjk** [comment]
Hi, this looks like a bug as we shouldn't be considering returning `notFound: true` during a revalidate an error as this is valid, thanks for reporting this!

**Comment by musme** [comment]
>

**Comment by musme** [comment]
Thanks 👍

**Comment by ramiel** [comment]
I checked version `12.1.1-canary.6` and revalidation is still not working. For me it constantly crash with no clear indication of why

```
2022-03-03T11:19:34.587Z	8f3d7a9a-33aa-44db-91fc-5b1703c0cdd2	ERROR	Error: Failed to revalidate /site1
    at unstable_revalidate (/var/task/sites/live/node_modules/next/dist/server/api-utils/node.js:236:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async handler (/var/task/sites/live/.next/server/pages/api/revalidate.js:24:9)
    at async Object.apiResolver (/var/task/sites/live/node_modules/next/dist/server/api-utils/node.js:186:9)
    at async NextNodeServer.runApi (/var/task/sites/live/node_modules/next/dist/server/next-server.js:388:9)
    at async Object.fn (/var/task/sites/live/node_modules/next/dist/server/base-server.js:485:37)
    at async Router.execute (/var/task/sites/live/node_modules/next/dist/server/router.js:234:32)
    at async NextNodeServer.run (/var/task/sites/live/node_modules/next/dist/server/base-server.js:597:29)
    at async NextNodeServer.handleRequest (/var/task/sites/live/node_modules/next/dist/server/base-server.js:304:20)
    at async Server.<anonymous> (/var/task/sites/live/___next_launcher.js:32:9)
```

Can I help somehow?

**Comment by ijjk** [comment]
@ramiel is this specifically not working when revalidating and returning `notFound: true` or are you seeing this error for all cases? This issue is specific to the `notFound: true` case which is being tested now.

**Comment by ijjk** [comment]
@ramiel I think your issue is more likely related to https://github.com/vercel/next.js/issues/34874

**Comment by ramiel** [comment]
Ok, because this definitely doesn't happen to me on localhost (dev or production mode), but this definitely happens on production on vercel. I'll monitor that issue, thanks. But just to understand: do you know there's a problem in some configurations/hosts?
