### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by abhinavkumar940** [vercel/next.js#34844]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.4
      react: 17.0.2
      react-dom: 17.0.2

```

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

```
2022-02-26T12:05:22.236Z	3b3580d4-559f-4f37-a322-c67420fc0f0f	ERROR	Error: Cannot find module '/var/task/node_modules/next/dist/server/next.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.5017 (/var/task/.next/server/pages/api/subscribe.js:23:39)
    at __webpack_require__ (/var/task/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/api/subscribe.js:73:39)
    at /var/task/.next/server/pages/api/subscribe.js:74:28 {
  code: 'MODULE_NOT_FOUND',
  path: '/var/task/node_modules/next/package.json',
  requestPath: 'next'
}
RequestId: 3b3580d4-559f-4f37-a322-c67420fc0f0f Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Expected Behavior

  The serverless function should execute successfully

### To Reproduce

Call an API route

**Comment by balazsorban44** [comment]
Could you please provide a reproduction

**Comment by abhinavkumar940** [comment]
That's the problem @balazsorban44, it works fine on my local env. Even when I run it in PROD mode. But when I push that to vercel, only then I see this issue.

**Comment by balazsorban44** [comment]
That's fine, if you can share a reproduction, I can deploy it myself. I'll need to verify the error myself so we can look more into this.

Are you maybe using `type: "module"` at your top-level `package.json`?

**Comment by abhinavkumar940** [comment]
I have already checked for that but with no luck. Here is a minimal version 

https://github.com/abhinavkumar940/nextjs-issue-reproduction

But weirdly the minimal version works on vercel, the original version doesn't. Although they both share the same package.json file.

**Comment by abhinavkumar940** [comment]
Okay, was able to solve it but I have no idea what or how. I had this 

```
import { NextApiRequest, NextApiResponse } from "next";
```

in my serverless function file `/pages/api/subscribe.js` (yes, a `.js` file)

I removed it and then it started working fine.
