### ISSUE TITLE
res.hasHeader is not a function

### ISSUE THREAD

**Issue by mandar1jn** [vercel/next.js#34929]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: win32
      Arch: x64      
      Version: Windows 10 Home
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.4
      react: 17.0.2
      react-dom: 17.0.2
```

### How are you deploying your application? (if relevant)

next start and next dev

### Describe the Bug

Some function on the res object throws the following error:
```
TypeError: res.hasHeader is not a function
    at Object.setRevalidateHeaders (C:\Users\Erik de Vlaam\Desktop\personal-website\node_modules\next\dist\server\send-payload\revalidate-headers.js:8:37)
    at Object.sendRenderResult (C:\Users\Erik de Vlaam\Desktop\personal-website\node_modules\next\dist\server\send-payload\index.js:43:33)
```

### Expected Behavior

I guess it is expected for the functions to just work(?) and not throw an error

### To Reproduce

The following page should be good to reproduce. The folder structure should be easy to resolve from this code.

```
import fs from "fs";
import { GetServerSideProps } from "next";
import path from "path";
import { FunctionComponent } from "react";

export const getServerSideProps: GetServerSideProps = async (context) => {

	const id = context.params!.id!.toString();

	const filePath = path.join("images", id);

	if(!fs.existsSync(filePath))
	{
		return {
			notFound: true
		}
	}

	context.res.setHeader("content-type", "image/png");
	context.res.write(fs.readFileSync(path.join("images", id)));
	context.res.end();

	return {
		props: {

		}
	}

}

const Images: FunctionComponent = () =>
{
	return <></>
}

export default Images;"
```

**Comment by balazsorban44** [comment]
I could not reproduce this given your code sample, everything works fine. Could you create a small repository that reproduces the issue?

**Comment by mandar1jn** [comment]
https://github.com/mandar1jn/personal-website
This should do the trick. Visiting the paths `/blog/how-to-dynimically-serve-images-with-next-js` and `/images/test.png` should throw the error

**Comment by alexrabin** [comment]
I get this error in the console when I try to revalidate a slugUrl that doesn't exist. The errors shows this in the console but the revalidate handler returns a 200 response.

```
TypeError: this._res.hasHeader is not a function
    at NodeNextResponse.hasHeader (C:\Git\MainWebsiteUI\node_modules\next\dist\server\base-http\node.js:70:26)
    at Object.setRevalidateHeaders (C:\Git\MainWebsiteUI\node_modules\next\dist\server\send-payload\revalidate-headers.js:8:37) 
    at NextNodeServer.renderToResponseWithComponents (C:\Git\MainWebsiteUI\node_modules\next\dist\server\base-server.js:1074:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NextNodeServer.renderPageComponent (C:\Git\MainWebsiteUI\node_modules\next\dist\server\base-server.js:1130:24)     
    at async NextNodeServer.renderToResponse (C:\Git\MainWebsiteUI\node_modules\next\dist\server\base-server.js:1159:36)        
    at async NextNodeServer.pipe (C:\Git\MainWebsiteUI\node_modules\next\dist\server\base-server.js:638:25)
    at async Object.fn (C:\Git\MainWebsiteUI\node_modules\next\dist\server\base-server.js:505:21)
    at async Router.execute (C:\Git\MainWebsiteUI\node_modules\next\dist\server\router.js:213:36)
    at async NextNodeServer.run (C:\Git\MainWebsiteUI\node_modules\next\dist\server\base-server.js:616:29)
```

**Comment by bejarano-tech** [comment]
After researching about this i can reproduce the error when fallback is false on getStaticPaths.
