### ISSUE TITLE
Values containing '!' chars in serverRuntimeConfig cause serverless builds to fail

### ISSUE THREAD

**Issue by jim-emed** [vercel/next.js#35269]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.10
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

The following next.config.js file fails to build when running `npm run build`:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  target: "serverless",
  serverRuntimeConfig: {
    SOME_KEY: "bad!value"
  }
}

module.exports = nextConfig
```

The error output is as follows:

```
info  - Checking validity of types
info  - Creating an optimized production build
Failed to compile.

    HookWebpackError: Cannot read property 'slice' of undefined
at makeWebpackError (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:41664:9)
at /Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:25354:12
at eval (eval at create (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:36:1)
  at fn (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:22775:17)
  at Hook.eval [as callAsync] (eval at create (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:34:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:140148:14)
    at cont (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:25351:34)
    at /Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:25399:10
    at symbolIterator (/Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:14443)
    at done (/Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:14823)
    -- inner error --
    TypeError: Cannot read property 'slice' of undefined
    at PagesManifestPlugin.createAssets (/Users/Downloads/bug-test/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:33:51)
    at /Users/Downloads/bug-test/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:47:22
    at fn (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:22773:10)
    at Hook.eval [as callAsync] (eval at create (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:34:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:140148:14)
      at cont (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:25351:34)
      at /Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:25399:10
      at symbolIterator (/Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:14443)
      at done (/Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:14823)
      at /Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:9429
      caused by plugins in Compilation.hooks.processAssets
      TypeError: Cannot read property 'slice' of undefined
      at PagesManifestPlugin.createAssets (/Users/Downloads/bug-test/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:33:51)
      at /Users/Downloads/bug-test/node_modules/next/dist/build/webpack/plugins/pages-manifest-plugin.js:47:22
      at fn (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:22773:10)
      at Hook.eval [as callAsync] (eval at create (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:140346:10), <anonymous>:34:1)
        at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:140148:14)
        at cont (/Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:25351:34)
        at /Users/Downloads/bug-test/node_modules/next/dist/compiled/webpack/bundle5.js:25399:10
        at symbolIterator (/Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:14443)
        at done (/Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:14823)
        at /Users/Downloads/bug-test/node_modules/next/dist/compiled/neo-async/async.js:1:9429
```

### Expected Behavior

The build should not error out.

### To Reproduce

A combination of using a `!` character in a `serverRuntimeConfig` value **and** `target: "serverless"` will cause a failure.
 
Conversely, the following configs will build just fine:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  target: "serverless",
  serverRuntimeConfig: {
    SOME_KEY: "good_value"
  }
}

module.exports = nextConfig
```

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  serverRuntimeConfig: {
    SOME_KEY: "bad!value"
  }
}

module.exports = nextConfig
```

**Comment by balazsorban44** [comment]
Keep in mind that `target: "serverless"` is a deprecated feature and will be completely removed in the next major release #34476

https://nextjs.org/blog/next-12#output-file-tracing

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think this was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
