### ISSUE TITLE
Ability to format nextjs logs and extend them with meta

### ISSUE THREAD

**Issue by kristijorgji** [vercel/next.js#35331]
### Describe the feature you'd like to request

Hi, right now after `next build` when we start next server with `next start` we see output logs only if error happens.

I would like to be able to have more control here over
1. log format. Example print json output instead of line by line example that i copy below
```
Error: {"size":0,"timeout":0}
at getStaticProps (/usr/src/app/.next/server/pages/post/[id].js:3576:11)
at runMicrotasks (<anonymous>)
```
2. Ability to add meta/context to nextjs logs after specifying a json format. Example enrich all logs with request url as well, or with custom tracing field whatever developer wants.
In that case above log would look like {"message": "some message here", "url": "domain.com/someurl", "appVersion":"something", ...othermeta}

### Describe the solution you'd like

As described in feature request I want to be able to do those actions.
I think one way maybe can be configurations in next.config.js but as I don't know nextjs internals well I am open to any solution that is best fit

### Describe alternatives you've considered

Unfortunately nothing because is impossible currently to add meta and format next output to json.

**Comment by kristijorgji** [comment]
Another example that is real life causing trouble for me to understand where and how error happens.
The below are logs straight from my `web` docker container.

I don't know where that error happens or in what context.
In previous php apps for example, I added to all logs MDC context requestId coming from frontend, also url and was easy to understand and fix issues.

```
web | TypeError: Cannot read property 'session' of undefined
web |     at /usr/src/app/.next/server/chunks/6606.js:1005:23
web |     at runMicrotasks (<anonymous>)
web |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
web |     at async Object.apiResolver (/usr/src/app/node_modules/next/dist/server/api-utils/node.js:182:9)
web |     at async NextNodeServer.runApi (/usr/src/app/node_modules/next/dist/server/next-server.js:386:9)
web |     at async Object.fn (/usr/src/app/node_modules/next/dist/server/base-server.js:488:37)
web |     at async applyCheckTrue (/usr/src/app/node_modules/next/dist/server/router.js:110:32)
web |     at async Router.execute (/usr/src/app/node_modules/next/dist/server/router.js:250:25)
web |     at async NextNodeServer.run (/usr/src/app/node_modules/next/dist/server/base-server.js:600:29)
web |     at async NextNodeServer.handleRequest (/usr/src/app/node_modules/next/dist/server/base-server.js:30
```

If only I could change above log output to json and add `requestId: valueIsendFromWebHttpClient` platform: `web|android|etc` `url` and other context then would be fantastic and proplery how a framework should work to allow proper monitoring.

I am quite confidend that you guys can implement this easily hopefully this post gets visibility.
