### ISSUE TITLE
Custom server `nextApp.prepare()` hides stack traces (webpack, ts-loader)

### ISSUE THREAD

**Issue by stevemarksd** [vercel/next.js#35476]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0:
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.15
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

I added webpack to my dev build for my custom server to be able to import ESM modules.

 - So I have a script to start webpack watch: `cross-env NODE_ENV=development ts-node --project ./tsconfig.build.json ./build/webpack.ts`
 - Then nodemon watches built file: `server.dev.js` and restarts when webpack generates new code

The problem now is that if I do the following

```
nextApp.prepare().then(async () => {
  const e = new Error(`>>>`)
  throw e;
```

I see:

```
error - unhandledRejection: Error: >>>
```

If I change to

```
waitMs(1).then(async () => {
  const e = new Error(`>>>`)
  throw e;
```

I see:

```
Error: >>>
    at /.dev/webpack:/server/index.ts:74:13
    at step (/.dev/server.dev.js:129638:23)
```

So basically using `nextjs prepare` removes stack traces.

### Expected Behavior

I expect to see the error stack.

### To Reproduce

tsconfig.server.json:
```
{
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "ES5",
    "lib": [
      "dom",
      "es2017",
      "es2019"
    ],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "esModuleInterop": true,
    "downlevelIteration": true,
    "jsx": "react-jsx"
  },
  "include": [
    "server/**/*.ts"
  ]
}
```

webpack config:

```
{
  "mode": "development",
  "watch": true,
  "entry": "./server/index.ts",
  "devtool": "source-map",
  "target": "node",
  "watchOptions": {
    "ignored": [
      "node_modules/**"
    ]
  },
  "module": {
    "rules": [
      {
        "test": {},
        "use": [
          {
            "loader": "ts-loader",
            "options": {
              "configFile": "/tsconfig.server.json",
              "logInfoToStdOut": true
            }
          }
        ],
        "exclude": {}
      }
    ]
  },
  "plugins": [
    {
      "definitions": {
        "process.env.NODE_ENV": "\"development\""
      }
    }
  ],
  "externals": {
  },
  "externalsPresets": {
    "node": true
  },
  "resolve": {
    "extensions": [
      ".tsx",
      ".ts",
      ".js"
    ]
  },
  "output": {
    "path": "/.dev",
    "filename": "server.dev.js"
  }
}

```

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
