### ISSUE TITLE
SWC Minify breaks with edge runtime & concurrent features

### ISSUE THREAD

**Issue by HurricanKai** [vercel/next.js#35505]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.1
      npm: 8.3.0
      Yarn: N/A
      pnpm: 6.32.2
    Relevant packages:
      next: 12.1.1-canary.15
      react: 18.0.0-rc.2
      react-dom: 18.0.0-rc.2

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

I'm testing Server Components / Concurrent Features / Edge Runtime / React 18 right now and get a weird bug when minifying, everything works fine without minifactions.
For reference I'm using relay & relay-next

The error is:
```
TypeError: e[n] is not a function
    at __nccwpck_require__ (C:\league.ml\webapp\.next\server\chunks\68.js:8:540858)
    at C:\league.ml\webapp\.next\server\chunks\68.js:8:541006
    at Object../node_modules/.pnpm/next@12.1.1-canary.15_bc22c48adf1a4e34a005159413cd72b5/node_modules/next/dist/compiled/querystring-es3/index.js (C:\league.ml\webapp\.next\server\chunks\68.js:8:541094)
    at a (C:\league.ml\webapp\.next\server\middleware-ssr-runtime.js:1:128)
    at Object../node_modules/.pnpm/next@12.1.1-canary.15_bc22c48adf1a4e34a005159413cd72b5/node_modules/next/dist/server/base-server.js (C:\league.ml\webapp\.next\server\chunks\68.js:8:698013)
    at a (C:\league.ml\webapp\.next\server\middleware-ssr-runtime.js:1:128)
    at Object../node_modules/.pnpm/next@12.1.1-canary.15_bc22c48adf1a4e34a005159413cd72b5/node_modules/next/dist/server/web-server.js (C:\league.ml\webapp\.next\server\chunks\68.js:8:796408)
    at a (C:\league.ml\webapp\.next\server\middleware-ssr-runtime.js:1:128)
    at Object../node_modules/.pnpm/next@12.1.1-canary.15_bc22c48adf1a4e34a005159413cd72b5/node_modules/next/dist/build/webpack/loaders/next-middleware-ssr-loader/render.js (C:\league.ml\webapp\.next\server\chunks\68.js:8:103316)
    at a (C:\league.ml\webapp\.next\server\middleware-ssr-runtime.js:1:128)
```
+ a super long line of code printed above.
[Full Error](https://github.com/vercel/next.js/files/8319060/stack.txt)
This happens on the first page load on both the server and the client

### Expected Behavior

Page normally loading. This works fine without minification 

### To Reproduce

Not sure. I'm attaching both the .next folder with minification and without (including trace). If helpful I can see to attach the project where this happens.

[Without Minification](https://drive.google.com/file/d/1jVMX8cesP1wEpwQNEutlTAS_M7AcpLe0/view?usp=sharing)
[With Minification](https://drive.google.com/file/d/1EA0fTaNDcLepd2WduJ41QpNzlfeAAIns/view?usp=sharing)

**Comment by kdy1** [comment]
I investigated (https://github.com/swc-project/swc/pull/4273), and I think the cause is

 - identifiers are reused by terser, with the `e` being the most common one.
 - AST optimizer does not care about variable scoping, thanks to the special trick swc uses
   - (This is common to almost all codes of swc. We use a very different approach for scoping)
 - the trick requires name mangler, but it’s disabled because eval is used
 - the top-level `e` is overridden by one of other `e`s


So making the AST optimizer aware of the scope should fix it.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
