### ISSUE TITLE
router.asPath causes an Unhandled Runtime Error when on custom 404 page

### ISSUE THREAD

**Issue by james-work-account** [vercel/next.js#36073]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Brave Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (x86_64)

### Describe the Bug

https://github.com/james-work-account/aspath-broken is the next.js default app installed through `npx create-next-app@latest --typescript`, with a custom 404 page that tells the user what route they're on using `router.asPath`.

When running locally through `yarn run dev` and navigating to a page which doesn't exist (e.g. `/about`), the following is logged to my browser console (with corresponding build errors in the browser):

<details closed>

<summary>Click to see errors</summary>

```
GET http://localhost:3002/about 404 (Not Found)

next-dev.js?3515:25 Warning: Text content did not match. Server: "/404" Client: "/about"
    at h1
    at div
    at Custom404 (webpack-internal:///./pages/404.tsx:15:72)
    at MyApp (webpack-internal:///./pages/_app.tsx:37:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:825:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:949:27) 

See more info here: https://nextjs.org/docs/messages/react-hydration-error
window.console.error @ next-dev.js?3515:25
printWarning @ react-dom.development.js?ac89:86
error @ react-dom.development.js?ac89:60
checkForUnmatchedText @ react-dom.development.js?ac89:9610
didNotMatchHydratedTextInstance @ react-dom.development.js?ac89:11337
prepareToHydrateHostTextInstance @ react-dom.development.js?ac89:14441
completeWork @ react-dom.development.js?ac89:19407
completeUnitOfWork @ react-dom.development.js?ac89:26431
performUnitOfWork @ react-dom.development.js?ac89:26403
workLoopSync @ react-dom.development.js?ac89:26303
renderRootSync @ react-dom.development.js?ac89:26271
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25577
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533

next-dev.js?3515:25 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>.
window.console.error @ next-dev.js?3515:25
printWarning @ react-dom.development.js?ac89:86
error @ react-dom.development.js?ac89:60
errorHydratingContainer @ react-dom.development.js?ac89:11413
recoverFromConcurrentError @ react-dom.development.js?ac89:25685
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25589
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533

react-dom.development.js?ac89:9618 Uncaught Error: Text content does not match server-rendered HTML.
    at checkForUnmatchedText (react-dom.development.js?ac89:9618:1)
    at didNotMatchHydratedTextInstance (react-dom.development.js?ac89:11337:1)
    at prepareToHydrateHostTextInstance (react-dom.development.js?ac89:14441:1)
    at completeWork (react-dom.development.js?ac89:19407:1)
    at completeUnitOfWork (react-dom.development.js?ac89:26431:1)
    at performUnitOfWork (react-dom.development.js?ac89:26403:1)
    at workLoopSync (react-dom.development.js?ac89:26303:1)
    at renderRootSync (react-dom.development.js?ac89:26271:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25577:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
checkForUnmatchedText @ react-dom.development.js?ac89:9618
didNotMatchHydratedTextInstance @ react-dom.development.js?ac89:11337
prepareToHydrateHostTextInstance @ react-dom.development.js?ac89:14441
completeWork @ react-dom.development.js?ac89:19407
completeUnitOfWork @ react-dom.development.js?ac89:26431
performUnitOfWork @ react-dom.development.js?ac89:26403
workLoopSync @ react-dom.development.js?ac89:26303
renderRootSync @ react-dom.development.js?ac89:26271
performConcurrentWorkOnRoot @ react-dom.development.js?ac89:25577
workLoop @ scheduler.development.js?bcd2:266
flushWork @ scheduler.development.js?bcd2:239
performWorkUntilDeadline @ scheduler.development.js?bcd2:533

react-dom.development.js?ac89:20583 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js?ac89:20583:1)
    at beginWork (react-dom.development.js?ac89:22370:1)
    at beginWork$1 (react-dom.development.js?ac89:27219:1)
    at performUnitOfWork (react-dom.development.js?ac89:26392:1)
    at workLoopSync (react-dom.development.js?ac89:26303:1)
    at renderRootSync (react-dom.development.js?ac89:26271:1)
    at recoverFromConcurrentError (react-dom.development.js?ac89:25689:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25589:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
```

</details>

There seems to be a mismatch between what is sent on the server and what is rendered on the page when using `router.asPath`.

React 17 doesn't actually error when using `router.asPath` on a custom 404 page, although it does log a warning to the console. React 18 does error.

### Expected Behavior

No errors are logged to the console and no "Unhandled Runtime Error" messages are logged to the browser due to a mismatch between server & client text content.

When running https://github.com/james-work-account/aspath-broken, navigating to a page which doesn't exist should render the page normally rather than erroring.

### To Reproduce

- `git clone https://github.com/james-work-account/aspath-broken`
- `cd aspath-broken`
- `yarn install`
- `yarn run dev`
- Open the Next app on a route that doesn't exist (e.g. `/about`)

**Comment by balazsorban44** [comment]
This is expected. You should not use `router.asPath` in the render tree, until `router.isReady === true` https://github.com/vercel/next.js/issues/34197#issuecomment-1035335803.

See: https://nextjs.org/docs/api-reference/next/router#router-object
