### ISSUE TITLE
node server/ next dev is broken but app running well on next build.

### ISSUE THREAD

**Issue by Biboswan** [vercel/next.js#36320]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

next: 12.0.4/12.1.4/12.1.5/12/1.6-canary.4"

next info

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.4
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Version 99.0.4844.84 (Official Build) (arm64)

### Describe the Bug
```
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /Users/biboswanroy/development/feats/applications/desktop-web/.babelrc.js
error - ./node_modules/next/dist/client/dev/error-overlay/hot-dev-client.js
TypeError: Cannot read properties of undefined (reading 'value')
Ready on http://localhost:5001/
```
Then when visiting a page:

```
wait  - compiling /_error (client and server)...
error - ./node_modules/next/dist/client/dev/error-overlay/hot-dev-client.js
TypeError: Cannot read properties of undefined (reading 'value')'
error - Error: Cannot find module '/Users/biboswanroy/development/feats/applications/desktop-web/.next/fallback-build-manifest.json'
Require stack:
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/load-components.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/utils.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/output/store.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/output/index.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/cli/next-dev.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/bin/next
Error: Cannot find module '/Users/biboswanroy/development/feats/applications/desktop-web/.next/fallback-build-manifest.json'
Require stack:
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/load-components.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/utils.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/output/store.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/output/index.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/cli/next-dev.js
- /Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.loadDefaultErrorComponents (/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/dev/next-dev-server.js:691:43)
    at async DevServer.renderErrorToResponse (/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/base-server.js:1194:40)
    at async pipe.req.req (/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/base-server.js:1138:30)
    at async DevServer.pipe (/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/base-server.js:605:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/server/load-components.js',
    '/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/utils.js',
    '/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/output/store.js',
    '/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/build/output/index.js',
    '/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/cli/next-dev.js',
    '/Users/biboswanroy/development/feats/applications/desktop-web/node_modules/next/dist/bin/next'
  ]
```

Posted here
https://github.com/vercel/next.js/discussions/35948

Maybe similar
https://github.com/vercel/next.js/issues/32115

### Expected Behavior

Running the dev server without any such errors

### To Reproduce

MVP
```
git clone git@github.com:Biboswan/mvp-nexterror.git
npm install --no-audit --legacy-peer-deps
$(npm bin)/next dev
```
In the MVP, I just noticed before adding the babel things app compiled successfully and the page ran without errors.

**Comment by balazsorban44** [comment]
This is not a Next.js bug.

https://github.com/peteringram0/babel-plugin-console-source/blob/cd6ac3e382cfa3bf5dd9c47ee63ee7bae6d3876b/index.js#L30

This line assumes that any `console` method invocation will have an argument, while `next dev` invokes `console.clear()` and thus the plugin will throw an error. You could reach out to the plugin author to fix the issue by correcting the condition to something like `if(path.node.arguments[0] && path.node.arguments[0].value !== value) {`
