### ISSUE TITLE
redirect header conflict at getInitialProps and getServerSideProps

### ISSUE THREAD

**Issue by yfhui** [vercel/next.js#36428]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022
    Binaries:
      Node: 16.9.1
      npm: 7.21.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.6
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 100.0.4896.88

### How are you deploying your application? (if relevant)

localhost

### Describe the Bug

if header is set at getInitialProps in _app.js, then other redirect feature in getServerSideProps of other pages will trigger an error of `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

e.g. 
in getInitialProps of _app.js:

```js
MyApp.getInitialProps = async (appContext) => {
    appContext?.ctx?.res?.writeHead?.(302, { Location: `/hello.html` });
    appContext?.ctx?.res?.end?.();
    return {};
}
```

in `getServerSideProps` of some page:
```js
export const getServerSideProps = async (ctx) =>{
    return {
        notFound: true,
    };
}
```

Then this error is logged when access the page
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at setHeadersFromObject (/home/daniel/nextjs-redirect-error/node_modules/next/dist/compiled/compression/index.js:46:680)
    at ServerResponse.setWriteHeadHeaders (/home/daniel/nextjs-redirect-error/node_modules/next/dist/compiled/compression/index.js:46:914)
    at ServerResponse.writeHead (/home/daniel/nextjs-redirect-error/node_modules/next/dist/compiled/compression/index.js:46:121)
    at Function.MyApp.getInitialProps (webpack-internal:///./pages/_app.js:27:38)
    at Object.loadGetInitialProps (/home/daniel/nextjs-redirect-error/node_modules/next/dist/shared/lib/utils.js:65:29)
    at Object.renderToHTML (/home/daniel/nextjs-redirect-error/node_modules/next/dist/server/render.js:480:32)
    at async doRender (/home/daniel/nextjs-redirect-error/node_modules/next/dist/server/base-server.js:894:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/home/daniel/nextjs-redirect-error/node_modules/next/dist/server/base-server.js:999:28) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

### Expected Behavior

The redirection of getServerSideProps or other server side functions should be skipped if the header is set.

### To Reproduce

I have pushed a quick demo at github, you can reproduce the issue yourself

https://github.com/yfhui/nextjs-redirect-error

**Comment by JanKaifer** [comment]
Hi, `getInitialProps` is a legacy for quite a while.
We recommend using `getServerSideProps` only.
