### ISSUE TITLE
`Link` and `Image` don't work with server components.

### ISSUE THREAD

**Issue by sanny-io** [vercel/next.js#36471]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

      Platform: win32
      Arch: x64
      Version: Windows 10 Home (actually Windows 11)
      Node: 16.14.1

      npm: 8.7.0
      Yarn: N/A
      pnpm: 6.32.10

      next: 12.1.6-canary.7
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Edge Version 100.0.1185.50 (Official build) (64-bit)

### How are you deploying your application? (if relevant)

`next dev`

### Describe the Bug

Using either `Link` or `Image` with server components on a page gives the following error:

![](https://i.imgur.com/PGU3w8A.png)

> TypeError: Cannot read properties of undefined (reading '')
    at resolveModuleMetaData (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:193:42)
    at resolveModelToJSON (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:1378:30)
    at Array.toJSON (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:979:14)
    at stringify (<anonymous>)
    at processModelChunk (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:165:14)
    at retrySegment (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:1563:26)
    at performWork (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:1591:7)
    at C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:1678:12
    at scheduleWork (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:59:3)
    at startWork (C:\Users\sanny\Documents\Projects\next-test\node_modules\.pnpm\next@12.1.6-canary.7_react-dom@18.0.0+react@18.0.0\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:1677:3)

### Expected Behavior

The components should render with no error.

### To Reproduce

1. Clone https://github.com/sanny-io/next-test
2. Run `next dev` and visit http://localhost:3000

**Comment by huozhi** [comment]
Can you try pnpm 6.32.10 it works for me when I upgrad?

**Comment by balazsorban44** [comment]
Could you try to pinpoint which `next` version broke, maybe?

**Comment by sanny-io** [comment]
@balazsorban44 since `next@12.0.0` and `react@18.0.0-rc.2` and `react-dom@18.0.0-rc.2`

The 18.0.0-rc.2 react packages are the earliest I can replicate the issue without getting a whole bunch of other errors I don't believe are related since they occur regardless of server components being enabled.

**Comment by balazsorban44** [comment]
Hi, since Next.js 13, server components are only supported in the `app/` directory. Both `Link` and `Image` should work there.
