### ISSUE TITLE
EPERM: operation not permitted - after upgrading react and next

### ISSUE THREAD

**Issue by omerfaran** [vercel/next.js#36645]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
"next": "^12.1.6",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
```

### Describe the Bug

I follow this guide to upgrade my project (react and nextjs):
https://nextjs.org/docs/upgrading

The upgrade is successful, then when I start nextjs OR my server it's working fine, however when I start the other one (server or nextjs), I get this error:

e```
vents.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open 'C:\Users\[myPath]\.next\trace'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:390:14
    at FSReqCallback.oncomplete (fs.js:163:23) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\[myPath]\\.next\\trace'
```
  
  Then when trying to delete my .next library on Windows, it cannot delete this trace file, then after some time it does.
  
  What could be causing this problem with the trace file? I tried many varitations of deleting my next folder, and running npm install, but the problem always comes back
  
 What should I try? Thank you very much in advance everyone
  

### Expected Behavior

starting next client and server without this issue

### To Reproduce

upgrade project from next 10 and react 16

**Comment by JanKaifer** [comment]
Hey, could you try creating minimal repo in next10 and then try to upgrade that? To make sure that it's not caused by an issue with your setup.

Sorry for taking so long to respond.
