### ISSUE TITLE
Unable to build: Failed to transform one off global selector after upgrade (versions afected and tested 12.0.8-canary.3 to 12.1.6)

### ISSUE THREAD

**Issue by gil-obradors** [vercel/next.js#36880]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

next info not available yet

Rocky Linux release 8.5 (Green Obsidian)
Node version v16.13.1
Npm version 8.1.2

package info
```
├── @szhsin/react-menu@2.3.0
├── bootstrap@4.6.0
├── eslint-config-next@12.0.8
├── eslint@8.6.0
├── firebase-admin@10.0.2
├── firebase@8.6.1
├── ip-range-check@0.2.0
├── jquery@3.6.0
├── js-cookie@3.0.1
├── latest-version@6.0.0
├── leaflet-contextmenu@1.4.0
├── leaflet-defaulticon-compatibility@0.1.1
├── leaflet-draw@1.0.4
├── leaflet-geosearch@3.6.0
├── leaflet@1.7.1
├── mongoose@6.1.6
├── next@12.0.8-canary.3
├── nodemailer@6.6.3
├── popper.js@1.16.1
├── pusher-js@7.0.3
├── pusher@5.0.0
├── react-bootstrap@1.6.3
├── react-dom@17.0.2
├── react-leaflet-custom-control@1.2.2
├── react-leaflet-draw@0.19.8
├── react-leaflet@3.2.2
├── react-select@5.2.1
├── react-toastify@8.0.2
├── react@17.0.2
└── swr@1.0.1
```

### What browser are you using? (if relevant)

not rellevant

### How are you deploying your application? (if relevant)

npm run build

### Describe the Bug

I'm on next@12.0.3
I can build successfully up to 12.0.8-canary2

After uprgading from [12.0.8-canary3](https://github.com/vercel/next.js/releases/tag/v12.0.8-canary.3) to latest the build fails:  `Error: error: Failed to transform one off global selector`

Here an example of One off global selectors affected :
```
340 |                 tbody > :global(tr: first-child) {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^
```

build log:
```
info  - Creating an optimized production build .thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(3516), hi: BytePos(3517), ctxt: #0 }, InvalidSelector) }', crates/core/src/styled_jsx/transform_css.rs:271:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(14837), hi: BytePos(14838), ctxt: #0 }, InvalidSelector) }', crates/core/src/styled_jsx/transform_css.rs:271:22
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(27420), hi: BytePos(27421), ctxt: #0 }, InvalidSelector) }', crates/core/src/styled_jsx/transform_css.rs:271:22
thread '<unnamed>' panicked at 'not yet implemented: nth', crates/core/src/styled_jsx/transform_css.rs:238:65
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(54983), hi: BytePos(54984), ctxt: #0 }, InvalidSelector) }', crates/core/src/styled_jsx/transform_css.rs:271:22
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(68183), hi: BytePos(68184), ctxt: #0 }, InvalidSelector) }', crates/core/src/styled_jsx/transform_css.rs:271:22
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(82250), hi: BytePos(82251), ctxt: #0 }, InvalidSelector) }', crates/core/src/styled_jsx/transform_css.rs:271:22
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: (Span { lo: BytePos(86647), hi: BytePos(86648), ctxt: #0 }, InvalidSelector) }', crates/core/src/styled_jsx/transform_css.rs:271:22
info  - Creating an optimized production build
Failed to compile.
```

Rust back trace:

```
Error: error: Failed to transform one off global selector

    |
340 |                 tbody > :global(tr: first-child) {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^

Stack backtrace:
   0: anyhow::kind::Adhoc::new
   1: swc::try_with_handler
   2: <next_swc_napi::transform::TransformTask as napi::task::Task>::compute
   3: napi::async_work::execute
   4: <unknown>
   5: start_thread
   6: __GI___clone

```

### Expected Behavior

Make build as from previous releases, if it's a rust transpiler bug.

### To Reproduce

Using selectors on off selectors. 
In this example, `:global(.popover-body)`, works.
The seconds fails: `  tbody > :global(tr: first-child) {`

```
<style jsx>{`
     :global(.popover-body) {
                    border-bottom: 1px #8a8a8a90 solid;
                    cursor: pointer;
                }
    tbody > :global(tr: first-child) {
                    border-top: 1px #8a8a8a90 solid;
                }
`}</style>

```

<sub>[PACK-2988](https://linear.app/vercel/issue/PACK-2988/unable-to-build-failed-to-transform-one-off-global-selector-after)</sub>

**Comment by balazsorban44** [comment]
Thanks. It looks like this was introduced in https://github.com/vercel/next.js/pull/32210 which updated SWC and seemed to be caused by SWC being stricter about whitespace https://github.com/vercel/next.js/pull/32297

**Comment by kdy1** [comment]
`tr: first-child` is invalid. It should be `tr first-child` or `tr > first-child`
