### ISSUE TITLE
Module not found from fresh install

### ISSUE THREAD

**Issue by tomasbruckner** [vercel/next.js#36939]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

Freshly installed Next.js app throws error MODULE_NOT_FOUND

### Expected Behavior

The application works

### To Reproduce

1. Run `npx create-next-app@latest`
```
What is your project named? ... nextdeletejs
Creating a new Next.js app in C:\.....\nextdeletejs.

Using npm.

Installing dependencies:
- react
- react-dom
- next


added 14 packages, and audited 15 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Installing devDependencies:
- eslint
- eslint-config-next


added 208 packages, and audited 223 packages in 4s

68 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Initialized a git repository.

Success! Created nextdeletejs at C:\....\nextdeletejs
Inside that directory, you can run several commands:

  npm run dev
    Starts the development server.

  npm run build
    Builds the app for production.

  npm start
    Runs the built app in production mode.

We suggest that you begin by typing:

  cd nextdeletejs
  npm run dev
```

2. cd nextdeletejs/
3. npm run dev

```> nextdeletejs@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
error - ./node_modules/next/dist/client/dev/amp-dev.js
Module not found: Can't resolve 'C:\...\nextdeletejs\node_modules\next\dist\compiled\regenerator-runtime\runtime.js' in 'C:\...\ud4d\nextdeletejs\node_modules\next\dist\client\dev'
```

4. When I try to go to localhost:3000
```
wait  - compiling /_error (client and server)...
wait  - compiling...
error - ./node_modules/next/dist/client/dev/amp-dev.js
Module not found: Can't resolve 'C:\....\nextdeletejs\node_modules\next\dist\compiled\regenerator-runtime\runtime.js' in 'C:\...\nextdeletejs\node_modules\next\dist\client\dev'
error - Error: Cannot find module 'C:\...\nextdeletejs\.next\fallback-build-manifest.json'
Require stack:
- C:\...\nextdeletejs\node_modules\next\dist\server\load-components.js
- C:\...\nextdeletejs\node_modules\next\dist\server\next-server.js
- C:\...\nextdeletejs\node_modules\next\dist\server\next.js
- C:\...\nextdeletejs\node_modules\next\dist\server\lib\start-server.js
- C:\...\nextdeletejs\node_modules\next\dist\cli\next-dev.js
- C:\...\nextdeletejs\node_modules\next\dist\bin\next
Error: Cannot find module 'C:\...\nextdeletejs\.next\fallback-build-manifest.json'
Require stack:
- C:\...\nextdeletejs\node_modules\next\dist\server\load-components.js
- C:\...\nextdeletejs\node_modules\next\dist\server\next-server.js
- C:\...\nextdeletejs\node_modules\next\dist\server\next.js
- C:\...\nextdeletejs\node_modules\next\dist\server\lib\start-server.js
- C:\...\nextdeletejs\node_modules\next\dist\cli\next-dev.js
- C:\...\nextdeletejs\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (C:\...\nextdeletejs\node_modules\next\dist\build\webpack\require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.loadDefaultErrorComponents (C:\...\nextdeletejs\node_modules\next\dist\server\load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (C:\...\nextdeletejs\node_modules\next\dist\server\dev\next-dev-server.js:696:43)
    at async DevServer.renderErrorToResponse (C:\...\nextdeletejs\node_modules\next\dist\server\base-server.js:1224:40)
    at async pipe.req.req (C:\...\nextdeletejs\node_modules\next\dist\server\base-server.js:1168:30)
    at async DevServer.pipe (C:\...\nextdeletejs\node_modules\next\dist\server\base-server.js:628:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\...\\nextdeletejs\\node_modules\\next\\dist\\server\\load-components.js',
    'C:\\...\\nextdeletejs\\node_modules\\next\\dist\\server\\next-server.js',
    'C:\\...\\nextdeletejs\\node_modules\\next\\dist\\server\\next.js',
    'C:\\...\\nextdeletejs\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'C:\\...\\nextdeletejs\\node_modules\\next\\dist\\cli\\next-dev.js',
    'C:\\...\\nextdeletejs\\node_modules\\next\\dist\\bin\\next'
  ]
}
```

**Comment by tomasbruckner** [comment]
Ok, so I investigated a little more and this error occurs if I have folder
```
~/workspace/foo/test
```

but when the folder is
```
~/workspace/test
```
it works fine.

In the first case, it cannot resolve the path
```
'C:\Users\tomas\workspacefoo\test\node_modules\next\dist\compiled\regenerator-runtime\runtime.js'
```

For some reason there is a missing slash in workspace and foo!

**Comment by NicolasMarafetti** [comment]
Hello, I had the same problem and I confirm this can occur because of folder names.
But this is not specific to "workspace" or "foo".

Working at -        D:\Programmation\Udemy\nextjs\cours-nextjs
Not working at - D:\Programmation\Udemy\udemy\cours-nextjs

**Comment by tomasbruckner** [comment]
it looks like duplicate of https://github.com/vercel/next.js/issues/36078

**Comment by arcreigh** [comment]
Looks like this also occurs when the drive is a network share. similar behavior where npm is unable to find amp-dev causing the build to fail.

**Comment by samcx** [comment]
Hi everyone,

I was not able to replicate this in the latest, and it is unlikely this is still an issue.

I will be closing this issue in the meantime!
