### ISSUE TITLE
'create-next-app, npm run dev' is failing

### ISSUE THREAD

**Issue by gomagon** [vercel/next.js#36961]
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

npx next info

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.6
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 101.0.4951.54

### Describe the Bug

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* c:\vscode\react\testapp\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[3].oneOf[2].use!C:\vscode\react\testapp\node_modules\next\dist\pages\_error.js
* c:\vscode\react\testapp\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[3].oneOf[2].use!c:\vscode\react\testapp\node_modules\next\dist\pages\_error.js
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\vscode\react\testapp\node_modules\react\cjs\react.development.js:1616:21)
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:204:73)
    at renderWithHooks (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5479:16)
    at renderIndeterminateComponent (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5552:15)
    at renderElement (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5767:7)
    at renderNodeDestructive (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5906:11)
    at finishClassComponent (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5509:3)
    at renderClassComponent (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5517:3)
    at renderElement (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5764:7)
    at renderNodeDestructive (c:\vscode\react\testapp\node_modules\react-dom\cjs\react-dom-server-legacy.browser.development.js:5906:11)

### Expected Behavior

Start default next app in the browser successfully.

### To Reproduce

npx create-next-app@latest --typescript testapp
cd testapp
npm run dev

Navigate to localhost:3000 in the browser
Browser shows nothing (white screen) and terminal shows TypeError: Cannot read properties of null (reading 'useContext')
The error is in node_modules.
This is the default next app with no configuration from me at all.

package.json
{
  "name": "testapp",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },
  "devDependencies": {
    "@types/node": "17.0.34",
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.4",
    "eslint": "8.15.0",
    "eslint-config-next": "12.1.6",
    "typescript": "4.6.4"
  }
}

**Comment by gomagon** [comment]
When I ran npm run dev in the vscode terminal instead of the windows command, app started successfully. So close the issue

**Comment by Disorrder** [comment]
same issue on Mac, run dev command in vscode console, but have same error
