### ISSUE TITLE
`build` command fails

### ISSUE THREAD

**Issue by freddi301** [vercel/next.js#37178]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

Running the `yar build` command it fails with this error

```
HookWebpackError: Cannot read properties of undefined (reading 'toLowerCase')
    at makeWebpackError (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\webpack\bundle5.js:41988:9)
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\webpack\bundle5.js:25497:12
    at eval (eval at create (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\webpack\bundle5.js:141841:10), <anonymous>:34:1)  
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at C:\Users\User\work\openk9\openk9\js-packages\admin-ui\static\css\a44a5c7380c43fea.css:26854:1
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:12453
    at Array.map (<anonymous>)
    at l.exports (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:12437)
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:23616
    at mergeRules (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:26770)
    at Object.merge (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:23598)
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:11960
    at Array.forEach (<anonymous>)
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:11932
    at C:\Users\User\work\openk9\openk9\node_modules\next\node_modules\postcss\lib\container.js:96:18
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at C:\Users\User\work\openk9\openk9\js-packages\admin-ui\static\css\a44a5c7380c43fea.css:26854:1
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:12453
    at Array.map (<anonymous>)
    at l.exports (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:12437)
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:23616
    at mergeRules (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:26770)
    at Object.merge (C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:23598)
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:11960
    at Array.forEach (<anonymous>)
    at C:\Users\User\work\openk9\openk9\node_modules\next\dist\compiled\cssnano-simple\index.js:190:11932
    at C:\Users\User\work\openk9\openk9\node_modules\next\node_modules\postcss\lib\container.js:96:18


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

It builds correctly

### To Reproduce

`yarn build` in this directory https://github.com/smclab/openk9/tree/main/js-packages/admin-ui

**Comment by balazsorban44** [comment]
I cannot run your reproduction since there seem to be some private/missing packages. Could you update your reproduction so it excludes/includes all of these?

It also has Next 10 as a dependency, but your `next info` states you tried `12.1.6`. Could you make sure you verify our `canary` release and make sure the reproduction reflects what you report?

**Comment by freddi301** [comment]
I'm very sorry for the inconvenience, these private packages must be built and linked (they are in the same level directory)
- `cd rest-api && yarn build && yarn link`
- `cd search-frontend && yarn build && yarn link`
- `cd admin-ui && yarn link @openk9/rest-api && yarn link @openk9/search-frontend`

I tried nxt version "12" and "12.1.6" and canary, all three present the same issue

**Comment by freddi301** [comment]
If the issue look too specific feel free to close it

**Comment by osequi** [comment]
I'm running into the same error from time to time:

```bash
TypeError: Cannot read properties of undefined (reading 'YRg')
    at Module.componentDefaultProps (/home/cs/mtx/mtx-fe/.next/server/chunks/45.js:18009:120)
    at /home/cs/mtx/mtx-fe/.next/server/chunks/45.js:8250:41
    at Function.__webpack_require__.a (/home/cs/mtx/mtx-fe/.next/server/webpack-runtime.js:91:13)
    at Object.34814 (/home/cs/mtx/mtx-fe/.next/server/chunks/45.js:8227:21)
    at __webpack_require__ (/home/cs/mtx/mtx-fe/.next/server/webpack-runtime.js:25:42)
    at /home/cs/mtx/mtx-fe/.next/server/chunks/45.js:8279:79
    at Function.__webpack_require__.a (/home/cs/mtx/mtx-fe/.next/server/webpack-runtime.js:91:13)
    at Object.63680 (/home/cs/mtx/mtx-fe/.next/server/chunks/45.js:8274:21)
    at __webpack_require__ (/home/cs/mtx/mtx-fe/.next/server/webpack-runtime.js:25:42)
    at /home/cs/mtx/mtx-fe/.next/server/chunks/45.js:8320:79 {
  type: 'TypeError'
}
error Command failed with exit code 1.
```
