### ISSUE TITLE
Production deployment keeps failing over and over again giving TypeError cannot read property of undefined reading ('0')

### ISSUE THREAD

**Issue by shellking4** [vercel/next.js#37232]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Linux/Ubuntu 20.04

### How are you deploying your application? (if relevant)

Vercel, docker, next start  

### Describe the Bug

I'm new to nextjs. I built the application and in order to test the progressive feature I want to deploy it to vercel but the builds keeps failing. giving me a TypeError. 

Logs is here

[22:06:54.781] Cloning github.com/shellking4/digital-immat (Branch: main, Commit: 8d89705)
[22:06:55.810] Cloning completed: 1.029s
[22:06:56.048] Installing build runtime...
[22:06:57.871] Build runtime installed: 1.823s
[22:06:58.719] No Build Cache available
[22:06:58.877] Installing dependencies...
[22:07:06.202] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[22:07:06.606] npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[22:07:06.928] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[22:07:07.145] npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[22:07:07.256] npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[22:07:10.614] npm WARN deprecated @zeit/next-css@1.0.1: Next.js now has built-in support for CSS: https://nextjs.org/docs/basic-features/built-in-css-support. The built-in support solves many bugs and painpoints that the next-css plugin had.
[22:07:10.675] npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
[22:07:10.780] npm WARN deprecated @types/sweetalert@2.0.4: This is a stub types definition for SweetAlert (https://github.com/t4t5/sweetalert/). SweetAlert provides its own type definitions, so you don't need @types/sweetalert installed!
[22:07:11.033] npm WARN deprecated @types/axios@0.14.0: This is a stub types definition for axios (https://github.com/mzabriskie/axios). axios provides its own type definitions, so you don't need @types/axios installed!
[22:07:13.782] npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[22:07:17.988] npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
[22:07:24.709] 
[22:07:24.709] added 1077 packages in 26s
[22:07:24.709] 
[22:07:24.709] 101 packages are looking for funding
[22:07:24.709]   run `npm fund` for details
[22:07:24.921] Detected `package-lock.json` generated by npm 7...
[22:07:24.921] Running "npm run build"
[22:07:25.197] 
[22:07:25.198] > digital-immat-web@0.1.0 build
[22:07:25.198] > next build
[22:07:25.198] 
[22:07:26.454] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[22:07:26.455] This information is used to shape Next.js' roadmap and prioritize features.
[22:07:26.455] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[22:07:26.455] https://nextjs.org/telemetry
[22:07:26.455] 
[22:07:26.508] info  - Checking validity of types...
[22:07:31.664] info  - Creating an optimized production build...
[22:07:31.705] info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
[22:07:31.720] > [PWA] Compile client (static)
[22:07:31.720] > [PWA] Auto register service worker with: /vercel/path0/frontends/digital-immat-web/node_modules/next-pwa/register.js
[22:07:31.720] > [PWA] Service worker: /vercel/path0/frontends/digital-immat-web/public/sw.js
[22:07:31.720] > [PWA]   url: /sw.js
[22:07:31.721] > [PWA]   scope: /
[22:07:31.952] > [PWA] Compile server
[22:07:31.954] > [PWA] Compile server
[22:07:32.343] info  - Using external babel configuration from /vercel/path0/frontends/digital-immat-web/.babelrc
[22:08:03.653] info  - Compiled successfully
[22:08:03.653] info  - Collecting page data...
[22:08:04.149] 
[22:08:04.149] > Build error occurred
[22:08:04.149] TypeError: Cannot read properties of undefined (reading '0')
[22:08:04.150]     at /vercel/path0/frontends/digital-immat-web/.next/server/chunks/987.js:353:129
[22:08:04.150]     at Function.__webpack_require__.a (/vercel/path0/frontends/digital-immat-web/.next/server/webpack-runtime.js:103:13)
[22:08:04.150]     at Object.8022 (/vercel/path0/frontends/digital-immat-web/.next/server/chunks/987.js:335:21)
[22:08:04.151]     at __webpack_require__ (/vercel/path0/frontends/digital-immat-web/.next/server/webpack-runtime.js:25:42)
[22:08:04.151]     at /vercel/path0/frontends/digital-immat-web/.next/server/pages/engines/qrcode.js:65:80
[22:08:04.151]     at Function.__webpack_require__.a (/vercel/path0/frontends/digital-immat-web/.next/server/webpack-runtime.js:103:13)
[22:08:04.152]     at __webpack_require__ (/vercel/path0/frontends/digital-immat-web/.next/server/webpack-runtime.js:25:42)
[22:08:04.152]     at __webpack_exec__ (/vercel/path0/frontends/digital-immat-web/.next/server/pages/engines/qrcode.js:295:39)
[22:08:04.152]     at /vercel/path0/frontends/digital-immat-web/.next/server/pages/engines/qrcode.js:296:86 {
[22:08:04.152]   type: 'TypeError'
[22:08:04.153] }
[22:08:04.177] Error: Command "npm run build" exited with 1
 Perhaps I'm making a silly mistake since I'm a newbie. Would appreciate any help.
Below the link to the app repo the nextjs frontend is in the frontends directory. 
https://github.com/shellking4/digital-immat

### Expected Behavior

The build should succeed and app would deploy without any hassle

### To Reproduce

clone the repo and go the frontends/digital-immat-web directory then try to deploy it on vercel

**Comment by awareness481** [comment]
(This is more appropriate for github discussions)

You will likely be able to reproduce the error if you do `npm run build` and `npm run start` locally, that should help you understand why the error is occurring.

**Comment by shellking4** [comment]
> (This is more appropriate for github discussions)
> 
> You will likely be able to reproduce the error if you do `npm run build` and `npm run start` locally, that should help you understand why the error is occurring.

Yes this is what is weird about my problem. The local build is successful but it is failing online

**Comment by shellking4** [comment]
> You could try building with (in your next.config.js)
> ```js
> module.exports = {
>   productionBrowserSourceMaps: true,
> }
> ```
> this means that you will get a better output when deploying to vercel and you will probably understand which line of code causes this error.
> 
> I would suggest reading this https://vercel.com/docs/concepts/next.js/overview#:~:text=Because%20secrets%20are,above%20like%20so%3A as it sounds likely to be the cause of the error (because it works locally)

I did what you suggested but same error. Same log on vercel. I did also check out the link but I'm not using secrets in the app. I have an external api which handles crud operations.

The  error seems to come from a component page named qrcode.tsx. I would appreciate If you could look at the repo and see what I'm doing wrong. I can't figure out where the error is coming from since the build worked in local

**Comment by awareness481** [comment]
Your error is coming from the rest config file, specifically these functions

```ts
export const apiHost = typeof window === "undefined" ? `http://${getServerAddresses()["wlp2s0"][0]}:8000` : "";

export const appHost = typeof window === "undefined" ? `http://${getServerAddresses()["wlp2s0"][0]}:3000` : "";
```

Seems like the object returned doesnt contain a "wlp2s0" property, Im unsure what you re trying to do but I suspect these values might be platform specific.


FWIW for future reference I suggest posting in [GH](https://github.com/vercel/next.js/discussions) or joining the [Next.js Discord](https://nextjs.org/discord)

**Comment by shellking4** [comment]
Haa Thank you a lot. Basically I was trying to get the local machine ip address in my wifi network. Than use it to create an url I can access locally from my android phone. I forgot to remove it or make it another way before deploying. Thank you very much. But I need to test out successfully with that part striped out before closing the issue.

**Comment by shellking4** [comment]
Thank you very much @awareness481. It deploys successfully now. You saved my day and career !! Be blessed. I'm closing this issue now
