### ISSUE TITLE
Cannot find module 'use-subscription/package.json'

### ISSUE THREAD

**Issue by devLeopar** [vercel/next.js#37731]
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

   Operating System:
      Platform: linux
      Arch: x64
      Version: #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

warn  - Latest canary version not detected, detected: "12.1.6", newest: "12.1.7-canary.40".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### How are you deploying your application? (if relevant)

vercel --prod

### Describe the Bug

Before committing I ran `next build` locally and the error below appeared. It is not got on while deploying to Github(on actions->build step)

```
> Build error occurred
Error: Cannot find module 'use-subscription/package.json'
Require stack:
- /usr/lib/node_modules/next/dist/build/webpack-config.js
- /usr/lib/node_modules/next/dist/build/index.js
- /usr/lib/node_modules/next/dist/cli/next-build.js
- /usr/lib/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/usr/lib/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getPackagePath (/usr/lib/node_modules/next/dist/build/webpack-config.js:551:41)
    at Object.getBaseWebpackConfig [as default] (/usr/lib/node_modules/next/dist/build/webpack-config.js:584:9)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/usr/lib/node_modules/next/dist/trace/trace.js:74:20)
    at async /usr/lib/node_modules/next/dist/build/index.js:330:29
    at async /usr/lib/node_modules/next/dist/build/index.js:326:9
    at async Span.traceAsyncFn (/usr/lib/node_modules/next/dist/trace/trace.js:74:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/next/dist/build/webpack-config.js',
    '/usr/lib/node_modules/next/dist/build/index.js',
    '/usr/lib/node_modules/next/dist/cli/next-build.js',
    '/usr/lib/node_modules/next/dist/bin/next'
  ]
}
```

I tried to upgrade nextjs to canary version but the error was the same.

### Expected Behavior

It should not give any error as it does on the build steps on Github.

### To Reproduce

`next build` on the root of the project

**Comment by balazsorban44** [comment]
I am trying to reproduce this issue, but am unable with a clean project. Could you link to yours that's having this issue? Is this consistently happening?

At the minimum, could you show your `package.json` file?

If you have tried `canary`, `use-subscription` should not be included in Next.js anymore, since https://github.com/vercel/next.js/pull/36733 so it should not be imported by Next.js as in the error above.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
