### ISSUE TITLE
NormalizeError: Requested and resolved page mismatch: /../public/images/slider1.png /public/images/slider1.png

### ISSUE THREAD

**Issue by JoaquinPalacios** [vercel/next.js#37800]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

info Direct dependencies
└─ next@12.1.7-canary.41
info All dependencies
├─ @next/env@12.1.7-canary.41
├─ @next/swc-win32-x64-msvc@12.1.7-canary.41
├─ @swc/helpers@0.3.17
├─ next@12.1.7-canary.41
├─ tslib@2.4.0
└─ use-sync-external-store@1.1.0

### What browser are you using? (if relevant)

Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I import dinamically three images from /public/images/ for a carousel.

The error pops up when I run yarn dev, the browser doesn't update any of the code due to the error on the console. The error says that:

_NormalizeError: Requested and resolved page mismatch: /../public/images/slider1.png /public/images/slider1.png
    at Object.normalizePagePath (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\shared\lib\page-path\normalize-page-path.js:14:15)
    at DevServer.hasPage (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\dev\next-dev-server.js:407:54)
    at DevServer._beforeCatchAllRender (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\dev\next-dev-server.js:439:28)
    at async Object.fn (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\dev\next-dev-server.js:715:21)
    at async Router.execute (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\router.js:207:36)
    at async DevServer.run (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\base-server.js:653:29)
    at async DevServer.run (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\dev\next-dev-server.js:546:20)
    at async DevServer.handleRequest (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\base-server.js:346:20)        
    at async imageOptimizer (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\image-optimizer.js:244:13)
    at async C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\next-server.js:192:72
NormalizeError: Requested and resolved page mismatch: /../public/images/slider2.png /public/images/slider2.png
    at Object.normalizePagePath (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\shared\lib\page-path\normalize-page-path.js:14:15)
    at DevServer.hasPage (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\dev\next-dev-server.js:407:54)
    at DevServer._beforeCatchAllRender (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\dev\next-dev-server.js:439:28)
    at async Object.fn (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\dev\next-dev-server.js:715:21)
    at async Router.execute (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\router.js:207:36)
    at async DevServer.run (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\base-ser    at async DevServer.handleRequest (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\base-server.js:346:20)    at async imageOptimizer (C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\image-optimizer.js:244:13)    at async C:\Users\joa_p\Desktop\Prgm\Tick4Solar\tick4solar\node_modules\next\dist\server\next-server.js:192:72_  

### Expected Behavior

To update any code in the browser. For example styles on the carousel. I am currently not able to update any styles on the home page due to that error.

### Link to reproduction

I couldn't create the bug on stackblitz due to there isn't an option for Next and Typescript

### To Reproduce

https://github.com/JoaquinPalacios/tick4Solar/tree/bug

Just clone the git repository from the brancg "bug" and run yarn dev and the error will pop up on the console.

The code is the following:

```
import React, { useEffect, useState } from "react";

import Image from "next/image";
import bgImg from '/public/images/mobile.jpg'
import styles from './Carousel.module.css';

const Carousel: React.FC<CarouselProps> = () => {

    const [slideIndex, setSlideIndex] = useState<number>(1);


    useEffect(() => {
        let timer = setInterval(() => {
            if (slideIndex !== Array.length) {
                setSlideIndex(slideIndex + 1);
            } else if (slideIndex === Array.length) {
                setSlideIndex(1);
            };
        }, 7000);
        
        return () => clearInterval(timer);
        
    }, [ slideIndex]);
    

    const moveDot = (index: React.SetStateAction<number>) => {
        setSlideIndex(index);
    };

    
    return (
        <div className={styles.containerSlider}>
            {Array.from({length: 3}).map((_, index) => {
                return (
                    <div
                      key={index}
                      className={slideIndex === index + 1 ? `${styles.slide} ${styles.activeAnim}` : styles.slide}
                    >
                        <Image                          
                          src={`/public/images/slider${index + 1}.png`}
                          alt='slides'
                          width={2000}
                          height={600}
                          layout={"fixed"}
                        />
                    </div>
                    )
                })}
            
            <div className={styles.fixImg}>
                <Image src={bgImg} alt='Image background' layout='fill' />
            </div>
             
            <div className={styles.containerDots}>
                  {Array.from({length: 3}).map((item, index) => (
                    <div 
                    key={index}
                    onClick={() => moveDot(index + 1)}
                    className={slideIndex === index + 1 ? `${styles.dot} ${styles.active}` : styles.dot}
                    ></div>
                    ))}
            </div>
        </div>
    );
};

export default Carousel;
```

**Comment by balazsorban44** [comment]
The reproduction repository is private so I could not have a look but this line seems to be the problem:

`src={`/public/images/slider${index + 1}.png`}`

You don't need to specify `/public` as shown in the documentation: https://nextjs.org/docs/basic-features/static-file-serving
