### ISSUE TITLE
Importing jpg image crashes build on node18

### ISSUE THREAD

**Issue by Hurtak** [vercel/next.js#38020]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.4.0
      npm: 8.12.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I am importing png image

```
import image from "../me.jpg";
```

- When running dev command everything works
- When running `next build` on node 17 everything works
- When running `next build` on node 18 it crashes with following message

```
Failed to compile.

./src/me.jpg
TypeError: Failed to parse URL from /Users/hurtak/hello/petrhurtak.com/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.wasm
    at new Request (node:internal/deps/undici/undici:4832:19)
    at Agent.fetch2 (node:internal/deps/undici/undici:5524:29)
    at Object.fetch (node:internal/deps/undici/undici:6351:20)
    at fetch (node:internal/bootstrap/pre_execution:197:25)
    at instantiateAsync (/Users/hurtak/hello/petrhurtak.com/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:424:28)
    at createWasm (/Users/hurtak/hello/petrhurtak.com/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:447:13)
    at /Users/hurtak/hello/petrhurtak.com/node_modules/next/dist/server/lib/squoosh/mozjpeg/mozjpeg_node_dec.js:1480:19
    at Object.instantiateEmscriptenWasm (/Users/hurtak/hello/petrhurtak.com/node_modules/next/dist/server/lib/squoosh/emscripten-utils.js:15:12)
    at Object.dec (/Users/hurtak/hello/petrhurtak.com/node_modules/next/dist/server/lib/squoosh/codecs.js:156:42)
    at Object.decodeBuffer (/Users/hurtak/hello/petrhurtak.com/node_modules/next/dist/server/lib/squoosh/impl.js:55:31)

Import trace for requested module:
./src/pages/index.tsx


> Build failed because of webpack errors
```

Here is github action running node 18 https://github.com/Hurtak/petrhurtak.com/runs/7056425060?check_suite_focus=true#step:5:41

Here is github action running node 17 https://github.com/Hurtak/petrhurtak.com/runs/7056461987?check_suite_focus=true

### Expected Behavior

Build works on node 18

### Link to reproduction

https://github.com/Hurtak/petrhurtak.com

### To Reproduce

Import this jpg image https://github.com/Hurtak/petrhurtak.com/blob/main/src/me.jpg like 

```
import image from "../me.png";
```

Use it somewhere in img tag

Run build command and observe the crash

**Comment by awareness481** [comment]
FWIW, doing `npm i sharp` will likely solve your issue. This looks like an upstream issue with squoosh
