### ISSUE TITLE
new project -> cannot find module

### ISSUE THREAD

**Issue by S1nPur1ty** [vercel/next.js#38151]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

After creating a new next app with, I tried to build and run it. However when building the project, it says: `Cannot find module '../../../../.nvm/versions/node/v16.9.1/lib/node_modules/next/dist/shared/lib/constants.js` can't be found.

I used: `yarn create next-app --typescript` to create my project and `next build` or `yarn run build` to build the project, but I get the same problem.

This is next info:

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.10.0
      npm: 7.24.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

Hope that anyone can help me resolve this issue.

### Describe the Bug

```
yarn run build
yarn run v1.22.19
$ next build
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data .node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Cannot find module '../../../../.nvm/versions/node/v16.9.1/lib/node_modules/next/dist/shared/lib/constants.js'
Require stack:
- /Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/pages/_document.js
- /Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/server/require.js
- /Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/server/load-components.js
- /Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/build/utils.js
- /Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/build/worker.js
- /Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.330 (/Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/pages/_document.js:32:18)
    at __webpack_require__ (/Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/webpack-runtime.js:25:42)
    at Object.989 (/Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/chunks/989.js:375:18)
    at __webpack_require__ (/Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/pages/_document.js:70:39)
    at /Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/pages/_document.js:71:70 {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/s1npur1ty/development/blockchain/smartcontract-deployer/.next/server/pages/_document.js',
    '/Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/server/require.js',
    '/Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/server/load-components.js',
    '/Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/build/utils.js',
    '/Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/build/worker.js',
    '/Users/s1npur1ty/development/blockchain/smartcontract-deployer/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

It should build and run my next project, but building doesn't work because of the missing module inside the next constants file.

### Link to reproduction

-

### To Reproduce

-

**Comment by LuizHAP** [comment]
I'm srry if it's a dumb question, but you tried to delete node_modules folder and the command `yarn or npm i` again?

**Comment by S1nPur1ty** [comment]
> I'm srry if it's a dumb question, but you tried to delete `node_modules` folder and the command `yarn or npm i` again?

Not at all! Yes, I tried it before. :)

**Comment by migsdeving** [comment]
I'm having the same problem, but for me it can't find module "is-arguments" right after creating next app

**Comment by S1nPur1ty** [comment]
It seems that after updating npx and recreating the project solved it.
