### ISSUE TITLE
TakeShape example readme is out of date

### ISSUE THREAD

**Issue by S3Prototype** [vercel/next.js#38210]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
The module 'react-dom' was not found. Next.js requires that 
you include it in 'dependencies' of your 'package.json'. To 
add it, run 'npm install react-dom'
(node:11140) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, realpath 'P:\NodeProjects\TakeShape\External Repos\next.js\info'
    at Function.realpathSync.native (fs.js:1855:3)
    at Object.getProjectDir (C:\Users\user\AppData\Roaming\npm\node_modules\next\dist\lib\get-project-dir.js:39:46)    at nextDev (C:\Users\user\AppData\Roaming\npm\node_modules\next\dist\cli\next-dev.js:84:37)
    at C:\Users\user\AppData\Roaming\npm\node_modules\next\dist\bin\next:119:34      
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.      
```

### Which example does this report relate to?

cms-takeshape https://github.com/vercel/next.js/tree/canary/examples/cms-takeshape

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

The readme is outdated. Old terminology and instructions needs to be updated. I'm the technical writer for TakeShape.

### Expected Behavior

Old terminology should be updated.

### To Reproduce

It's an issue in the readme.

**Comment by JanKaifer** [comment]
Hey, sorry for taking too long to follow up here.
We would love to merge your PR.
