### ISSUE TITLE
Production server crashes on 12.2.0 when built on Ubuntu

### ISSUE THREAD

**Issue by lerela** [vercel/next.js#38279]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202112220937~1640185481~21.04~b3a2c21-Ubuntu SMP Mon Jan 3 16:5
    Binaries:
      Node: 14.17.4
      npm: 6.14.14
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.2
      eslint-config-next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

When building a [sample app](https://github.com/fasfoxcom/next-antd) using Antdesign in production mode on an Ubuntu/Debian machine, the server fails at the first request and returns a 500. It also failed with Next 12.1.6. It did not fail with Next 12.1.5. It also works with 12.1.7-canary33. It does not work with 12.1.7-canary35. It is still broken in 12.2.1-canary2.

The error is the following:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
TypeError: Cannot read property 'vertical' of undefined
    at Object.children (/pnpm-next-antd/node_modules/antd/lib/form/FormItemLabel.js:84:26)
    at a.b.render (/pnpm-next-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:213)
    at a.b.read (/pnpm-next-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/pnpm-next-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/pnpm-next-antd/node_modules/next/dist/server/render.js:756:46)
    at Object.defaultGetInitialProps (/pnpm-next-antd/node_modules/next/dist/server/render.js:369:51)
    at Function.getInitialProps (/pnpm-next-antd/.next/server/chunks/105.js:422:20)
    at Object.<anonymous> (/pnpm-next-antd/node_modules/next/dist/shared/lib/utils.js:103:33)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/pnpm-next-antd/node_modules/next/dist/shared/lib/utils.js:15:28)
```

When built on macOS, there is no error. `yarn run dev` also works as expected.

This is vastly similar to this old ticket for which there was no fix: https://github.com/vercel/next.js/issues/7082 

Considering this does not happen in 12.1.7-canary33, I believe this is a Next.js issue.

### Expected Behavior

Production server runs without crashing.

### Link to reproduction

https://github.com/fasfoxcom/next-antd

### To Reproduce

- Check out the given repo on a Debian/Ubuntu machine or Debian-based Docker instance (`node:16-bullseye-slim` base image is known to show the issue)
- Run `yarn install && yarn run build && yarn run start`
- Visit [http://localhost:3000/](http://localhost:3000/)
- There should be a crash

**Comment by Whiteme01** [comment]
> ### Verify canary release
> 
> - [X] I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> 
>     Operating System:
>       Platform: linux
>       Arch: x64
>       Version: #202112220937~1640185481~21.04~b3a2c21-Ubuntu SMP Mon Jan 3 16:5
>     Binaries:
>       Node: 14.17.4
>       npm: 6.14.14
>       Yarn: 1.22.11
>       pnpm: N/A
>     Relevant packages:
>       next: 12.2.1-canary.2
>       eslint-config-next: 12.1.6
>       react: 17.0.2
>       react-dom: 17.0.2
> 
> ### What browser are you using? (if relevant)
> 
> _No response_
> 
> ### How are you deploying your application? (if relevant)
> 
> _No response_
> 
> ### Describe the Bug
> 
> When building a [sample app](https://github.com/fasfoxcom/next-antd) using Antdesign in production mode on an Ubuntu/Debian machine, the server fails at the first request and returns a 500. It also failed with Next 12.1.6. It did not fail with Next 12.1.5. It also works with 12.1.7-canary33. It does not work with 12.1.7-canary35. It is still broken in 12.2.1-canary2.
> 
> The error is the following:
> ```
> ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> TypeError: Cannot read property 'vertical' of undefined
>     at Object.children (/pnpm-next-antd/node_modules/antd/lib/form/FormItemLabel.js:84:26)
>     at a.b.render (/pnpm-next-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:213)
>     at a.b.read (/pnpm-next-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
>     at Object.exports.renderToString (/pnpm-next-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
>     at Object.renderPage (/pnpm-next-antd/node_modules/next/dist/server/render.js:756:46)
>     at Object.defaultGetInitialProps (/pnpm-next-antd/node_modules/next/dist/server/render.js:369:51)
>     at Function.getInitialProps (/pnpm-next-antd/.next/server/chunks/105.js:422:20)
>     at Object.<anonymous> (/pnpm-next-antd/node_modules/next/dist/shared/lib/utils.js:103:33)
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (/pnpm-next-antd/node_modules/next/dist/shared/lib/utils.js:15:28)
> ```
> 
> When built on macOS, there is no error. `yarn run dev` also works as expected.
> 
> This is vastly similar to this old ticket for which there was no fix: https://github.com/vercel/next.js/issues/7082 
> 
> Considering this does not happen in 12.1.7-canary33, I believe this is a Next.js issue.
> 
> ### Expected Behavior
> 
> Production server runs without crashing.
> 
> ### Link to reproduction
> 
> https://github.com/fasfoxcom/next-antd
> 
> ### To Reproduce
> 
> - Check out the given repo on a Debian/Ubuntu machine or Debian-based Docker instance (`node:16-bullseye-slim` base image is known to show the issue)
> - Run `yarn install && yarn run build && yarn run start`
> - Visit [http://localhost:3000/](http://localhost:3000/)
> - There should be a crash

**Comment by tehps** [comment]
Having this issue with 12.2.0 on AWS as well. 
Temporary downgraded to 12.1.6 resolves it.

Is there any update to why this happen on 12.2.0?

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
