### ISSUE TITLE
Github action production build fail at next build: since I updated to next v12

### ISSUE THREAD

**Issue by beumsk** [vercel/next.js#38330]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Github actions env
Environment: ubuntu-20.04
Version: 20220626.1
next@12

### What browser are you using? (if relevant)

NA

### How are you deploying your application? (if relevant)

Github action

### Describe the Bug

Since I switched from v11 to v12 I can't get my nextjs site deployed with github actions.
I receive this weird error that I dont get with yarn dev or yarn start locally:
```
/home/runner/work/beumsk.github.io/beumsk.github.io/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:7
placeholder = true;
SyntaxError: Unexpected token =
 at Module._compile (internal/modules/cjs/loader.js:723:23)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
     at Module.load (internal/modules/cjs/loader.js:653:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
     at Module.require (internal/modules/cjs/loader.js:692:17)
     at require (internal/modules/cjs/helpers.js:25:18)
     at Object.<anonymous> (/home/runner/work/beumsk.github.io/beumsk.github.io/node_modules/next/dist/shared/lib/router/utils/index.js:17:21)
     at Module._compile (internal/modules/cjs/loader.js:778:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
full log can be seen here: https://pipelines.actions.githubusercontent.com/serviceHosts/8895607a-933a-4321-87c1-d15f0bf230e6/_apis/pipelines/1/runs/159/signedlogcontent/2?urlExpires=2022-07-04T16%3A34%3A09.2242214Z&urlSigningMethod=HMACV1&urlSignature=nEpO0LP%2Finn6ch6mPcoVU4UzOSX2FY0XYurcBd3svkM%3D

and my repo: https://github.com/beumsk/beumsk.github.io

I searched here and online without success.
Can anyone help me or at least point me in the right direction?

Thank you so much already :)

### Expected Behavior

The production build should work as it does in my local env.

### Link to reproduction

na

### To Reproduce

I don't know how I can make it possible to reproduce.

**Comment by tarkungZZ** [comment]
Same problem bro still finding out how to fix this.

**Comment by kiafas-k** [comment]
have you had any luck fixing that ?

**Comment by beumsk** [comment]
Yes, switching to Nextjs v12 needs a more recent version of Node, which you have to explicitly choose in your `integrate.yml`.
Here is the way to specify it to node 14 for example, as you can read here: https://github.com/actions/setup-node
```
- uses: actions/setup-node@v3
        with:
          node-version: 14
```
Hope it fixes your issues as well!
