### ISSUE TITLE
`caches` on middleware is undefined when deploying to Vercel

### ISSUE THREAD

**Issue by aiji42** [vercel/next.js#38539]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.18
      pnpm: 7.0.1
    Relevant packages:
      next: 12.2.3-canary.1
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

However, the problem is occurring on Vercel Edge Functions

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When deploying to Vercel, I cannot run `caches.open` on middleware.ts due to the following error.
```
TypeError: Cannot read properties of undefined (reading 'open')
    at worker.js:13:2307
    at worker.js:13:25696
    at worker.js:13:2146
    at worker.js:20:11430
    at worker.js:30:34
    at worker.js:45:10071
    at worker.js:45:10919
    at worker.js:45:11775
```

![スクリーンショット 2022-07-12 午前10 35 58](https://user-images.githubusercontent.com/6711766/178389251-bd1bc532-024e-4107-b260-8a15d1c1dbf9.png)

Locally, no errors occur, `caches.oepn`, `.put`, and `.match` are available, and in fact the cache store and restore appear to succeed.

```ts
import { NextMiddleware, NextResponse } from 'next/server'

export const middleware: NextMiddleware = async (request, event) => {
  const cache = await caches.open('cache:example')
  const url = new URL('https://www.googleapis.com/identitytoolkit/v3/relyingparty/publicKeys')
  let pubKeyRes = await cache.match(url)
  if (!pubKeyRes) {
    console.log('cache NOT hit')
    pubKeyRes = await fetch(url)
    event.waitUntil(cache.put(url, pubKeyRes))
  } else {
    console.log('cache hit')
  }

  return NextResponse.next()
}
```
![スクリーンショット 2022-07-12 午前10 41 42](https://user-images.githubusercontent.com/6711766/178389929-53dcf5b9-a114-4231-8629-b64e539ef195.png)

### Expected Behavior

Can use cache api on Vercel Edge Functions

### Link to reproduction

https://github.com/aiji42/middleware-cache

### To Reproduce

Deploy to Vercel and access.

---

Documentation states that `Web Cache` can be used.
https://edge-runtime.vercel.app/features/available-apis#web-standards-apis
![スクリーンショット 2022-07-12 午後7 06 03](https://user-images.githubusercontent.com/6711766/178466197-6dbf6123-33a5-4cfe-8f66-9ba28df0edcb.png)

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
