### ISSUE TITLE
JSON files in dependency package aren't resolved when deployed

### ISSUE THREAD

**Issue by suneettipirneni** [vercel/next.js#38933]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 3.2.1
      pnpm: 6.11.0
    Relevant packages:
      next: 12.2.3-canary.17
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 103.0.5060.114

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

When deploying my application to vercel and using on-demand static generation via `fallback: 'true'`, the serverless function executing the update cannot find a json file located within a package dependency. In my specific case, I'm using api-extractor which references and resolves a json file in another directory.

More specifically, this `resolve` in the package source code seems to be causing issues:
https://github.com/microsoft/tsdoc/blob/31bcfd59d73ad81459210e723cf02d75d902430f/tsdoc-config/src/TSDocConfigFile.ts#L21

On the serverless function the error is presented whenever nextjs tries to generate the page via `getStaticProps`

```
[GET] /docs/foo
13:57:05:30
2022-07-22T17:57:06.522Z	d3b8e6c0-1eaa-41d7-a84f-35f933b2f6a0	ERROR	Error: Cannot find module '@microsoft/tsdoc/schemas/tsdoc.schema.json' from '/var/task/website/node_modules/@microsoft/tsdoc-config/lib'
    at Object.resolveSync (/var/task/website/node_modules/@microsoft/tsdoc-config/node_modules/resolve/lib/sync.js:90:15)
    at initializeSchemaValidator (/var/task/website/node_modules/@microsoft/tsdoc-config/lib/TSDocConfigFile.js:34:36)
    at Object.<anonymous> (/var/task/website/node_modules/@microsoft/tsdoc-config/lib/TSDocConfigFile.js:42:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/task/website/node_modules/@microsoft/tsdoc-config/lib/index.js:3:25) {
  code: 'MODULE_NOT_FOUND',
  page: '/docs/[...slug]'
}
RequestId: d3b8e6c0-1eaa-41d7-a84f-35f933b2f6a0 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Note that this code works as expected when using `next-dev`, it only fails when deployed.

### Expected Behavior

The json file referenced in the dependency should be able to be resolved in server-side contexts such as `getStaticProps()`.

### Link to reproduction

https://github.com/suneettipirneni/next-test

### To Reproduce

- Deploy the application in the linked repo to vercel
- Visit any path under the `/docs` route, for example `/docs/foo`
- Observe resolve error in function logs in vercel dashboard.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
