### ISSUE TITLE
`'cypress.config.ts' cannot be compiled under '--isolatedModules'` in `with-cypress` example

### ISSUE THREAD

**Issue by nasso** [vercel/next.js#38957]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 16.15.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-cypress

### Describe the Bug

The following error is displayed when I try to build the example:

```
./cypress.config.ts:1:1
Type error: 'cypress.config.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

> 1 | const { defineConfig } = require('cypress')
    | ^
  2 | 
  3 | module.exports = defineConfig({
  4 |   e2e: {

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/tmp/with-cypress-app/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/tmp/with-cypress-app/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
```

### Expected Behavior

The application builds successfully.

### To Reproduce

```sh
yarn build
```

**Comment by titusdmoore** [comment]
@nasso did that pr resolve the issues you were having on your end?

**Comment by ijjk** [comment]
Closing per above, please respond with additional info if this is still an issue!

**Comment by nasso** [comment]
That seems to solve it! I thought adding `export {}` was ugly but I guess it's fine here.
