### ISSUE TITLE
Rendering /_error mutates the status code for no reason 

### ISSUE THREAD

**Issue by masad-frost** [vercel/next.js#39144]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Can reproduce on any environment

### Describe the Bug

When using Next with a custom server and rendering `/_error`, Next changes the res.status to 404 before rendering the page, it's really odd. 

It's really easy to reproduce https://replit.com/@replitfaris/NextChangeStatusCode, you can fork this and run it yourself

Looks like there's a report of this behavior going back to 2017 https://github.com/vercel/next.js/issues/2866

### Expected Behavior

Maintain res.status

### Link to reproduction

https://replit.com/@replitfaris/NextChangeStatusCode

**Comment by masad-frost** [comment]
Call stack when changing the status code:

```
at ServerResponse.set [as statusCode] (/home/runner/NextChangeStatusCode-1/index.js:40:13)
    at NodeNextResponse.set statusCode [as statusCode] (/home/runner/NextChangeStatusCode-1/node_modules/next/dist/server/base-http/node.js:50:30)
    at DevServer.render404 (/home/runner/NextChangeStatusCode-1/node_modules/next/dist/server/base-server.js:1330:24)
    at DevServer.render404 (/home/runner/NextChangeStatusCode-1/node_modules/next/dist/server/next-server.js:500:22)
    at DevServer.render (/home/runner/NextChangeStatusCode-1/node_modules/next/dist/server/base-server.js:688:25)
    at DevServer.render (/home/runner/NextChangeStatusCode-1/node_modules/next/dist/server/next-server.js:488:22)
    at NextServer.render (/home/runner/NextChangeStatusCode-1/node_modules/next/dist/server/next.js:92:23)
````

From what I can Next thinks `/_error` does not exist

**Comment by balazsorban44** [comment]
`/_error` is a reserved pathname and will render 404 when accessed directly:

https://github.com/vercel/next.js/blob/48405e6bd791acc4f228554ec0c3c980bebe056d/packages/next/server/base-server.ts#L1156-L1158

https://github.com/vercel/next.js/blob/48405e6bd791acc4f228554ec0c3c980bebe056d/packages/next/shared/lib/constants.ts#L25

You can try rendering your error page on a different path instead.

**Comment by masad-frost** [comment]
@balazsorban44 do you wanna add that to https://nextjs.org/docs/advanced-features/custom-error-page#404-page

**Comment by balazsorban44** [comment]
I can do it later, you can also open a PR, here is the file that needs to be edited: https://github.com/vercel/next.js/edit/canary/docs/advanced-features/custom-error-page.md
