### ISSUE TITLE
Inconsistent error `basePath` config validation error messages

### ISSUE THREAD

**Issue by hood** [vercel/next.js#39215]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

`next info` output:

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000
    Binaries:
      Node: 18.5.0
      npm: 8.12.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.2.3", newest: "12.2.4-canary.8".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
Done in 1.26s.
```

### What browser are you using? (if relevant)

N.A.

### How are you deploying your application? (if relevant)

N.A.

### Describe the Bug

Getting both
```
Error: Specified basePath /. basePath has to be either an empty string or a path prefix"
    at assignDefaults (/myapp/node_modules/next/dist/server/config.js:266:19)
    at Object.loadConfig [as default] (/myapp/node_modules/next/dist/server/config.js:97:16)
    at async NextServer.prepare (/myapp/node_modules/next/dist/server/next.js:115:24)
    at async /myapp/node_modules/next/dist/cli/next-dev.js:147:9
error Command failed with exit code 1.
```

and
```
warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "/basePath",
    "schemaPath": "#/properties/basePath/minLength",
    "keyword": "minLength",
    "params": {
      "limit": 1
    },
    "message": "must NOT have fewer than 1 characters"
  }
] 
See more info here: https://nextjs.org/docs/messages/invalid-next-config
```

When providing an empty `basePath` (both `""` and `undefined`) in my `next.config.js`.

### Expected Behavior

Getting coherent error messages

### Link to reproduction

-

### To Reproduce

-

**Comment by ijjk** [comment]
Hi, this was fixed in https://github.com/vercel/next.js/pull/38998 which is available in `v12.2.4-canary.8` of Next.js, please update and give it a try!
