### ISSUE TITLE
Nextjs site fails to compile on cloudflare pages

### ISSUE THREAD

**Issue by Lastofthefirst** [vercel/next.js#39235]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Cloudflare pages

### How are you deploying your application? (if relevant)

Cloudflare pages

### Describe the Bug

Here are logs from the crash:

2022-08-01T19:53:54.495224Z	Cloning repository...
2022-08-01T19:53:55.987203Z	From https://github.com/Lastofthefirst/pilgrim-notes
2022-08-01T19:53:55.987838Z	 * branch            3ed042c84097c7c9d72ca46d80a44cbeff673cfa -> FETCH_HEAD
2022-08-01T19:53:55.988019Z	
2022-08-01T19:53:56.112396Z	HEAD is now at 3ed042c next config unoptimized images
2022-08-01T19:53:56.112987Z	
2022-08-01T19:53:56.282489Z	
2022-08-01T19:53:56.31538Z	Success: Finished cloning repository files
2022-08-01T19:53:57.009971Z	Installing dependencies
2022-08-01T19:53:57.021997Z	Python version set to 2.7
2022-08-01T19:54:00.607221Z	v12.18.0 is already installed.
2022-08-01T19:54:01.909101Z	Now using node v12.18.0 (npm v6.14.4)
2022-08-01T19:54:02.165364Z	Started restoring cached build plugins
2022-08-01T19:54:02.182505Z	Finished restoring cached build plugins
2022-08-01T19:54:02.698842Z	Attempting ruby version 2.7.1, read from environment
2022-08-01T19:54:06.556177Z	Using ruby version 2.7.1
2022-08-01T19:54:06.940929Z	Using PHP version 5.6
2022-08-01T19:54:07.112859Z	5.2 is already installed.
2022-08-01T19:54:07.141235Z	Using Swift version 5.2
2022-08-01T19:54:07.14182Z	Started restoring cached node modules
2022-08-01T19:54:07.159078Z	Finished restoring cached node modules
2022-08-01T19:54:07.411823Z	Installing NPM modules using NPM version 6.14.4
2022-08-01T19:54:08.400376Z	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2022-08-01T19:54:21.463856Z	
2022-08-01T19:54:21.464197Z	> core-js-pure@3.23.2 postinstall /opt/buildhome/repo/node_modules/core-js-pure
2022-08-01T19:54:21.464353Z	> node -e "try{require('./postinstall')}catch(e){}"
2022-08-01T19:54:21.464475Z	
2022-08-01T19:54:21.578128Z	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2022-08-01T19:54:21.578486Z	
2022-08-01T19:54:21.578641Z	[96mThe project needs your help! Please consider supporting of core-js:[0m
2022-08-01T19:54:21.579613Z	[96m>[94m https://opencollective.com/core-js [0m
2022-08-01T19:54:21.579843Z	[96m>[94m https://patreon.com/zloirock [0m
2022-08-01T19:54:21.579976Z	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2022-08-01T19:54:21.580105Z	
2022-08-01T19:54:21.580222Z	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2022-08-01T19:54:21.580333Z	
2022-08-01T19:54:21.956059Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm-eabi@12.2.3 (node_modules/@next/swc-android-arm-eabi):
2022-08-01T19:54:21.956403Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm-eabi@12.2.3: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.956584Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-android-arm64@12.2.3 (node_modules/@next/swc-android-arm64):
2022-08-01T19:54:21.956746Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-android-arm64@12.2.3: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.956906Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-arm64@12.2.3 (node_modules/@next/swc-darwin-arm64):
2022-08-01T19:54:21.957025Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-arm64@12.2.3: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.95715Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-freebsd-x64@12.2.3 (node_modules/@next/swc-freebsd-x64):
2022-08-01T19:54:21.957784Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-freebsd-x64@12.2.3: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.95802Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-darwin-x64@12.2.3 (node_modules/@next/swc-darwin-x64):
2022-08-01T19:54:21.958155Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-darwin-x64@12.2.3: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.958283Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-arm64-msvc@12.2.3 (node_modules/@next/swc-win32-arm64-msvc):
2022-08-01T19:54:21.958397Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-arm64-msvc@12.2.3: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.958531Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-gnu@12.2.3 (node_modules/@next/swc-linux-arm64-gnu):
2022-08-01T19:54:21.95866Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-gnu@12.2.3: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.958867Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm-gnueabihf@12.2.3 (node_modules/@next/swc-linux-arm-gnueabihf):
2022-08-01T19:54:21.959009Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm-gnueabihf@12.2.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.959131Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-linux-arm64-musl@12.2.3 (node_modules/@next/swc-linux-arm64-musl):
2022-08-01T19:54:21.959251Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-linux-arm64-musl@12.2.3: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.959359Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-x64-msvc@12.2.3 (node_modules/@next/swc-win32-x64-msvc):
2022-08-01T19:54:21.9595Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-x64-msvc@12.2.3: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.959612Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @next/swc-win32-ia32-msvc@12.2.3 (node_modules/@next/swc-win32-ia32-msvc):
2022-08-01T19:54:21.959746Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @next/swc-win32-ia32-msvc@12.2.3: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.959869Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2022-08-01T19:54:21.959996Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2022-08-01T19:54:21.960125Z	
2022-08-01T19:54:21.961553Z	added 273 packages from 186 contributors and audited 285 packages in 13.597s
2022-08-01T19:54:22.073527Z	
2022-08-01T19:54:22.073928Z	78 packages are looking for funding
2022-08-01T19:54:22.074128Z	  run `npm fund` for details
2022-08-01T19:54:22.074281Z	
2022-08-01T19:54:22.074436Z	found 0 vulnerabilities
2022-08-01T19:54:22.074593Z	
2022-08-01T19:54:22.095967Z	NPM modules installed
2022-08-01T19:54:22.521429Z	Installing Hugo 0.54.0
2022-08-01T19:54:23.246098Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2022-08-01T19:54:23.251112Z	Started restoring cached go cache
2022-08-01T19:54:23.275379Z	Finished restoring cached go cache
2022-08-01T19:54:23.451012Z	go version go1.14.4 linux/amd64
2022-08-01T19:54:23.469494Z	go version go1.14.4 linux/amd64
2022-08-01T19:54:23.47276Z	Installing missing commands
2022-08-01T19:54:23.473265Z	Verify run directory
2022-08-01T19:54:23.473477Z	Executing user command: next build && next export
2022-08-01T19:54:24.046132Z	warn  - You have enabled experimental features (newNextLinkBehavior, images) in next.config.js.
2022-08-01T19:54:24.046482Z	warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
2022-08-01T19:54:24.046649Z	
2022-08-01T19:54:24.04824Z	(node:1342) ExperimentalWarning: The ESM module loader is experimental.
2022-08-01T19:54:24.048718Z	warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2022-08-01T19:54:24.09188Z	Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-08-01T19:54:24.092217Z	This information is used to shape Next.js' roadmap and prioritize features.
2022-08-01T19:54:24.092408Z	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2022-08-01T19:54:24.092549Z	https://nextjs.org/telemetry
2022-08-01T19:54:24.092669Z	
2022-08-01T19:54:24.231342Z	info  - Linting and checking validity of types...
2022-08-01T19:54:26.615334Z	info  - Creating an optimized production build...
2022-08-01T19:54:53.912027Z	info  - Compiled successfully
2022-08-01T19:54:53.912792Z	info  - Collecting page data...
2022-08-01T19:54:54.612924Z	(node:1431) ExperimentalWarning: The ESM module loader is experimental.
2022-08-01T19:54:54.737237Z	
2022-08-01T19:54:54.737632Z	> Build error occurred
2022-08-01T19:54:54.739987Z	file:///opt/buildhome/repo/node_modules/@headlessui/react/dist/hooks/use-iso-morphic-effect.js:1
2022-08-01T19:54:54.740233Z	import{useLayoutEffect as e,useEffect as f}from"react";let t=typeof window!="undefined"?e:f;export{t as useIsoMorphicEffect};
2022-08-01T19:54:54.7404Z	       ^^^^^^^^^^^^^^^
2022-08-01T19:54:54.740534Z	SyntaxError: The requested module 'react' does not provide an export named 'useLayoutEffect'
2022-08-01T19:54:54.740662Z	    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
2022-08-01T19:54:54.740799Z	    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
2022-08-01T19:54:54.740923Z	    at async Loader.import (internal/modules/esm/loader.js:179:24) {
2022-08-01T19:54:54.741035Z	  type: 'SyntaxError'
2022-08-01T19:54:54.741143Z	}
2022-08-01T19:54:54.810511Z	Failed: build command exited with code: 1
2022-08-01T19:54:55.624468Z	Failed: an internal error occurred

### Expected Behavior

Expect the site to produce a working build as it does on my local machine.

### Link to reproduction

n/a

### To Reproduce

I'm not sure other than just next build && next export.

**Comment by abuu-u** [comment]
this helped me https://github.com/tailwindlabs/headlessui/issues/1614#issuecomment-1187442835

**Comment by gertasik** [comment]
> Now using node v12.18.0 (npm v6.14.4)

Have you recently updated React? As the link above suggests, the newer React versions often don't play well with older node versions. On Cloudflare Pages, you can set the node version by going into Settings -> Environmental variables, and adding NODE_VERSION=16 to the list.

**Comment by Lastofthefirst** [comment]
I added the node version env variable, then there were more issues related to the whole image processing stuff, but the following config worked. Thanks.

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: { loader: 'custom' },

  experimental: {
    newNextLinkBehavior: true,

    images: {
      unoptimized: true,
      allowFutureImage: true,

    },
  },
}
```
