### ISSUE TITLE
`next/head` with svg leads to infinite re-render

### ISSUE THREAD

**Issue by defjosiah** [vercel/next.js#39449]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.2.4
      eslint-config-next: 12.1.5
      react: 16.14.0
      react-dom: 16.9.0
```

### Describe the Bug

When upgrading a complex app to next@12.2.4, we ran into an infinite re-render bug that affected our existing usage of 
next/head.

We embed SVGs using `next/head` i.e.
// Somewhere in the component tree
```
<>
  <Head>
      <SelectiveSpritesheet icon={[MyIcon]}/>
  </Head>
</>
```
Where SelectiveSpritesheet and "MyIcon" are defined as follows
```
const Calendar = {
  name: 'calendar',
  svg: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M20.75 4.5H19.5V3.25C19.5 2.56111 18.9389 2 18.25 2C17.5611 2 17 2.56111 17 3.25V4.5H7V3.25C7 2.56111 6.43889 2 5.75 2C5.06111 2 4.5 2.56111 4.5 3.25V4.5H3.25C3.16111 4.5 3.07777 4.5111 2.99999 4.52777C2.78888 4.57222 2.59444 4.67222 2.43333 4.80555C2.32778 4.89444 2.23888 5.00556 2.16666 5.12778C2.0611 5.31111 2 5.52222 2 5.75V20.75C2 21.4389 2.56111 22 3.25 22H20.75C21.4389 22 22 21.4389 22 20.75V10.75V5.75C22 5.05556 21.4389 4.5 20.75 4.5ZM19.5 19.5H4.5V12H19.5V19.5Z" fill="currentColor"/>
</svg>`,
};

const SelectiveSpritesheet = (props) => {
  return (
    <svg>
      <defs>
        {props.icons.map(({ name, svg }) => (
          <g key={name} id={name} dangerouslySetInnerHTML={{ __html: svg }} />
        ))}
      </defs>
    </svg>
  );
};
```
The error is only present in a production set-up (i.e. `next build && next start`).

I bisected all tagged diffs between `v12.1.1` and `v12.2.4` and the issue is present starting from
`v12.1.7-canary.32` (`v12.1.7-canary.31`) is fine, I think the suspect change is (https://github.com/vercel/next.js/pull/37526) but I'm not sure why.

It's hard to get a clear stack-trace from this bug, but I did get this screenshot.
![Screen Shot 2022-08-09 at 11 23 40 PM](https://user-images.githubusercontent.com/3061661/183839628-482447c8-7967-4d84-8705-ae47ad8c1eb1.png)

### Expected Behavior

I would expect that the existing behavior (no infinite re-render/hydration error) would happen.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-ckf9xg?file=pages/index.tsx

### To Reproduce

The reproduction shows the issue. If you run `npm run build && npm run start` you'll get an infinite error
```
main-52d6c7105de892eb.js:1 TypeError: Cannot read properties of null (reading 'content')
    at main-52d6c7105de892eb.js:1:11486
    at main-52d6c7105de892eb.js:1:11963
    at Array.forEach (<anonymous>)
    at Object.updateHead (main-52d6c7105de892eb.js:1:11334)
    at Object.t [as _pendingUpdate] (main-52d6c7105de892eb.js:1:88004)
    at main-52d6c7105de892eb.js:1:88443
    at ri (framework-4556c45dd113b893.js:1:93730)
    at Ss (framework-4556c45dd113b893.js:1:113957)
    at framework-4556c45dd113b893.js:1:110547
    at S (framework-4556c45dd113b893.js:1:138450)
```

**Comment by defjosiah** [comment]
We "fixed" it in our repo by removing the "<Head></Head>" tags.

**Comment by defjosiah** [comment]
Manual bisect log - I didn't use git bisect, it was easier to just do it manually and install the individual tagged canary releases. Then I inspected the changelog between "Good" and "Bad" to find the diff.

```
v12.1.1 (Good)
v12.1.1-canary.0
v12.1.1-canary.1
v12.1.1-canary.2
v12.1.1-canary.3
v12.1.1-canary.4
v12.1.1-canary.5
v12.1.1-canary.6
v12.1.1-canary.7
v12.1.1-canary.8
v12.1.1-canary.9
v12.1.1-canary.10
v12.1.1-canary.11
v12.1.1-canary.12
v12.1.1-canary.13
v12.1.1-canary.14
v12.1.1-canary.15
v12.1.1-canary.16
v12.1.1-canary.17
v12.1.1-canary.18
v12.1.2
v12.1.2-canary.0
v12.1.2-canary.1
v12.1.3
v12.1.3-canary.0
v12.1.3-canary.1
v12.1.3-canary.2
v12.1.3-canary.3
v12.1.3-canary.4
v12.1.4
v12.1.4-canary.0
v12.1.4-canary.1
v12.1.5
v12.1.5-canary.0
v12.1.5-canary.1
v12.1.5-canary.2
v12.1.5-canary.3
v12.1.5-canary.4
v12.1.5-canary.5
v12.1.5-canary.6
v12.1.5-canary.7
v12.1.6
v12.1.6-canary.0
v12.1.6-canary.1
v12.1.6-canary.2
v12.1.6-canary.3
v12.1.6-canary.4
v12.1.6-canary.5
v12.1.6-canary.6
v12.1.6-canary.7
v12.1.6-canary.8
v12.1.6-canary.9
v12.1.6-canary.10
v12.1.6-canary.11
v12.1.6-canary.12
v12.1.6-canary.13
v12.1.6-canary.14 (First step) - Good
v12.1.6-canary.15
v12.1.6-canary.16
v12.1.6-canary.17
v12.1.7-canary.0
v12.1.7-canary.1
v12.1.7-canary.2
v12.1.7-canary.3
v12.1.7-canary.4
v12.1.7-canary.5
v12.1.7-canary.6
v12.1.7-canary.7
v12.1.7-canary.8
v12.1.7-canary.9
v12.1.7-canary.10
v12.1.7-canary.11
v12.1.7-canary.12
v12.1.7-canary.13
v12.1.7-canary.14
v12.1.7-canary.15
v12.1.7-canary.16
v12.1.7-canary.17
v12.1.7-canary.18
v12.1.7-canary.19
v12.1.7-canary.20
v12.1.7-canary.21
v12.1.7-canary.22
v12.1.7-canary.23
v12.1.7-canary.24 (Second Step) -  Good
v12.1.7-canary.25
v12.1.7-canary.26
v12.1.7-canary.27
v12.1.7-canary.28
v12.1.7-canary.29
v12.1.7-canary.30
v12.1.7-canary.31 (Fourth Step) -  Good
v12.1.7-canary.32 (Sixth step) - Bad
v12.1.7-canary.33
###### install does not exist v12.1.7-canary.34 (Fifth Step) - 
v12.1.7-canary.35 (Fifth Step) - Bad
v12.1.7-canary.36
v12.1.7-canary.37
v12.1.7-canary.38 (Third Step) - Bad
v12.1.7-canary.39
v12.1.7-canary.40
v12.1.7-canary.41
v12.1.7-canary.42
v12.1.7-canary.43
v12.1.7-canary.44
v12.1.7-canary.45
v12.1.7-canary.46
v12.1.7-canary.47
v12.1.7-canary.48
v12.1.7-canary.49
v12.1.7-canary.50
v12.1.7-canary.51
v12.1.7-canary.52
v12.2.0
```

**Comment by SukkaW** [comment]
Any `<svg />` tag added to `<head />` violates HTML5 spec, thus adding it to `next/head` is not supported by Next.js, which might/could/would cause unexpected/unintended behavior, and is not guaranteed to work.
