### ISSUE TITLE
next/dynamic hydrate error

### ISSUE THREAD

**Issue by Capricair** [vercel/next.js#39522]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 16.16.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.2.5-canary.7
  eslint-config-next: 12.1.0
  react: 17.0.2
  react-dom: 17.0.2
```

### Describe the Bug

```
Warning: Did not expect server HTML to contain a <div> in <div>.
    at div
    at Homepage (webpack-internal:///./pages/index.js:21:26)
    at MyApp (webpack-internal:///./pages/_app.js:21:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23632)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:71:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:588:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:699:27)
```

### Expected Behavior

no error no warning

### Link to reproduction

https://github.com/Capricair/next-dynamic-issue

### To Reproduce

1. code
```
// homepage
import dynamic from "next/dynamic"

const Test = dynamic(() => import(`/components/test`))

function Homepage() {
  return (
    <div>
      <Test />
    </div>
  )
}

export default Homepage
```

```
// test component
function Test(){
  return <div>Test Component</div>
}

export default Test
```

2. npm run dev
3. open homepage

![image](https://user-images.githubusercontent.com/6244446/184278440-5231ec19-6eb0-41e6-8baa-1365e708bf7e.png)

**Comment by balazsorban44** [comment]
Thanks for reporting! It was hard to catch, but this is coming from when using backticks `

instead of `'` or `"` in your dynamic import.

I.e.: `import("/components/test")` won't show you this hydration warning.

We should allow backticks as well though. :+1:

**Comment by SukkaW** [comment]
I guess the issue is caused by the Next.js built-in webpack plugin `react-loadable-plugin`: It seems that `import()` with backtick (TemplateStringLiteral) is being parsed as an "un-analyzable" import.

**Comment by magic-akari** [comment]
@SukkaW Thanks for your Investigation, it is very useful.
