### ISSUE TITLE
next/image - TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by jtweaver** [vercel/next.js#39763]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.0.3-canary.7
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome Version 104.0.5112.79

### How are you deploying your application? (if relevant)

next build - Docker

### Describe the Bug

Giving next/image an S3 pre-signed URL for an image causes the error below and the image doesn't load. The image is a jpeg with a system defined metadata Content-Type of `image/jpg`.

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Mime.lookup (/app/node_modules/next/dist/compiled/send/index.js:44:1638)
    at Object.getContentType (/app/node_modules/next/dist/server/serve-static.js:35:17)
    at sendResponse (/app/node_modules/next/dist/server/image-optimizer.js:449:43)
    at Object.fn (/app/node_modules/next/dist/server/next-server.js:196:25)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:594:29)
    at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:299:20)
    at async Server.<anonymous> (/app/server.js:16:5)
```

When downloading the image via Postman using the same pre-signed URL, the `Content-Type` header is set to `image/jpg` in the response payload. The image loads everywhere else.

### Expected Behavior

The image should load and there should be no error messages in the server side logs.

### Link to reproduction

An AWS account would be required for this. Willing to help in any way

### To Reproduce

1. Have an S3 bucket with a jpeg image in it.
2. Use a backend language to generate a pre-signed URL for the image.
3. Pass that pre-signed URL to a next/image component.
4. Load the page in a browser.

**Comment by balazsorban44** [comment]
Could you paste the response headers that are being sent from S3 with `curl -I` or the image url?

From the stack trace it sounds like the issue is here: https://github.com/vercel/next.js/blob/7e9f9bfbef2cf4d63ceb899eeccf5bd0fcba2ec5/packages/next/server/image-optimizer.ts#L700

Sounds like we cannot detect the extension and getting the content type fails. 🤔

**Comment by jtweaver** [comment]
Here are the response headers and request query params. Credentials redacted

Response headers:
```
Server: AmazonS3
Content-Type: image/jpg
Content-Length: 932004
Accept-Ranges: bytes
x-amz-server-side-encryption: aws:kms
Date: Tue, 23 Aug 2022 03:09:47 GMT
Last-Modified: Sat, 20 Aug 2022 04:08:04 GMT
x-amz-request-id: 12345678910
```

Request query params:
```
https://bucket/c98fa742-fc2e-462f-a92e-459ea45054ab.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REDACTED%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220823T030738Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=REDACTED
```

**Comment by SukkaW** [comment]
@balazsorban44 @jtweaver I guess I have found out what the issue is.

The correct `content-type` for `.jpg` files should be `image/jpeg`, not `image/jpg`. And the `mime` package does exactly what it should do when an invalid/unknown `content-type` is given.

https://runkit.com/sukkaw/630483162039b900087efaf1

<img width="982" alt="image" src="https://user-images.githubusercontent.com/40715044/186099439-710f13c6-26b5-4f93-97cf-389758955522.png">

**Comment by ghislainDeffo** [comment]
Any update on this? We just moved from CRA to Next at work, and I'd like to enable image optimization without this risk.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
