### ISSUE TITLE
HookWebpackError: Cannot set properties of undefined (setting 'type')

### ISSUE THREAD

**Issue by aliSalehAbdulhadi** [vercel/next.js#39875]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

yarn run dev, npm run dev

### Describe the Bug

yarn run v1.22.19
$ next build
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

HookWebpackError: Cannot set properties of undefined (setting 'type')
    at makeWebpackError (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/webpack/bundle5.js:49590:9)
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/webpack/bundle5.js:33095:12
    at eval (eval at create (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/webpack/bundle5.js:23385:10), <anonymous>:34:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
TypeError: Cannot set properties of undefined (setting 'type')
    at /home/ali/Desktop/development/projects/daily-app/static/css/04a7d2f9c1ff8270.css:1335:3
    at flatten (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:64125)
    at getValue (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:63922)
    at normalizeBoxShadow (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:67038)
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:63635
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:72:18
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:55:18
    at Rule.each (/home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:41:16)
    at Rule.walk (/home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:52:17)
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:60:24
    at Root.each (/home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:41:16)
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot set properties of undefined (setting 'type')
    at /home/ali/Desktop/development/projects/daily-app/static/css/04a7d2f9c1ff8270.css:1335:3
    at flatten (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:64125)
    at getValue (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:63922)
    at normalizeBoxShadow (/home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:67038)
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/dist/compiled/cssnano-simple/index.js:190:63635
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:72:18
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:55:18
    at Rule.each (/home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:41:16)
    at Rule.walk (/home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:52:17)
    at /home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:60:24
    at Root.each (/home/ali/Desktop/development/projects/daily-app/node_modules/next/node_modules/postcss/lib/container.js:41:16)

> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected Behavior

On the main branch everything run as expected. But when I decided to add more features to my app (adding-inner-todos) and after completing, got this error while deploying to Vercel. then tried to build the app locally and got the same error.

Apparently its a webpack error. I'm not very familiar with webpack config or in general. not sure what data i need to provided more to be able to fix this issue. I linked my repo and the branch you can check it yourself.

### Link to reproduction

https://github.com/aliSalehAbdulhadi/Daily   branch: adding-inner-todos 

### To Reproduce

build the app

**Comment by SukkaW** [comment]
@aliSalehAbdulhadi 

I am afraid it is caused by a syntax error in your CSS:

https://github.com/aliSalehAbdulhadi/Daily/blob/63598b64f23ddbcb38d591d2cc915908946f18ff/styles/globals.css#L97

```css
-webkit-box-shadow: /*your box-shadow*/ , 0 0 0 50px white inset;
```

If you remove `/*your box-shadow*/ , `, the compilation error is then gone.

**Comment by aliSalehAbdulhadi** [comment]
Thanks a lot, @SukkaW, I should mind my copy-paste more carefully from now on lol. just wondering why it didn't show any error during development?
