### ISSUE TITLE
new project 2 -> cannot find module constants.js

### ISSUE THREAD

**Issue by di1606** [vercel/next.js#39936]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.6.0
      npm: 8.13.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

hi, 

I am setting up docker. I just installed next.js with typescript, so there is no external development dependency.
```

 => CACHED [builder 3/5] COPY --from=installer /usr/src/app/yarn.lock ./usr/src/app/                                                                                                               0.0s
 => CACHED [builder 4/5] COPY . .                                                                                                                                                                  0.0s
 => ERROR [builder 5/5] RUN yarn build                                                                                                                                                             4.4s
------                                                                                                                                                                                                  
 > [builder 5/5] RUN yarn build:                                                                                                                                                                        
#14 0.269 yarn run v1.22.19                                                                                                                                                                             
#14 0.290 $ next build                                                                                                                                                                                  
#14 0.522 info  - SWC minify release candidate enabled. https://nextjs.link/swcmin                                                                                                                      
#14 0.583 info  - Linting and checking validity of types...                                                                                                                                             
#14 2.110 info  - Creating an optimized production build...
#14 4.139 info  - Compiled successfully
#14 4.139 info  - Collecting page data...
#14 4.265 node:internal/process/promises:288
#14 4.265             triggerUncaughtException(err, true /* fromPromise */);
#14 4.265             ^
#14 4.265 
#14 4.265 Error: Cannot find module '../usr/src/app/node_modules/next/dist/shared/lib/constants.js'
#14 4.265 Require stack:
#14 4.265 - /usr/src/app/.next/server/pages/_document.js
#14 4.265 - /usr/src/app/node_modules/next/dist/server/require.js
#14 4.265 - /usr/src/app/node_modules/next/dist/server/load-components.js
#14 4.265 - /usr/src/app/node_modules/next/dist/build/utils.js
#14 4.265 - /usr/src/app/node_modules/next/dist/build/worker.js
#14 4.265 - /usr/src/app/node_modules/next/dist/compiled/jest-worker/processChild.js
#14 4.265     at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
#14 4.265     at mod._resolveFilename (/usr/src/app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
#14 4.265     at mod._resolveFilename (/usr/src/app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
#14 4.265     at Module._load (node:internal/modules/cjs/loader:804:27)
#14 4.265     at Module.require (node:internal/modules/cjs/loader:1022:19)
#14 4.265     at require (node:internal/modules/cjs/helpers:102:18)
#14 4.265     at 110 (/usr/src/app/.next/server/pages/_document.js:32:18)
#14 4.265     at __webpack_require__ (/usr/src/app/.next/server/webpack-runtime.js:25:42)
#14 4.265     at 30 (/usr/src/app/.next/server/chunks/30.js:333:18)
#14 4.265     at __webpack_require__ (/usr/src/app/.next/server/webpack-runtime.js:25:42) {
#14 4.265   type: 'Error',
#14 4.265   code: 'MODULE_NOT_FOUND',
#14 4.265   requireStack: [
#14 4.265     '/usr/src/app/.next/server/pages/_document.js',
#14 4.265     '/usr/src/app/node_modules/next/dist/server/require.js',
#14 4.265     '/usr/src/app/node_modules/next/dist/server/load-components.js',
#14 4.265     '/usr/src/app/node_modules/next/dist/build/utils.js',
#14 4.265     '/usr/src/app/node_modules/next/dist/build/worker.js',
#14 4.265     '/usr/src/app/node_modules/next/dist/compiled/jest-worker/processChild.js'
#14 4.265   ]
#14 4.265 }
#14 4.265 
#14 4.265 Node.js v18.6.0
#14 4.310 error Command failed with exit code 1.
#14 4.310 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

successfully build my app with dockerfile

### Link to reproduction

N/A

### To Reproduce

package.json
```
{
  "name": "front",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.2.5",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@types/node": "18.7.13",
    "@types/react": "18.0.17",
    "@types/react-dom": "18.0.6",
    "eslint": "8.22.0",
    "eslint-config-next": "12.2.5",
    "typescript": "4.7.4"
  }
}
```
Dockerfile
```
# ---------- Base ----------
FROM node:18.6 AS base

# Create app directory
WORKDIR /usr/src/app

# -------- Installer -------
FROM base AS installer

COPY package.json ./
COPY yarn.lock ./

# Install app dependencies
RUN yarn install

# -------- Builder ---------
FROM installer AS builder

ARG API_URL
ARG LEGACY_API_URL

ENV NEXT_PUBLIC_API_URL=${API_URL}
ENV NEXT_PUBLIC_LEGACY_API_URL=${LEGACY_API_URL}

COPY --from=installer /usr/src/app/node_modules ./usr/src/app/node_modules
COPY --from=installer /usr/src/app/package.json ./usr/src/app/
COPY --from=installer /usr/src/app/yarn.lock ./usr/src/app/

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

RUN yarn build

# ---------- Release ----------
FROM base AS release

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/yarn.lock ./
COPY --from=builder /usr/src/app/.next ./.next
COPY --from=builder /usr/src/app/public/ ./public
COPY --from=builder /usr/src/app/next.config.js ./

# Add cmd yarn pure ...

# Add a new user
RUN useradd -ms /bin/bash runner
USER runner

ENV PORT=80
ENV NODE_ENV=production

EXPOSE 80

CMD ["yarn", "start"]
```

**Comment by ijjk** [comment]
Hi, it sounds like your install failed or was corrupted, ensure you don't have a `.yarnclean` file or similar.

**Comment by di1606** [comment]
not, I don't have this file, 

I just fixed the bug, it comes from my dockerfile.

here is my new dockerfile

```
# ---------- Base ----------
FROM node:18.6 AS base
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# ---------- Builder ----------
FROM node:18.6 as builder
WORKDIR /usr/src/app 
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY . .
COPY --from=base /usr/src/app/node_modules ./node_modules
RUN yarn build

# ---------- Release ----------
FROM node:18.6 as release
WORKDIR /usr/src/app
ENV NODE_ENV=production
COPY --chown=node --from=builder /usr/src/app/next.config.js ./
COPY --chown=node --from=builder /usr/src/app/public ./public
COPY --chown=node --from=builder /usr/src/app/.next ./.next
COPY --chown=node --from=builder /usr/src/app/yarn.lock /usr/src/app/package.json ./
COPY --chown=node --from=builder /usr/src/app/node_modules ./node_modules
USER node
EXPOSE 3000
CMD [ "yarn", "start" ]
```
