### ISSUE TITLE
Serverless function error with custom 500 page

### ISSUE THREAD

**Issue by eprothro** [vercel/next.js#39952]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

N/A

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Server side functions that throw an (application level) error result in a `Runtime.ExitError` with `Error: Runtime exited with error: exit status 1` due to a `MissingStaticPage` being thrown.

```
2022-08-25T17:16:19.318Z	99155e5b-28a2-426f-a1bd-fedd6a849c7c	ERROR	MissingStaticPage [Error]: Failed to load static file for page: /en-US/500 ENOENT: no such file or directory, open '/var/task/.next/server/pages/en-US/500.html'
    at /var/task/node_modules/next/dist/server/require.js:55:19
    at async Promise.all (index 2)
    at async Object.loadComponents (/var/task/node_modules/next/dist/server/load-components.js:53:49)
    at async NextNodeServer.findPageComponents (/var/task/node_modules/next/dist/server/next-server.js:451:36)
    at async NextNodeServer.renderErrorToResponse (/var/task/node_modules/next/dist/server/base-server.js:1250:26)
    at async NextNodeServer.renderToResponse (/var/task/node_modules/next/dist/server/base-server.js:1188:30)
    at async NextNodeServer.pipe (/var/task/node_modules/next/dist/server/base-server.js:634:25)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:501:21)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:222:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:612:29)
2022-08-25T17:16:19.319Z	99155e5b-28a2-426f-a1bd-fedd6a849c7c	ERROR	Error: a test error has been manually thrown undefined
    at getServerSideProps (/var/task/.next/server/pages/test-77af5/server-side-error.js:43:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.renderToHTML (/var/task/node_modules/next/dist/server/render.js:490:20)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:908:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/var/task/node_modules/next/dist/server/base-server.js:1013:28)
    at async /var/task/node_modules/next/dist/server/response-cache.js:69:36 {
  page: '/test-77af5/server-side-error'
}
RequestId: 99155e5b-28a2-426f-a1bd-fedd6a849c7c Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Expected Behavior

No error to be thrown by the serverless function.

### Link to reproduction

https://github.com/eprothro/next-500-issue

### To Reproduce

1. Deploy on Vercel
2. Visit the index page
3. View the functions page for the Vercel deployment
4. See the error

**Comment by paales** [comment]
Experiencing this as well

**Comment by JannikSt** [comment]
+1
