### ISSUE TITLE
Dev server failed after build and export

### ISSUE THREAD

**Issue by Asoul** [vercel/next.js#40149]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
    Binaries:
      Node: 18.4.0
      npm: 8.12.1
      Yarn: 1.22.19
      pnpm: 7.2.1
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

After next build and export, the dev server will failed. Is this a normal workflow for next project, or is that something I missed? thanks!

### Expected Behavior

Dev server should not failed

### Link to reproduction

https://github.com/vercel/next.js

## Minimum Steps

```bash
# Tab 1
> yarn create next-app
> cd my-app && npm run dev

# --> Browser view good

# Tab 2
> cd my-app
> npx next build && npx next export 

# --> Browser reload failed after press Cmd + R
# --> Tab1 got error message about ENOENT

 ```

```bash
error - Error: ENOENT: no such file or directory, open '/Users/asoul/Projects/test-nextjs/my-app/.next/server/pages/index.js'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at Module._extensions..js (node:internal/modules/cjs/loader:1129:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (/Users/asoul/Projects/test-nextjs/my-app/node_modules/next/dist/server/require.js:58:12)
    at /Users/asoul/Projects/test-nextjs/my-app/node_modules/next/dist/server/load-components.js:56:50
    at async Promise.all (index 2) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/asoul/Projects/test-nextjs/my-app/.next/server/pages/index.js',
  page: '/'
}
```

**Comment by Asoul** [comment]
Note: My workaround is restart dev server every time I exported, want to know if there is another easier way to do it

**Comment by balazsorban44** [comment]
The `.next` directory is cleaned between builds, so if you are running `next dev` while building, it will miss files after the build is finished. You can disable this behavior by setting `cleanDistDir: false` in your `next.config.js`. See: https://nextjs.org/docs/upgrading#cleaning-the-distdir-is-now-a-default

**Comment by Asoul** [comment]
That's awesome, thank you! @balazsorban44
