### ISSUE TITLE
Json data error on read

### ISSUE THREAD

**Issue by selcukguler0** [vercel/next.js#40208]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Hi,

i created a simple API.
Im getting data from json file. Everything working fine locally but when i try to use it on vercel im getting this error.

```
[GET] /getAllCharacters
14:15:24:06
2022-09-04T11:15:27.005Z	aa3f7ac7-38f8-4be4-8cae-2a9ada98f0ff	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"SyntaxError: Unexpected token v in JSON at position 0","reason":{"errorType":"SyntaxError","errorMessage":"Unexpected token v in JSON at position 0","stack":["SyntaxError: Unexpected token v in JSON at position 0","    at JSON.parse (<anonymous>)","    at /var/task/index.js:36:16","    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)","    at next (/var/task/node_modules/express/lib/router/route.js:144:13)","    at Route.dispatch (/var/task/node_modules/express/lib/router/route.js:114:3)","    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)","    at /var/task/node_modules/express/lib/router/index.js:284:15","    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:346:12)","    at next (/var/task/node_modules/express/lib/router/index.js:280:10)","    at jsonParser (/var/task/node_modules/body-parser/lib/types/json.js:110:7)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: SyntaxError: Unexpected token v in JSON at position 0","    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)","    at process.emit (node:events:539:35)","    at emit (node:internal/process/promises:140:20)","    at processPromiseRejections (node:internal/process/promises:274:27)","    at processTicksAndRejections (node:internal/process/task_queues:97:32)"]}
Unknown application error occurred
```

API

```
const characterList = fs.readFileSync(path.join(__dirname, '/public/characterList.json'), "utf8");
JSON.parse(characterList)
```

JSON file

{
"character": [
{
	"name": "A O",
	"japanName": "A・O（アー・オー）",
	"romanName": "Ā Ō",
}
]
}

also tried this json

[
{
	"name": "A O",
	"japanName": "A・O（アー・オー）",
	"romanName": "Ā Ō",
}
]

### Describe the Bug

JSON working in local not work on vercel

### Expected Behavior

Expected to see data from json

### Link to reproduction

https://api.onepiece.selcukguler.com/getAllCharacters

### To Reproduce

to repd

**Comment by adxmcollins** [comment]
I believe the issue you’re seeing is because when built to Vercel, the API functions are running inside a serverless environment which either doesn’t have access to the public folder or is not accessible using ‘__surname’.

Here’s a doc from Vercel which shows how you should be able to do this: https://vercel.com/guides/how-can-i-use-files-in-serverless-functions

**Comment by balazsorban44** [comment]
Since Next.js compiles your code into a separate directory you can't use `__dirname` as the path it will return will be different.

So the above answer is correct, please refer to the linked documentation. :pray: 

Here is a working deployment, using `process.cwd()`: https://balazsorban-40208.vercel.app/api/hello
