### ISSUE TITLE
Failed to build on GitHub Actions with Next.js 12.3

### ISSUE THREAD

**Issue by robertu7** [vercel/next.js#40831]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.7.0
      Yarn: 1.22.10
      pnpm: 6.11.0
    Relevant packages:
      next: 12.3.2-canary.7
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

`npm run build` is keep failing with the following error message on GitHub Actions, however, it's build success on my computer and Vercel:

```
info  - Compiled successfully
info  - Collecting page data...
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:5[52](https://github.com/thematters/matters-web/actions/runs/3111145523/jobs/5043100695#step:9:52):9)
    at new URL (node:internal/url:628:5)
    at Object.6926 (/home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:44:1)
    at __webpack_require__ (/home/runner/work/matters-web/matters-web/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:168:39)
    at /home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:169:71
    at Function.__webpack_require__.X (/home/runner/work/matters-web/matters-web/.next/server/webpack-runtime.js:207:21)
    at /home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:169:47
    at Object.<anonymous> (/home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:172:3) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.6926 (/home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:44:1)
    at __webpack_require__ (/home/runner/work/matters-web/matters-web/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:168:39)
    at /home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:169:71
    at Function.__webpack_require__.X (/home/runner/work/matters-web/matters-web/.next/server/webpack-runtime.js:207:21)
    at /home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:169:47
    at Object.<anonymous> (/home/runner/work/matters-web/matters-web/.next/server/pages/_document.js:172:3) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
> Build error occurred
Error: Failed to collect page data for /404
    at /home/runner/work/matters-web/matters-web/node_modules/next/dist/build/utils.js:916:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'Error'
}
```

### Expected Behavior

Build successfully

### Link to reproduction

https://github.com/thematters/matters-web/pull/2766

### To Reproduce

Run `npm run build` on both GitHub Actions and local computer.

**Comment by Raydman** [comment]
same with me

**Comment by menegat00** [comment]
same with me

**Comment by SukkaW** [comment]
@robertu7 After inspecting the source code of the repo, it is possible that the error is thrown by this: https://github.com/thematters/matters-web/blob/9af3b688519a258a7b971d808ad7521b5d887546/src/common/enums/csp.ts#L56

Have you checked that `NEXT_PUBLIC_API_URL` env is available?

**Comment by robertu7** [comment]
@SukkaW Great hunting! I can reproduce on my local via removing the `NEXT_PUBLIC_API_URL`. 

Just curious if it's caused by `_document` changes. Any references?

**Comment by SukkaW** [comment]
@robertu7

The `new URL` is introduced by `~/enum/csp`, which is being used in `_document`. That's how I found it.

AFAIK Next.js doesn't change `_document` parts recently, it is more likely related to how Next.js 12.3 handles `.env.*` files.

**Comment by robertu7** [comment]
> @robertu7
> 
> The `new URL` is introduced by `~/enum/csp`, which is being used in `_document`. That's how I found it.
> 
> AFAIK Next.js doesn't change `_document` parts recently, it is more likely related to how Next.js 12.3 handles `.env.*` files.

That's weird, I have [changed to `.env.local`](https://github.com/thematters/matters-web/pull/2766/commits/03cda2aeeba941eeda0f72d20db989dfc24c9fc1) (prior is `.env`) as local, still doesn't work.

**Comment by robertu7** [comment]
@SukkaW fixed by [adding `.env`](https://github.com/thematters/matters-web/pull/2766/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R54) before running `npm run build`.

I am going to close this issue, feel free to reopen if anyone needs.
