### ISSUE TITLE
Apps scaffolded with create-next-app fail right away

### ISSUE THREAD

**Issue by mixaildudin** [vercel/next.js#41331]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.24
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

I scaffolded a new app using `npx create-next-app next-app` (v12.3.1 of create-next-app seems to be used).
Then I did `cd next-app` and `npm run dev`. When I go to localhost:3000, the app gives me the following error (both in the terminal and in the browser):

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\user\Documents\next-app\node_modules\react\cjs\react.development.js:1618:21)
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:680:106)
    at renderWithHooks (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\user\Documents\next-app\node_modules\react\cjs\react.development.js:1618:21)
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:680:106)
    at renderWithHooks (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (c:\Users\user\Documents\next-app\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
```

The funny part is, this is all I did! That is, the app doesn't work right out of the box. The same thing happens on the other machine I have with nodejs@14.7.whatever on board.

### Expected Behavior

The new scaffolded app works fine (well, at least until I break it myself)

### Link to reproduction

nothing to show

### To Reproduce

```
npx create-next-app next-app
cd next-app
npm run dev
```

**Comment by balazsorban44** [comment]
I am unable to reproduce this. :thinking: Could you add a reproduction repository? :pray:

**Comment by mixaildudin** [comment]
Thought about that. Tried removing all globally installed packages completely, no effect.

All of a sudden, after a reboot it just started to work. On both machines. This is weird, but, well, okay :)

**Comment by ian** [comment]
I am running into the same issue. 

Working on a reproducible example but I believe this has to do with 12 + 13 being installed, possibly in a npm workspace context.

**Comment by ian** [comment]
Of interest is that `npx create-next-app@12 blog` will force install next@13.
