### ISSUE TITLE
Styled-components missing CSS when rendered client-side in turbopack example

### ISSUE THREAD

**Issue by thgh** [vercel/next.js#41801]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.0", newest: "12.3.2-canary.43".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

with-turbopack

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

The styled-components elements are mounted in the DOM, but the CSS is missing.

Actual:
<img width="516" alt="Screenshot 2022-10-25 at 21 36 46" src="https://user-images.githubusercontent.com/1109982/197865974-cd339409-5ec3-4bd4-b3ce-426044716760.png">

Expected:
<img width="491" alt="Screenshot 2022-10-25 at 21 37 02" src="https://user-images.githubusercontent.com/1109982/197866025-c86a1a07-9177-40c1-b311-541a30d6af3b.png">

Related DOM:
<img width="407" alt="Screenshot 2022-10-25 at 21 35 43" src="https://user-images.githubusercontent.com/1109982/197865790-2c87cd88-f583-4336-8693-11d7bd8c1846.png">

Related PR: #41789

Related line: https://github.com/vercel/next.js/blob/ba02680b7bd0e3f0830ab371ef1d25dbaab4404f/examples/with-turbopack/app/styling/styled-components/page.tsx#L5

Potentially related error when _server rendering_, there is no error when rendering client-side.
```
Warning: Prop `className` did not match. Server: "sc-hvuYJx bOwUPp" Client: "SkeletonImg-sc-4bc32d60-2 gfaKhz"
    at div
    at forwardRef (http://localhost:3000/_next/static/chunks/node_modules_589e6e.js:1237:16)
    at div
    at forwardRef (http://localhost:3000/_next/static/chunks/node_modules_589e6e.js:1237:16)
    at Skeleton
    at div
    at forwardRef (http://localhost:3000/_next/static/chunks/node_modules_589e6e.js:1237:16)
    at div
    at Page
    at div
    at InnerLayoutRouter (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:93:30)
    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:206:9)
    at RedirectBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:212:29)
    at NotFoundBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:243:29)
    at LoadingBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:167:28)
    at ErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:588:26)
    at RenderFromTemplateContext (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_render-from-template-context.js:15:34)
    at OuterLayoutRouter (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:20:30)
    at StyleSheetManager (http://localhost:3000/_next/static/chunks/node_modules_589e6e.js:906:176)
    at StyledComponentsRegistry (http://localhost:3000/_next/static/chunks/[project-with-next]_turbopack_8ce042.js:55:15)
    at StyledComponentsRegistry (http://localhost:3000/_next/static/chunks/[project-with-next]_turbopack_8ce042.js:17:11)
    at div
    at InnerLayoutRouter (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:93:30)
    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:206:9)
    at RedirectBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:212:29)
    at NotFoundBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:243:29)
    at LoadingBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:167:28)
    at ErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:588:26)
    at RenderFromTemplateContext (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_render-from-template-context.js:15:34)
    at OuterLayoutRouter (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:20:30)
    at div
    at div
    at div
    at InnerLayoutRouter (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:93:30)
    at RedirectErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:206:9)
    at RedirectBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:212:29)
    at NotFoundErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:237:9)
    at NotFoundBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:243:29)
    at LoadingBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:167:28)
    at ErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:588:26)
    at RenderFromTemplateContext (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_render-from-template-context.js:15:34)
    at OuterLayoutRouter (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:20:30)
    at div
    at div
    at div
    at body
    at html
    at ErrorBoundary (http://localhost:3000/_next/static/chunks/[embedded_modules]_@vercel_turbopack-next_2f51ae.js:1387:1)
    at ReactDevOverlay (http://localhost:3000/_next/static/chunks/[embedded_modules]_@vercel_turbopack-next_2f51ae.js:755:11)
    at HotReload (http://localhost:3000/_next/static/chunks/[embedded_modules]_@vercel_turbopack-next_2f51ae.js:21:11)
    at Router (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:319:19)
    at ErrorBoundaryHandler (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:577:9)
    at ErrorBoundary (http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_components_89f843.js:588:26)
    at AppRouter
    at ServerRoot (http://localhost:3000/_next/static/chunks/[project-with-next]_turbopack_4afe3f.js:241:11)
    at RSCComponent
```

### Expected Behavior

It should render styled-components without having to refresh the page.

### To Reproduce

* Follow steps on https://turbo.build/pack/docs
* `npx create-next-app --example with-turbopack`
* `yarn dev`
* Open `http://localhost:3000/styling` in browser
* Click on styled-components
* The page does not show cards
* Refresh
* The page shows cards

**Comment by balazsorban44** [comment]
Please provide this feedback here https://github.com/vercel/turbo/discussions/2312
