### ISSUE TITLE
Next 13 - next export issue

### ISSUE THREAD

**Issue by dmerchier** [vercel/next.js#42282]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

> my-app2@0.1.0 info
> next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.1
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

next export doesn't work as expected with a new project on my project after the migration to nextjs 13.
I tried to do the same thing on a new project:

```shell
npx create-next-app@latest --experimental-app --ts my-app
cd my-app
npx --no-install next build && npx --no-install next export -o .dist
```

will throw
```
Route (app)                                Size     First Load JS
─ ○ /                                      0 B                0 B
+ First Load JS shared by all              64.2 kB
  ├ chunks/17-521a5439222a82c0.js          62 kB
  ├ chunks/main-app-5dbe79f35bd947e6.js    200 B
  └ chunks/webpack-9e765e27c32b1a64.js     2.07 kB

Route (pages)                              Size     First Load JS
┌ ○ /404                                   179 B          79.8 kB
└ λ /api/hello                             0 B            79.6 kB
+ First Load JS shared by all              79.6 kB
  ├ chunks/main-8b1401f2e64382f7.js        77.3 kB
  ├ chunks/pages/_app-9f5490aa3d56632f.js  192 B
  └ chunks/webpack-9e765e27c32b1a64.js     2.07 kB

...

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - using build directory: /home/damien/my-app/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/home/damien/my-app/next.config.js". Generating map from "./pages"
info  - Launching 15 workers
warn  - Statically exporting a Next.js application via `next export` disables API routes.
This command is meant for static-only hosts, and is not necessary to make your application static.
Pages in your application without server-side data dependencies will be automatically statically exported by `next build`, including pages powered by `getStaticProps`.
Learn more: https://nextjs.org/docs/messages/api-routes-static-export
info  - Copying "public" directory
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /
    at Object.getPagePath (/home/damien/my-app/node_modules/next/dist/server/require.js:77:15)
    at /home/damien/my-app/node_modules/next/dist/export/index.js:373:48
    at Array.map (<anonymous>)
    at /home/damien/my-app/node_modules/next/dist/export/index.js:364:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/home/damien/my-app/node_modules/next/dist/trace/trace.js:79:20) {
  code: 'ENOENT'
}
```

### Expected Behavior

I should be able to export static pages from my project.

### Link to reproduction

No link

### To Reproduce

```shell
npx create-next-app@latest --experimental-app --ts my-app
cd my-app
npx --no-install next build && npx --no-install next export -o .dist
```

**Comment by awareness481** [comment]
`next export` is still not supported for the `app` folder. See planned features: https://beta.nextjs.org/docs/app-directory-roadmap#planned-features

**Comment by dmerchier** [comment]
Sorry I missed this information.
