### ISSUE TITLE
Edge runtime giving 500 error on vercel with route groups

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#42387]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Sun Oct 16 18:11:16 PDT 2022; root:xnu-8792.60.32.0.1~11/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.18
      pnpm: 7.1.0
    Relevant packages:
      next: 13.0.2-canary.0
      eslint-config-next: N/A
      react: N/A
      react-dom: N/A

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When deploying with vercel, every page within a group gives a 500 error, in my app i'm using group to provide an error boundary in root pages. 

I also tried to see this on the `app-dir` example provided by nextjs, and it seems to bug on the route groups. 

The logs in vercel show this :

```bash
2022-11-02T21:52:33.790Z	4e64120d-d3e0-4fa3-9cb5-a32e7802f79b	ERROR	ReferenceError: self is not defined
    at Object.<anonymous> (/var/task/webapp/.next/server/app/(root)/page.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (/var/task/node_modules/.pnpm/next@13.0.1-canary.1_yh4i277f6ufllgtdszlodalmum/node_modules/next/dist/server/require.js:88:12)
    at /var/task/node_modules/.pnpm/next@13.0.1-canary.1_yh4i277f6ufllgtdszlodalmum/node_modules/next/dist/server/load-components.js:37:73
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/'
}
RequestId: 4e64120d-d3e0-4fa3-9cb5-a32e7802f79b Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Expected Behavior

It should not throw an error... (i think ?)

### Link to reproduction

https://github.com/Fredkiss3/nextjs-13-react-router-contacts

### To Reproduce

Go to the the website, you can deploy to your vercel account or go to the website url (you will only the 500 error though).
Or go to this example : http://app-directory-next-13.vercel.app/ then go to the route groups you will see the same error.

**Comment by spencerbeggs** [comment]
I see this error without a route group as well:

```json
{
  "level": "error",
  "message": "ReferenceError: self is not defined\n    at Object.<anonymous> (/var/task/.next/server/app/page.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.requirePage (/var/task/node_modules/next/dist/server/require.js:88:12)\n    at /var/task/node_modules/next/dist/server/load-components.js:37:73\n    at processTicksAndRejections (node:internal/process/task_queues:96:5) {\n  page: '/'\n}\nRequestId: 6e63314b-122c-4628-b2db-9451b89a6bc5 Error: Runtime exited with error: exit status 1\nRuntime.ExitError",
  "request": {
    "host": "nextjs-template-spencerbeggs.vercel.app",
    "id": "iad1:iad1::dq9vn-1667488472077-1855f88d6460",
    "ip": "108.54.185.106",
    "method": "GET",
    "path": "/",
    "scheme": "https",
    "statusCode": 500,
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
  },
  "vercel": {
    "deploymentId": "dpl_T88VeQHxdXqd3V5FYL8YyTnDCwBE",
    "deploymentURL": "nextjs-template-ifuz3k4zb-spencerbeggs.vercel.app",
    "environment": "production",
    "projectId": "prj_HRnXCXZpAMNsqJ5ZxP4ROKPTsA8W",
    "projectName": "nextjs-template",
    "region": "iad1",
    "route": "/en-US",
    "source": "lambda-log",
    "userName": "spencerbeggs"
  }
}
```

**Comment by spencerbeggs** [comment]
You know what, I had `i18n` set in my config. Removing that let it deploy and I no longer see this error.

**Comment by alvarlagerlof** [comment]
Also seeing this:

Preview url: https://portfolio-gpm8sa1sx-lagerlof.vercel.app/about
Pull request: https://github.com/alvarlagerlof/portfolio/pull/584

Error:

```
2022-11-05 13:44:04.961 [portfolio] 500 GET portfolio-gpm8sa1sx-lagerlof.vercel.app /about XX.XXX.XXX.XX START RequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913 Version: $LATEST
2022-11-05T12:44:06.177Z	d6941b6c-0b4b-4cc1-9525-dc048db77913	ERROR	ReferenceError: self is not defined
    at Object.<anonymous> (/var/task/.next/server/app/(main)/about/page.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (/var/task/node_modules/next/dist/server/require.js:88:12)
    at /var/task/node_modules/next/dist/server/load-components.js:37:73
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/about'
}
RequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913 Error: Runtime exited with error: exit status 1
Runtime.ExitError
END RequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913
REPORT RequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913	Duration: 97.05 ms	Billed Duration: 98 ms	Memory Size: 1024 MB	Max Memory Used: 106 MB	
```

```
{
    "vercel": {
        "deployment_id": "dpl_7q1PRCwJ27HRU2UZQC71zCLp83yu",
        "host": "portfolio-gpm8sa1sx-lagerlof.vercel.app",
        "id": "1667652245286883221570081558",
        "path": "about",
        "project_id": "QmbkgPDvFUUZCukE9PioUT1jrWDTvb3T5tL3aynfnEY3a8",
        "proxy": {
            "client_ip": "XX.XXX.XXX.XX",
            "errorCode": "FUNCTION_INVOCATION_FAILED",
            "host": "portfolio-gpm8sa1sx-lagerlof.vercel.app",
            "method": "GET",
            "path": "/about",
            "referer": "https://portfolio-gpm8sa1sx-lagerlof.vercel.app/",
            "region": "arn1",
            "scheme": "https",
            "status_code": 500,
            "timestamp": 1667652244961,
            "user_agent": {
                "0": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
            },
            "vercelCache": "MISS"
        },
        "request_id": "arn1:arn1::zjl9h-1667652244961-c127061ab740",
        "source": "lambda",
        "source_type": "http",
        "statusCode": 500
    },
    "dt": "1667652244961",
    "message": "START RequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913 Version: $LATEST\n2022-11-05T12:44:06.177Z\td6941b6c-0b4b-4cc1-9525-dc048db77913\tERROR\tReferenceError: self is not defined\n    at Object.<anonymous> (/var/task/.next/server/app/(main)/about/page.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.requirePage (/var/task/node_modules/next/dist/server/require.js:88:12)\n    at /var/task/node_modules/next/dist/server/load-components.js:37:73\n    at processTicksAndRejections (node:internal/process/task_queues:96:5) {\n  page: '/about'\n}\nRequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913 Error: Runtime exited with error: exit status 1\nRuntime.ExitError\nEND RequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913\nREPORT RequestId: d6941b6c-0b4b-4cc1-9525-dc048db77913\tDuration: 97.05 ms\tBilled Duration: 98 ms\tMemory Size: 1024 MB\tMax Memory Used: 106 MB\t\n",
    "platform": "Vercel"
}
```

**Comment by mrkldshv** [comment]
Having the same issue. Can confirm removing `i18n` option from the config fixed it.

**Comment by alvarlagerlof** [comment]
> Having the same issue. Can confirm removing `i18n` option from the config fixed it.

That did not work for me. Is your repo public so I can compare?

**Comment by spencerbeggs** [comment]
@alvarlagerlof It is here: https://github.com/spencerbeggs/nextjs-template

This is a work-in-progress and my docs are incomplete.

**Comment by weyert** [comment]
I am having this error with 13.0.3 too while not using `i18n` in `next.config.js`

**Comment by Fredkiss3** [comment]
I dis not word this issue correctly, it is about route groups like this : 

ˋ`ˋ
app
     (root)
        page.tsx
     layout.tsx 
ˋ`ˋ

And not anything else 🤦‍♂️.
If you have an issue about i18n, please do so in another issue or open one if you want.

Thank you.

**Comment by spencerbeggs** [comment]
I am just trying to be helpful as I encountered the exact same error and the solution had to do with incompatible config items. 🤷🏻‍♂️

**Comment by Winwardo** [comment]
@Fredkiss3 Did you mean to close this issue?
I'm still experiencing this same problem of pages returning 500 if using edge runtime in a route group (and I do not use i18n in my code-base either).

**Comment by Fredkiss3** [comment]
@Winwardo yes the problem is that the issue was about route groups and not i18n and i don't see what is the relation between those two, and like you i didn't use i18n.

Right now it isn't a pain for me since i don't really use vercel to deploy my nextjs projects, but feel free to open another issue. Maybe that one will be picked by nextjs core team.

**Comment by spencerbeggs** [comment]
Please accept my sincerest apologies for trying to help.
