### ISSUE TITLE
Next.js 13 server rendering + Antd gives error "TypeError: Super expression must either be null or a function"

### ISSUE THREAD

**Issue by davidbnk** [vercel/next.js#42553]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
    Platform: linux
    Arch: x64
    Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
  Binaries:
    Node: 18.11.0
    npm: 8.19.2
    Yarn: 1.22.19
    pnpm: N/A
  Relevant packages:
    next: 13.0.3-canary.0
    eslint-config-next: N/A
    react: 18.2.0
    react-dom: 18.2.0

### Describe the Bug

Using any ant design component and rendering on the server will give the error "TypeError: Super expression must either be null or a function". 

```
error - TypeError: Super expression must either be null or a function
    at _inherits (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/inherits.js:5:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/DomWrapper.js:16:28)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/DomWrapper.js:31:2)
    at (sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/DomWrapper.js (/home/david/next-test/.next/server/app/page.js:9093:1)
    at __webpack_require__ (/home/david/next-test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/index.js:13:42)
    at (sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/index.js (/home/david/next-test/.next/server/app/page.js:9104:1)
    at __webpack_require__ (/home/david/next-test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/index.js:12:46)
    at (sc_server)/./node_modules/rc-resize-observer/lib/index.js (/home/david/next-test/.next/server/app/page.js:9115:1) {
  type: 'TypeError',
  page: '/'
}
```

### Expected Behavior

No error should happen

### Link to reproduction

https://github.com/davidbnk/next-13-antd-bug

### To Reproduce

1. Create new app: `npx create-next-app@latest --experimental-app`
2. Install antd into the project: `npm install antd`
3. Use any antd component:
```
import "antd/dist/antd.css";
import { Alert } from "antd";

export default function Home() {
  return (
    <div>
      <main>
      <Alert message="Hello World" />
      </main>
    </div>
  )
}
```

If you transform the component into a client compoment with `"use client";`, it will work

**Comment by balazsorban44** [comment]
This is expected, as interactive elements are meant to be Client Components, which requires the `'use client'` directive.

See: https://beta.nextjs.org/docs/rendering/server-and-client-components#when-to-use-server-vs-client-components
