### ISSUE TITLE
Cannot find module 'next/dist/server/node-polyfill-fetch' when creating new app with yarn

### ISSUE THREAD

**Issue by robko23** [vercel/next.js#42651]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
  Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022
    Binaries:
      Node: 18.1.0
      npm: 8.8.0
      Yarn: 3.2.4
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.3-canary.1
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

When creating new next app with `yarn create next-app --experimental-app` and enabling turbopack, it will result in several warnings and error:

```
warning - [other] 
  Could not resolve React Refresh runtime
  React Refresh will be disabled.
  To enable React Refresh, install the `react-refresh` and `@next/react-refresh-utils` modules.

warning - [other] 
  Could not resolve React Refresh runtime
  React Refresh will be disabled.
  To enable React Refresh, install the `react-refresh` and `@next/react-refresh-utils` modules.

warning - [other] 
  Could not resolve React Refresh runtime
  React Refresh will be disabled.
  To enable React Refresh, install the `react-refresh` and `@next/react-refresh-utils` modules.

error -
  [rendering]
    [root of the dev server]/
      Error during SSR Rendering
      Error: Cannot find module 'next/dist/server/node-polyfill-fetch'
        at <unknown> (.next/server/app/chunks/ssr/_4b5bba.js:83:15)
        at <unknown> (.next/server/app/chunks/ssr/_4b5bba.js:86:3)
        at [project-with-next]/app/entry (ecmascript, ssr) (.next/server/app/chunks/ssr/_4b5bba.js:313:3)
        at <unknown> (.next/server/app/chunks/ssr/_4b5bba.js:692:21)
        at runModuleExecutionHooks (.next/server/app/chunks/ssr/_4b5bba.js:730:5)
        at instantiateModule (.next/server/app/chunks/ssr/_4b5bba.js:691:5)
        at instantiateRuntimeModule (.next/server/app/chunks/ssr/_4b5bba.js:1276:12)
        at <unknown> (.next/server/app/chunks/ssr/_4b5bba.js:331:1)
        at <unknown> (.next/server/app/chunks/ssr/_4b5bba.js:1327:39)
        at <anonymous>
        at Object.registerChunk [as push] (.next/server/app/chunks/ssr/_4b5bba.js:1327:25)
        at Object.<anonymous> (.next/server/app/chunks/rsc/app_layout.tsx_layout-entry.tsx_with-client-chunks.js:1:41)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Module._load (node:internal/modules/cjs/loader:827:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (.next/server/app/index.js:12:1)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Module._load (node:internal/modules/cjs/loader:827:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
        at <unknown> (node:internal/main/run_main_module:17:47)

  [resolve]
    [next]/entry/fallback.tsx
      Error resolving esm request
      unable to resolve module "react" with subpath "/jsx-runtime"

      Error resolving esm request
      unable to resolve module "react-dom" with subpath "/client"

    [next]/overlay/internal/ErrorBoundary.tsx
      Error resolving esm request
      unable to resolve module "react"

      Error resolving esm request
      unable to resolve module "react" with subpath "/jsx-runtime"

    [next]/overlay/internal/ReactDevOverlay.tsx
      Error resolving esm request
      unable to resolve module "react"

      Error resolving esm request
      unable to resolve module "react" with subpath "/jsx-runtime"

    ... [24 more paths] are hidden, run with --show-all to show all
```

### Expected Behavior

It should display default nextjs page after project creation

### Link to reproduction

---

### To Reproduce

1. Run `yarn create next-app --experimental-app`
2. edit package.json to `"dev": "next dev --turbo",`
3. Run it with `yarn dev`

**Comment by robko23** [comment]
I have had trouble recreating this issue on my work machine, however I managed to create dockerfile where the bug still is.

```Dockerfile
FROM node:18

RUN apt update

RUN apt install -y jq moreutils

RUN corepack enable

RUN corepack prepare yarn@stable --activate

RUN yarn create next-app --experimental-app --ts --eslint test

WORKDIR /test

RUN jq '.scripts.dev = "next dev --turbo"' package.json | sponge package.json

CMD yarn dev
```

To set it up run:
`docker build -t next-42651 .`

`docker run --rm -it -p 3000:3000 next-42651`

**Comment by balazsorban44** [comment]
Thanks, I could reproduce it with Yarn 2+. `pnpm`, Yarn 1, and `npm` work fine.

**Comment by millsp** [comment]
I am seeing this too in a `pnpm` monorepo

**Comment by millsp** [comment]
I found that in `standalone/node_modules/next` points to `.pnpm/next@12.../next/dist/server/next-server.js`. That file exists but none of its imports are present.

**Comment by millsp** [comment]
Same happens with `npm` workspaces

**Comment by belgattitude** [comment]
Here's a reproduction with 

- PNPM 8.4.0 
- monorepo 
- node.js v18.16.0
- auto-peers-deps false -> https://github.com/belgattitude/artist/blob/main/.npmrc

Clone: https://github.com/belgattitude/artist/pull/4

```bash
corepack enable
pnpm install
cd apps/web
pnpm dev --turbo
```

**Comment by sokra** [comment]
We currently don't support Yarn PnP, but you can use `yarn config set nodeLinker node-modules` to switch to normal node_modules mode for Yarn, which should work.

**Comment by altechzilla** [comment]
`Error: Cannot find module 'next/dist/server/node-polyfill-fetch'`
... when trying to load an app with Turbopack.

**Comment by ForsakenHarmony** [comment]
Just a note: this is currently very low priority as we would have to implement the whole pnp resolution for turbopack

**Comment by arcanis** [comment]
I already implemented the PnP resolution for Rust as a crate, in https://github.com/arcanis/pnp-rust. I'm very open to merge any change necessary to make it easier to use on your side.

**Comment by christianjuth** [comment]
The Trubo brand has done an amazing job of pushing monorepo tooling forward. Similarly PnP has been a big life improvement for managing a large monorepo. I believe lack of support for PnP would be a big miss for the Turbo brand as great monorepo compatible tooling.

Part of the Turbo philosophy is [**"never doing the same work twice"**](https://turbobuild.org/repo/docs/core-concepts/remote-caching). I believe [Yarn Zero-installs](https://yarnpkg.com/features/caching#zero-installs) operates under the same philosophy.

I understand that PnP is less popular then traditional node_modules, but a Turbo Pack + PnP combo would be a big quality of live improvement for large projects. I understand you have a lot more people to answer to then just us PnP folk, but I urge the team to reconsider support. Is it possible @arcanis existing work could be used to mane PnP happen?

Thanks for all the hard work the teams does!

**Comment by mehdad-hussain** [comment]
Hello, is there any update for pnp support for turbo pack ?

**Comment by vycos-zen** [comment]
hi folks, 

I was just reading the new Turbopack improvement release notes and got excited to try it. I been working, and experimenting with NextJs in the past few years as semi hobby project and got a Yarn PnP monorepo together with multi app deployments via Vercel. Sadly I realized, Turbopack is not supporting this structure at this time right in this thread. I hope to see it working one day, and thanks for all the hard work put into making life better on the development end. <3

Best Regards

**Comment by skorphil** [comment]
> Any news?

No, use NX

**Comment by timneutkens** [comment]
Hey all,
At this point we're not planning to add Yarn PnP to Turbopack. I know this is likely not what you were hoping to hear but at this point in time we can't justify the maintenance based on 17 thumbs up over 3 years. Feel free to open a feature request on GitHub discussions to track if you still would like to see this as a features.

**Comment by arcanis** [comment]
I don't really mind either way, but I don't think it'd be a significant maintenance cost at least; it got merged in rspack in less than a week. As for counting the thumbs up, that doesn't seem a very good metric imo - if only because [a random post in the middle of thread](https://github.com/vercel/next.js/issues/42651#issuecomment-2015433748) got 30 hearts, which at least shows that the amount of lurkers is greater than you think.
