### ISSUE TITLE
function style `next.config.js` seems to be ignored when `--turbo` enabled

### ISSUE THREAD

**Issue by h-takeyeah** [vercel/next.js#43001]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000
    Binaries:
      Node: 16.17.1
      npm: 9.1.1
      Yarn: 1.22.19
      pnpm: 7.5.2
    Relevant packages:
      next: 13.0.4-canary.2
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

## Overview
When write up configuration as function style in `next.config.js` and run `next dev --turbo`, the configuration is ignored. This is not produced when using object export.

- When I write config like this, "myConfig" is ignored by turbopack
```javascript
module.exports = (phase, { defaultConfig }) => {
  /** @type {import('next').NextConfig} */
  const myConfig = {
    /* custom configuration */
  }
  return config
}
```

- This style has no problem (as used [this example](https://github.com/vercel/next.js/tree/canary/examples/with-turbopack) and as documented [here](https://nextjs.org/docs/advanced-features/turbopack))
```javascript
/** @type {import('next').NextConfig} */
const myConfig = {
  /* custom configuration */
}
module.exports = myConfig
```

### Matrix
||w/o `--turbo`|`--turbo`|
|---|---|---|
|**object export**|OK|OK|
|**function export**|OK|NG (this issue)|

### Expected Behavior

The function style nextConfig loaded properly in case of `--turbo` option passed to `next dev`.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/h-takeyeah/nextjs-bug-report/tree/funcconf-turbo

### To Reproduce

1. Clone my repository [here](https://github.com/h-takeyeah/nextjs-bug-report/tree/funcconf-turbo)
3. `npm i`
4. `npm run dev`

That repository is copy of an example project, *with-turbopack*.

Then you will see the process exits. It is expected that server boots and starts to listen.

:memo: The configuration `next.config.js` is seems to take effect when omitting `--turbo` (i.e. just `npx next dev`).

**Comment by h-takeyeah** [comment]
:note: (outdated) Current release (13.0.3) had emitted an error message like this:
```plain
Error: > The `app` dir is experimental. Please add `{experimental:{appDir: true}}` to your `next.config.js` to enable it
    at findPagesDir (/home/youtaku/prog/github.com/h-takeyeah/nextjs-bug-report/node_modules/next/dist/lib/find-pages-dir.js:80:19)
    at /home/youtaku/prog/github.com/h-takeyeah/nextjs-bug-report/node_modules/next/dist/cli/next-dev.js:271:48
```

**Comment by h-takeyeah** [comment]
I know the document [Turbopack (alpha)](https://nextjs.org/docs/advanced-features/turbopack) recommends using [this example](https://github.com/vercel/next.js/tree/canary/examples/with-turbopack) on project startup, and know the example is written in object export style. So I respect next.js team's intention if function style configuration won't be supported by turbopack (*next integrated* turbopack).

I think missing normalization at loading config is cause of this issue.
1. `loadConfig` skips normalization because final parmeter *rawConfig* set `true` [here](https://github.com/vercel/next.js/blob/3fe9b4c867d0b3019be6aef54f0832e0fcf109a2/packages/next/cli/next-dev.ts#L182)
  https://github.com/vercel/next.js/blob/3fe9b4c867d0b3019be6aef54f0832e0fcf109a2/packages/next/server/config.ts#L848-L850
  https://github.com/vercel/next.js/blob/3fe9b4c867d0b3019be6aef54f0832e0fcf109a2/packages/next/server/config.ts#L857

2. When `typeof *rawNextConfig* === 'function'`, `Object.keys(rawNextConfig)` returns an empty array and succeeding validations are not run (i.e. always pass).
  https://github.com/vercel/next.js/blob/3fe9b4c867d0b3019be6aef54f0832e0fcf109a2/packages/next/cli/next-dev.ts#L221-L223
