### ISSUE TITLE
next.js problem compiling - node modules error

### ISSUE THREAD

**Issue by anthonygarced** [vercel/next.js#43086]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 19.1.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Not relevant, but Chrome

### How are you deploying your application? (if relevant)

installed via npx create-next-app

### Describe the Bug

You can see the error here:
`wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 80 ms (187 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\garced\Documents\anthonygarced.com\my-app\node_modules\react\cjs\react.development.js:1618:21)
    at Html (webpack-internal:///../../../AppData/Roaming/npm/node_modules/next/dist/pages/_document.js:678:104)
    at renderWithHooks (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (C:\Users\garced\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)`

I have checked multiple times, there is no duplicates of any react folder, I reinstalled the next.js variables by installing them multiple times in different folders, and BY default it creates this error every single time.

I even reinstalled node,js and react and it still creates this issue. I also made a post on StackOverflow, but got no response.
I'm lilkely missing something here, but I'd thought I would make an issue here and see if this would help with the issue.

### Expected Behavior

I expected to see the default page when you first installed next.js, which would be how to get started.

Instead, I got a context error.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/anthonygarced/test-example

### To Reproduce

_This should be how you do it here:_

1. Open VSC (Visual Studio Code)
2.. ctrl `, npx install create-next-app
3. This does not matter if you install ESLint or TypeScript, this issue occurs via the node_modules

**Comment by balazsorban44** [comment]
The repo is private, could you make sure we can access the reproduction?

**Comment by anthonygarced** [comment]
Sure thing.  

One problem is: I do have to upload the entirety of the **node_modules** folder. I will figure this out when I get home, but

**Comment by balazsorban44** [comment]
It's unclear why you would need to upload the `node_modules` folder.
