### ISSUE TITLE
Random Vercel runtime errors invariant: invalid Cache-Control duration provided: 0 < 1

### ISSUE THREAD

**Issue by transitive-bullshit** [vercel/next.js#43157]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.15.0
    Relevant packages:
      next: 13.0.5-canary.2
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I'm experiencing this error for seemingly random pages on my site using `appDir`.

I am not changing the default caching options, and other pages of the same segment load fine, though once a page experiences this error, it seems to stick.

These errors don't repro on dev or local build; only on Vercel.

```
[GET] /titles/8587
18:25:23:52
2022-11-20T00:25:25.933Z	494244e3-c28b-4fe7-bb20-aa189128b892	ERROR	Error: invariant: invalid Cache-Control duration provided: 0 < 1
    at Object.setRevalidateHeaders (/var/task/node_modules/.pnpm/next@13.0.5-canary.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/send-payload/revalidate-headers.js:13:19)
    at Object.sendRenderResult (/var/task/node_modules/.pnpm/next@13.0.5-canary.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/send-payload/index.js:62:33)
RequestId: 494244e3-c28b-4fe7-bb20-aa189128b892 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Expected Behavior

These pages should load fine with no errors.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/transitive-bullshit/next-movie/tree/feature/next-themes-beta

### To Reproduce

1. Visit https://next-movie-ainytmtbp-saasify.vercel.app/titles/8587
2. Notice the 500 error
3. Check the vercel function logs for the above error

The branch in question for the repro case uses cookies via https://github.com/pacocoursey/next-themes/issues/152 which may be related.

**Comment by ruucm** [comment]
I had a similar issue, and it turned out to be caused by the combination of static site generation (of dynamic routes) + using cookies on the server-side.

I used `generateStaticParams` with an empty array but when I added a mock value the error disappeared and ISR works correctly.

**Comment by maurice-re** [comment]
I also ran into this. Did not use cookies but did use searchParams

**Comment by pmarsceill** [comment]
I ran into this recently. Anyone have any idea of how to troubleshoot it or possible work arounds?

**Comment by remib18** [comment]
I have a similar issue every time I go on a route with a `dynamic segment`. They're all SSR.

It works fine with the development server but throw the error in the production server. I also tried with the local production server so it's not related to Vercel.

Note that I also tried with Next 13.1.2 and 13.1.3-canary.0 (latest canary).

**Comment by homanp** [comment]
Any updates regarding this issue? Seeing it as well.

**Comment by schemburkar** [comment]
v13.1.1 seems not to have this issue. I rolled back to that version without any issues.

**Comment by homanp** [comment]
> v13.1.1 seems not to have this issue. I rolled back to that version without any issues.

Will give it a try.

**Comment by nilscox** [comment]
I am also having the issue in 13.1.2 but not in 13.1.1, and I did nothing else than `yarn add next@13.1.1` (without caret, to install this exact version).

**Comment by pmarsceill** [comment]
I'm also seeing it in `13.1.1`

**Comment by jvmusin** [comment]
I have this bug on `13.1.2`, but it works well with `13.1.1`

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.3-canary.5` of Next.js to show a proper error explaining what is occurring better. 

The problem here is that the dynamic path is being statically generated during the build and then dynamic server methods are being used during runtime e.g. `cookies()` or `headers()` from `next/headers`. 

If these are being used in a shared library and the page is meant to be statically generated then `export const dynamic = 'force-static'` can be used to prevent this error or alternatively if the page isn't meant to be statically generated and these methods are needed `export const dynamic = 'force-dynamic'` can be leveraged.
