### ISSUE TITLE
On-demand revalidation with dynamic routes

### ISSUE THREAD

**Issue by A-Emile** [vercel/next.js#43345]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
Binaries:
      Node: 18.8.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 13.0.5
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When I call res.revalidate("path-to-dynamic-route") on a dynamic route, I get the following error:
```
TypeError: res.hasHeader is not a function
    at Object.setRevalidateHeaders (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\send-payload\revalidate-headers.js:8:37)
    at NextNodeServer.sendRenderResult (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\next-server.js:380:34)
    at NextNodeServer.pipe (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\base-server.js:418:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.fn (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\next-server.js:744:21)
    at async Router.execute (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\router.js:252:36)
    at async NextNodeServer.run (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\base-server.js:383:29)
    at async NextNodeServer.handleRequest (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\base-server.js:321:20)
    at async revalidate (C:\Users\pc\DEV\glugano\node_modules\next\dist\server\api-utils\node.js:288:13)
```

### Expected Behavior

The route gets revalidated

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/A-Emile/glugano

### To Reproduce

1. Create a dynamic route that fetches some data.
2. Create api endpoint to revalidate the dynamic route
3. Build the app (yarn build)
4. Run the app (yarn start)

**Comment by Fredkiss3** [comment]
Your reproduction link seems to not exists.
And I would suggest to setup your reproduction code by doing at least the first and second steps that you listed.
