### ISSUE TITLE
Hydration failure - Text content mismatch error due to URL-safe characters

### ISSUE THREAD

**Issue by joaisa17** [vercel/next.js#43564]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/joaisa17/nextjs-urlsafe-char-mismatch

### To Reproduce

The following example attempts to style a `h1` to use the Roboto font:
```tsx
export default function Home() {
    return <>
        <style>{`h1 { font-family: 'Roboto'; }`}</style>
        <h1>Hello world</h1>
    <>
}
```

### Describe the Bug

The reproduction example produces the following error, and causes hydration to fail:
```
Warning: Text content did not match. Server: "h1 { font-family: &#x27;Roboto&#x27;; }" Client: "h1 { font-family: 'Roboto'; }"
    at style
    at Home
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:27:1)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)
```

This seems to be caused by the server not considering converted characters while checking for a content match.

### Expected Behavior

Although the Roboto font is not imported in the reproduction example, it does not affect the error displayed.

Expected behavior is for the text to match on both the server and the client, so hydration can continue.

**Comment by balazsorban44** [comment]
This is unrelated to Next.js. If you want to set the inner HTML of the `style` element, you'll need to use `dangerouslySetInnerHTML`. The HTML will be escaped otherwise.

See: https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
