### ISSUE TITLE
After i create new Project and Run it using "npm run dev" it gives me error

### ISSUE THREAD

**Issue by harshendra1998** [vercel/next.js#43602]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Here is the complete log it get.

`> onelink@0.1.0 dev /home/harshendra/Desktop/excer/onelink
> next dev

/home/harshendra/Desktop/excer/onelink/node_modules/next/dist/cli/next-dev.js:315
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/harshendra/Desktop/excer/onelink/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/home/harshendra/Desktop/excer/onelink/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onelink@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the onelink@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harshendra/.npm/_logs/2022-12-01T13_03_06_113Z-debug.log
`

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-ww4psv?file=next.config.js

### To Reproduce

just create new project , then run 'npx run dev'

### Describe the Bug

> onelink@0.1.0 dev /home/harshendra/Desktop/excer/onelink
> next dev

/home/harshendra/Desktop/excer/onelink/node_modules/next/dist/cli/next-dev.js:315
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/harshendra/Desktop/excer/onelink/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/home/harshendra/Desktop/excer/onelink/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onelink@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the onelink@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harshendra/.npm/_logs/2022-12-01T13_03_06_113Z-debug.log

### Expected Behavior

should run the project without this error,

![Screenshot from 2022-12-01 18-39-57](https://user-images.githubusercontent.com/35134976/205064253-97f5a655-cebe-480f-9a9d-b76b60ca49a4.png)

**Comment by balazsorban44** [comment]
It's likely that you are on an old version of Node.js that [does not support nullish coalescing](https://node.green/#ES2020-features--nullish-coalescing-operator-----).

You'll need at least Node.js 14 or newer as documented here: https://nextjs.org/docs/getting-started#system-requirements
