### ISSUE TITLE
rewrites, trailingSlash: true and getStaticProps cause TypeError [ERR_INVALID_URL]: Invalid URL 

### ISSUE THREAD

**Issue by jdddog** [vercel/next.js#43623]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #148~18.04.1-Ubuntu SMP Mon Oct 24 20:41:14 UTC 2022
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/jdddog/next-invalid-url-reproduction

### To Reproduce

Run `yarn dev`

Navigate to: `http://localhost:3000/country/` (you want to trigger a server render not client side navigation).

Then you should receive this error in the browser:

![image](https://user-images.githubusercontent.com/5715104/205213755-9fd87e47-cd63-4229-b358-aa9b89284ed1.png)

And this error in the terminal for the server:
```bash
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at /home/user/next-invalid-url-reproduction/node_modules/next/dist/shared/lib/router/adapters.js:97:21
    at Object.useMemo (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at Object.useMemo (/home/user/next-invalid-url-reproduction/node_modules/react/cjs/react.development.js:1650:21)
    at PathnameContextProviderAdapter (/home/user/next-invalid-url-reproduction/node_modules/next/dist/shared/lib/router/adapters.js:65:31)
    at renderWithHooks (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7) {
  input: '//',
  code: 'ERR_INVALID_URL'
}
error - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at /home/user/next-invalid-url-reproduction/node_modules/next/dist/shared/lib/router/adapters.js:97:21
    at Object.useMemo (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at Object.useMemo (/home/user/next-invalid-url-reproduction/node_modules/react/cjs/react.development.js:1650:21)
    at PathnameContextProviderAdapter (/home/user/next-invalid-url-reproduction/node_modules/next/dist/shared/lib/router/adapters.js:65:31)
    at renderWithHooks (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/home/user/next-invalid-url-reproduction/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7) {
  input: '//',
  code: 'ERR_INVALID_URL',
  page: '/'
}
```

### Describe the Bug

This bug occurs when using `rewrites`, where a page, e.g. `/country/` is rewritten to `/`, `trailingSlash` is true and `getStaticProps` is present on the index page (the page we are rewriting to).

When the user requests the source page using server navigation, e.g. `/country/` the error TypeError [ERR_INVALID_URL]: Invalid URL is thrown.

The error occurs in PathnameContextProviderAdapter at `new URL(router.asPath, 'http://f')` because router.asPath is set to `//`: https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/router/adapters.tsx#L120

It might be related to this bug: https://github.com/vercel/next.js/issues/40549. I've used the workaround in that thread by setting `source: "/country/{/}?"` to fix the client side navigation (see that thread), however, if the source is set to `source: "/country/"` the error from this example still occurs.

### Expected Behavior

When the user requests the source page using server navigation, e.g. `/country/` no error should be thrown and the page rendered.

### Which browser are you using? (if relevant)

Version 107.0.5304.87 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next dev

**Comment by balazsorban44** [comment]
Thanks, seems to be a regression introduced in https://github.com/vercel/next.js/pull/41767, we will have a look!

**Comment by jdddog** [comment]
> Thanks, seems to be a regression introduced in #41767, we will have a look!

Thanks very much for fixing it @balazsorban44 and @wyattjoh!
