### ISSUE TITLE
Next 13 does not throw exception when multi children are nested in LINK

### ISSUE THREAD

**Issue by bobs619** [vercel/next.js#43651]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

n/a

### To Reproduce

                <Link
                  href={`/loanApps/${Id}/upload`}
                  className="inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 focus:ring-offset-gray-50 "
                >
         
                    <CloudArrowUpIcon
                      className="-ml-1 mr-2 h-5 w-5 text-gray-400"
                      aria-hidden="true"
                    />
                    Upload
     
                </Link>

### Describe the Bug

The browser or build did not catch the multiple children nested in the <LINK> tag.  The previous version Next 12 did throw this error.  Unexpected behavior can result if this error is not caught.   In my case i had an issue with a websocket library called Signal-r.  It was until i downgraded to 12, i was able to correct the issue, then i proceeded to upgrade _back_ to 13.   Now everything is gravy.  

Please fix this issue so no one will have to go through my 12hr ordeal.  

### Expected Behavior

The browser should throw this error https://nextjs.org/docs/messages/link-multiple-children

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Azure

**Comment by Fredkiss3** [comment]
In the new version of nextjs, the link component behaves very differently and does not need to have a `<a>` child, the component will replace directly the need of the tag and so can accept it. 

More informations here in the docs : https://beta.nextjs.org/docs/upgrade-guide#link-component

> The [<Link> Component](https://beta.nextjs.org/docs/routing/linking-and-navigating#link-component) no longer requires manually adding an <a> tag as a child. This behavior was added as an experimental option in [version 12.2](https://beta.nextjs.org/blog/next-12-2) and is now the default. In Next.js 13, <Link> always renders <a> and allows you to forward props to the underlying tag.

**Comment by aaroncase86** [comment]
I am experiencing a similar error. After running the codemod for legacy links (https://nextjs.org/docs/advanced-features/codemods#new-link), my application built and ran without console errors, but I did end up with a `<Link>` with two children. 

I was only aware of the problem when our Jest tests failed with the error regarding multiple children.

**Comment by Fredkiss3** [comment]
I don't understand, does nextjs throw any error when you have two children ?

Because now `<Link />` can have multiple children, that's how it is now, i don't think this is a bug.

**Comment by aaroncase86** [comment]
> I don't understand, does nextjs throw any error when you have two children ?
> 
> Because now `<Link />` can have multiple children, that's how it works now, ane behaves more like a normal anchor tag.

It should, according to this:
https://nextjs.org/docs/messages/link-multiple-children

**Comment by aaroncase86** [comment]
This produces an error in testing in next 13.0.6 but not in the console. Is there a jest configuration that also should be updated for next13 links?

```
<Link href={href} className={className}>
      {'hi'}
      {'hello'}
</Link>
```

**Comment by Fredkiss3** [comment]
I think yes, it seems like jest considers the component behavior as the legacy way. 
I had a similar problem when using nextjs `<Link>` component in storybook, though the problem was in next 12 but with a flag (in `nextjs.config.js`) to make the component behave like in next 13.

I don't know if jest take account of the config or if it needs a flag somewhere to be compatible with next 13.

May i ask how you are testing your app with jest and next (just for information, i don't really know jest well) ?

**Comment by aaroncase86** [comment]
> May i ask how you are testing your app with jest and next (just for information, i don't really know jest well) ?

Sure thing! We use a configuration of Jest, React Testing Library, and MSW to mock network responses. With those three utilities you can effectively mock the pieces you need and fully test your app. As a bonus they also make testing the full next page experience possible within storybook.

**Comment by Fredkiss3** [comment]
Do you use any custom configuration to make it work with nextjs ?

**Comment by aaroncase86** [comment]
> Do you use any custom configuration to make it work with nextjs ?

mostly based on this: https://github.com/vercel/next.js/tree/canary/examples/with-jest

**Comment by Fredkiss3** [comment]
By looking at the example, i noticed that the jest example uses the package `next/jest` : 

```tsx
// nextjs/examples/with-jest/jest.config.js

const nextJest = require('next/jest')

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})
```
I think it's the package that have not been updated and still considering the `Link` component as the legacy one.

**Comment by AlexandreBourdeaudhui** [comment]
> I think it's the package that have not been updated and still considering the `Link` component as the legacy one.

I think so. Since the upgrade of my application to Next@13, all tests using next/link are failed. Previously, it worked like a charm. And I'm on "pages" folder for now.

<details>
<summary>Details</summary>

  console.error
    Error: Uncaught [Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `RezoLink`.]
        at reportException (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
        at invokeEventListeners (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
        at HTMLUnknownElementImpl._dispatch (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
        at HTMLUnknownElement.dispatchEvent (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
        at Object.invokeGuardedCallbackDev (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
        at invokeGuardedCallback (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
        at beginWork$1 (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react-dom/cjs/react-dom.development.js:27451:7)
        at performUnitOfWork (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react-dom/cjs/react-dom.development.js:26560:12)
        at workLoopSync (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
        at renderRootSync (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
        at performConcurrentWorkOnRoot (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react-dom/cjs/react-dom.development.js:25738:74)
        at flushActQueue (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react/cjs/react.development.js:2667:24)
        at act (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/react/cjs/react.development.js:2582:11)
        at /home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/@testing-library/react/dist/act-compat.js:63:25
        at renderRoot (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/@testing-library/react/dist/pure.js:159:26)
        at render (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/@testing-library/react/dist/pure.js:246:10)
        at Object.<anonymous> (/home/abourdeaudhui/dev/prj/rezo-site/next/app/src/components/ui/atoms/Link/index.test.tsx:14:33)
        at Promise.then.completed (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/utils.js:289:28)
        at new Promise (<anonymous>)
        at callAsyncCircusFn (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/utils.js:222:10)
        at _callCircusTest (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/run.js:248:40)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at _runTest (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/run.js:184:3)
        at _runTestsForDescribeBlock (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/run.js:86:9)
        at _runTestsForDescribeBlock (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/run.js:81:9)
        at run (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/run.js:26:3)
        at runAndTransformResultsToJestFormat (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:120:21)
        at jestAdapter (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
        at runTestInternal (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-runner/build/runTest.js:367:16)
        at runTest (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-runner/build/runTest.js:444:34)
        at Object.worker (/home/abourdeaudhui/dev/prj/rezo-site/next/app/node_modules/jest-runner/build/testWorker.js:106:12) {
      detail: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.



</details>

**Comment by anonymouscatcher** [comment]
Same thing here :/ WTF
