### ISSUE TITLE
NextJS, using with-jest example and NodeJS 18, doesn't support fetch() out of the box

### ISSUE THREAD

**Issue by ajvincent** [vercel/next.js#43676]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```plaintext
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sat Nov 26 16:55:13 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-jest

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

NodeJS's fetch API support, [although listed as experimental](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch), [should be supported](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#browser_compatibility).  In writing a test for this, however, I found an inconsistency:  I'm running version 18 of Node, and fetch is undefined.

In addition, the fallback, `import fetch from "node-fetch"`, doesn't work either.

### Expected Behavior

`expect(typeof fetch).toBe("function");` should pass.

### To Reproduce

- In terminal 1:

```bash
npx create-next-app --example with-jest with-jest-app
cd with-jest-app/
npm install node-fetch
npm install --save next@canary react react-dom
npm run dev
```

- Disable `with-jest-app/__tests__/snapshot.tsx`: Replace `it(` with `xit(`.
- Add the following file at `__tests__/fetchExists.tsx`:

```typescript
// I didn't know how to just import enough for Jest to expose the "it" function.
import { render, screen } from '@testing-library/react'
void(render);
void(screen);

it("fetch should exist in version 18+ of NodeJS", () => {
  expect(parseFloat(process.versions.node)).toBeGreaterThanOrEqual(18);

  // https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch
  expect(typeof fetch).toBe("function");
});
```

- Add the following file at `__tests__/import-node-fetch.tsx`:

```typescript
import fetch from 'node-fetch';

it("node-fetch should expose fetch", () => {
  expect(typeof fetch).toBe("function");
});
```

- In terminal 2:

```plaintext
$ node
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> typeof fetch
'function'
> .exit

npm run test
```
- Results:

```plaintext
 FAIL  __tests__/import-node-fetch.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/ajvincent/nextjs-dev/nextjs-jest-20221203/with-jest-app/node_modules/node-fetch/src/index.js:9
    import http from 'node:http';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 | it("node-fetch should expose fetch", () => {
      4 |   expect(typeof fetch).toBe("function");
    > 5 | });
        |              ^
      6 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (__tests__/import-node-fetch.tsx:5:57)

 FAIL  __tests__/fetchExists.tsx
  ● fetch should exist in version 18+ of NodeJS

    expect(received).toBe(expected) // Object.is equality

    Expected: "function"
    Received: "undefined"

       7 |
       8 |   // https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch
    >  9 |   expect(typeof fetch).toBe("function");
         |                        ^
      10 | });
      11 |

      at Object.toBe (__tests__/fetchExists.tsx:9:24)
```

I ran into similar trouble using the [documented steps for installing Jest with Rust on next.js](https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler).

I know a _lot_ of people have explored this problem before, and the answer has usually been "Install node-fetch, you'll be fine."  Well... I tried that, and it didn't work.  Plus, it's supposed to be no longer necessary with Node 18.

I do understand this is likely to be a duplicate bug, but I am new to NextJS.  I've used Jest before, some time ago.  Help!!

**Comment by jodator** [comment]
I found this issue researching why Jest test fails on Node 18 while it properly work locally and on Vercel.

For the `node-fetch` I see that we have below inside `jest.config.js` file:

```javascript
// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
module.exports = async () => {
  const config = await createJestConfig(customJestConfig)()
  config.transformIgnorePatterns = [
    '<rootDir>/node_modules/.pnpm/(?!node-fetch)'
  ]
  return config
}
```

This works, however the goal is to remove `node-fetch` and just use `fetch` from Node 18 directly.

**Comment by ajvincent** [comment]
> This works

What changes to the test files did you do?  Making your suggested change and reusing the tests I posted earlier, I get exactly the same results.
