### ISSUE TITLE
@next/font/google failed to run or is incorrectly configured.

### ISSUE THREAD

**Issue by k2xl** [vercel/next.js#43695]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (@next/font)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/sspenst/pathology/pull/674

### To Reproduce

Run `npm test` with jest.

### Describe the Bug

We are trying to use the new font optimization from next 13.

We currently use jest as our testing framework.

Running `npm test` gives the following errors across our pages that are testing getStaticProps` and `getServersideProps`    

```
Test suite failed to run

    @next/font/google failed to run or is incorrectly configured.

    Read more: https://nextjs.org/docs/basic-features/font-optimization

      2 |
      3 | import '../styles/global.css';
    > 4 | import { Rubik, Teko } from '@next/font/google';
        | ^
      5 | import type { AppProps } from 'next/app';
      6 | import Head from 'next/head';
      7 | import { DefaultSeo } from 'next-seo';

      at Object.<anonymous> (node_modules/@next/font/google/index.js:15:7)
```

### Expected Behavior

We expect that our tests pass. Note that the app itself runs fine it is just the tests that fail.

**Comment by hanneslund** [comment]
When using [`next/jest`](https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler) it's automatically mocked.

Mocking it manually should be something like this
```ts
// jest.config.ts
moduleNameMapper: {
    '\\.(css|less)$': '<rootDir>/tests/jest/__mocks__/styleMock.js',
    '@next/font/(.*)': require.resolve('next/dist/build/jest/__mocks__/nextFontMock.js'),
  },
```

**Comment by sspenst** [comment]
`'@next/font/(.*)': require.resolve('next/dist/build/jest/__mocks__/nextFontMock.js'),` is exactly what we needed, thank you!

**Comment by crazyweeds** [comment]
The project was a disaster for beginners.


next build
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data .Error: @next/font/google failed to run or is incorrectly configured.

Read more: https://nextjs.org/docs/basic-features/font-optimization
    at Object.<anonymous> (/usr/local/var/www/fuck/node_modules/@next/font/google/index.js:15:7)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 415 (/usr/local/var/www/fuck/.next/server/pages/index.js:49:32)
    at __webpack_require__ (/usr/local/var/www/fuck/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/usr/local/var/www/fuck/.next/server/pages/index.js:329:39)

> Build error occurred
Error: Failed to collect page data for /
    at /usr/local/lib/node_modules/next/dist/build/utils.js:960:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
info  - Collecting page data .%
