### ISSUE TITLE
Using getHeader in getServerSideProps broken in production/preview, but works locally

### ISSUE THREAD

**Issue by theodormarcu** [vercel/next.js#43840]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 3.2.2
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.3
      eslint-config-next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/theodormarcu/csp-next-repro

### To Reproduce

Run app locally. You will notice that the CSP headers that get printed in the terminal are as expected `context.res.getHeader frame-ancestors 'self';`:

<img width="728" alt="Screenshot 2022-12-07 at 10 46 06 PM" src="https://user-images.githubusercontent.com/8714338/206351723-4e81773b-35db-4d8e-bfc3-2b19b9e7a338.png">

Deploy app to production. Notice that the headers are `undefined` when using `context.res.getHeader(...)` in `getServerSideProps`.

<img width="1452" alt="Screenshot 2022-12-07 at 10 47 39 PM" src="https://user-images.githubusercontent.com/8714338/206351889-f4b98528-a032-4720-a4b8-f873604f1f1a.png">

### Describe the Bug

The bug is that `res.getHeader` returns `undefined` server-side when Next runs on Vercel in Preview / Production when headers are configured in `next.config.js`. This differs from local behavior. When Next runs in dev mode **or** in production mode locally (using `next start`), `context.res.getHeader` returns the correct response. 

Expected behavior: `res.getHeader` returns whatever is defined in `next.config.js` both in preview/prod and locally.

This is very annoying, because it means that currently developers cannot override or act on headers defined in next.config.js in getServerSideProps.

### Expected Behavior

Expected behavior: `res.getHeader` returns whatever is defined in `next.config.js` both in preview/prod and locally.

### How are you deploying your application? (if relevant)

Vercel

**Comment by mishchief** [comment]
Any traction on this? I'm experiencing something similar that's causing my `auth0/nextjs-auth0` implementation to break.

Or is there a roll back version that doesn't have this issue?

**Comment by mishchief** [comment]
Is anybody going to address this issue?

**Comment by mishchief** [comment]
I'm having this issue also in local development:

I’m currently getting this error every once in a while after a two days or so of being idle. Clearing my cookies and logging back in fixes the issue. The error message I’m getting is:
```
TypeError: Cannot read properties of undefined (reading 'getHeader')
at NodeCookies.getSetCookieHeader (<repo_path>/master/node_modules/@auth0/nextjs-auth0/dist/auth0-session/utils/cookies.js:47:27)
at Cookies.commit (<repo_path>/master/node_modules/@auth0/nextjs-auth0/dist/auth0-session/utils/cookies.js:31:36)
at StatelessSession.<anonymous> (<repo_path>/master/node_modules/@auth0/nextjs-auth0/dist/auth0-session/session/stateless-session.js:204:38)
at step (<repo_path>/master/node_modules/tslib/tslib.js:193:27)
at Object.next (<repo_path>/master/node_modules/tslib/tslib.js:174:57)
at fulfilled (<repo_path>/master/node_modules/tslib/tslib.js:164:62) {
page: '/dashboard/manage-events'
}
```
I’m not sure what’s causing the issue, but it seems to be related to the ‘getHeader’ property of an undefined variable. I’m working with the [@auth0](https://community.auth0.com/u/auth0)/nextjs-auth0 package, and the error is being thrown from the cookies.js file.

Has anybody encountered this issue or know what else I should be looking at to fix it?

I’ve tried updating the package, but it’s already at the latest version and this still occasionally happens, so far it has only happened on local but am afraid it will happen on prod.

Stack:
NextJs@13.2.3
@auth0/nextjs-auth0@2.4.0

Thanks!

### Reproduction

Unsure about the reproduction steps since it seems to happen randomly and it affects all users of the application, this happened to me today, and to one of my clients and we both had to log out and log back in.

Could it be related to the refresh token?

![Screenshot 2023-04-18 at 2 16 10 PM](https://user-images.githubusercontent.com/14078533/232867548-911bb02c-d246-4859-abca-36b50489db78.png)

It seems to be happening after the auth/me call.

### SDK version

@auth0/nextjs-auth0@2.4.0

### Next.js version

NextJs@13.2.3

### Node.js version

16.x
