### ISSUE TITLE
use client throwing "ReferenceError: document is not defined" when document perfectly available

### ISSUE THREAD

**Issue by Eduard-Hasa** [vercel/next.js#44014]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Using the latest Nextjs 13.0.7 with the app directory.

### Link to the code that reproduces this issue

https://codesandbox.io/

### To Reproduce

Simply try to use the document object in a app directory page with 'use client' active and you will see the following in the logs:

ReferenceError: document is not defined
    at Page (eval at (sc_client)/./src/app/(test- Layout)/test/[id]/builder/page.tsx (/home/reaction/my-client/.next/server/app/(test- Layout)/test/[id]/builder/page.js:1738:1), <anonymous>:11:17)
    at renderWithHooks (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7756:16)
    at renderIndeterminateComponent (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7830:15)
    at renderElement (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8065:7)
    at renderLazyComponent (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8045:3)
    at renderElement (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8155:11)
    at renderNodeDestructiveImpl (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8204:14)
    at retryTask (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:5)
    at performWork (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8741:7)
    at /home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7453:14
    at scheduleWork (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:78:3)
    at pingTask (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7452:5)
    at ping (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7485:14)
    at wakeChunk (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:299:5)
    at wakeChunkIfInitialized (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:306:7)
    at resolveModuleChunk (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:386:5)
    at /home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:668:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Describe the Bug

ReferenceError: document is not defined
    at SortableTree (webpack-internal:///(sc_client)/./src/components/dnd-kit/SortableTree.tsx:113:17)
    at renderWithHooks (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7756:16)
    at renderIndeterminateComponent (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7830:15)
    at renderElement (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8065:7)
    at renderNodeDestructiveImpl (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8204:14)
    at renderNode (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8388:12)
    at renderHostElement (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7740:3)
    at renderElement (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8071:5)
    at renderNodeDestructiveImpl (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8204:14)
    at renderIndeterminateComponent (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7884:7)
    at renderElement (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8065:7)
    at renderLazyComponent (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8045:3)
    at renderElement (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8155:11)
    at renderNodeDestructiveImpl (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8204:14)
    at retryTask (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:5)
    at performWork (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8741:7)
    at /home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7453:14
    at scheduleWork (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:78:3)
    at pingTask (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7452:5)
    at ping (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7485:14)
    at wakeChunk (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:299:5)
    at wakeChunkIfInitialized (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:306:7)
    at resolveModuleChunk (/home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:386:5)
    at /home/reaction/HASA/pos-client/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:668:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Expected Behavior

The document object us perfectly accessible on every render when 'use client' is enabled so we should not see this error.

**Comment by focux** [comment]
I'm experiencing this same issue, I would expect `document` to be defined on a client component and that component not to be server rendered.

**Comment by Eduard-Hasa** [comment]
Right... actually the document is perfectly defined and available. The problem is the error is falsely being logged. My app uses document object perfectly fine.

**Comment by SzymonGalazka** [comment]
I think it is not falsely reported - as per the [documentation](https://beta.nextjs.org/docs/rendering/server-and-client-components#client-components):

> Client Components enable you to add client-side interactivity to your application. **In Next.js, they are [prerendered](https://beta.nextjs.org/docs/rendering/fundamentals#client-and-server-rendering-at-the-component-level) on the server and [hydrated](https://beta.nextjs.org/docs/rendering/fundamentals#client-and-server-rendering-at-the-component-level) on the client. You can think of Client Components as how Next.js 12 and previous versions worked (i.e. the pages/ directory).**

Client components = SSR + hydration + CSR.
All `document`, `window` usages should still be guarded.

**Comment by Eduard-Hasa** [comment]
> I think it is not falsely reported - as per the [documentation](https://beta.nextjs.org/docs/rendering/server-and-client-components#client-components):
> 
> 
> 
> > Client Components enable you to add client-side interactivity to your application. **In Next.js, they are [prerendered](https://beta.nextjs.org/docs/rendering/fundamentals#client-and-server-rendering-at-the-component-level) on the server and [hydrated](https://beta.nextjs.org/docs/rendering/fundamentals#client-and-server-rendering-at-the-component-level) on the client. You can think of Client Components as how Next.js 12 and previous versions worked (i.e. the pages/ directory).**
> 
> 
> 
> Client components = SSR + hydration + CSR.
> 
> All browser-related APIs should still be guarded.

It's not falsely reported. The document object is available but the error is saying it's not.

**Comment by raphaelbadia** [comment]
I encounter the same problem.

I need to change a logo, and it depends on the hostname. I tried that, and it works, my component instantly renders with the logo.

![CleanShot 2023-02-21 at 19 04 11](https://user-images.githubusercontent.com/1901628/220424386-798796da-9a2f-4228-ad50-e75f26870125.png)

But the console complains about `window is not defined`....

**Comment by timneutkens** [comment]
As @SzymonGalazka shared this is correct, if you want to read `window` or `document` you have to do so in `useEffect`, same as in `pages`. `'use client'` marks a component as "can run in the browser" and not "shall only run in the browser", it's basically the same as components in `pages` today, there's no semantic difference. The only new part is server components.

The docs explain this: https://beta.nextjs.org/docs/rendering/server-and-client-components#client-components
