### ISSUE TITLE
Error: Static page generation for /PATH is still timing out after 3 attempts

### ISSUE THREAD

**Issue by andrewmartin** [vercel/next.js#44166]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 9.1.3
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: 13.0.5
      react: 18.3.0-next-fecc288b7-20221025
      react-dom: 18.3.0-next-fecc288b7-20221025

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

git@github.com:andrewmartin/izzyatelier.git

### To Reproduce

Attempt to deploy my project in Netlify/Vercel. I'm not sure how to share much more beyond that but I'm happy to! It works fine locally using my `yarn build` command and I always get successful output.

### Describe the Bug

In Vercel, and Netlify, my builds fail every single time:

```
> Build error occurred
13:17:46.502 | Error: Static page generation for /about/our-process-for-custom-projects is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
13:17:46.503 | at onRestart (/vercel/path0/node_modules/next/dist/build/index.js:647:35)
13:17:46.503 | at Worker.exportPage (/vercel/path0/node_modules/next/dist/lib/worker.js:48:40)
13:17:46.504 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
13:17:46.504 | at async /vercel/path0/node_modules/next/dist/export/index.js:322:32
13:17:46.504 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
13:17:46.504 | at async Promise.all (index 2)
13:17:46.504 | at async /vercel/path0/node_modules/next/dist/export/index.js:317:9
13:17:46.505 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
13:17:46.505 | at async /vercel/path0/node_modules/next/dist/build/index.js:1345:21
13:17:46.505 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
13:17:46.545
```

This happens every time for me and I'm very confused; it doesn't happen locally.

### Expected Behavior

A build should succeed in CI systems (Vercel, Netlify).

### How are you deploying your application? (if relevant)

Vercel

**Comment by kvarela** [comment]
We're also experiencing the same thing with next on Vercel. Any way to solve or work around it?
