### ISSUE TITLE
`--turbo` incompatible with `core-js dom-collections`

### ISSUE THREAD

**Issue by zoobestik** [vercel/next.js#44169]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue

https://github.com/zoobestik/nextjs-turbo-corejs-bug

### To Reproduce

Steps for repo:
* Clone the above [repository](https://github.com/zoobestik/nextjs-turbo-corejs-bug)
* `npm i`
* `npm run dev:turbo`
* go to http://localhost:3000
* Click on a button

### Describe the Bug

Looks like currently `--turbo incompatibale` with some babel transpiled packages.
If in code presents `web.dom-collections.iterator` import (https://github.com/zloirock/core-js/issues/1003) it raises exception:
<img width="822" alt="Screenshot 2022-12-19 at 23 30 00" src="https://user-images.githubusercontent.com/242514/208539269-bd7a98c3-ccd4-4299-82e3-cfe805c56e39.png">

<details>
  <summary>See stacktrace</summary>
```
_cc1f6a.js:63 Uncaught TypeError: Illegal invocation
    at Object.registerExportsForReactRefresh (_cc1f6a.js:63:40)
    at registerExportsAndSetupBoundaryForReactRefresh (_cc1f6a.js:50086:13)
    at runModuleExecutionHooks (_cc1f6a.js:50036:7)
    at instantiateModule (_cc1f6a.js:49991:5)
    at getOrInstantiateModuleFromParent (_cc1f6a.js:50073:12)
    at commonJsRequire (_cc1f6a.js:49816:12)
    at Object.<anonymous> (_cc1f6a.js:269:29)
    at [project-with-next]/node_modules/core-js/modules/web.dom-collections.iterator.js (ecmascript) (_cc1f6a.js:300:3)
    at _cc1f6a.js:49992:21
    at runModuleExecutionHooks (_cc1f6a.js:50031:5)
```
</details>

afterwards any client code doesn't worked.

### Expected Behavior

There should be works with transpiled packages like before turbopack migration.

### Which browser are you using? (if relevant)

Chrome 107.0.5304.87, Firefox 109.0b2, Safari 16.1

### How are you deploying your application? (if relevant)

next dev --turbo

**Comment by zoobestik** [comment]
For reproduce also is possible just import in `pages` any of this files:
```
import 'core-js/modules/web.dom-collections.iterator.js';
// or
import "core-js/modules/web.dom-collections.for-each.js";
```

It happened in this script after access `length` prop of `DOMTokenList` instance. I think it's problem inside proxy getter, but i haven't got where. 😞

Chrome DevTools state before crash:
<img width="1631" alt="Screenshot 2022-12-19 at 23 40 46" src="https://user-images.githubusercontent.com/242514/208541381-62771713-15a6-43b7-b310-fff3aeb3fec6.png">
