### ISSUE TITLE
Next 13 Shiki vscode-oniguruma wasm file not found in React Server Component

### ISSUE THREAD

**Issue by selenecodes** [vercel/next.js#44316]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.18.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/selenecodes/next13-rsc-shiki-wasm-not-found

### To Reproduce

1. Install the reproduction
2. Run npm install
3. Witness the following error:
```
Error: ENOENT: no such file or directory, open '(sc_server)\node_modules\vscode-oniguruma\release\onig.wasm'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at getOniguruma (webpack-internal:///(sc_server)/./node_modules/shiki/dist/index.js:2178:32)
    at Object.getHighlighter (webpack-internal:///(sc_server)/./node_modules/shiki/dist/index.js:2682:36)
    at getHighlighter (webpack-internal:///(sc_server)/./markdown.plugin.ts:66:66)
    at Function.rehypePrettyCode (webpack-internal:///(sc_server)/./node_modules/rehype-pretty-code/dist/rehype-pretty-code.js:30110:45)
    at Function.freeze (webpack-internal:///(sc_server)/./node_modules/unified/lib/index.js:115:74)
    at Function.process (webpack-internal:///(sc_server)/./node_modules/unified/lib/index.js:306:19)
    at parseMarkdown (webpack-internal:///(sc_server)/./markdown.plugin.ts:41:31)
    at Page (webpack-internal:///(sc_server)/./app/page.tsx:15:87)
    at preloadComponent (D:\Code\osr\my-app\node_modules\next\dist\server\app-render.js:82:22)
    at D:\Code\osr\my-app\node_modules\next\dist\server\app-render.js:880:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createComponentTree (D:\Code\osr\my-app\node_modules\next\dist\server\app-render.js:879:25)
    at async D:\Code\osr\my-app\node_modules\next\dist\server\app-render.js:819:56
    at async Promise.all (index 0)
    at async createComponentTree (D:\Code\osr\my-app\node_modules\next\dist\server\app-render.js:783:38)
    at async D:\Code\osr\my-app\node_modules\next\dist\server\app-render.js:1059:51 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '(sc_server)\\node_modules\\vscode-oniguruma\\release\\onig.wasm'
}
```

### Describe the Bug

When loading the [shiki.js](https://github.com/shikijs/shiki) syntax highlighter in a React Server Component the `vscode-oniguruma` file can't be found.

### Expected Behavior

Load the syntax highlighter without issues and allow it to resolve the installed node module containing the `vscode-oniguruma` wasm file.

**Comment by selenecodes** [comment]
Here's the link to the shiki issue as well: shikijs/shiki#398

**Comment by selenecodes** [comment]
A workaround has been posted in https://github.com/shikijs/shiki/issues/398, closing.
