### ISSUE TITLE
"ISR" failing on Vercel with appDir

### ISSUE THREAD

**Issue by ervwalter** [vercel/next.js#44475]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: 7.18.2
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/ervwalter/games.ewal.net/tree/main/frontend

### To Reproduce

Deploy to Vercel, wait for revalidation to happen.

### Describe the Bug

I am getting a strange error only when deployed on Vercel with an appDir project.  The symptom is that sometime after the initial deploy, revalidations (aka appDir equivalent of ISR) all start failing.  All of my routes have an error in the function logs that looks like this:

```
2023-01-01T03:25:31.847Z	70439c75-bf11-4750-8334-6b6578991e6a	ERROR	TypeError: Cannot read properties of undefined (reading 'current')
    at Wd (/var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:77)
    at /var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:127:369
    at new Promise (<anonymous>)
    at Object.exports.renderToReadableStream (/var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:126:53)
    at Object.renderToInitialStream (/var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/node-web-streams-helper.js:124:27)
    at bodyResult (/var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/app-render.js:1141:71)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async wrappedRender (/var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/app-render.js:1167:57)
    at async doRender (/var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/var/task/frontend/node_modules/.pnpm/next@13.1.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/base-server.js:828:28) {
  page: '/collection'
}
RequestId: 70439c75-bf11-4750-8334-6b6578991e6a Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

My repo is linked above.  This has gotten into this state several times.  I don't really know how to debug it as none of the call stack appears to involve my code.  Also, I am certain that if I just redeploy, the site will start working again.  Is there something you'd suggest I look at before I do that?

### Expected Behavior

Not error out

### How are you deploying your application? (if relevant)

Vercel

**Comment by ervwalter** [comment]
Note, to get my site working again, I redeployed without `revalidate` in any of my fetches to they are all SSR.  But the branch linked above is still the code that causes the problem.
