### ISSUE TITLE
Using next/image fails to find sharp when packaging with nix

### ISSUE THREAD

**Issue by onepunchtech** [vercel/next.js#44690]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

building
     Operating System:
       Platform: linux
       Arch: x64
       Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Jan  4 10:29:02 UTC 2023
     Binaries:
       Node: 18.12.1
       npm: 8.19.2
       Yarn: 1.22.19
       pnpm: N/A
     Relevant packages:
       next: 13.1.2-canary.2
       eslint-config-next: 13.1.1
       react: 18.2.0
       react-dom: 18.2.0
 warn  - Failed to fetch latest canary version. (Reason: request to https://api.github.com/repos/vercel/next.js/releases failed, reason: getaddrinfo EAI_AGAIN api.github.com.)
       Detected "13.1.2-canary.2". Visit https://github.com/vercel/next.js/releases.
       Make sure to try the latest canary version (eg.: `npm install next@canary`) to confirm the issue still exists before creating a new issue.
       Read more - https://nextjs.org/docs/messages/opening-an-issue

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

https://github.com/onepunchtech/nextjs-nix-build-fail

### To Reproduce

1. Install nix package manager
2. add the following to `flake.nix` in your project dir

```
{
  description = "my project description";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs?rev=2117c50988e796dc76bab4b5fc9dab84dbb91098";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        web = pkgs.mkYarnPackage rec {
          pname = "ui";
          version = "0.0.1";
          packageJSON = ./package.json;
          yarnLock = ./yarn.lock;
          src = pkgs.nix-gitignore.gitignoreSource [] ./.;


          buildPhase = ''
            export HOME=$(mktemp -d)
            export NODE_ENV=production

            # NOTE! Trying to set next sharp path doesn't work
            export NEXT_SHARP_PATH=$node_modules/sharp

            $node_modules/.bin/next info
            yarn --offline build
          '';


          installPhase = ''
            mkdir -p $out
            mv package.json $out
            mv next.config.js $out
            mv next-env.d.ts $out
            mv tsconfig.json $out
            cp -a node_modules $out/node_modules
            mv .next $out
          '';

          configurePhase = ''
            # ln -s $node_modules node_modules
            cp -r $node_modules node_modules
            chmod -R +w  node_modules

            # NOTE! Trying to wrap next binary with environment doesn't work either
            wrapProgram node_modules/.bin/next \
              --set NEXT_SHARP_PATH node_modules/sharp
            cat node_modules/.bin/next
          '';

          distPhase = "true";

          nativeBuildInputs = [ pkgs.makeWrapper ];
        };

        myDevTools = [
          pkgs.nodejs
          pkgs.yarn
        ];

        builds = pkgs.callPackage ./nix/builds.nix {inherit pkgs self;};

        ui-image = pkgs.dockerTools.buildImage {
          name = "ui";
          tag = "latest";
          copyToRoot = pkgs.buildEnv {
            name = "image-root";
            paths = [pkgs.bashInteractive pkgs.coreutils web pkgs.yarn];
            pathsToLink = [ "/" ];
          };

          config = {
            Cmd = [ "yarn" "start"];
            Env = [
              "NODE_ENV=production"
              "NEXT_SHARP_PATH=/node_modules/sharp"
            ];
            ExposedPorts = {
              "3000/tcp" = {};
            };
          };
        };

      in {
        devShells.default = pkgs.mkShell {
          buildInputs = myDevTools;
          LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath myDevTools;
        };

        packages = {
          inherit web ui-image;
        };
      });
}

```
3. build with command `nix --experimental-features 'nix-command flakes' -L build .#web`

### Describe the Bug

The nix build output warns about not finding sharp. 
The docker image built with nix (also in the nix flake) can't find sharp when run.
Setting the env variable NEXT_SHARP_PATH makes no difference. I tried setting it in multiple places. The env variable is definitely there, and is pointing to the correct node_modules/sharp dir.

`yarn dev` doesn't warn about sharp
`yarn start` doesn't warn about sharp

Output shows 
```
ui> https://nextjs.org/telemetry
ui> info  - Skipping validation of types
ui> info  - Linting .info  - Linting ..info  - Linting ...info  - Linting .info  - Linting ..info  - Linting ...info  - Linting
ui> info  - Creating an optimized production build .info  - Creating an optimized production build ..info  - Creating an optimized production build ...Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
```

### Expected Behavior

Should be able to pick up the sharp dependency even inside nix without setting env variable.
Setting NEXT_SHARP_PATH should work as that is what documentation claimed the fix was.

Nix has a lot of ways to workaround issues like this. Just need to know where to start. However, I'm wondering why sharp isn't a concrete dependency. It seems pretty critical. I believe it would be better to fix this upstream.

**Comment by onepunchtech** [comment]
Apologies. This is not a nextjs build issue. This issue is a problem with sharp build (in nix anyway).
trying to require sharp with `${pkgs.nodejs}/bin/node -p "require('sharp')"`

gives this error

```
ui> /nix/store/bf1wsi054qrydz4v7299lic5vg4d8fyq-build-fail-modules-0.0.1/node_modules/sharp/lib/sharp.js:34
ui>   throw new Error(help.join('\n'));
ui>   ^
ui> Error:
ui> Something went wrong installing the "sharp" module
ui> Cannot find module '../build/Release/sharp-linux-x64.node'
ui> Require stack:
ui> - /nix/store/bf1wsi054qrydz4v7299lic5vg4d8fyq-build-fail-modules-0.0.1/node_modules/sharp/lib/sharp.js
ui> - /nix/store/bf1wsi054qrydz4v7299lic5vg4d8fyq-build-fail-modules-0.0.1/node_modules/sharp/lib/constructor.js
ui> - /nix/store/bf1wsi054qrydz4v7299lic5vg4d8fyq-build-fail-modules-0.0.1/node_modules/sharp/lib/index.js
ui> - /build/8kzxqkf852sy5ab2pypy0zls5s1zh8yf-source/[eval]
ui> Possible solutions:
ui> - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
ui> - Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
ui> - Consult the installation documentation: https://sharp.pixelplumbing.com/install
ui>     at Object.<anonymous> (/nix/store/bf1wsi054qrydz4v7299lic5vg4d8fyq-build-fail-modules-0.0.1/node_modules/sharp/lib/sharp.js:34:9)
ui>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
ui>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
ui>     at Module.load (node:internal/modules/cjs/loader:1037:32)
ui>     at Module._load (node:internal/modules/cjs/loader:878:12)
ui>     at Module.require (node:internal/modules/cjs/loader:1061:19)
ui>     at require (node:internal/modules/cjs/helpers:103:18)
ui>     at Object.<anonymous> (/nix/store/bf1wsi054qrydz4v7299lic5vg4d8fyq-build-fail-modules-0.0.1/node_modules/sharp/lib/constructor.js:8:1)
ui>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
ui>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
```
