### ISSUE TITLE
Next is not running out of the box

### ISSUE THREAD

**Issue by oussamaelhajoui** [vercel/next.js#44822]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

PS C:\Users\mo\projects\next-chat> npm -v
8.15.0
PS C:\Users\mo\projects\next-chat> node -v
v16.17.1
PS C:\Users\mo\projects\next-chat> next -v
Next.js v13.1.1

### Link to the code that reproduces this issue

npx create-next-app next-chat

### To Reproduce

Just run it, the first time i had this as well. So i removed the .next folder and i ran next dev again and it worked. This was when the application just was installed using create-next-app. So i uploaded the app to github cloned it to my new device and did an npm i and npm i --dev

And again i get the same problem.

I tried to remove the .next folder again and retry the next dev command but i have the same error in the browser:
![image](https://user-images.githubusercontent.com/17781939/212091052-a8ee209e-1bfe-4b7b-8713-6a47446fe4f0.png)

### Describe the Bug

Complains about "@next/font": "^13.1.1",

Stacktrace

PS C:\Users\mo\projects\next-chat> next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000

warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
event - compiled client and server successfully in 1288 ms (166 modules)
wait  - compiling...
event - compiled successfully in 70 ms (133 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 166 ms (167 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\mo\projects\next-chat\node_modules\react\cjs\react.development.js:1618:21)
    at Head (webpack-internal:///../../AppData/Roaming/npm/node_modules/next/dist/shared/lib/head.js:136:34)
    at renderWithHooks (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5696:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5943:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
warn  - Fast Refresh had to perform a full reload due to a runtime error.
wait  - compiling / (client and server)...
event - compiled client and server successfully in 281 ms (182 modules)
error - Error: @next/font/google failed to run or is incorrectly configured.
If you just installed `@next/font`, please try restarting `next dev` and resaving your file.

Read more: https://nextjs.org/docs/basic-features/font-optimization
    at Object.<anonymous> (C:\Users\mo\projects\next-chat\node_modules\@next\font\google\index.js:15:7)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.@next/font/google (C:\Users\mo\projects\next-chat\.next\server\pages\index.js:87:18)
    at __webpack_require__ (C:\Users\mo\projects\next-chat\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:9:75)
    at Object../pages/index.tsx (C:\Users\mo\projects\next-chat\.next\server\pages\index.js:33:1)
    at __webpack_require__ (C:\Users\mo\projects\next-chat\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (C:\Users\mo\projects\next-chat\.next\server\pages\index.js:174:39)
    at C:\Users\mo\projects\next-chat\.next\server\pages\index.js:175:28
    at Object.<anonymous> (C:\Users\mo\projects\next-chat\.next\server\pages\index.js:178:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\require.js:88:12)
    at C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\load-components.js:37:73
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loadComponents (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\load-components.js:37:26)
    at async DevServer.findPageComponents (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\next-server.js:561:36)
    at async DevServer.renderPageComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:942:24)
    at async DevServer.renderToResponse (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:971:32)
    at async DevServer.pipe (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:407:25)
    at async Object.fn (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\next-server.js:757:21)
    at async Router.execute (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\router.js:253:36)
    at async DevServer.run (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:384:29)
    at async DevServer.run (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\dev\next-dev-server.js:741:20)
    at async DevServer.handleRequest (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:322:20) {
  page: '/'
}
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\mo\projects\next-chat\node_modules\react\cjs\react.development.js:1618:21)
    at Html (webpack-internal:///../../AppData/Roaming/npm/node_modules/next/dist/pages/_document.js:678:104)
    at renderWithHooks (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at retryTask (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6528:5)
    at performWork (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6576:7)
    at C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6902:12
    at scheduleWork (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:77:3)
    at startWork (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6901:3)
    at C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6996:5
    at new Promise (<anonymous>)
    at Object.renderToReadableStream (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6949:10)
    at renderToString (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\render.js:59:55)
    at Object.renderToHTML (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\render.js:862:32)
    at async doRender (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:828:28)
    at async C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\response-cache\index.js:83:36
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\mo\projects\next-chat\node_modules\react\cjs\react.development.js:1618:21)
    at Html (webpack-internal:///../../AppData/Roaming/npm/node_modules/next/dist/pages/_document.js:678:104)
    at renderWithHooks (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5920:3)
    at renderElement (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at retryTask (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6528:5)
    at performWork (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6576:7)
    at C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6902:12
    at scheduleWork (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:77:3)
    at startWork (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6901:3)
    at C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6996:5
    at new Promise (<anonymous>)
    at Object.renderToReadableStream (C:\Users\mo\AppData\Roaming\npm\node_modules\next\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6949:10)
    at renderToString (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\render.js:59:55)
    at Object.renderToHTML (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\render.js:862:32)
    at async doRender (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:828:28)
    at async C:\Users\mo\AppData\Roaming\npm\node_modules\next\dist\server\response-cache\index.js:83:36

### Expected Behavior

Running without the error being showed

**Comment by TJBlackman** [comment]
Same issue. Fresh new project install, installed MUI. Boom! useContext error. :(

**Comment by GabenGar** [comment]
You didn't say how you are calling NextJS exactly and at what working directory.

**Comment by timneutkens** [comment]
Closing as no additional reply was added after @seanxwzhang's comment.
