### ISSUE TITLE
MissingStaticPage Error in production

### ISSUE THREAD

**Issue by Uni2K** [vercel/next.js#45148]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Thu Aug 11 22:41:16 UTC 2022
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.2
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

/

### To Reproduce

It happens random over the time, no idea how to reproduce it.

### Describe the Bug

I am running an EC2 instance with PM2 and nextjs. Since a few months, there are random crashes with the following error message:

>  Invariant: failed to load static page {
 "page": "/",
"url": "/",
"initUrl": "http://localhost:3000/"
}
MissingStaticPage [Error]: Failed to load static file for page: / ENOENT: no such file or directory, open '/home/ec2-user/.../.next/server/pages/index.html'
   at /home/ec2-user/.../node_modules/next/dist/server/require.js:85:19
   at async Object.loadComponents (/home/ec2-user/.../node_modules/next/dist/server/load-components.js:37:26)
   at async NextNodeServer.findPageComponents (/home/ec2-user/.../node_modules/next/dist/server/next-server.js:562:36)
   at async NextNodeServer.renderPageComponent (/home/ec2-user/.../node_modules/next/dist/server/base-server.js:942:24)
   at async NextNodeServer.renderToResponse (/home/ec2-user/.../node_modules/next/dist/server/base-server.js:971:32)
   at async NextNodeServer.pipe (/home/ec2-user/.../node_modules/next/dist/server/base-server.js:407:25)
   at async Object.fn (/home/ec2-user.../node_modules/next/dist/server/next-server.js:758:21)
   at async Router.execute (/home/ec2-user/.../node_modules/next/dist/server/router.js:253:36)
   at async NextNodeServer.run (/home/ec2-user/.../node_modules/next/dist/server/base-server.js:384:29)
   at async NextNodeServer.handleRequest (/home/ec2-user/.../node_modules/next/dist/server/base-server.js:322:20)

This exact message repeats ~3 times and then the following happens:

>  <--- Last few GCs --->
  [5079:0x63bac90] 47033293 ms: Scavenge 480.1 (486.5) -> 478.3 (486.5) MB, 1.5 / 0.0 ms  (average mu = 0.272, current mu = 
 0.242) allocation failure 
  [5079:0x63bac90] 47033294 ms: Scavenge 480.1 (486.5) -> 478.5 (486.5) MB, 0.5 / 0.0 ms  (average mu = 0.272, current mu = 
 0.242) allocation failure 
  [5079:0x63bac90] 47033295 ms: Scavenge 480.2 (486.5) -> 478.5 (490.5) MB, 0.7 / 0.0 ms  (average mu = 0.272, current mu = 
 0.242) allocation failure 
  <--- JS stacktrace --->
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
  1: 0xb30950 node::Abort() [node]
  2: 0xa4219e node::FatalError(char const*, char const*) [node]
  3: 0xd22ffe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
  4: 0xd23377 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
  5: 0xedc7a5  [node]
  6: 0xedd286  [node]
  7: 0xeecefc  [node]
  8: 0xeed970 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
  9: 0xef0895 v8::internal::Heap::HandleGCRequest() [node]
 10: 0xe7b797 v8::internal::StackGuard::HandleInterrupts() [node]
 11: 0x1231ec5 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
 12: 0x1635c39  [node]

It works fine basically 99.9% the time, but all 2 weeks it crashes over night with this message. The index page is just a static page, there are no other changes. There is still plenty of memory and storage left on the server, so running out of memory is not an option.

### Expected Behavior

It does not crash.

### How are you deploying your application? (if relevant)

next start, AWS EC2 Amazon Linux

**Comment by nilankar19** [comment]
bug lie at /home/ec2-user/.../node_modules/next/dist/server/require.js:85:19 
share the code snippet of require:85:19

**Comment by Uni2K** [comment]
I fear that won't help:

![image](https://user-images.githubusercontent.com/20185223/214101362-0c4079a6-f7f3-4432-b861-e3d9bdb55447.png)
