### ISSUE TITLE
[appDir]: Dynamic pages with dynamic parameters rendered as static by default

### ISSUE THREAD

**Issue by peterjuras** [vercel/next.js#45156]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 18.13.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.5-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/peterjuras/nextjs-13-wrong-static-rendering

### To Reproduce

1. Clone the repository
2. Run `yarn build`

### Describe the Bug

In my project, the `[slug]/page` is rendered as static, although the `cookies` function is called. According to the [docs](https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering#using-dynamic-functions), this should mark the page as dynamic.

Right now, for the current canary version the following error occurs however, which is also not as expected:
```
[    ] info  - Generating static pages (0/4)
Error occurred prerendering page "/[slug]/page". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Invariant: Method expects to have requestAsyncStorage, none available
    at cookies (/home/juras/src/misc/nextjs-13-wrong-static-rendering/.next/server/pages/[slug]/page.js:88:15)
    at TestPage (/home/juras/src/misc/nextjs-13-wrong-static-rendering/.next/server/pages/[slug]/page.js:210:38)
    at Wc (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Xc (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409)
    at Zc (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:210)
    at Z (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/juras/src/misc/nextjs-13-wrong-static-rendering/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
```

### Expected Behavior

The page should compile successfully and be marked as dynamic.

**Comment by ben519** [comment]
Your issue says "appDir: true" but your example uses the `pages/` directory, not the `app/` directory.

**Comment by ijjk** [comment]
Hi, `next/headers` is not available in `pages` and is specific to `app` currently.
