### ISSUE TITLE
tests in e2e/appDir for vercel/next.js leads to errors

### ISSUE THREAD

**Issue by sroussey** [vercel/next.js#45233]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 9.3.0
      Yarn: N/A
      pnpm: 7.24.3
    Relevant packages:
      next: 13.1.6-canary.0
      eslint-config-next: 13.1.6-canary.0
      react: 18.2.0
      react-dom: 18.2.0
```

I cloned canary branch today.

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Jest (next/jest)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js

### To Reproduce

After cloning...
```
pnpm i
pnpm build
pnpm testonly-start test/e2e/app-dir/app-static
```

### Describe the Bug

The tests in https://github.com/vercel/next.js/blob/canary/contributing/core/testing.md as examples work fine, but the e2e/appDir ones fail. For the `pnpm testonly-start test/e2e/app-dir/app-static` example:

```
~/C/next.js ❯❯❯ pnpm testonly-start test/e2e/app-dir/app-static

> nextjs-project@0.0.0 testonly-start /Users/steve/Code/next.js
> cross-env NEXT_TEST_MODE=start pnpm testonly "test/e2e/app-dir/app-static"


> nextjs-project@0.0.0 testonly /Users/steve/Code/next.js
> pnpm jest --runInBand "test/e2e/app-dir/app-static"

info  - Using locally built binary of @next/swc
Using test mode: start in test folder e2e
Creating test directory with isolated next...
Creating next instance in:
/private/var/folders/mn/hjbyw5n91w31n1g_nyjplql00000gn/T/next-install-fe343c71d676144f237831167d63cf724688f9fe21c55a238d987aa5deb08077

 RUNS  test/e2e/app-dir/app-static/app-static.test.ts
Packages: +23
+++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/steve/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm

dependencies:
+ @types/node 18.11.18
+ @types/react 18.0.27
+ next 13.1.6-canary.0
+ react 18.2.0
+ react-dom 18.2.0
+ typescript 4.9.4

The integrity of 3323 files was checked. This might have caused installation to take longer.
created next.js install, writing test filesd 1, added 23, done
  console.log
    running yarn next build

      at NextStartInstance.start (lib/next-modes/next-start.ts:66:13)

yarn run v1.22.19
$ /private/var/folders/mn/hjbyw5n91w31n1g_nyjplql00000gn/T/next-install-fe343c71d676144f237831167d63cf724688f9fe21c55a238d987aa5deb08077/node_modules/.bin/next build
warn  - You have enabled experimental features (appDir, fetchCache) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
info  - Creating an optimized production build...
info  - Using locally built binary of @next/swc
Failed to compile.

./node_modules/.pnpm/file+..+..+..+..+..+..+..+Users+steve+Code+next.js+packages+next+packed-next.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/pages/_app.js
Error: unknown field `appDir` at line 1 column 2186

./node_modules/.pnpm/file+..+..+..+..+..+..+..+Users+steve+Code+next.js+packages+next+packed-next.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/pages/_document.js
Error: unknown field `appDir` at line 1 column 2196

./node_modules/.pnpm/file+..+..+..+..+..+..+..+Users+steve+Code+next.js+packages+next+packed-next.tgz_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/pages/_error.js
Error: unknown field `appDir` at line 1 column 2190

./app/(new)/custom/page.js
Error: unknown field `appDir` at line 1 column 1868

Import trace for requested module:
./app/(new)/custom/page.js

./app/(new)/layout.js
Error: unknown field `appDir` at line 1 column 1858

Import trace for requested module:
./app/(new)/layout.js


> Build failed because of webpack errors
error Command failed with exit code 1.
Failed to create next instance Error: next build failed with code/signal 1
    at ChildProcess.<anonymous> (/Users/steve/Code/next.js/test/lib/next-modes/next-start.ts:79:15)
    at ChildProcess.emit (node:events:520:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
  ●  process.exit called with "1"

      183 |       nextInstance.destroy()
      184 |     } catch (_) {}
    > 185 |     process.exit(1)
          |             ^
      186 |   } finally {
      187 |     flushAllTraces()
      188 |   }

      at createNext (lib/e2e-utils.ts:185:13)
      at lib/e2e-utils.ts:216:14

 RUNS  test/e2e/app-dir/app-static/app-static.test.ts
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected Behavior

No to fail your own tests. ;)

**Comment by sroussey** [comment]
BTW: my goal is to make a test to check if pages are actually prerendered during build based on `generateStaticParams`

**Comment by teobler** [comment]
same here, want to use e2e test ensure something, but cannot create next instance and throw errors

**Comment by teobler** [comment]
somehow I fixed this issue by running pnpm clean lol

**Comment by timneutkens** [comment]
Can you try again? Running `pnpm clean` and `pnpm install` should be enough, the reason this happened is that you had an outdated version of SWC running somehow.

**Comment by balazsorban44** [comment]
Closing this as this is likely fixed now. Note that tests are constantly evolving and are trying to cover the latest state of the repository, sometimes could be flaky or time out, but are addressed in quick follow-ups. Ie: we do not usually release a new version of the package with failing tests, as that would be blocked in our CI environment anyway.

You can open a new issue if you still have issues. :pray:
