### ISSUE TITLE
Deploying NextJS Site To Gh-Pages Doesn't Work Even With basePath and assetPrefix

### ISSUE THREAD

**Issue by JimLynchCodes** [vercel/next.js#45370]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

`npx --no-install next info` just returns this:

```
node:fs:2567
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, realpath '/Users/jim/xpress/website/info'
    at Function.realpathSync.native (node:fs:2567:3)
    at Object.getProjectDir (/Users/jim/xpress/website/node_modules/next/dist/lib/get-project-dir.js:39:46)
    at nextDev (/Users/jim/xpress/website/node_modules/next/dist/cli/next-dev.js:84:37)
    at /Users/jim/xpress/website/node_modules/next/dist/bin/next:119:34 {
  errno: -2,
  syscall: 'realpath',
  code: 'ENOENT',
  path: '/Users/jim/xpress/website/info'
}
website (main) 🏖  npx --no-install next info
node:fs:2567
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, realpath '/Users/jim/xpress/website/info'
    at Function.realpathSync.native (node:fs:2567:3)
    at Object.getProjectDir (/Users/jim/xpress/website/node_modules/next/dist/lib/get-project-dir.js:39:46)
    at nextDev (/Users/jim/xpress/website/node_modules/next/dist/cli/next-dev.js:84:37)
    at /Users/jim/xpress/website/node_modules/next/dist/bin/next:119:34 {
  errno: -2,
  syscall: 'realpath',
  code: 'ENOENT',
  path: '/Users/jim/xpress/website/info'
}
```

### Link to the code that reproduces this issue

see code

### To Reproduce

see code

### Describe the Bug

I have a site build with next.js that works locally (code: https://github.com/xpress-smoke-shop/website).

I am trying to deploy a static html version of the site to the domain: https://xpress-smoke-shop.github.io/website/

I can clone the repo and run these commands:

```
nvm use
yarn install
yarn build
yarn export
yarn deploy-gh
```

And I have changed the `next.config.js` file to reflect the repository that I'm using:

```javascript
/* eslint-disable import/no-extraneous-dependencies */
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

module.exports = withBundleAnalyzer({
  poweredByHeader: false,
  trailingSlash: true,
  basePath: '/website',
  assetPrefix: '/website/',
  reactStrictMode: true,
});
```

But my deployed site still looks wrong and has all these file-not-found errors...

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/s73zy.png

### Expected Behavior

working

### Which browser are you using? (if relevant)

any

### How are you deploying your application? (if relevant)

gh-pages

**Comment by JimLynchCodes** [comment]
I must cry
