### ISSUE TITLE
Running development mode on fresh create-next-app not working

### ISSUE THREAD

**Issue by aaronsweeneyweb** [vercel/next.js#45413]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

N/A

### To Reproduce

Run `npm run dev` from root directory of project.

Package.json:
```
{
  "name": "next-base",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@next/font": "13.1.6",
    "next": "13.1.6",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
}

```

### Describe the Bug

When running `npm run dev` on a fresh create-next-app, the dev server is not starting, no errors are logged in the terminal - it just kills the command and shows the terminal cursor again. Localhost is not being used by another application.

### Expected Behavior

Dev server to spin up in localhost:3000.

**Comment by mjth** [comment]
+1 looks like I'm having the same issue. My repo was working perfectly on windows, but can't get the dev server to start up on Mac.

**Comment by mjth** [comment]
Additional note, rolled all the way back to next@13.0.0 to have it working again. Even 13.0.1 was still crashing with the same issue.

**Comment by mjth** [comment]
Can confirm next@canary still experiences the same issue.

**Comment by aaronsweeneyweb** [comment]
> Additional note, rolled all the way back to next@13.0.0 to have it working again. Even 13.0.1 was still crashing with the same issue.

Thanks @mjth  - Working for me on 13.0.0 too. Will just use that for now.

**Comment by mjth** [comment]
Looking back at the commit history, perhaps an issue with [this one](https://github.com/vercel/next.js/commit/96696c2d3bf24b181d24ecc57506e66de3c5a44b
)

@ijjk - CLI/bin isn't my speciality, any chance you could look into if this would cause some issues with older macs?

**Comment by balazsorban44** [comment]
> Additional note, rolled all the way back to next@13.0.0 to have it working again. Even 13.0.1 was still crashing with the same issue.

This is very helpful, could you maybe pin down the exact `canary` release this way too (13.0.1-canary.0 - 13.0.1-canary.4)? :pray: The commit you link to does sound relevant.

**Comment by ijjk** [comment]
@mjth can you add a screen recording showing the behavior you are seeing if no errors are being shown that can be shared?

**Comment by AndreLSilva** [comment]
Just to add some information: I'm also on `next: 13.1.6` and experiencing a really similar (if not the same) issue, but for me the dev server doesn't exit, just stays there as if it was working properly.
I'm using Ubuntu via WSL on Windows.

**Comment by ZiBuDo** [comment]
+1 saw this issue, when I debug the stack trace I get the issue to point at _webpack.webpack.DefinePlugin is undefined because the import seems to not have called the _webpack.init() method, if I do this manually with breakpoints I get further, but I get it working on 13.0.0 as stated above

**Comment by gcd253** [comment]
I was experiencing a very similar issue on `next: 13.1.6`

After installing the canary version, `npm run dev` was was working as intended. I am on Mac

**Comment by ZiBuDo** [comment]
When I run on 13.0.0 I see:
![image](https://user-images.githubusercontent.com/8965320/218608906-0287458a-2c7b-433e-982a-1edca65157cb.png)

in next/dist/server/config.js

When I run on canary 13.1.7-11 I see:
![image](https://user-images.githubusercontent.com/8965320/218609062-a8aec6e4-327c-4d60-910d-6ef5b3977a75.png)


The error I ultimately get on canary is:

Failed to start next js server TypeError: Cannot read properties of undefined (reading 'ProvidePlugin')
    at Object.getBaseWebpackConfig [as default] (\node_modules\next\src\build\webpack-config.ts:2019:21)
    at async Promise.all (index 0)
    at Span.traceAsyncFn (\node_modules\next\src\trace\trace.ts:106:14)
    at Span.traceAsyncFn (\node_modules\next\src\trace\trace.ts:106:14)
    at HotReloader.start (\node_modules\next\src\server\dev\hot-reloader.ts:584:26)
    at DevServer.prepare (\node_modules\next\src\server\dev\next-dev-server.ts:731:5)
    at ViewService.createServer (\src\server\view\view.service.ts:21:9)
    at bootstrap (\src\server\main.ts:77:5) {stack: 'TypeError: Cannot read properties of undefined...\src\server\main.ts:77:5)', message: 'Cannot read properties of undefined (reading 'ProvidePlugin')'}

If the loadWebpackHook this doesn't happen for me, I remove the conditional load and the server starts fine for me.

**Comment by Juugis** [comment]
on next:^13.2.1 getting error: TypeError: Cannot read properties of undefined (reading 'ProvidePlugin') while building custom dev server. Production environment works fine. next:^13.0.1 does not have this issue. Please fix.

**Comment by frankda** [comment]
Experiencing the same issue with next `13.2.1`, getting error: TypeError: Cannot read properties of undefined (reading 'ProvidePlugin') while building custom dev server. Raised details in https://github.com/vercel/next.js/issues/46588. Stackbliz link: https://stackblitz.com/edit/nextjs-n5mjba?file=package.json,.vscode%2Fsnippets.json

**Comment by frankda** [comment]
Any updates for this one?

**Comment by farhan2077** [comment]
Can confirm this issue still exists in nextjs `13.2.4`. So installed nextjs `13.0.0` as per suggestion. My current dependencies look like this:
![image](https://user-images.githubusercontent.com/32035481/226174342-82932549-79fa-4040-a96c-0f5846aaf7e2.png)

However downgrading to version 13 introduces another problem.
![image](https://user-images.githubusercontent.com/32035481/226174383-127b1481-fa99-4f46-a6ee-345aeb3b7417.png)
Removing instances of `next/font` removes the error but that's not the solution either.

**Comment by karlhorky** [comment]
> Looks like this commit introduced this condition:
> [aa0664c](https://github.com/vercel/next.js/commit/aa0664cc2c0415fbe851a0e2aa9dd932bc9327e9)
> Any reason why this is needed?

@ijjk do you think aa0664cc2c0415fbe851a0e2aa9dd932bc9327e9 (your PR with the experimental #43198) may be breaking things here as well, as @farhan2077 [mentioned above](https://github.com/vercel/next.js/issues/45413#issuecomment-1475234869)?

The other location that it could be breaking things is this other issue:

- https://github.com/vercel/next.js/issues/46588

**Comment by Veath** [comment]
I have similar problem
```
➜  ai-app git:(main) ✗ npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 7.18.2
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.1.0
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.2.4", newest: "13.2.5-canary.28".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

`pnpm  run dev` automatically exits without an error message, but `pnpm run build` has the following error message
```
ai-app git:(main) ✗ pnpm run build  

> ai-app@0.1.0 build /Users/veath/forchange/ai-app
> next build

info  - Linting and checking validity of types  
info  - Creating an optimized production build ..[1]    74295 segmentation fault  pnpm run build
```

**Comment by rdimascio** [comment]
@ijjk I've tracked down the conditional loading of compiled Webpack to be the culprit - https://github.com/vercel/next.js/pull/43198/files#diff-7836d903b56ef6914ef5f3e8d1711c1d353d7b6ae4efefb0d2193897ee4fca85R837-R839

I removed that condition from my local `next@13.2.4` build and everything is working as expected when using `conf`

**Comment by stern-shawn** [comment]
> **UPDATE:** Instead of downgrading nextjs, I downgraded installed node to `16.9.1` and now it's working with latest nextjs `13.2.4`. However, again this is not a solution either.

I've been running into SIGSEGV and silent crashes all day trying to get my application working on my chromebook (crostini) instead of my mac. Downgrading Node to `16.9.1` finally has it working for me locally, thank you ❤️

**Comment by lizardlove** [comment]
still open, I have same issue right now. I use next@latest init a new project, `yarn dev` can not work. I downgrade next@13.0.0, there are error 'can not import next/font/google`.
