### ISSUE TITLE
Error: error:1E08010C:DECODER routines::unsupported (`ERR_OSSL_UNSUPPORTED`)

### ISSUE THREAD

**Issue by nuotsu** [vercel/next.js#45578]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
	Platform: darwin
	Arch: arm64
	Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
Binaries:
	Node: 18.14.0
	npm: 9.3.1
	Yarn: 1.22.19
	pnpm: 6.32.10
Relevant packages:
	next: 13.1.6
	eslint-config-next: N/A
	react: 18.2.0
	react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

API routes

### Link to the code that reproduces this issue

https://github.com/nuotsu/next-ossl-issue

### To Reproduce

1. Install `googleapis` and setup a Google Spreadsheet with Spreadsheet API enabled and setup.
2. Setup `api/hello.ts` and insert Spreadsheet retrieval code
```js
const auth = new google.auth.JWT(
	'<EMAIL>.iam.gserviceaccount.com',
	undefined,
	'<SECRET>',
	['https://www.googleapis.com/auth/spreadsheets.readonly'],
)

const sheets = google.sheets({ version: 'v4', auth })

const response = await sheets.spreadsheets.values.get({
	spreadsheetId: '<ID',
	range: '<RANGE>',
})

console.log(response)
```
3. Error displays in the console.
```sh
Error: error:1E08010C:DECODER routines::unsupported
```

### Describe the Bug

```
Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (/.../node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/.../node_modules/jws/lib/sign-stream.js:32:24)
    at GoogleToken.requestToken (/.../node_modules/gtoken/build/src/index.js:232:31)
    at GoogleToken.getTokenAsyncInner (/.../node_modules/gtoken/build/src/index.js:166:21)
    at GoogleToken.getTokenAsync (/.../node_modules/gtoken/build/src/index.js:145:55)
    at GoogleToken.getToken (/.../node_modules/gtoken/build/src/index.js:97:21)
    at JWT.refreshTokenNoCache (/.../node_modules/google-auth-library/build/src/auth/jwtclient.js:172:36)
    at JWT.refreshToken (/.../node_modules/google-auth-library/build/src/auth/oauth2client.js:153:24)
    at JWT.getRequestMetadataAsync (/.../node_modules/google-auth-library/build/src/auth/oauth2client.js:298:28)
    at JWT.getRequestMetadataAsync (/.../node_modules/google-auth-library/build/src/auth/jwtclient.js:94:26)
    at JWT.requestAsync (/.../node_modules/google-auth-library/build/src/auth/oauth2client.js:371:34)
    at JWT.request (/.../node_modules/google-auth-library/build/src/auth/oauth2client.js:365:25)
    at createAPIRequestAsync (/.../node_modules/googleapis-common/build/src/apirequest.js:273:31)
    at createAPIRequest (/.../node_modules/googleapis-common/build/src/apirequest.js:52:16)
    at Resource$Spreadsheets$Values.get (/.../node_modules/googleapis/build/src/apis/sheets/v4.js:570:65)
    at handler (webpack-internal:///(api)/./src/pages/api/hello.ts:19:59)
    at Object.apiResolver (/.../node_modules/next/dist/server/api-utils/node.js:372:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runApi (/.../node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/.../node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/.../node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/.../node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/.../node_modules/next/dist/server/dev/next-dev-server.js:743:20)
    at async DevServer.handleRequest (/.../node_modules/next/dist/server/base-server.js:322:20) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}
```

### Expected Behavior

Successfully connect to API and retrieve the response.

**Comment by SukkaW** [comment]
The issue should be reported to the `googleapis`, IMHO it is not related to Next.js

**Comment by jsmrcaga** [comment]
@nuotsu while looking for this error (bc using signature verify on NodeJS, nothing to do with next.js or react) I stumbled upon this answer:
https://stackoverflow.com/a/72338317/1895443
hope this helps and this issue can be closed

**Comment by ernestd** [comment]
@jsmrcaga I don't really understand the answer given in that stackoverflow thread. Setting the google private key to empty string?!

**Comment by nuotsu** [comment]
I was able to resolve. I had used a different type of API key (needed to use the once that includes the `\n` line break characters, aka the "long" one).

Stupid and basic error on my end, but regardless, the error logs were not helpful at all and lead me in a way different different to find the solution.

**Comment by jsmrcaga** [comment]
@ernestd I have no idea. I was looking for this actual error because I am playing with cryptography, but it appears mostly on this google thing. I'm guessing as @nuotsu said it's a problem on "which" key to use, or if you even need one 🤷🏼 

in any case the google documentation will be a better place to find answers than the nextjs github issues page. And someone using these APIs should really open an issue on google sdk to explain the problem, they could catch the error and give more context to developers. Good luck on your google endeavours! ✨

**Comment by The-True-Hooha** [comment]
I'm not using google or next.js in my case, but I'm currently facing this error. 

I would appreciate any help/pointers @nuotsu @jsmrcaga

**Comment by jsmrcaga** [comment]
@The-True-Hooha i've created this issue to migrate the discussion away from other libraries, we can continue there
https://github.com/nodejs/help/issues/4115

**Comment by ted123** [comment]
Just sharing what I did so I can call on the google sheets api, in case someone gets stuck.
You need to set node options to:
```NODE_OPTIONS=--openssl-legacy-provider```
but setting it directly in the env variables in vercel will yield an error, so what I did is add a script in my build command that will reset the NODE_OPTIONS to the desired value
Here is the contents of the script (I think you can just use `delete` to unset the variable but I placed both ways just incase) :
```
process.env.NODE_OPTIONS=undefined
delete process.env.NODE_OPTIONS
process.NODE_OPTIONS="--openssl-legacy-provider"
```
and in the package.json build command place something like:
```"build": "node scripts/fixSSL.js && next build",```

Hope it helps.
