### ISSUE TITLE
fix pageExtensions to allow regular expressions and also "draft" pages

### ISSUE THREAD

**Issue by y-nk** [vercel/next.js#45646]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.24.3
    Relevant packages:
      next: 13.1.7-canary.4
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

will add after getting issue number

### To Reproduce

1. create a next project (with appDir enabled, but it's not really important here)
2. add a route such as `app/(published)/article-1/page.tsx`
3. add a route such as `app/(drafts)/article-2/page.ts`
4. add `pageExtensions` in next config as following:

```
  // cut off what's under `(drafts)/` for non dev
  pageExtensions: process.env.NODE_ENV !== 'development'
    ? ["(?<!(drafts).*).tsx?"]
    : ["tsx?"],
```

### Describe the Bug

# The regular expression used during the build does not allow RegExp syntax to be inserted.

### Investigation

I've put console.log to debug the RegExp, which seems to be assembled properly but there's a further bug in webpack later on.

Places to log:

1. `regexp`: https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/index.ts#L489-L498
2. `{ absolutePath, filter, partName }`: https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/lib/recursive-readdir.ts#L40-L42
3. `regexp`: https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/entries.ts#L53-L61
4. `pageKey`: https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/entries.ts#L83-L85

Log output:

```
{
  absolutePath: '/~/app/head.tsx',
  filter: /^page\.(?:(?<!(drafts).*).tsx?)$/,
  partName: 'head.tsx'
}
{
  absolutePath: '/~/app/layout.tsx',
  filter: /^page\.(?:(?<!(drafts).*).tsx?)$/,
  partName: 'layout.tsx'
}
```

We can see that this line here may cause a problem against lookbehind in regular expression.

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/lib/recursive-readdir.ts#L40-L42

We can change to:

```diff
-if (!filter.test(path.name)) {
+if (!filter.test(absolutePath)) {
  return;
}
```

...and the regular expression becomes aware of the full path of the file, which can be handy, but...

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/index.ts#L489-L498

The regular expression used is `/^page\.(${pageExtensions.join('|')})$/` ; the problematic part is `/^page\.` since it enforces that the tested string starts with `page`, but hopefully removing `^` helps easily there.

```diff
if (appDir) {
  appPaths = await nextBuildSpan
    .traceChild('collect-app-paths')
    .traceAsyncFn(() =>
      recursiveReadDir(
        appDir,
-        new RegExp(`^page\\.(?:${config.pageExtensions.join('|')})$`)
+        new RegExp(`page\\.(?:${config.pageExtensions.join('|')})$`)
      )
    )
}
```

The `\\.` is not ideal, but we can always modify the `pageExtensions` to be `(?<!(drafts).*)tsx?` which omits the dot in the extension. It's a bit less natural but kinda ok.

Running again `yarn build` now yields console.logs 3 and 4, a sign that the routes were properly included (excluding the one containing `(drafts)`):

```
{ regexp: /\.+((?<!(drafts).*)tsx?)$/ }
{ pageKey: '/api/hello' } // ← lambda from boilerplate
{ regexp: /\.+((?<!(drafts).*)tsx?)$/ }
{ pageKey: '/page' } // ← index
{ regexp: /\.+((?<!(drafts).*)tsx?)$/ }
{ pageKey: '/(published)/article-1/page' }
```

We can further add a console.log here:

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/entries.ts#L320-L322

showing this log:

```
{
  appPathsPerRoute: {
    '/': [ '/page' ],
    '/article-1': [ '/(published)/article-1/page' ],
  }
}
```

...but now webpack complains:

```
TypeError: Cannot read properties of null (reading 'request')
    at /~/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:220:55
```

So, `entryMod` is `null` and looking at `{ compilation }` shows this:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '(drafts).*)tsx%3F' in '/~/'`
```

Checking the `{ entrypoints }` in here:

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/webpack-build.ts#L51-L69

shows:

```
server: {
    'app/page': {
      import: 'next-app-loader?name=app%2Fpage&pagePath=private-next-app-dir%2Fpage.tsx&appDir=%2F~%2Fapp&appPaths=%2Fpage&pageExtensions=(%3F%3C!(drafts).*)tsx%3F!',
      layer: 'sc_server'
    },
    'app/(published)/article-1/page': {
      import: 'next-app-loader?name=app%2F(published)%2Farticle-1%2Fpage&pagePath=private-next-app-dir%2F(published)%2Farticle-1%2Fpage.ts&appDir=%2F~%2Fapp&appPaths=%2F(published)%2Farticle-1%2Fpage&pageExtensions=(%3F%3C!(drafts).*)tsx%3F!',
      layer: 'sc_server'
    },
```

which seems to be related to the trouble, since the webpack error is a `ModuleNotFound` so there must be a problem with a import string, defined at:

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/entries.ts#L225

By checking if/how `pageExtensions` is used in next-app-loader, we can see this:

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/webpack/loaders/next-app-loader.ts#L193-L198

which is obviously our problem.

Since the `import` string seems to be broken, we can eventually hotfix `pageExtensions` not to be the user defined config values, but rather an array containing the actual extension of the file (so that, it'd be a perfect match all the time):

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/entries.ts#L225

```diff
export function getAppEntry(opts: {
  name: string
  pagePath: string
  appDir: string
  appPaths: string[] | null
  pageExtensions: string[]
  isDev?: boolean
  rootDir?: string
  tsconfigPath?: string
}) {
+ const [_, fileExtension] = opts.pagePath.match(/\.([\w]*)$/i)
+ opts.pageExtensions = [fileExtension]

  return {
    import: `next-app-loader?${stringify(opts)}!`,
    layer: WEBPACK_LAYERS.server,
  }
}
```

and running this falls into a minor serialisation problem:

```
./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fpage&pagePath=private-next-app-dir%2Fpage.tsx&appDir=%2F~%2Fapp&appPaths=%2Fpage&pageExtensions=tsx!
TypeError: pageExtensions.map is not a function
    at Object.nextAppLoader (/~/node_modules/next/dist/build/webpack/loaders/next-app-loader.js:161:39)
```

it seems that, because there's only _one_ entry in pageExtensions, the deserialized value of `pageExtensions` in the loader is `string` rather than `string[]`, which we can confirm by adding a console.log right before:

https://github.com/vercel/next.js/blob/836ac9cc7f290e95b564a61341fa95a5f4f0327e/packages/next/src/build/webpack/loaders/next-app-loader.ts#L193-L198

such as `console.log(console.log({ ...buildInfo.route, name, pageExtensions })`

revealing that `pageExtensions` is now a string!

```
{
  page: '/page',
  absolutePagePath: '/~/app/page.tsx',
  name: 'app/page',
  pageExtensions: 'tsx' // ← hello!
}
```

I thought first that it'd be easier to fix the `next-app-loader` to correct the type of `pageExtensions`, such as:

```
const extensions = (Array.isArray(pageExtensions) ? pageExtensions : [pageExtensions])
  .map((extension)=>`.${extension}`);
```

but doing so threw an Error when using non `.tsx` pages saying:

```
error - /(published)/article-1/page.ts doesn't have a root layout. To fix this error, make sure every page has a root layout.
```

so i figured the best way to fix this issue was simply:

```
export function getAppEntry(opts: {
  name: string
  pagePath: string
  appDir: string
  appPaths: string[] | null
  pageExtensions: string[]
  isDev?: boolean
  rootDir?: string
  tsconfigPath?: string
}) {
+ const [_, fileExtension] = opts.pagePath.match(/\.([\w]*)$/i)
+ opts.pageExtensions = ['tsx', fileExtension]

  return {
    import: `next-app-loader?${stringify(opts)}!`,
    layer: WEBPACK_LAYERS.server,
  }
}
```

### Expected Behavior

Doing all the fixes above allowed me to easily have lookbehind expressions in `pageExtensions` to create "draft" pages, only available on dev mode, but not in production mode.

Result of the build afterwards is:

```
info  - Generating static pages (2/2)
info  - Finalizing page optimization

Route (app)                                Size     First Load JS
┌ ○ /                                      0 B                0 B
└ ○ /article-1                             0 B                0 B
```

(Don't mind the 0B, this is another bug but non blocking)

**Comment by y-nk** [comment]
👀

**Comment by y-nk** [comment]
😂
