### ISSUE TITLE
Better handling of "Error: Export encountered errors on following paths:"

### ISSUE THREAD

**Issue by wscourge** [vercel/next.js#45713]
### Describe the feature you'd like to request

I reached the point where this error:

> Error: Export encountered errors on following paths

is not solvable based on its message. It gives me nothing useful and is an equivalent to "it does not work".

<details>
  <summary>Build log</summary>

  When running ` yarn next build --profile --no-lint`, I get the following:

```js
  yarn run v1.22.19
  $ /opt/app/node_modules/.bin/next build --profile --no-lint
  warn  - Profiling is enabled. Note: This may affect performance
  warn  - Linting is disabled
  warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
  info  - Skipping validation of types
  info  - Creating an optimized production build...
  info  - Compiled successfully
  info  - Collecting page data...
  Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
  Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization
  info  - Generating static pages (0/21)
  info  - Generating static pages (5/21)
  info  - Generating static pages (10/21)
  info  - Generating static pages (15/21)
  Error: getaddrinfo ENOTFOUND hix-cms
  Error: getaddrinfo ENOTFOUND hix-cms
  Error: getaddrinfo ENOTFOUND hix-cms
  Error: getaddrinfo ENOTFOUND hix-cms
  Error: getaddrinfo ENOTFOUND hix-api
  Error occurred prerendering page "/ruby/ruby-on-rails/checkout". Read more: https://nextjs.org/docs/messages/prerender-error
  Error: getaddrinfo ENOTFOUND hix-api
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
  info  - Generating static pages (21/21)
  > Build error occurred
  Error: Export encountered errors on following paths:
    /[language]/[template]/checkout: /ruby/ruby-on-rails/checkout
      at /opt/app/node_modules/next/dist/export/index.js:404:19
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Span.traceAsyncFn (/opt/app/node_modules/next/dist/trace/trace.js:79:20)
      at async /opt/app/node_modules/next/dist/build/index.js:1229:21
      at async Span.traceAsyncFn (/opt/app/node_modules/next/dist/trace/trace.js:79:20)
      at async /opt/app/node_modules/next/dist/build/index.js:1091:17
      at async Span.traceAsyncFn (/opt/app/node_modules/next/dist/trace/trace.js:79:20)
      at async Object.build [as default] (/opt/app/node_modules/next/dist/build/index.js:65:29)
```
</details>

### Describe the solution you'd like

The "paths" mentioned in the stacktrace simply points to the page in the `pages` folder, and that's it. I'd like to know which component is responsible - ideally, which line/char of my code.

### Describe alternatives you've considered

Not really

**Comment by wscourge** [comment]
Nothing mentioned on the ["Prerender error"](https://nextjs.org/docs/messages/prerender-error) page is helpful, too.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.

**Comment by PLQin** [comment]
Execute `next dev` first, keep the server running, and then execute `next build&&next export`;

**Comment by Perumalt82** [comment]
Error: Export encountered errors on following paths:
	/p/[id]
    at /Users/apple/Documents/STW-Projects/stw-frontend-app/STWCommerceFrontEnd/node_modules/next/dist/export/index.js:31:1106
    at async Span.traceAsyncFn (/Users/apple/Documents/STW-Projects/stw-frontend-app/STWCommerceFrontEnd/node_modules/next/dist/telemetry/trace/trace.js:6:584)
