### ISSUE TITLE
[NEXT-518] Bundler throws error when bundles a third-partry lib that uses next/dynamic

### ISSUE THREAD

**Issue by jianliao** [vercel/next.js#45756]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```yaml
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
Binaries:
  Node: 19.5.0
  npm: 9.3.1
  Yarn: 1.22.19
  pnpm: 7.26.0
Relevant packages:
  next: 13.1.7-canary.8
  eslint-config-next: 13.1.6
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

https://github.com/jianliao/nextjs-bundler-bug

### To Reproduce

```
$ npm i
$ npm run build
```

### Describe the Bug

Below error only throws when using the latest canary. next@13.1.6 works fine.
```
> npm run build

> nextjs-next-dynamic-bug@0.1.0 build
> next build

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Linting and checking validity of types  
info  - Collecting page data  
[    ] info  - Generating static pages (0/3)TypeError: next_dynamic__WEBPACK_IMPORTED_MODULE_0__ is not a function
    at 9294 (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/chunks/544.js:5559:18)
    at __webpack_require__ (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/webpack-runtime.js:25:43)
    at 7989 (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/app/page.js:360:12)
    at __webpack_require__ (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/webpack-runtime.js:25:43)
    at /Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:915:337

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: next_dynamic__WEBPACK_IMPORTED_MODULE_0__ is not a function
    at 9294 (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/chunks/544.js:5559:18)
    at __webpack_require__ (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/webpack-runtime.js:25:43)
    at 7989 (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/app/page.js:360:12)
    at __webpack_require__ (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/.next/server/webpack-runtime.js:25:43)
    at /Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:915:337
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
        /page: /
    at /Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/export/index.js:417:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/build/index.js:1268:21
    at async Span.traceAsyncFn (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/build/index.js:1127:17
    at async Span.traceAsyncFn (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/Users/jianliao/Work/git/nextjs-next-dynamic-bug/node_modules/next/dist/build/index.js:69:29)
```
The code that causes the error is in [app/page.tsx](https://github.com/jianliao/nextjs-bundler-bug/blob/ae02053df7309302e01478531217ff7c89b41566/app/page.tsx#L6). Line 7 is the same local component that uses `next/dynamic` and it works fine. But the `SpButton` that comes from a third-party library will fail the build. 

### Expected Behavior

No error and build success.

### Which browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

<sub>[NEXT-518](https://linear.app/vercel/issue/NEXT-518/bundler-throws-error-when-bundles-a-third-partry-lib-that-uses)</sub>

**Comment by jianliao** [comment]
Thanks man @huozhi
