### ISSUE TITLE
Next build throwing error while building in argo workflow: Error occurred prerendering page "/page-name".

### ISSUE THREAD

**Issue by sharanyam123** [vercel/next.js#45840]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

`react` version: 17.0.2
`next` version: 12.0.7
`nx` version: 13.6.1
`@emotion/react` version: 11.10.5

### Link to the code that reproduces this issue

currently dont have a demo repo

### To Reproduce

create nx monorepo with next+react
emotion versions: 11.10.5
build the next application in argo workflow

### Describe the Bug

I have nx monorepo project with nextJS + React and I am using @emotion/react and @emotion/styled in project. Earlier it was working fine but all of a sudden while building the project in argo workflow It is throwing the error related to emotion/styled for all the pages.

Note: In local, build is successful but while building in argo workflow I am facing this issue

```
Error occurred prerendering page "/page-name". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'registered' of undefined
    at /project-directory/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.prod.js:131:53
    at Styled(svg) (/project-directory/node_modules/@emotion/react/dist/emotion-element-20108edd.cjs.prod.js:62:16)
    at d (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/project-directory/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/project-directory/node_modules/next/dist/server/render.js:686:46)
    at Object.defaultGetInitialProps (/project-directory/node_modules/next/dist/server/render.js:316:51)
    at Function.getInitialProps (/project-directory/dist/apps/ui/.next/server/pages/_document.js:514:20)
```

```
Docker file: 
FROM node:14.21.0-alpine3.16

ARG ENV="${ENV}"

RUN apk --no-cache add git

RUN git clone --single-branch --branch master 

WORKDIR /project-directory

RUN npm config set user 0

RUN node --version

RUN npm --version

RUN npm cache clean --force

RUN npm install --force

RUN npm i @nx-tools/nx-docker

RUN npm install -g node-modules

RUN npm install -g @nrwl/cli

RUN npm run build:${ENV} -----> error at this step

CMD npx nx run ui:serve --configuration=production
```

### Expected Behavior

Build should be succesful

### How are you deploying your application? (if relevant)

deploying the application through linux remote host to argo workflow by executing the docker file commands

_No response_

**Comment by Garajluc** [comment]
I have similar problem with `"react": "18.2.0"`, `"next": "13.1.6"` and `"@emotion/react": "11.10.5"`, `"@emotion/styled": "11.10.5"`. All of the sudden the build fails on TypeError during the prerendering stage:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'compat')
    at /home/ubuntu/console/node_modules/@emotion/react/dist/emotion-react.cjs.prod.js:85:36
    at /home/ubuntu/console/node_modules/@emotion/react/dist/emotion-element-eeaa326f.cjs.prod.js:27:31
    at Wc (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/home/ubuntu/console/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
```

**Comment by sharanyam123** [comment]
The issue I am facing is because of @mui/material, I think the issue will get resolved once their PR will get merged
[https://github.com/mui/material-ui/issues/36096](https://github.com/emotion-js/emotion/issues/url)
PR: [https://github.com/mui/material-ui/pull/36162](https://github.com/emotion-js/emotion/issues/url)
