### ISSUE TITLE
Plugin combination produces TypeError

### ISSUE THREAD

**Issue by alex289** [vercel/next.js#45870]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.0
      npm: 9.4.2
      Yarn: 1.22.19
      pnpm: 7.27.0
    Relevant packages:
      next: 13.1.7-canary.11
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/alex289/nextjs-error-example

### To Reproduce

Run `pnpm build` or `pnpm dev` to get the error.

### Describe the Bug

Using the next-content layer and the next-intl plugin in the next.config.js crashes the build.

When running `pnpm build` or `pnpm dev` I get the following error:

TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default(...)' as it is undefined.
    at Object.7965 (/Users/alex/dev/test-app/.next/server/chunks/171.js:11293:9)
    at __webpack_require__ (/Users/alex/dev/test-app/.next/server/webpack-runtime.js:25:42)
    at Object.3173 (/Users/alex/dev/test-app/.next/server/chunks/171.js:7694:15)
    at __webpack_require__ (/Users/alex/dev/test-app/.next/server/webpack-runtime.js:25:42)
    at Object.9561 (/Users/alex/dev/test-app/.next/server/chunks/171.js:8216:26)
    at __webpack_require__ (/Users/alex/dev/test-app/.next/server/webpack-runtime.js:25:42)
    at Object.7535 (/Users/alex/dev/test-app/.next/server/app/[locale]/page.js:443:67)
    at Function.__webpack_require__ (/Users/alex/dev/test-app/.next/server/webpack-runtime.js:25:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async collectGenerateParams (/Users/alex/dev/test-app/node_modules/.pnpm/next@13.1.7-canary.11_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/utils.js:715:17)

I don't know if this is a Nextjs problem and opened issues on the plugin repos as well
https://github.com/contentlayerdev/contentlayer/issues/341
https://github.com/amannn/next-intl/issues/188

### Expected Behavior

No error at all.

**Comment by amannn** [comment]
See also: https://github.com/contentlayerdev/contentlayer/issues/341#issuecomment-1429313376

I don't think this is an issue in Next.js.
