### ISSUE TITLE
[NEXT-705] API routes returning 404 when adding RSC header

### ISSUE THREAD

**Issue by rijk** [vercel/next.js#46095]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
npx next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.26.3
    Relevant packages:
      next: 13.1.7-canary.20
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/rijk/repro-issue-api-rsc-routing

### To Reproduce

1. Go to https://repro-issue-api-rsc-routing.vercel.app/
2. Observe in Network console prefetch call to /api/get-next-lesson returning a 404
3. Click on [Continue learning](https://repro-issue-api-rsc-routing.vercel.app/api/get-next-lesson) link
4. Observe no 404, but redirecting as intended

Alternative reproduction:

1. Do a GET request to https://repro-issue-api-rsc-routing.vercel.app/api/get-next-lesson from Postman
2. Observe lesson page returned
3. Add `RSC: 1` header
4. Observe 404 returned

### Describe the Bug

In my course app, there are "Continue" buttons that take take you to the next uncompleted lesson in the course. This is implemented with an API route, that fetches your progress and then redirects you to the next lesson.

This works fine when clicking the link, however when the router prefetches it, Vercel returns a 404. I believe this is because the `RSC` header forces the routing into the app directory, even though this is an API route. I think this header should be ignored for API routes (and maybe for all routes that have a filesystem match in the `pages` directory, but not sure about that).

### Expected Behavior

I would expect the server to return the same thing for a GET request to https://repro-issue-api-rsc-routing.vercel.app/api/get-next-lesson with or without the `RSC` header: the redirect. This is how it works when running the code locally through `npm dev`, and allows the client to prefetch so it already knows what to redirect to and the user does not have to wait when clicking the Continue button.

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-705](https://linear.app/vercel/issue/NEXT-705/api-routes-returning-404-when-adding-rsc-header)</sub>

**Comment by rijk** [comment]
[I added an `/app/[lesson]/[sub]/page.tsx`](https://github.com/rijk/repro-issue-api-rsc-routing/commit/1edfbe5ce93859e69840ff5b0ce20a5e245a3eb1) to see if this would match the API request. This resulted in Vercel now returning a 500 instead of a 404. This was the error in the console:

```
[GET] /api/get-next-lesson
14:44:08:63
2023-02-18T13:44:09.195Z	047c4a5a-2e1c-48d3-ac7e-5904da032429	ERROR	Error: Cannot find module '/var/task/.next/server/pages/api/get-next-lesson.js'
Require stack:
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at mod._resolveFilename (/var/task/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:486:34)
    at NextNodeServer.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:830:21)
    at Object.fn (/var/task/node_modules/next/dist/server/next-server.js:784:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:229:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ]
}
RequestId: 047c4a5a-2e1c-48d3-ac7e-5904da032429 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

The deployment is [here](https://repro-issue-api-rsc-routing-ak7435g9t-uniti.vercel.app), to reproduce do a GET request to https://repro-issue-api-rsc-routing-ak7435g9t-uniti.vercel.app/api/get-next-lesson with `RSC: 1`.

**Comment by ianwensink** [comment]
I have this as well for a page that is the result of a url rewrite. The rewrite is gradually adopting a Next app but keeping the old app in place as well by rewriting it. Is there any news on this?

**Comment by chrisb2244** [comment]
Also causing me minor issues (well, flags on check systems and a 404 in the console, site appears fine if you don't check the console!) with a `route.ts` which redirects to a dynamic page (like so):

```
// app/my-page/route.ts
import { redirect } from 'next/navigation';
import { currentDisplayYear } from '@/lib/databaseModels';

export const GET = () => {
  redirect(`/my-page/${currentDisplayYear}`);
};
```

```
// app/my-page/[year]/page.tsx
type PageProps = {
  params: {
    year: string;
  }
}

const MyPageForYear = async (props: PageProps) => {
  const { params: { year } } = props;

  return (
    // all of the page stuff
  )
}
```

Does switching to a `page.tsx` (from `route.ts`) and then redirecting "fix" this? Is there some other suitable workaround?

**Comment by gkielwasser** [comment]
I have the same issue.

This 404 seems to happen more generally when landing on a page from app folder having a Link trying to prefetch a page that exists only on pages folder.

**Comment by mdstaff** [comment]
I'm seeing the same behaviour described by @chrisb2244 per https://github.com/vercel/next.js/issues/46095#issuecomment-1752923322

**Comment by RyanJMS** [comment]
If a Link doesn't necessarily need to be prefetched, you can disable it using prefetched={false} on your Link components. Removed the browser errors I was getting. Not a fix, but will remove errors.

**Comment by rijk** [comment]
Not stale

**Comment by huozhi** [comment]
Hi, seems you're using the Next.js 13 in the original repro. Can you upgrade to latest Next.js? I've verified the issue is goned now.

The local prefetch to the pages router API url `/api/get-next-lesson?_rsc=3lb4g` with as RSC request will be redirected to the actual API route.

<img width="841" height="338" alt="Image" src="https://github.com/user-attachments/assets/07a3d4a7-db59-4e68-bfa0-09bc128b3e46" />

You can refer to [this upgration doc](https://nextjs.org/docs/app/guides/upgrading/version-15) to migrate your app to latest Next.js.
