### ISSUE TITLE
Error: Cannot find module 'next/dist/server/font-utils'

### ISSUE THREAD

**Issue by KosmosKey** [vercel/next.js#46194]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Hey there i am using nextjs version 13.0.7 and i have tried installing @next/font@13.0.7 and i got this error:

pages\_app.tsx An error occured in `@next/font`.  Error: Cannot find module 'next/dist/server/font-utils'

I have also tried upgrading latest versions of next and @next/font, but still no luck. 

I have also tried to delete the `.next` and rebuild it as well.

Code: 
```
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (@next/font)

### Link to the code that reproduces this issue

Code is above ☝️

### To Reproduce

`npm i --save @next/font@13.0.7`

### Describe the Bug

Error: Cannot find module 'next/dist/server/font-utils'

This happens on next version 13.0.7

### Expected Behavior

To work fine

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

No. Locally

**Comment by balazsorban44** [comment]
Quick note, `@next/font` is becoming `next/font`, so you will only need to install `next@canary`, and change the imports by removing the `@` symbol. Let us know if that resolves your issue! If it does not, could you attach a reproduction repository so we can look into this?

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.

**Comment by kelvinsekx** [comment]
When I tried installing next@canary, it didn't resolve it for me. Instead I got this error

```
error - Failed to patch lockfile, please try uninstalling and reinstalling next in this workspace
TypeError: Cannot read properties of undefined (reading 'os')
    at fetchPkgInfo (/home/badtechies/node_modules/next/dist/lib/patch-incorrect-lockfile.js:72:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async patchIncorrectLockfile (/home/badtechies/node_modules/next/dist/lib/patch-incorrect-lockfile.js:161:26)
error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```
