### ISSUE TITLE
TypeError: bindings.createTurboTasks is not a function

### ISSUE THREAD

**Issue by okbeng03** [vercel/next.js#46346]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Tue May 22 03:28:18 UTC 2018
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation, Turbopack (--turbo)

### Link to the code that reproduces this issue

null

### To Reproduce

npm run build

### Describe the Bug

error output:
> Build error occurred
TypeError: bindings.createTurboTasks is not a function
    at Object.createTurboTasks (/node_modules/next/dist/build/swc/index.js:428:59)
    at runTurbotrace (/node_modules/next/dist/build/index.js:495:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /node_modules/next/dist/build/index.js:878:13
    at async Span.traceAsyncFn (/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/node_modules/next/dist/build/index.js:72:29)

### Expected Behavior

it is ok in my mac; but error in the linux service;(word in next 13.1.1)
By error, i think this is new feature turbopack error; can i close the feature?

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
