### ISSUE TITLE
[NEXT-733] global-error.tsx issues

### ISSUE THREAD

**Issue by jazzypants1989** [vercel/next.js#46572]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.3
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/jazzypants1989/nextjs-test

### To Reproduce

1.) Add a .env file with these variables:
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=*whatever*
MONGODB_URI=*whatever*

2.)  Run local dev server

3.) Create a user

4.) Go to admin page

5.) Go to other page

6.) Go back to admin page

### Describe the Bug

The entire server breaks and gives me this stack trace:

Uncaught TypeError: Cannot read properties of undefined (reading '')
    at resolveClientReferenceMetadata (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:189:70)
    at serializeClientReference (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1425:47)
    at resolveModelToJSON (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1856:28)
    at Object.toJSON (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1132:28)
    at stringify (<anonymous>)
    at processModelChunk (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:162:24)
    at retryTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1979:38)
    at performWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:2017:21)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1372:28)
    at scheduleWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:47:13)
    at pingTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1371:17)
    at ping (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1384:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
resolveErrorDev @ react-server-dom-webpack-client.browser.development.js?7de2:755
processFullRow @ react-server-dom-webpack-client.browser.development.js?7de2:800
processBinaryChunk @ react-server-dom-webpack-client.browser.development.js?7de2:835
progress @ react-server-dom-webpack-client.browser.development.js?7de2:893
react-server-dom-webpack-client.browser.development.js?7de2:755 Uncaught TypeError: Cannot read properties of undefined (reading '')
    at resolveClientReferenceMetadata (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:189:70)
    at serializeClientReference (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1425:47)
    at resolveModelToJSON (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1856:28)
    at Object.toJSON (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1132:28)
    at stringify (<anonymous>)
    at processModelChunk (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:162:24)
    at retryTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1979:38)
    at performWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:2017:21)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1372:28)
    at scheduleWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:47:13)
    at pingTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1371:17)
    at ping (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1384:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
resolveErrorDev @ react-server-dom-webpack-client.browser.development.js?7de2:755
processFullRow @ react-server-dom-webpack-client.browser.development.js?7de2:800
processBinaryChunk @ react-server-dom-webpack-client.browser.development.js?7de2:835
progress @ react-server-dom-webpack-client.browser.development.js?7de2:893
react-dom.development.js?5198:20605 The above error occurred in the <ServerRoot> component:

    at ServerRoot (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:126:11)
    at RSCComponent
    at Root (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:143:11)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js?5198:20605
update.callback @ react-dom.development.js?5198:20631
callCallback @ react-dom.development.js?5198:15106
commitCallbacks @ react-dom.development.js?5198:15153
commitLayoutEffectOnFiber @ react-dom.development.js?5198:26427
commitLayoutEffects @ react-dom.development.js?5198:27872
commitRootImpl @ react-dom.development.js?5198:30955
commitRoot @ react-dom.development.js?5198:30809
finishConcurrentRender @ react-dom.development.js?5198:29668
performConcurrentWorkOnRoot @ react-dom.development.js?5198:29549
workLoop @ index.js?10c5:10
flushWork @ index.js?10c5:10
performWorkUntilDeadline @ index.js?10c5:10
index.js?10c5:10 Uncaught TypeError: Cannot read properties of undefined (reading '')
    at resolveClientReferenceMetadata (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:189:70)
    at serializeClientReference (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1425:47)
    at resolveModelToJSON (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1856:28)
    at Object.toJSON (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1132:28)
    at stringify (<anonymous>)
    at processModelChunk (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:162:24)
    at retryTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1979:38)
    at performWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:2017:21)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1372:28)
    at scheduleWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:47:13)
    at pingTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1371:17)
    at ping (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1384:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
resolveErrorDev @ react-server-dom-webpack-client.browser.development.js?7de2:755
processFullRow @ react-server-dom-webpack-client.browser.development.js?7de2:800
processBinaryChunk @ react-server-dom-webpack-client.browser.development.js?7de2:835
progress @ react-server-dom-webpack-client.browser.development.js?7de2:893
admin:1 The resource http://localhost:3000/_next/static/chunks/polyfills.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### Expected Behavior

The entire server not breaking.

### Which browser are you using? (if relevant)

Brave v1.48.171, but I tested in Chrome and Firefox and got the same issue.

### How are you deploying your application? (if relevant)

I can't even get to deployment because I have ridiculous bugs every single day.

<sub>[NEXT-733](https://linear.app/vercel/issue/NEXT-733/global-errortsx-issues)</sub>

**Comment by jazzypants1989** [comment]
I'm fairly certain this is a caching error because it works perfectly on the first load every time, but telling NextJS to not cache the file doesn't make a difference.

**Comment by marysmech** [comment]
I have same problem after update from `13.1.6` to `13.2.3`. I tried to delete `global-error.tsx` and since then everything seems fine (at least so far).

**Comment by samuelcotterall** [comment]
I am also experiencing a similar issue in `13.2.3`, with the warning `The resource http://localhost:3000/_next/static/chunks/polyfills.js was preloaded using link preload but not used within a few seconds from the window's load event [...]` being shown in the browser’s console. 

The build seems to be unaffected, there are no warnings/errors in the Node console, and I do not have a `global-error.tsx` file. 

I’ll be looking into it further today.

**Comment by shuding** [comment]
Hey could you provide a simpler reproduction? I tried `git@github.com:jazzypants1989/nextjs-test.git` and got this locally:

```
error - ReferenceError: authOptions is not defined
    at getSession (./src/Auth/session.ts:9:83)
    at getCurrentUser (./src/Auth/session.ts:12:27)
    at AdminLayout (./src/app/admin/layout.tsx:22:85)
    at runMicrotasks (<anonymous>)
    at async Promise.all (index 0)
   5 |
   6 | export async function getSession() {
>  7 |   return await getServerSession(authOptions)
     |                                ^
   8 | }
   9 |
```

Which is an obvious mistake. After fixing it everything worked fine:

<img width="975" alt="CleanShot-2023-03-08-clGBfllX@2x" src="https://user-images.githubusercontent.com/3676859/223805697-3007f8df-c3a3-4e4a-b977-ea37ecd69301.png">

**Comment by jazzypants1989** [comment]
I apologize. I accidentally broke the demo. It's fixed now and the error is still there.

**Comment by coopernewby** [comment]
I got this issue too upgrading from 13.1.6 to 13.2.4. 
`error - SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>)`
I used the exact code in the beta docs.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/5702661/229958142-66851857-8017-4d48-905e-32ea899c66aa.png">

When I deleted global-error.tsx, the error resolved. not really sure how to add back global error but just leaving it out for now

**Comment by JohnnyCarreiro** [comment]
I'm facing a different error, i have may global error boundary configured and also a error route in app root dir according with Next Docs. When i throw a error on pages, they are handled by error boundary as expected, but when some error occurs on root layout, the expected behavior is to this error be handled by global error boundary, which is not happening

**Comment by muhammadali-pro** [comment]
i'm using next.js 13.4.4. i have setup my global-error.tsx file as mentioned in docs. i tried to simulate the global-error.tsx by throwing an error on root layout.tsx  but still my global-error.tsx is not catching the errors. is it an issue with next.js? or am i making some mistake. @JohnnyCarreiro  have you figured it out?

**Comment by priya-jain-dingg** [comment]
> i'm using next.js 13.4.4. i have setup my global-error.tsx file as mentioned in docs. i tried to simulate the global-error.tsx by throwing an error on root layout.tsx but still my global-error.tsx is not catching the errors. is it an issue with next.js? or am i making some mistake. @JohnnyCarreiro have you figured it out?

I am facing same issue. Did anyone find any solution

**Comment by KristineTrona** [comment]
I am on version 13.4.10 and throwing an error in root layout still does not show the `global-error.tsx`

**Comment by timneutkens** [comment]
Please open a new issue with a reproduction.
