### ISSUE TITLE
EACCESS when using create-next-app in current folder (existing git repository)

### ISSUE THREAD

**Issue by axelle-panopli** [vercel/next.js#46651]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
None of the above command worked, sorry
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

There's no code because I couldn't create the app

### To Reproduce

1. created a new git repository using GitHub Desktop
2. opened a terminal inside the repository's folder and ran `npx create-next-app . --typescript`
3. answered the prompts as follow:
✔ Would you like to use ESLint with this project? … No / Yes
✔ Would you like to use `src/` directory with this project? … No / Yes
✔ Would you like to use experimental `app/` directory with this project? … No / Yes
✔ What import alias would you like configured? …  "@/components/*": ["components/*"]

And that's when the installation aborted

### Describe the Bug

Installation aborted with the following error message
```
Aborting installation.
Unexpected error. Please report it as a bug:
 [Error: EACCES: permission denied, open '/Users/axelle/Documents/Dev/next-tests/.git/objects/74/b23aac600e7b44553819b5e1b1a5b6351865be'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/axelle/Documents/Dev/next-tests/.git/objects/74/b23aac600e7b44553819b5e1b1a5b6351865be'
}
```

### Expected Behavior

I expected the installation to proceed smoothly to the end

**Comment by habahabahaba** [comment]
I might have the same issue. In my case git repository wasn't set up. (MacBookAir M2, MacOS 13.3).

alexsmola@<User>-MacBook-Air next % pnpm create next-app .
Library/pnpm/store/v3/tmp/dlx-2706       |   +1 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/<username></username>/Library/pnpm/store/v3
  Virtual store is at:             Library/pnpm/store/v3/tmp/dlx-2706/node_modules/.pnpm
Library/pnpm/store/v3/tmp/dlx-2706       | Progress: resolved 1, reused 1, downloaded 0, added 1, done
✔ Would you like to use TypeScript with this project? … No / Yes
✔ Would you like to use ESLint with this project? … No / Yes
✔ Would you like to use Tailwind CSS with this project? … No / Yes
✔ Would you like to use `src/` directory with this project? … No / Yes
✔ Use App Router (recommended)? … No / Yes
✔ Would you like to customize the default import alias? … No / Yes
Creating a new Next.js app in /Users/<username>/udemy React - The Complete Guide /next.

Using pnpm.

Initializing project with template: app 


Installing dependencies:
- react
- react-dom
- next
- typescript
- @types/react
- @types/node
- @types/react-dom
- eslint
- eslint-config-next

Packages: +295
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/<username>/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 303, reused 295, downloaded 0, added 295, done

dependencies:
+ @types/node 20.2.3
+ @types/react 18.2.7
+ @types/react-dom 18.2.4
+ eslint 8.41.0
+ eslint-config-next 13.4.3
+ next 13.4.3
+ react 18.2.0
+ react-dom 18.2.0
+ typescript 5.0.4

Done in 14.3s
Initialized a git repository.

Success! Created next at /Users/<username>/udemy React - The Complete Guide /next


Aborting installation.
Unexpected error. Please report it as a bug:
 Error: EACCES: permission denied, open '/Users/<username>/Library/Preferences/create-next-app-nodejs/config.json.tmp-49723050200bf607'
    at openSync (node:fs:601:3)
    at attempt (/Users/<username>/Library/pnpm/store/v3/tmp/dlx-2706/node_modules/.pnpm/create-next-app@13.4.3/node_modules/create-next-app/dist/index.js:32:12168)
    at Object.writeFileSync (/Users/<username>/Library/pnpm/store/v3/tmp/dlx-2706/node_modules/.pnpm/create-next-app@13.4.3/node_modules/create-next-app/dist/index.js:32:7657)
    at Conf._write (/Users/<username>/Library/pnpm/store/v3/tmp/dlx-2706/node_modules/.pnpm/create-next-app@13.4.3/node_modules/create-next-app/dist/index.js:38:35206)
    at set store [as store] (/Users/<username>/Library/pnpm/store/v3/tmp/dlx-2706/node_modules/.pnpm/create-next-app@13.4.3/node_modules/create-next-app/dist/index.js:38:33652)
    at Conf.set (/Users/<username>/Library/pnpm/store/v3/tmp/dlx-2706/node_modules/.pnpm/create-next-app@13.4.3/node_modules/create-next-app/dist/index.js:38:32256)
    at run (/Users/<username>/Library/pnpm/store/v3/tmp/dlx-2706/node_modules/.pnpm/create-next-app@13.4.3/node_modules/create-next-app/dist/index.js:325:35701)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/<username>/Library/Preferences/create-next-app-nodejs/config.json.tmp-49723050200bf607'
}

<username>@Alexs-MacBook-Air next %

**Comment by muckee** [comment]
I'm not sure if it's supposed to be the case, but `create-next-app` only works when inside of a workspace.

You can use the following workaround to solve the issue.

```
mkdir temp-workspace
cd temp-workspace
yarn init -w
touch yarn.lock
yarn install
yarn dlx create-next-app packages/my-app
mv packages/my-app ../..
cd ../..
rm -rf temp-workspace
cd my-app
touch yarn.lock
yarn install
```

What this does:

- Create a folder which will be used to store a workspace temporarily.
- Initialise the workspace.
- Create a lock file for the workspace.
- Populate the lock file with `yarn install`.
- Create a new next app called 'my-app', inside the `package` directory which was created automatically when the workspace was initialised.
- Move the directory which contains the next app outside of the workspace.
- Delete the workspace.
- Create an empty lock file within the root directory of the next app.
- Populate the lock file with `yarn install`.

**Comment by qin-guan** [comment]
Can confirm that this issue is present when trying to run the command in a Git repository. Perhaps it is possible to reintroduce the `--no-git` option to skip any Git related steps? Temporary workaround would be to move the `.git` folder outside, create the project and then move it back in again.

```shell
mv .git ../_temp_git && \ 
pnpx create-next-app@latest ./ && \
rm -rf .git && \
mv ../_temp_git .git
```

**Comment by zhichucode** [comment]
```bash
sudo chown -R $(whoami) /Users/hoppe/Library/Preferences/create-next-app-nodejs
```

**Comment by luizlugo** [comment]
Thanks @zhichucode that command solves my issue

**Comment by habahabahaba** [comment]
> I'm not sure if it's supposed to be the case, but `create-next-app` only works when inside of a workspace.
> 
> You can use the following workaround to solve the issue.
> 
> ```
> mkdir temp-workspace
> cd temp-workspace
> yarn init -w
> touch yarn.lock
> yarn install
> yarn dlx create-next-app packages/my-app
> mv packages/my-app ../
> cd ..
> rm -rf temp-workspace
> cd my-app
> touch yarn.lock
> yarn install
> ```
> 
> What this does:
> 
> * Create a folder which will be used to store a workspace temporarily.
> * Initialise the workspace.
> * Create a lock file for the workspace.
> * Populate the lock file with `yarn install`.
> * Create a new next app called 'my-app', inside the `package` directory which was created automatically when the workspace was initialised.
> * Move the directory which contains the next app outside of the workspace.
> * Delete the workspace.
> * Create an empty lock file within the root directory of the next app.
> * Populate the lock file with `yarn install`.

Thank you oh so much, **muckee** !!!

**Comment by bgub** [comment]
Closing as stale/resolved
