### ISSUE TITLE
`dynamic = "error"` cause `fetch` with Authorization header to be considered as dynamic data method

### ISSUE THREAD

**Issue by aidenlx** [vercel/next.js#46694]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.12.1
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.18.2
Relevant packages:
  next: 13.2.4-canary.0
  eslint-config-next: 13.2.3
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/aidenlx/nextjs-app-fetch-header-ssg

### To Reproduce

1. Fork example repo
2. Run the command `pnpm i`
3. Run the command `next build`

### Describe the Bug

Setting `dynamic = "error"` in `page.js` can cause `fetch` requests with headers like `fetch("https://example.com/", { headers: { Authorization: 'Bearer 123' } })` to be considered as dynamic data method, throwing: 

    Page with dynamic = "error" encountered dynamic data method on ...

This seems to be affecting `@upstash/redis`, `@vercel/edge-config`, and other libs that use this header. 

```
> my-app@0.1.0 build /Users/aidenlx/repo/nextjs-app-fetch-header-ssg
> next build

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Compiled successfully
info  - Linting and checking validity of types ...Pages directory cannot be found at /Users/aidenlx/repo/nextjs-app-fetch-header-ssg/pages or /Users/aidenlx/repo/nextjs-app-fetch-header-ssg/src/pages. If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.
info  - Linting and checking validity of types  
info  - Collecting page data  
[    ] info  - Generating static pages (0/4)(node:40134) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[==  ] info  - Generating static pages (3/4)
Error occurred prerendering page "/this-broken". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Page with dynamic = "error" encountered dynamic data method on /this-broken.
    at /Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/export/worker.js:288:35
    at async Span.traceAsyncFn (/Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
info  - Generating static pages (4/4)

> Build error occurred
Error: Export encountered errors on following paths:
        /this-broken/page: /this-broken
    at /Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/export/index.js:425:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:1405:21
    at async Span.traceAsyncFn (/Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:1263:17
    at async Span.traceAsyncFn (/Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/Users/aidenlx/repo/nextjs-app-fetch-header-ssg/node_modules/.pnpm/next@13.2.4-canary.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:72:29)
info  - Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
```

### Expected Behavior

To be able to compile the application correctly.

### How are you deploying your application? (if relevant)

next start, Vercel

**Comment by aidenlx** [comment]
It seems that fetch with Authorization header is consider uncacheable since https://github.com/vercel/next.js/pull/46287, maybe worth mentioning in [chapter Caching](https://beta.nextjs.org/docs/data-fetching/caching) and [chapter Static and Dynamic Rendering](https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering#using-dynamic-data-fetches). Also, I'm wondering if it's possible to provide some escape hatches since libs like [@vercel/edge-config](https://github.com/vercel/edge-config/blob/730dc5d1171b79873ce16d5ea215ae27fb586157/src/index.edge.ts#L34) need Authorization headers to work.

**Comment by ReinhardtR** [comment]
I have the same issue using `@planetscale/database-js`.

https://github.com/planetscale/database-js/blob/main/src/index.ts#L267

**Comment by pttsky** [comment]
> I'm wondering if it's possible to provide some escape hatches since libs like [@vercel/edge-config](https://github.com/vercel/edge-config/blob/730dc5d1171b79873ce16d5ea215ae27fb586157/src/index.edge.ts#L34) need constant Authorization headers to work

+1

Not always precense Authorization header means that the data to be fetched is different for every user of an app. For example, Woocommerce REST API requires Authentication header even to get common public things like lists of products (luckily, there is an alternative method of authentication via GET parameters).
