### ISSUE TITLE
new build doesn't work

### ISSUE THREAD

**Issue by EnenDaveyBoy** [vercel/next.js#47025]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

npx create-next-app@latest --experimental-app

### To Reproduce

I had a project I was working on and all of a sudden i kept getting an error saying invalid hook, so I commented everything in the project and still got the error, so I decided to create a new app without modifying it and I still get the error I am stumped

npx create-next-app@latest --experimental-app

### Describe the Bug

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\enend\source\repos\Siranna\src\UIs\src\nextjs\siranna-web-app\node_modules\next\dist\compiled\react\cjs\react.development.js:1753:21)
    at Html (webpack-internal:///../../../../../../../../AppData/Roaming/npm/node_modules/next/dist/pages/_document.js:678:104)
    at renderWithHooks (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7756:16)
    at renderIndeterminateComponent (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7830:15)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8065:7) 
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at finishClassComponent (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7786:3)
    at renderClassComponent (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7794:3)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8062:7) 
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at renderContextProvider (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8029:3)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8143:11)
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at renderContextProvider (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8029:3)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8143:11)
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at retryTask (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8674:5)     
    at performWork (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8741:7)   
    at C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9118:12
    at scheduleWork (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:78:3)    
    at startWork (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9117:3)     
    at C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9221:5
    at new Promise (<anonymous>)
    at Object.renderToReadableStream (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9170:10)
    at renderToString (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\render.js:59:55)
    at Object.renderToHTML (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\render.js:862:32)
    at async doRender (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:837:28)
    at async C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\response-cache\index.js:83:36
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (C:\Users\enend\source\repos\Siranna\src\UIs\src\nextjs\siranna-web-app\node_modules\next\dist\compiled\react\cjs\react.development.js:1753:21)
    at Html (webpack-internal:///../../../../../../../../AppData/Roaming/npm/node_modules/next/dist/pages/_document.js:678:104)
    at renderWithHooks (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7756:16)
    at renderIndeterminateComponent (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7830:15)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8065:7) 
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at finishClassComponent (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7786:3)
    at renderClassComponent (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:7794:3)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8062:7) 
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at renderContextProvider (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8029:3)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8143:11)
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at renderContextProvider (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8029:3)
    at renderElement (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8143:11)
    at renderNodeDestructiveImpl (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8232:11)
    at renderNodeDestructive (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8204:14)
    at retryTask (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8674:5)     
    at performWork (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:8741:7)   
    at C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9118:12
    at scheduleWork (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:78:3)    
    at startWork (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9117:3)     
    at C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9221:5
    at new Promise (<anonymous>)
    at Object.renderToReadableStream (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.browser.development.js:9170:10)
    at renderToString (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\render.js:59:55)
    at Object.renderToHTML (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\render.js:862:32)
    at async doRender (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\base-server.js:837:28)
    at async C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\server\response-cache\index.js:83:36
error - ..\AppData\Roaming\npm\node_modules\next\font\google\index.js (1:6) @ eval
error - Error: You tried to import `next/font/google`, did you mean `@next/font/google`?
Read more: https://nextjs.org/docs/basic-features/font-optimization
    at eval (webpack-internal:///(sc_server)/../../../../../../../../AppData/Roaming/npm/node_modules/next/font/google/index.js:1:7)
    at (sc_server)/../../../../../../../../AppData/Roaming/npm/node_modules/next/font/google/index.js (C:\Users\enend\source\repos\Siranna\src\UIs\src\nextjs\siranna-web-app\.next\server\app\page.js:655:1)
    at __webpack_require__ (C:\Users\enend\source\repos\Siranna\src\UIs\src\nextjs\siranna-web-app\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./src/app/page.js:8:74)
    at (sc_server)/./src/app/page.js (C:\Users\enend\source\repos\Siranna\src\UIs\src\nextjs\siranna-web-app\.next\server\app\page.js:688:1)      
    at Function.__webpack_require__ (C:\Users\enend\source\repos\Siranna\src\UIs\src\nextjs\siranna-web-app\.next\server\webpack-runtime.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (C:\Users\enend\AppData\Roaming\npm\node_modules\next\dist\build\utils.js:714:17) {
  type: 'Error',
  page: '/'
}
null

### Expected Behavior

to run without issue

### Which browser are you using? (if relevant)

firefox

### How are you deploying your application? (if relevant)

next dev

**Comment by EnenDaveyBoy** [comment]
I have removed next and re installed it and it seems to have fixed it.
