### ISSUE TITLE
[NEXT-843] React minified error 130 during build if third party packages are used in client components imported to page.tsx

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#47232]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.5-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/joulev/debug/tree/nextjs-react-minified-error-130-on-build

### To Reproduce

* Clone the linked repo
* `next build`

### Describe the Bug

The following error shows up:

> Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= ...

<details>
<summary>Full log</summary>

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Be (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:389)
    at Be (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:355)
    at Z (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:91)
    at Ce (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:98)
    at Ee (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:424)
    at Z (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:222)
    at Ce (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:98)
    at Ee (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:424)
    at Z (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:222)
    at Be (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:93)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Be (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:389)
    at Be (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:355)
    at Z (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:91)
    at Ce (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:98)
    at Ee (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:424)
    at Z (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:222)
    at Ce (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:98)
    at Ee (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:424)
    at Z (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:222)
    at Be (/Users/joulev/dev/www/debug/node_modules/.pnpm/next@13.2.5-canary.5_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:93)
```

</details>

The app works fine in dev mode, or in prod mode in v13.2.4.

**Note:** My claim in the title "error during build if third party packages are used in client components imported to `page.tsx`" is not guaranteed to be correct. But at least I can guarantee that using `react-intersection-observer` in the same way as in the reproduction will throw this error during build.

### Expected Behavior

It should be able to build normally.

<sub>[NEXT-843](https://linear.app/vercel/issue/NEXT-843/react-minified-error-130-during-build-if-third-party-packages-are-used)</sub>

**Comment by balazsorban44** [comment]
It seems like the issue is that the package has a class component that is not supported in server components:

https://github.com/thebuilder/react-intersection-observer/blob/main/src/InView.tsx#L65

Although [you marked](https://github.com/joulev/debug/blob/f29dc1540a9e5515b245b1604874d15bccba797b/app/content.tsx#L1) the component with `"use client"` which for some reason we don't seem to detect correctly in this case. :thinking:

Adding `"use client"` to the page itself or `next dev` works, so will have to have a closer look.

**Comment by joulev** [comment]
This has been fixed some time between this issue was reported and now. `next build` can work normally now.
