### ISSUE TITLE
[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies

### ISSUE THREAD

**Issue by DanielWahl** [vercel/next.js#47394]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Debian 5.10.162-1 (2023-01-21)
    Binaries:
      Node: 16.19.1
      npm: 9.6.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.12
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

fresh/new create-next-app

### To Reproduce

Simply creating a new Next.js project and running yarn build logs the following warning in the console:
```
npx create-next-app@latest
cd app-name
npm run build  // or yarn build
```
result:
![Bildschirmfoto 2023-03-22 um 13 41 14](https://user-images.githubusercontent.com/9644563/226907719-4ded5dfa-3d4a-437f-92bf-a7e241426a30.png)

### Describe the Bug

It's probably linked to the issue [27650](https://github.com/vercel/next.js/issues/27650) and [35877](https://github.com/vercel/next.js/discussions/35877), but it was not resolved, nor did any of this information help me fix this bug.
On a freshly set-upped Debian server with the specs above, Next.js build throws the following error&warning-message (but not an error that cancels the build):

```
npm run build

> takeoff-frontend@0.1.0 build
> next build

info  - Loaded env from /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/.env.local
info  - Skipping linting
info  - Checking validity of types
info  - Creating an optimized production build ...    [webpack.cache.PackFileCacheStrategy] No pack exists at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/.next/cache/webpack/server-production.pack: Error: ENOENT: no such file or directory, stat '/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/.next/cache/webpack/server-production/index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 30.694241 ms
info  - Creating an optimized production build ..    [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: Compilation/modules|/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js??ruleSet[1].rules[1].oneOf[2].use!/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/pages/_app.tsx
    [webpack.cache.PackFileCacheStrategy] Storing pack...
    [webpack.cache.PackFileCacheStrategy] Capturing build dependencies... (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/next.config.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/ignore-loader/index.js)
<t> [webpack.cache.PackFileCacheStrategy] resolve build dependencies: 44.93478 ms
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of /usr/www/users: Error: EACCES: permission denied, open '/usr/www/users'
<t> [webpack.cache.PackFileCacheStrategy] snapshot build dependencies: 0.941732 ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
    [webpack.cache.PackFileCacheStrategy] Error: Unable to snapshot resolve dependencies
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:553124
        at jobError (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:276218)
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:277146
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:289658
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:1302194
        at Hook.eval [as callAsync] (eval at create (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:6:1)
        at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:13:25925)
        at AsyncQueue._handleResult (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:1301742)
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:1301593
        at ReadFileContext.<anonymous> (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:289057)
    [webpack.cache.PackFileCacheStrategy] No pack exists at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/.next/cache/webpack/edge-server-production.pack: Error: ENOENT: no such file or directory, stat '/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/.next/cache/webpack/edge-server-production/index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 14.656235 ms
    [webpack.cache.PackFileCacheStrategy] No pack exists at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/.next/cache/webpack/client-production.pack: Error: ENOENT: no such file or directory, stat '/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/.next/cache/webpack/client-production/index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 6.988857 ms
info  - Creating an optimized production build .    [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: Compilation/modules|/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?absolutePagePath=private-next-pages%2F_app.tsx&page=%2F_app!
    [webpack.cache.PackFileCacheStrategy] Storing pack...
    [webpack.cache.PackFileCacheStrategy] Capturing build dependencies... (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/next.config.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/sass-loader/cjs.js, /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/mini-css-extract-plugin/loader.js)
<t> [webpack.cache.PackFileCacheStrategy] resolve build dependencies: 78.69155 ms
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of /usr/www/users: Error: EACCES: permission denied, open '/usr/www/users'
<t> [webpack.cache.PackFileCacheStrategy] snapshot build dependencies: 0.703472 ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
    [webpack.cache.PackFileCacheStrategy] Error: Unable to snapshot resolve dependencies
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:553124
        at jobError (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:276218)
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:277146
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:289658
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:1302194
        at Hook.eval [as callAsync] (eval at create (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:6:1)
        at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:13:25925)
        at AsyncQueue._handleResult (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:1301742)
        at /usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:1301593
        at ReadFileContext.<anonymous> (/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules/next/dist/compiled/webpack/bundle5.js:28:289057)
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (12/12)
info  - Finalizing page optimization

Route (pages)                              Size     First Load JS
┌ ○ / (484 ms)                             2.18 kB         110 kB
├   /_app                                  0 B              74 kB
├ ○ /404 (540 ms)                          1.77 kB         109 kB
├ ○ /500 (494 ms)                          1.77 kB         109 kB
└ λ /api/hello                             0 B              74 kB
+ First Load JS shared by all              88.6 kB
  ├ chunks/framework-cda2f1305c3d9424.js   45.2 kB
  ├ chunks/main-75b811eb5316bd1a.js        27.7 kB
  ├ chunks/pages/_app-fc698ddf2bb24351.js  297 B
  ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
  └ css/e90b5e437a2ca258.css               14.6 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

info  - Creating an optimized production build ..
```

In the result above, there's also an error `Error: EACCES: permission denied, open '/usr/www/users'`.
The linux user is not a superuser, so has no access to this folder, but this should not prevent the build from being successful.

After this build and exposing the webpage to a port (I can also send a link to test), the homepage "/" shows an 404 error, but the styling, some components like navigation, ... (on a non-fresh build) shows.

This is the content of 
![Bildschirmfoto 2023-03-22 um 13 52 00](https://user-images.githubusercontent.com/9644563/226910115-0398fe9f-de53-426e-8cb1-e9573bbc12ff.png)
the .next/cache folder:

### Expected Behavior

The build should be finished without any warning/error.

### How are you deploying your application? (if relevant)

Startet an pm2 process with a proxypass pointing to the port.

**Comment by DanielWahl** [comment]
Not quite sure if that's the root of the problem, but webpack is trying to access the base root folder of the server:
```
Set(8) {
  '/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend/node_modules',
  '/usr/www/users/takeoff/takeoffshow.blocknote.dev/takeoff-frontend',
  '/usr/www/users/takeoff/takeoffshow.blocknote.dev',
  '/usr/www/users/takeoff',
  '/usr/www/users',
  '/usr/www',
  '/usr',
  '/'
}
```

The file causing this: `lib/FileSystemInfo.js:2055 --> processCapturedFiles`

**Comment by richleach** [comment]
any luck with this bug? I'm getting the same error on my Mac environment (MacOS Big Sur 11.7.4 Node v 16.17.0 npm v 9.6.2)

**Comment by DanielWahl** [comment]
Still didn't find a solution to the problem.
I'm currently not using TailwindCSS, the problem occurs even after a completely fresh Next.js install on the server.

**Comment by richleach** [comment]
Yeah, I'm now getting the problem with completely fresh Next.js installs too.
I made sure my Node and NPM were up to date (per the Next.js docs), trying to work this problem....

**Comment by richleach** [comment]
... but oddly my site is loading locally just fine, not even any errors in the browser console, just that webpack error in my server console

**Comment by karlo-humanmanaged** [comment]
I have the same error:
```
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

- info Linting and checking validity of types...
- info Creating an optimized production build...
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (659kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
- warn Compiled with warnings

../../../node_modules/.pnpm/next@13.4.2_3j7hb26pwgm6spbxoejtjx6xja/node_modules/next/dist/server/web/spec-extension/image-response.js
A Node.js API is used (process.turbopack at line: 14) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

Import trace for requested module:
../../../node_modules/.pnpm/next@13.4.2_3j7hb26pwgm6spbxoejtjx6xja/node_modules/next/dist/server/web/spec-extension/image-response.js
../../../node_modules/.pnpm/next@13.4.2_3j7hb26pwgm6spbxoejtjx6xja/node_modules/next/server.js
../../../node_modules/.pnpm/next-auth@4.22.1_cmp7sjki5xcmfyvhcokzzink7a/node_modules/next-auth/next/middleware.js
../../../node_modules/.pnpm/next-auth@4.22.1_cmp7sjki5xcmfyvhcokzzink7a/node_modules/next-auth/middleware.js
```

**Comment by mkmrcodes** [comment]
same error with version 13.4
- warn You have enabled experimental feature (swcPlugins) in next.config.js.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
- info Creating an optimized production build ..<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (659kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
- warn Compiled with warnings

**Comment by JuniorAlbuquerque** [comment]
in my case, I fixed it like this:

- remove node_modules, lockfile and .next folder
-  install dependencies again and run app

**Comment by WesleyRafaelp** [comment]
did anyone manage to solve it? I have the same problem

**Comment by prodkt** [comment]
@WesleyRafaelp same issue persists here as well, Wes.

**Comment by ucefkh** [comment]
what is this weird problem? C'mon Vercel and next team

**Comment by ucefkh** [comment]
Resting everything solves it, at least for now

**Comment by kimhwanhoon** [comment]
Same

```
unhandledRejection: [Error: ENOENT: no such file or directory, stat '/Users/.../.next/cache/webpack/server-development/0.pack.gz'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/.../.next/cache/webpack/server-development/0.pack.gz'
}
```

**Comment by PeterCastilloG** [comment]
same error

**Comment by Maxdoggydog** [comment]
I have the same problem but I can't load anything. One day(two days ago) it came after I tried to build it and since I can do anything one the website.
But it is due to the 'scss' extension , if I am using 'css' files it is working fine, but with this other one, nop.

**Comment by Maxdoggydog** [comment]
> in my case, I fixed it like this:
> 
> * remove node_modules, lockfile and .next folder
> * install dependencies again and run app

It worked for me, thanks. I was removing the "node_modules" but not "package-lock.json".

**Comment by fernandezAmor** [comment]
> in my case, I fixed it like this:
> 
> * remove node_modules, lockfile and .next folder
> * install dependencies again and run app

This worked for me too, no need to remove lockfile but node_modules and .next folder.
Thanks!!

**Comment by Maxdoggydog** [comment]
> > in my case, I fixed it like this:
> > 
> > * remove node_modules, lockfile and .next folder
> > * install dependencies again and run app
> 
> This worked for me too, no need to remove lockfile but node_modules and .next folder. Thanks!!

I have removed the ".next" and "node_modules" but I was still getting this error, but I when I removed "lockfile", it worked.

**Comment by IDNK2203** [comment]
> in my case, I fixed it like this:
> 
> * remove node_modules, lockfile and .next folder
> * install dependencies again and run app

Worked for me

**Comment by juliocarneiro** [comment]
> in my case, I fixed it like this:
> 
> * remove node_modules, lockfile and .next folder
> * install dependencies again and run app

work for me too

**Comment by wjbetech** [comment]
Not working for me. Have done all efforts advised here.

**Comment by webbahadurproject** [comment]
Still not working for me as well with next 14.0.4

**Comment by developerwill** [comment]
I'm expericing the same [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies, does anyone have a fix? Removing node_modules, lockfile and .next folder and re-installing dependencies didn't work for me.

**Comment by keisokoo** [comment]
Same warning. [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item ...

In my case, it occurs in css-loader, postcss-loader and vanilla-extract-webpack-plugin.
even i'm using swc...

**Comment by josemsb92** [comment]
I also have deleted node-modules, .next/ folder and lock file and re-installed them and still having the warn:
[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies

**Comment by demirtasdurmus** [comment]
`[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies`

Same for me as well, tried everything advised here including `rm -rf .next & rm -rf node_modules & rm -rf package-lock.json` and `npm i` again.

**Comment by ikhsanytc** [comment]
i got the same error, and i move the dir project to C:/ and its run normally :)

**Comment by tomato-ga** [comment]
I am using tailwind css.

The same problem appears randomly after deleting /node_modules / .next / package-lock.json and restarting the server.

When this error occurs, the CSS is disabled.

**Comment by JakeCasey** [comment]
I was having this issue, alongside an issue with next yelling about EOF errors. Cleaning out .next, node_modules, and package-lock.json, and then upgrading from node v20.9.0 to v21.7.3 fixed it for me.

**Comment by MostafaKMilly** [comment]
Still having this issue

**Comment by mio-19** [comment]
I had this issue after upgrading node from 22 to node.js23

**Comment by h-behgam** [comment]
I had this issue after upgrading node to ver 23 . After downgrade, solved it.

**Comment by nattaphongklinjan** [comment]
Får feilmeldinger i terminalen ved oppgradering av node23. 
https://github.com/vercel/next.js/issues/47394

**Comment by longfellowone** [comment]
Also getting this in v23, downgrading to 22 fixes it

**Comment by j-fdion** [comment]
> Also getting this in v23, downgrading to 22 fixes it

Worked for me, thank you! @h-behgam & @longfellowone

**Comment by yonisetiawan** [comment]
> in my case, I fixed it like this:
> 
> * remove node_modules, lockfile and .next folder
> * install dependencies again and run app

its work, firts you can try remote node_modules and .next folder

**Comment by mio-19** [comment]
I tried removing node_modules and .next. still:

```

  ▲ Next.js 15.0.1

   Creating an optimized production build ...
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
```

**Comment by flawnn** [comment]
> Also getting this in v23, downgrading to 22 fixes it

Interesting - probably not supported yet?

**Comment by suprunchuk** [comment]
### Here's how to fix the caching error for package dependencies in your project:

1.  First, clear your npm cache:

```bash
npm cache clean --force
```

2. Delete `node_modules` and `package-lock.json`:
```bash
rm -rf node_modules package-lock.json
```

3. Install dependencies fresh:
```bash
npm install
```

**If the issue persists, try using a specific npm version:**
```bash
npm install -g npm@latest
```

**Then rebuild the project:**
```bash
npm run build
```

These steps will resolve the dependency caching issues by doing a clean reinstall of all packages listed in your `package.json`.

**Comment by oidualc** [comment]
Same for me, using NextJS 14.2.16 and upgrading from Node v22.x.x to v23.0.0 (or even v23.1.0) results in this warning and a broken build. It's probably best to open a specific issue about Node 23 support.

**Comment by Mindgames** [comment]
> Also getting this in v23, downgrading to 22 fixes it

👉 **This solved it for me**  - MacOS  

This is a odd issue and the warnings + possible fixes found when searching are a bit misleading

**Comment by Pnlvfx** [comment]
same for me in nodejs 23 and latest next canary

**Comment by Melvynx** [comment]
Yes, the only way is to downgrade to NodeJS 21 or 22 to fix the problems when using NextJS 15

**Comment by harisiqbal12** [comment]
downgrading to v22 works for me.

**Comment by klaygomes** [comment]
Same issue here.

Doesn't work on version v23
```bash
node --version
v23.1.0
```

After I downgraded to:
```
node --version 
v22.11.0
```

Worked fine.


-- specs
MacOs: Version 15.1.1 (24B91)
webpack": "^5.96.1"
 next: "^14.2.17",
Typescript:

**Comment by 3miliator** [comment]
Upgrading node did the trick

**Comment by randomtoni** [comment]
I checked in my Activity Monitor and saw many next-server processes where running.
After finishing them all, I runned yarn dev again and issue was gone


Example snapshot:

<img width="961" alt="Image" src="https://github.com/user-attachments/assets/4c18e9fb-a239-4669-9fd9-2d7fc6253b20" />

**Comment by marcoshernanz** [comment]
Thanks for the report. I reproduced the original `EACCES` case on 13.2.5-canary.12 when an ancestor directory is traversable but not readable. This was fixed by #73697 in 15.1.0. The same setup builds cleanly on 15.5.25, 16.3.4, and the current canary, including with `next build --webpack`, and the cache packs are written normally.

The reported 404 is separate because the affected build completed, emitted `/`, and served it successfully in the reproduction. Later comments contain several different causes for the same webpack warning. If this still occurs on a supported release, please open a new issue with a focused reproduction and verbose `FileSystemInfo` output. Closing as fixed.
