### ISSUE TITLE
[NEXT-892] Re-export of client components needs to be marked as use client as well

### ISSUE THREAD

**Issue by danbalarin** [vercel/next.js#47450]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.14
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-tlwzjp?file=src/layout.jsx

### To Reproduce

1. Create pages/layouts in separate folder (not `app/`)
2. Mark those as client components (`'use client'`)
3. Reexport those in `app/` directory without marking that file as client component

### Describe the Bug

The build process fails while trying to generate pages with following error:
```
Error occurred prerendering page "<page>". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Cannot access .then on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
    at Object.get (<project-folder>/.next/server/chunks/256.js:31807:15)
    at async createComponentTree (<project-folder>/node_modules/next/dist/server/app-render/index.js:501:29)
    at async <project-folder>/node_modules/next/dist/server/app-render/index.js:419:56
    at async Promise.all (index 0)
    at async createComponentTree (<project-folder>/node_modules/next/dist/server/app-render/index.js:383:38)
    at async <project-folder>/node_modules/next/dist/server/app-render/index.js:419:56
    at async Promise.all (index 0)
    at async createComponentTree (<project-folder>/node_modules/next/dist/server/app-render/index.js:383:38)
    at async <project-folder>/node_modules/next/dist/server/app-render/index.js:419:56
    at async Promise.all (index 0)
```

### Expected Behavior

The build doesn't fail without the need of marking those components manually. This was the behaviour on `next@13.1.6`

<sub>[NEXT-892](https://linear.app/vercel/issue/NEXT-892/re-export-of-client-components-needs-to-be-marked-as-use-client-as)</sub>

**Comment by marcoshernanz** [comment]
Thanks for the report. This was fixed by #65519 and backported in Next.js 14.2.8. I confirmed the original repro now builds and prerenders correctly on the latest stable and canary releases with both Webpack and Turbopack, without adding `use client` to the re-export files. Closing as fixed.
