### ISSUE TITLE
`NEXT_RSC_ERR_CLIENT_METADATA_EXPORT` when using metadata

### ISSUE THREAD

**Issue by QuiiBz** [vercel/next.js#47703]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.30.5
    Relevant packages:
      next: 13.2.5-canary.21
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/lagonapp/lagon/pull/724

### To Reproduce

- `git clone git@github.com:lagonapp/lagon.git`
- `cd lagon`
- `git checkout refactor/www-app-router`
- `pnpm install`
- `pnpm dev`
- Access this page: http://localhost:3000/blog

### Describe the Bug

I've come across a strange bug when migrating to the app router. When accessing a specific page (`/blog`) that exports a metadata, a `NEXT_RSC_ERR_CLIENT_METADATA_EXPORT` error is thrown:

```bash
Error: 
  x NEXT_RSC_ERR_CLIENT_METADATA_EXPORT: metadata
    ,-[/Users/tom/dev/lagon/www/app/blog/page.tsx:37:1]
 37 |   );
 38 | }
 39 | 
 40 | export const metadata = {
    :              ^^^^^^^^
 41 |   title: 'Blog - Lagon',
 42 | };
    `----

Import trace for requested module:
./app/blog/page.tsx
./app/blog/ lazy ^\.\/.*$ namespace object
./lib/blog.ts
./app/blog/page.tsx
```

The following error is also logged before the one above:

```bash
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.getModuleTrace (/Users/tom/dev/lagon/node_modules/.pnpm/next@13.2.5-canary.21_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/getModuleTrace.js:58:48)
    at Object.getRscError (/Users/tom/dev/lagon/node_modules/.pnpm/next@13.2.5-canary.21_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseRSC.js:81:64)
    at Object.getModuleBuildError (/Users/tom/dev/lagon/node_modules/.pnpm/next@13.2.5-canary.21_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:117:32)
    at async /Users/tom/dev/lagon/node_modules/.pnpm/next@13.2.5-canary.21_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:15:49
    at async Promise.all (index 0)
    at async /Users/tom/dev/lagon/node_modules/.pnpm/next@13.2.5-canary.21_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:13:21
```

I've tried to remove the `export const metadata = ...` part and the page works fine. By commenting parts of the code, I found that this specific line causes the bug, which is strange because it doesn't relates to the error (replace it by `const articles = []` to make the bug disappear): 

https://github.com/lagonapp/lagon/pull/724/files#diff-ca8498319a72381b1ff2b0e2fc3bf64e09a18cadb31b4291d77433eaf9fa5742R8

### Expected Behavior

No error should be thrown

**Comment by balazsorban44** [comment]
Hi, I cannot reproduce this given your steps. Could you please create a **minimal** reproduction that only focuses on the issue? :pray:

There are many - likely unrelated - other errors and warnings which would make it hard to track down the actual reported issue. The code also seems to use `13.2.4`, and we ask you to test `next@canary` before reporting a bug. Thanks!

**Comment by QuiiBz** [comment]
I pushed a commit that fixes the bug a few minutes ago, so that's "normal" that you can't reproduce. I'll provide another minimal reproduction after work! (I've also tried with `next@canary` before creating this issue, that's why I ticked the box)

**Comment by QuiiBz** [comment]
Closing this issue as I'm not able to reproduce it right now. I'll dig more into it this weekend.
