### ISSUE TITLE
Error while creating next-app with Typescript using Yarn

### ISSUE THREAD

**Issue by Deveesh-Shetty** [vercel/next.js#47789]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
Platform: linux
Arch: x64
Version: #1 ZEN SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:40 +0000
Binaries:
Node: 18.14.2
npm: 9.5.0
Yarn: 1.22.19
pnpm: N/A
Relevant packages:
next: 13.1.5
eslint-config-next: N/A
react: 18.2.0
react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/Deveesh-Shetty/CineSurge

### To Reproduce

I am creating a next-app with typescript using yarn
`yarn create next-app --typescript .`

The creation is done successfully, but I am getting an error while doing `next build`

### Describe the Bug

```
info  - Linting and checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data .Error: You tried to import `next/font/google`, did you mean `@next/font/google`?
Read more: https://nextjs.org/docs/basic-features/font-optimization
at 68 (/home/deveesh/DriveD/Projects/cinesurge/.next/server/chunks/47.js:533:7)
at __webpack_require__ (/home/deveesh/DriveD/Projects/cinesurge/.next/server/webpack-runtime.js:25:42)
at 681 (/home/deveesh/DriveD/Projects/cinesurge/.next/server/pages/index.js:42:74)
at __webpack_require__ (/home/deveesh/DriveD/Projects/cinesurge/.next/server/webpack-runtime.js:25:42)
at __webpack_exec__ (/home/deveesh/DriveD/Projects/cinesurge/.next/server/pages/index.js:321:39)
at /home/deveesh/DriveD/Projects/cinesurge/.next/server/pages/index.js:322:69
at __webpack_require__.X (/home/deveesh/DriveD/Projects/cinesurge/.next/server/webpack-runtime.js:108:21)
at /home/deveesh/DriveD/Projects/cinesurge/.next/server/pages/index.js:322:47
at Object.<anonymous> (/home/deveesh/DriveD/Projects/cinesurge/.next/server/pages/index.js:325:3)
at Module._compile (node:internal/modules/cjs/loader:1254:14)

> Build error occurred
Error: Failed to collect page data for /
at /usr/lib/node_modules/next/dist/build/utils.js:963:15
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
type: 'Error'
}
```

### Expected Behavior

I ran the same command in my previous project some weeks ago, but at that time I didn't get any errors. But now I am getting this error,  I tried redoing the same 2-3 times and every time getting the same issue.

**Comment by samparmenter** [comment]
Isn't it only next 13.2 that has the build in `next/font` and prior to that you need to use `@next/font`. You are using 13.1.5.

**Comment by Deveesh-Shetty** [comment]
I don't know how it installed the previous version...any idea how i can upgrade the version

**Comment by samparmenter** [comment]
The current version of NextJS is 13.2.4 unless you are running canary so the command  `yarn create next-app --typescript .` shouldn't be installing 13.1.5.

If I pull down the latest 13.2.4 I can use `next/font/google` just fine.

If I pull down 13.1.5 I can't use `next/font/google` and it shows me the same error as you are getting. You have to manually run `yarn add @next/font@13.1.5` and then use the import as `import { MyFont } from @next/font/google`

**Comment by Deveesh-Shetty** [comment]
Yeah! Thanks...but I am still wondering how it installed nextJS 13.1.5 version... and also my previous project is also in next 13.1.5 but it didn't give this issue....
