### ISSUE TITLE
[next/jest] Executing jest with Storybook preview crashes on version 13.2.3 onwards

### ISSUE THREAD

**Issue by vallovic** [vercel/next.js#47866]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.28
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/vallovic/next-jest-issue

### To Reproduce

Clone repository, execute `npm run test` and you'll see it crash with the following error. You may change `next` version in `package.json` to `13.2.3` to check that [in that version it's working without any issues]([working-13.2.3.png](https://github.com/vallovic/next-jest-issue/blob/main/working-13.2.3.png)).

```
# npm run test

> test
> jest

 FAIL  components/span.test.tsx
  ● Test suite failed to run

    Cannot find module '.storybook/preview' from 'jest.setup.js'

    However, Jest was able to find:
        '.storybook/preview.ts'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'mjs', 'cjs', 'jsx', 'ts', 'tsx', 'json', 'node'].

    See https://jestjs.io/docs/configuration#modulefileextensions-arraystring

      4 | setProjectAnnotations(globalStorybookConfig);
      5 |

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (jest.setup.js:6:56)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.865 s
```

### Describe the Bug

I'm using Storybook to write stories and leverage its use to also run unit tests. I have `baseUrl`/`paths` in my `tsconfig.json` thus I'm also using the `moduleNameMapper` in `jest.config.js` to keep it all working and in sync - as you may check it in the referenced repository. [Up until `next` version 13.2.3]([working-13.2.3.png](https://github.com/vallovic/next-jest-issue/blob/main/working-13.2.3.png)), everything was working fine.

After updating to version `13.2.4` (and also most recent `13.2.5-canary.28`), the bug above started appearing so it won't allow me to test. 

This bug may be related with the changes introduce in #45815. Following those introduced changes, if I happen to remove `moduleNameMapper` from `jest.config.js` in this new version, it **also doesn't** work.

Referenced repository includes 3 screenshots of all the results with the different versions.

### Expected Behavior

Running `npm run test` should not crash with an error like this since it was working flawlessly on version before.

**Comment by DanProudfoot** [comment]
I'm getting the same issue in similar circumstances - with Next 13.2.4, when using `next/jest` it seems that basically any library that I use in jest.setup.js can't be loaded. For example when doing `import { setupServer } from 'msw/node';` I get the error `Cannot find module '../../msw'` - Obviously msw isn't a local path, it's a node module.

**Comment by mizozobu** [comment]
Temporary workaround is to rename `.storybook` to `storybook`. You'll have to start your storybook with [`-c .storybook` flag](https://storybook.js.org/docs/react/api/cli-options#dev).

I think there is an issue importing a file whose path includes a directory that starts with `.`.

```ts
import test from './.a/b';
// Error: Cannot find module 'xxx/.a/b' from 'yyy'
```

**Comment by sshah98** [comment]
Running into the same issue as [DanProudfoot](https://github.com/DanProudfoot) --     Cannot find module './@testing-library/jest-dom' from '__tests__/pages/api/**'

**Comment by sshah98** [comment]
> Running into the same issue as [DanProudfoot](https://github.com/DanProudfoot) -- Cannot find module './@testing-library/jest-dom' from '**tests**/pages/api/**'

I fixed this in my local code btw -- https://github.com/vercel/next.js/issues/40183#issuecomment-1500614550, basically my tsconfig and jest.config weren't matching up with the module mappers. I removed it all and it worked
