### ISSUE TITLE
Image not scaling down in verison 13.3.1-canary.0

### ISSUE THREAD

**Issue by mycallCampbell** [vercel/next.js#48063]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/mycallCampbell/infowaveFrontend/

### To Reproduce

open inspect and view in mobile version. The Image does not scale down. 

### Describe the Bug

I have previously built a website (www.robdiamond.co.uk) using NEXT JS version 12.1.0 and the 'Hero' image scales down when viewed in mobile device. I set the image using the 'next Image component' with a width and height value. In this example, the hero imaged used is 3360px by 2240px (quite large) and scales down correctly on any mobile device keeping all of the image in view.

I have now started a new project using the latest versioin of Next JS with Canary updated and the 'Hero' image is not scaling down as the expected behavior seen in my previous project (see domain above). Instead, when viewed on mobile, the image does not scale down. 

I have set the 'Hero' image using the same principles as in the above example. 

### Expected Behavior

I wish for the 'Hero' image to scale down and keep the same aspect ratio when viewed on mobile device. 

### Which browser are you using? (if relevant)

Chrome Version 111.0.5563.147 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Vercel

**Comment by timruiterkamp** [comment]
I am not sure if I have the exact same issue but there seems to be something wrong with the image optimizer. After upgrading to Next 13.3 all my images where broken on a production build. And this were the logs:

```Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/squoosh/main.js
- /app/node_modules/next/dist/server/image-optimizer.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/squoosh/main.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/squoosh/main.js',
    '/app/node_modules/next/dist/server/image-optimizer.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/server.js'
  ]
}
```

After changing my next.config.js to 
```const nextConfig = { 
  output: "standalone", 
  images: {unoptimized: true}
}
``` 
it showed the image again. But I have lost all the optimization and therefore also the downsizing of the images on different screens.

It is not really a solution since this looks like a bug. If you have found a solution please let me know!

**Comment by mycallCampbell** [comment]
Have not found a solution as of yet, although creating my projects using the older version (12) of Next.js to avoid the Image optimisation bug. Hope this helps
