### ISSUE TITLE
HookWebpackError: Class constructor URL cannot be invoked without 'new'

### ISSUE THREAD

**Issue by xabitrigo** [vercel/next.js#48296]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #202303130630~1679424972~22.04~4a8cde1 SMP PREEMPT_DYNAMIC Tue M
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

unavailable

### To Reproduce

This is an upgrade of an existing and big app. Creating a minimal reproduction might prove difficult. I will try though.

The only step I need to work is:

```
yarn && yarn run build:prod
```

`build:prod` is an alias for `cross-env NODE_ENV=production next build`

### Describe the Bug

We are trying to upgrade a legacy app (started as next v8, currently at next v10) to nextjs v13. The app is a fairly large ecommerce site, with lots of legacy libraries and it's using redux and a custom server. 

We did the upgrade quite easily using dev mode, but when we tried to produce a build, the following error appeared:

```
Failed to compile.

    HookWebpackError: Class constructor URL cannot be invoked without 'new'
at makeWebpackError (/home/xabi/projects/ecommerce/node_modules/next/dist/compiled/webpack/bundle5.js:28:308185)
at /home/xabi/projects/ecommerce/node_modules/next/dist/compiled/webpack/bundle5.js:28:105236
at eval (eval at create (/home/xabi/projects/ecommerce/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:27:1)
    at /home/xabi/projects/ecommerce/node_modules/next/dist/compiled/webpack/bundle5.js:28:68649
    at /home/xabi/projects/ecommerce/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:414:143
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    -- inner error --
    TypeError: Class constructor URL cannot be invoked without 'new'
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    caused by plugins in Compilation.hooks.processAssets
    TypeError: Class constructor URL cannot be invoked without 'new'
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

We don't have a class URL in our code. 

We pinpointed the last version of nextjs that works as `12.0.2-canary-9`. `12.0.2-canary-10` gives this exact problem all the way up to 13.3.1-canary-5. The main change between these two versions is an upgrade of webpack from 5.60.0 to 5.61.0

We tried a bunch of different stuff:
- Removed all custom `next.config.js` configuration
- Removed .babelrc so SWC could take over
- Upgraded some of the libraries
- Removed some of the libraries

The only thing we could do to get rid of that concrete error was to downgrade nextjs.

### Expected Behavior

I should be able to compile my application.

**Comment by xabitrigo** [comment]
This seems that it was a problem with the transpilation process. 

We had a property in an object called URL that somehow later in the code the compiler interpreted as an attempt to call the system class URL. 

```js
  const {
    component: {
      // ...
      imageDesktop: {
        cmsComponent: { component: { URL = '' } = {} } = {},
      } = {},
    },
    isMobile,
  } = props;

  // later
  const image = !isMobile ? URL: "";
```

Renaming the variable in the destructuring fixed the problem.

```js
  const {
    component: {
      imageDesktop: {
        cmsComponent: { component: { URL: urlDesktop = "" } = {} } = {},
      } = {},
    },
    isMobile,
    // ...
  } = props;

  // later
  const image = !isMobile ? urlDesktop : "";
```
