### ISSUE TITLE
Typescript 5 decorators do not build

### ISSUE THREAD

**Issue by austinlogo** [vercel/next.js#48360]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue

https://github.com/austinlogo/nextjs-typescript-5

### To Reproduce

Install and build as normal you should see an error in building types. 

When you use the experimental flags in the tsconfig.json

### Describe the Bug

This build Error

```
./src/pages/api/hello.ts
Error:
  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
    ╭─[/Users/logo/workspaces/scratch/ts5/test-types/src/pages/api/hello.ts:23:1]
 23 │ }
 24 │
 25 │ class Test {
 26 │   @loggedMethod
    ·   ─
 27 │   myMethod() {
 28 │     return "hello";
 29 │   }
    ╰────
```

### Expected Behavior

I would expect it to build.

**Comment by nandorojo** [comment]
Same with `function f<const T>() {}` generics not working.

**Comment by Frikki** [comment]
@nandorojo Please open a different issue after verifying that nobody hasn’t already reported the issue.

**Comment by nandorojo** [comment]
Fair suggestion, however, I think it’s under the same umbrella issue: TS 5 features not being supported. My guess is all syntax gets supported together by upgrading the TS version Next (or SWC) uses.

**Comment by pokatomnik** [comment]
This is SWC-only issue. Fortunately, NextJS allows to switch back to the original TSC instead of SWC. I tried It, and It IS working right now.
My advice: use TSC. This is the only fully-functional TS compiler right now.

**Comment by pokatomnik** [comment]
> Oh, good to know. What did you do exactly?

1. Install `ts-loader`
2. Configure your next.config.js like this:
```
module.exports = {
  webpack: (config) => {
    config.module.rules.push({
      test: /\.tsx?$/,
      use: [
        {
          loader: "ts-loader",
          options: { transpileOnly: true },
        },
      ],
    });

    return config;
  },
};
```
3. try to run `npm start dev`

You may notice there will be some errors in the console (`ts-loader` cannot handle some imports located in the newly created app). Remove them or try to solve those error by yourself.

**Comment by ksaldana1** [comment]
Ran into this today—is there any plan to support these in the near future?

**Comment by runjuu** [comment]
Another way to quickly fix this issue, without waiting for NextJS to update, is to use [patch-package](https://github.com/ds300/patch-package) or [pnpm patch](https://pnpm.io/cli/patch) to directly enable SWC's [stage 3 decorator support](https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion).

An example of how to use `pnpm patch` to enable this can be found at https://github.com/orch-js/orch-js/commit/47b28ee29fad3ebf688fd56cfe5c96aaac3e1c28. Just simply mark `decorators` as `true` and specify the `decoratorVersion` to `2022-03`.

**Comment by yanickrochon** [comment]
I have a library using TypeScript 5, nothing special with the `tsconfig.json`. This library is built, imported in the Next application, and it fails.

If the above solution works, it should be added to Next's configuration; opt-in to enable TS decorators.

**Comment by Traveller23** [comment]
> Another way to quickly fix this issue, without waiting for NextJS to update, is to use [patch-package](https://github.com/ds300/patch-package) or [pnpm patch](https://pnpm.io/cli/patch) to directly enable SWC's [stage 3 decorator support](https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion).
> 
> An example of how to use `pnpm patch` to enable this can be found at [orch-js/orch-js@47b28ee](https://github.com/orch-js/orch-js/commit/47b28ee29fad3ebf688fd56cfe5c96aaac3e1c28). Just simply mark `decorators` as `true` and specify the `decoratorVersion` to `2022-03`.

Under nextjs version 14.1.0, compiling with the patch gives an error:

```
   Collecting page data ...
ReferenceError: Cannot access 'A' before initialization
    at 97607 (C:\data\javascript\oasis\oasis-tools\.next\server\chunks\217.js:1:34166)
    at Function.t (C:\data\javascript\oasis\oasis-tools\.next\server\webpack-runtime.js:1:142)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (C:\data\javascript\oasis\oasis-tools\node_modules\next\dist\build\utils.js:919:21)
    at async C:\data\javascript\oasis\oasis-tools\node_modules\next\dist\build\utils.js:1138:17
    at async Span.traceAsyncFn (C:\data\javascript\oasis\oasis-tools\node_modules\next\dist\trace\trace.js:151:20)

> Build error occurred
Error: Failed to collect page data for /_not-found
    at C:\data\javascript\oasis\oasis-tools\node_modules\next\dist\build\utils.js:1258:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

**Comment by Traveller23** [comment]
Next.js is now at version 14.1.0, and this issue has not yet been officially resolved (though thanks to @runjuu for the solution).

**Comment by qd-qd** [comment]
Next.js is now at version 14.2.3, and this issue has not yet been officially resolved.
Give us the ability to use decorators.

**Comment by dartess** [comment]
Hello @kdy1, I see you self-assigned this almost half a year ago. Please share, is there any news or ETA?

**Comment by sawich** [comment]
Status? 👀

**Comment by kdy1** [comment]
https://github.com/vercel/next.js/pull/65963

**Comment by tomas-c** [comment]
@kdy1 I see https://github.com/vercel/next.js/pull/65963 was closed until the support is implemented in SWC... Is SWC now ready for this?

**Comment by hjellek** [comment]
Support for Stage 3 decorators seems to have landed on SWC now: https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion

**Comment by iSuslov** [comment]
It's still broken and non configurable while type checking via `tsc` works flawlessly  

> Support for Stage 3 decorators seems to have landed on SWC now: https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion

@kdy1 we have `turbopack` and `swc` not working correctly. Turbopack doing really strange things:

```
export function ClassDecorator<T extends abstract new (...args: any) => any>() {
    return function (target:T,context: ClassDecoratorContext<T>) {
        console.log('ClassDecorator target', target)
        console.log('ClassDecorator context', context)
    };
}
``` 

**ClassDecorator target:**
<img width="612" alt="Image" src="https://github.com/user-attachments/assets/50f75357-c288-4a7a-a1c2-b19630f3222e" />

**ClassDecorator context:** undefined

**Comment by kdy1** [comment]
Stage 3 decorator is not landed in SWC isde

**Comment by IntusFacultas** [comment]
> Another way to quickly fix this issue, without waiting for NextJS to update, is to use [patch-package](https://github.com/ds300/patch-package) or [pnpm patch](https://pnpm.io/cli/patch) to directly enable SWC's [stage 3 decorator support](https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion).
> 
> An example of how to use `pnpm patch` to enable this can be found at [orch-js/orch-js@47b28ee](https://github.com/orch-js/orch-js/commit/47b28ee29fad3ebf688fd56cfe5c96aaac3e1c28). Just simply mark `decorators` as `true` and specify the `decoratorVersion` to `2022-03`.


@runjuu Just wanted to hop in real quick  and and say thank you for this, this worked a treat and saved my bacon.

**Comment by programming-with-ia** [comment]
+1

**Comment by HerrNiklasRaab** [comment]
@kdy1 I don't understand, this isn't the offical docs?

> Support for Stage 3 decorators seems to have landed on SWC now: https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion

**Comment by HerrNiklasRaab** [comment]
Given that support has landed in SWC, there is a ready to merge PR and high demand for a solution. Isn't this a low hanging fruit?

**Comment by HerrNiklasRaab** [comment]
Hi @ijjk — pinging you since @kdy1 (the assignee) appears to no longer be at Vercel and hasn't responded since May.

SWC has shipped stage-3 decorator support ([`jsc.transform.decoratorVersion`](https://swc.rs/docs/configuration/compilation#jsctransformdecoratorversion)), and there's a [ready PR (#65963)](https://github.com/vercel/next.js/pull/65963) that was closed waiting on exactly that. With both pieces in place this looks like a low-hanging fruit — would you be able to reassign and take another look? Happy to help test. Thanks!
