### ISSUE TITLE
next/font refactor seems to brake builds when deployed

### ISSUE THREAD

**Issue by elrumordelaluz** [vercel/next.js#48377]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.6
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (next/font)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/bold-kalam-ztju0q?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A12%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A12%2C%22startLineNumber%22%3A14%7D%5D

### To Reproduce

1. Import a font from `next/font/google` like:
```js
import { Jost } from 'next/font/google'
```

2. Use it in some of the [documented ways](https://nextjs.org/docs/basic-features/font-optimization#google-fonts)
3. Deploy the code to Vercel

### Describe the Bug

Seems that the [last refactor](https://github.com/vercel/next.js/pull/46731/files#diff-1a962444b9309d7fdb380f39786872f78c7b7456bad5b34dee72db0282356b63) of next/font/google published in [v13.2.4](https://github.com/vercel/next.js/releases/tag/v13.2.4) broke the builds [when deploying to Vercel](https://github.com/vercel/next.js/discussions/48371). 

This doesn't happen when downgrading to `v13.2.3`.

### Expected Behavior

Not to broke build in production.

### How are you deploying your application? (if relevant)

Vercel

**Comment by karaoak** [comment]
+1

**Comment by msahajwani** [comment]
+1

**Comment by kelvinsekx** [comment]
+1

**Comment by mendoanjoe** [comment]
i got same 
`import { DM_Sans } from 'next/font/google';`
```bash
 > [builder 5/5] RUN npm run build:
#17 0.344 myapp@0.1.0 build /app
#17 0.344 > next build
#17 0.344 
#17 0.917 Webpack version 5.74.0
#17 0.964 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#17 0.964 This information is used to shape Next.js' roadmap and prioritize features.
#17 0.964 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#17 0.964 https://nextjs.org/telemetry
#17 0.964 
#17 1.061 info  - Linting and checking validity of types...
#17 2.343 info  - Creating an optimized production build...
#17 3.106 ReferenceError: AbortController is not defined
#17 3.106     at fetchCSSFromGoogleFonts (/app/node_modules/next/dist/compiled/@next/font/dist/google/fetch-css-from-google-fonts.js:34:28)
#17 3.106     at nextFontGoogleFontLoader (/app/node_modules/next/dist/compiled/@next/font/dist/google/loader.js:76:79)
#17 3.106     at /app/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:72:99
#17 3.106     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
#17 4.783 Failed to compile.
#17 4.783 
#17 4.783 src/pages/_app.js
#17 4.783 `next/font` error:
#17 4.783 Failed to fetch `DM Sans` from Google Fonts.
#17 4.783 
#17 4.784 
#17 4.784 > Build failed because of webpack errors
#17 4.938 npm ERR! code ELIFECYCLE
#17 4.939 npm ERR! errno 1
#17 4.946 npm ERR! myapp@0.1.0 build: `next build`
#17 4.946 npm ERR! Exit status 1
#17 4.946 npm ERR! 
#17 4.946 npm ERR! Failed at the myapp@0.1.0 build script.
#17 4.946 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#17 5.006 
#17 5.006 npm ERR! A complete log of this run can be found in:
#17 5.006 npm ERR!     /root/.npm/_logs/2023-04-27T17_59_13_958Z-debug.log
------
executor failed running [/bin/sh -c npm run build]: exit code: 1
```

**Comment by kelvinsekx** [comment]
> > i got same `import { DM_Sans } from 'next/font/google';`
> > ```shell
> >  > [builder 5/5] RUN npm run build:
> > #17 0.344 myapp@0.1.0 build /app
> > #17 0.344 > next build
> > #17 0.344 
> > #17 0.917 Webpack version 5.74.0
> > #17 0.964 Attention: Next.js now collects completely anonymous telemetry regarding usage.
> > #17 0.964 This information is used to shape Next.js' roadmap and prioritize features.
> > #17 0.964 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> > #17 0.964 https://nextjs.org/telemetry
> > #17 0.964 
> > #17 1.061 info  - Linting and checking validity of types...
> > #17 2.343 info  - Creating an optimized production build...
> > #17 3.106 ReferenceError: AbortController is not defined
> > #17 3.106     at fetchCSSFromGoogleFonts (/app/node_modules/next/dist/compiled/@next/font/dist/google/fetch-css-from-google-fonts.js:34:28)
> > #17 3.106     at nextFontGoogleFontLoader (/app/node_modules/next/dist/compiled/@next/font/dist/google/loader.js:76:79)
> > #17 3.106     at /app/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:72:99
> > #17 3.106     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:79:20)
> > #17 4.783 Failed to compile.
> > #17 4.783 
> > #17 4.783 src/pages/_app.js
> > #17 4.783 `next/font` error:
> > #17 4.783 Failed to fetch `DM Sans` from Google Fonts.
> > #17 4.783 
> > #17 4.784 
> > #17 4.784 > Build failed because of webpack errors
> > #17 4.938 npm ERR! code ELIFECYCLE
> > #17 4.939 npm ERR! errno 1
> > #17 4.946 npm ERR! myapp@0.1.0 build: `next build`
> > #17 4.946 npm ERR! Exit status 1
> > #17 4.946 npm ERR! 
> > #17 4.946 npm ERR! Failed at the myapp@0.1.0 build script.
> > #17 4.946 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > #17 5.006 
> > #17 5.006 npm ERR! A complete log of this run can be found in:
> > #17 5.006 npm ERR!     /root/.npm/_logs/2023-04-27T17_59_13_958Z-debug.log
> > ------
> > executor failed running [/bin/sh -c npm run build]: exit code: 1
> > ```
> 
> i change from node:14-alpine to node:18-alpine that will works🔥

The question is when you upgrade locally, can you do the same on vercel?
Because even after upgrading the node version it fails on vercel build.
