### ISSUE TITLE
Can't pass `JSX` via `getStaticProps`

### ISSUE THREAD

**Issue by bayraak** [vercel/next.js#48462]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
❯ npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.8
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### To Reproduce

1. Create a `page` under `pages/` directory.
2. Add a prop to the new Page component called `{children: ReactNode}`
3. Pass JSX via `getStaticProps()`

You can reproduce here: https://stackblitz.com/edit/nextjs-tbjoct?file=pages/index.js

### Describe the Bug

I have the following React Next.JS code:

```tsx
import type { NextPage } from "next";
import SinglePage from "../components/single-page/SinglePage";
import { ReactNode } from "react";
import DigitalTransformationContent from "../content/al/digitalTransformationContent";

interface Props {
  children: ReactNode;
}

const DigitalTransformation: NextPage<Props> = ({ children }) => {
  return <SinglePage page="digital-transformation">{children}</SinglePage>;
};

export async function getStaticProps() {
  return {
    props: {
      children: <DigitalTransformationContent />,
    },
  };
}
export default DigitalTransformation;
```

When I'm trying to pass a JSX as a static prop, I'm getting the following issue:

```
dex.js:598 Uncaught Error: Error serializing `.children.$$typeof` returned from `getStaticProps` in "/digital-transformation".
Reason: `symbol` cannot be serialized as JSON. Please only return JSON serializable data types.
    at isSerializable (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/lib/is-serializable-props.js:61:15)
    at <unknown> (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/lib/is-serializable-props.js:43:66)
    at Array.every (<anonymous>)
    at isSerializable (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/lib/is-serializable-props.js:40:39)
    at <unknown> (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/lib/is-serializable-props.js:43:66)
    at Array.every (<anonymous>)
    at isSerializable (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/lib/is-serializable-props.js:40:39)
    at Object.isSerializableProps (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/lib/is-serializable-props.js:63:12)
    at Object.renderToHTML (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/server/render.js:474:99)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/server/base-server.js:936:34)
    at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/server/base-server.js:1059:28)
    at async (file:///Users/bayramali/Projects/Private/digital-era-next/node_modules/next/dist/server/response-cache/index.js:83:36)
g
```

Apparently, Next.JS is not supporting React component `serialization/deserialization`

### Expected Behavior

I would expect that passing a JSX would work like normal since idiomatically it is pretty normal to use that syntax in React or `JSX/TSX` world.

- It should not be a big deal to also support JSX serialization/deserialization. 
- It is not working as `<AnyJSX />` or `AnyJSX`.

### How are you deploying your application? (if relevant)

Vercel

**Comment by shuding** [comment]
This is expected, you can only return serializable values (because you need to pass that value across server/client during client navigations). A React element isn't serializable (because `DigitalTransformationContent` is a function).
