### ISSUE TITLE
standalone + appDir breaks _app with getInitialProps

### ISSUE THREAD

**Issue by klarstrup** [vercel/next.js#48918]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.3.5-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps), Standalone mode (output: "standalone")

### Link to the code that reproduces this issue

https://github.com/klarstrup/next.js-repro-repo/tree/standalone-appdir-_app-getInitialProps

### To Reproduce

- Enable `appDir`
- Set output mode to `standalone`
- Create `pages/_app.js`
- Add minimal `_app` such as
```jsx
import App from "next/app";

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />;
}

MyApp.getInitialProps = (appContext) => App.getInitialProps(appContext);

export default MyApp;
```

- Install deps, build and run standalone server:

```sh
npm i
npm run build
node .next/standalone/server.js
```

- Request any URL from said server(`http://localhost:3000/whatevs`)

### Describe the Bug

The exports of `react` seem to be unavailable in the environment that `_app` runs in with `getInitialProps` present, causing errors for any access to React methods. Above repro gives us a stacktrace like so:

```
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (~/code/my-app/.next/standalone/node_modules/next/dist/compiled/react/cjs/react.production.min.js:28:118)
    at Head (~/code/my-app/.next/standalone/.next/server/pages/_error.js:282:44)
    at renderWithHooks (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (~/code/my-app/.next/standalone/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
```

### Expected Behavior

I would expert a `pages/_app` file with `getInitialProps` to behave as documented, like it does without `appDir: true`.

**Comment by khuezy** [comment]
There's definitely something strange w/ `13.3.2-canary`. My standalone app throws this error now:
```
errorMessage | Error: Cannot find module 'react/jsx-runtime'
Require stack:
- /var/task/node_modules/next/dist/server/require-hook.js
- /var/task/node_modules/next/dist/server/next-server.js
```

**Comment by klarstrup** [comment]
Still broken as of 13.3.5-canary.5
