### ISSUE TITLE
Build error in Route Handlers

### ISSUE THREAD

**Issue by ZZZCNY** [vercel/next.js#48979]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```powershell
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.15.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.3.1
Relevant packages:
  next: 13.3.2-canary.13
  eslint-config-next: 13.3.1
  react: 18.2.0
  react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/wizardly-forest-04hqq3?file=%2FREADME.md

### To Reproduce

1. write a `Route Handler` 
2. build or commit to GitHub to run the CI

### Describe the Bug

The `Route Handler` may be recognized as a page in the build phase. 
path: `app\api\user\captcha\route.ts`. 
```ts
import { HTTP_METHODS } from 'next/dist/server/web/http';

export async function GET(request: Request) {
  return await fetch('http://localhost:8080/user/captcha', {
    method: HTTP_METHODS[0],
  });
}

```
This is normal during dev, but the flag (?) when building may be different from other api's and the same as page:
```powershell
pnpm build

> xxx@0.1.0 build C:\Users\xxx\Documents\GitHub\xxx
> next build

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Creating an optimized production build
info  - Compiled successfully
info  - Linting and checking validity of types
info  - Collecting page data
info  - Generating static pages (13/13)
info  - Finalizing page optimization

Route (app)                                Size     First Load JS
┌ ○ /                                      3.44 kB         110 kB
├ λ /api/todo                              0 B                0 B
├ λ /api/todo/[id]                         0 B                0 B
├ λ /api/todo/efficiency                   0 B                0 B
├ λ /api/user                              0 B                0 B
├ λ /api/user/[id]                         0 B                0 B
├ ○ /api/user/captcha                      0 B                0 B
├ λ /api/user/email/[email]                0 B                0 B
├ λ /api/user/login                        0 B                0 B
├ ○ /todo/dashboard                        2.38 kB        99.9 kB
├ ○ /todo/dashboard                        2.38 kB        99.9 kB
├ ○ /todo/list                             6.29 kB         171 kB
├ ○ /todo/list                             6.29 kB         171 kB
├ ○ /todo/settings                         2.06 kB        94.6 kB
├ ○ /todo/settings                         2.06 kB        94.6 kB
├ ○ /todo/settings                         2.06 kB        94.6 kB
├ ○ /user/login                            2 kB            112 kB
└ ○ /user/sign-up                          3.89 kB         114 kB
+ First Load JS shared by all              92.5 kB
  ├ chunks/162-6a4d20dfec7f2176.js         16.5 kB
  ├ chunks/403-a2261e80ff7ca8a7.js         23.6 kB
  ├ chunks/8a8d382d-7f3e983644ae106e.js    50.5 kB
  ├ chunks/main-app-6ead25a71c46abd7.js    219 B
  └ chunks/webpack-0922537f9bf9a4b7.js     1.76 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   180 B          86.2 kB
+ First Load JS shared by all              86 kB
  ├ chunks/main-1e1105c21a08ba5c.js        84.1 kB
  ├ chunks/pages/_app-549aee5ab37675f5.js  195 B
  └ chunks/webpack-0922537f9bf9a4b7.js     1.76 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```
Similarly, Github CI will report the error:
```bash
Run pnpm build

> xxx@0.1.0 build /home/runner/work/xxx/xxx
> next build

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Creating an optimized production build...
info  - Compiled successfully
info  - Linting and checking validity of types...
info  - Collecting page data...
info  - Generating static pages (0/13)
info  - Generating static pages (3/13)

Error occurred prerendering page "/api/user/captcha". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
info  - Generating static pages ([6](https://github.com/ZZZCNY/xxx/actions/runs/4837810791/jobs/8621878674#step:6:7)/13)
info  - Generating static pages ([9](https://github.com/ZZZCNY/xxx/actions/runs/4837810791/jobs/8621878674#step:6:10)/[13](https://github.com/ZZZCNY/xxx/actions/runs/4837810791/jobs/8621878674#step:6:14))
info  - Generating static pages (13/13)

> Export encountered errors on following paths:
	/api/user/captcha/route: /api/user/captcha
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```
The same problem is present in Vercel deployments:
```bash
[17:31:56.061] Running build in Washington, D.C., USA (East) – iad1
[17:31:56.119] Cloning github.com/ZZZCNY/xxx (Branch: main, Commit: 04cd835)
[17:31:56.521] Cloning completed: 401.536ms
[17:32:01.246] Restored build cache
[17:32:01.275] Running "vercel build"
[17:32:01.723] Vercel CLI 29.0.0
[17:32:02.039] Warning: Detected "engines": { "node": ">=18.15.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[17:32:02.063] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[17:32:02.077] Installing dependencies...
[17:32:02.702] Lockfile is up to date, resolution step is skipped
[17:32:02.791] Progress: resolved 1, reused 0, downloaded 0, added 0
[17:32:02.912] Packages: +105 -26
[17:32:02.912] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------
[17:32:03.802] Progress: resolved 105, reused 0, downloaded 31, added 26
[17:32:04.801] Progress: resolved 105, reused 0, downloaded 70, added 66
[17:32:05.803] Progress: resolved 105, reused 0, downloaded 101, added 101
[17:32:06.803] Progress: resolved 105, reused 0, downloaded 102, added 102
[17:32:08.149] Progress: resolved 105, reused 0, downloaded 103, added 102
[17:32:09.149] Progress: resolved 105, reused 0, downloaded 103, added 103
[17:32:10.150] Progress: resolved 105, reused 0, downloaded 105, added 103
[17:32:11.905] Progress: resolved 105, reused 0, downloaded 105, added 104
[17:32:12.560] 
[17:32:12.561] dependencies:
[17:32:12.561] - @emotion/react 11.10.6
[17:32:12.561] + @emotion/react 11.10.8
[17:32:12.561] - next 13.3.1
[17:32:12.561] + next 13.3.2-canary.13
[17:32:12.561] 
[17:32:12.562] Done in 10.4s
[17:32:12.906] Progress: resolved 105, reused 0, downloaded 105, added 105, done
[17:32:12.943] Detected Next.js version: 13.3.2-canary.13
[17:32:12.955] Running "pnpm run build"
[17:32:13.473] 
[17:32:13.473] > xxx@0.1.0 build /vercel/path0
[17:32:13.473] > next build
[17:32:13.473] 
[17:32:13.914] warn  - You have enabled experimental feature (appDir) in next.config.js.
[17:32:13.914] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[17:32:13.915] 
[17:32:13.915] info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
[17:32:14.051] info  - Creating an optimized production build...
[17:32:42.624] info  - Compiled successfully
[17:32:42.633] info  - Linting and checking validity of types...
[17:32:47.982] info  - Collecting page data...
[17:33:01.701] info  - Generating static pages (0/13)
[17:33:01.747] info  - Generating static pages (3/13)
[17:33:01.776] 
[17:33:01.777] Error occurred prerendering page "/api/user/captcha". Read more: https://nextjs.org/docs/messages/prerender-error
[17:33:01.777] TypeError: fetch failed
[17:33:01.777]     at Object.fetch (node:internal/deps/undici/undici:11413:11)
[17:33:01.777]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[17:33:01.818] info  - Generating static pages (6/13)
[17:33:02.230] info  - Generating static pages (9/13)
[17:33:02.427] info  - Generating static pages (13/13)
[17:33:02.428] 
[17:33:02.429] > Export encountered errors on following paths:
[17:33:02.429] 	/api/user/captcha/route: /api/user/captcha
[17:33:02.477]  ELIFECYCLE  Command failed with exit code 1.
[17:33:02.505] Error: Command "pnpm run build" exited with 1
[17:33:03.178] Deployment completed
[17:33:02.766] BUILD_UTILS_SPAWN_1: Command "pnpm run build" exited with 1
```

### Expected Behavior

Normal build, no error reported.

### How are you deploying your application? (if relevant)

Vercel

**Comment by masterkain** [comment]
I see this too, production builds fails, has this been solved? next 13.4.1, the content inside the function will try to get generated

I have other endpoint that doesn't seem to exhibit this behavior.

```
import { prisma } from '@/lib/db';
import { NextRequest, NextResponse } from 'next/server';

// GET /api/hc
// health check
export async function GET(request: NextRequest) {
  // just do something to check if the db is working
  await prisma.projects.findFirst();

  return new NextResponse('OK');
}
```

```
#17 43.70 Error occurred prerendering page "/api/hc". Read more: https://nextjs.org/docs/messages/prerender-error
#17 43.70 Error: 
#17 43.70 Invalid `prisma.projects.findFirst()` invocation:
#17 43.70 
#17 43.70 
#17 43.70 error: Environment variable not found: DATABASE_URL.
#17 43.70   -->  schema.prisma:8
#17 43.70    | 
#17 43.70  7 |   provider   = "postgresql"
#17 43.70  8 |   url        = env("DATABASE_URL")
#17 43.70    | 
#17 43.70 
#17 43.70 Validation Error Count: 1
#17 43.70     at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6750)
#17 43.70     at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)
#17 43.70     at /app/node_modules/@prisma/client/runtime/library.js:179:3087
#17 43.70     at async /app/node_modules/@prisma/client/runtime/library.js:179:3294
#17 43.70     at async t._executeRequest (/app/node_modules/@prisma/client/runtime/library.js:179:10755)
#17 43.70     at async t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)
#17 43.70     at async GET (/app/.next/server/app/api/hc/route.js:83:5)
#17 43.70     at async /app/.next/server/chunks/616.js:2903:37
#17 43.70 - info Generating static pages (1/6)
#17 43.72 - info Generating static pages (2/6)
#17 43.87 - info Generating static pages (4/6)
#17 43.94 - info Generating static pages (6/6)
#17 43.94 
#17 43.94 > Export encountered errors on following paths:
#17 43.94 	/api/hc/route: /api/hc
```

**Comment by ZZZCNY** [comment]
This is because Next.js thinks that every run is the same result, I solved my problem by adding options `cache: 'no-store'`, maybe you should find a similar way to solve this problem.

**Comment by ZZZCNY** [comment]
> I see this too, production builds fails, has this been solved? next 13.4.1, the content inside the function will try to run.
> 
> I have other endpoint that doesn't seem to exhibit this behavior.
> 
> ```ts
> import { prisma } from '@/lib/db';
> import { NextRequest, NextResponse } from 'next/server';
> 
> // GET /api/hc
> // health check
> export async function GET(request: NextRequest) {
>   // just do something to check if the db is working
>   await prisma.projects.findFirst();
> 
>   return new NextResponse('OK');
> }
> ```
> 
> ```
> #17 43.70 Error occurred prerendering page "/api/hc". Read more: https://nextjs.org/docs/messages/prerender-error
> #17 43.70 Error: 
> #17 43.70 Invalid `prisma.projects.findFirst()` invocation:
> #17 43.70 
> #17 43.70 
> #17 43.70 error: Environment variable not found: DATABASE_URL.
> #17 43.70   -->  schema.prisma:8
> #17 43.70    | 
> #17 43.70  7 |   provider   = "postgresql"
> #17 43.70  8 |   url        = env("DATABASE_URL")
> #17 43.70    | 
> #17 43.70 
> #17 43.70 Validation Error Count: 1
> #17 43.70     at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6750)
> #17 43.70     at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)
> #17 43.70     at /app/node_modules/@prisma/client/runtime/library.js:179:3087
> #17 43.70     at async /app/node_modules/@prisma/client/runtime/library.js:179:3294
> #17 43.70     at async t._executeRequest (/app/node_modules/@prisma/client/runtime/library.js:179:10755)
> #17 43.70     at async t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)
> #17 43.70     at async GET (/app/.next/server/app/api/hc/route.js:83:5)
> #17 43.70     at async /app/.next/server/chunks/616.js:2903:37
> #17 43.70 - info Generating static pages (1/6)
> #17 43.72 - info Generating static pages (2/6)
> #17 43.87 - info Generating static pages (4/6)
> #17 43.94 - info Generating static pages (6/6)
> #17 43.94 
> #17 43.94 > Export encountered errors on following paths:
> #17 43.94 	/api/hc/route: /api/hc
> ```

Is this the reason for: `error: Environment variable not found: DATABASE_URL.`

**Comment by ozgur-shape** [comment]
@ZZZCNY , I think Next.js tries to fetch data in the building process. That doesn't make sense at all. I have the same issue. It is trying to fetch real data from my API. We should reopen this issue.

**Comment by masterkain** [comment]
https://github.com/vercel/next.js/issues/49441

**Comment by ZZZCNY** [comment]
> @ZZZCNY , I think Next.js tries to fetch data in the building process. That doesn't make sense at all. I have the same issue. It is trying to fetch real data from my API. We should reopen this issue.

This is actually correct, considering the possibility of SSG and completing the rendering earlier during the build.

**Comment by ozgur-shape** [comment]
> > @ZZZCNY , I think Next.js tries to fetch data in the building process. That doesn't make sense at all. I have the same issue. It is trying to fetch real data from my API. We should reopen this issue.
> 
> This is actually correct, considering the possibility of SSG and completing the rendering earlier during the build.

I've solved my issue by using this doc: [Route Segment Config](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config). Basically, devs can decide which page should be static or dynamic.
