### ISSUE TITLE
Errno: -4094 when running create-next-app@latest

### ISSUE THREAD

**Issue by j-machuca** [vercel/next.js#49043]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Local\npm-cache\_logs\2023-05-01T14_45_32_387Z-debug-0.log
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

npx create-next-app@latest rts

### To Reproduce

1. Run `npx create-next-app@latest rts`

### Describe the Bug

```bash
√ Would you like to use TypeScript with this project? ... No / Yes
√ Would you like to use ESLint with this project? ... No / Yes
√ Would you like to use Tailwind CSS with this project? ... No / Yes
√ Would you like to use `src/` directory with this project? ... No / Yes
√ Would you like to use experimental `app/` directory with this project? ... No / Yes
√ What import alias would you like configured? ... @/*
Creating a new Next.js app in E:\typescript\rts.

Using npm.

Initializing project with template: default-tw


Installing dependencies:
- react
- react-dom
- next
- typescript
- @types/react
- @types/node
- @types/react-dom
- tailwindcss
- postcss
- autoprefixer
- eslint
- eslint-config-next


Aborting installation.
Unexpected error. Please report it as a bug:
 Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:743:9)
    at spawn (C:\Users\***\AppData\Local\npm-cache\_npx\cc2145a2fe1558fa\node_modules\create-next-app\dist\index.js:44:7594)
    at C:\Users\***\AppData\Local\npm-cache\_npx\cc2145a2fe1558fa\node_modules\create-next-app\dist\index.js:325:18946
    at new Promise (<anonymous>)
    at install (C:\Users\***\AppData\Local\npm-cache\_npx\cc2145a2fe1558fa\node_modules\create-next-app\dist\index.js:325:18439)
    at installTemplate (C:\Users\***\AppData\Local\npm-cache\_npx\cc2145a2fe1558fa\node_modules\create-next-app\dist\index.js:325:23294)
    at async createApp (C:\Users\***\AppData\Local\npm-cache\_npx\cc2145a2fe1558fa\node_modules\create-next-app\dist\index.js:325:26083)
    at async run (C:\Users\***\AppData\Local\npm-cache\_npx\cc2145a2fe1558fa\node_modules\create-next-app\dist\index.js:325:34719) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```

### Expected Behavior

Project being created.

**Comment by j-machuca** [comment]
Tried installing v13.3.3 was installed successfully with no issues

**Comment by j-machuca** [comment]
Issue fixed in new version
