### ISSUE TITLE
Server Action Validation example does not use async functions

### ISSUE THREAD

**Issue by kerwanp** [vercel/next.js#49344]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 3.5.0
      pnpm: 7.30.3
    Relevant packages:
      next: 13.4.1-canary.2
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.4.1-canary.2", newest: "13.4.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/kerwanp/next-server-actions-repr/blob/main/app/with-validate.ts

#### 2. Copy the validation example from the documentation

```typescript
// app/_actions.ts
import { cookies } from 'next/headers';
 
async function addItem(data) {
  'use server';
 
  const cartId = cookies().get('cartId')?.value;
 
  await saveToDb({ cartId, data });
}
```

```typescript
// app/with-validate.ts

function verifyData(data: FormData) {
  return true;
}

function process(data: FormData) {
  return data;
}

export function withValidate(action) {
  return (formData: FormData) => {
    "use server";

    const isValidData = verifyData(formData);

    if (!isValidData) {
      throw new Error("Invalid input.");
    }

    const data = process(formData);
    return action(data);
  };
}
```

#### 3. Use the Server Action in a page

```typescript
// app/page.tsx

import { action } from "./_actions";

/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  return (
    <form action={action}>
      <input type="text" />
      <button type="submit">Hello</button>
    </form>
  );
}
```

### Describe the Bug

When running the application and compiling the page using our Server Action we receive the following error:

```
Error:
  x Server actions must be async functions
    ,-[/home/mpaucot/workspace/kerwanp/reproduction-next/app/with-validate.ts:7:1]
  7 |     }
  8 |
  9 |     export function withValidate(action) {
 10 | ,->   return (formData: FormData) => {
 11 | |       "use server";
 12 | |
 13 | |       const isValidData = verifyData(formData);
 14 | |
 15 | |       if (!isValidData) {
 16 | |         throw new Error("Invalid input.");
 17 | |       }
 18 | |
 19 | |       const data = process(formData);
 20 | |       return action(data);
 21 | `->   };
 22 |     }
    `----

Import trace for requested module:
./app/with-validate.ts
./app/_actions.ts
./app/page.tsx
```

When following the instructions given by the error by making the returned function async the page render properly:

```typescript
export function withValidate(action) {
  return async (formData: FormData) => {
            ^^^^
    "use server";

    const isValidData = verifyData(formData);

    if (!isValidData) {
      throw new Error("Invalid input.");
    }

    const data = process(formData);
    return action(data);
  };
}
```

But when executing the action by submiting the form we get the following error message:

```typescript
- error app/with-validate.ts (10:16) @ formData
- error TypeError: Cannot read properties of null (reading '1')
    at $$ACTION_1 (./app/with-validate.ts:17:54)
    at $$ACTION_0 (./app/with-validate.ts:13:43)
   8 |
   9 | export function withValidate(action) {
> 10 |   return async (formData: FormData) => {
     |                ^
  11 |     "use server";
  12 |
  13 |     const isValidData = verifyData(formData);
```

### Expected Behavior

The nested function inside withValidate should be called when executing the Server Action.

**Comment by kerwanp** [comment]
I'm able to use this pattern by simply removing the `'use server';` from the `withValidate` function.

And I am also able to use an async function:
```typescript
export function withValidation<S extends AnyObjectSchema>(
  schema: S,
  action: (data: InferType<S>) => unknown
) {
  return async (data: InferType<S>) => {
    const valid = await schema.validate(data);
    return action(data);
  };
}
```
