### ISSUE TITLE
Upgrading from 13.3.4 to 13.4.0 causes react error "Warning: Invalid hook call."

### ISSUE THREAD

**Issue by jamesopti** [vercel/next.js#49376]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
➜  client git:(nextjs-13-4) ✗ yarn next info
(node:47392) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 3.4.1
      pnpm: 6.11.0
    Relevant packages:
      next: 13.4.1-canary.2
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Unsure (not using new app directory)

### Link to the code that reproduces this issue

n/a

### To Reproduce

Upgrading from next 13.3.4 to 13.4.1 causes react hook error.

The only change being made is upgrading next and adding the `@opentelemetry/*` packages per https://github.com/vercel/next.js/issues/48118#issuecomment-1501113705

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useMemo')
    at useMemo (/Users/u/app/node_modules/react/cjs/react.development.js:1650:21)
    at ThemeProvider (file:///Users/u/app/node_modules/@chakra-ui/system/dist/chunk-3ZTTLJBV.mjs:14:25)
    at renderWithHooks (/Users/u/app/packages/client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:16)
    at renderIndeterminateComponent (/Users/u/app/packages/client/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8748:15)
```

### Describe the Bug

`next dev` starts but any page load results in a server side render error (see above)

### Expected Behavior

The app starts normally

### Which browser are you using? (if relevant)

Version 112.0.5615.137 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

**Comment by jamesopti** [comment]
The root cause of this issue is the same as https://github.com/vercel/next.js/issues/49355

I'll close this in favor of that one.
