### ISSUE TITLE
[NEXT-1188] [13.4.x] ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by ribeaud** [vercel/next.js#49397]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
❯ npx next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://gitlab.com/biomedit/next-widgets/

### To Reproduce

1. Checkout the project
2. Adapt **next.js** version
3. Run `npm i && npm run test`

### Describe the Bug

Since _v13.4.x_, our test suites started to throw following error:
```
ReferenceError: TextEncoder is not defined
```
If we roll back to _v13.3.4_, the tests are green.

Somehow I have the impression that https://github.com/vercel/next.js/pull/49053 introduced the problem on our side but I am not sure 100% (I went through all the changes listed in the changelog).

[Here](https://gitlab.com/biomedit/next-widgets/-/merge_requests/223) is the **MR** where the problem started to appear.
The **MR** did succeed because I reverted **Next.js** to _v13.3.4_.

### Expected Behavior

Tests should be green.

<sub>[NEXT-1188](https://linear.app/vercel/issue/NEXT-1188/[134x]-referenceerror-textencoder-is-not-defined)</sub>

**Comment by mikedidomizio** [comment]
I encountered this exact same error on my team when running Jest tests.  The error for us, appears to be coming through Apollo Client [@apollo/client@3.7.14](https://www.npmjs.com/package/@apollo/client)

Like @ribeaud the fix was to downgrade to v13.3.4.  I bisected through it and for us, the error is introduced through [this PR](https://github.com/vercel/next.js/pull/49061) which removes node-fetch as a fallback and goes straight to [undici](https://github.com/nodejs/undici).

I reverted the commit `e6acd40cba2c565919ee3e94bb9e8a100dc69495` ([branch here](https://github.com/vercel/next.js/compare/canary...mikedidomizio:next.js:fix-undici-2)) and everything works.  Not the answer, but just some info.  Even if I just return node-fetch and never undici things work fine.

Otherwise, setting the global TextEncoder did get me a step further as suggested [here](https://github.com/apollographql/apollo-client/pull/9975#discussion_r943778481), but ran into further issues

```shell
clearImmediate is not defined

/next.js/packages/next/dist/compiled/undici/index.js:1:82074)
```

The below didn't work for me but may work for someone else.  For me the Apollo client would never return data

```shell
// jest.setup.ts

global.clearImmediate = jest.fn()
```


My info

```shell
npx next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 7.28.0
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.5-canary.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.2
```

**Comment by davidbnk** [comment]
This happens sometimes to us in production

```
ReferenceError: TextEncoder is not defined
  at Object.119(./node_modules/next/dist/client/app-index.js:76:17)
  at s(app:///_next/static/chunks/webpack-aaa2a25000886b98.js:1:167)
  at callback(./node_modules/next/dist/client/app-next.js:10:26)
  at hydrate(./node_modules/next/dist/client/app-bootstrap.js:58:9)
  at appBootstrap(./node_modules/next/dist/client/app-bootstrap.js:23:16)
  at Object.4918(./node_modules/next/dist/client/app-next.js:6:19)
  at s(app:///_next/static/chunks/webpack-aaa2a25000886b98.js:1:167)
  at n(app:///_next/static/chunks/main-app-bcd83a9e7e626f59.js:1:763)
  at ? (app:///_next/static/chunks/main-app-bcd83a9e7e626f59.js:1:819)
  at Function.s.O(app:///_next/static/chunks/webpack-aaa2a25000886b98.js:1:593)
  at c(app:///_next/static/chunks/webpack-aaa2a25000886b98.js:1:3908)
  at <anonymous>(./node_modules/next/dist/build/polyfills/polyfill-module.js?5488:1:1)
  at Script.runInContext(vm.js:144:12)
  at Object.runInContext(vm.js:294:6)
  at processJavaScript(/bwtpn/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:241:10)
  at HTMLScriptElementImpl._innerEval(/bwtpn/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
  at onLoadExternalScript(/bwtpn/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:98:12)
  at QueueItem.onLoadWrapped [as onLoad](/bwtpn/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:53:33)
  at AsyncResourceQueue._check(/bwtpn/node_modules/jsdom/lib/jsdom/browser/resources/async-resource-queue.js:39:22)
  at ? (/bwtpn/node_modules/jsdom/lib/jsdom/browser/resources/async-resource-queue.js:74:20)
  at processTicksAndRejections(internal/process/task_queues.js:95:5)
  ```

**Comment by davidbnk** [comment]
https://github.com/vercel/next.js/blob/387430c659f12189f9a36b55570820954f9b3a5c/packages/next/src/client/app-index.tsx#L97

this class seems to be imported from the polyfill, which maybe is failing to build under some some circumstances

https://github.com/vercel/next.js/blob/387430c659f12189f9a36b55570820954f9b3a5c/packages/next/src/client/app-index.tsx#L2

**Comment by ribeaud** [comment]
It is clear that the problem relates to **Jest** only. The deployed application works correctly. As a workaround one could apply any of the ones suggested [here](https://github.com/inrupt/solid-client-authn-js/issues/1676).

**Comment by davidbnk** [comment]
It happened to me in production a bunch of times running on vercel

![image](https://github.com/vercel/next.js/assets/1213985/06d87c75-001a-4efa-aa20-f6fa9aeebe3b)

**Comment by ribeaud** [comment]
Could it be that the **fetch** [polyfill](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/node-polyfill-fetch.ts) is not complete and miss `TextDecoder` resp. `TextEncoder` implementation?

**Comment by zigang93** [comment]
I am confirm this bug exist on `13.4.x`
I am not recommand those people try to mock `TextEncoder` and `TextDecoder` 
because it will break the `useFakerTimer` and `waitFor` for hanging the jest unit testing..

I am downgrade to `13.2.x` , my test resolved

**Comment by zigang93** [comment]
> It is clear that the problem relates to **Jest** only. The deployed application works correctly on our side. As a workaround one could apply any of the ones suggested [here](https://github.com/inrupt/solid-client-authn-js/issues/1676).

it is not jest related. it already been patched long time ago..

**Comment by camin-mccluskey** [comment]
![Screenshot 2023-08-21 at 09 50 04](https://github.com/vercel/next.js/assets/18604525/a41d19c1-f100-40fb-af1b-5e191fbac005)

Also spotted this issue in production. Same Chrome version as the repro above

**Comment by alexboii** [comment]
having this issue as well

**Comment by tom-mason-verses** [comment]
Has there been any movement on this?  I'm encountering it as well

**Comment by novaotp** [comment]
Getting the same error in the middleware file... (NextJS 14.0.1)

Has someone found a workaround ?

**Comment by Rieranthony** [comment]
Same issue for me in production, got this in my sentry logs this morning (running 14.0.2).

![CleanShot 2023-11-13 at 08 53 38@2x](https://github.com/vercel/next.js/assets/19694603/7d2a3f71-488a-4638-9623-b0882f1f2790)

If this can help!

**Comment by timneutkens** [comment]
https://caniuse.com/mdn-api_textencoder

This API has been available in browsers for a long time i.e. added in Chrome 38, which was published on 15th of August 2014. Looking at the stacktraces the reports are related to jsdom and somehow running Next.js internals with JSDOM (not sure how that setup would work, but the stacktrace is quite clear that it is using jsdom). JSDOM doesn't have TextEncoder it seems: https://github.com/jsdom/jsdom/issues/2524

**Comment by MenaiAla** [comment]
It happened to me in production ( NextJS13.4.0 ) :

![image](https://github.com/vercel/next.js/assets/20143684/e9c9d4ac-c90c-4d51-bae6-6f24c9377d86)

**Comment by Kevin-McGonigle** [comment]
> https://caniuse.com/mdn-api_textencoder
> 
> This API has been available in browsers for a long time, added in Chrome 38 which was published on 15th of August 2014. Looking at the stacktraces the reports are related to jsdom and somehow running Next.js internals with JSDOM (not sure how that setup would work, but the stacktrace is quite clear that it is using jsdom). JSDOM doesn't have TextEncoder it seems: [jsdom/jsdom#2524](https://github.com/jsdom/jsdom/issues/2524).
> 
> Is anyone else running into this that is not in the JSDOM environment?

For those of you experiencing this error when using jest, your default `testEnvironment` is `jsdom`, and you're testing code that's meant to be run on the server - try adding this to the top of your test file:
```ts
/**
 * @jest-environment node
 */
```

See the jest [docs](https://jestjs.io/docs/configuration#testenvironment-string) for more.

**Comment by MenaiAla** [comment]
@Kevin-McGonigle, do you mean to add it at the top of each file? Is there another way to add it to the jest config once time?

**Comment by Kevin-McGonigle** [comment]
@MenaiAla If most of your tests are for code executed in the node runtime, then going the opposite direction of setting the `testEnvironment` property of your jest config to `'node'` (or omitting it entirely, since `'node'` is the default) and then adding:
```
/**
 * @jest-environment jsdom
 */
```
to the top of tests for files where the code under test is typically executed in the browser might be the less painful route.

This, and my previous comment, is only applicable when the cause of this error is due to the mix up in runtimes.

**Comment by MenaiAla** [comment]
Thank you @Kevin-McGonigle.

**Comment by woodwoerk** [comment]
I'm seeing the same issue in production in the same Chrome version as the reports above (`Chrome 84.0.4147`). Our Next.js version is `14.0.4`.

<img width="802" alt="image" src="https://github.com/vercel/next.js/assets/15343658/e5bf1d52-a836-4501-ab36-49118922638b">

**Comment by kiurious** [comment]
We're on Next 14.0.1 and we had the same error in production this morning. We are not using jest though. 
![image](https://github.com/vercel/next.js/assets/29750764/954b3fba-d175-4134-b128-22cc0d645b30)

**Comment by marcoshernanz** [comment]
Thanks for the report. I reproduced this on Next 13.4.1 and confirmed that it came from the bundled `undici` fetch polyfill introduced by #49061 when Jest ran under JSDOM. That polyfill was removed in #56899 before Next 14, and Next 13 and 14 are no longer supported. The production stack traces shared here also run through Node's VM and JSDOM, where `TextEncoder` was historically missing, rather than a real Chrome runtime.

For older test setups, use the Node test environment for server code or provide the missing JSDOM globals. Closing as resolved and outdated. If this reproduces on a supported Next.js version outside JSDOM, please open a new issue with a minimal reproduction.
