### ISSUE TITLE
TypeError: handler is not a function before server is fully online

### ISSUE THREAD

**Issue by masterkain** [vercel/next.js#49536]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Tue Sep 13 07:51:46 UTC 2022
    Binaries:
      Node: 20.1.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### To Reproduce

I'm building the app for docker in standalone mode, so I start the server with `node server.js`.
I'm also deploying in kubernetes, and this is happening. at the moment it's unclear if it's happening because traffic is hitting the pod before the server is fully ready or there's something else.

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: 'standalone'
};

module.exports = nextConfig;
```

### Describe the Bug

```
│ TypeError: handler is not a function                                                                                                                                               │
│     at Server.<anonymous> (/app/server.js:29:11)                                                                                                                                   │
│     at Server.emit (node:events:511:28)                                                                                                                                            │
│     at parserOnIncoming (node:_http_server:1109:12)                                                                                                                                │
│     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)                                                                                                               │
│ TypeError: handler is not a function                                                                                                                                               │
│     at Server.<anonymous> (/app/server.js:29:11)                                                                                                                                   │
│     at Server.emit (node:events:511:28)                                                                                                                                            │
│     at parserOnIncoming (node:_http_server:1109:12)                                                                                                                                │
│     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)                                                                                                               │
│ TypeError: handler is not a function                                                                                                                                               │
│     at Server.<anonymous> (/app/server.js:29:11)                                                                                                                                   │
│     at Server.emit (node:events:511:28)                                                                                                                                            │
│     at parserOnIncoming (node:_http_server:1109:12)                                                                                                                                │
│     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)                                                                                                               │
│ Listening on port 3000 url: http://airbroke-web-f88f4dbc7-dvxqb:3000     
```

### Expected Behavior

I'm debugging an issue with prisma connections and stumbled upon this, so I took a look at the compiled server.js

maybe to ensure the server is fully initialized before it starts accepting incoming traffic, we can move the `handler` initialization to be before the `createServer` call, like this?

```js
(async () => {
  handler = await createServerHandler({
    port: currentPort,
    hostname,
    dir,
    conf: nextConfig,
  })

  const server = http.createServer(async (req, res) => {
    try {
      await handler(req, res)
    } catch (err) {
      console.error(err);
      res.statusCode = 500
      res.end('Internal Server Error')
    }
  })

  if (
    !Number.isNaN(keepAliveTimeout) &&
    Number.isFinite(keepAliveTimeout) &&
    keepAliveTimeout >= 0
  ) {
    server.keepAliveTimeout = keepAliveTimeout
  }
  server.listen(currentPort, (err) => {
    if (err) {
      console.error("Failed to start server", err)
      process.exit(1)
    }

    console.log(
      'Listening on port',
      currentPort,
      'url: http://' + hostname + ':' + currentPort
    )
  })
})()
```

**Comment by ferdingler** [comment]
The issue appears to have been introduced here: https://github.com/ferdingler/next.js/commit/83b774eeb69f1fe4f636260f83ed98c6d0717a3d where the creation of the Next Server now returns a promise that takes a while to resolve

**Comment by masterkain** [comment]
that's interesting, that also might be source of my prisma issues

**Comment by ferdingler** [comment]
Here is a server.js that works if it helps you: 

```
const http = require("http");
const path = require("path");
const {
  createServerHandler,
} = require("next/dist/server/lib/render-server-standalone");

const dir = path.join(__dirname);

process.env.NODE_ENV = "production";
process.chdir(__dirname);

// Make sure commands gracefully respect termination signals (e.g. from Docker)
// Allow the graceful termination to be manually configurable
if (!process.env.NEXT_MANUAL_SIG_HANDLE) {
  process.on("SIGTERM", () => process.exit(0));
  process.on("SIGINT", () => process.exit(0));
}

const currentPort = parseInt(process.env.PORT, 10) || 3000;
const hostname = process.env.HOSTNAME || "localhost";
const keepAliveTimeout = parseInt(process.env.KEEP_ALIVE_TIMEOUT, 10);

// const nextConfig = {}; // ommitted for brevity

process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(nextConfig);

createServerHandler({
  port: currentPort,
  hostname,
  dir,
  conf: nextConfig,
}).then((nextHandler) => {
  console.log("Creating http server");
  const server = http.createServer(async (req, res) => {
    try {
      console.log("Handling request");
      await nextHandler(req, res);
    } catch (err) {
      console.error("Failed to call handler", err);
      res.statusCode = 500;
      res.end("Internal Server Error");
    }
  });

  if (
    !Number.isNaN(keepAliveTimeout) &&
    Number.isFinite(keepAliveTimeout) &&
    keepAliveTimeout >= 0
  ) {
    console.log("Setting keep alive timeout", keepAliveTimeout);
    server.keepAliveTimeout = keepAliveTimeout;
  }

  server.listen(currentPort, async (err) => {
    if (err) {
      console.error("Failed to start server", err);
      process.exit(1);
    }

    console.log(
      "Listening on port",
      currentPort,
      "url: http://" + hostname + ":" + currentPort
    );
  });
}).catch(err => {
  console.error("Failed to create next server handler", err);
  process.exit(1);
});
```

You can copy it manually to the standalone directory to override the one Next.js generates after running a build: 
```
cp server.js .next/standalone/server.js
```

**Comment by masterkain** [comment]
ok, I have some findings /cc @shuding 

I downgraded to `13.3.5-canary.8`, the last release before https://github.com/vercel/next.js/commit/83b774eeb69f1fe4f636260f83ed98c6d0717a3d

and my problems with the application using prisma on both server side components and route handlers getting completely unresponsive goes away, I've spent two good days investigating database connections and setups as I was thinking I did mess up my prisma connections somehow, aggravated from the fact that I run pgbouncer and that there are different ways of reusing prisma given the context (dev, prod, serverless function).

I've seen all kind of weird issues with the latest canary, but mainly what I was able to see is that route handlers along with prisma were fine, but the moment I performed a web request to the web app the server would crash or halt, not responding to any request and stopping responding also on route handlers.

on `13.3.5-canary.8` these issues goes away, but in the logs we can now see:

```
│ Error: ENOENT: no such file or directory, open '/app/app/favicon.ico'                                                                                                              │
│     at Object.openSync (node:fs:590:3)                                                                                                                                             │
│     at Object.readFileSync (node:fs:458:35)                                                                                                                                        │
│     at 3576 (/app/.next/server/app/favicon.ico/route.js:102:38)                                                                                                                    │
│     at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:43)                                                                                                            │
│     at __webpack_exec__ (/app/.next/server/app/favicon.ico/route.js:153:39)                                                                                                        │
│     at /app/.next/server/app/favicon.ico/route.js:154:73                                                                                                                           │
│     at __webpack_require__.X (/app/.next/server/webpack-runtime.js:150:21)                                                                                                         │
│     at /app/.next/server/app/favicon.ico/route.js:154:47                                                                                                                           │
│     at Object.<anonymous> (/app/.next/server/app/favicon.ico/route.js:157:3)                                                                                                       │
│     at Module._compile (node:internal/modules/cjs/loader:1267:14) {                                                                                                                │
│   errno: -2,                                                                                                                                                                       │
│   syscall: 'open',                                                                                                                                                                 │
│   code: 'ENOENT',                                                                                                                                                                  │
│   path: '/app/app/favicon.ico'                                                                                                                                                     │
│ }
│ TypeError: Cannot read properties of null (reading 'useContext')                                                                                                                   │
│     at exports.useContext (/app/node_modules/next/dist/compiled/react/cjs/react.production.min.js:28:118)                                                                          │
│     at Head (/app/.next/server/pages/_error.js:282:44)                                                                                                                             │
│     at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)                                                                                       │
│     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)                                                                                      │
│     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)                                                                                        │
│     at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)                                                                                       │
│     at bd (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)                                                                                      │
│     at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)                                                                                       │
│     at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)                                                                                       │
│     at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)                                                                                      
```

the commit linked should fix the `useContext` issue but somehow I think that the favicon request in the most recent version has some issue, beside the prisma crazyness.

in `13.3.5-canary.8` we get ENOENT as per logs above, but on the latest canary I think that's one reason why I'm seeing pure node.js exceptions and by the looks of them it appears that a connection is failing upon the very same process. like it's attempting to connect to itself.
that connection crashes and on the browser we see Internal Server Error. I suspect this might have to do with a failed favicon request because sometimes I was able to open up the site but it crashed right after it. unfortunately I did not save the exception but it was just a pure connection failed.

**Comment by petertflem** [comment]
I might have seen the same issue. We're on 13.4. What I saw was a blank page, with only the word "Internal server error" written. After a few moments, the error went away. Has happened twice now. Check the logs right after the last time, and I have this error with a timestamp that looked reasonable:
```
TypeError: handler is not a function
```

We are using `output: 'standalone'` also, the site running in a docker container. Tried to reproduce it locally with just building it and running with `node .next/standalone/server.js`, but it didn't work. Maybe it would have to be in a docker container, or some other processes to slow things down.

So I am not a 100% sure it is the same issue, but seems plausible.

**Comment by julieca-magloft** [comment]
> I might have seen the same issue. We're on 13.4. What I saw was a blank page, with only the word "Internal server error" written. After a few moments, the error went away. Has happened twice now. Checked the logs right after the last time, and I have this error with a timestamp that looked reasonable:
> 
> ```
> TypeError: handler is not a function
> ```
> 
> We are using `output: 'standalone'` also, the site running in a docker container. Tried to reproduce it locally with just building it and running with `node .next/standalone/server.js`, but it didn't work. Maybe it would have to be in a docker container, or some other processes to slow things down.
> 
> So I am not a 100% sure it is the same issue, but seems plausible.
> 
> EDIT: Managed to trigger it by changing revisions in GCP. Here is a screenshot of what I see: <img alt="image" width="689" src="https://user-images.githubusercontent.com/5292940/237459095-fdac4ed0-3e82-4b86-998c-70c0554bce2c.png">

I experience the same as you, do you already have any clue?
