### ISSUE TITLE
React is null in vercel production build

### ISSUE THREAD

**Issue by jeetiss** [vercel/next.js#49753]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.0
      npm: 8.19.3
      Yarn: 1.22.17
      pnpm: 7.29.1
    Relevant packages:
      next: 13.4.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue

https://github.com/jeetiss/next-react-is-null

### To Reproduce

- deploy to vercel 
- build will fail with error

```
17:08:21.113 | TypeError: Cannot read properties of null (reading 'useEffect')
17:08:21.113 | at exports.useEffect (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:292)
17:08:21.113 | at QueryClientProvider (file:///vercel/path0/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)
17:08:21.113 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
17:08:21.114 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
17:08:21.114 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
17:08:21.114 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
17:08:21.114 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
17:08:21.115 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
17:08:21.115 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
17:08:21.115 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
17:08:21.117 |  
17:08:21.118 | Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
17:08:21.118 | TypeError: Cannot read properties of null (reading 'useEffect')
17:08:21.118 | at exports.useEffect (/vercel/path0/node_modules/react/cjs/react.production.min.js:24:292)
17:08:21.118 | at QueryClientProvider (file:///vercel/path0/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)
17:08:21.118 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
17:08:21.120 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
17:08:21.124 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
17:08:21.124 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
17:08:21.124 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
17:08:21.125 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
17:08:21.125 | at Ge (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
17:08:21.125 | at Z (/vercel/path0/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)



```

### Describe the Bug

deploy to vercel doesn't work when both `app` and `pages` directories are exist

### Expected Behavior

deploy should work

### How are you deploying your application? (if relevant)

Vercel

**Comment by jeetiss** [comment]
сс @shuding seems like `Cannot read properties of null` bug affects deployment to vercel too

`v13.3.4` works, but all releases after is not

**Comment by laubonghaudoi** [comment]
This seems to be related to https://github.com/vercel/next.js/issues/49261#issuecomment-1545222421
Are you using a dynamic component too?

**Comment by jeetiss** [comment]
Nope, I don't use dynamic imports.

And my demo works when i remove the `app` folder
https://github.com/jeetiss/next-react-is-null/pull/1

**Comment by jeetiss** [comment]
Thanks, it works ❤️‍🔥

**Comment by Hanggi** [comment]
I have same issue in Next `v13.4.6`

**Comment by huozhi** [comment]
@Hanggi please file a new issue with your reproduction, thanks

**Comment by quocthangit247** [comment]
> I have same issue in Next `v13.4.6`

same issue but I downgraded it to `v13.4.3`, it works like a charm

**Comment by Linkmetal** [comment]
Same here, downgraded it to v13.4.3 and works fine in Firebase Hosting

**Comment by chrisneven** [comment]
We've noticed this issue as well. It also broke our revalidation implementation

Can confirm downgrading to `v13.4.3` resolves the issue
