### ISSUE TITLE
Custom server doesn't work with App dir if hostname/port are unspecified

### ISSUE THREAD

**Issue by vain0x** [vercel/next.js#49943]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/vain0x/next.js/releases/download/2023-05-18/repro.zip

### To Reproduce

1. Install dependencies, run `next build`, start the server

```sh
npm ci
npm run build
node server.js
```

2. Open <http://localhost:3000/api/echo/hello>. The server writes an error in the console.

### Describe the Bug

If `hostname`, `port` parameters are not provided to start a custom server (`next({...})` invocation), the server doesn't work correctly. It instead emits an error to console when a route endpoint is accessed.

Note this issue happens even if middleware is *NOT* used. (hostname is mandatory if middleware is used.)

- Remarks: This issue doesn't happen if I specify `hostname` and `port` as written in the example of Custom Server documentation.
    - Also, this doesn't happen if I don't use a custom server (but use `next start`.)

## Error

Console output is:

```
- error TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at URL.onParseError (node:internal/url:566:9)
    at new URL (node:internal/url:646:5)
    at new URL (node:internal/url:643:22)
    at NextRequestAdapter.fromNodeNextRequest ($PWD\node_modules\next\dist\server\web\spec-extension\adapters\next-request.js:36:19)
    at NextRequestAdapter.fromBaseNextRequest ($PWD\node_modules\next\dist\server\web\spec-extension\adapters\next-request.js:20:35)
    at RouteHandlerManager.handle ($PWD\node_modules\next\dist\server\future\route-handler-managers\route-handler-manager.js:26:57)
    at doRender ($PWD\node_modules\next\dist\server\base-server.js:936:58)
    at cacheEntry.responseCache.get.incrementalCache.incrementalCache ($PWD\node_modules\next\dist\server\base-server.js:1152:46)
    at $PWD\node_modules\next\dist\server\response-cache\index.js:99:42
    at ResponseCache.get ($PWD\node_modules\next\dist\server\response-cache\index.js:149:11)
    at DevServer.renderToResponseWithComponentsImpl ($PWD\node_modules\next\dist\server\base-server.js:1081:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.renderPageComponent ($PWD\node_modules\next\dist\server\base-server.js:1313:24)
    at async DevServer.renderToResponseImpl ($PWD\node_modules\next\dist\server\base-server.js:1344:32)
    at async DevServer.pipeImpl ($PWD\node_modules\next\dist\server\base-server.js:628:25)
    at async Object.fn ($PWD\node_modules\next\dist\server\next-server.js:1139:21)
    at async Router.execute ($PWD\node_modules\next\dist\server\router.js:315:32)
    at async DevServer.runImpl ($PWD\node_modules\next\dist\server\base-server.js:602:29)
    at async DevServer.run ($PWD\node_modules\next\dist\server\dev\next-dev-server.js:922:20)
    at async DevServer.handleRequestImpl ($PWD\node_modules\next\dist\server\base-server.js:533:20) {
  input: '/api/echo/hello',
  code: 'ERR_INVALID_URL'
}
```

where `$PWD` is the absolute path to the `repro` diretory

### Expected Behavior

A response is sent and it should be a plaintext with status 200 and body `hello`.

### How are you deploying your application? (if relevant)

node server.js

**Comment by shuding** [comment]
I'm running your code without any changes but I can't reproduce the problem - /api/echo/hello returns the correct response. Could you please double confirm?

**Comment by islamhanafi94** [comment]
I have the same issue

**Comment by vain0x** [comment]
@shuding Thank you for trying the reproduction case and I'm sorry it didn't work for you. I just did the reproduction steps again and I saw the same error ("Invalid URL").
