### ISSUE TITLE
Using Preact example is broken with NextJS 13

### ISSUE THREAD

**Issue by RodrigoTomeES** [vercel/next.js#50010]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.3-canary.2
      eslint-config-next: N/A
      react: 17.1.2
      react-dom: 17.1.2
      typescript: 4.8.2
```

### Which example does this report relate to?

using-preact

### Describe the Bug

The app can't be build

```bash
╰─ yarn build                                                                                                                     ─╯
yarn run v1.22.19
$ next build
- info Linting and checking validity of types  

> Build error occurred
Error: Next.js requires react >= 18.2.0 to be installed.
    at Object.<anonymous> (/Users/rodrigotome/Sites/using-preact-app/node_modules/next/dist/build/webpack-config.js:143:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/rodrigotome/Sites/using-preact-app/node_modules/next/dist/build/webpack-build/impl.js:29:64)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Next build work

### To Reproduce

```bash
yarn create next-app --example using-preact using-preact-app
yarn build
```

**Comment by kyle-ssg** [comment]
Related https://github.com/vercel/next.js/issues/42530

**Comment by RodrigoTomeES** [comment]
Hi, I didn't see that issue, I will close this.
