### ISSUE TITLE
Error occurring while using Sequelize v6 with Next.js 13 approuter

### ISSUE THREAD

**Issue by 16522855** [vercel/next.js#50035]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.11.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

https://github.com/cornflourblue/next-js-13-mysql-registration-login-example.git

### Describe the Bug

When I am developing using the next.js 13 approuter mode and integrating sequlize v6 version, it reports an error when starting:`./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs`, adjusting to the old page router mode does not have this problem.

### Expected Behavior

Sequelize v6 was expected to integrate successfully with the Next.js 13 approuter routing mode without any errors. However, upon starting the application, an error occurred regarding a critical dependency request.

### To Reproduce

You can directly create a Next.js project in app router mode yarn pg pg-hstore, make an example of connecting to the database to reproduce.

log：
```
./app/models/db.ts
error - Error: The edge runtime does not support Node.js 'buffer' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at <unknown> (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:212)
    at Object.get (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:212:19)
    at eval (webpack-internal:///(middleware)/./node_modules/wkx/lib/binarywriter.js:19:51)
    at (middleware)/./node_modules/wkx/lib/binarywriter.js (file://F:\git\digital-therapy\digital-therapy-webapp\.next\server\middleware.js:3170:1)
    at __webpack_require__ (file://F:\git\digital-therapy\digital-therapy-webapp\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://F:\git\digital-therapy\digital-therapy-webapp\.next\server\edge-runtime-webpack.js:281:21)
    at eval (webpack-internal:///(middleware)/./node_modules/wkx/lib/point.js:7:20)
    at (middleware)/./node_modules/wkx/lib/point.js (file://F:\git\digital-therapy\digital-therapy-webapp\.next\server\middleware.js:3240:1)
    at __webpack_require__ (file://F:\git\digital-therapy\digital-therapy-webapp\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://F:\git\digital-therapy\digital-therapy-webapp\.next\server\edge-runtime-webpack.js:281:21)
    at eval (webpack-internal:///(middleware)/./node_modules/wkx/lib/geometry.js:5:13) {
  middleware: true
}
warn  - ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./app/models/db.ts

./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./app/models/db.ts
wait  - compiling /_error (client and server)...
warn  - ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./app/models/db.ts

./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./app/models/db.ts
```

**Comment by hohogpb** [comment]
same to me! 
in middleware, not only sequelize, but also prismajs, all those are not working

**Comment by balazsorban44** [comment]
Hi, the reproduction seems to be different than the description (eg I cannot see Middleware), but the issue is likely the same. Certain packages are not (yet) compatible with the Edge Runtime.

You can see all the APIs being supported here: https://nextjs.org/docs/pages/api-reference/edge#unsupported-apis

The Edge Runtime is constantly evolving and adding support for more APIs, as well as libraries are adding first-class support.

**Comment by Sanskar696** [comment]
Facing similar kind of issue dont know why is it happening 

wait compiling...
- warn ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./models/init_models.js

./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/sequelize/lib/dialects/abstract/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/connection-manager.js
./node_modules/sequelize/lib/dialects/mariadb/index.js
./node_modules/sequelize/lib/sequelize.js
./node_modules/sequelize/lib/index.js
./node_modules/sequelize/lib/index.mjs
./models/init_models.js
- error node_modules/sequelize/lib/utils/deprecations.js (34:0) @ <unknown>
- error (0 , import_util.deprecate) is not a function
