### ISSUE TITLE
Error running a new project - 13.4.3

### ISSUE THREAD

**Issue by brianjolly** [vercel/next.js#50228]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
I am seeing the same issue as https://github.com/vercel/next.js/issues/46632 after creating a fresh 13.4.3 project.


npx create-next-app --version
13.4.3
```

```
➜  ~ npx create-next-app          
✔ What is your project named? … my-app
✔ Would you like to use TypeScript with this project? … No / Yes
✔ Would you like to use ESLint with this project? … No / Yes
✔ Would you like to use Tailwind CSS with this project? … No / Yes
✔ Would you like to use `src/` directory with this project? … No / Yes
✔ Use App Router (recommended)? … No / Yes
✔ Would you like to customize the default import alias? … No / Yes
Creating a new Next.js app in /home/bjolly/my-app.

Using npm.

Initializing project with template: app-tw 


Installing dependencies:
- react
- react-dom
- next
- typescript
- @types/react
- @types/node
- @types/react-dom
- tailwindcss
- postcss
- autoprefixer
- eslint
- eslint-config-next




added 351 packages, and audited 352 packages in 8s

135 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Initialized a git repository.

Success! Created my-app at /home/bjolly/my-app
```

```
➜  ~ cd my-app 
➜  my-app git:(main)
```

```
 npm run build

> my-app@0.1.0 build
> next build

- info Creating an optimized production build
- info Compiled successfully
- info Linting and checking validity of types
- info Collecting page data
[    ] - info Generating static pages (0/4)
Error occurred prerendering page "/favicon.ico". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: trace.getSpan is not a function
    at NextTracerImpl.getActiveScopeSpan (/home/bjolly/my-app/.next/server/chunks/109.js:2244:22)
    at NextTracerImpl.trace (/home/bjolly/my-app/.next/server/chunks/109.js:2263:103)
    at /home/bjolly/my-app/.next/server/chunks/109.js:1403:53
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/home/bjolly/my-app/.next/server/chunks/109.js:808:24)
    at /home/bjolly/my-app/.next/server/chunks/109.js:1357:97
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (/home/bjolly/my-app/.next/server/chunks/109.js:760:24)
    at /home/bjolly/my-app/.next/server/chunks/109.js:1356:75
    at AsyncLocalStorage.run (node:async_hooks:338:14)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: trace.getSpan is not a function
    at NextTracerImpl.getActiveScopeSpan (/home/bjolly/my-app/node_modules/next/dist/server/lib/trace/tracer.js:71:22)
    at NextTracerImpl.trace (/home/bjolly/my-app/node_modules/next/dist/server/lib/trace/tracer.js:90:103)
    at /home/bjolly/my-app/node_modules/next/dist/server/lib/trace/tracer.js:155:31
    at wrappedRender (/home/bjolly/my-app/node_modules/next/dist/server/app-render/app-render.js:1006:62)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: trace.getSpan is not a function
    at NextTracerImpl.getActiveScopeSpan (/home/bjolly/my-app/node_modules/next/dist/server/lib/trace/tracer.js:71:22)
    at NextTracerImpl.trace (/home/bjolly/my-app/node_modules/next/dist/server/lib/trace/tracer.js:90:103)
    at renderToHTML (/home/bjolly/my-app/node_modules/next/dist/server/render.js:827:59)
    at async /home/bjolly/my-app/node_modules/next/dist/export/worker.js:456:36
    at async Span.traceAsyncFn (/home/bjolly/my-app/node_modules/next/dist/trace/trace.js:103:20)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: trace.getSpan is not a function
    at NextTracerImpl.getActiveScopeSpan (/home/bjolly/my-app/node_modules/next/dist/server/lib/trace/tracer.js:71:22)
    at NextTracerImpl.trace (/home/bjolly/my-app/node_modules/next/dist/server/lib/trace/tracer.js:90:103)
    at renderToHTML (/home/bjolly/my-app/node_modules/next/dist/server/render.js:827:59)
    at async /home/bjolly/my-app/node_modules/next/dist/export/worker.js:456:36
    at async Span.traceAsyncFn (/home/bjolly/my-app/node_modules/next/dist/trace/trace.js:103:20)
- info Generating static pages (4/4)

> Export encountered errors on following paths:
        /_error: /404
        /_error: /500
        /favicon.ico/route: /favicon.ico
        /page: /
```

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app

### To Reproduce

```
npx create-next-app
cd my-app
npm run build
```

### Describe the Bug

`TypeError: trace.getSpan is not a function`

### Expected Behavior

Expecting no TypeError

**Comment by Grekz** [comment]
This error also happened to me when I created the app using: `npx create-next-app@latest`
As a workaround I ran: 
```bash
npm install @opentelemetry/api
```

I hope it helps :)

**Comment by caprica** [comment]
Grekz' answer was very helpful, but then instead of installing the telemetry package you can simply disable telemetry:

```
npx next telemetry disable
```
