### ISSUE TITLE
ValidationError: Invalid options object. Ignore Plugin has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by Walids35** [vercel/next.js#50381]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

Company Repository

### To Reproduce

- yarn dev

### Describe the Bug

The CopyWebpackPlugin struggles when it comes to copy CSS files into 'public'. It returns the following error:
`ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns should be a non-empty array.
    at validate (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\copy-webpack-plugin\node_modules\schema-uti
    at new CopyPlugin (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\copy-webpack-plugin\dist\index.js:172
    at Object.webpack (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\next.config.js:96:7)
    at Object.webpack (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\@next\bundle-analyzer\index.js:22:29)
    at Object.getBaseWebpackConfig [as default] (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\next\dist\b
    at async Promise.all (index 1)
    at async Span.traceAsyncFn (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\next\dist\trace\trace.js:79:
    at async Span.traceAsyncFn (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\next\dist\trace\trace.js:79:
    at async HotReloader.start (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\next\dist\server\dev\hot-rel
    at async DevServer.prepare (C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\next\dist\server\dev\next-de
    at async C:\Users\wsial\Desktop\walid\GithubRepos\automa-to\dashboard\node_modules\next\dist\cli\next-dev.js:521:17 {
  errors: [
    {
      instancePath: '/patterns',
      schemaPath: '#/properties/patterns/minItems',
      keyword: 'minItems',
      params: [Object],
      message: 'must NOT have fewer than 1 items',
      schema: 1,
      parentSchema: [Object],
      data: []
    }
  ],
  schema: {`

### Expected Behavior

Should run & compile

**Comment by Walids35** [comment]
The Github Repository that I'm working on is not public and belong to a company. Therefore, I could not upload a reproduction

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
