### ISSUE TITLE
[App Router] The redirect function of 'next/navigation' package stay in pending status

### ISSUE THREAD

**Issue by CamilleLegeron** [vercel/next.js#50595]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://gitlab.com/incubateur-territoires/startups/donnees-et-territoires/nextjs-bug-reproduction

### To Reproduce

Start the project in local with `npm run dev`
Open the inspector on network tab
Click on the `Submit` button and see that the page `/redirection` stay in `pending` state. But if you go directly to the url `http://localhost:3000/redirection` it's work. 

### Describe the Bug

The redirection from route is not working
With nextjs version `13.3.0` it was working fine

### Expected Behavior

I expect that when you click on the submit button it go to the `/redirection` page.

### Which browser are you using? (if relevant)

Chrome 110.0.5481.77

### How are you deploying your application? (if relevant)

npm run dev

**Comment by BaffinLee** [comment]
I did some debugging, and found this pattern:

works:
```javascript
fetch("http://localhost:3000/redirection", {
  "method": "POST",
});
```

pending:
```javascript
fetch("http://localhost:3000/redirection", {
  "headers": {
    "content-type": "application/x-www-form-urlencoded",
  },
  "method": "POST",
});
```

Maybe next treat that header differently, need more work here.

**Comment by garethlowrie** [comment]
Same thing happening to me, spent hours trying to get this working.
Works if I go directly to the url but when I do a fetch it does not redirect.

**Comment by Angelelz** [comment]
@BaffinLee 
Can you elaborate? Do you have any workaround for this issue?

**Comment by Angelelz** [comment]
There is currently no way to redirect from an api route.
That is just crazy!! Next is calling the App Router production ready, it blows my mind.
I attempted to recreate this issue, and tried to work around it by using the NextRequest.redirect function (doesn't work) and then using the old pages route handler with res.redirect function and it doesn't work either.

Please try this reproduction link:
https://github.com/Angelelz/next-redirect-bug

**Comment by BaffinLee** [comment]
> @BaffinLee Can you elaborate? Do you have any workaround for this issue?

@Angelelz @CamilleLegeron redirect with code 301/302/303 might work.

According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections), redirect with code 301/302/303 will change method to GET (from POST), so that should be a workaround.

**Comment by claudioscheer** [comment]
I fixed this error with the following

```javascript
export async function POST(req: Request, res) {
  try {
    const data = await req.formData();

    return NextResponse.redirect(new URL("/redirect", req.url), 303);
  } catch (e) {
    console.error(e);
    return NextResponse.json({ success: false, error: "Something went wrong" });
  }
}

```

**Comment by peppymon** [comment]
@claudioscheer 
amazing!! thansk!!

I was searching how to redirect on POST call, do you know why with the 303 status works but not with other 3xx status??

**Comment by claudioscheer** [comment]
@peppymon From what I can see, it's because `the method used to display this redirected page is always GET`, while 307 keeps the same method (POST in this case).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307

**Comment by zahitrios** [comment]
it make sense, thanks again @claudioscheer

**Comment by nicnocquee** [comment]
> @peppymon From what I can see, it's because `the method used to display this redirected page is always GET`, while 307 keeps the same method (POST in this case).
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307

This should be in the documentation. Spent a long time to figure out why I couldn't the post-redirect-get when submitting a POST form.

**Comment by ascii042** [comment]
I am seeing this in production for a website that is behind CloudeFlare firewall. If a user visits a secondary domain (with a redirect to the main one) and needs to pass CloudFlare challenge, the post-challenge request gets these two headers: `content-type:application/x-www-form-urlencoded` & `origin:null`. I did not know that `origin` can could be null, but that is real: https://stackoverflow.com/a/22625354/1818285

Reproduction for `next dev` / `next start`:

```
http POST http://localhost:3000 "content-type:application/x-www-form-urlencoded" "origin:null"
```

```
 ⨯ TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at rw (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:6487)
    at r6 (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1262)
    at /path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:42:726
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:16615)
    at /path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:42:616
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:15721)
    at r3 (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:42:543)
    at nd.render (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:42:4661)
    at doRender (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/server/base-server.js:1438:44)
    at cacheEntry.responseCache.get.routeKind (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/server/base-server.js:1587:46)
    at ResponseCache.get (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/server/response-cache/index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (/path/to/project/node_modules/.pnpm/next@14.2.5_patch_hash=hcy55snj4ba4np4572joyxkryq_@playwright+test@1.46.0_react-dom@18.3.1_re_cmvz2lpd4z4gk3hjdj2yjxqcuq/node_modules/next/dist/server/base-server.js:1507:53) {
  code: 'ERR_INVALID_URL',
  input: 'null',
  page: '/'
}
 POST / 500 in 15ms
 ```

Here is a line that crashes: 
https://github.com/vercel/next.js/blob/939251bf65633c6b330bdcd6476e651bbc16efa2/packages/next/src/server/app-render/action-handler.ts#L459-L462

And here is what leads to it:
https://github.com/vercel/next.js/blob/939251bf65633c6b330bdcd6476e651bbc16efa2/packages/next/src/server/lib/server-action-request-meta.ts#L26-L27

Here is my current workaround (at the very top of `middleware.ts`):

```ts
  if (
    request.headers.get("content-type") ===
      "application/x-www-form-urlencoded" &&
    request.headers.get("origin") === "null"
  ) {
    const modifiedRequestHeaders = new Headers(request.headers);
    modifiedRequestHeaders.delete("application/x-www-form-urlencoded");
    modifiedRequestHeaders.delete("origin");

    return NextResponse.redirect(request.nextUrl, {
      headers: modifiedRequestHeaders,
      status: 303, // POST → GET
    });
  }
```

**Comment by marcoshernanz** [comment]
Thanks for the report. This was fixed by #58885, which changed form/action redirects to use 303 so the POST is not re-submitted to the destination. The original repro fails on 14.0.3 but works on 14.0.4 and current canary. The later `Origin: null` case was tracked in #84786 and fixed by #85402. Closing as resolved.
