### ISSUE TITLE
`NEXT_RSC_ERR_CLIENT_METADATA_EXPORT` when importing page.tsx with a variable path

### ISSUE THREAD

**Issue by austinlangdon** [vercel/next.js#50779]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.5-canary.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/austinlangdon/metadata-export-err/blob/ce706baad9c64c36c8c3ae70990b64b1f4e71b60/app/page.tsx#LL11C12-L11C12

### To Reproduce

1. create next app
2. create a page `app/about/page.tsx` + add metadata to it
3. try dynamically importing it using a variable path - it doesn't work (throws `NEXT_RSC_ERR_CLIENT_METADATA_EXPORT`)

```
const path = '/about/page'
const page = await import(`../app${path}`);  

console.log(page.metadata)
```

This does work (explicitly written import path)

```
const page = await import('../app/about/page');

console.log(page.metadata)
```

### Describe the Bug

When you dynamically import a page.tsx file with metadata using a variable path, it triggers a NEXT_RSC_ERR_CLIENT_METADATA_EXPORT error:

```
- error ./app/about/page.tsx

Error: 
  x NEXT_RSC_ERR_CLIENT_METADATA_EXPORT: metadata
   ,-[/Users/austinlangdon/code/metadata-export-err/app/about/page.tsx:1:1]
 1 | export const metadata = {
   :              ^^^^^^^^
 2 |     title: 'About'
 3 | }
   `----
```

The following error is also logged before the one above:

```
TypeError: Cannot read properties of undefined (reading 'replace')
    at getModuleTrace (/Users/austinlangdon/code/metadata-export-err/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/getModuleTrace.js:74:48)
    at getRscError (/Users/austinlangdon/code/metadata-export-err/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseRSC.js:88:78)
    at getModuleBuildError (/Users/austinlangdon/code/metadata-export-err/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:122:43)
    at async /Users/austinlangdon/code/metadata-export-err/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:21:49
    at async Promise.all (index 0)
    at async /Users/austinlangdon/code/metadata-export-err/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:19:21
```

Another person also reported this exact bug a few months ago:
https://github.com/vercel/next.js/issues/47703

### Expected Behavior

No error should be thrown

**Comment by tubbo** [comment]
Something similar just started happening for me in Next v13.4.9 builds using `page.mdx` files. I'm not sure what caused it, but trying to see if anything in [the changelog for this release](https://github.com/vercel/next.js/releases/tag/v13.4.9) jumps out at me.

The error is thrown at build time, during "Creating an optimized production build", so I'm assuming this is happening in the type-checking phase of the whole process. There have been a couple changes made to the TS Plugin, namely https://github.com/vercel/next.js/pull/52211, which I think may have something to do with this. 

**Logs:**

```
yarn run v1.22.19
$ next build
- info Loaded env from /Users/tubbo/Code/psychedeli.ca/.env.production
- info Loaded env from /Users/tubbo/Code/psychedeli.ca/.env
TypeError: Cannot read properties of undefined (reading 'replace')
    at getModuleTrace (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/getModuleTrace.js:74:48)
    at getRscError (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseRSC.js:88:78)
    at getModuleBuildError (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:122:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:21:49
    at async Promise.all (index 0)
    at async /Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:19:21
TypeError: Cannot read properties of undefined (reading 'replace')
    at getModuleTrace (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/getModuleTrace.js:74:48)
    at getRscError (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseRSC.js:88:78)
    at getModuleBuildError (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:122:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:21:49
    at async Promise.all (index 1)
    at async /Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:19:21
TypeError: Cannot read properties of undefined (reading 'replace')
    at getModuleTrace (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/getModuleTrace.js:74:48)
    at getRscError (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseRSC.js:88:78)
    at getModuleBuildError (/Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:122:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:21:49
    at async Promise.all (index 2)
    at async /Users/tubbo/Code/psychedeli.ca/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:19:21
Failed to compile.

./app/categories/[category]/page.tsx
Error: 
  × NEXT_RSC_ERR_CLIENT_METADATA_EXPORT: generateMetadata
    ╭─[/Users/tubbo/Code/psychedeli.ca/app/categories/[category]/page.tsx:9:1]
  9 │   }
 10 │ }
 11 │ 
 12 │ export function generateMetadata({ params }: Props) {
    ·                 ────────────────
 13 │   return {
 14 │     title: params.category,
 15 │   }
    ╰────

Import trace for requested module:
./app/categories/[category]/page.tsx
./app/ lazy ^.*$ referencedExports: default, metadata namespace object
./app/find-articles.ts
./app/sitemap.ts
./node_modules/next/dist/build/webpack/loaders/next-metadata-route-loader.js?page=%2Fsitemap.xml%2Froute&isDynamic=1!./app/sitemap.ts?__next_metadata_route__

./app/layout.tsx
Error: 
  × NEXT_RSC_ERR_CLIENT_METADATA_EXPORT: metadata
    ╭─[/Users/tubbo/Code/psychedeli.ca/app/layout.tsx:15:1]
 15 │   variable: '--font-rum-raisin',
 16 │ })
 17 │ 
 18 │ export const metadata: Metadata = {
    ·              ────────
 19 │   title: {
 20 │     template: `%s - ${process.env.NEXT_PUBLIC_TITLE}`,
 21 │     default: process.env.NEXT_PUBLIC_TITLE,
    ╰────

Import trace for requested module:
./app/layout.tsx
./app/ lazy ^.*$ referencedExports: default, metadata namespace object
./app/find-articles.ts
./app/sitemap.ts
./node_modules/next/dist/build/webpack/loaders/next-metadata-route-loader.js?page=%2Fsitemap.xml%2Froute&isDynamic=1!./app/sitemap.ts?__next_metadata_route__

./app/tags/[tag]/page.tsx
Error: 
  × NEXT_RSC_ERR_CLIENT_METADATA_EXPORT: generateMetadata
    ╭─[/Users/tubbo/Code/psychedeli.ca/app/tags/[tag]/page.tsx:9:1]
  9 │   }
 10 │ }
 11 │ 
 12 │ export function generateMetadata({ params }: Props) {
    ·                 ────────────────
 13 │   return {
 14 │     title: `#${params.tag}`,
 15 │   }
    ╰────

Import trace for requested module:
./app/tags/[tag]/page.tsx
./app/ lazy ^.*$ referencedExports: default, metadata namespace object
./app/find-articles.ts
./app/sitemap.ts
./node_modules/next/dist/build/webpack/loaders/next-metadata-route-loader.js?page=%2Fsitemap.xml%2Froute&isDynamic=1!./app/sitemap.ts?__next_metadata_route__


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tubbo** [comment]
The only way I've been able to get the error to stop is to remove `export const metadata = { .. }` and `export function generateMetadata({ params }) { ... }` from my code, which obviously just removes all the titles and stuff I set on each page.

This other issue I found seems to have the same problem: https://github.com/vercel/next.js/issues/47703

**Comment by nickmccurdy** [comment]
@austinlangdon Upgrade to at least `13.4.20-canary.16`, when this was [fixed](https://github.com/vercel/next.js/issues/47299#issuecomment-1705572928).

@tubbo Have you already upgraded?
