### ISSUE TITLE
Can't read body in any API method

### ISSUE THREAD

**Issue by imLymei** [vercel/next.js#50846]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/imLymei/nextjs-13.4.5-api-error

### To Reproduce

- Start the server with `npm run dev`
- Send a API POST request to `localhost:3000/api`(I used Postman) with a normal body: `{ "teste": 1 }` as JSON
- get `Error [TypeError]: Body is unusable` on console and a empty response 

### Describe the Bug

No matter what type of HTTP request is sent, the API routes can't receive a body. It sends an error of `Error [TypeError]: Body is unusable` and `NEXT_STATIC_GEN_BAILOUT` when trying to read it.

### Expected Behavior

The API sends back the body data from the response and logs it to the console.

### Which browser are you using? (if relevant)

Postman was used to send my API requests

**Comment by imLymei** [comment]
now my [original project](https://github.com/imLymei/js-imoveis-app) is sending this error:
```
error StaticGenBailoutError: Page with `dynamic = "error"` couldn't be rendered statically because it used `request.json`.
    at Object.staticGenerationBailout (webpack-internal:///(sc_server)/./node_modules/next/dist/client/components/static-generation-bailout.js:27:15)
    at handleReqBailout (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/helpers/proxy-request.js:93:23)
    at Object.get (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/helpers/proxy-request.js:101:13)
    at POST (webpack-internal:///(sc_server)/./src/app/api/users/route.ts:26:32)  
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:242:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:111:36)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NoopTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:953:34)
    at ProxyTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:993:36)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:100:107)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NextTracerImpl.trace (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:100:32)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:230:53)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:39:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:184:97)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/next/dist/server/async-storage/request-async-storage-wrapper.js:77:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:183:75)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AppRouteRouteModule.execute (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:180:56)
    at AppRouteRouteModule.handle (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:303:41)
    at RouteHandlerManager.handle (D:\__projects\nextjs\js-imoveis\node_modules\next\dist\server\future\route-handler-managers\route-handler-manager.js:28:29)      
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
    at async doRender (D:\__projects\nextjs\js-imoveis\node_modules\next\dist\server\base-server.js:936:38)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (D:\__projects\nextjs\js-imoveis\node_modules\next\dist\server\base-server.js:1162:28)  
    at async D:\__projects\nextjs\js-imoveis\node_modules\next\dist\server\response-cache\index.js:99:36 {
  code: 'NEXT_STATIC_GEN_BAILOUT'
}
```
but I am just sending an API request with a body.

**Comment by JesseKoldewijn** [comment]
Hey man, 
1. You're not testing against the latest canary release (as far as your repo goes).
2. The json function returns a promise which is the reason why it throws the error

To read the POST body you need to change your POST handler to the following:
```
export async function POST(request: Request) {
	const body = await request.json();
	console.log(body);

	return NextResponse.json({ response: body });
}
```

**Comment by JesseKoldewijn** [comment]
You were halfway there with the async function, you just needed to await the json convertion before returning it 👍

**Comment by imLymei** [comment]
I managed to solve that. The export settings don't work with the dynamic API routes. I don't know if it's an expected behavior or not, but thanks anyway. :)

**Comment by JesseKoldewijn** [comment]
Out of curiosity, what do you mean by "export settings"?

**Comment by imLymei** [comment]
The next.js setting to export the project to static files on `npm run build`
![image](https://github.com/vercel/next.js/assets/104811512/842e88e1-a0bb-4659-964e-39ffe51635a7)

**Comment by JesseKoldewijn** [comment]
Well api's aren't supported on expert because they require a runtime to function.
