### ISSUE TITLE
DELETE route in the app router causes: TypeError: Response body object should not be disturbed or locked

### ISSUE THREAD

**Issue by harryfoster** [vercel/next.js#51439]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 20.3.0
      npm: 8.18.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/harryfoster/delete-bug

### To Reproduce

Create a route.ts file, and create an empty DELETE function:

```
export async function DELETE(request: Request) {

}
```

Then test it with a basic curl. 

`curl -X DELETE -H "Content-Type: application/json" -d '{"id":1}' http://localhost:3000/api`

### Describe the Bug

- error TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:6155:17)
    at new Request (node:internal/deps/undici/undici:7081:48)
    at new NextRequest (/home/hfoster/scratch/delete-bug/node_modules/next/dist/server/web/spec-extension/request.js:32:9)
    at NextRequestAdapter.fromNodeNextRequest (/home/hfoster/scratch/delete-bug/node_modules/next/dist/server/web/spec-extension/adapters/next-request.js:38:16)
    at NextRequestAdapter.fromBaseNextRequest (/home/hfoster/scratch/delete-bug/node_modules/next/dist/server/web/spec-extension/adapters/next-request.js:20:35)
    at RouteHandlerManager.handle (/home/hfoster/scratch/delete-bug/node_modules/next/dist/server/future/route-handler-managers/route-handler-manager.js:26:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/home/hfoster/scratch/delete-bug/node_modules/next/dist/server/base-server.js:996:38)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/home/hfoster/scratch/delete-bug/node_modules/next/dist/server/base-server.js:1182:28)
    at async /home/hfoster/scratch/delete-bug/node_modules/next/dist/server/response-cache/index.js:99:36

### Expected Behavior

DELETE route should be able to call code without erroring. 

### Which browser are you using? (if relevant)

curl

### How are you deploying your application? (if relevant)

next dev

**Comment by rexfordessilfie** [comment]
Hi @harryfoster! I reproduced your issue and noticed you did not have a response as return which may have been an oversight. Could you try to see if it resolves your issue? 

Something like `return new Response("OK")` or `return NextResponse.json({...})`, at the end of your DELETE handler.

**Comment by harryfoster** [comment]
Yup, simply left it blank to show that it wasn't NextReponse or parsing the Request header that caused it. The rest of the methods when blank don't call this error. You can put almost anything inside the function and the same error will be called. 

Updated the repo to show a generic request straight from the docs:
https://nextjs.org/docs/app/building-your-application/routing/router-handlers#request-body 

```
import { NextResponse } from "next/server";

export async function DELETE(request: Request) {
    const res = await request.json();
    return NextResponse.json(res)
}
```

**Comment by princemuel** [comment]
Hi. I'm experiencing a similar issue with the delete request handler, but all the other request handlers with similar setup are working

```ts
 I'm making this request on the client
   const response = await fetch(`/api/resource/${id}`, {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
        });

And on the server at `resource/[id]/route.ts`
export async function DELETE(
  request: Request,
  { params }: { params: IParams }
) {
  console.log('PARAMS', params);
}
```

I've tried both using the `request object` like the OP above or using `params` like in my code example.
- When using the request object, it throws a malformed json response
 ```js
On the client
   const response = await fetch(`/api/resource`, {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JON.stringify({id})
        });

And on the server at `resource/route.ts`

export async function DELETE(
  request: Request,
) {
  const body = await request.json();
}
```

**Comment by harryfoster** [comment]
@princemuel Is the server throwing the same error? The server won't respond with anything that can be parsed as JSON, so the client will probably see it as malformed.

Discussion regarding this bug: #49524

Interestingly, it appears to affect versions [Version 13.2.5-canary.28](https://github.com/vercel/next.js/releases/tag/v13.2.5-canary.28) and upward.

**Comment by princemuel** [comment]
Hmm, I'm not sure why it's working, but I was able to resolve the issue by de-structuring the params object to retrieve the id instead of accessing the object directly

```js
const {id} = params // instead of params?.id
```

**Comment by harryfoster** [comment]
Closing issue.

**Comment by harryfoster** [comment]
Yes, I just re-wrote the API to utilise params for the delete method.
