### ISSUE TITLE
v13.4.6 started causing `Error: Cannot read properties of null (reading 'useContext')`

### ISSUE THREAD

**Issue by shehi** [vercel/next.js#51482]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.1
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

N/A

### To Reproduce

Unfortunately I can't share any code - my app is not open source.

I can give some points tho:

1. Not using `next/image` , Image Optimization.
2. Output = "standalone" (makes deployments smaller).
3. As you can see, apparently (somehow) error is happening inside `SWRConfig`. My layout and all providers are wrapped by `SWRConfig`.
4. Using React.Suspense almost everywhere I need suspense. Only 2 components use next/dynamic. Pretty sure these 2 components have no relation to the issue at hand.

### Describe the Bug

While my whole app is working quite flawlessly in NextJs v13.4.5, it broke once I upgraded to v13.4.6. The same error continues in the latest canary.

Following error started to popup across board:

```
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/var/www/.next/standalone/node_modules/react/cjs/react.production.min.js:24:118)
    at SWRConfig (file:///var/www/.next/standalone/node_modules/swr/_internal/dist/index.mjs:519:26)
    at Ge (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:114:273)
    at Z (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
    at Ge (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
    at Z (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
    at Ge (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:95)
    at Z (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
    at Ge (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:115:9)
    at Z (/var/www/.next/standalone/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:91)
```

This is happening only on `production` and only when I run app via `node server.js` instead of `npm start` (`standalone` output recommends the former). During `npm run dev` or `npm start` everything works fine.

### Expected Behavior

As in v13.4.5, I shouldn't be getting the aforementioned errors which only happen in v13.4.6.

### How are you deploying your application? (if relevant)

node start.js (`standalone` output)

**Comment by shuding** [comment]
Seems to be caused by the changes in https://github.com/vercel/next.js/pull/51172.

**Comment by huozhi** [comment]
@shehi Are you seeing errors in pages/ or app/?

**Comment by alexanbj** [comment]
@huozhi I just encountered this bug, in an app using `pages`. Downgrading to 13.4.5 fixed the issue for me.

**Comment by huozhi** [comment]
@alexanbj Thanks for provding the info, will investigate it asap

**Comment by Breuls** [comment]
I have the same problem, also solved by downgrading to 13.4.5. If another stacktrace helps, I'd be happy to post it, but it's basically the same as above, except for the third line (which refers to a different dependency).

**Comment by shehi** [comment]
`/pages`. Isn't `/apps` still a beta?

**Comment by Breuls** [comment]
I've got one right here: https://github.com/Breuls/next-issue-51482
