### ISSUE TITLE
Since bumping from 13.4.4 to 13.4.5 next dev broke

### ISSUE THREAD

**Issue by marcofranssen** [vercel/next.js#51861]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8-canary.5
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```
```


### Which area(s) of Next.js are affected? (leave empty if unsure)

_No response_

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/marcofranssen/nextjs-blog

### To Reproduce

The repo is private, but happy to give access to a maintainer to further troubleshoot / reproduce.

### Describe the Bug

When running `next dev` pages fail to load due to what it seems a webpack error. I'm using the app-dir for my entire pages. When running `next build && next start` all still works as expected. Bisecting my Git repo, the first commit that breaks is the dependabot merge that bumps next from `13.4.4` to `13.4.5`. Haven't noticed it earlier as `yarn build` and `yarn start` just works as expected.

```shell
$ yarn dev            
yarn run v1.22.19
$ next dev
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /Users/marco/code/priv/nextjs-blog/.env- event compiled client and server successfully in 4.9s (20 modules)
- wait compiling...
- wait compiling /blog/page (client and server)...
- error unhandledRejection: Error: Entry app-client-internals depends on main-app, but this entry was not found
    at Compilation.seal (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:101818)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:148814
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:99267
    at _next2 (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:25:1)
    at eval (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:52:1)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:305473
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at Object.each (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9608)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:305212
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at done (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9742)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9372
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:302404
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15876
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15437
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:536929
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15906
    at eval (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:30:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

The page just loads as usual in `yarn dev` mode. Using `yarn build && yarn start` all works.

### Which browser are you using? (if relevant)

Chromium 114.0.5735.133

### How are you deploying your application? (if relevant)

yarn dev

**Comment by marcofranssen** [comment]
Just want to confirm downgrading to `13.4.4` fixes the issue.

```
$ yarn add nextjs@13.4.4
$ yarn dev
…
…
And all works again as expected
…
…
…
```

**Comment by shuding** [comment]
Hi! The repo you linked is 404 for me, could you update it? Thanks.

**Comment by marcofranssen** [comment]
> Hi! The repo you linked is 404 for me, could you update it? Thanks.

Yes it is a private repo as mentioned in the issue. I can open it up for a maintainer that will look into the issue temporary

**Comment by marcofranssen** [comment]
This issue still persists on the latest release `13.4.8`. Opening the browser results in following error.

```shell
- error unhandledRejection: Error: Entry app-client-internals depends on main-app, but this entry was not found
    at Compilation.seal (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:101818)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:148814
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:99267
    at _next2 (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:16:1)
    at eval (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:42:1)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:305473
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at Object.each (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9608)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:305212
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at done (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9742)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9372
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:302404
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15876
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15437
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:536929
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15906
    at eval (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:30:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Downgrading back to `13.4.4` resolves the issue and everything continues to work.

Please let me know who will look into the issue and I will add you to my repo.

**Comment by 3dln** [comment]
Same problem here (13.4.9)

- error unhandledRejection: Error: Entry app-client-internals depends on main-app, but this entry was not found
    at Compilation.seal (/Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:101818)
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:148814
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:99267
    at _next2 (eval at create (/Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:16:1)
    at eval (eval at create (/Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:42:1)
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:305473
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at Object.each (/Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:9608)
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:305212
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at done (/Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:9742)
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:9372
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:302404
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:15876
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:15437
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:536929
    at /Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:15906
    at eval (eval at create (/Users/mac/projects/catgpt/front/node_modules/.pnpm/next@13.4.9_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:30:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by marcofranssen** [comment]
Tried again with 13.4.10. Still same issue.

```shell
- error unhandledRejection: Error: Entry app-client-internals depends on main-app, but this entry was not found
    at Compilation.seal (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:101818)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:148814
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:99267
    at _next2 (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:16:1)
    at eval (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:42:1)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:305473
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at Object.each (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9608)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:305212
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9430
    at done (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9742)
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/neo-async/async.js:1:9372
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:302404
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15876
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15437
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:536929
    at /Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:28:15906
    at eval (eval at create (/Users/marco/code/priv/nextjs-blog/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:30:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

@timneutkens I noticed you got the access, have been able to find the culprit? The 2 other invitations for your colleagues expired.

**Comment by ztanner** [comment]
Hey @marcofranssen -- I took a look and identified the offending line to be the custom webpack config (the `generateAppDirEntry`). Removing this line resolves the issue as later versions of Next changed how entrypoints are generated (x-ref: https://github.com/vercel/next.js/pull/50379).

It seems like `next-pwa` doesn't support appDir, but there are some forks of the library that may work better if you were having trouble integrating it (https://github.com/shadowwalker/next-pwa/issues/482)

**Comment by marcofranssen** [comment]
> Hey @marcofranssen -- I took a look and identified the offending line to be the custom webpack config in your `next.config.js` (the `generateAppDirEntry`). Removing this line resolves the issue as later versions of Next changed how entrypoints are generated (x-ref: https://github.com/vercel/next.js/pull/50379).
> 
> 
> 
> It seems like `next-pwa` doesn't support appDir, but there are some forks of the library that may work better if you were having trouble integrating it (https://github.com/shadowwalker/next-pwa/issues/482) 

Will check as soon I'm back from my vacation. Thanks for this. Would be great if the stack traces would be more clear to figure these kind of things out.

**Comment by marcofranssen** [comment]
I have switched to a fork of next-pwa and removed the custom webpack config. This indeed solved it for me. Now running nextjs 13.4.13. 🤞

**Comment by timneutkens** [comment]
Going to close this issue then 👍
