### ISSUE TITLE
"RangeError: WebAssembly.instantiate(): Out of memory: wasm memory" when using environment with limited virtual memory

### ISSUE THREAD

**Issue by IoanStoianov** [vercel/next.js#51870]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
/app # npx next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Thu May 25 07:17:40 UTC 2023
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.3
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0

/app # ulimit -a 
core file size (blocks)         (-c) 0
data seg size (kb)              (-d) unlimited
scheduling priority             (-e) 0
file size (blocks)              (-f) unlimited
pending signals                 (-i) 63574
max locked memory (kb)          (-l) 82000
max memory size (kb)            (-m) 2048000
open files                      (-n) 1048576
POSIX message queues (bytes)    (-q) 819200
real-time priority              (-r) 0
stack size (kb)                 (-s) 8192
cpu time (seconds)              (-t) unlimited
max user processes              (-u) unlimited
virtual memory (kb)             (-v) 2048000
file locks                      (-x) unlimited
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/IoanStoianov/limited-virtual-memory-nextjs/tree/main

### To Reproduce

Clone the `limited-virtual-memory-nextjs` and follow the Readme

Local:
1. Limit the virtual memory of your environment. I tried it on docker image `node:16.20.0-alpine` - `ulimit -v 2048000`
2. Install version higher than 13.3.3
3. Run `npx next info`
4. Get: `RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
    at lazyllhttp (node_modules/next/dist/compiled/undici/index.js:1:55249)`

### Describe the Bug

This behavior happens when I upgrade to a version higher than 13.3.3. I cannot run even `npx next info`

### Expected Behavior

To be able to perform next commands on environment with limited virtual memory

### How are you deploying your application? (if relevant)

I deployed the app on my client's cPanel

**Comment by Kraktoos** [comment]
Getting the same issue with cPanel

**Comment by omarqra** [comment]
i am having the same problem with v13.5.3

**Comment by Kraktoos** [comment]
> i am having the same problem with v13.5.3 on cpanel, when running build on Linux server :
> `unhandledRejection RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
> at lazyllhttp (eval at requireWithFakeGlobalScope (/home2/jeventeventreg/jevent-client/node_modules/next/dist/compiled/@edge-runtime/primitives/load.js:65:3), <anonymous>:9988:32)`
> even though the server have alot of memory.
> @Kraktoos do you manage to solve this problem ?

Yeap, I downgraded some package versions. Here is a part of our updated package.json. The duplicate packages mean that the first one is the old one that didn't work and the latter one the one that fixed it. I don't know which specific package didn't work so that is why I'm sending this commit changes. Hope this helps.

"dotenv": "^16.3.1", "drizzle-orm": "^0.28.6", "eslint": "^8.49.0", "eslint-config-next": "^13.4.19", "eslint-config-next": "^12.0.4", "formidable": "^3.5.1", "ftp": "^0.3.10", "jsftp": "^2.1.3", "jsx-runtime": "^1.2.0", "lucide-react": "^0.277.0", "mysql2": "^3.6.1", "net": "^1.0.2", "next": "^13.4.19", "next": "13.4.8", "next-auth": "^4.23.1", "next-intl": "^2.20.0", "next-themes": "^0.2.1",@@ -72,11 +72,11 @@ "postcss": "8.4.29", "promise": "^8.3.0", "radix-ui": "^1.0.1", "react": "^18.2.0", "react": "18.2.0", "react-apexcharts": "^1.4.1", "react-chartjs-2": "^5.2.0", "react-day-picker": "^8.8.2", "react-dom": "^18.2.0", "react-dom": "18.2.0", "react-email": "^1.9.4", "react-parallax-tilt": "^1.7.166", "shadcn-ui": "^0.3.0",

**Comment by omarqra** [comment]
> > i am having the same problem with v13.5.3 on cpanel, when running build on Linux server :
> > `unhandledRejection RangeError: WebAssembly.instantiate(): Out of memory: wasm memory at lazyllhttp (eval at requireWithFakeGlobalScope (/home2/jeventeventreg/jevent-client/node_modules/next/dist/compiled/@edge-runtime/primitives/load.js:65:3), <anonymous>:9988:32)`
> > even though the server have alot of memory.
> > @Kraktoos do you manage to solve this problem ?
> 
> Yeap, I downgraded some package versions. Here is a part of our updated package.json. The duplicate packages mean that the first one is the old one that didn't work and the latter one the one that fixed it. I don't know which specific package didn't work so that is why I'm sending this commit changes. Hope this helps.
> 
> "dotenv": "^16.3.1", "drizzle-orm": "^0.28.6", "eslint": "^8.49.0", "eslint-config-next": "^13.4.19", "eslint-config-next": "^12.0.4", "formidable": "^3.5.1", "ftp": "^0.3.10", "jsftp": "^2.1.3", "jsx-runtime": "^1.2.0", "lucide-react": "^0.277.0", "mysql2": "^3.6.1", "net": "^1.0.2", "next": "^13.4.19", "next": "13.4.8", "[next-auth](https://linear.app/vercel/issue/NEXT-auth)": "^4.23.1", "[next-intl](https://linear.app/vercel/issue/NEXT-intl)": "^2.20.0", "[next-themes](https://linear.app/vercel/issue/NEXT-themes)": "^0.2.1",@@ -72,11 +72,11 @@ "postcss": "8.4.29", "promise": "^8.3.0", "radix-ui": "^1.0.1", "react": "^18.2.0", "react": "18.2.0", "react-apexcharts": "^1.4.1", "react-chartjs-2": "^5.2.0", "react-day-picker": "^8.8.2", "react-dom": "^18.2.0", "react-dom": "18.2.0", "react-email": "^1.9.4", "react-parallax-tilt": "^1.7.166", "shadcn-ui": "^0.3.0",

it didn't work for my, its give me `aborted (core dumped)`  which look like it it's memory issues with node on Linux

**Comment by tjmosia** [comment]
I am experiencing the exact same issue: 

Detected configuration files

stderr:
undefined:9972
      return await WebAssembly.instantiate(mod, {
                               ^

RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
    at lazyllhttp (eval at requireWithFakeGlobalScope (/home/motocoil/nodevenv/app/webapp/18/lib/node_modules/next/dist/compiled/@edge-runtime/primitives/load.js:64:3), <anonymous>:9972:32)

Node.js v18.16.1

**Comment by deoobordoicao** [comment]
#Hello guys I am really new to this technology Next.js . But I hope that these information will help you solve the issue.
##  check the free memory in linux: free-h
##  memory usage: cat /proc/meminfo
##  if it has still a lot then run : node --max-old-space-size=4096 index.js or node --max-old-space-size=4096 server.js
##  it depends on how you name it inside the app, and try to increase the size if you have still enough memory
##  Remove unnecessary files inside the File Manage, but be careful to do it.
##  Change the port number in next.config.js 
#    Try this: npm run start, npm run dev, npm next start.  These commands are recorded in my terminal.
#    But the funny this is the I really focus os much of my time in C language using GTK and I enjoyed it.
## Thank you so much guys!  Node.js v18.18.2

**Comment by 1w4nkx** [comment]
hi, i have same issue.
any update/idea to solve this issue?

i'm using CPanel with storage 4GB and 1GB memory (1core).

am i need to upgrade my cpanel? if yes, how about storage 8GB and 2GB memory(2core)

**Comment by IoanStoianov** [comment]
Sadly my workaround was to export my next.js app as a static page which I served with a standard express app. The drawback of my approach was that I couldn't use the benefits of the serverside components, caching, etc ...

**Comment by imvad** [comment]
We have this issue when on rocky linux as well.

**Comment by 0xrinegade** [comment]
helpm im stuck too

**Comment by AbuBakkarSiddiqueAnir** [comment]
I am stuck on the issues for last three days, anyone got any workaround without downgrading the packages..!!

**Comment by AbuBakkarSiddiqueAnir** [comment]
> I am stuck on the issues for last three days, anyone got any workaround without downgrading the packages..!!

this problem isn't showing till 12.3.4 ... when it is at 13.0.0, the nextjs taking much of memory to run

**Comment by yas1nshah** [comment]
any fix guys?
i had been working on this app for months and now i cant even deploy it on a shared hosting (c-panel) it has 4GB Ram which is more than enough ig.
![image_2024-02-08_182203962](https://github.com/vercel/next.js/assets/117914394/4eab2129-271a-42d3-b843-b5ef9b043b54)

  if anyone has any workaround do let me know

**Comment by AbuBakkarSiddiqueAnir** [comment]
> any fix guys?
> i had been working on this app for months and now i cant even deploy it on a shared hosting (c-panel) it has 4GB Ram which is more than enough ig.
> ![image_2024-02-08_182203962](https://github.com/vercel/next.js/assets/117914394/4eab2129-271a-42d3-b843-b5ef9b043b54)
> 
>   if anyone has any workaround do let me know

I worked around with that issue by downgrading the app 12.3.4 😶.

**Comment by yas1nshah** [comment]
downgraded to v12? then it wont use the app router and other next features. in that case Next Js is useless to me.

**Comment by Rehab-Osman** [comment]
Build app before deploy to server and delete .next folder on server before deploy the new one after build.
 also u need to increase "max_execution_time" to make your app load fast

**Comment by Maraoui21** [comment]
same issue here

**Comment by aghamohammadi** [comment]
In version 13.5.6, it worked for me, definitively!!!
After testing various methods, I finally resolved the memory error issue RangeError: WebAssembly.instantiate(): Out of memory: wasm memory using this approach.

1- To deploy, don't fetch the app build from the cpanel terminal. Instead, obtain it locally and upload the .next folder to the cpanel host. Otherwise, the memory error persists.

2- Note that if your local operating system is Windows and you've built the Next.js app on a Windows system, the built version won't work on a Linux cpanel host. You'll need Docker assistance.

3- First, run the app on Docker, then extract the .next folder from the Docker image to your local system. Upload the .next folder to the cpanel host, and you'll see the site running smoothly.

4- Here's a simple Dockerfile for creating a Docker image:

```dockerfile
FROM node:20.9.0

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
COPY . .

RUN npm run build

CMD ["npm", "start"]
``` 

5- Build the image in CMD:
```shell
docker build -t nextjs-sample .
``` 

6- Extract the .next folder from the Docker image. Pay attention to the paths; the first path is for Docker, the second for extraction on the local system, and container_id is the container code,  in CMD.
```shell
docker cp [container_id]:/usr/src/app/build /output
``` 
7- Upload ".next" folder to cpanel host

**Comment by Mem0Real** [comment]
After pulling my hair out for so long, I managed to fix it. The above method sort of works (docker containerization) if you don't have to generate any specific env dependent outputs and is a bit cumbersome to do the whole process whenever you change something so this is how I went about it. I downloaded putty software to access the terminal from my pc. Follow this guide to achieve that. [https://youtu.be/uP7Vo_tUAjs?si=rpQxmi3HR2K9HHqW](url)

**Comment by Pushpendra160** [comment]
I am trying to host my next js app (having app router )on  panel , it is giving me same error, I even upgraded the server ram from 4 gb to 32 gb then too it is showing me same error, 
my server os is Alma linux.
can anybody help me in this?

**Comment by Rehab-Osman** [comment]
@Pushpendra160 
 Where do u deploy it? shard host or VPS host
 after trying many 100 times I can not deploy my project with (node js app through cPanel), I changed my host from shared to VPS and deploy it on home folder through FileZilla then build and start it with ssh connection, same way exactly as u did on local 

it working like charm

**Comment by ByAnthony** [comment]
Managed to deploy a Next.js 14.2.4 app to CPanel through GitHub Actions. Got a [wee guide](https://github.com/ByAnthony/newzealandtunnellers/blob/main/docs/deployment.md); hopefully that helps 🙏

**Comment by Shoyas** [comment]
> Managed to deploy a Next.js 14.2.4 app to CPanel through GitHub Actions. Got a [wee guide](https://github.com/ByAnthony/newzealandtunnellers/blob/main/docs/deployment.md); hopefully that helps 🙏

I've followed your guideline without Image optimization and GitHub action, but I can't solve the "RangeError: WebAssembly.instantiate()" error.

next.config.mjs file without Image optimization:
==============================
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
      unoptimized: true,
  },
  };
  export default nextConfig;
```
  ===================

Before I've deployed NextJs projects on cPanel with shared hosting of another service provider. There was no issue for deployment. But That version was 14.1.0

Now My project is Next.js 14.2.4 version.
This build project is working perfectly in locally/on my PC (production mood). When I run this on my Shared cPanel. Then, I got the "RangeError: WebAssembly.instantiate()" error.
Can you help me?

**Comment by ByAnthony** [comment]
Hi @Shoyas 👋 Do you deploy via github actions? How do you restart your app?

**Comment by ikaz-jem** [comment]
if you have a whm server SSH and just install to that specific CPAnel user and it will work

**Comment by ikaz-jem** [comment]
also u can try to install other node versions 18 will work here :
![1](https://github.com/user-attachments/assets/56d0b72b-f01b-4565-88c4-38ca98ca7d91)

uninstalled v20 and installed v18 and works perfectly :
![2](https://github.com/user-attachments/assets/081f00c4-abce-4d95-b343-1cf2a58ce3d3)

**Comment by Shoyas** [comment]
After using Next.js [v14.1.4], I can deploy easily on shared hosting.
Then I understand that some of the latest versions are not capable of deploying on shared hosting.

**Comment by maestroyaco** [comment]
Error: ![Image](https://github.com/user-attachments/assets/e0f10dff-b013-4032-ac90-bc528b615749)

Hello. I had the same problem with Cpanel. Doing a little research. I discovered that the problem is in the cpanel terminal, which has certain limitations. So the solution for 2025 is to configure SSH access using putty, so you can use a terminal without limitations like cpanel. Here is the evidence that it works.

![Image](https://github.com/user-attachments/assets/ea051bfd-1c66-4147-a3d5-bba5d49a5dcd)

My Hosting is shared and only has 2 memory for my plan. With SSH access through putty I was able to solve the memory problem, which was really the memory of the Cpanel terminal and not my hosting.

**Comment by kane81** [comment]
@maestroyaco 

When I start via putty SSH, it starts fine, but I cannot access the website publicly. When it is started via NodeJS cpanel <Start App> button, it automatically links /proxy the app to public with https certificate etc.  Any idea how to link app started via SSH to be available publicly / kick off the proxy?

**Comment by TCLJOHANT** [comment]
si a sabiendas de esos limites de los compartido toca por sh correr los trabajos o scripst que requieren mas recursos pero sin abusar.

**Comment by AhmedHHamdy** [comment]
> Error: ![Image](https://github.com/user-attachments/assets/e0f10dff-b013-4032-ac90-bc528b615749)
> 
> Hello. I had the same problem with Cpanel. Doing a little research. I discovered that the problem is in the cpanel terminal, which has certain limitations. So the solution for 2025 is to configure SSH access using putty, so you can use a terminal without limitations like cpanel. Here is the evidence that it works.
> 
> ![Image](https://github.com/user-attachments/assets/ea051bfd-1c66-4147-a3d5-bba5d49a5dcd)
> 
> My Hosting is shared and only has 2 memory for my plan. With SSH access through putty I was able to solve the memory problem, which was really the memory of the Cpanel terminal and not my hosting.

This worked for me thank you so much

**Comment by Parviz-Elite** [comment]
I discussed this with my hosting support team. In my case, the root cause was a cPanel/CloudLinux memory limit affecting the Git deployment process.

I’m running a Laravel + Vite build on a dedicated server using cPanel Git Deploy and Node.js 22. **Increasing the Max cPanel process memory** resolved the WebAssembly.instantiate(): Out of memory error during the build.

**Comment by marcoshernanz** [comment]
Thanks everyone for the additional reports. I reproduced the original `next info` regression under `ulimit -v 2048000`, including the Next.js 13.3.3 to 13.4.0 boundary. The same `lazyllhttp` failure occurs with a plain Node `fetch()` and no Next.js, confirming that it comes from Node/V8's WebAssembly virtual-memory reservation.

On Node.js 20.15+ or 22.2+, set `NODE_OPTIONS=--disable-wasm-trap-handler` or ask the hosting provider to raise the process virtual-memory limit. Node.js 24.19+ handles this low-limit case automatically. Since the original Next.js and Node.js versions are unsupported and the remaining behavior is controlled by Node and the hosting environment, we are closing this issue.
