### ISSUE TITLE
TypeError: Cannot redefine property: default in 13.4.8 when used with Storybook

### ISSUE THREAD

**Issue by manuelbieh** [vercel/next.js#52246]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020
Binaries:
  Node: 18.16.0
  npm: 9.3.1
  Yarn: 1.22.19
  pnpm: 8.6.6
Relevant Packages:
  next: 13.4.9-canary.2
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/manuelbieh/next-storybook-error

### To Reproduce

```
git clone git@github.com:manuelbieh/next-storybook-error.git
cd next-storybook-error
yarn
yarn storybook:start
```
Open localhost:6006 in your browser (if not opened automatically).

### Describe the Bug

After upgrading from next 13.4.7 to 13.4.8 our Storybook is not working anymore. That's why I am opening the issue here and not in the Storybook repo. Feel free to close it if you think this issue should be opened in the Storybook repo. 

When I start Storybook as usual `yarn storybook:start`, Storybook builds successfully but in the browser I get the following error:
```
TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at ./node_modules/@storybook/nextjs/dist/preview.js (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_asyncToGenerator_js-node_modules_babel_runtime_hel-2878f5.iframe.bundle.js:18448:6999)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:314:25)
    at Object.getProjectAnnotations [as nextFn] (http://localhost:6006/main.iframe.bundle.js:4847:75)
    at http://localhost:6006/sb-preview/runtime.js:4:78234
    at Array.forEach (<anonymous>)
    at SynchronousPromise4._runResolutions (http://localhost:6006/sb-preview/runtime.js:4:78175)
    at SynchronousPromise4.then (http://localhost:6006/sb-preview/runtime.js:4:75717)
    at PreviewWeb.getProjectAnnotationsOrRenderError (http://localhost:6006/sb-preview/runtime.js:74:13216)
```

This did not happen in 13.4.7.

// update:

I checked the different canary releases and it looks like it's still working in `13.4.8-canary.8` and first happens in `13.4.8-canary.9`.

### Expected Behavior

Storybook should open and show stories as usual.

### Which browser are you using? (if relevant)

114.0.5735.198 (Official Build) (arm64)

**Comment by roottool** [comment]
[Storybook v7.0.26](https://github.com/storybookjs/storybook/releases/tag/v7.0.26) has released. This issue is fixed by this release👍

**Comment by manuelbieh** [comment]
Can confirm, thank you! 👍
