### ISSUE TITLE
Url which contain several locales have strange behaviour

### ISSUE THREAD

**Issue by oleggrishechkin** [vercel/next.js#52314]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Internationalization (i18n), Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/tender-shannon-ykkmm6?file=%2Fmiddleware.ts%3A4%2C1

### To Reproduce

1. Open /en/fr url
2. Check middleware log

### Describe the Bug

When /en/fr (or similar url with two locales) next resolve locale incorrect in middleware and 404 page shown incorrectly. I have a `Error: Invariant: The detected locale does not match the locale in the query. Expected to find 'fr' in '/en/fr' but found 'en'}` in my case, in CodeSendbox reproduction hard navigate error caused. Middleware logs "/en/fr" with "fr" locale.

### Expected Behavior

404 page should be shown with "en" locale (first part of the url) without errors
Middleware shoud log "/fr" pathname with "en" locale

**Comment by koennjb** [comment]
I am also running into the same issue. I have explicitly set `localeDetection: false` in `next.config.js` but given the error message it seems like it is still attempting to detect the locale.

**Path:** `/es/en`
**default locale:** `en`

**Error:**
```
Invariant: The detected locale does not match the locale in the query. Expected to find 'en' in '/es/en' but found 'es'
```

### Environment Information
```
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Jul 12 20:29:40 UTC 2023
    Binaries:
      Node: 18.16.1
      npm: 6.14.17
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

Also in case it makes a difference, this app is running in a custom Express server.

**Comment by davidhoeck** [comment]
Any update on that?

**Comment by gabrielf** [comment]
I got this error in a largish next-application when switching between git branches where different locales were active with next 13.4.2. Upgrading  to 13.5.6 solved the problem. However I couldn't reproduce the error in a minimal next-application even on 13.4.2…

**Comment by psoaresbj** [comment]
I am having the same issue. On dev mode, it returns a 404, if that `/:lang1/:lang2` page doesn't exist (expected behaviour) but if I build and run start, it sets the lang as lang2 and returns the page for lang1 (with a catch all [...page]).

**Comment by federicocappellotto97** [comment]
Same problem here
This is my middleware
```
 if (req.nextUrl.locale === 'default') {
        let locale = process.env.DEFAULT_LOCALE!

        if (
            req.cookies.get('NEXT_LOCALE')?.value &&
            process.env.LOCALES!.split(',').includes(req.cookies.get('NEXT_LOCALE')!.value)
        ) {
            locale = req.cookies.get('NEXT_LOCALE')!.value
        }
        return NextResponse.redirect(new URL(`/${locale}${req.nextUrl.pathname}${req.nextUrl.search}`, req.url))
    }
    ```
    
    If i go to /it/en i got "Error: Invariant: The detected locale does not match the locale in the query. Expected to find 'it' in '/en' but found 'en'}"

**Comment by toviszsolt** [comment]
I have the same problem with the following url for example: `http://localhost:3015/hu-HU/en-US"`, using `Page Router`

**Related config:**
```js
module.exports = {
  i18n: {
    locales: ['default', 'hu-HU', 'en-US'],
    defaultLocale: 'default',
  }
}
```

**The error log might help:**
```bash
 ⨯ Error: Invariant: The detected locale does not match the locale in the query. Expected to find 'hu-HU' in '/en-US' but found 'en-US'}
    at I18NProvider.fromQuery (*removed*\node_modules\next\dist\server\future\helpers\i18n-provider.js:70:27)
    at NextNodeServer.handleCatchallRenderRequest (*removed*\node_modules\next\dist\server\next-server.js:225:106)
    at DevServer.handleRequestImpl (*removed*\node_modules\next\dist\server\base-server.js:807:28)
    at async *removed*\node_modules\next\dist\server\dev\next-dev-server.js:331:20
    at async Span.traceAsyncFn (*removed*\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (*removed*\node_modules\next\dist\server\dev\next-dev-server.js:328:24)
    at async invokeRender (*removed*\node_modules\next\dist\server\lib\router-server.js:163:21)
    at async handleRequest (*removed*\node_modules\next\dist\server\lib\router-server.js:342:24)
    at async requestHandlerImpl (*removed*\node_modules\next\dist\server\lib\router-server.js:366:13)
    at async Server.requestListener (*removed*\node_modules\next\dist\server\lib\start-server.js:140:13)
```

**Next Info:**
```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: * not relevant *
Binaries:
  Node: 18.18.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

**Comment by lipoolock** [comment]
Hello @timneutkens 

I would like to raised up this topic again because I'm facing the same issue with the `13.5.6` version of NextJs
I created a sandbox to help you understanding the context of this 
https://codesandbox.io/p/devbox/distracted-bouman-y6rzfc

If you type in URL `/en/fr` for instance, you'll get the error reported above
![image](https://github.com/vercel/next.js/assets/42861634/f87fd02e-522b-4267-9d1e-4fb3ac835dcb)

Could we have a chance that some of you take time to investigate what is wrong either in config or in core of NextJs ?

PS: I have currently no way to upgrade to `14` version, then I would be happy if a patch can be provided for the `13.5.x` version

Thanks a lot for help

**Comment by kirill-zhirnov** [comment]
Hello,
I have the same bug, Next v13. I made patch which works for me:

Add `middleware.ts`:

```ts
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const regExpForBuggyUrls = /^\/(en|de|fr)\/(en|de|fr)\/.*/i;

export function middleware(request: NextRequest) {
  /**
   * If an URL has double langs in the URL it leads to 500 error,
   * e.g.: /fr/de/outil-de-valorisation/fr-discover-how-essential-it-is-to-present-your-business-in-a-compelling-manda-equity-story/
   *
   * It is a known bug:
   * https://github.com/vercel/next.js/issues/52314
   * https://github.com/vercel/next.js/issues/52316
   */
  const pathname = new URL(request.url).pathname;
  const result = pathname.match(regExpForBuggyUrls);

  if (result !== null) {
    return NextResponse.redirect(new URL('/not-found', request.nextUrl))
  }

  return NextResponse.next();
}

```

Thx

**Comment by jlalmes** [comment]
Same issue, would ideally not need to write a middlewares for all our apps just so we can upgrade beyond next version `13.0.2`.

**Comment by jlalmes** [comment]
Related PR: https://github.com/vercel/next.js/issues/65167

**Comment by marcoshernanz** [comment]
Verified on `16.4.0-canary.0`: `/en/fr` keeps `en` as the locale, passes `/fr` to middleware, and renders the localized 404 without the invariant error. The related catch-all case is also fixed after #94157. Closing as resolved. Thanks for the report!
