### ISSUE TITLE
Cannot run even a fresh Next.js build.

### ISSUE THREAD

**Issue by Repith** [vercel/next.js#52322]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise LTSC 2019
    Binaries:
      Node: 20.4.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/tree/canary/examples/reproduction-template

### To Reproduce

Using GIT Bash as a shell:
npx create-next-app@latest
Followed thorugh the instalation process.
npm run dev

### Describe the Bug

I got problems with favicon, googlefonts, and the latest bug is:

```sh
Error: Cannot find module '../../../Project  #1/my-app/node_modules/next/dist/shared/lib/constants.js'
Require stack:
- C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\pages\_document.js
- C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\require.js
- C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\next-server.js
- C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\dev\next-dev-server.js
- C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\next.js
- C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\lib\render-server.js
- C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\compiled\jest-worker\processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\require-hook.js:189:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at ../shared/lib/constants (C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\pages\_document.js:82:18)
    at __webpack_require__ (C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\webpack-runtime.js:33:42)
    at eval (eval at ../../Project  #1/my-app/node_modules/next/dist/pages/_document.js (C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\pages\_document.js:42:1), <anonymous>:33:20)
    at ../../Project  #1/my-app/node_modules/next/dist/pages/_document.js (C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\pages\_document.js:42:1)
    at __webpack_require__ (C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\pages\_document.js:122:39)
    at C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\pages\_document.js:123:28
    at Object.<anonymous> (C:\Users\Thiper\Desktop\Project #1\my-app\.next\server\pages\_document.js:126:3)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at requirePage (C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\require.js:156:12)
    at C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\load-components.js:67:65
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async loadComponentsImpl (C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\load-components.js:66:33)
    at async DevServer.findPageComponentsImpl (C:\Users\Thiper\Desktop\Project #1\my-app\node_modules\next\dist\server\next-server.js:772:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Thiper\\Desktop\\Project #1\\my-app\\.next\\server\\pages\\_document.js',
    'C:\\Users\\Thiper\\Desktop\\Project #1\\my-app\\node_modules\\next\\dist\\server\\require.js',
    'C:\\Users\\Thiper\\Desktop\\Project #1\\my-app\\node_modules\\next\\dist\\server\\next-server.js',
    'C:\\Users\\Thiper\\Desktop\\Project #1\\my-app\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js',
    'C:\\Users\\Thiper\\Desktop\\Project #1\\my-app\\node_modules\\next\\dist\\server\\next.js',
    'C:\\Users\\Thiper\\Desktop\\Project #1\\my-app\\node_modules\\next\\dist\\server\\lib\\render-server.js',
    'C:\\Users\\Thiper\\Desktop\\Project #1\\my-app\\node_modules\\next\\dist\\compiled\\jest-worker\\processChild.js'
  ]
}
```

### Expected Behavior

Just... want to install it and run. 
It's a fresh problem.
Reinstalled node, npm, deleted cache, tried everything...

### Which browser are you using? (if relevant)

Chrome 114.0.5735.199

**Comment by balazsorban44** [comment]
I confirmed, naming the directory `Project  #1` reproduced the issue. The problem seems to be the `#` character.

**Comment by Repith** [comment]
> 

This WAS that easy... after 5 hours of reinstalling everything it's done... Thanks a lot <3
