### ISSUE TITLE
`@vercel/og` does not accept a function as a child (`<Foo>{() => 'bar'}</Foo>`)

### ISSUE THREAD

**Issue by klaasman** [vercel/next.js#52394]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/serene-mclean-27v4mn?file=%2Fapp%2Froute.tsx%3A18%2C1-23%2C79

### To Reproduce

1. go to https://codesandbox.io/p/sandbox/serene-mclean-27v4mn?file=%2Fapp%2Froute.tsx%3A18%2C1-23%2C79
2. see an image being served with the text "Hello from renderProp"
3. Uncomment one of the broken test cases in the file `/app/route.tsx`
4. reload image
5. it won't load

### Describe the Bug

The ﻿`@vercel/og` library does not support using a function as children in both the `﻿/app` and `﻿/pages/api` directories.

❌ For example this won't work:
```
<Test>{() => <p>Hello from children() as child</p>}</Test>
```

❌ Assigning `children` as a prop also doesn't work:
```
<Test children={() => <p>Hello from children() as prop</p>} />
```

✅ Any other prop does work:
```
<Test renderProp={() => <p>Hello from renderProp()</p>} />
```

The following error is thrown:

```
error unhandledRejection: Error [TypeError]: Cannot read properties of undefined (reading 'children')
    at n (file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:15039:29)
    at n (file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:15039:77)
    at file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:15039:69
    at Array.map (<anonymous>)
    at n (file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:15039:58)
    at pu (file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:15042:10)
    at xl (file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:17132:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async render (file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:18709:15)
    at async Object.start (file:///workspace/node_modules/next/dist/compiled/@vercel/og/index.node.js:18753:25) {
  digest: undefined
}
```

### Expected Behavior

With  `@vercel/og` I expect to be able to use functions as children.

**Comment by shuding** [comment]
Yep this is an upstream issue on Satori’s side, will close this and track there.
