### ISSUE TITLE
Brand new project throws "Cannot read properties of null (reading 'useContext')"

### ISSUE THREAD

**Issue by jdcodes1** [vercel/next.js#52478]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jdcodes1/nextjstest/tree/main

### To Reproduce

Create new project with `npx create-next-app@latest`, `next build` to see the error.

I've tried upgrading and downgrading versions of `next` and `react`, to no avail.

I also made sure it still reproduces on the canary, as well as most recent versions.

### Describe the Bug

"Generating static pages (0/4)TypeError: Cannot read properties of null (reading 'useContext')
at exports.useContext (node_modules/react/cjs/react.production.min.js:24:118)
at Head (.next/server/chunks/259.js:325:44)

Also getting errors from ErrorBoundary:
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (node_modules/next/dist/compiled/react/cjs/react.production.min.js:28:118)
    at usePathname (.next/server/chunks/580.js:1650:34)
    at ErrorBoundary (.next/server/chunks/580.js:975:50)

### Expected Behavior

No error is thrown, able to run dev/prod and build (`next build` successfully)

### Which browser are you using? (if relevant)

Chrome 114.0.5735.198

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
I could not reproduce this. A common issue is that if you have a global `react` installed, or you are creating this project inside another one, and your package manager is trying to resolve to the wrong version.

**Comment by asmehra** [comment]
I am also getting **same error** while setting up a new nextjs project. Any solutions?

**Comment by jdcodes1** [comment]
Unfortunately not, this thread also appears to have the same issue with no clear resolution: https://github.com/vercel/next.js/discussions/43577. I've tried changing react/next/dom package versions to no avail 😢

**Comment by jdcodes1** [comment]
> I am also getting **same error** while setting up a new nextjs project. Any solutions?

Unfortunately not, this thread also appears to have the same issue with no clear resolution: https://github.com/vercel/next.js/discussions/43577. I've tried changing react/next/dom package versions to no avail 😢

**Comment by gpolis** [comment]
Same error for me as well.. but only for one route

TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/app/node_modules/next/dist/compiled/react-experimental/cjs/react.production.min.js:30:49)
    at usePathname (/app/.next/server/chunks/23.js:1494:34)

**Comment by Abayoh** [comment]
I am also experiencing the same error

This is from the layout I say hi
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/app/node_modules/next/dist/compiled/react-experimental/cjs/react.production.min.js:30:49)
    at usePathname (/app/.next/server/chunks/114.js:1499:34)
    at ErrorBoundary (/app/.next/server/chunks/114.js:813:50)
    at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:117:273)
    at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
    at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:118:9)
    at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:11)
    at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
    at kg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
    at mg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:126:289)

**Comment by Abayoh** [comment]
I am also experiencing the same error

TypeError: Cannot read properties of null (reading 'useContext')
at exports.useContext (/app/node_modules/next/dist/compiled/react-experimental/cjs/react.production.min.js:30:49)
at usePathname (/app/.next/server/chunks/114.js:1499:34)
at ErrorBoundary (/app/.next/server/chunks/114.js:813:50)
at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:117:273)
at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:118:9)
at jg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:123:11)
at Z (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:124:91)
at kg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:127:155)
at mg (/app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.production.min.js:126:289)

**Comment by Abayoh** [comment]
After  some debugging from my end, I notice my problem was introduced by fetch!! Whenever fetch pulls data from a server component in production it produces the above error and then returns a 500 Internal Server Error.
