### ISSUE TITLE
'window is not defined' in component with 'use client' statement

### ISSUE THREAD

**Issue by tvardero** [vercel/next.js#52503]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 11
    Binaries:
      Node: 19.9.0
      npm: 9.6.3
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tvardero/nextjs-bug-window-undefined

### To Reproduce

```tsx
"use client" // <-- does not help

import 'client-only';  // <-- does not help neither
import React from 'react';
import Link from 'next/link';

export default function Header() {
    const refreshToken = window.localStorage.getItem("refresh_token"); // 'window is not defined'

    return (
        <header className="flex items-center justify-between px-6 py-4 bg-gray-800 text-white">
            <div className="flex items-center">
                <Link href="/"><b>Logo</b></Link>
            </div>

            <div className="flex items-center">
                {!refreshToken && <Link href="login">Login</Link>}
            </div>
        </header>
    );
}
```

Header.tsx is used in root layout:
```tsx
import Header from "./Header";
import "./global.css"

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="flex flex-col h-screen">
                <Header />
                <main className="flex-grow">{children}</main>
            </body>
        </html>
    );
}
```

### Describe the Bug

On `npm run build` the following exception appears:
```
- info Loaded env from C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\.env.production
- info Loaded env from C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\.env
- info Creating an optimized production build
- info Compiled successfully
- info Linting and checking validity of types
- info Collecting page data
[    ] - info Generating static pages (0/3)ReferenceError: window is not defined
    at Header (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\.next\server\app\page.js:260:26)
    at Ue (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:113:273)       
    at Ue (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:119:11)        
    at Z (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:120:91)
    at Ve (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:123:155)       
    at Xe (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:122:289)       
    at Z (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:120:350)        
    at Ve (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:123:155)       
    at Ue (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:114:215)       
    at Z (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:120:91)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
    at Header (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\.next\server\app\page.js:260:26)
    at Ue (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:113:273)       
    at Ue (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:119:11)        
    at Z (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:120:91)
    at Ve (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:123:155)       
    at Xe (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:122:289)       
    at Z (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:120:350)        
    at Ve (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:123:155)       
    at Ue (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:114:215)       
    at Z (C:\Users\OldNeer\OneDrive\Documents\bArtCRM\nextjs-bug-window-undefined\node_modules\next\dist\compiled\react-dom\cjs\react-dom-server.edge.production.min.js:120:91)
- info Generating static pages (3/3)

> Export encountered errors on following paths:
        /page: /
```

Also the same problem appears when debugging the application in development (npm run dev).

### Expected Behavior

`next build` finishes without exceptions.

### Which browser are you using? (if relevant)

not relevant

### How are you deploying your application? (if relevant)

not relevant

**Comment by tvardero** [comment]
Workaround: wrap window call into `if (typeof window !== "undefined") { ... }`

**Comment by tvardero** [comment]
Duplicated by: https://github.com/vercel/next.js/issues/50428
