### ISSUE TITLE
Next.js 13.4.10 breaks useSyncExerternalStore

### ISSUE THREAD

**Issue by natew** [vercel/next.js#52707]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 3.5.0
      pnpm: 7.32.1
    Relevant packages:
      next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3

(I downgraded after this bug came up)
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tamagui/tamagui/tree/72b28addf5969b6cc3f0953f8ab7ea7a1d05271c

### To Reproduce

Can reproduce loading this using Chrome responsive mode iPhone X:

https://site-iqj7d8h5p-tamagui.vercel.app

In the repo checkout 72b28addf5969b6cc3f0953f8ab7ea7a1d05271c, `yarn` and `yarn site` and then load the homepage on mobile device.

### Describe the Bug

```
main-79f22335469cfa5b.js:1 TypeError: Cannot read properties of null (reading 'getSnapshot')
    at Object.aP [as useSyncExternalStore] (framework-e5b12c291073d220.js:9:63102)
    at n.useSyncExternalStore (framework-e5b12c291073d220.js:25:6223)
    at y (_app-17f1cfb0d0a82165.js:12:7258)
    at B (80-fe61b202f42fb298.js:1:5781)
    at V.Anchor (80-fe61b202f42fb298.js:1:4923)
    at ab (framework-e5b12c291073d220.js:9:60869)
    at ud (framework-e5b12c291073d220.js:9:72751)
    at i (framework-e5b12c291073d220.js:9:120306)
    at oO (framework-e5b12c291073d220.js:9:99058)
    at framework-e5b12c291073d220.js:9:98925
    at oF (framework-e5b12c291073d220.js:9:98932)
    at ox (framework-e5b12c291073d220.js:9:95684)
    at oC (framework-e5b12c291073d220.js:9:96073)
    at r4 (framework-e5b12c291073d220.js:9:44769)
    at framework-e5b12c291073d220.js:9:111585
    at oI (framework-e5b12c291073d220.js:9:111591)
    at oS (framework-e5b12c291073d220.js:9:94961)
    at x (framework-e5b12c291073d220.js:33:1364)
    at MessagePort.T (framework-e5b12c291073d220.js:33:1894)
```

### Expected Behavior

No bug

**Comment by timneutkens** [comment]
@Desttro that would indicate you have a reproduction? Can you share a codesandbox / repository to look at?

**Comment by timneutkens** [comment]
Are the steps to reproduce still correct? I'm unable to reproduce with this setup:

```
gh clone tamagui/tamagui
cd tamagui
git checkout 72b28addf5969b6cc3f0953f8ab7ea7a1d05271c

yarn
yarn build # had to do this in order for yarn site to work
yarn site 
```

Then I opened http://localhost:5005, opened chrome devtools, selected iPhone XR as X wasn't in the list, but that's probably the same thing for the most part, and then tried opening / scrolling on the page. I'm unable to see the error posted in the initial issue.

**Comment by natew** [comment]
Hey Tim, sorry try running yarn site:prod. It’s only the prod release. And then load the site in a small viewport I usually just enable iPhone emulation in chrome.

**Comment by timneutkens** [comment]
I'm seeing the build fail on babel parsing somehow, I'm guessing that's not expected but somehow it happens from the tamagui loader 🤔 Did I miss running another command as well?
```
Tamagui Webpack Loader Error:
   Error parsing babel: SyntaxError: Unexpected character ''. (1:0) in code
Error: Error parsing babel: SyntaxError: Unexpected character ''. (1:0) in code
    at babelParse (/Users/timneutkens/projects/sandbox/tamagui/packages/static/dist/cjs/extractor/babelParse.js:59:11)
    at extractToClassNames (/Users/timneutkens/projects/sandbox/tamagui/packages/static/dist/cjs/extractor/extractToClassNames.js:86:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
    at async Object.loader2 (/Users/timneutkens/projects/sandbox/tamagui/packages/loader/dist/cjs/loader.js:69:23)
```

**Comment by 0xBigBoss** [comment]
@balazsorban44  see this repo for an example https://github.com/0xBigBoss/nextjs-tamagui-bug.git

Reproduced with nodejs v18.17.1

```sh
git clone https://github.com/0xBigBoss/nextjs-tamagui-bug.git && cd nextjs-tamagui-bug
yarn install
yarn web:prod && yarn web:prod:serve
```

Then open in a browser window less than 767px wide.

**Comment by balazsorban44** [comment]
Thanks @0xBigBoss. I can't say it followed exactly https://github.com/vercel/next.js/issues/52707#issuecomment-1686215955, as I still used much time to remove a bunch of unrelated code/dependencies, etc. Ideally, a minimal reproduction is much more minimal. But I was at least able to start it up.

My conclusion is that it's related to https://github.com/tamagui/tamagui/blob/master/packages/next-plugin/src/withTamagui.ts which makes a bunch of modifications to the `webpack` config, which is not covered by semver, as documented https://nextjs.org/docs/app/api-reference/next-config-js/webpack

It would be very valuable to see a reproduction that does not modify Next.js internals via the `webpack` config to verify whether it's an expected bug or not.

**Comment by yanickrochon** [comment]
> ReactServerComponentsError:
>
> You're importing a component that needs useSyncExternalStore. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

Happens in Next 14. If `useSyncExternalStore` has a third argument to get the server snapshot, then why does it error while being called on the server-side?

**Comment by kevin-sjj** [comment]
I'm wondering about why a custom hook using `useSyncExternalStore` may not be called on the server side. The third parameter, the `getServerSnapshot` function, seems to support SSR based on a specific snapshotValue(== fallbackValue.)

![image](https://github.com/vercel/next.js/assets/95740822/517a9760-d422-4b48-bf3d-8fa885551634)

When a directive is added, the following error occurs.

![image](https://github.com/vercel/next.js/assets/95740822/afffaffe-adbc-4a42-933f-5885edd2d587)

Happens in Next `14.1.0`

In my opinion, I think this hook should be able to run on both the server and client sides.

**Comment by jaypoojara12** [comment]
@kevin-sjj Have you got any workaround to deal with the error?

**Comment by chad-vogel** [comment]
We are getting the same error
![1f367d0e-4b36-4c18-a937-07897503a01b](https://github.com/vercel/next.js/assets/45291842/c712e504-caad-466b-b939-15f1f72e7809)

Next 14.1.0

**Comment by kevin-sjj** [comment]
@jaypoojara12 

As of now, it seems that the useSyncExternalStore hook cannot be directly called in the server component. Therefore, as an alternative, consider adding the 'use client' directive to hook and the components using the hook, allowing it to be executed on the client side.

**Comment by chad-vogel** [comment]
Although React allows useSyncExternalStore to be used server-side, it's important to note that Next.js currently does not provide support for this feature. While React offers this capability, Next.js lacks compatibility with useSyncExternalStore on the server-side. However, there is a case to be made for incorporating support for this feature into Next.js for a more seamless server-side rendering experience. We have use cases for it in our code base.

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
