### ISSUE TITLE
`not-found` build hangs with `NODE_ENV=test`

### ISSUE THREAD

**Issue by karlhorky** [vercel/next.js#53083]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/reverent-matan-pvw8wk?file=%2F.codesandbox%2Ftasks.json%3A10%2C4

### To Reproduce

1. Visit the CodeSandbox link above, which uses `NODE_ENV=test next build`
2. The `build-and-start` task, which starts automatically, hangs and never completes💥 (process exits after 3 retries)

```sh
$ next build
- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types  
- info Collecting page data  
- warn Restarted static page generation for /_not-found because it took more than 60 seconds
- warn See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
- warn Restarted static page generation for /_not-found because it took more than 60 seconds

> Build error occurred
Error: Static page generation for /_not-found is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (/project/sandbox/node_modules/next/dist/build/index.js:697:39)
    at Worker.exportPage (/project/sandbox/node_modules/next/dist/lib/worker.js:88:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /project/sandbox/node_modules/next/dist/export/index.js:519:32
    at async Span.traceAsyncFn (/project/sandbox/node_modules/next/dist/trace/trace.js:103:20)
    at async Promise.all (index 2)
    at async /project/sandbox/node_modules/next/dist/export/index.js:510:9
    at async Span.traceAsyncFn (/project/sandbox/node_modules/next/dist/trace/trace.js:103:20)
    at async /project/sandbox/node_modules/next/dist/build/index.js:1579:21
    at async Span.traceAsyncFn (/project/sandbox/node_modules/next/dist/trace/trace.js:103:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

<img width="934" alt="Screenshot 2023-07-23 at 19 03 30" src="https://github.com/vercel/next.js/assets/1935696/d0f16ac8-9701-4129-ae96-39c17bc92b39">

This may have been caused by the following PR by @huozhi, reviewed by @ijjk :

- https://github.com/vercel/next.js/pull/52985

### Describe the Bug

The `not-found` page build hangs when using `NODE_ENV=test`

This behavior is not present when using `next@13.4.11`

This may have been caused by the following PR by @huozhi, reviewed by @ijjk :

- https://github.com/vercel/next.js/pull/52985

Related issue (not exactly a dupe): https://github.com/vercel/next.js/issues/53082

### Expected Behavior

The `not-found` page build should succeed when using `NODE_ENV=test`

**Comment by karlhorky** [comment]
Thanks for #53106 @huozhi and @ijjk 🙌 

I can confirm that `next@13.4.13-canary.0` fixes the problem:

CodeSandbox: https://codesandbox.io/p/sandbox/awesome-rosalind-ntzj8k?file=%2Fpackage.json%3A13%2C23

![Screenshot 2023-07-25 at 07 04 32](https://github.com/vercel/next.js/assets/1935696/1eaec6a9-5121-4c9b-b5e1-9482e88ab972)
