### ISSUE TITLE
Unhandled "location is not defined" error reported when running the application.

### ISSUE THREAD

**Issue by ChetSocio** [vercel/next.js#53350]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime), Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/turbo

### To Reproduce

Just create a new project using: `npx create-next-app@latest` using typescript and turbopack. Then create a route using folder and create layout inside it.  I cannot publicly publish my code as it is a code for my business and has some api keys. I think the closest thing to this problem is my layout.tsx file handlings.So these are my layout.tsx files:  

### My App/layout.tsx file code:
```
import '../assets/globals.css'
import '@fontsource/roboto/400.css';

export const metadata = {
    title: 'Nextjs Demo',
    // description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

    return (
        <html lang="en">
            <head>
                <link rel='icon' href='/favicon.png' />
            </head>
            <body>
                {children}
            </body>
        </html>
    )
}

```

### My App/Login/layout.tsx file code:

```
import Navbar from '@/components/Home/Navbar'
import Footer from '@/components/Home/Footer'

export const metadata = {
    title: 'Login to Demo Site',
    description: 'Secure signin to demo site and access the features that non-logged-in users donot get.',
    alternates: {
        canonical: `https://demsite.com/login`,
    },
}


export default function RootLayout({ children, }: { children: React.ReactNode }) {

    return (
        <>
            <header>
                <Navbar />
            </header>
            <main>
                {children}
            </main>
            <Footer />
        </>
    )
}

```

This same principle is used in my code for other pages too. 

### Describe the Bug

I am using `next dev --turbo` in package.json and have experienced some improvements in code compiling time during development. However when ever i go to any page, I get this error:
 
## Unhandled errors reported when running the application.
#Error: location is not defined
```
Call Stack
updateDehydratedSuspenseComponent
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (16348:17)
updateSuspenseComponent
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (16048:16)
beginWork$1
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (17361:14)
beginWork
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25689:14)
performUnitOfWork
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24540:12)
workLoopSync
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24256:5)
renderRootSync
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24211:7)
performConcurrentWorkOnRoot
/turbopack/[project]/node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23339:74)
workLoop
/turbopack/[project]/node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (261:34)
flushWork
/turbopack/[project]/node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (230:14)
MessagePort.performWorkUntilDeadline
/turbopack/[project]/node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (537:21)
```

### In browser console: 

```
react-dom.development.js:16348 Uncaught Error: location is not defined
    at updateDehydratedSuspenseComponent (react-dom.development.js:16348:17)
    at updateSuspenseComponent (react-dom.development.js:16048:16)
    at beginWork$1 (react-dom.development.js:17361:14)
    at beginWork (react-dom.development.js:25689:14)
    at performUnitOfWork (react-dom.development.js:24540:12)
    at workLoopSync (react-dom.development.js:24256:5)
    at renderRootSync (react-dom.development.js:24211:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:23339:74)
    at workLoop (scheduler.development.js:261:34)
    at flushWork (scheduler.development.js:230:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:537:21)
```

My App/Page.tsx code: 
```
import Navbar from "@/components/Home/Navbar"
import Footer from "@/components/Home/Footer"

export default function Home () {
    return (
        <>
           <header>
                     <Navbar />
           </header>
            <main>
                 <div>
                      <!--Some simple html codes here->
                 </div>
            </main>
          <Footer />
        </>
    )
}

```

![image](https://github.com/vercel/next.js/assets/114129405/f3acaec6-9f44-4456-a7c5-7986273d2e7c)

That's all the code I have written till now. This project is a business project with some codes and turbopack installed. I don't know why it happened as it has mostly referenced to turbopack in error

### Expected Behavior

Expected to run without this error. Its a new project and doesnot contain any heavy packages or any heavy code. Just a hello world code.

### Which browser are you using? (if relevant)

Chrome latest

### How are you deploying your application? (if relevant)

Vercel

**Comment by ChetSocio** [comment]
Update: The motive behind using this apprach was that we have to use two different navbars (one on main homepages and another inside /dashoard urls ).To do this I have to include navbars and Footer component on Child layout.tsx file instead of main-parent layout.tsx file. However in homepage, i will get no layout.tsx file instad of main layout.tsx file. The catch comes here! When I include those Navbar and Footer component on parent layout.tsx file and code according to it, the error doesnot come. But when i do as stated above in main issue (Using Navabr and Footer component on page.tsx file), i get this error. The code is fairly simple and doesnot use outside packages. If you think my approach has any mistake then please tell me.

**Comment by ChetSocio** [comment]
I found where the error was . Solved!
