### ISSUE TITLE
failed to get redirect response TypeError: fetch failed

### ISSUE THREAD

**Issue by jfmoura** [vercel/next.js#53392]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023
    Binaries:
      Node: 16.20.1
      npm: 8.19.4
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.4.1", newest: "13.4.13-canary.6".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/WebDevSimplified/next-13-todo-list

### To Reproduce

Update next from 13.4.1 to next 13.4.12 editing package.json
```bash
npm i
npm run dev
```
run browser add todo.

### Describe the Bug

```
prisma:query SELECT 1
prisma:query BEGIN
prisma:query INSERT INTO `main`.`Todo` (`id`, `title`, `complete`, `cleatedAt`, `updatedAt`) VALUES (?,?,?,?,?) RETURNING `id` AS `id`
prisma:query SELECT `main`.`Todo`.`id`, `main`.`Todo`.`title`, `main`.`Todo`.`complete`, `main`.`Todo`.`cleatedAt`, `main`.`Todo`.`updatedAt` FROM `main`.`Todo` WHERE `main`.`Todo`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
failed to get redirect response TypeError: fetch failed
    at Object.fetch (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:26669) {
  cause: RequestContentLengthMismatchError: Request body length does not match content-length header
      at write (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:67105)
      at _resume (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:66726)
      at resume (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:65413)
      at connect (/home/jorge/next-13-todo-list/node_modules/next/dist/compiled/undici/index.js:1:65301) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

### Expected Behavior

In addition to the error in the console, the page that lists the todos is no longer updated.
In the previous version, it did.
I would like It work as before or some guide.

### Which browser are you using? (if relevant)

firefox 112.0.3

**Comment by jfmoura** [comment]
It worked!
I will wait impatiently for the next stable version.
Thanks!

**Comment by RnbWd** [comment]
I'm noticing the same issue with a redirect, and my code hasn't changed, I only updated nextjs to the latest version

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it wasn't verified against next@canary. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
