### ISSUE TITLE
TypeError: trace.getSpan is not a function

### ISSUE THREAD

**Issue by shaungt1** [vercel/next.js#53500]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-app-dir

### To Reproduce

Brand new project set up
I ran 

npx create-next-app@latest
On installation, I selected the following prompts:

Terminal

What is your project named? my-app
Would you like to use TypeScript? No / Yes
Would you like to use ESLint? No / Yes
Would you like to use Tailwind CSS? No / Yes
Would you like to use `src/` directory? No / Yes
Would you like to use App Router? (recommended) No / Yes
Would you like to customize the default import alias? No / Yes
What import alias would you like configured? @/*

### Describe the Bug

After I did a fresh install I recived this interal next error: TypeError: trace.getSpan is not a function

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 253 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 186 ms (20 modules)
TypeError: trace.getSpan is not a function
    at NextTracerImpl.getActiveScopeSpan (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\lib\trace\tracer.js:75:22)
    at NextTracerImpl.trace (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\lib\trace\tracer.js:94:103)
    at DevServer.handleRequest (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\base-server.js:263:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.handleRequest (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\dev\next-dev-server.js:312:16)
TypeError: trace.getSpan is not a function
    at NextTracerImpl.getActiveScopeSpan (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\lib\trace\tracer.js:75:22)
    at NextTracerImpl.trace (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\lib\trace\tracer.js:94:103)
    at DevServer.handleRequest (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\base-server.js:263:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.handleRequest (C:\Users\Frontside\Documents\App_Production\primary-ai\primaryai\node_modules\next\dist\server\dev\next-dev-server.js:312:16)

### Expected Behavior

It was a brand new install should have started as normal but did not.  tryed 5 times delting old installs createing new isntalls, changing directories, changing drives, and still same issue presist.

### Which browser are you using? (if relevant)

firefox and chrome

### How are you deploying your application? (if relevant)

npm run dev

**Comment by balazsorban44** [comment]
It's not clear which options you chose. Please add a reproduction repository so we can investigate. Please also test `next@canary` to make sure it's not an already fixed issue.
