### ISSUE TITLE
next/image "url" parameter is valid but upstream response is invalid

### ISSUE THREAD

**Issue by luca-vogels** [vercel/next.js#53715]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.0
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/luca-vogels/bug-next-image

### To Reproduce

Run `npm run dev` or `npm run build && npm run start`

### Describe the Bug

When using next with a custom server like express images are not displayed anymore.

Default next image uses following route for fetching optimized images:
`/_next/image/?url=...&w=...&q=...`

However opening this route returns following error:
`"url" parameter is valid but upstream response is invalid`

### Expected Behavior

Optimized image is returned

### Which browser are you using? (if relevant)

115.0.5790.111 

### How are you deploying your application? (if relevant)

npm run start

**Comment by shotanue** [comment]
I've encountered a similar issue in the project I'm working on.

It occurred when I attempted the following version upgrade:

```diff
- "next": "13.4.12",
+ "next": "13.4.13",
```

**Comment by admmasters** [comment]
Same issue. EKS,running in a container. Images load fine on 13.4.12.

**Comment by Mejiabrayan** [comment]
Has anyone found a solution to this issue? I'm also encountering the same thing.

**Comment by jordanpurinton** [comment]
bump, same issue

**Comment by sagardewani** [comment]
I am also facing this issue for Absolute path images like /apple-icon.png inside the app folder. It never loads.

**Comment by moshie** [comment]
Still getting this on `v13.5.3`

Not sure why it's connecting to port `3000` when the APP_PORT is set to `8080`?

```
upstream image response failed for /images/navbar/image.png TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async /opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:362:39
    at async imageOptimizer (/opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:519:61)
    at async /opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:102:36 {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}
```

**Comment by 0xboga** [comment]
> > I've encountered a similar issue in the project I'm working on.
> > It occurred when I attempted the following version upgrade:
> > ```diff
> > - "next": "13.4.12",
> > + "next": "13.4.13",
> > ```
> 
> Yeah, I confirm that versions above v13 don't work. Only v12 doesn't have problems with the images.

Same issue happens when upgrading from: 
```diff
 - "next": "13.5.2",
 + "next": "13.5.3",
```

**Comment by terrymun** [comment]
We have also encountered a similar issue: images loaded via `/_next/image?url=<path>&w=<num>&q=<num>` is failing and complaining that `"url" parameter is valid but upstream response is invalid`.

However, when attempting to load the actual image in the `url` parameter it works. This issue is only reproducible in production build and does not seem to affect when running the development server locally.

**Comment by moshie** [comment]
Can confirm `13.5.4-canary.1` fixed the issue for me

**Comment by Iulian-Dragomirescu** [comment]
> Still getting this on `v13.5.3`
> 
> It seems to work locally also when navigating to `/_next/static/media/image.2b36cbd7.png` I do get the image.
> 
> Not sure why it's connecting to port `3000` when the PORT is set to `8080` in our custom server?
> 
> looking into the code it seems to be something going on in the fetch perhaps it's not using the correct port? https://github.com/stefanprobst/next.js/blob/canary/packages/next/server/image-optimizer.ts#L291
> 
> ```
> upstream image response failed for /_next/static/media/image.2b36cbd7.png TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11576:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async invokeRequest (/opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
>     at async /opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:362:39
>     at async imageOptimizer (/opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/image-optimizer.js:537:13)
>     at async cacheEntry.imageResponseCache.get.incrementalCache (/opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:519:61)
>     at async /opt/application/node_modules/.pnpm/next@13.5.3_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:102:36 {
>   cause: Error: connect ECONNREFUSED ::1:3000
>       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
>       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
>     errno: -111,
>     code: 'ECONNREFUSED',
>     syscall: 'connect',
>     address: '::1',
>     port: 3000
>   }
> }
> ```

This might help you in your solution: https://github.com/vercel/next.js/issues/56038#issuecomment-1736985533

**Comment by moshie** [comment]
@Iulian-Dragomirescu 
Using the latest canary solved the issue for me in the end but that's good advice anyways thanks
https://github.com/vercel/next.js/issues/53715#issuecomment-1737030215

**Comment by mrkpatchaa** [comment]
The latest canary didn't fix it for me :/ 
I am getting `ERR_SSL_WRONG_VERSION_NUMBER` as here https://github.com/vercel/next.js/issues/55706#issuecomment-1740034370

**Comment by mrkpatchaa** [comment]
I can also confirm that now it's working. I didn't change anything... I rebuild my docker container like twice since this morning 👀

**Comment by samuelbailey123** [comment]
Also randomly experiencing this issue. 13.4.9 fixed it for me at the moment.... 
This needs to be a high priority issue if not already. Not sure how a company can push so many issues in production releases.

**Comment by ShahriarKh** [comment]
I'm getting the `ERR_SSL_WRONG_VERSION_NUMBER` error and only on linux on production.
I tried different file paths for the image src but none of them work.

**Comment by JustinTBrown** [comment]
Can confirm going back to 13.5.2 from 13.5.3 solved it for me.

**Comment by ngocdd** [comment]
I got the same issue, and it only appear with production build run dev local can not foud it,
when I' using the ubuntu laptop to access into production web the image can load normally ???
but when I using other my laptop or phone to access into production web it's can not load the images. 

my next version: 13.5.3

**Comment by shawngustaw** [comment]
this was broken on 13.5.3 for me but with 13.5.4 seems like it's fixed 👍

**Comment by WynstelleID** [comment]
like @shawngustaw after upgrade to 13.5.4 it's already fixed

**Comment by timomedia** [comment]
> this was broken on 13.5.3 for me but with 13.5.4 seems like it's fixed

It is still not fixed yet. I upgraded to version 13.5.4 but still have the image error as above

**Comment by 9vfQbg7z4ajrGQxR** [comment]
> > this was broken on 13.5.3 for me but with 13.5.4 seems like it's fixed
> 
> It is still not fixed yet. I upgraded to version 13.5.4 but still have the image error as above. Version 13.5.4 will have the following error message: **UND_ERR_INVALID_ARG**

Same here, the issues happening again in production

**Comment by lpbonomi** [comment]
Same here with `15.5.4`

```
upstream image response failed for /images/logo-ud.png TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11600:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (/home/ubuntu/ultradrop-app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:127:62909)
    at async invokeRequest (/home/ubuntu/ultradrop-app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async /home/ubuntu/ultradrop-app/node_modules/next/dist/server/next-server.js:362:39
    at async imageOptimizer (/home/ubuntu/ultradrop-app/node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/home/ubuntu/ultradrop-app/node_modules/next/dist/server/next-server.js:519:61)
    at async /home/ubuntu/ultradrop-app/node_modules/next/dist/server/response-cache/index.js:102:36 {
  cause: [Error: 00A8CB89397F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```

**Comment by tkafka** [comment]
I confirm - still broken in 13.5.4

```
upstream image response failed for /img/promo.png TypeError: fetch failed
...
cause: InvalidArgumentError: invalid connection header
...
code: 'UND_ERR_INVALID_ARG'
```

**Comment by sleeporsmile** [comment]
+1

**Comment by clevertree** [comment]
corporate sabotage to stay in profit. which version can we revert to to get this up and running again?

**Comment by benduran** [comment]
Confirmed pinning explicitly to `13.5.2` also resolves the issue for me. In any other version, I was seeing strange, non-deterministic behavior where sometimes images would succeed, and other times the same images would fail with that `500` error complaining about the `url` parameter.

**Comment by breakerh** [comment]
> Confirmed pinning explicitly to `13.5.2` also resolves the issue for me. In any other version, I was seeing strange, non-deterministic behavior where sometimes images would succeed, and other times the same images would fail with that `500` error complaining about the `url` parameter.

`13.5.4` works for us.. Stable and well, don't see images with 500 errors whatsoever.. Had a little heart attack when i noticed the error live... (bad testing in staging on our side.. shame)

**Comment by marcosbrasil** [comment]
I can confirmed that 13.5.4 and 13.5.3 dosent work but 13.5.2 did...

**Comment by lpbonomi** [comment]
using an import instead of the source fixes the errors for me:

```
import Image from 'next/image'
import profilePic from './me.png'
 
export default function Page() {
  return (
    <Image
      src={profilePic}
      alt="Picture of the author"
      // width={500} automatically provided
      // height={500} automatically provided
      // blurDataURL="data:..." automatically provided
      // placeholder="blur" // Optional blur-up while loading
    />
  )
}
```

You can read more about this here: https://nextjs.org/docs/app/building-your-application/optimizing/images#local-images

**Comment by Zaruike** [comment]
For my part it works instead of using ```/assets``` I use the full domain name (``https://domain/assets/``) directly... I know it's not necessarily ideal but at least it fixes the problem for me 😄 

My basic problem was also the same as @tkafka

**Comment by tavareshenrique** [comment]
I have the same problem, I consume images from a specific domain. I read some of the Next Image documentation, I noticed that I don't use the `remotePatterns` configuration, I only use the `domain`.

Do you think you should use both?

**Comment by dr-star** [comment]
**Downgrading** to version **13.5.2 works** for me. For those who have also **next-i18n** check https://stackoverflow.com/questions/77224157/error-500-when-deployed-on-vercel-but-working-in-local

**Comment by fanzypantz** [comment]
Can verify it does not work in production on 13.5.3, downgrading to 13.5.2 fixed it.

**Comment by ShahriarKh** [comment]
Can confirm it is fixed in 13.5.4 ✔

**Comment by allicanseenow** [comment]
Doesn't work for `domains` with 13.5.4 from what I've tested with.

**Comment by allicanseenow** [comment]
Did another test and 13.5.4 was completely broken for both approaches. 13.5.2 is working

**Comment by sagrawal-code** [comment]
> cause: InvalidArgumentError: invalid connection header

@tkafka are you running behind nginx? Maybe this will help: https://github.com/vercel/next.js/issues/56038#issuecomment-1752876655

**Comment by duthanhduoc** [comment]
Have same issue with `    "next": "13.5.4"`

**Comment by 0xNunana** [comment]
The issue persists in nextjs :13.5.4 
upstream image response failed for /me.png TypeError: fetch failed
    at Object.fetch (/app/node_modules/next/dist/compiled/undici/index.js:1:26672)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:16:12)
    at async /app/node_modules/next/dist/server/next-server.js:362:35
    at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:517:61)
    at async /app/node_modules/next/dist/server/response-cache/index.js:102:36 {
  cause: InvalidArgumentError: invalid connection header

**Comment by achainarong** [comment]
I allready tested multiple version of nextjs and it's still not working. Should i just use normal img tags instead?

**Comment by jorisdugue** [comment]
> I allready tested multiple version of nextjs and it's still not working. Should i just use normal img tags instead?

You can specify the full url with your domain this will be working too 😄 (in https)

**Comment by achainarong** [comment]
> > I allready tested multiple version of nextjs and it's still not working. Should i just use normal img tags instead?
> 
> You can specify the full url with your domain this will be working too 😄 (in https)

Oh my gosh i deployed the wrong branch and wondered why it was not fixed hahahaaa

**Comment by mertafor** [comment]
I seriously can't believe that I cannot insert and display a simple local png image on a page after 2 hours of trial and error. It works in both dev mode and production mode on localhost but whenever I upload it to my server, it doesn't show. Interestingly other images work fine. I thought maybe the image's itself has a problem yet browser nicely loading it if I try to access the url under /_next-static. Of course, using HTML img tag works as well. My server is behind ngnix proxy but I don't imagine it would be the problem because other images are being loaded fine. Tried with 13.5.2, 5.3, .5.4 and finally 13.4.x. having the same result. In the end, I changed the image format to SVG and it worked (probably because next/image won't re-encode SVG images). My guess is next/image encoding method has problems. I read somewhere Next will use sharp for resizing if it's installed. I have it and tried to remove in case it's related but nothing changed.

Honestly, I have encountered many issues with Next 13, I supported you for your hard work and continue supporting but not being able to add an image to web page is simply a humiliating experience.

**Comment by ndizazzo** [comment]
> My server is behind ngnix proxy but I don't imagine it would be the problem because other images are being loaded fine

@mertafor I think this may be a proxy configuration issue? Try adding:

```nginx
location / {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $proxy_protocol_addr;
  proxy_set_header X-Forwarded-For $proxy_protocol_addr;
  proxy_pass <your server>;
}
```

**Comment by mertafor** [comment]
@ndizazzo That resolved the problem. Thanks a lot!

**Comment by jscoobyced** [comment]
For me without any hack, I simply used
https://nextjs.org/docs/messages/sharp-missing-in-production
by adding 
```
yarn add sharp
```
And the issue is gone.

**Comment by NumanAnees** [comment]
Still getting this on **next: v13.5.4**
```
upstream image response failed for /_next/static/media/illustrations.885dc0f2.png TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11600:11)
    at async globalThis.fetch (/home/dev/turboschema-server/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:13:9347)
    at async invokeRequest (/home/dev/turboschema-server/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:16:12)
    at async /home/dev/turboschema-server/node_modules/next/dist/server/next-server.js:362:35
    at async imageOptimizer (/home/dev/turboschema-server/node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/home/dev/turboschema-server/node_modules/next/dist/server/next-server.js:517:61)
    at async /home/dev/turboschema-server/node_modules/next/dist/server/response-cache/index.js:102:36 {
  cause: InvalidArgumentError: invalid connection header
      at processHeader (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:102994)
      at new Request (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:100295)
      at [dispatch] (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:64352)
      at Intercept (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:2:93153)
      at [Intercepted Dispatch] (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:115359)
      at Client.dispatch (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:115591)
      at [dispatch] (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:2:264035)
      at [Intercepted Dispatch] (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:115258)
      at Pool.dispatch (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:115591)
      at [dispatch] (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:29874)
      at Agent.Intercept (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:2:93153)
      at Agent.dispatch (/home/dev/turboschema-server/node_modules/next/dist/compiled/undici/index.js:1:115591)
      at node:internal/deps/undici/undici:11474:55
      at new Promise (<anonymous>)
      at dispatch (node:internal/deps/undici/undici:11474:16)
      at httpNetworkFetch (node:internal/deps/undici/undici:11375:73)
      at httpNetworkOrCacheFetch (node:internal/deps/undici/undici:11277:39)
      at httpFetch (node:internal/deps/undici/undici:11126:43)
      at schemeFetch (node:internal/deps/undici/undici:11054:24)
      at node:internal/deps/undici/undici:10930:26
      at mainFetch (node:internal/deps/undici/undici:10947:11)
      at fetching (node:internal/deps/undici/undici:10904:7)
      at fetch2 (node:internal/deps/undici/undici:10782:20)
      at Object.fetch (node:internal/deps/undici/undici:11598:18)
      at fetch (node:internal/process/pre_execution:274:25)
      at T (/home/dev/turboschema-server/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:354915)
      at /home/dev/turboschema-server/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:13:9860
      at NextTracerImpl.trace (/home/dev/turboschema-server/node_modules/next/dist/server/lib/trace/tracer.js:90:20)
      at globalThis.fetch (/home/dev/turboschema-server/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:13:9371)
      at invokeRequest (/home/dev/turboschema-server/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:16:18)
      at /home/dev/turboschema-server/node_modules/next/dist/server/next-server.js:362:74
      at imageOptimizer (/home/dev/turboschema-server/node_modules/next/dist/server/image-optimizer.js:537:19)
      at DevServer.imageOptimizer (/home/dev/turboschema-server/node_modules/next/dist/server/next-server.js:357:20)
      at cacheEntry.imageResponseCache.get.incrementalCache (/home/dev/turboschema-server/node_modules/next/dist/server/next-server.js:517:72)
      at /home/dev/turboschema-server/node_modules/next/dist/server/response-cache/index.js:102:42 {
    code: 'UND_ERR_INVALID_ARG'
  }
}
ImageError: "url" parameter is valid but upstream response is invalid
    at imageOptimizer (/home/dev/turboschema-server/node_modules/next/dist/server/image-optimizer.js:549:19)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/home/dev/turboschema-server/node_modules/next/dist/server/next-server.js:517:61)
    at async /home/dev/turboschema-server/node_modules/next/dist/server/response-cache/index.js:102:36 {
  statusCode: 500
}

```

I am giving absolute path value to src attribute.

**Comment by huozhi** [comment]
The original reproduction in the issue missed passing down `hostname` and `port` as argument, can someone still repro it with passing them down to next custom server?

**Comment by Stevemoretz** [comment]
> > cause: InvalidArgumentError: invalid connection header
> 
> @tkafka are you running behind nginx? Maybe this will help: [#56038 (comment)](https://github.com/vercel/next.js/issues/56038#issuecomment-1752876655)

Thanks for this, I updated so maybe some bugs go away but more things broke than fixed lol.

**Comment by styfle** [comment]
@luca-vogels Thanks for the code to reproduce this issue!

The reason you're seeing port 3000 is because its the default port assigned here:

https://github.com/vercel/next.js/blob/dabeb51fffd6505cf8b580036b694e51b8b840db/packages/next/src/server/next.ts#L283-L285

The solution is to pass `hostname` and `port` to the custom server so that subsequent fetch() calls work as expected. 

I created a PR to demonstrate here: 

- https://github.com/luca-vogels/bug-next-image/pull/1

**Comment by f1ght3rlucky** [comment]
I have still this issue

**Comment by mcasters** [comment]
J've just tried v13.5.5-canary.16 but it still doesn't work on production (no problem on local dev).
The only way for me to display my images (which are local) is to unoptimize them, or to come back to IMG tag (which is the same). 
I tried many things since two weeks, it is very frustrating (several version of next, changing my custom server from 'http' to 'express', add or remove hostname and port in the server, set cafile in npm config, trying http or https, imageLoader to encodeURIComponent the src and then return  /_next/image?url...) but for the moment I get always the same error (ImageError: "url" parameter is valid but upstream response is invalid with a ECONNREFUSED). Please don't hesitate to share your solution when you get one. Thank you so much !

**Comment by clevertree** [comment]
Confirmed they finally fixed this issue in 13.5.5. #corporateSabotage

**Comment by PawelWywiol** [comment]
It's not working (for me). I've still got the same error, even with a clean setup.

```
upstream image response failed for /_next/static/media/img-grid-03.66c7ff3b.jpg TypeError: fetch failed
    at Object.fetch (/path-to-node-app/public_nodejs/node_modules/next/dist/compiled/undici/index.js:1:21788)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async invokeRequest (/path-to-node-app/public_nodejs/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async /path-to-node-app/public_nodejs/node_modules/next/dist/server/next-server.js:365:35
    at async imageOptimizer (/path-to-node-app/public_nodejs/node_modules/next/dist/server/image-optimizer.js:533:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/path-to-node-app/public_nodejs/node_modules/next/dist/server/next-server.js:519:61)
    at async /path-to-node-app/public_nodejs/node_modules/next/dist/server/response-cache/index.js:92:36
    at async /path-to-node-app/public_nodejs/node_modules/next/dist/lib/batcher.js:43:32 {
  cause: Error: connect ECONNREFUSED 127.0.0.1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 3000
  }
}
```

**Comment by alinayebi9080** [comment]
I find that error occurred because in next/server/next-server.js below code is added. and always use http as protocol.
                
const protocol = this.serverOptions.experimentalHttpsServer ? "https" : "http";
                const invokeRes = await (0, _invokerequest.invokeRequest)(`${protocol}://${this.fetchHostname || "localhost"}:${this.port}${newReq.url || ""}`, {
                    method: newReq.method || "GET",
                    headers: newReq.headers,
                    signal: (0, _nextrequest.signalFromNodeResponse)(res.originalResponse)
                });

**Comment by Faruqt** [comment]
This issue gave me a headache. I can confirm that v13.5.5 fixes the problem.

**Comment by spbro007** [comment]
I haven't checked if 13.5.5 fixed it or not but even if it did, 13.5.5 doesn't work on aws beanstalk node18 / 6.0.1

**Comment by BestTrier** [comment]
I found out that this error still exist in 13.5.6. How can I fix this?

**Comment by VittorioMorellini** [comment]
Hi I have the same issue in Next 13.5.5 released on IIS
When I release on Https the Image does not work, the img yes.

I did not understand how to fix the issue, the Image over https does not work
The Image component released on IIS it does not work

**Comment by yongsk0066** [comment]
same issue in Next 14.0.1. It was ok before(v13). 
```
  cause: SocketError: other side closed
      at Socket.onSocketEnd (node:internal/deps/undici/undici:9981:26)
      at Socket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1408:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '127.0.0.1',
      localPort: 50501,
      remoteAddress: '127.0.0.1',
      remotePort: 3000,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 1741,
      bytesRead: 0
    }
  }
}```

**Comment by spbro007** [comment]
To everyone encountering this issue,
**Cause**
I think underlying cause of this issue is OS mismatch as  an application works differently on different systems.
I was encountering this issue when trying to use local images in public dir.
**Solution**
I switched to a cdn for all images. (though other assets like font etc. work as they should).
Now in production, I didn't get that error even in 13.4, 14.

**Comment by AymanMorsy** [comment]
I upgraded from v13.5.4 to  v14.0.1 by follwing the same steps in this article
https://nextjs.org/docs/pages/building-your-application/upgrading/version-14
and I got the problem for all images and this Error example :

```
 ⨯ upstream image response failed for /imgs/home/services/concrete.webp TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (I:\Projects\swaidg\swaidgroup\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:14353)
    at async invokeRequest (I:\Projects\swaidg\swaidgroup\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async I:\Projects\swaidg\swaidgroup\node_modules\next\dist\server\next-server.js:592:35
    at async imageOptimizer (I:\Projects\swaidg\swaidgroup\node_modules\next\dist\server\image-optimizer.js:576:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (I:\Projects\swaidg\swaidgroup\node_modules\next\dist\server\next-server.js:176:65)
    at async I:\Projects\swaidg\swaidgroup\node_modules\next\dist\server\response-cache\index.js:93:36
    at async I:\Projects\swaidg\swaidgroup\node_modules\next\dist\lib\batcher.js:41:32 {
  cause: Error: connect ETIMEDOUT ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4039,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}
```
I'm using:
- windows 10
- chrome v118

**Comment by AymanMorsy** [comment]
I upgraded from v13.5.4 which was OK to V14.0.1 to found this problem, so I revert back to the earlier version and two days later I tried again to upgrade and it works ( the version I upgraded to is the same as before V14.0.1 so weird).

**Comment by bluecomet1994** [comment]
Also had the same issue with v14.0.1. Anyone tried it successfully in this version?

**Comment by stasdre** [comment]
Same problem in version 14

**Comment by maylorsan** [comment]
Same issue with NextJS 14

**Comment by yaroslav-kulpan** [comment]
The same problem in NextJS 14

**Comment by bluecomet1994** [comment]
It seems the team is not able to see our comments as it is closed issue.
I posted a new issue with what I have and please comment to there together so that we could resolve our issues as soon as possible.
https://github.com/vercel/next.js/issues/58248
