### ISSUE TITLE
In v13.4.13 standalone server unexpectedly uses workers with experimental appDir

### ISSUE THREAD

**Issue by matmannion** [vercel/next.js#53740]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.17.0
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: standalone
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/matmannion/standalone-workers

### To Reproduce

```
npm run build
node .next/standalone/server.js
curl 'http://localhost:3000/api/ping'
```

On most environments this is fine, but it's spinning up workers where it wasn't previously.

### Describe the Bug

Following the upgrade to 13.4.13, we saw errors in our environment starting and on inspection, this was because our API routes weren't working:

```
- error Failed to handle request for /api/isReady
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async requestHandler (/app/node_modules/next/dist/server/lib/start-server.js:336:33)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:152:13) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:43001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 43001
  }
}
- error Failed to handle request for /api/ping
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async requestHandler (/app/node_modules/next/dist/server/lib/start-server.js:336:33)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:152:13) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:43001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 43001
  }
}
```

These routes are incredibly simple, just ping/pong responses. Seeing a connection to a localhost port was unexpected and we think the reason is because of the inclusion of https://github.com/vercel/next.js/commit/1398de9977b89c9c4717d26e213b52bc63ccbe7e, which switches the standalone server.js to use `startServer` as follows:

```
startServer({
  dir,
  isDev: false,
  config: nextConfig,
  hostname: hostname === 'localhost' ? '0.0.0.0' : hostname,
  port: currentPort,
  allowRetry: false,
  keepAliveTimeout,
  useWorkers: !!nextConfig.experimental?.appDir,
}).then(() => {
  console.log(
    'Listening on port',
    currentPort,
    'url: http://' + hostname + ':' + currentPort
  )
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
```

Notably, this sets `useWorkers` to true with `appDir` (which is on by default). By setting `experimental: { appDir: false }` in `next.config.js` this doesn't use workers and works as it did in 13.4.12. 

### Expected Behavior

Would hope that this would work in all environments, this is an unexpected breaking change for us.

### How are you deploying your application? (if relevant)

Standalone + Docker + k8s

**Comment by darthmaim** [comment]
Duplicate of #53171

**Comment by matmannion** [comment]
Closing as #53171 is the actual cause
