### ISSUE TITLE
Worpress with vercal guide: https://vercel.com/guides/wordpress-with-vercel does not work and results in build errors when deplying

### ISSUE THREAD

**Issue by Drygord** [vercel/next.js#54032]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.16-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Drygord/MizzTastyTreats

### To Reproduce

Follow The guide from https://vercel.com/guides/wordpress-with-vercel using localwp

The wordpress api line in env.local is 

`WORDPRESS_API_URL=http://mizztastytreats.local/graphql`

### Describe the Bug

Deploy errors despite doing everything exactly by the book.

[12:35:02.046] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[12:35:02.086] Cloning github.com/Drygord/MizzTastyTreats (Branch: main, Commit: e3ff434)
[12:35:02.381] Previous build cache not available
[12:35:02.572] Cloning completed: 485.556ms
[12:35:02.937] Running "vercel build"
[12:35:03.426] Vercel CLI 31.2.3
[12:35:03.653] Installing dependencies...
[12:35:03.978] yarn install v1.22.17
[12:35:04.001] info No lockfile found.
[12:35:04.008] [1/4] Resolving packages...
[12:35:06.298] [2/4] Fetching packages...
[12:35:19.368] [3/4] Linking dependencies...
[12:35:22.251] [4/4] Building fresh packages...
[12:35:22.259] success Saved lockfile.
[12:35:22.264] Done in 18.29s.
[12:35:22.291] Detected Next.js version: 13.4.15
[12:35:22.293] Running "yarn run build"
[12:35:22.471] yarn run v1.22.17
[12:35:22.495] $ next build
[12:35:23.047] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[12:35:23.047] This information is used to shape Next.js' roadmap and prioritize features.
[12:35:23.047] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[12:35:23.047] https://nextjs.org/telemetry
[12:35:23.047] 
[12:35:23.131] - info Linting and checking validity of types...
[12:35:25.871] - info Creating an optimized production build...
[12:35:25.889] - info Downloading swc package @next/swc-wasm-nodejs...
[12:35:26.794] - info Using wasm build of next-swc
[12:35:26.814] - warn Attempted to load @next/swc-linux-x64-gnu, but an error occurred: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /vercel/path0/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node)
[12:35:26.814] - warn Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
[12:35:35.442] - info Compiled successfully
[12:35:35.442] - info Collecting page data...
[12:35:35.940] TypeError: fetch failed
[12:35:35.940]     at Object.fetch (node:internal/deps/undici/undici:11457:11)
[12:35:35.940]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[12:35:35.941]     at async fetchAPI (/vercel/path0/.next/server/chunks/924.js:432:17)
[12:35:35.941]     at async getAllPostsWithSlug (/vercel/path0/.next/server/chunks/924.js:464:18)
[12:35:35.942]     at async getStaticPaths (/vercel/path0/.next/server/pages/posts/[slug].js:317:22)
[12:35:35.945]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:700:33)
[12:35:35.945]     at async /vercel/path0/node_modules/next/dist/build/utils.js:1125:113
[12:35:35.945]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:103:20) {
[12:35:35.945]   cause: Error: getaddrinfo ENOTFOUND mizztastytreats.local
[12:35:35.946]       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
[12:35:35.946]     errno: -3008,
[12:35:35.946]     code: 'ENOTFOUND',
[12:35:35.946]     syscall: 'getaddrinfo',
[12:35:35.947]     hostname: 'mizztastytreats.local'
[12:35:35.947]   }
[12:35:35.947] }
[12:35:35.947] 
[12:35:35.947] > Build error occurred
[12:35:35.948] Error: Failed to collect page data for /posts/[slug]
[12:35:35.948]     at /vercel/path0/node_modules/next/dist/build/utils.js:1156:15
[12:35:35.948]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[12:35:35.948]   type: 'Error'
[12:35:35.948] }
[12:35:35.994] error Command failed with exit code 1.
[12:35:35.994] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[12:35:36.015] Error: Command "yarn run build" exited with 1

### Expected Behavior

I'd expect it to just work out of the box after following a guide. A proper deployment and build etc.

### Which browser are you using? (if relevant)

Firefox latest version

### How are you deploying your application? (if relevant)

In this case, vercel

**Comment by kyleshut** [comment]
Also running into this issue. I'm on latest version of nextjs 13.4.16 and node 18 deployed on vercel. Few unique intermittent errors i'm facing in production with different causes but all related to undici "TypeError: fetch failed":

1. 
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8422:28)
      at node:internal/deps/undici/undici:8380:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8411:13)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

2. 
 TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ETIMEDOUT 74.74.21.9:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '74.74.21.9',
    port: 443
  }
}
3.
 TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: [Error: 802CA17C9C7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:355:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}

I use axios for requests and don't use fetch whatsoever in my source code so seems to be an issue with node 18 and next js 13.4.16 under the hood

**Comment by TrustyTechSG** [comment]
Im also facing **TypeError: fetch failed error** after upgrade to 13.4.16.

**Comment by sorenhoyer** [comment]
I have the same problem

**Comment by kylehotchkiss** [comment]
I've encountered this error while fetch()ing from API routes (non-edge). Very sporadic and I can't yet tell if there's something on the server side causing it to occur. In other conversations around the internet, I've seen people say the issue is resolved by upgrading to Node.js 20 which isn't available for Vercel at the moment.

**Comment by nick964** [comment]
> I've encountered this error while fetch()ing from API routes (non-edge). Very sporadic and I can't yet tell if there's something on the server side causing it to occur. In other conversations around the internet, I've seen people say the issue is resolved by upgrading to Node.js 20 which isn't available for Vercel at the moment.

In the convos you have had, is this specific to the fetch call? I'm seeing this error intermittetently in production. I'm using Next.JS 13.4.13 and node version 18. Trying to figure this out, so curious if converting this to an axios call will resolve it

**Comment by rossamurphy** [comment]
I have the same problem.
