### ISSUE TITLE
Rendering is not working after page refresh on StackBlitz

### ISSUE THREAD

**Issue by lazarv** [vercel/next.js#54215]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Aug 18 2023 12:01:15 GMT+0200 (Central European Summer Time)
    Binaries:
      Node: 16.20.0
      npm: 9.4.2
      Yarn: 1.22.19
      pnpm: 8.6.10
    Relevant Packages:
      next: 13.4.18-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://stackblitz.com/edit/stackblitz-starters-u9soom?file=app%2Fpage.jsx

### To Reproduce

1. starts up correctly
2. refresh the page
3. see error in the console

### Describe the Bug

Upon refreshing the page, rendering stops working.

```
TypeError: s.tee is not a function or its return value is not iterable
    at cloneBody (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/compiled/undici/index.js:2:1855)
    at cloneResponse (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/compiled/undici/index.js:2:54852)
    at cloneResponse (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/compiled/undici/index.js:2:54747)
    at Response.clone (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/compiled/undici/index.js:2:54275)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/react/cjs/react.shared-subset.development.js:237:41)
    at async globalThis.fetch (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/lib/patch-fetch.js:93:16)
    at async invokeRequest (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async invokeIpcMethod (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/lib/server-ipc/request-utils.js:45:21)
    at async DevServer.ensurePage (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/dev/next-dev-server.js:522:13)
    at async Object.ensure (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/dev/next-dev-server.js:162:17)
    at async DevRouteMatcherManager.matchAll (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
    at async DevRouteMatcherManager.match (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:159:26)
    at async DevServer.handleCatchallRenderRequest (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/next-server.js:646:27)
    at async DevServer.handleRequestImpl (file:///home/projects/stackblitz-starters-u9soom/node_modules/next/dist/server/base-server.js:647:17)
```

### Expected Behavior

Rendering is still working after page refresh.

**Comment by eric-burel** [comment]
Same with Next 13.4, does a rollback eg to 13.3  help?

**Comment by lazarv** [comment]
This is still happening using 13.4.20-canary.16

**Comment by lazarv** [comment]
This is now working as expected with 13.4.20-canary.28

**Comment by jeltehomminga** [comment]
still seeing this error on 13.5.3

for example in official MUI starter https://stackblitz.com/github/mui/material-ui/tree/master/examples/material-ui-nextjs-ts when you remove the babel.config.js


![CleanShot 2023-09-27 at 16 17 05](https://github.com/vercel/next.js/assets/35220102/dd1b9b1f-aac0-4fc9-92be-bf7f9ad142bf)

**Comment by lazarv** [comment]
At least the dev server is not dying because of this @jeltehomminga 

I updated my original StackBlitz repro app to use 13.5.3 and it's working as expected without the stream tee'ing issue.
https://stackblitz.com/edit/stackblitz-starters-u9soom?file=package.json

The MUI example is also working ok when I removed the `.babelrc` file and the image from the `MediaCard` component.
https://stackblitz.com/edit/github-nj1clt?file=src%2Fcomponents%2FMediaCard.tsx

**Comment by jeltehomminga** [comment]
Ok thanks for your quick reply, should be fine then
