### ISSUE TITLE
`Cannot set property message of ... which has only a getter` when an error happens during instrumentation hook being require'd

### ISSUE THREAD

**Issue by SeriousBug** [vercel/next.js#54417]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 08 Aug 2023 22:13:48 +0000
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/SeriousBug/nextjs-error-repro

### To Reproduce

Enable `instrumentationHook` experimental feature, then in the `instrumentation.ts` throw an error where the `message` field is a getter. This will cause the error `Cannot set property message of ... which has only a getter`. A similar error occurs if the error was not an object.

### Describe the Bug

The bug is caused by this line which incorrectly assumes that the error must have a `message` field, which results inside the catch block: https://github.com/vercel/next.js/blob/1e3920c3dde6a96623205f968aee6e18db7843dc/packages/next/src/server/dev/next-dev-server.ts#L566

I encountered this issue because I was parsing data with Zod at the top level of `instrumentation.ts`, which throws a custom error with a getter `message` field.

### Expected Behavior

A concise error message should still be displayed if the `message` field can not be overwritten.

**Comment by BellCubeDev** [comment]
I experienced this bug just a little bit ago in development of an instrumentation hook in `14.2.4`. If the `err.message` property cannot be set for whatever reason, this will cause an error. Some safer approaches to consider:
* Checking if the `err.message` property exists as a property and can be written using `Object.getOwnPropertyDescriptor()` before attempting to overwrite it (perhaps use one of the methods below as a fallback if it isn't writable?)
  * In my case, no descriptor would be returned because there is no `message` proeprty
* Overwriting the `err.message` property through the use of a method such as `Object.assign()` or `Object.defineProperty()`
* Logging a message and letting the error go through (ideally using try/finally rather than try/catch)
* Logging the error object and throwing a new error (something I don't recommend in the case that the user has a custom server setup)

A real-world example of a library whose error does not have a writable `message` would be Zod with [their ZodError class](https://github.com/colinhacks/zod/blob/826d6a22a008ed38b64a6deb405a59b6ba74b6af/src/ZodError.ts#L283-L285). This is where my error originated from.

**Comment by akselinurmio** [comment]
This is not stale, as it still occurs in Next.js 15.5.9 when running `next start`:

```
Failed to prepare server TypeError: An error occurred while loading instrumentation hook: Cannot set property _conf of [object Module] which has only a getter
    at G._config (.next/server/chunks/547.js:19:169268)
    at G.start (.next/server/chunks/547.js:19:169543)
    at Module.d (.next/server/instrumentation.js:1:680)
TypeError: An error occurred while loading instrumentation hook: Cannot set property _conf of [object Module] which has only a getter
    at G._config (.next/server/chunks/547.js:19:169268)
    at G.start (.next/server/chunks/547.js:19:169543)
    at Module.d (.next/server/instrumentation.js:1:680)
 ⨯ unhandledRejection:  TypeError: An error occurred while loading instrumentation hook: Cannot set property _conf of [object Module] which has only a getter
    at G._config (.next/server/chunks/547.js:19:169268)
    at G.start (.next/server/chunks/547.js:19:169543)
    at Module.d (.next/server/instrumentation.js:1:680)
```
