### ISSUE TITLE
useSelectedLayoutSegments return an error with jest:  Error: Uncaught [TypeError: Cannot destructure property 'tree' of '(0 , _react.useContext)(...)' as it is null.]

### ISSUE THREAD

**Issue by borracciaBlu** [vercel/next.js#54421]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Error** 
```bash
 Error: Uncaught [TypeError: Cannot destructure property 'tree' of '(0 , _react.useContext)(...)' as it is null.]
```

**Info**
```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/objective-gianmarco-ygyrz6

### To Reproduce

in https://codesandbox.io/p/sandbox/objective-gianmarco-ygyrz6 use `yarn test`

Add `useSelectedLayoutSegments` to a component. Run the component test
```
import { useSelectedLayoutSegments } from 'next/navigation'

const segments = useSelectedLayoutSegments();
```

This trigger the issue.
In particular see:

```
// https://github.com/vercel/next.js/blob/1e3920c3dde6a96623205f968aee6e18db7843dc/packages/next/src/client/components/navigation.ts#L221
const { tree } = useContext(LayoutRouterContext)
```

Where `LayoutRouterContext` is init to `null`.
```
// https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/app-router-context.ts#L112
export const LayoutRouterContext = React.createContext<{
  childNodes: CacheNode['parallelRoutes']
  tree: FlightRouterState
  url: string
}>(null as any)
```

### Describe the Bug

When you run the test you got:
```
onsole.error
      Error: Uncaught [TypeError: Cannot destructure property 'tree' of '(0 , _react.useContext)(...)' as it is null.]
          at reportException (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at innerInvokeEventListeners (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
          at invokeEventListeners (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
          at HTMLUnknownElementImpl._dispatch (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
          at HTMLUnknownElement.dispatchEvent (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
          at Object.invokeGuardedCallbackDev (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
          at invokeGuardedCallback (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
          at beginWork$1 (/Users/marcobuttini/Code/tests/with-jest-app/node_modules/react-dom/cjs/react-dom.development.js:27451:7)
```

And so you force to use a mock:
```
jest.mock('next/navigation', () => ({
    useSelectedLayoutSegments: jest.fn()
}));

useSelectedLayoutSegments.mockReturnValue([''])
```

### Expected Behavior

it should return an empty segment but not an error. 
Check the context is not null before destructure.

**Comment by balazsorban44** [comment]
Hi, it looks like the reproduction was missing the actual code, it was just an empty project: 
![image](https://github.com/vercel/next.js/assets/18369201/bd998bef-ce4f-49e8-8b23-1a54ffb47bee)

Please open a new issue with an attached reproduction. Make sure to use `next@canary` to avoid reporting a potentially fixed issue. Thanks!
