### ISSUE TITLE
Hooks is `null` on SSR after 13.4.13 and up

### ISSUE THREAD

**Issue by EloB** [vercel/next.js#54429]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: 12.3.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/TanStack/query/issues/5371

### To Reproduce

I don't have any reproduce repo but I found this [issue](https://github.com/TanStack/query/issues/5371) describing a simliar situation as our error. The error was introduced for us in `13.4.13` and still exists in `13.4.20-canary.2`. In `13.4.12` everything works fine for us.

- We have a custom server and use `App.getInitialProps`. We use this pattern https://github.com/vercel/next.js/issues/9336#issuecomment-1092830219. A thought might be the `await getDataFromTree(<AppTree {...treeProps} />);` being executed in `App.getInitialProps`. This might be the cause for `renderWithHooks`?
- We use monorepo
- We use pnpm
- We **don't** use `app/`.
- We use `pages/`.
- We also use `@tanstack/react-query`. It fails because it tries to run `useEffect` in SSR and therefor `useEffect` becomes `null` and throws an error. I saw that they had `'use client'` in that failing [file](https://github.com/TanStack/query/blob/845751180decd86b2feab669e487a2887e12f8b5/packages/react-query/src/QueryClientProvider.tsx#L1). Maybe has something todo with it. I'm unsure if `@tanstack/react-query` is the source error or the first occurrence of `useEffect`. Adding the experimental `appDir: false` in the `next.config.js` fixed the issue a bit but then instead get this error:

```
[0] Error: Failed to initialize render worker app
[0]     at invokeRender (/Users/ollebroms/Documents/tv4/nordic-web/node_modules/.pnpm/next@13.4.20-canary.2_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/lib/router-server.ts:362:15)
[0]     at handleRequest (/Users/ollebroms/Documents/tv4/nordic-web/node_modules/.pnpm/next@13.4.20-canary.2_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/lib/router-server.ts:662:22)
[0]     at runMicrotasks (<anonymous>)
[0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0]     at async NextCustomServer.requestHandlerImpl [as requestHandler] (/Users/ollebroms/Documents/tv4/nordic-web/node_modules/.pnpm/next@13.4.20-canary.2_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/lib/router-server.ts:700:7)
```

Sometimes the server starts up without errors but making multiple requests before all startup script than we see that above error more frequently. So it seems like a queuing issue.

When using canary without `appDir: false` I get this error:
```
[0] Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
[0] 1. You might have mismatching versions of React and the renderer (such as React DOM)
[0] 2. You might be breaking the Rules of Hooks
[0] 3. You might have more than one copy of React in the same app
[0] See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
[0] TypeError: Cannot read properties of null (reading 'useReducer')
```

Running these shows the project only containing one version of `react` and `react-dom` except those bundled in `next` so it doesn't seem to be multiple react versions and our ESLint isn't complaining about "Rules of Hooks".
```bash
❯ grep -R '"name": "react"'
./node_modules/.pnpm/react@18.2.0/node_modules/react/package.json:  "name": "react",

❯ grep -R '"name": "react-dom"'
./node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/package.json:  "name": "react-dom",
```

### Describe the Bug

It runs `useEffect` on SSR.

### Expected Behavior

Don't expect `useEffect` to run on SSR.

https://react.dev/reference/react/useEffect#caveats
![image](https://github.com/vercel/next.js/assets/476567/39ac12eb-0c94-4393-9922-f6ed32f4a143)

**Comment by EloB** [comment]
I saw that `next` contains a bundled `react` and `react-dom`. Maybe it's some type of conflict here?

https://unpkg.com/browse/next@13.4.19/dist/compiled/react/
https://unpkg.com/browse/next@13.4.19/dist/compiled/react-dom/

**Comment by EloB** [comment]
I've been debugging this issue for 3 days. The team/client has decided to not invest more time into this. Maybe in the future.

I think it might have something todo with the bundled version and `node_modules/` of `react/react-dom` somehow conflicting. We don't have any babel and pretty clean `next.config.js`. How does you bundle version of react work?

Is Next.js battle tested with `pnpm`? I don't use it except from my current client.

**Comment by jvandenaardweg** [comment]
I'm seeing the exact same error. Just using regular npm. No custom server logic. Am using react-query. Using pages dir. Using turborepo.

I've (also) tracked it down to being a problem since 13.4.13: https://github.com/vercel/next.js/releases/tag/v13.4.13

Works fine on 13.4.12 and lower. Once I upgrade to 13.4.13 I get the error like @EloB mentioned.

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useEffect')
    at Module.useEffect (/Users/jordy/Projects/**********/node_modules/react/cjs/react.development.js:1634:21)
    at QueryClientProvider (file:///Users/jordy/Projects/**********/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)
    at renderWithHooks (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8738:16)
    at renderIndeterminateComponent (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8812:15)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9047:7)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderContextProvider (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9011:3)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9124:11)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderIndeterminateComponent (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8866:7)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9047:7)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderIndeterminateComponent (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8866:7)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9047:7)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderIndeterminateComponent (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8866:7)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9047:7)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderNode (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9392:12)
    at renderChildrenArray (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9341:7)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9249:7)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9073:9)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderNode (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9392:12)
    at renderChildrenArray (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9341:7)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9249:7)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9073:9)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderContextProvider (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9011:3)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9124:11)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderContextProvider (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9011:3)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9124:11)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderIndeterminateComponent (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8866:7)
    at renderElement (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9047:7)
    at renderNodeDestructiveImpl (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9213:11)
    at renderNodeDestructive (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:14)
    at renderContextProvider (/Users/jordy/Projects/**********/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9011:3)
```

**Comment by EloB** [comment]
@jvandenaardweg do you also have apollo client?

**Comment by jvandenaardweg** [comment]
@EloB nope!

**Comment by EloB** [comment]
@jvandenaardweg Good to know. I thought it maybe was that. It's weird that `renderWithHooks` is ran on server.

Have you tried to add in next.config.js? That fixed some of the issues but wasn't fully working.
```
experimental: {
  appDir: false,
},
```

**Comment by jvandenaardweg** [comment]
With `appDir: false` I get this error, instead of the one I posted earlier. Same one as you mentioned in your post.

```
Error: Failed to initialize render worker app
    at invokeRender (/Users/jordy/Projects/**********/node_modules/next/dist/server/lib/router-server.js:240:23)
    at handleRequest (/Users/jordy/Projects/**********/node_modules/next/dist/server/lib/router-server.js:447:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestHandler (/Users/jordy/Projects/**********/node_modules/next/dist/server/lib/router-server.js:464:13)
    at async Server.<anonymous> (/Users/jordy/Projects/**********/node_modules/next/dist/server/lib/start-server.js:117:13)
```

**Comment by joshua-lawrence** [comment]
Only one developer on our team is encountering this issue.. same setup with pnpm and Next 13.4.19. The app runs fine, his console is just unreadable.

```
velvet-ui git:staging  
❯ pnpm i                          
Lockfile is up to date, resolution step is skipped
Packages: +525 -311
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------------------------------------------------

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.6.5 → 8.6.12.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.6.12   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Progress: resolved 525, reused 516, downloaded 9, added 309, done

dependencies:
+ @mui/x-date-pickers 6.11.2
+ @tanstack/query-sync-storage-persister 5.0.0-beta.18
- @tanstack/react-query 4.33.0
+ @tanstack/react-query 5.0.0-beta.19
+ @tanstack/react-query-devtools 5.0.0-beta.19
+ @tanstack/react-query-persist-client 5.0.0-beta.19
+ dayjs 1.11.9

devDependencies:
- @types/testing-library__jest-dom 5.14.0
+ @types/testing-library__jest-dom 5.14.9

Done in 5.9s
                                                                                                                                                                                                                                                                                     
velvet-ui git:staging  6s
❯ pnpm dev

> velvet_ui@0.1.0 dev /Users/redacted/Developer/velvet/velvet-ui
> next dev

- info Loaded env from /Users/redacted/Developer/velvet/velvet-ui/.env.local
- ready started server on [::]:3000, url: http://localhost:3000
- event compiled client and server successfully in 532 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 63 ms (20 modules)
- info Loaded env from /Users/redacted/Developer/velvet/velvet-ui/.env.local
- info Loaded env from /Users/redacted/Developer/velvet/velvet-ui/.env.local
- wait compiling /(dashboard)/(individual)/page (client and server)...
- event compiled client and server successfully in 5.4s (3466 modules)
AccessTokenError: The user does not have a valid session.
    at Object.eval [as getAccessToken] (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/session/get-access-token.js:22:19)
    at async attachAccessToken (webpack-internal:///(rsc)/./hooks/make-server-request.tsx:22:24)
    at async handleRequest (webpack-internal:///(rsc)/./hooks/make-server-request.tsx:38:32) {
  code: 'ERR_MISSING_SESSION',
  cause: undefined,
  status: undefined
}
- wait compiling /api/auth/[auth0]/route (client and server)...
- error node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/session/get-access-token.js (17:18) @ Object.eval [as getAccessToken]
- error unhandledRejection: Error [AccessTokenError]: The user does not have a valid session.
    at Object.eval [as getAccessToken] (webpack-internal:///(rsc)/./node_modules/.pnpm/@auth0+nextjs-auth0@3.1.0_next@13.4.19/node_modules/@auth0/nextjs-auth0/dist/session/get-access-token.js:22:19)
    at async attachAccessToken (webpack-internal:///(rsc)/./hooks/make-server-request.tsx:22:24)
    at async handleRequest (webpack-internal:///(rsc)/./hooks/make-server-request.tsx:38:32) {
  digest: undefined
}
null
- event compiled client and server successfully in 3.2s (3423 modules)
nextjs-auth0 is attempting to set cookies from a server component,see https://github.com/auth0/nextjs-auth0#important-limitations-of-the-app-directory
- wait compiling /onboarding/page (client and server)...
- wait compiling /_error (client and server)...
- event compiled client and server successfully in 1808 ms (4181 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useReducer')
    at Object.useReducer (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react/cjs/react.development.js:1760:21)
    at ReactDevOverlay (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:857:969)
    at ReactDevOverlay (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:96:12)
    at renderWithHooks (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at retryTask (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6528:5)
    at performWork (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6576:7)
    at /Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6902:12
    at scheduleWork (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:77:3)
    at startWork (/Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6901:3)
    at /Users/redacted/Developer/velvet/velvet-ui/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6996:5... (151 KB left)
    ```

**Comment by EloB** [comment]
Maybe reopen this? Since it's not one person issue. Multiple different consumers getting the same problem.

**Comment by balazsorban44** [comment]
@elob see https://github.com/vercel/next.js/issues/54429#issuecomment-1690063173

None of the other comments are providing helpful information to track this down.

> The team/client has decided to not invest more time into this. Maybe in the future.

If this is not true anymore, the correct action here that provides the most help for us to investigate is to open a new issue with a **minimal reproduction**.
