### ISSUE TITLE
Retrieving cookie in route handler

### ISSUE THREAD

**Issue by Revaycolizer** [vercel/next.js#54493]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Revaycolizer/minimal-repo

### To Reproduce

Error retrieving user token: TypeError: Cannot read properties of undefined (reading 'value')
    at GET (webpack-internal:///(rsc)/./app/api/login/route.ts:94:47)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:254:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/trace/tracer.js:111:36)
    at NoopContextManager.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NoopTracer.startActiveSpan (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:953:34)
    at ProxyTracer.startActiveSpan (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:993:36)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/trace/tracer.js:100:107)
    at NoopContextManager.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(rsc)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NextTracerImpl.trace (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/trace/tracer.js:100:32)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:242:53)
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at Object.wrap (webpack-internal:///(rsc)/./node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:42:24)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:196:97)
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at Object.wrap (webpack-internal:///(rsc)/./node_modules/next/dist/server/async-storage/request-async-storage-wrapper.js:82:24)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:195:75)
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at AppRouteRouteModule.execute (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:192:56)
    at AppRouteRouteModule.handle (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:315:41)
    at doRender (D:\project\next-backend\node_modules\next\dist\server\base-server.js:1103:56)
    at cacheEntry.responseCache.get.incrementalCache.incrementalCache (D:\project\next-backend\node_modules\next\dist\server\base-server.js:1312:34)
    at D:\project\next-backend\node_modules\next\dist\server\response-cache\index.js:99:42
    at ResponseCache.get (D:\project\next-backend\node_modules\next\dist\server\response-cache\index.js:149:11)
    at DevServer.renderToResponseWithComponentsImpl (D:\project\next-backend\node_modules\next\dist\server\base-server.js:1231:53)
    at D:\project\next-backend\node_modules\next\dist\server\base-server.js:813:121
    at NextTracerImpl.trace (D:\project\next-backend\node_modules\next\dist\server\lib\trace\tracer.js:90:20)
    at DevServer.renderToResponseWithComponents (D:\project\next-backend\node_modules\next\dist\server\base-server.js:813:41)
    at DevServer.renderPageComponent (D:\project\next-backend\node_modules\next\dist\server\base-server.js:1463:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DevServer.renderToResponseImpl (D:\project\next-backend\node_modules\next\dist\server\base-server.js:1507:32)
    at async DevServer.pipeImpl (D:\project\next-backend\node_modules\next\dist\server\base-server.js:735:25)
    at async DevServer.handleCatchallRenderRequest (D:\project\next-backend\node_modules\next\dist\server\next-server.js:695:13)
    at async DevServer.handleRequestImpl (D:\project\next-backend\node_modules\next\dist\server\base-server.js:647:17)
Failed to fetch users
undefined

### Describe the Bug

cannot retrieve cookie using get request although the logic is implement within the same route

### Expected Behavior

A cookie should be retrieved using a get request so as to be directly consumed in the frontend rather than returning a null value

### Which browser are you using? (if relevant)

Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by balazsorban44** [comment]
Duplicate, see https://github.com/vercel/next.js/issues/54432#issuecomment-1690057619
