### ISSUE TITLE
Pages opted into dynamic rendering don't have access to production filesystem (EONOENT)

### ISSUE THREAD

**Issue by KnowIsPow** [vercel/next.js#54804]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
    Binaries:
      Node: 20.1.0
      npm: 9.6.4
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/romantic-ptolemy-qlvdz4?file=%2Fnext.config.js%3A1%2C1

## ✅ Working Code
This version of the code does not use "searchParams".

```js
export default async function Page({
  params,
}) {
  const category = await getArticle(params.category);

  if (!category) {
    notFound();
  }

  // configure the default search settings
  const relatedData = await externalLibraryFetch();

  return (
    <main>
        <Suspense fallback={"Loading..."}>
            <RelatedItems data={relatedData} />
        </Suspense>
     </main>
  );
}
```

## ❌ NOT WORKING Code
This version of the code uses searchParams. When searchParams is used, [Next.js 13 opts the page into dynamic rendering.](https://nextjs.org/docs/app/api-reference/file-conventions/page#searchparams-optional)

```js
export default async function Page({
  params,
  searchParams,
}) {
  const category = await getArticle(params.category);

  if (!category) {
    notFound();
  }

  // configure the default search settings
  const relatedData = await externalLibraryFetch({...searchParams});

  return (
    <main>
        <Suspense fallback={"Loading..."}>
            <RelatedItems data={relatedData} />
        </Suspense>
     </main>
  );
}
```

(Apologies I'm not familiar with code sandbox and had a hard time reproducing there)

### Describe the Bug

When deploying a Next.js 13 (with app dir) on Vercel, I'm seeing the following error:

```
Error: ENOENT: no such file or directory, scandir '/var/task/src/app/data/markdown'
    at Object.readdirSync (node:fs:1527:3)
    at readAllFiles (/var/task/.next/server/chunks/1833.js:41:41)
    at readAllFiles.next (<anonymous>)
    at /var/task/.next/server/chunks/1833.js:64:16
    at /var/task/.next/server/chunks/9755.js:11502:23
    at getArticle (/var/task/.next/server/chunks/1833.js:93:28)
    at VacationRentalCategoryPage (/var/task/.next/server/app/(vacation-rentals)/vacation-rentals/[category]/page.js:492:112)
    at preloadComponent (/var/task/node_modules/next/dist/server/app-render/preload-component.js:23:22)
    at /var/task/node_modules/next/dist/server/app-render/app-render.js:615:101
    at async createComponentTree (/var/task/node_modules/next/dist/server/app-render/app-render.js:615:29) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/var/task/src/app/data/markdown'
}
```

This error only occurs on pages which have been opted into dynamic rendering by Next.js.

The problematic code retrieves a list of markdown files from the filesystem using the "fs" module. Here is the implementation of the code

```js
import fs from 'fs';
import path from 'path';

export function* readAllFiles(dir: string): Generator<string> {
  const files = fs.readdirSync(dir, { withFileTypes: true });

  for (const file of files) {
    if (file.isDirectory()) {
      yield* readAllFiles(path.join(dir, file.name));
    } else {
      yield path.join(dir, file.name);
    }
  }
}
```

```js
export const getArticles = cache(async () => {
  const articles = [];

  const articleDirectory = path.resolve(process.cwd(), 'src/app/data/markdown');

  for (const file of readAllFiles(articleDirectory)) {
    if (path.extname(file) === '.mdx') {
      const source = await fs.readFile(file, 'utf8');
      const { content, data } = matter(source);

      articles.push({
        content,
        slug: path.parse(file).name,
        file,
      });
    }
  }

  return articles;
});

export async function getArticle(slug) {
  const articles = await getArticles();
  return articles.find(article => article.slug === slug);
}
```

✅ In development, these files are available on both statically rendered and dynamically rendered pages.
✅ In production (Vercel), on statically rendered pages, these files are available.
❌ In production (Vercel), on pages which have been opted into dynamic rendering, these files are unavailable.

It seems like the issue may be similar to https://github.com/vercel/next.js/discussions/16117 and [this stackoverflow post](https://stackoverflow.com/questions/76696417/vercel-error-no-such-file-or-directory-open-var-task-node-modules-shiki-theme).

From what I can gather, the markdown files are not being bundled into the server environment, and are not accessible at runtime.

### Expected Behavior

/var/task/src/app/data/markdown should be an accessible directory in Vercel production.

On routes which have not been opted into dynamic rendering, this directory is accessible. and the readAllFiles() function can retrieve its contents.

In routes which are dynamically rendered, this directory is inaccessible.

The expected behavior is that it is accessible in both situations.

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
The reproduction seems a bit broken. The first issue is the path `src/app/data/markdown`, which does not exist, there is no `src` directory in the reproduction.

Then `externalLibraryFetch` does not return an array but expects one later on when calling `.map()`, causing another build-time error. Also, `notFound()` was not imported, also causing another issue.

Fixing these and deploying to Vercel I don't see the issue you are describing. https://nextjs-54804.vercel.app/static/test?hi

Can you please correct your reproduction so we can resume investigating?

These are small issues, but I recommend testing your own reproduction before opening an issue in the future. If you are unfamiliar with CodeSandbox, it's perfectly fine to use a GitHub repository instead.

In this issue, it's probably even better, so I can deploy my own version of the code.

**Comment by KitsonBroadhurst** [comment]
I've been running into this issue for a week or so now and I've been struggling to find the exact issue - this was it!

To help with debugging, I've created a minimal reproducible example:
https://github.com/KitsonBroadhurst/next-issue-54804

Running locally you will see the articles listed, but once it's deployed the articles fail to load:
https://next-issue-54804.vercel.app/library

Removing the searchParams results in the deployed page loading correctly. I've created a branch "without params":
https://github.com/KitsonBroadhurst/next-issue-54804/commit/a7ffa438d14abd6d4e3ec800e3c7912b9fdfc38f

The deployed version without searchParams is accessible here:
https://next-issue-54804-git-without-params-kitson.vercel.app/library

**Comment by KnowIsPow** [comment]
@KitsonBroadhurst thanks so much for adding this!

I made a separate content directory outside of "src" directory and that seemed to address the issue.

**Comment by KitsonBroadhurst** [comment]
@KnowIsPow that's interesting to know! In my case it wouldn't solve the issue as the content is within a folder group which has it's own `layout.tsx` and is covered by an Auth wrapper.

**Comment by KitsonBroadhurst** [comment]
@KnowIsPow I've re-written my implementation to use `next-mdx-remote/rsc` and source the articles from a folder outside of src too in the end. Shame that the standard routing won't support `searchParams`

**Comment by KnowIsPow** [comment]
@KitsonBroadhurst yeah seems like a largely overlooked and under-documented issue for anyone looking to create a markdown blog with server functionality.

In terms of using searchParams, looking through a few projects, looks like I have one that uses both mdx-remote/rsc and searchParams. It's for a ECommerce app, with a list of products.

I'm loading the product category pages (MDX files) from a content directory outside of src, and using generateStaticParams to prebuild the pages... When the user updates the search filters it updates search params which are then applied. Would this be a helpful use case for you?

Glad you were able to make something work in the end!

**Comment by leonardofaria** [comment]
I was creating a function to generate custom sitemaps and hit the same issue: dynamic routes are not listed indeed.

Found this package that might help: https://github.com/Emiyaaaaa/next-routes-list
