### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by filmerjarred** [vercel/next.js#54899]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
NOTE: Installing next@canary caused a bunch of `ERESOLVE` errors, so I have not tested with it

 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant Packages:
      next: 13.4.20-canary.15
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Sage-Future/fatebook/tree/revision-test

### To Reproduce

Push to vercel and load page

Issue deployment here https://vercel.com/sage-org/forecast-bot/6CiFTtcpywgQBwxYUpPJHTVQwZPz

### Describe the Bug

We pushed a new version of our app to production today and started seeing "MaxListenersExceededWarning" warnings.

What we tried:

1. "Instant rollback" made the warnings stop, _however_
2. forking the code identical to the rolled back commit and deploying to a new branch still had the warnings
3. Updating the deploy install command to `npm ci` and clearing the build cache didn't help

I figured out how to get a stack trace for the warnings, and this is what we see:

```
  (node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
  MaxListenersExceededWarning
  Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
  MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
      at _addListener (node:events:588:17)
      at ClientRequest.prependListener (node:events:620:14)
      at ClientRequest.prependOnceListener (node:events:665:12)
      at mod.request (/var/task/___vc/__launcher.js:190:13)
      at Bridge.handleEvent (/var/task/___vc/__launcher.js:617:31)
      at async Bridge.launcher [as handler] (/var/task/___vc/__launcher.js:474:26)
```
    
My guess is this `__launcher.js:190:13` has been updated in the last couple days and this is causing the issue. We don't see the warnings when we use "instant rollback" as I assume it's using a cached version of `launcher.js`

I can see 2 other issues potentially related, https://github.com/vercel/next.js/issues/53949 and https://github.com/vercel/next.js/issues/54104

### Expected Behavior

Our logs not being full of memory leak warnings

### How are you deploying your application? (if relevant)

vercel

**Comment by DB-Alex** [comment]
We have the same all over our logs in vercel:

```
(node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
(node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
(node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
```

**Comment by Renetnielsen** [comment]
same here:

```
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
(node:97237) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
```

**Comment by devjiwonchoi** [comment]
Hey @filmerjarred https://vercel.com/sage-org/forecast-bot/6CiFTtcpywgQBwxYUpPJHTVQwZPz this link is only visible for you.

**Comment by san-pblr-gct** [comment]
Same here. 
<img width="343" alt="image" src="https://github.com/vercel/next.js/assets/12759816/e9fc7c55-6531-43ed-a05f-45b4b192f51e">

**Comment by devjiwonchoi** [comment]
@filmerjarred @Renetnielsen @san-pblr-gct @DB-Alex Y'all need to provide some valid repros. Sharing logs or undeployable repos doesn't help to fix this issue.

**Comment by filmerjarred** [comment]
Seems fixed now, we're not seeing it with new deploys.

And this probably wanted to be a vercel support request rather than a nextjs issue.

Was hoping someone could eyeball whatever had changed within the last week around `/var/task/___vc/__launcher.js:190:13` within the vercel code and it would be obvious whatever it adding listeners.

**Comment by elie222** [comment]
Facing the exact same issue as others. So not sure what that supposed fix is.

I can't provide a repo as it's our entire codebase, and don't have the time to try create a reproduction that is smaller. If I knew what was causing it I'd fix it.

I'm using Prisma with data proxy as a best guess but actually have no idea what's causing it.

**Comment by GainorB** [comment]
Same issue here. Looking to move my deployment to Vercel, and I am seeing this error in the logs while trying to debug next-auth issues as well.

**Comment by rawestmoreland** [comment]
Seeing the same issue. We've rolled back our production app. We're seeing these `Maximum call stack size exceeded` errors as well. Also referencing `/var/task/___vc/__launcher.js`

**Comment by tpae** [comment]
Seeing this as well

**Comment by wwei-github** [comment]
How to solve this problem？

**Comment by youminkim** [comment]
We see MaxListenersExceededWarning errors from many severless functions.

It happens only to deployments after today 4:30 pm (Singapore time). We instant rollbacked to previous build and it works fine without errors.

```(node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit```

**Comment by domharrington** [comment]
Seeing lots of these errors rolling into our Vercel logs in the past 30 mins or so.

**Comment by angelpadillar** [comment]
This also began happening ~2 hours ago. All was good yesterday.

`(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit
`

**Comment by marcelocch** [comment]
Same here in our account "artisan-labs" my project is "brisas-titicaca"
Same logs
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]

**Comment by devPablo** [comment]
This is happening on our end as well, error message: `(node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit`

**Comment by domharrington** [comment]
I just created a support case on Vercel: https://vercel.com/help I will update in here if I hear anything.

**Comment by christopherliedtke** [comment]
> We see MaxListenersExceededWarning errors from many severless functions.
> 
> It happens only to deployments after today 4:30 pm (Singapore time). We instant rollbacked to previous build and it works fine without errors.
> 
> `(node:15) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 response listeners added to [ClientRequest]. Use emitter.setMaxListeners() to increase limit`

I do have the same problem and rolling back didn't work for me unfortunately. This issue should be reopened.

**Comment by maccman** [comment]
We're seeing the same issue.

**Comment by kitajchuk** [comment]
Also having this issue.

**Comment by Fruchtix** [comment]
Same Issue over here. Any help is appreciated.
<img width="503" alt="Screenshot 2023-09-20 at 22 05 35" src="https://github.com/vercel/next.js/assets/47560593/10acfd90-64e9-433c-a676-f127297971cb">

**Comment by askkaz** [comment]
Same issue here.

**Comment by theZaX** [comment]
Same issue here. Connected to axiom and sentry on vercel.

**Comment by christopherliedtke** [comment]
> Same issue here - seeing this on all of our API routes (page router). We tried redeploying the older version of our code on Vercel that was working and it is now exhibiting the same behavior. Suspect something underlying in the Vercel infrastructure. We're on Next 13.4.19.

For all API routes on page router mode as well. `"next": "^13.5.2",`

**Comment by holcz** [comment]
Same issue for us as well. Our stack that can be relevant: 
```
"next": "~12.1.6",
"next-auth": "~4.20.1",
"next-axiom": "^0.14.0",
"@next-auth/prisma-adapter": "^1.0.3",
"prisma": "4.8.1",
```
Connected to Axiom.
Thanks for looking into this.

**Comment by danielhochman** [comment]
Same issue here. I have opened a support case with Vercel and I would suggest anyone experiencing the problem to do the same, as this is likely an issue with their environment.

**Comment by christopherliedtke** [comment]
seems to be fixed according to my logs now 👍
