### ISSUE TITLE
Next 13 updating subproject in monorepo causing TypeError

### ISSUE THREAD

**Issue by AntonZaikaFXE** [vercel/next.js#55017]
### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/fervent-hooks-28vh4m?file=/exaple-project/next.congig.js:17,1

### To Reproduce

In monorepo project (lerna) with main package.json dependencies
    "next": "12.2.5",
    "react": "18.1.0",
    "react-dom": "18.1.0"
 and node version v16.20.2 
 update subproject to next 13 with external next.config configuration:
 
 /** @type {import('next').NextConfig} */
const config = require('fx-config');

const withTM = require('next-transpile-modules')(config.transpiledModules);
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true'
});

const nextConfig = {
  ...config.nextConfig
};

module.exports = withBundleAnalyzer(withTM(nextConfig));

----
the actual error: 

TypeError: Cannot read properties of undefined (reading 'push')
    at writeConfigurationDefaults (/Users/Projects/-ui/packages/fx-app-currencies/node_modules/next/dist/lib/typescript/writeConfigurationDefaults.js:229:30)
    at async verifyTypeScriptSetup (/Users/Projects/-ui/packages/fx-app-currencies/node_modules/next/dist/lib/verifyTypeScriptSetup.js:120:9)
    at async verifyTypeScript (/Users/Projects/-ui/packages/fx-app-currencies/node_modules/next/dist/server/lib/router-utils/setup-dev.js:95:26)
    at async startWatcher (/Users/Projects/-ui/packages/fx-app-currencies/node_modules/next/dist/server/lib/router-utils/setup-dev.js:116:29)
    at async setupDev (/Users/Projects/-ui/packages/fx-app-currencies/node_modules/next/dist/server/lib/router-utils/setup-dev.js:1032:20)
    at async initialize (/Users/Projects/-ui/packages/fx-app-currencies/node_modules/next/dist/server/lib/router-server.js:68:23)
    at async Server.<anonymous> (/Users/Projects/-ui/packages/fx-app-currencies/node_modules/next/dist/server/lib/start-server.js:178:36)
  

### Current vs. Expected behavior

Expecting to upgrade for next 13

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
OS: Mac
Node: v16.20.2 
Next: 12.2.5
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

Tested with different node version and next canaries but it not helped

**Comment by AntonZaikaFXE** [comment]
I have tried 13.4.20-canary.16 and it didn't help the error is the same

**Comment by RusseII** [comment]
Same issue.
