### ISSUE TITLE
Custom server + App router doesn't run in dev mode

### ISSUE THREAD

**Issue by coltonehrman** [vercel/next.js#55278]
### Link to the code that reproduces this issue or a replay of the bug

https://app.replay.io/recording/untitled--434d663c-8bfa-4630-9489-80ca45309b22

### To Reproduce

1. `npx create-next-app@latest`
2. Install canary `npm i next@canary`
3. Add custom server (https://nextjs.org/docs/pages/building-your-application/configuring/custom-server)
4. Switch dev script to use `node server.js`
5. Run `npm run dev`

### Current vs. Expected behavior

App should work.

What happens?

```
❯ npm run dev

> my-app@0.1.0 dev
> node server.js

 ✓ ready
> Ready on http://localhost:3000
 ○ compiling /page ...
 X Error: Cannot find module 'react-server-dom-webpack/client.edge'
Require stack:
- /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js
- /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/lib/router-utils/setup-dev.js
- /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/lib/router-server.js
- /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/lib/start-server.js
- /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/next.js
- /Users/cehrman/WebPlatform/my-app/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/require-hook.js:16:36
    at Function.resolve (node:internal/modules/cjs/helpers:114:19)
    at deleteAppClientCache (/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js:51:41)
    at /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js:117:17
    at Hook.eval [as callAsync] (eval at create (/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:21:17)
    at /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:28:144800
    at /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/compiled/neo-async/async.js:1:9372
    at done (/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/compiled/neo-async/async.js:1:14788)
    at Hook.eval [as callAsync] (eval at create (/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:15:1)
    at /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:28:143189
    at /Users/cehrman/WebPlatform/my-app/node_modules/next/dist/compiled/webpack/bundle5.js:1:268008
    at /Users/cehrman/WebPlatform/my-app/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js',
    '/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/lib/router-utils/setup-dev.js',
    '/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/lib/router-server.js',
    '/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/lib/start-server.js',
    '/Users/cehrman/WebPlatform/my-app/node_modules/next/dist/server/next.js',
    '/Users/cehrman/WebPlatform/my-app/server.js'
  ]
}
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
Binaries:
  Node: 16.20.1
  npm: 8.19.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.4.20-canary.25
  eslint-config-next: 13.4.19
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Standalone mode (output: "standalone")

### Additional context

Seems to be related to this PR https://github.com/vercel/next.js/pull/54813

<sub>[NEXT-1612](https://linear.app/vercel/issue/NEXT-1612/custom-server-app-router-doesnt-run-in-dev-mode)</sub>

**Comment by coltonehrman** [comment]
Is custom server a thing with the App router? Based on the docs, I do not see any reference to custom server under the App router section. However, I do see it under the Pages router section.

<img width="728" alt="Screenshot 2023-09-12 at 10 47 31 AM" src="https://github.com/vercel/next.js/assets/12456288/838f5f82-674c-44ce-ba8c-26a14dd0b650">

@timneutkens

**Comment by fedetorre** [comment]
Hi @coltonehrman ,

I have the same issue without custom server and latest canary release, rolling back to version 13.4.20-canary.23 and the problem disappear!

Below the stacktrace:
```
Error: Cannot find module 'react-server-dom-webpack/client.edge'
Require stack:
- /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js
- /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/server/lib/router-utils/setup-dev.js
- /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/server/lib/router-server.js
- /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/server/lib/start-server.js
- /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/cli/next-dev.js
- /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/lib/commands.js
- /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/server/require-hook.js:16:36
    at Function.resolve (node:internal/modules/cjs/helpers:127:19)
    at deleteAppClientCache (/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js:51:41)
    at /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js:117:17
    at Hook.eval [as callAsync] (eval at create (/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:21:17)
    at /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/compiled/webpack/bundle5.js:28:144800
    at /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/compiled/neo-async/async.js:1:9372
    at done (/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/compiled/neo-async/async.js:1:14788)
    at Hook.eval [as callAsync] (eval at create (/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:15:1)
    at /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/compiled/webpack/bundle5.js:28:143189
    at /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/compiled/webpack/bundle5.js:1:268008
    at /home/fede/workspace/selfcommunity/community-pwa/app/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:200:23)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js',
    '/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/server/lib/router-utils/setup-dev.js',
    '/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/server/lib/router-server.js',
    '/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/server/lib/start-server.js',
    '/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/cli/next-dev.js',
    '/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/lib/commands.js',
    '/home/fede/workspace/selfcommunity/community-pwa/app/node_modules/next/dist/bin/next'
  ]
}
```

**Comment by karlhorky** [comment]
> rolling back to version 13.4.20-canary.23 and the problem disappear!

Indeed, it appears this bug was introduced in [`next@13.4.20-canary.24`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.24)

**Comment by karlhorky** [comment]
Custom Servers are also broken in production (`next build` + `next start`), I get the `renderToReadableStream is not a function` error (shown as an HTTP `500` status code to users):

```
[WebServer] TypeError: e.renderToReadableStream is not a function
    at /home/runner/work/courses/courses/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:1:62297
    at NextTracerImpl.trace (/home/runner/work/courses/courses/node_modules/next/dist/server/lib/trace/tracer.js:90:20)
    at O (/home/runner/work/courses/courses/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:1:62251)
    at /home/runner/work/courses/courses/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:1:179058
    at /home/runner/work/courses/courses/node_modules/next/dist/server/lib/trace/tracer.js:159:62
    at /home/runner/work/courses/courses/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/home/runner/work/courses/courses/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/home/runner/work/courses/courses/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/home/runner/work/courses/courses/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/home/runner/work/courses/courses/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
[WebServer]  ⚠ You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.
See here for info: https://nextjs.org/docs/messages/custom-error-no-custom-404
[WebServer] GET / 500 [43]4.286 ms - -
```

<img width="504" alt="Screenshot 2023-09-13 at 12 37 41" src="https://github.com/vercel/next.js/assets/1935696/4a07ff1d-bd77-467a-88f3-cdbf3067dfc4">

**Comment by feedthejim** [comment]
This is most likely #54813, we are taking a look!

**Comment by feedthejim** [comment]
Does this work in the latest canary? I landed a refactor that should affect this.

**Comment by karlhorky** [comment]
Still broken in latest canary on [Releases page](https://github.com/vercel/next.js/releases) (currently [`next@13.4.20-canary.33`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.33))

**Comment by feedthejim** [comment]
@karlhorky I can not manage to repro anymore after the latest canary, can you double check and/or share your error?

**Comment by karlhorky** [comment]
I'll check again with [`next@13.4.20-canary.35`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.35)

**Comment by karlhorky** [comment]
My error, I think [`next@13.4.20-canary.33`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.33) is working after all. I saw an error on Sunday, but I may have tricked myself or tested incorrectly.

Can confirm that [`next@13.4.20-canary.33`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.33) is working 🙌 

Updated my post above!
