### ISSUE TITLE
TypeError: handler is not a function

### ISSUE THREAD

**Issue by indapublic** [vercel/next.js#55514]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/indapublic/nextjs-issue

### To Reproduce

```npm run build```

### Current vs. Expected behavior

Expected: build is successful
Actual: 

```
> next build

- info Creating an optimized production build
- info Compiled successfully
- info Linting and checking validity of types
- info Collecting page data
[    ] - info Generating static pages (0/3)
Error occurred prerendering page "/domain/icon". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: handler is not a function
    at GET (/Volumes/Data/Workspace/issue/.next/server/app/domain/icon/route.js:87:10)
    at /Volumes/Data/Workspace/issue/.next/server/chunks/218.js:8897:43
    at /Volumes/Data/Workspace/issue/.next/server/chunks/218.js:9764:36
    at NoopContextManager.with (/Volumes/Data/Workspace/issue/.next/server/chunks/218.js:1598:30)
    at ContextAPI.with (/Volumes/Data/Workspace/issue/.next/server/chunks/218.js:1268:58)
    at NoopTracer.startActiveSpan (/Volumes/Data/Workspace/issue/.next/server/chunks/218.js:2191:34)
    at ProxyTracer.startActiveSpan (/Volumes/Data/Workspace/issue/.next/server/chunks/218.js:2231:36)
    at /Volumes/Data/Workspace/issue/.next/server/chunks/218.js:9753:107
    at NoopContextManager.with (/Volumes/Data/Workspace/issue/.next/server/chunks/218.js:1598:30)
    at ContextAPI.with (/Volumes/Data/Workspace/issue/.next/server/chunks/218.js:1268:58)
- info Generating static pages (3/3)

> Export encountered errors on following paths:
	/domain/icon/route: /domain/icon
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

After canary install error still exists, but with message some changed:

```
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/3) [    ]
Error occurred prerendering page "/domain/icon". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: u is not a function
    at l (/Volumes/Data/Workspace/issue/.next/server/app/domain/icon/route.js:1:772)
    at /Volumes/Data/Workspace/issue/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:1:45649
    at /Volumes/Data/Workspace/issue/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/Volumes/Data/Workspace/issue/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Volumes/Data/Workspace/issue/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/Volumes/Data/Workspace/issue/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/Volumes/Data/Workspace/issue/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /Volumes/Data/Workspace/issue/node_modules/next/dist/server/lib/trace/tracer.js:106:107
    at NoopContextManager.with (/Volumes/Data/Workspace/issue/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/Volumes/Data/Workspace/issue/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
 ✓ Generating static pages (3/3)

> Export encountered errors on following paths:
	/domain/icon/route: /domain/icon
```

But if change `icon` to `icons` - build works! 🤯

**Comment by icyJoseph** [comment]
The problem is that `icon` is a special metadata file convention:

- https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#icon

**Comment by indapublic** [comment]
Thank you, but regarding to docs icon file can only be located in the top level of `app/` but here is inside of `domain` folder. Sorry, not big experienced with Next, it can be skipped somehow? (Really don't want to change name convention for that). Thank you again @icyJoseph

**Comment by icyJoseph** [comment]
> Use an image file to set an app icon by placing a favicon, icon, or apple-icon image file within your /app directory. The favicon image can only be located in the top level of app/.

It is only the favicon that can be top level like that. Everything else says, within your app directory.

**Comment by icyJoseph** [comment]
Maybe you could use: 

- https://nextjs.org/docs/app/building-your-application/routing/colocation#private-folders

**Comment by indapublic** [comment]
Thank you @icyJoseph. I'll leave this topic as opened for some days (maybe others answers can be collected) and I'll close it after. Thank you

**Comment by huozhi** [comment]
Hi thanks @icyJoseph to mention the convention [here](https://github.com/vercel/next.js/issues/55514#issuecomment-1722940160) `icon.[ext]` is a special convention for metadata API, so you might want to rename that file to sth else as it will be built into a route that serving the icon
