### ISSUE TITLE
`optimizePackageImports` doesn't work with nested MUI Material components

### ISSUE THREAD

**Issue by mwskwong** [vercel/next.js#55566]
### Link to the code that reproduces this issue

https://github.com/mwskwong/optimize-package-imports-with-mui-material

### To Reproduce

1. Create an arbitrary component that imports from MUI Material using named import, (e.g. it is called `NestedMui` in the repo)
    ```tsx
    import { Button } from "@mui/material";

    export const NestedMui = () => <Button>test</Button>;
    ```

2. Import this component in `page` or `layout`, within another MUI component imported via named import.
    ```tsx
    import { Box } from "@mui/material";
    import { NestedMui } from "../components/nested-mui";

    /** Add your relevant code here for the issue to reproduce */
    export default function Home() {
      return (
        <Box>
          Hello world <NestedMui />
        </Box>
      );
    }
    ```

### Current vs. Expected behavior

Current: the following errors are observed when build

```
> build
> next build

 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (2/4) [=   ]
Error: Could not find the module "\node_modules\@mui\material\node\Box\index.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at Pe (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:252228)
    at \node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:263750
    at Array.toJSON (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:264845)
    at stringify (<anonymous>)
    at Me (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:253295)
    at Ie (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:253826)
    at Timeout._onTimeout (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:251644)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Could not find the module "\node_modules\@mui\material\node\Box\index.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at Pe (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:252228)
    at \node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:263750
    at Array.toJSON (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:264845)
    at stringify (<anonymous>)
    at Me (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:253295)
    at Ie (\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:1:253826)

> Export encountered errors on following paths:
        /page: /
```

Expected: The project should build successfully.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.40
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by florianliebig** [comment]
I think this is an issue with the optimizePackageImports & Client components in general: https://github.com/vercel/next.js/issues/54967
