### ISSUE TITLE
Build fail when using `React.cache` in `sitemap.ts`

### ISSUE THREAD

**Issue by mwskwong** [vercel/next.js#55561]
### Link to the code that reproduces this issue

https://github.com/mwskwong/cache-in-sitemap

### To Reproduce

1. Call a function, e.g. fetcher, wrapped in `React.cache` in `sitemap.ts`
2. Attempt to build the project

### Current vs. Expected behavior

Current: the following error will appear during build

```
   Collecting page data ..TypeError: (0 , p.cache) is not a function
    at 5398 (\.next\server\app\sitemap.xml\route.js:1:605)
    at t (\.next\server\webpack-runtime.js:1:127)
    at a (\.next\server\app\sitemap.xml\route.js:1:1737)
    at \.next\server\app\sitemap.xml\route.js:1:1764
    at t.X (\.next\server\webpack-runtime.js:1:1191)
    at \.next\server\app\sitemap.xml\route.js:1:1750
    at Object.<anonymous> (\.next\server\app\sitemap.xml\route.js:1:1791)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)

> Build error occurred
Error: Failed to collect page data for /sitemap.xml
    at \node_modules\next\dist\build\utils.js:1191:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

Expected: build should be successful

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.40
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by balazsorban44** [comment]
This is expected. The `sitemap.xml` is not a React Server Component, so `react` is not necessary.

Next.js will already cache the `fetch` call, which you can configure as described in https://nextjs.org/docs/app/api-reference/functions/fetch#optionscache if necessary.

**Comment by huozhi** [comment]
We patched a fix in next 13.5 that this API is available now for `sitemap.js`, but it's same like react server components, only the APIs available in react server components are available here. Thanks. So if it's in some util and being imported to the sitemap, these APIs should still be available
