### ISSUE TITLE
TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed

### ISSUE THREAD

**Issue by willianrod** [vercel/next.js#55608]
### Link to the code that reproduces this issue

https://github.com/willianrod/next-readable-stream-error

### To Reproduce

1. Run the project locally
2. Go to `/auth/login`
3. The app will redirect you to `/sample/list` after resolving the promise
4. You should now see the error on your console

### Current vs. Expected behavior

**Current:** Right now, when I'm navigating between pages with server components I'm seeing errors on my development console.
**Expected:** When navigating between pages no errors should be prompted

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.5.1
      eslint-config-next: 13.5.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

There is a discussion with more people with the same issue. The latest request was to update to the latest version `13.5.1` and see if the issue was still happening.

https://github.com/vercel/next.js/discussions/55027

```
Internal error: TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed
    at new NodeError (node:internal/errors:399:5)
    at ReadableByteStreamController.enqueue (node:internal/webstreams/readablestream:1150:13)
    at /path/to/app/readable-error/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:447268
    at ut (/path/to/app/readable-error/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:447318)
    at ct (/path/to/app/readable-error/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:446596)
    at Timeout._onTimeout (/path/to/app/readable-error/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:443766)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7
```

**Comment by icyJoseph** [comment]
Looks like a form of this error started to happen after:

- next@13.4.13-canary.4

Could someone else double check by using  next@13.4.13-canary.3, verify no error, and then use next@13.4.13-canary.4, to see the error?

**Comment by icyJoseph** [comment]
There doesn't seem to be anything that should trigger this between these canaries... 🤔

**Comment by willianrod** [comment]
@icyJoseph yep, I can confirm that the error started after `next@13.4.13-canary.4`.

```
TypeError [ERR_INVALID_STATE]: Invalid state: Unable to enqueue
    at new NodeError (node:internal/errors:399:5)
    at transformStreamDefaultControllerEnqueue (node:internal/webstreams/transformstream:488:11)
    at TransformStreamDefaultController.enqueue (node:internal/webstreams/transformstream:301:5)
    at Timeout._onTimeout (/path/to/app/readable-error/node_modules/next/dist/server/stream-utils/node-web-streams-helper.js:166:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ERR_INVALID_STATE'
}
- error unhandledRejection: TypeError [ERR_INVALID_STATE]: Invalid state: Unable to enqueue
    at new NodeError (node:internal/errors:399:5)
    at transformStreamDefaultControllerEnqueue (node:internal/webstreams/transformstream:488:11)
    at TransformStreamDefaultController.enqueue (node:internal/webstreams/transformstream:301:5)
    at Timeout._onTimeout (/path/to/app/readable-error/node_modules/next/dist/server/stream-utils/node-web-streams-helper.js:166:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  digest: undefined
}
- error TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed
```

If I would guess, the error is originated on [pipeReadable](https://github.com/vercel/next.js/compare/v13.4.13-canary.3...v13.4.13-canary.4#diff-9be48534a043c68023eef0f61dacd526b677c70ee3b61807b9da74a279aba2e5)

Diff between `next@13.4.13-canary.3` and `next@13.4.13-canary.4`
https://github.com/vercel/next.js/compare/v13.4.13-canary.3...v13.4.13-canary.4#diff-9be48534a043c68023eef0f61dacd526b677c70ee3b61807b9da74a279aba2e5R41

**Comment by icyJoseph** [comment]
Ah I had selected the wrong tags when comparing... 🤦‍♂️

**Comment by Hardel-DW** [comment]
https://github.com/Hardel-DW/next-issue

Same problem with <Suspense>
If I reload my page before the request is completed I get error messages.
If I reload very quickly several times, the requests seem to accumulate.
If I use "loading.tsx", the error looks different.
![image](https://github.com/vercel/next.js/assets/42413417/7a106322-fa23-4945-9358-182a5f83f5ca)

**Comment by FaryarKankash** [comment]
Same problem here 
i don't use suspense in my layout but i use loading.tsx file
this error doesn't cause any problem in my build

![Screenshot 2023-09-20 091244](https://github.com/vercel/next.js/assets/107303813/68f2fd27-1174-4d2d-a8c8-696b0efbe43c)

**Comment by andycansdale** [comment]
Yup, we're seeing the same in 13.5.1. I've not been able to track down the source of the error.

**Comment by Hardel-DW** [comment]
Problem still present in 13.5.2

**Comment by fadjrie** [comment]
experiencing that problem, how to fix?

**Comment by jridgewell** [comment]
This should be fixed by https://github.com/facebook/react/pull/27405

**Comment by cheryl-c-tirerack** [comment]
"next": "13.5.3-canary.1",
--- fixed for me! Thanks.

**Comment by igloo1505** [comment]
Has anyone noticed any actual negative effects from this? I'm working on two separate apps more or less simultaneously, and they're both experiencing this same error but both are performing as they should as far as I can tell, but it is a bit concerning...

**Comment by wriddhi** [comment]
@igloo1505 I'm facing this issue too but without having downsides in performance or code execution flow. I'm building an application for production. Have you seen/felt any real consequences/crashes issue with this yet or found a workaround? I really don't wanna rollback next to 13.4.5.

**Comment by huozhi** [comment]
Should be fixed by #56012 which carried the [react change](https://github.com/facebook/react/pull/27405)

**Comment by amyfranz** [comment]
I'm also still getting it on Next.js 13.5.3

**Comment by huozhi** [comment]
The fix is landed in [13.5.4-canary.2](https://github.com/vercel/next.js/releases/tag/v13.5.4-canary.2)

**Comment by cheryl-c-tirerack** [comment]
upgraded to [13.5.4-canary.2](https://github.com/vercel/next.js/releases/tag/v13.5.4-canary.2)

Now I get 
<img width="1165" alt="image" src="https://github.com/vercel/next.js/assets/132275474/e5a4aec6-b30f-46ac-bd1f-29509155f360">

**Comment by jridgewell** [comment]
@cheryl-c-tirerack That's a different issue, it just happen to originate from the same file. I'm not sure where we need to handle it.

**Comment by huozhi** [comment]
@cheryl-c-tirerack would be possible for you to file a reproduction in new issue? That would be super helpful for investigation 🙏

**Comment by cheryl-c-tirerack** [comment]
> @cheryl-c-tirerack would be possible for you to file a reproduction in new issue? That would be super helpful for investigation 🙏

I wouldn't begin to know what to reproduce minimally. I have a full backend running locally, and many nested dynamic paths. I'm using app directory, with TanStack/react-query.
It happens on any page that touches my api.
Exactly as the original issue, my api calls are in server components. 
It happens right after navigating to a new endpoint.
The description and the error are exactly as shown on this OP, without any authorization.

**Comment by dstarosta** [comment]
> upgraded to [13.5.4-canary.2](https://github.com/vercel/next.js/releases/tag/v13.5.4-canary.2)
> 
> still I get <img alt="image" width="1165" src="https://user-images.githubusercontent.com/132275474/271083250-e5a4aec6-b30f-46ac-bd1f-29509155f360.png">

I get the same issue as well. When I run Playwright tests it happens in the same place the old error was happening.

**Comment by Dev-Harmattan** [comment]
I get the same issue. is there any fix for this ?
`⨯ Internal error: TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed
    at new NodeError (node:internal/errors:405:5)
    at ReadableByteStreamController.enqueue (node:internal/webstreams/readablestream:1152:13)
    at /Users/sodiq/Desktop/potfolio-project/discord-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:461602`

**Comment by V-iktor** [comment]
> I get the same issue. is there any fix for this ?
> `⨯ Internal error: TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed at new NodeError (node:internal/errors:405:5) at ReadableByteStreamController.enqueue (node:internal/webstreams/readablestream:1152:13) at /Users/sodiq/Desktop/potfolio-project/discord-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:1:461602`

Try updating to the latest React canary - now I get the correct error message instead of ERR_INVALID_STATE

`yarn add react@18.3.0-canary-f81c0f1ed-20230927`

The correct message I get after upgrading

`TypeError: fetch failed`

**Comment by luistak** [comment]
Same here on `13.5.2` but debugging the error stacktrace i caught that this error occurs in this order:

![image](https://github.com/vercel/next.js/assets/19766035/50fcf03e-97ee-4581-be96-02ed6a154d1d)

1. `Server component Loading
2.  Error: The render was aborted by the server without a reason.
```
Error: The render was aborted by the server without a reason.
    at nR (/app/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:45:67960)
    at Object.cancel (/app/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:45:71720)
    at readableByteStreamControllerCancelSteps (node:internal/webstreams/readablestream:3022:37)
    at [kCancel] (node:internal/webstreams/readablestream:1166:12)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at readableStreamCancel (node:internal/webstreams/readablestream:1887:5)
    at node:internal/webstreams/readablestream:1439:15
    at complete (node:internal/webstreams/readablestream:1323:9)
    at shutdownWithAnAction (node:internal/webstreams/readablestream:1319:5)
    at node:internal/webstreams/readablestream:1438:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
3. TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed
```
TypeError [ERR_INVALID_STATE]: Invalid state: ReadableStream is already closed
    at new NodeError (node:internal/errors:405:5)
    at ReadableByteStreamController.enqueue (node:internal/webstreams/readablestream:1152:13)
    at u (/app/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:45:486)
    at nP (/app/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:45:67693)
    at nR (/app/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:45:68650)
    at Object.cancel (/app/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:45:71720)
    at readableByteStreamControllerCancelSteps (node:internal/webstreams/readablestream:3022:37)
    at [kCancel] (node:internal/webstreams/readablestream:1166:12)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at readableStreamCancel (node:internal/webstreams/readablestream:1887:5)
    at node:internal/webstreams/readablestream:1439:15
    at complete (node:internal/webstreams/readablestream:1323:9)
    at shutdownWithAnAction (node:internal/webstreams/readablestream:1319:5)
    at node:internal/webstreams/readablestream:1438:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
4. SocketError: other side closed
```
node:internal/deps/undici/undici in TLSSocket.onSocketEnd at line 9790:26
In App
node:events in TLSSocket.emit at line 526:35
In App
node:domain in TLSSocket.emit at line 489:12
In App
Called from: /app/app/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js in TLSSocket.emit
node:internal/streams/readable in endReadableNT at line 1359:12
In App
node:internal/process/task_queues in process.processTicksAndRejections at line 82:21
```

Which Sentry identified that may be related to this other issue https://github.com/vercel/next.js/issues/49896:
![image](https://github.com/vercel/next.js/assets/19766035/68dd0854-e8b1-4172-865f-9c599f2f2f27)

**Comment by Zanzofily** [comment]
I tried updating next and node to the latest versions, but the error was still present. It seems to be related to how caching is handled. Changing coaching to dynamic worked for me.

`export const dynamic = 'force-dynamic'`

**Comment by amiryxe** [comment]
I get this error when I **refresh the pages quickly** and one after another.

**Comment by DevOkone** [comment]
Je reçois  aussi le problème  sur Next.js 13.5.3 mais j'ai l'impression que l'erreur ce déclenche lorsque j'utilise suspense sur une page 
mais le code fonctionne bien en production
