### ISSUE TITLE
Turbopack with edge runtime cannot be used

### ISSUE THREAD

**Issue by azvyae** [vercel/next.js#55656]
### Link to the code that reproduces this issue

https://github.com/azvyae/minimal-repro

### To Reproduce

1. Set the runtime to `edge` in `layout.tsx`
2. Start the app with `next dev --turbo`

### Current vs. Expected behavior

It shows error:

```bash
next dev --turbo

>>> TURBOPACK (beta)

Thank you for trying Next.js v13 with Turbopack! As a reminder
Turbopack is currently in beta and not yet ready for production.
We appreciate your ongoing support as we work to make it ready
for everyone.


Learn more about Next.js v13 and Turbopack: https://nextjs.link/with-turbopack

  ▲ Next.js 13.5.2-canary.0
  - Local:        http://localhost:3000

 ✓ Ready in 907ms
thread 'tokio-runtime-worker' panicked at 'not yet implemented: edge pages are not supported yet', packages/next-swc/crates/next-core/src/next_app/app_page_entry.rs:133:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 X Error: A task panicked: not yet implemented: edge pages are not supported yet

Debug info:
- Execution of AppEndpoint::output failed
- A task panicked: not yet implemented: edge pages are not supported yet
    at withErrorCause (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/swc/index.js:391:19)
    at async EndpointImpl.writeToDisk (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/swc/index.js:581:20)
    at async Object.ensurePage (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev.js:890:73)
    at async Object.ensurePage (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:88:24)
    at async DevServer.ensurePage (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:517:9)
    at async Object.ensure (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:163:17)
    at async DevRouteMatcherManager.matchAll (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
    at async DevRouteMatcherManager.match (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:159:26)
    at async DevServer.handleCatchallRenderRequest (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:569:27)
    at async DevServer.handleRequestImpl (/home/azvyae/Code/azvyae/minimal-repro/node_modules/.pnpm/next@13.5.2-canary.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:722:17) {
  [cause]: [Error: A task panicked: not yet implemented: edge pages are not supported yet
  
  Debug info:
  - Execution of AppEndpoint::output failed
  - A task panicked: not yet implemented: edge pages are not supported yet] {
    code: 'GenericFailure'
  }
}
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #7-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 23 15:37:39 UTC 2023
    Binaries:
      Node: 20.3.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.5.2-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime), Turbopack (--turbo)

**Comment by balazsorban44** [comment]
Thanks, this is currently expected, as the message suggests.
