### ISSUE TITLE
`Image` component does not work with https `next dev`

### ISSUE THREAD

**Issue by peakercope** [vercel/next.js#55706]
### Link to the code that reproduces this issue

https://github.com/peakercope/material-ui-nextjs-pages-router-ts-example

### To Reproduce

1. Clone the example repo
2. Run `pnpm i`
3. Run `pnpm dev`
4. Open `https://localhost:3000/` in browser

### Current vs. Expected behavior

Current result: Banner is not visible

Expected result: Banner is visible

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.18.0
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: 7.25.0
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

Image response with 500 error code in browser with message `"url" parameter is valid but upstream response is invalid`
<img width="570" alt="image" src="https://github.com/vercel/next.js/assets/10975462/d5564ca1-c695-4d8f-9459-c99649af48b2">

Terminal console error:
```
upstream image response failed for /_next/static/media/half-page-banners-desktop-dog-coat.d9613929.jpeg TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async invokeRequest (/material-ui-nextjs-pages-router-ts/node_modules/.pnpm/next@13.5.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async /material-ui-nextjs-pages-router-ts/node_modules/.pnpm/next@13.5.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:362:39
    at async imageOptimizer (/material-ui-nextjs-pages-router-ts/node_modules/.pnpm/next@13.5.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/material-ui-nextjs-pages-router-ts/node_modules/.pnpm/next@13.5.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:519:61)
    at async /material-ui-nextjs-pages-router-ts/node_modules/.pnpm/next@13.5.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/response-cache/index.js:102:36 {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (/material-ui-nextjs-pages-router-ts/node_modules/.pnpm/next@13.5.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/undici/index.js:1:73361)
      at Socket.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1368:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '::1',
      localPort: 60275,
      remoteAddress: '::1',
      remotePort: 3000,
      remoteFamily: 'IPv6',
      timeout: undefined,
      bytesWritten: 946,
      bytesRead: 0
    }
  }
}
``` 

<sub>[NEXT-1646](https://linear.app/vercel/issue/NEXT-1646/image-component-does-not-work-with-https-next-dev)</sub>

**Comment by 0xABBCCC** [comment]
I was able to replicate your error after cloning but then I did these steps and the banner was visible with https
1. I deleted the certificates folder, removed --experimental-https
2. I run the demo without the experimental
3. I re added the experimental

App worked fine after doing this

**Comment by hipdev** [comment]
Ummm, I'm not able to reproduce the issue 🤔

![image](https://github.com/vercel/next.js/assets/48492084/6c5e4d94-53a2-4bac-b9c6-b2260ac8230e)

**Comment by moshie** [comment]
I've been getting a similar issue on our UAT environment it works on local:

```
upstream image response failed for /images/navbar/image.png TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/opt/application/node_modules/.pnpm/next@13.5.2_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async /opt/application/node_modules/.pnpm/next@13.5.2_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:362:39
    at async imageOptimizer (/opt/application/node_modules/.pnpm/next@13.5.2_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/opt/application/node_modules/.pnpm/next@13.5.2_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:519:61)
    at async /opt/application/node_modules/.pnpm/next@13.5.2_@babel+core@7.22.20_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:102:36 {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}
```

This started happening when I updated from 12 to 13 I tried using the `next/legacy/image` but same outcome.

Some information that might be useful:
```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.18.0
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: 8.7.1
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 12.3.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

**Comment by joacub** [comment]
noes does not work in http 😀

**Comment by joacub** [comment]
"url" parameter is valid but upstream response is invalid

**Comment by nagman** [comment]
I have the same issue:

In the browser:
```
"url" parameter is valid but upstream response is invalid
```

In the server console:
```
upstream image response failed for /_next/static/media/landscape.4c44eb27.jpg TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:127:62909)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async /app/node_modules/next/dist/server/next-server.js:362:39
    at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:519:61)
    at async /app/node_modules/next/dist/server/response-cache/index.js:102:36 {
  cause: [Error: 587BFC6F477F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```

Yet I'm importing a local image, with `import`, like this:
```ts
import Landscape from '../../../components/ResponsiveImage/samples/landscape.jpg';
```

My env info:
```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
Binaries:
  Node: 18.18.0
  npm: 7.20.0
  Yarn: 1.22.19
  pnpm: 8.7.5
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: standalone
```

I must precise that when I build on my local env (macOs m1 Ventura), it works.

But when I build a container image and deploy it in preproduction on my kubernetes cluster, with node alpine 18.18.0 and sharp installed, it doesn't work.

I don't know if it's related to the fact that the preproduction has an https url, unlike my local build. I'll try to deploy my build to vercel in order to see if it's due to my Dockerfile config or not.

**Comment by nagman** [comment]
Ok, so when building and deploying on vercel, the error is gone. I'll investigate in my Dockerfile to see why it fails on my preproduction server.

**Comment by advancingu** [comment]
@nagman I'm seeing the exact same error with static image files when deploying to Kubernetes.

My hypothesis is that some component tries to access these images locally from Next.js for processing through `https` even though everything behind the load balancer should use `http`.

**Comment by advancingu** [comment]
Issue should be fixed in https://github.com/vercel/next.js/pull/55988

**Comment by terrymun** [comment]
Might be related to #53715

**Comment by timothyerwin** [comment]
I'm getting the same issue. Is there a workaround in the meantime while we wait for the supposed fix above?

```jsx
 <Image
          src="/logo.png"
          width={256}
          height={256}
          priority
        />
```

```sh
2023-09-28T21:25:38.990747564Z upstream image response failed for /logo.png TypeError: fetch failed
2023-09-28T21:25:38.990800465Z     at Object.fetch (node:internal/deps/undici/undici:11576:11)
2023-09-28T21:25:38.990807166Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-28T21:25:38.990811466Z     at async globalThis.fetch (/home/site/wwwroot/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:127:62909)
2023-09-28T21:25:38.990815266Z     at async invokeRequest (/home/site/wwwroot/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
2023-09-28T21:25:38.990819666Z     at async /home/site/wwwroot/node_modules/next/dist/server/next-server.js:362:39
2023-09-28T21:25:38.990823366Z     at async imageOptimizer (/home/site/wwwroot/node_modules/next/dist/server/image-optimizer.js:537:13)
2023-09-28T21:25:38.990827266Z     at async cacheEntry.imageResponseCache.get.incrementalCache (/home/site/wwwroot/node_modules/next/dist/server/next-server.js:519:61)
2023-09-28T21:25:38.990831266Z     at async /home/site/wwwroot/node_modules/next/dist/server/response-cache/index.js:102:36 {
2023-09-28T21:25:38.990834966Z   cause: [Error: C0070786B4710000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
2023-09-28T21:25:38.990839266Z   ] {
2023-09-28T21:25:38.990843366Z     library: 'SSL routines',
2023-09-28T21:25:38.990847366Z     reason: 'wrong version number',
2023-09-28T21:25:38.990851467Z     code: 'ERR_SSL_WRONG_VERSION_NUMBER'
2023-09-28T21:25:38.990855667Z   }
2023-09-28T21:25:38.990859767Z }
```

**Comment by Iulian-Dragomirescu** [comment]
@timothyerwin You use a custom server? (Node.js) or next build in?
If u use a custom server try to add port in ```next({port})```
```
// Config
const port = process.env.PORT || 3000; // this line

// Next js init
const dev = process.env.NODE_ENV !== "production";
const server = next({ dev, dir: process.cwd(), port }); // add port here
const handle = server.getRequestHandler();

```

**Comment by shawngustaw** [comment]
this was broken on 13.5.3 for me but with 13.5.4 seems like it's fixed 👍
