### ISSUE TITLE
[next/dynamic] build error: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by kjxbyz** [vercel/next.js#55739]
### Link to the code that reproduces this issue

https://github.com/kjxbyz/react-quill-issue

### To Reproduce

1. `clone code`
2. `yarn`
3. `yarn build`

### Current vs. Expected behavior

```
yarn run v1.22.19
$ next build
 ✓ Linting and checking validity of types   
 ✓ Creating an optimized production build   
 ✓ Compiled successfully
   Collecting page data ../Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661
var elem = document.createElement('div');
           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)

Node.js v18.17.1
Static worker unexpectedly exited with code: 1 and signal: null
 ✓ Collecting page data   
   Generating static pages (2/3) [=   ] 
/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661
var elem = document.createElement('div');
           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)

Static worker unexpectedly exited with code: 1 and signal: null
   Generating static pages (2/3) [=   ] 
/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661
var elem = document.createElement('div');
           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)

   Generating static pages (2/3) [==  ] 
/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661
var elem = document.createElement('div');
           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)

   Generating static pages (2/3) [ ===] 
/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661
var elem = document.createElement('div');
           ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/Users/ying/react-quill-issue/node_modules/quill/dist/quill.js:36:30)


> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/Users/ying/react-quill-issue/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/Users/ying/react-quill-issue/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
   Generating static pages (2/3) [    ] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A

```
```


### Which area(s) are affected? (Select all that apply)

Dynamic imports (next/dynamic)

### Additional context

_No response_

<sub>[NEXT-1648](https://linear.app/vercel/issue/NEXT-1648/[nextdynamic]-build-error-referenceerror-document-is-not-defined)</sub>

**Comment by icyJoseph** [comment]
Hi,

You need to dynamically import like this:

```ts
const ReactQuill = dynamic(() => import('react-quill'), { ssr: false });
```

Try it out here: https://stackblitz.com/edit/github-tdsmu9?file=pages%2Findex.tsx

**Comment by balazsorban44** [comment]
Seems to be related to https://github.com/vercel/next.js/pull/54411 since https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.3 is the first release having this issue. We will have a look, thanks!

**Comment by balazsorban44** [comment]
Oh wait. @icyJoseph is correct. You'll need to pass a function, this is also documented as such: https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic

So this should be working as per the documentation then.

**Comment by icyJoseph** [comment]
According to the implementation, the option to pass the import directly, and not in function form was supported:

- https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/dynamic.tsx#L105C1-L112C1

```tsx
  // Support for direct import(), eg: dynamic(import('../hello-world'))
  // Note that this is only kept for the edge case where someone is passing in a promise as first argument
  // The react-loadable babel plugin will turn dynamic(import('../hello-world')) into dynamic(() => import('../hello-world'))
  // To make sure we don't execute the import without rendering first
  if (dynamicOptions instanceof Promise) {
    loadableOptions.loader = () => dynamicOptions
    // Support for having import as a function, eg: dynamic(() => import('../hello-world'))

```

So what happens is that it gets transformed to a function anyway? But since you don't use the function form, the module is probably being parsed. Hard to tell. The official, sure way to do it is as function form.
