### ISSUE TITLE
ECONNRESET fetch cache issue (I created a repo in order to replicate that issue)

### ISSUE THREAD

**Issue by FerrariAndrea** [vercel/next.js#56005]
### Link to the code that reproduces this issue

https://github.com/FerrariAndrea/next13-fetch-cache-issue-template

### To Reproduce

I created a repo in order to reproduce that.
Download that Repo and follow the Readme inside:
https://github.com/FerrariAndrea/next13-fetch-cache-issue-template

# INIT
cd backend
yarn install
cd ..
cd my-app
yarn install
# RUN TEST USE-CASE
open a new terminal inside the backend folder
node server.js
open a new terminal inside my-app folder
yarn build

Read the yarn build logs, you should find the issue.
Note: if you can't see any error in the log, pls increase that size:
https://github.com/FerrariAndrea/next13-fetch-cache-issue-template/blob/905113b181a7d4226dabe98f482bac183727b7b8/my-app/app/config.js#L21

We noted that the error doesn't occur in some environments/machines, sometimes we need to use a big payload response size in order to see the issue.

### Current vs. Expected behavior

Introduction:

- fetch cache enabled with revalidate
- server-side rendering (server-side page build)
- response of the fetch with a big payload

Current:
Error came out:
```
`Failed to set fetch cache http://localhost:4000/test_req TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async globalThis.fetch (D:\Illuminem\old\next13-fetch-cache-issue-template\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:127:62909)
    at async invokeRequest (D:\Illuminem\old\next13-fetch-cache-issue-template\my-app\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeIpcMethod (D:\Illuminem\old\next13-fetch-cache-issue-template\my-app\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
    at async D:\Illuminem\old\next13-fetch-cache-issue-template\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:127:66497 {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
```

Expected: I'm not expecting that issue.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.4-canary.0
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

The Next.js version 13.4.12, seems to dosen't have that issue.

Related issue: https://github.com/vercel/next.js/issues/53695

**Comment by FerrariAndrea** [comment]
Checked the latest release ("next": "^13.5.7-canary.25"), and the issue persists.

This is really important issue, in my opinion, I can't go into production with that without a fix or at least an understanding of what that will cause.

**Comment by diaz-hfc** [comment]
In my case the issue has been reduced, before it was in all fetch calls, now it is in like 10, at least there is some progress.

**Comment by FerrariAndrea** [comment]
Tested with next:14.0.0, the issue still here.

```
Failed to set fetch cache http://#######/graphql TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async globalThis.fetch (#######\node_modules\next\dist\server\lib\patch-fetch.js:197:16)
    at async invokeRequest (#######\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeIpcMethod (#######\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
    at async #######\node_modules\next\dist\server\lib\patch-fetch.js:394:29
    at async Promise.all (index 3) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
Failed to set fetch cache http://#######/graphql TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async globalThis.fetch (#######\node_modules\next\dist\server\lib\patch-fetch.js:197:16)
    at async invokeRequest (#######\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeIpcMethod (#######\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
    at async #######\node_modules\next\dist\server\lib\patch-fetch.js:394:29
    at async Promise.all (index 6) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
   Generating static pages (30/66) [    ]
Failed to set fetch cache http://#######/graphql TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async globalThis.fetch (#######\node_modules\next\dist\server\lib\patch-fetch.js:197:16)
    at async invokeRequest (#######\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeIpcMethod (#######\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
    at async #######\node_modules\next\dist\server\lib\patch-fetch.js:394:29
    at async Promise.all (index 4) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
Failed to set fetch cache http://#######/graphql TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async globalThis.fetch (#######\node_modules\next\dist\server\lib\patch-fetch.js:197:16)
    at async invokeRequest (#######\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeIpcMethod (#######\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
    at async #######\node_modules\next\dist\server\lib\patch-fetch.js:394:29
    at async Promise.all (index 7) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
Failed to set fetch cache http://#######/graphql TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async globalThis.fetch (#######\node_modules\next\dist\server\lib\patch-fetch.js:197:16)
    at async invokeRequest (#######\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeIpcMethod (#######\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
    at async #######\node_modules\next\dist\server\lib\patch-fetch.js:394:29
    at async Promise.all (index 9) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
Failed to set fetch cache http://#######/graphql TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async globalThis.fetch (#######\node_modules\next\dist\server\lib\patch-fetch.js:197:16)
    at async invokeRequest (#######\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeIpcMethod (#######\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
    at async #######\node_modules\next\dist\server\lib\patch-fetch.js:394:29
    at async Promise.all (index 8) {
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

**Comment by diaz-hfc** [comment]
@FerrariAndrea server actions are mutation events so they are not called on build time.

**Comment by FerrariAndrea** [comment]
I edit the next.js code directly inside the node_modules folder, in order to retrieve more information about that issue.
So in that file: `node_modules\next\dist\server\lib\server-ipc\invoke-request.js`
I just add a try-catch and some logs like that:

```
const invokeRequest = async (targetUrl, requestInit, readableBody)=>{
    const invokeHeaders = (0, _utils.filterReqHeaders)({
        "cache-control": "",
        ...requestInit.headers
    }, _utils.ipcForbiddenHeaders);
    try{
        console.log("MY TRAKING; WORKING: ",targetUrl.length)
        return await fetch(targetUrl, {
            headers: invokeHeaders,
            method: requestInit.method,
            redirect: "manual",
            signal: requestInit.signal,
            ...requestInit.method !== "GET" && requestInit.method !== "HEAD" && readableBody ? {
                body: readableBody,
                duplex: "half"
            } : {},
            next: {
                // @ts-ignore
                internal: true
            }
        });
    }catch(err){
        console.log("MY TRAKING: ",{
        requestInit,
        targetUrl:targetUrl.length,
        readableBody,err})
    }
};

```

I discovered that the issue seems to be related to the hashed/encrypted URL that is passed here, which sometimes seems to be really long, and the URL seems to be longer as bigger the response that we receive by the fetch. 

Here you can read a part of the 'yarn build' output:
```
MY TRAKING; WORKING:  185
MY TRAKING; WORKING:  185
MY TRAKING; WORKING:  185
MY TRAKING; WORKING:  185
MY TRAKING; WORKING:  57822
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  59014
MY TRAKING; WORKING:  511
MY TRAKING; WORKING:  63246
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  57674
MY TRAKING; WORKING:  511
MY TRAKING; WORKING:  511
MY TRAKING; WORKING:  68316
MY TRAKING; WORKING:  3482
MY TRAKING; WORKING:  59748
MY TRAKING; WORKING:  1257398
MY TRAKING:  {
  requestInit: { method: 'GET', headers: {} },
  targetUrl: 68316,
  readableBody: undefined,
  err: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11576:11)
      at async globalThis.fetch (#######website\node_modules\next\dist\server\lib\patch-fetch.js:197:16)
      at async invokeRequest (#######website\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:19:16)
      at async invokeIpcMethod (#######website\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
      at async #######website\node_modules\next\dist\server\lib\patch-fetch.js:394:29 {
    cause: Error: read ECONNRESET
        at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
        at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read'
    }
  }
}
Failed to set fetch cache http://#######/graphql TypeError: Cannot read properties of undefined (reading 'text')
    at invokeIpcMethod (#######website\node_modules\next\dist\server\lib\server-ipc\request-utils.js:49:32)
    at async #######website\node_modules\next\dist\server\lib\patch-fetch.js:394:29
MY TRAKING; WORKING:  3482
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  3214
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  3214
MY TRAKING; WORKING:  528
MY TRAKING; WORKING:  528
MY TRAKING:  {
  requestInit: { method: 'GET', headers: {} },
  targetUrl: 1257398,
  readableBody: undefined,
  err: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11576:11)
      at async globalThis.fetch (#######website\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:111:13700)
      at async invokeRequest (#######website\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:19:16)
      at async invokeIpcMethod (#######website\node_modules\next\dist\server\lib\server-ipc\request-utils.js:45:21)
      at async #######website\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:111:17355 {
    cause: Error: read ECONNRESET
        at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
        at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read'
    }
  }
}
Failed to set fetch cache http://#######/graphql TypeError: Cannot read properties of undefined (reading 'text')
    at invokeIpcMethod (#######website\node_modules\next\dist\server\lib\server-ipc\request-utils.js:49:32)
    at async #######website\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:111:17355
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  529
MY TRAKING; WORKING:  59026
MY TRAKING; WORKING:  187
MY TRAKING; WORKING:  529
```

You can see here that the catch cache request that fails are the one with really long URLs:

-    targetUrl: 1257398 length of chars
-    targetUrl: 68316, length of chars

And the fact that I can find a URL longer 1.257.398 chars is really strange, I'm not a protocols expert, but I think is not a good stuff.

**Comment by FerrariAndrea** [comment]
In overthinking, maybe is the keep-alive option? 
[here are the references](https://nextjs.org/docs/app/api-reference/next-config-js/httpAgentOptions)
In node 18 the keep-alive is true as default, but what about the timers? 

Maybe a big request fails due to that?

I really don't know how to fix that, so I'm try to explore everything

**Comment by FerrariAndrea** [comment]
I need to do more tests but it seems that they fix it on the last canary: [v14.0.2-canary.9](https://github.com/vercel/next.js/releases/tag/v14.0.2-canary.9)

On my localhost the build now is working, there is no fatch issue anymore!

**Comment by FerrariAndrea** [comment]
Update, my deadline ends, so our website is online with the version "next": "^14.0.2".

The issue is not present anymore, but it seems that the same fetch is called bypassing the cache on the Vercel machine.
That is because I have a console.log that prints out the amount of time needed to fetch the data, and the time is always the same, so I can assume that the cache is not used, and the fetch is done evry time.

I will investigate that, maybe in the new version of Next.js they will fix that or maybe I will find something on the documentation that will underline some configuration error on my side.

**Comment by yoeven** [comment]
Happens to me as well, seems like changing the function region solved it for me for now. Initially functions were on `sf01` and I changed it to `iad1`, redeployed and it all works

**Comment by FerrariAndrea** [comment]
> Happens to me as well, seems like changing the function region solved it for me for now. Initially functions were on `sf01` and I changed it to `iad1`, redeployed and it all works

Sorry, what did you mean? 
How to do it?

thx
