### ISSUE TITLE
`redirect()` should trigger loading screen if the target page takes too long

### ISSUE THREAD

**Issue by roblen45** [vercel/next.js#56149]
### Link to the code that reproduces this issue

https://github.com/5minds/redirect_timeout_in_server_actions

### To Reproduce

1. Start the application in dev 
2. Click on redirect button

### Current vs. Expected behavior

When a server action redirects to a new server component with a long running async method call, the client hangs for a few minutes until the redirect get a timeout exception:

`Internal error: Error: The render was aborted by the server without a reason.
    at eQ (/Users/XXX/src/5Minds/redirect_timeout_in_server_actions/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:68:94611)
    at Object.cancel (/Users/XXX/src/5Minds/redirect_timeout_in_server_actions/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:68:108428)
    at readableByteStreamControllerCancelSteps (node:internal/webstreams/readablestream:2576:37)
    at ReadableByteStreamController.[kCancel] (node:internal/webstreams/readablestream:1135:12)
    at ensureIsPromise (node:internal/webstreams/util:174:19)
    at readableStreamCancel (node:internal/webstreams/readablestream:1552:5)
    at node:internal/webstreams/readablestream:1389:15
    at complete (node:internal/webstreams/readablestream:1279:9)
    at shutdownWithAnAction (node:internal/webstreams/readablestream:1275:5)
    at node:internal/webstreams/readablestream:1388:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

I would expect that the loading page is shown until the long running method finished.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
Binaries:
  Node: 16.17.0
  npm: 8.15.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.4-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, TypeScript (plugin, built-in types)

<sub>[NEXT-1668](https://linear.app/vercel/issue/NEXT-1668/redirect-timeout-in-server-actions)</sub>

**Comment by balazsorban44** [comment]
There is no `redirect()` calls in the reproduction. To investigate, I added `redirect("/other")` to the `redirectToOtherPage` action, but I could not reproduce the issue you are describing. Can you make sure the reproduction reflects the issue description?

Are you maybe able to pinpoint if this is a regression (did this work in a previous version, if so what's the last one that worked)?

**Comment by roblen45** [comment]
Sorry for that. 
I added the redirect to the  server action.

**Comment by roblen45** [comment]
The next version is: 13.5.4-canary.4

**Comment by Shamilx** [comment]
I think, it is normal behaviour of Server Actions. They get executed on server. Thats why loading screen is not displayed. Maybe I am wrong.
