### ISSUE TITLE
Failed to generate self-signed certificate. with `--experimental-https` flag

### ISSUE THREAD

**Issue by M7ilan** [vercel/next.js#56276]
### Link to the code that reproduces this issue

https://github.com/M7ilan/next-auth-bungie-provider

### To Reproduce

1. create next app `npx create-next-app@latest .`
2. update `package.json` script for `dev` to: `next dev --experimental-https` for https support.
3. run `npm run dev` and you get the following error:

```bat
> npm run dev

> nextjs-template@0.1.0 dev    
> next dev --experimental-https

 ⚠ Self-signed certificates are currently an experimental feature, use at your own risk.
   Attempting to generate self signed certificate. This may prompt for your password
 ⨯ Failed to generate self-signed certificate. Falling back to http. Error: Command failed: C:\Users\Administrator\AppData\Local\mkcert\mkcert-v1.4.4-windows-amd64.exe -install -key-file C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\certificates\localhost-key.pem -cert-file C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\certificates\localhost.pem localhost 127.0.0.1 ::1     
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at createSelfSignedCertificate (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\lib\mkcert.js:123:37)
    at async runDevServer (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\cli\next-dev.js:286:35)  
    at async C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\cli\next-dev.js:302:9
    at async Span.traceAsyncFn (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\trace\trace.js:105:20)
    at async nextDev (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\cli\next-dev.js:301:5)        
    at async main (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\bin\next:156:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6844,
  stdout: null,
  stderr: null
}
(node:9032) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ▲ Next.js 13.5.3
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Ready in 3.9s
```

### Current vs. Expected behavior

I belive the error saying that he can't generate self-signed certificate while I already have the 2 files `localhost-key.pem` and `localhost.pem` inside of `certificates` folder. and I expect to run `npm run dev` without any errors and work with the HTTPS to work with bungie API which require HTTPS in localhosts.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
> npx --no-install next info

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.12.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Package manager (npm, pnpm, Yarn)

### Additional context

Here's more info about my app:

Project Structure Image:
![image](https://github.com/vercel/next.js/assets/81147447/72145f32-3cd4-45c3-a6f6-102315dbda81)

Error Image:
![image](https://github.com/vercel/next.js/assets/81147447/b6b9d386-bf01-4be6-b530-58422cbfc01f)

**Comment by M7ilan** [comment]
Have the same problem in the new update `v13.5.4`
I tried with not having any certificates and with it installing it manual using `mkcert localhost` but non of them works.

with this error:
```bash
> npm run dev      

> next-auth-bungie-provider@0.1.0 dev
> next dev --experimental-https

 ⚠ Self-signed certificates are currently an experimental feature, use at your own risk.
   Attempting to generate self signed certificate. This may prompt for your password
 ⨯ Failed to generate self-signed certificate. Falling back to http. Error: Command failed: "C:\Users\Administrator\AppData\Local\mkcert\mkcert-v1.4.4-windows-amd64.exe" -install -key-file "C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\certificates\localhost-key.pem" -cert-file "C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\certificates\localhost.pem" localhost 127.0.0.1 ::1
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at createSelfSignedCertificate (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\lib\mkcert.js:123:37)
    at async runDevServer (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\cli\next-dev.js:285:35)  
    at async C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\cli\next-dev.js:301:9
    at async Span.traceAsyncFn (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\trace\trace.js:105:20)
    at async nextDev (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\cli\next-dev.js:300:5)        
    at async main (C:\Personal\VSCode\Github\M7ilan\next-auth-bungie-provider\node_modules\next\dist\bin\next:156:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12728,
  stdout: null,
  stderr: null
}
(node:12496) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Ready in 4.3s
```

**Comment by igeligel** [comment]
How to fix this:
You can just run your terminal with administrator rights at least once. Afterward, it works.

It would be cool if Next.js auto detects this before throwing an error with some utility like `is-admin` [1].

[1] https://github.com/sindresorhus/is-admin

**Comment by M7ilan** [comment]
> How to fix this: You can just run your terminal with administrator rights at least once. Afterward, it works.
> 
> It would be cool if Next.js auto detects this before throwing an error with some utility like `is-admin` [1].
> 
> [1] https://github.com/sindresorhus/is-admin

Thanks, all I do is run VSCode as administrator.
