### ISSUE TITLE
Starting at 13.4.13-canary-0 Internal Server Error due to connection refused

### ISSUE THREAD

**Issue by studentIvan** [vercel/next.js#56831]
### Link to the code that reproduces this issue

https://github.com/darthmaim-reproductions/vercel-next.js-53171

### To Reproduce

1. Clone https://github.com/darthmaim-reproductions/vercel-next.js-53171
2. Run this command to build and start the next.js app in a docker container docker build -t vercel-next.js-53171 . && docker run --rm -p3000:3000 vercel-next.js-53171
3. Access http://localhost:3000/
4. The server responds with Internal Server Error
5. The server logs output

```
- ready started server on e68ae5711fa3:3000, url: http://e68ae5711fa3:3000
Listening on port 3000 url: http://e68ae5711fa3:3000
- error Failed to handle request for /
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async requestHandler (/app/node_modules/next/dist/server/lib/start-server.js:336:33)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:152:13) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:41303
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 41303
  }
}
- error Failed to handle request for /favicon.ico
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async requestHandler (/app/node_modules/next/dist/server/lib/start-server.js:336:33)
    at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:152:13) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:41303
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 41303
  }
}
```

### Current vs. Expected behavior

server responds with Internal Server Error, on version 13.4.12 everything works as expected

In the deep logs it's trying to access the address 127.0.0.1:3000 and falls with the error

```


Error: connect ECONNREFUSED 127.0.0.1:3000
--
  | 2023-10-13T03:02:26.940+03:00 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  | 2023-10-13T03:02:26.940+03:00 | errno: -111,
  | 2023-10-13T03:02:26.940+03:00 | code: 'ECONNREFUSED',
  | 2023-10-13T03:02:26.940+03:00 | syscall: 'connect',
  | 2023-10-13T03:02:26.940+03:00 | address: '127.0.0.1',
  | 2023-10-13T03:02:26.940+03:00 | port: 3000
  | 2023-10-13T03:02:26.940+03:00 | }

```

HOSTNAME=0.0.0.0 environment variable didn't help both with [solution for intl middleware](https://github.com/vercel/next.js/issues/53171#issuecomment-1652856227)

```
function rewrite(url: string) {
      return NextResponse.rewrite(
        // this is to try to not called the middleware twice remove when next handle this better
        new URL(
          url,
          request.url
            .replace("https://localhost", "https://0.0.0.0")
            .replace("http://localhost", "http://0.0.0.0")
        ),
        getResponseInit()
      );
    }
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Docker (nixpacks)
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router, Internationalization (i18n), Middleware / Edge (API routes, runtime)

### Additional context

Original issue has all the details https://github.com/vercel/next.js/issues/53171 and it's closed by bot

**Comment by studentIvan** [comment]
My app uses the custom server.js file + next.js build + i18n middleware from the next.js example. It all runs inside the docker container with no ip 127.0.0.1 but for some reason app tries to access it.

It's not the edge environment, just node v18

**Comment by benj-dobs** [comment]
I think I've got this issue too. In my case it's usually `TypeError: fetch failed` with a cause of `SocketError: other side closed`. I think this is the same issue as it was also introduced in 13.4.13 - rolling back to 13.4.12 is the only successful fix so far. Also in the Node 18 environment (standalone server in a docker container).

Definitely an issue as of 13.4.19. Not tested 13.5 yet.

**Comment by studentIvan** [comment]
For people who faced with this issue:

1. check you server.js is using the object configuration, and pass the hostname to it, even you have HOSTNAME env
2. upgrade node.js up to 18.18 (latest) - if you use nixpacks, configure the nixpacks.toml file inside the workdir (see below)
3. check if the server/service doesn't add any extra next.js configuration options, like for me, for example, it was the stale-while-revalidate (link to [flightcontrol docs](https://www.flightcontrol.dev/docs/guides/advanced/swr#setup))


```
[phases.setup]
nixpkgsArchive = 'dc569412d01a61cb4969bd5fe961a321290653a8'
```

Everything is fixed now!
