### ISSUE TITLE
[turbopack] App breaks when used with `serverActions`

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/next.js#57095]
### Link to the code that reproduces this issue

https://github.com/devjiwonchoi/turbopack-server-actions-repro

### To Reproduce

Run `pnpm dev`

### Current vs. Expected behavior

The app breaks with log:

```
 ⨯ Error: Module [node]/.next/server/app/page/actions.js (ecmascript, rsc) was instantiated as a runtime entry of chunk server/app/page.js, but the module factory is not available. It might have been deleted in an HMR update.
    at instantiateModule (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/.next/server/chunks/rsc/[turbopack]_runtime.js:377:15)
    at instantiateRuntimeModule (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/.next/server/chunks/rsc/[turbopack]_runtime.js:459:12)
    at Object.getOrInstantiateRuntimeModule (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/.next/server/chunks/rsc/[turbopack]_runtime.js:474:12)
    at Object.<anonymous> (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/.next/server/app/page.js:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/node_modules/.pnpm/next@13.5.7-canary.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:119:18)
    at requirePage (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/node_modules/.pnpm/next@13.5.7-canary.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js:109:84)
    at /Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/node_modules/.pnpm/next@13.5.7-canary.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:59:84
    at async loadComponentsImpl (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/node_modules/.pnpm/next@13.5.7-canary.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:59:26)
    at async DevServer.findPageComponentsImpl (/Users/devjiwonchoi/DevLife/Repro/turbopack-server-actions-repro/node_modules/.pnpm/next@13.5.7-canary.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:437:36) {
  page: '/'
}
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.6.12
Relevant Packages:
  next: 13.5.7-canary.11
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

**Comment by devjiwonchoi** [comment]
Expected to be fixed with https://github.com/vercel/turbo/pull/6227, I'll close this after I observe it being fixed.
