### ISSUE TITLE
next I upgraded to 13.5.3. The build is running, but when the app service starts up, it gives cannot find module error logs. All pages give 500 errors.

### ISSUE THREAD

**Issue by almirjakubaitis** [vercel/next.js#57130]
next I upgraded to 13.5.3. The build is running, but when the app service starts up, it gives cannot find module error logs. All pages give 500 errors.

We use a Windows machine when building.

```
Error: Cannot find module 'next/dist\client\components\static-generation-async-storage.external.js'
Require stack:
- /home/site/wwwroot/.next/server/app/page.js /home/site/wwwroot/node modules/next/dist/server/require.js /home/site/wwwroot/node modules/next/dist/server/next-server.js
- /home/site/wwwroot/node modules/next/dist/server/next.is
/home/site/wwwroot/node modules/next/dist/server/lib/start-server.js /home/site/wwwroot/node modules/next/dist/cli/next-start.is
/home/site/wwwroot/node modules/next/dist/lib/commands.js
- /home/site/wwwroot/node modules/next/dist/bin/next at Module. resolveFilename (node:internal/modules/cjs/loader: 1077:15)
at /home/site/wwwroot/node_modules/next/dist/server/require-hook.js:54:36 at Module. load (node:internal/modules/cjs/loader: 922:27)
at Module.require (node: internal/modules/cis/loader: 1143:19)
at Module.patchedRequire (/agents/nodejs/node modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
at mod.require (/home/site/wwwroot/node_modules/next/dist/server/require-hook.js:64:28)
at require (node: internal/modules/cjs/helpers: 110:18)
at 5319 (/home/site/wwwroot/.next/server/app/page.js:1:614)
at t /home/site/wwwroot/.next/server/webpack-runtime.js:1:128)
at 1775 (/home/site/wwwroot/.next/server/chunks/8051.js:1:107062)
code: 'MODULE NOT FOUND' requireStack:
home/site/wwwroot/.next/server/app/page.js',
"home/site/wwwroot/node modules/next/dist/server/require.is' /hone/site/wwwroot/node modules/next/dist/server/next-server.js
" /home/site/wwwroot/node_modules/next/dist/server/next.js', home/site/wwwroot/node_modules/next/dist/server/lib/start-server.js', /home/site/wwwroot/node_modules/next/dist/cli/next-start.js', home/site/wwwroot/node modules/next/dist/lib/commands.js'
"
```

_Originally posted by @ugursepetci in https://github.com/vercel/next.js/discussions/56010_

**Comment by balazsorban44** [comment]
Please file an issue using the bug report template: https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml

**Comment by Enngage** [comment]
> Please file an issue using the bug report template: https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml

Mate, please have a look at the original post (https://github.com/vercel/next.js/discussions/56010), it's pretty serious issue preventing people from using next.js within Azure unless you build the app elsewhere, use docker etc. We cannot do this and so we are stuck on older version with many bugs (some of which are fixed in later versions).
