### ISSUE TITLE
Next expermintal production standalone Error: Not implemented.  at Object.getCacheForType 

### ISSUE THREAD

**Issue by bu3alwa** [vercel/next.js#57205]
### Link to the code that reproduces this issue

https://github.com/bu3alwa/Jellyfin-Patreon-Account-Portal/tree/d8b4a1fc2f250a92af9d908ffbf8c629614c4ac3

### To Reproduce

1. Create a next standalone with server actions experimental (page must use server action)
2. Run `next build`
3. Copy standalone folder to a different location
4. Run `node server.js`

### Current vs. Expected behavior

Seems to have a missing function during production on experimental features.

Current: Page does not load (white page)
Expected: Page should load

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Education
Binaries:
  Node: 18.18.2
  npm: N/A
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tested 13.5.1, 13.5.5, and canary doesn't build right now for me.I am running node 18.18.0.
This  seems to affect only the experimental feature. Dev seems to work without any errors loading but prod seems to have an issue on standalone. `Next start` does not have this issue it seems like its only standalone output.

```
account  | Error: Not implemented.
account  |     at Object.getCacheForType (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:38524)
account  |     at /app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:51:4529
account  |     at Providers (/app/.next/server/chunks/387.js:1:1088)
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:42286)        
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:55760)        
account  |     at nO (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:58995)        
account  |     at nM (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)        
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:52940)        
account  |     at nO (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:58995)        
account  |     at nM (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)        
account  | Error: Not implemented.
account  |     at Object.getCacheForType (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:38524)
account  |     at /app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:51:4529
account  |     at Providers (/app/.next/server/chunks/387.js:1:1088)
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:42286)        
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:55760)        
account  |     at nO (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:58995)        
account  |     at nM (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)        
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:52940)        
account  |     at nO (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:58995)        
account  |     at nM (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)        
account  | Error: Not implemented.
account  |     at Object.getCacheForType (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:38524)
account  |     at /app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:51:4529
account  |     at Providers (/app/.next/server/chunks/387.js:1:1088)
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:42286)        
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:55760)        
account  |     at nO (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:58995)        
account  |     at nM (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)        
account  |     at nP (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:52940)        
account  |     at nO (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:58995)        
account  |     at nM (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:62939)        
account  | Error: Not implemented.
account  |     at Object.getCacheForType (/app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:27:38524)
account  |     at /app/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:51:4529
```

**Comment by FreyzerFault** [comment]
I've also encounter this error in building process, when generating static pages.

Not using cache() method from react seems to fix it.

I can run it in dev mode without problems, but with no build I can't test a production run.



### My Environment

```
System:
    OS: Windows 10 10.0.22635
    CPU: (12) x64 AMD Ryzen 5 3600XT 6-Core Processor
    Memory: 3.14 GB / 15.91 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Local\pnpm\pnpm.EXE
  Managers:
    pip3: 23.2.1 - C:\Python311\Scripts\pip3.EXE
  Utilities:
    Git: 2.41.0.
    Curl: 8.0.1 - C:\WINDOWS\system32\curl.EXE
  IDEs:
    Android Studio: AI-223.8836.35.2231.10406996
    VSCode: 1.83.1 - C:\Users\marti\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.6.33723.286 (Visual Studio Community 2022)       
  Languages:
    Java: 11.0.19
    Python: 3.11.5
  Browsers:
    Edge: Chromium (119.0.2151.12)
    Internet Explorer: 11.0.22621.1
```

It's a shame, I need cache() for a third party library which do some fetching to an external API witth lots of data and cache() is so usefull for that.

**Comment by John9570** [comment]
also running into this, watching for fix

**Comment by nicole0707** [comment]
Having the issue too

**Comment by jakevollkommer** [comment]
same error, but for me I'm using @urql/next as described in the docs [here](https://commerce.nearform.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs)

**Comment by Marcosld** [comment]
This is not really a bug. It happens because you are calling React.cache within a Client Component (it has the `"use client"` directive). As stated in [React doc](https://react.dev/reference/react/cache), React cache can only be used within RSC. I think you just should not use React.cache for your use case.
In our case we have a module to store metadata reused for Sever and Client components. In order to avoid this error it looks like this:
```typescript
import React from 'react';

export type FlowMetadata = {
  foo: string;
};

const ServerMetadata = () => {
    let metadata: FlowMetadata = {
        foo: 'bar'
    };

    return {
        get: () => metadata,
        set: (newMetadata: FlowMetadata) => {
            metadata = newMetadata;
        },
    };
};

const MemoizedServerMetadata = React.cache(ServerMetadata)

let browserMetadata: FlowMetadata = {
  foo: 'bar',
};

export const getFlowMetadata = () => {
    if (typeof window !== 'undefined') {
        return browserMetadata;
    }
    try {
        return MemoizedServerMetadata().get();
    } catch (e) {
        // When rendering client components on the server, the cache is not available
        return browserMetadata;
    }
};

export const setFlowMetadata = (metadata: FlowMetadata) => {
    if (typeof window !== 'undefined') {
        browserMetadata = metadata;
        return;
    }
    MemoizedServerMetadata().set(metadata);
};

```

**Comment by marcoshernanz** [comment]
Thanks for the report. I could reproduce this on Next 13.5.6, but not on Next 15+ or current canary. The linked repro calls `React.cache()` inside a `"use client"` provider, while [`cache` is only supported in Server Components](https://react.dev/reference/react/cache). The same error also occurs with a normal `next start` build, so it isn't specific to standalone output. For this `QueryClient`, initialize it with client state instead (for example, `useState(() => new QueryClient())`). Closing as resolved.
