### ISSUE TITLE
`useRouter` doesn't work with forms

### ISSUE THREAD

**Issue by bernaferrari** [vercel/next.js#57293]
### Link to the code that reproduces this issue

https://github.com/bernaferrari/reproduction-app

### To Reproduce

Clicking in a button inside a form will go to /about and then immediately redirect back to `/`.

```tsx
"use client";

import { useRouter } from "next/navigation";

/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  const router = useRouter();

  return (
    <div>
      <button
        onClick={() => {
          router.push("/about");
        }}
      >
        This works
      </button>
      <form
        onSubmit={() => {
          router.push("/about");
        }}
      >
        <button type="submit">This doesn't work</button>
      </form>
    </div>
  );
}
```

### Current vs. Expected behavior

I expect when push to /about that it stays in about, not that it flashes and goes back with:

```
 ⨯ Internal error: Error: The render was aborted by the server without a reason.
    at eG (/Users/bernardoferrari/Documents/work/Rendition/assistant/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:330259)
    at Object.cancel (/Users/bernardoferrari/Documents/work/Rendition/assistant/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:343583)
    at readableByteStreamControllerCancelSteps (node:internal/webstreams/readablestream:3117:37)
    at [kCancel] (node:internal/webstreams/readablestream:1185:12)
    at ensureIsPromise (node:internal/webstreams/util:185:19)
    at readableStreamCancel (node:internal/webstreams/readablestream:1982:5)
    at node:internal/webstreams/readablestream:1507:15
    at complete (node:internal/webstreams/readablestream:1396:9)
    at shutdownWithAnAction (node:internal/webstreams/readablestream:1392:5)
    at node:internal/webstreams/readablestream:1506:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.7-canary.17
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

**Comment by sam3d** [comment]
Don't you need to preventDefault on a form submission if you're not actually POST'ing the data to a server?

**Comment by bernaferrari** [comment]
You are right. I didn't know about this and couldn't find anywhere in the documentation. Thanks!
