### ISSUE TITLE
MDX breaks as now requires "use client"

### ISSUE THREAD

**Issue by LunaticMuch** [vercel/next.js#57538]
### Link to the code that reproduces this issue

https://github.com/LunaticMuch/redesigned-octo-fortnight

### To Reproduce

1. Install NextJS v14
2. Follow the `[manual](https://nextjs.org/docs/app/building-your-application/configuring/mdx)` for installing MDX
3. Create a sample mdx page
4. Run `npm run dev`

### Current vs. Expected behavior

You would expect to see the mdx page, instead

```bash
 ⨯ node_modules/@mdx-js/react/lib/index.js (30:19) @ React
 ⨯ createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at __webpack_require__ (/Users/stefano/_TEST/potato-world/.next/server/webpack-runtime.js:33:42)
    at eval (./app/mdx/page.mdx:6:85)
    at (rsc)/./app/mdx/page.mdx (/Users/stefano/_TEST/potato-world/.next/server/app/mdx/page.js:184:1)
    at Function.__webpack_require__ (/Users/stefano/_TEST/potato-world/.next/server/webpack-runtime.js:33:42)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 20.5.1
  npm: 9.8.0
  Yarn: 1.22.19
  pnpm: 8.7.6
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

MDX (@next/mdx)

### Additional context

I just did a simple test following the manual.

**Comment by irawel** [comment]
Make sure you have ```mdx-components.tsx``` file at the root of your poject.

**Comment by BastKakrolot** [comment]
I also encountered the same problem, this was my solution, I once thought if I had configured it wrong!
<img width="814" alt="image" src="https://github.com/vercel/next.js/assets/45719798/5e07fa25-4916-488e-90df-b1b8905211e9">

**Comment by kyldvs** [comment]
Had the same issue, specifically `mdx-components.tsx` needs to be inside the `root` directory, NOT `root/app` like in your example: https://github.com/LunaticMuch/redesigned-octo-fortnight/blob/main/app/mdx-components.tsx

I wish the documentation made this more clear, or the error called out that it couldn't find `mdx-components.tsx` in the appropriate file location.

**Comment by rohan-kiratsata** [comment]
The problem persists, even though I have `mdx-components.tsx` at root of `app` directory, the error remains unchanged.

**Comment by kyldvs** [comment]
> The problem persists, even though I have `mdx-components.tsx` at **root of `app` directory**, the error remains unchanged.

See my previous comment, `mdx-components.tsx` should **not** be in the `/app` directory.

**Comment by Claire06140** [comment]
If it may help someone, I had added providerImportSource: "@mdx-js/react" to the createMDX opions in next.config.js, removing it solved the problem 🪄🪄🪄

```const withMDX = createMDX({
  options: {
    remarkPlugins: [remarkGfm],
    rehypePlugins: [],
    // Remove this line
    // providerImportSource: "@mdx-js/react",
  },
})
```

**Comment by pablofdezr** [comment]
> If it may help someone, I had added providerImportSource: "@mdx-js/react" to the createMDX opions in next.config.js, removing it solved the problem 🪄🪄🪄
> 
> ```
>   options: {
>     remarkPlugins: [remarkGfm],
>     rehypePlugins: [],
>     // Remove this line
>     // providerImportSource: "@mdx-js/react",
>   },
> })
> ```

This is what worked for me, I had Claude 3.7 fill the providerImportSource options mistakenly. It does not appear on nextjs current docs so I just had to remove it and it worked again

**Comment by marcoshernanz** [comment]
Thanks for the report. I reproduced the linked repo on Next 14.0.0. Its `mdx-components.tsx` is inside `app/`, but App Router requires it at the project root, or inside `src/` when the app uses a `src` directory. Moving the file next to `app/` makes both `next dev` and `next build` pass without `"use client"`, including on current stable and canary. The broader DX issue around this confusing fallback is the subject of #80870, so I’m closing this as a setup issue.
