### ISSUE TITLE
--turbo flag not work with pageExtensions

### ISSUE THREAD

**Issue by bightg30098** [vercel/next.js#57603]
### Link to the code that reproduces this issue

https://github.com/bightg30098/turbo-flag-not-work-with-page-extensions

### To Reproduce

```bash
pnpm dlx create-next-app@latest

✔ What is your project named? … my-app
✔ Would you like to use TypeScript? … Yes
✔ Would you like to use ESLint? … Yes
✔ Would you like to use Tailwind CSS? … Yes
✔ Would you like to use `src/` directory? … Yes
✔ Would you like to use App Router? (recommended) … No
✔ Would you like to customize the default import alias (@/*)? … No
```

1. update dev script with `"dev": "next dev --turbo"`
2. add `pageExtensions: ['page.tsx']` to next.config.js
3. rename _app.tsx, _document.tsx, index.tsx to _app.page.tsx, _document.page.tsx, _document.page.tsx
4. start dev server with `pnpm dev`

### Current vs. Expected behavior

```bash
   ▲ Next.js 14.0.0 (turbo)
   - Local:        http://localhost:3000

 ✓ Ready in 1284ms
 ⨯ PageNotFoundError: Cannot find module for page: route not found /
    at Object.ensurePage (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:966:27)
    at async DevBundlerService.ensurePage (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:518:9)
    at async Object.ensure (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:164:17)
    at async DevRouteMatcherManager.matchAll (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
    at async DevRouteMatcherManager.match (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:222:31)
    at async DevServer.handleRequestImpl (/Users/bightg30098/Repositories/turbo-flag-not-work-with-page-extensions/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:748:17) {
  code: 'ENOENT'
}
 ✓ Compiled /_error in 322ms
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

<sub>[PACK-1950](https://linear.app/vercel/issue/PACK-1950/turbo-flag-not-work-with-pageextensions)</sub>

**Comment by ForsakenHarmony** [comment]
Thanks for reporting, I think we might only be parsing anything after the last `.` in the filename as the extension

**Comment by WinmezzZ** [comment]
<img width="1479" alt="image" src="https://github.com/vercel/next.js/assets/40154766/7e64e668-7578-4ebf-bf7d-bff353afe443">

still happend?

**Comment by doas3140** [comment]
I get very similar error with src/pages/_app.page.tsx and next.config.js:
```ts
const config = {
  output: 'standalone',
  pageExtensions: ['page.tsx', 'route.ts'],
  transpilePackages: ['ui'],
}
```

![image](https://github.com/vercel/next.js/assets/24541726/157a2de4-4697-4ed5-8656-816c05264733)

**Comment by WinmezzZ** [comment]
> I get very similar error with src/pages/_app.page.tsx and next.config.js:
> 
> ```ts
> const config = {
>   output: 'standalone',
>   pageExtensions: ['page.tsx', 'route.ts'],
>   transpilePackages: ['ui'],
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/24541726/284815654-157a2de4-4697-4ed5-8656-816c05264733.png)

You should use beta version, this change not publish lts version yet
