### ISSUE TITLE
TypeError: Cannot destructure property 'store' of 'C(...)' as it is null.

### ISSUE THREAD

**Issue by vanyapr** [vercel/next.js#57742]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js/

### To Reproduce

After updating NEXTJS version from 13.5.4 to 14 (canary), I had errors when compiling the project (npm run build).

 **Generating static pages (16/31) [ ===]** 
**TypeError: Cannot destructure property 'store' of 'C(...)' as it is null.**
    at Object.<anonymous> /.next/server/chunks/5497.js:34:7293)
    at C.Z (PROJECT/.next/server/chunks/5497.js:23:21179)
    at nk (PROJECT/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:38654)
    at nC (PROJECT/trusty-tools-new-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:54802)
    at nk (PROJECT/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:51563)
    at nC (PROJECT/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:54802)
    at nw (PROJECT/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:38210)
    at nk PROJECT/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:38805)
    at nC (PROJECT/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:54802)
    at nw (PROJECT/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:38210)
    
    
    
I use redux toolkit and next-persist. Everything works correctly on version 13.5.4:

```
'use client';


import createStore from '@store/store';
import { Provider } from 'react-redux';
import PersistWrapper from 'next-persist/lib/NextPersistWrapper';

const { store } = createStore();

type TProps = {
  children: any,
}

const npConfig = {
  method: 'localStorage',
  allowList: {
    cart: [],
  },
};

function ContextProvider({ children }: TProps) {
  return (
    <Provider store={store}>
      <PersistWrapper wrapperConfig={npConfig}>
        {children}
      </PersistWrapper>
    </Provider>
  );
}

export default ContextProvider;

```

And here is Root layout

```
export default async function RootLayout() {
 
  return (
    <ContextProvider>
      ... content
    </ContextProvider>
  );
}
```

### Current vs. Expected behavior

I expect that the code that works correctly will not break after upgrading to the latest version. There is no reason for this.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:23 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.3
  eslint-config-next: 13.4.9
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I tested my reproduction against different canary releases, and the first one that introduced the bug was &quot;14.0.1-canary.3&quot;, since reverting to &quot;1 13.5.4&quot; works.

**Comment by vanyapr** [comment]
Updated Next 14.0.2-canary.1, now everything is working correctly
