### ISSUE TITLE
name of next.js project cannot start with 'ud'

### ISSUE THREAD

**Issue by Hwlhwlxyz** [vercel/next.js#57780]
### Link to the code that reproduces this issue

https://github.com/Hwlhwlxyz/next.js-project-start-with-ud

### To Reproduce

1. run `npx create-next-app@14.0.1`, and then set the name to any string start with 'ud', such as 'udv_app'. 

```
C:\temp\nextjs-test>npx create-next-app@14.0.1
Need to install the following packages:
  create-next-app@14.0.1
Ok to proceed? (y) y

√ What is your project named? ... udv_app
√ Would you like to use TypeScript? ... No / Yes
√ Would you like to use ESLint? ... No / Yes
√ Would you like to use Tailwind CSS? ... No / Yes
√ Would you like to use `src/` directory? ... No / Yes
√ Would you like to use App Router? (recommended) ... No / Yes
√ Would you like to customize the default import alias (@/*)? ... No / Yes
Creating a new Next.js app in C:\temp\nextjs-test\udv_app.

Using npm.

Initializing project with template: default


Installing dependencies:
- react
- react-dom
- next



added 22 packages, and audited 23 packages in 12s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Initialized a git repository.

Success! Created udv_app at C:\temp\nextjs-test\udv_app
```

2. After create the project, run `npm run dev`.
3. open browser, and go to 'http://localhost:3000/'

Here are logs
```
> udv_app@0.1.0 dev
> next dev

   ▲ Next.js 14.0.1
   - Local:        http://localhost:3000

 ✓ Ready in 3.3s
thread '<unnamed>' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs:3883:53:
byte index 6 is out of bounds of `\ud`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs:3883:53:
byte index 6 is out of bounds of `\ud`
thread '<unnamed>' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs:3883thread ':<unnamed>53' panicked at :
C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rsbyte index 6 is out of bounds of `\ud`:3883
:53:
byte index 6 is out of bounds of `\ud`
thread '<unnamed>' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs:3883:53:
byte index 6 is out of bounds of `\ud`
 ⨯ ./src/pages/_app.js
Error: failed to process byte index 6 is out of bounds of `\ud`
 ○ Compiling / ...
thread '<unnamed>' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs:3883:53:
byte index 6 is out of bounds of `\ud`
thread '<unnamed>' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs:3883:53:
byte index 6 is out of bounds of `\ud`
thread 'thread '<unnamed><unnamed>' panicked at ' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rsC:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs::38833883::5353:
:
byte index 6 is out of bounds of `\ud`byte index 6 is out of bounds of `\ud`

thread '<unnamed>' panicked at C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.146.2\src\lib.rs:3883:53:
byte index 6 is out of bounds of `\ud`
 ⨯ ./src/pages/_app.js
Error: failed to process byte index 6 is out of bounds of `\ud`
```

### Current vs. Expected behavior

If I change the name to other strings without leading 'ud', the project can run.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: N/A
  pnpm: 8.4.0
Relevant Packages:
  next: 14.0.1-canary.5
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, CLI (create-next-app)

**Comment by auziqni** [comment]
same here

**Comment by darklight9811** [comment]
Same issue here, tried several versions and couldn't make it work

**Comment by balazsorban44** [comment]
Duplicate of #36078
