### ISSUE TITLE
Geist requires @next/font/local only when using turbopack

### ISSUE THREAD

**Issue by JesseKoldewijn** [vercel/next.js#57837]
### Link to the code that reproduces this issue

https://github.com/JesseKoldewijn/JKinsight

### To Reproduce

1. create a new empty project
2. install the Geist font (not sure if this happens with other font installs)
3. import the Gesit font, and add its variables to any dom node's classnames value (just the import itself triggers an error on turbo already)
4. run next dev with turbo flag to see the dev server crash or without turbopack to see no errors

### Current vs. Expected behavior

either one or two things:
1. if @next/fonts/local is required, mention this in the docs and Geist's install docs for next.js
2. if this is a bug in turbopack

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux (tested on wsl2 and bare-metal linux)
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 18.17.1
  npm: 10.2.2
  Yarn: 1.22.19
  pnpm: 8.10.0
Relevant Packages:
  next: 14.0.2-canary.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```
```


### Which area(s) are affected? (Select all that apply)

App Router, Font optimization (next/font), Turbopack (--turbo)

### Additional context

I've only tested this locally yet since turbopack (atleast for now) is only used on the dev command

**Comment by alexe-dev** [comment]
Hello. I have the same issue. Set it up as told in next js docs. Works without --turbo pack, but gives an @next/font/local error with it

**Comment by sokra** [comment]
> the dev server crash

Could you post the error message here?

**Comment by JesseKoldewijn** [comment]
> > the dev server crash
> 
> 
> 
> Could you post the error message here?

I'll drop by around the same time as I mentioned in the postCSS&tailwindCSS&turbopack issue. (around 7pm my time tomorrow)

**Comment by JesseKoldewijn** [comment]
Sorry for the late drop of the logs, our internet dropped out at the end of the day. Down below you'll find the logs I get when trying to load the page while also loading geist inside of my layout. 

<details>
  <summary>Click me to open log output</summary>
<code>⨯ Error: @next/font/local failed to run or is incorrectly configured.
If you just installed `@next/font`, please try restarting `next dev` and resaving your file.
Read more: https://nextjs.org/docs/basic-features/font-optimization
    at Object.<anonymous> (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/node_modules__pnpm_b3987e._.js:4646:7)
    at [project]/node_modules/.pnpm/@next+font@13.5.6/node_modules/@next/font/local/index.js [rsc] (ecmascript) (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/node_modules__pnpm_b3987e._.js:4648:3)
    at instantiateModule (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at esmImport (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:110:20)
    at /home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/node_modules__pnpm_b3987e._.js:4656:205
    at [project]/node_modules/.pnpm/geist@1.0.0/node_modules/geist/dist/font.js [rsc] (ecmascript) (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/node_modules__pnpm_b3987e._.js:4760:3)
    at instantiateModule (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at esmImport (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:110:20)
    at /home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[root of the server]__87c43d._.js:16:184
    at [project]/src/app/layout.tsx [rsc] (ecmascript) (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[root of the server]__87c43d._.js:49:3)
    at instantiateModule (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at esmImport (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[turbopack]_runtime.js:110:20)
    at Module.default (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/[root of the server]__87c43d._.js:53:20)
    at tree.layout (/home/jesse/wsl-projects/GlitchTech/jkinsight/.next/server/chunks/node_modules__pnpm_b3987e._.js:4830:162)
    at eq (/home/jesse/wsl-projects/GlitchTech/jkinsight/node_modules/.pnpm/next@14.0.3-canary.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:401014)
    at re (/home/jesse/wsl-projects/GlitchTech/jkinsight/node_modules/.pnpm/next@14.0.3-canary.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:5835)
    at /home/jesse/wsl-projects/GlitchTech/jkinsight/node_modules/.pnpm/next@14.0.3-canary.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:18630
    at eR (/home/jesse/wsl-projects/GlitchTech/jkinsight/node_modules/.pnpm/next@14.0.3-canary.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:198638)
    at eW (/home/jesse/wsl-projects/GlitchTech/jkinsight/node_modules/.pnpm/next@14.0.3-canary.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:202289)
    at ez (/home/jesse/wsl-projects/GlitchTech/jkinsight/node_modules/.pnpm/next@14.0.3-canary.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:203045)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Timeout._onTimeout (/home/jesse/wsl-projects/GlitchTech/jkinsight/node_modules/.pnpm/next@14.0.3-canary.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:216301)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  digest: '541524011',
  page: '/'
}<code/>
</details>

**Comment by ForsakenHarmony** [comment]
@JesseKoldewijn can you confirm this is still happening on the latest canary?

**Comment by JesseKoldewijn** [comment]
> @JesseKoldewijn can you confirm this is still happening on the latest canary?

I'll check that right away!
