### ISSUE TITLE
Can't import Node.js core modules inside instrumentation file

### ISSUE THREAD

**Issue by coltonehrman** [vercel/next.js#58003]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js/tree/canary/examples/with-opentelemetry

### To Reproduce

1. Add an instrumentation file
2. Include & import any npm module that has a core Node.js dependency in it
3. Run `next dev`

### Current vs. Expected behavior

Currently, Next.js throws and error at any core Node.js module import/require line.

```
❯ npm run dev

> dev
> next dev

   ▲ Next.js 14.0.1
   - Local:        http://localhost:3000
   - Experiments (use at your own risk):
     · instrumentationHook

 ○ Compiling /instrumentation ...
 ⨯ ../../node_modules/<redacted>
Module not found: Can't resolve 'child_process'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../node_modules/<redacted>
../../node_modules/<redacted>
../../<redacted>
./instrumentation.ts
TypeError: An error occurred while loading instrumentation hook: instrumentationHook.register is not a function
    at DevServer.runInstrumentationHookIfAvailable (<redacted>/node_modules/next/dist/server/dev/next-dev-server.js:409:43)
    at async DevServer.prepareImpl (<redacted>/node_modules/next/dist/server/dev/next-dev-server.js:208:9)
    at async NextServer.prepare (<redacted>/node_modules/next/dist/server/next.js:159:13)
    at async initializeImpl (<redacted>/node_modules/next/dist/server/lib/render-server.js:91:5)
    at async initialize (<redacted>/node_modules/next/dist/server/lib/router-server.js:103:22)
    at async Server.<anonymous> (<redacted>/node_modules/next/dist/server/lib/start-server.js:236:36)
```

If I hop to the node_modules file and add `node:` prefix to the require line, I then get the below error.

```
❯ npm run dev

> dev
> next dev

   ▲ Next.js 14.0.1
   - Local:        http://localhost:3000
   - Experiments (use at your own risk):
     · instrumentationHook

 ○ Compiling /instrumentation ...
 ⨯ node:child_process
Module build failed: UnhandledSchemeError: Reading from "node:child_process" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:child_process
../../node_modules/<redacted>
../../node_modules/<redacted>
../../node_modules/<redacted>
../../<redacted>
TypeError: An error occurred while loading instrumentation hook: instrumentationHook.register is not a function
    at DevServer.runInstrumentationHookIfAvailable (<redacted>/node_modules/next/dist/server/dev/next-dev-server.js:409:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.prepareImpl (<redacted>/node_modules/next/dist/server/dev/next-dev-server.js:208:9)
    at async NextServer.prepare (<redacted>/node_modules/next/dist/server/next.js:159:13)
    at async initializeImpl (<redacted>/node_modules/next/dist/server/lib/render-server.js:91:5)
    at async initialize (<redacted>/node_modules/next/dist/server/lib/router-server.js:103:22)
    at async Server.<anonymous> (<redacted>/node_modules/next/dist/server/lib/start-server.js:236:36)
```

I was expecting to be able to use any core Node.js module inside the instrumentation file.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Oct  4 21:26:55 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: N/A
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by coltonehrman** [comment]
Sorry, I didn't realize the conditional in the documentation was absolutely necessary for this to work. I added and now everything is working fine.

```
if (process.env.NEXT_RUNTIME === 'nodejs') {
  await import('./instrumentation-node')
}
```

[Reference](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation)
