### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by codewithahad01** [vercel/next.js#58055]
### Link to the code that reproduces this issue

https://github.com/Abdulahadahmadi/codewithahad.git

### To Reproduce

I have a web app in Nextjs in Navbar component when I go to other router and return to main route it show the above error that I attach in title. 

### Current vs. Expected behavior

I tried many ways in stackoverflow and github issue that people suggested but I couldn't find the solution for this problem.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
operating system: window 11
next.js v 14
node v 20
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

I host this app in vercel

**Comment by IlirEdis** [comment]
Im having the same issue when trying to redirect to `notFound()`, like this:

<img width="589" alt="Screenshot 2023-11-06 at 12 47 22" src="https://github.com/vercel/next.js/assets/128377763/b58e7f0c-189a-48b3-bc34-c7b28d843573">

**Comment by IlirEdis** [comment]
@Abdulahadahmadi no, its a dynamic page. 
I'm thinking this probably happens because i'm using internationalization but im not able to debug for now.

**Comment by luisjuniorj** [comment]
This does the same:

![image](https://github.com/vercel/next.js/assets/1423420/c0e7df94-8224-4dd4-85c3-ec00c3b3d2eb)

**Comment by Abdulahadahmadi** [comment]
@IlirEdis that's fine if its a dynamic page. for your dynamic page do you have a layout.tsx file ?

**Comment by samcx** [comment]
@codewithahad01 Thank you for sharing!

Is it possible to clarify how exactly we can replicate this? I was not able to replicate it with the latest stable v14.0.04.

**Comment by zerosoul** [comment]
> @Abdulahadahmadi no, its a dynamic page. I'm thinking this probably happens because i'm using internationalization but im not able to debug for now.

Yes, after adding multilingual support to Next.js, I also encountered this issue and couldn't figure out the cause.

**Comment by yousifalraheem** [comment]
The same is happening with me. I think the error thrown is somehow captured `NextIntlClientProvider` instead of falling back to NextJS ErrorBoundary. I tried importing the `ErrorBoundary` and wrapping the content inside the `NextIntlClientProvider` which prevented the crash on the client, but it didn't show the 404 page. Instead it was telling me that nextjs encountered an error and I should check the browser console for more details.

**Comment by alaahammam** [comment]
Adding a layout.tsx file to the Dynamic Routing, e.g. [Slug] solved that Problem for me (Next.js 14.0.1)

**Comment by DrunkOldDog** [comment]
Same issue here with _internationalization_. We are using `next 13.5.6` with `next-intl`.

**Comment by uraden** [comment]
having the same issue

**Comment by devDoubleH** [comment]
Just putting it here that I found helpful: [docs](https://next-intl-docs.vercel.app/docs/routing/navigation)

**Comment by woodwoerk** [comment]
I'm seeing the same error in production (`next-intl@3.3.2` and `next@14.0.4`) but it happens spontaneously upon navigation and can't be reproduced consistently. I already have a `[locale]/not-found.tsx` file, so that doesn't help unfortunately.

Error displayed in the browser:
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

Error logged in the console:
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at aq (<URL>/_next/static/chunks/<CHUNK>.js:1:75973)
    ...
    at MessagePort.x (<URL>/_next/static/chunks/<CHUNK>.js:6:26820)
```

**Comment by SachinthaI** [comment]
Anyone found a solution? I'm having the same issue with next@14.2.3 and next-intl@3.12.0

**Comment by catosaurusrex2003** [comment]
i also having the exact same error.
originally i was on next@14.0.2
i upgraded to next@14.2.3
and same issue.

i referred
[https://github.com/facebook/react/issues/13278](https://github.com/facebook/react/issues/13278)
[https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome](https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome)

and this
[https://github.com/facebook/react/issues/24865#issuecomment-2078026197](https://github.com/facebook/react/issues/24865#issuecomment-2078026197)

none of this worked for me.

**Comment by sarkarovmurad** [comment]
Guys, I found solution. 

If yout want option `localePrefix = 'as-needed'` in file **middleware.ts** and in page, for example, **/es/about/** everything is ok, but in page **/about/** aplication is crushing, you have to check option **matcher** in your **middleware.ts** file.
I had this error when my config looked like that:
```tsx
export const config = {
  matcher: ['/', '/(es|de|fr|ja|hi|it|pl|pt|nl|ru|tr|zh|ko|vi)/:path*'],
};
```
I changed to 
```tsx
export const config = {
  matcher: ['/((?!api|_next|.*\\..*).*)'],
};
```
and now everything is ok.

**p.s.:**
If you're interested, I found this when I added the files to **app** directory (not in **[locale]**):

**not-found.tsx**:
```tsx
'use client';

import Error from 'next/error';
import React from 'react';

export default () => (
  <html lang="en">
    <body>
      <Error statusCode={404} />
    </body>
  </html>
);
```
**layout.tsx** :
```tsx
import {PropsWithChildren} from 'react';

export default ({children}: PropsWithChildren) => children;
```
After that, I saw that I had a 404 error page on the **"/about"** page. This is a lot better than when the application crashed.

https://next-intl-docs.vercel.app/docs/routing/middleware#locale-prefix-as-needed
Here in documentation written:
_1. If you use this strategy, you should make sure that [your matcher detects unprefixed pathnames](https://next-intl-docs.vercel.app/docs/routing/middleware#matcher-no-prefix)._

**Comment by duonghungkiet** [comment]
> Guys, I found solution.
> 
> If yout want to use option `localePrefix = 'as-needed'` in file **middleware.ts** and in page, for example, **/es/about/** everything is ok, but in page **/about/** aplication is crushing, you should check option **matcher** in your **middleware.ts** file. I had this error when my config looked like that:
> 
> ```tsx
> export const config = {
>   matcher: ['/', '/(es|de|fr|ja|hi|it|pl|pt|nl|ru|tr|zh|ko|vi)/:path*'],
> };
> ```
> 
> I changed to
> 
> ```tsx
> export const config = {
>   matcher: ['/((?!api|_next|.*\\..*).*)'],
> };
> ```
> 
> and now everything is ok.
> 
> **p.s.:** If you're interested, I found this when I added the files to **app** directory (not in **[locale]**):
> 
> **not-found.tsx**:
> 
> ```tsx
> 'use client';
> 
> import Error from 'next/error';
> import React from 'react';
> 
> export default () => (
>   <html lang="en">
>     <body>
>       <Error statusCode={404} />
>     </body>
>   </html>
> );
> ```
> 
> **layout.tsx** :
> 
> ```tsx
> import {PropsWithChildren} from 'react';
> 
> export default ({children}: PropsWithChildren) => children;
> ```
> 
> After that, I saw that I had a 404 error page on the **"/about"** page. This is a lot better than when the application crashed.
> 
> https://next-intl-docs.vercel.app/docs/routing/middleware#locale-prefix-as-needed Here in documentation written: _1. If you use this strategy, you should make sure that [your matcher detects unprefixed pathnames](https://next-intl-docs.vercel.app/docs/routing/middleware#matcher-no-prefix)._

Thanks a lot, it's work for me

**Comment by ryanfavour4** [comment]
> I tried to move from my landing page to my auth/login page. then tried to move back to my landing page from my login page but I am getting this error

```
Unhandled Runtime Error
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Call Stack
React
```

> And yes I am using Link tag `<Link href={"/"}>Login</Link>`

**Comment by arekspiewak1991** [comment]
> > I tried to move from my landing page to my auth/login page. then tried to move back to my landing page from my login page but I am getting this error
> 
> ```
> Unhandled Runtime Error
> NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> 
> Call Stack
> React
> ```
> 
> > And yes I am using Link tag `<Link href={"/"}>Login</Link>`

I had same problem when I have started using next-i18n navigation, and I mixed from where I do "import { Link }"
so I stared having such issue when Link was imported fromo "next", then I realized I should import from my "navigation.ts", so like: `import { Link } from @/src/navigation`

**Comment by Ahmad-Hanki** [comment]
guys, I have the exacts same issue. im useing localePrefix = 'as-needed'.
you dont need to add custon notfoud or navigationts. all you need is to add this matcher

  matcher: ["/((?!api|_next|.*\\..*).*)"],
in the middleware.ts

**Comment by abolfazlNik** [comment]
if you get this error when you want to create multiple layout.jsx files for different parts of your application make sure to return a react fragment (<></>) from any layout.jsx component Except the root layout. so DO NOT return html and body tag again.

**Comment by foadtkf** [comment]
> if you get this error when you want to create multiple layout.jsx files for different parts of your application make sure to return a react fragment (<></>) from any layout.jsx component Except the root layout. so DO NOT return html and body tag again.

Man.. this helped me a lot and this is the legit solution I guess..

**Comment by DaneSharafinski** [comment]
FYI my issue was I was missing a layout.tsx at the root /app/ folder. I am using internationalization, so I have app/[locale]/ directory structure. My root layout was sitting at /app/[locale]/layout.tsx, but since moving it to /app/layout.tsx my `notFound()` invocations do render the 404 Not Found page successfully.

**Comment by philwolstenholme** [comment]
Whenever I've had this error it's been because I've forgotten to add a `default.tsx` file to a parallel route slots, e.g. `src/app/@modal/default.tsx`.

The file's contents can be as simple as this, it just needs to exist:

```
export default function Default() {
  return null;
}
```

**Comment by yashavanth-acharya** [comment]
> if you get this error when you want to create multiple layout.jsx files for different parts of your application make sure to return a react fragment (<></>) from any layout.jsx component Except the root layout. so DO NOT return html and body tag again.

thanks a lot @abolfazlNik

**Comment by dhruvin-rv** [comment]
I was getting this same error, but I realised that I am using next-intl for my entire web app, and I have placed not-found.tsx in app/not-found.tsx, but instead, it should be inside app/[locale]/not-found.tsx and the issue is resolved by doing that.

**Comment by Eliot00** [comment]
Found same error if `Script` not inside a `div`:

```tsx
'use client'

import Script from 'next/script'

export default function Comment() {

  // replace <div> with <> will get error
  return (
    <div>
      <div id="tcomment"></div>
      <Script
        src="https://cdn.jsdelivr.net/npm/twikoo@1.6.39/dist/twikoo.min.js"
        onLoad={() => {
          window.twikoo.init({
            envId: '',
            el: '#tcomment',
            lang: 'zh-CN',
          })
        }}
      />
    </div>
  )
}
```

**Comment by Eliot00** [comment]
> I wrote a comment component with twikoo, if `Script` not inside a `div`, every time leave a page with this component will get error `NotFoundError: Failed to execute 'removeChild' on 'Node'`:
> 
> ```tsx
> 'use client'
> 
> import Script from 'next/script'
> 
> export default function Comment() {
> 
>   // replace <div> with <> will get error
>   return (
>     <div>
>       <div id="tcomment"></div>
>       <Script
>         src="https://cdn.jsdelivr.net/npm/twikoo@1.6.39/dist/twikoo.min.js"
>         onLoad={() => {
>           window.twikoo.init({
>             envId: '',
>             el: '#tcomment',
>             lang: 'zh-CN',
>           })
>         }}
>       />
>     </div>
>   )
> }
> ```
> 
> Edited: But if a `div` is added, `onLoad` will not be executed when entering the page for the first time, must refresh.

Workaround:

```tsx
'use client'

import Script from 'next/script'

export default function Comment() {
  return (
    <div>
      <div id="tcomment"></div>
      <Script
        src="https://cdn.jsdelivr.net/npm/twikoo@1.6.39/dist/twikoo.min.js"
        onReady={() => {
            console.log("excuted")
          window.twikoo.init({
          })
        }}
      />
    </div>
  )
}
```

**Comment by Emmanuel-FSE** [comment]
```
'use client';
import DrepProfileCard from '@/components/atoms/DrepProfileCard';
import DrepTimeline from '@/components/molecules/DrepTimeline';
import { useGetSingleDRepQuery } from '@/hooks/useGetSingleDRepQuery';
import { notFound, useParams } from 'next/navigation';
import DrepClaimProfileCard from '@/components/atoms/DrepClaimProfileCard';

const page = () => {
  const { drepid } = useParams();
  const { dRep, isDRepLoading } = useGetSingleDRepQuery(drepid);

  if (!isDRepLoading && !dRep) {
    notFound();
  }

  return (
      <div className="flex flex-col lg:flex-row">
        <div className="lg:sticky lg:top-10 lg:w-[30%] lg:self-start lg:!scroll-smooth">
          {dRep?.drep_id ? (
            <DrepProfileCard drep={dRep} state={isDRepLoading} />
          ) : (
            <DrepClaimProfileCard drep={dRep} state={isDRepLoading} />
          )}
        </div>
        <div className="lg:w-[70%]">
            <DrepTimeline drep={dRep} />
        </div>
      </div>
  );
};

export default page;
```
I am also running into the same error when trying to use notFound().
Any tips?
Thanks.

**Comment by AnanthSankaralingam** [comment]
I fixed this issue by adding a layout.js page to the route (NextJS folder) I was rendering, hope it helps!

**Comment by krish287-rejoice** [comment]
hey did you see this is my layout file and i have used gsap and lenis and when i am changing the pages via links 4 to 5 time fifth time got this error 
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

this is my project github link and project link
github :- https://github.com/krishvaghasiya705/aristo
project link :- https://aristo-group.netlify.app/


how can i resolve it could you please help me 
![Image](https://github.com/user-attachments/assets/049ea03f-eb1b-400c-8a93-5b20372b50ad)

**Comment by jaakdentrekhaak** [comment]
I got the error from the title because of Google Translate that automatically translated everything on the page. This solved the issue for me: https://stackoverflow.com/a/12238414/9720964

In the root layout file: `<html className="notranslate" translate="no">`

**Comment by risuvoo** [comment]
@jaakdentrekhaak Thanks! You're right — this worked for me too.

I encountered the same issue while integrating Google Translate in both Next.js 13 and Next.js 15. The browser threw the following error:

> NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**### How I fixed it**

I created a small utility function to patch the DOM methods used by Google Translate:

```javascript
// utils/applyGoogleTranslateDOMPatch.ts
export default function applyGoogleTranslateDOMPatch() {
  if (typeof Node === "function" && Node.prototype) {
    const originalRemoveChild = Node.prototype.removeChild;

    Node.prototype.removeChild = function (child) {
      if (child.parentNode !== this) {
        console.warn(
          "Google Translate attempted to remove a child node from the wrong parent. Skipping.",
          {
            childNode: child?.nodeName,
            expectedParent: this?.nodeName,
            actualParent: child?.parentNode?.nodeName,
          }
        );
        return child;
      }

      return originalRemoveChild.apply(this, arguments);
    };

    const originalInsertBefore = Node.prototype.insertBefore;

    Node.prototype.insertBefore = function (newNode, referenceNode) {
      if (referenceNode && referenceNode.parentNode !== this) {
        console.warn(
          "Google Translate attempted to insert before a reference node from the wrong parent. Skipping.",
          {
            newNode: newNode?.nodeName,
            expectedParent: this?.nodeName,
            actualParent: referenceNode?.parentNode?.nodeName,
          }
        );
        return newNode;
      }

      return originalInsertBefore.apply(this, arguments);
    };
  }
}

``` 

**### How to use**

Call this function once in your RootLayout (or top-level layout) inside a useEffect. Make sure the component has the 'use client' directive:

```javascript
'use client';

import { useEffect } from 'react';
import applyGoogleTranslateDOMPatch from '@/utils/applyGoogleTranslateDOMPatch';

export default function RootLayout({ children }) {
  useEffect(() => {
    applyGoogleTranslateDOMPatch();
  }, []);

  return <>{children}</>;
}

``` 

⚠️ Important Notice

If you experience similar DOM-related errors with other packages or libraries that dynamically create or manipulate DOM elements (such as translation tools, chat widgets, or third-party overlays), you should apply this patch as well.

**Comment by jonasdev** [comment]
Doesn't seem to be **NextJS** only?
I receive it after bumping an application from react 16.14 to react 17 using Vite

<img width="1077" height="152" alt="Image" src="https://github.com/user-attachments/assets/6301c1b8-2d8f-47b1-befe-db33e5840beb" />

Found in `node_modules/.vite/deps` chunk

**Comment by ZemanJiri** [comment]
I will also contribute one solution that helped me.
We switched to **[NextIntl](https://next-intl.dev/docs/getting-started/app-router)** ​​on the project and started using routing.
The problem that sometimes caused our application to crash was that we were using **Next router** for the **push** function. When I changed the import **(import { useRouter } from 'next/router'**) to **useRouter** from **NextIntl**, everything started working again. 

_The problem was in the usage_.
Next router and how we used it before was: 
`router.push(routes.index, { locale: locale })`
Now with NextIntl ​​router it is: 
`router.push(routes.index)`

**Comment by Fanoflix** [comment]
I do not have any internationalization / translations in my app and one of my customers still got this error.

As stated previously, the error is not reproducible consistently.

**Comment by piscodev** [comment]
@risuvoo that got mine fixed, thanks!

```
// utils/applyGoogleTranslateDOMPatch.ts
export default function applyGoogleTranslateDOMPatch()
{
    if (typeof Node === "function" && Node.prototype)
    {
        const originalRemoveChild = Node.prototype.removeChild
        Node.prototype.removeChild = function<T extends Node>(child: T): T
        {
            if (child.parentNode !== this)
            {
                console.warn("Google Translate attempted to remove a child node from the wrong parent. Skipping.",
                {
                    childNode: child?.nodeName,
                    expectedParent: this?.nodeName,
                    actualParent: child?.parentNode?.nodeName,
                }
            )
                return child
            }

            return originalRemoveChild.call(this, child) as T
        }

        const originalInsertBefore = Node.prototype.insertBefore
        Node.prototype.insertBefore = function<T extends Node>(newNode: T, referenceNode: Node | null): T
        {
            if (referenceNode && referenceNode.parentNode !== this)
            {
                console.warn("Google Translate attempted to insert before a reference node from the wrong parent. Skipping.",
                {
                    newNode: newNode?.nodeName,
                    expectedParent: this?.nodeName,
                    actualParent: referenceNode?.parentNode?.nodeName,
                })

                return newNode
            }

            return originalInsertBefore.call(this, newNode, referenceNode) as T
        }
    }
}
```

**Comment by philwolstenholme** [comment]
Does patching `Node.removeChild` and `Node.insertBefore` stop Google Translate from working properly? Or is it a case that they wouldn't have worked properly even without the patching? 

The errors can be annoying when they fill up Sentry etc but I wouldn't want to prevent users who need to translate from being able to translate…

**Comment by eduardomrigo** [comment]
> [@jaakdentrekhaak](https://github.com/jaakdentrekhaak) Thanks! You're right — this worked for me too.
> 
> I encountered the same issue while integrating Google Translate in both Next.js 13 and Next.js 15. The browser threw the following error:
> 
> > NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> 
> **### How I fixed it**
> 
> I created a small utility function to patch the DOM methods used by Google Translate:
> 
> // utils/applyGoogleTranslateDOMPatch.ts
> export default function applyGoogleTranslateDOMPatch() {
>   if (typeof Node === "function" && Node.prototype) {
>     const originalRemoveChild = Node.prototype.removeChild;
> 
>     Node.prototype.removeChild = function (child) {
>       if (child.parentNode !== this) {
>         console.warn(
>           "Google Translate attempted to remove a child node from the wrong parent. Skipping.",
>           {
>             childNode: child?.nodeName,
>             expectedParent: this?.nodeName,
>             actualParent: child?.parentNode?.nodeName,
>           }
>         );
>         return child;
>       }
> 
>       return originalRemoveChild.apply(this, arguments);
>     };
> 
>     const originalInsertBefore = Node.prototype.insertBefore;
> 
>     Node.prototype.insertBefore = function (newNode, referenceNode) {
>       if (referenceNode && referenceNode.parentNode !== this) {
>         console.warn(
>           "Google Translate attempted to insert before a reference node from the wrong parent. Skipping.",
>           {
>             newNode: newNode?.nodeName,
>             expectedParent: this?.nodeName,
>             actualParent: referenceNode?.parentNode?.nodeName,
>           }
>         );
>         return newNode;
>       }
> 
>       return originalInsertBefore.apply(this, arguments);
>     };
>   }
> }
> **### How to use**
> 
> Call this function once in your RootLayout (or top-level layout) inside a useEffect. Make sure the component has the 'use client' directive:
> 
> 'use client';
> 
> import { useEffect } from 'react';
> import applyGoogleTranslateDOMPatch from '@/utils/applyGoogleTranslateDOMPatch';
> 
> export default function RootLayout({ children }) {
>   useEffect(() => {
>     applyGoogleTranslateDOMPatch();
>   }, []);
> 
>   return <>{children}</>;
> }
> ⚠️ Important Notice
> 
> If you experience similar DOM-related errors with other packages or libraries that dynamically create or manipulate DOM elements (such as translation tools, chat widgets, or third-party overlays), you should apply this patch as well.

this worked for me, thanks!

**Comment by pedrouzcategui** [comment]
If you are using Next.js and GSAP, and using the Scroll Smoother plugin, be careful by adding the Scroll Smoother plugin in the layout.tsx or page.tsx files. The problem is that the useGSAP plugin requires useClient directive, but you shouldn't be creating "use client" directives on page and/or layouts directly.

**Comment by icyJoseph** [comment]
There's a good breakdown about this issue here: https://martijnhols.nl/blog/everything-about-google-translate-crashing-react

All in all, it is really an upstream issue, that user-land code may run into, and likewise, user-land code can fix. The discoverability, or awareness during development time is annoying indeed. The next.js site had a few of these, that we have fixed too. 

I am gonna schedule this to be closed.
