### ISSUE TITLE
Requests with `form-data` or `x-www-form-data-urlencoded` returns error

### ISSUE THREAD

**Issue by lkimrxnt** [vercel/next.js#58152]
### Link to the code that reproduces this issue

https://github.com/lkimrxnt/next-formData-issue

#### form-data
1. Start application in development (port 3000)
2. Send `POST` request to the application with any form data:
```
curl --location 'http://localhost:3000/' \
--form 'username="testUserName"' \
--form 'password="testPassword"'
```

### x-www-form-data-urlencoded
1. Start application in development (port 3000)
2. Send `POST` request to the application with any form data:
```
curl --location 'http://localhost:3000/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'username=testUserName' \
--data-urlencode 'password=testPassword'
```

#### Current
If `form-data` or `x-www-form-data-urlencoded` has been sent the application returns the error below:
```
Missing `origin` header from a forwarded Server Actions request.
 ⨯ TypeError: s is not a function
    at C:\dev\test-next-app\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:13:5619
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async tE (C:\dev\test-next-app\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:13:4860)
    at async tV (C:\dev\test-next-app\my-app\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:13:32468)
    at async doRender (C:\dev\test-next-app\my-app\node_modules\next\dist\server\base-server.js:1294:26)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (C:\dev\test-next-app\my-app\node_modules\next\dist\server\base-server.js:1446:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\dev\test-next-app\my-app\node_modules\next\dist\server\base-server.js:1361:28)
    at async DevServer.renderPageComponent (C:\dev\test-next-app\my-app\node_modules\next\dist\server\base-server.js:1600:24)
    at async DevServer.renderToResponseImpl (C:\dev\test-next-app\my-app\node_modules\next\dist\server\base-server.js:1638:32)
    at async DevServer.pipeImpl (C:\dev\test-next-app\my-app\node_modules\next\dist\server\base-server.js:826:25)
    at async DevServer.handleCatchallRenderRequest (C:\dev\test-next-app\my-app\node_modules\next\dist\server\next-server.js:623:13)
    at async DevServer.handleRequestImpl (C:\dev\test-next-app\my-app\node_modules\next\dist\server\base-server.js:728:17) {
  page: '/'
}
```
If `x-www-form-data-urlencoded` has been sent the equest stuck and never completes

## Expected
The application executes logic in the [middleware](https://github.com/lkimrxnt/next-formData-issue/blob/master/src/middleware.ts), parses formData and renders root page `/`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

#### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 16.20.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.6.12
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Additional context

I've tested the same behavior using the latest version of next (14).

#### Important note
If I send the requests below to a page in `Pages routing` [`/pages/testPage`](https://github.com/lkimrxnt/next-formData-issue/blob/master/src/pages/testPage/index.tsx), everything works as expected.

```
curl --location 'http://localhost:3000/testPage' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'username=testUserName' \
--data-urlencode 'password=testPassword'
```
```
curl --location 'http://localhost:3000/testPage' \
--form 'username="testPassword"' \
--form 'password="testPassword"'
```

<sub>[NEXT-1761](https://linear.app/vercel/issue/NEXT-1761/requests-with-form-data-or-x-www-form-data-urlencoded-returns-error)</sub>

**Comment by atomicleopard** [comment]
This is impacting my application which is using inbound webhooks from Slack. I'm trying to receive the call using a Route Handler registered for `POST`

My application logs `Missing `origin` header from a forwarded Server Actions request.` and the handler is never called.

**Comment by feedthejim** [comment]
what's the usecase?

**Comment by laurens-mesure** [comment]
> what's the usecase?

The usecase is using data from `x-www-form-data-urlencoded` in route handlers?

**Comment by rpavlovs** [comment]
Same issue.

I have a POST endpoint that is supposed receive files as form data. It works if do just that, but as soon as I import and try to use logic to process those files I get this error. I'm not sure what exactly is causing this.

Importing Prisma is fine. Do these app router endpoints have anything special about how they are compiled? My runtime is explicitly set to 'nodejs'

**Comment by rpavlovs** [comment]
I was able to trace it to this package: https://github.com/AIDungeon/GPT-3-Encoder

Removing import & usage fixed the issue 🤔
