### ISSUE TITLE
NextJS export does not recognise generateStaticParams

### ISSUE THREAD

**Issue by meds** [vercel/next.js#58171]
### Link to the code that reproduces this issue

https://github.com/meds/nextjs-broken-export

### To Reproduce

1. Run `pnpm build`

### Current vs. Expected behavior

I expected nextjs to build and export to an output directory with static files.

Instead I got an error:

`Error: Page "/test/[id]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Tue Jul 18 20:35:35 PDT 2023; root:xnu-10002.0.199.505.1~3/RELEASE_ARM64_T6000
Binaries:
  Node: 18.12.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 8.6.5
Relevant Packages:
  next: 14.0.1
  eslint-config-next: N/A
  react: 18.0.0
  react-dom: 18.0.0
  typescript: 5.0.2
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

App Router, Static HTML Export (output: "export")

**Comment by GonzagaGustavo** [comment]
This is not a bug. You need to return the array with an object with a parameter that indicates the dynamic route.
Ex: 
```
export function generateStaticParams() {
  return [{ id: "test" }];
}

export default async function Page(props: any) {
  return <div>{JSON.stringify(props.params)}</div>;
}

```

**Comment by airtonix** [comment]
It's a bug.

```tsx
// apps/web/src/app/p/[slug]/page.tsx

import { DocumentRenderer } from '@keystatic/core/renderer';

import { NormalPageTemplate } from '@zenobius/ui-web-pagetemplates-normalpage';
import { Site } from '@zenobius/ui-web-components-sitelayout';
import { CmsContent } from '@zenobius/ui-web-components-cmscontent'

import { ContentStore } from '../../../services/ContentStore';

export default async function Post({ params }: {
    params: { slug: string }
}) {
    const post = await ContentStore.collections.pages.read(params.slug);

    if (!post) {
        return (
            <Site>
                <h1>Not found</h1>
            </Site>
        )
    }

    return (
        <Site>
            <NormalPageTemplate
                title={post.title}
                stage={post.stage}
            >
                <CmsContent>
                    <DocumentRenderer document={await post.content()} />
                </CmsContent>
            </NormalPageTemplate>
        </Site>
    );
}


type Params = {
    slug: string;
}

export async function generateStaticParams(): Promise<Params[]> {

    const pages = await ContentStore.collections.pages.all();

    if (!pages) {
        return [{ slug: 'not-found' }];
    }

    return pages.map(page => ({
        slug: page.slug
    }));
}
```

then

```console
zenobi.us on git feat/keystatic [x!?] via nodejs v18.17.0 took 15s 
x yarn nx build web

> nx run web:build:production

   ▲ Next.js 14.0.4
   - Experiments (use at your own risk):
     · typedRoutes
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types ...
   Collecting page data ...
> Build error occurred
Error: Page "/p/[slug]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.
    at /mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/build/index.js:1012:59
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/trace/trace.js:147:20)
    at async Promise.all (index 8)
    at async /mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/build/index.js:892:17
    at async Span.traceAsyncFn (/mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/trace/trace.js:147:20)
    at async /mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/build/index.js:829:124
    at async Span.traceAsyncFn (/mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/trace/trace.js:147:20)
    at async build (/mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/build/index.js:187:29)
    at async main (/mnt/Store/Projects/Mine/Github/zenobi.us/node_modules/next/dist/bin/next:157:5)
Error occurred while trying to run the build command
1

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project web (8s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

**Comment by luoluo5945** [comment]
我懂了，你可以根据环境变量或者一些条件判断来按需打包自己需要的页面，不需要的统统打包到指定的垃圾桶目录，例如：'not-found'
（I see. You can package the pages you need based on environment variables or some criteria. Everything that is not needed is packed into the designated bin directory, For example: 'not-found'）
`
// apps/web/src/app/p/[slug]/page.tsx

export async function generateStaticParams(): Promise<Params[]> {

    const pages = await ContentStore.collections.pages.all();

    if (!pages || pages.length === 0) {
        return [{ slug: 'not-found' }];
    }

    return pages.map(page => ({
        slug: page.slug
    }));
}
`
这样打包出来的out里面会有一个 “not-found” 垃圾桶目录，可以在build脚本里面手动删了这个目录就好了！
(In this way, there will be a "not-found" garbage bin directory inside the packaged out, then you can manually delete this directory in the build script!)

**Comment by pthurmond-vmlyr** [comment]
> This is not a bug. You need to return the array with an object with a parameter that indicates the dynamic route. Ex:
> 
> ```
> export function generateStaticParams() {
>   return [{ id: "test" }];
> }
> 
> export default async function Page(props: any) {
>   return <div>{JSON.stringify(props.params)}</div>;
> }
> ```

So I have a situation where I have no idea what the value will end up being. I cannot query a collection or DB or whatever. It is truly dynamic. How do I tell it that it needs to just pull it from the URL path on page load? The documentation is VERY unclear on this.

**Comment by simplenotezy** [comment]
> > This is not a bug. You need to return the array with an object with a parameter that indicates the dynamic route. Ex:
> > ```
> > export function generateStaticParams() {
> >   return [{ id: "test" }];
> > }
> > 
> > export default async function Page(props: any) {
> >   return <div>{JSON.stringify(props.params)}</div>;
> > }
> > ```
> 
> So I have a situation where I have no idea what the value will end up being. I cannot query a collection or DB or whatever. It is truly dynamic. How do I tell it that it needs to just pull it from the URL path on page load? The documentation is VERY unclear on this.

Same - we just want client rendering (static site) without pre-generating any routes

**Comment by landed1** [comment]
This is how I finally got it working for me - https://github.com/landed1/poolsdubai/

`export const generateStaticParams = async ()=>{
    //we need to return all the pages from the .md files in a specific folder.
    const slugs = await getSlugs();
    //slugs ['about2.md','extra.md','random'] - an array of markdown files
    const other = slugs.map(page => ({
      slug: page.replace('.md','')
    }));
    return await other;
}`

**Comment by ajwaaholding** [comment]
> return [{ id: "test" }];

Exactly. This is a issue actually. I have perfectly written generatestaticparams code and still i get like its missing why

**Comment by emmanuel-salvo** [comment]
Any updates on this?

**Comment by ajwaaholding** [comment]
I am still trying but its stated in document that generateSTtaticparams is supported for output export static. Dynamic routing witjhout generatestaticparams is not supported . Lets work together reach out to me at https://www.linkedin.com/in/mohammed-ismail-3742b8215/

**Comment by aeskildsen** [comment]
> This error wasted an hour of my life. Could we update the error message here:
> 
> > [Error: Page "/projects/[projectName]/[milestoneName]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.]
> 
> The page isn't missing `generateStaticParams`... it's just that `generateStaticParams` is returning an empty array.

I came here with the same story. I agree, the error message could be improved. If `generateStaticParams` is a function but doesn't return the expected output, the error message could perhaps be updated to say something like this:

```
[Error: The return value of "generateStaticParams()" for page "/[slug]" is incompatible with "output: export" config.]
```

**Comment by jsuryakt** [comment]
**TL;DR**: The error fires when `generateStaticParams()` returns `[]`, not when it's actually missing. The fix is to ensure it always returns at least one param.

I hit this on Next.js 16.2.4 with `output: "export"` and Turbopack. My `generateStaticParams` fetched from a remote API that was returning HTTP 500, so the catch block returned `[]`. The error message led me down a hours-long rabbit hole inspecting compiled Turbopack chunks, thinking the export was being tree-shaken.

**What actually happens:**

```
generateStaticParams returns [] → Next.js treats it as "missing" → misleading error
```

**Minimal fix — always return at least one param:**

```ts
export async function generateStaticParams() {
  try {
    const res = await fetch(`${process.env.API_URL}/posts`);
    if (!res.ok) return [{ slug: "placeholder" }];
    const posts: { slug: string }[] = await res.json();
    if (posts.length === 0) return [{ slug: "placeholder" }];
    return posts.map((p) => ({ slug: p.slug }));
  } catch {
    return [{ slug: "placeholder" }];
  }
}
```

The page component handles unknown slugs with `notFound()`, so `/blog/placeholder` just renders a 404 — harmless.

**Suggestion**: The error message should differentiate between "function not exported" vs "function returned empty array." Something like:

```
Error: "generateStaticParams()" for page "/blog/[slug]" returned an empty array.
With "output: export", at least one param must be generated. If this route has
no content yet, return a placeholder value or remove the dynamic route.
```

**Comment by marcoshernanz** [comment]
Thanks for the report. The reproduction returns `['test']` for an `[id]` route, but `generateStaticParams()` must return params objects such as `[{ id: 'test' }]`. Current Next.js builds that form successfully and reports the invalid string value directly, fixed by #95968 and released in 16.3.0. The separate empty-array case discussed below is tracked in #61213, so I’m closing this as resolved.
