### ISSUE TITLE
Generating incorrect paths on assembly

### ISSUE THREAD

**Issue by alexop1000** [vercel/next.js#58244]
### Link to the code that reproduces this issue

https://github.com/alexop1000/nextjs-issue-reproduction/tree/master

### To Reproduce

1. Build your next application on Windows (npm run build)
2. Build the docker image (for example, ``docker build --pull --rm -f "Dockerfile" -t nexttest:latest "."``)
3. Run the docker image on a Linux machine, or on Docker desktop.

### Current vs. Expected behavior

The user gets an internal error 500 when visiting your website. You get "Error: Cannot find module 'next/dist\client\components\static-generation-async-storage-external.js'" on server logs. The specifics can be found in [this discussion](https://github.com/vercel/next.js/discussions/56010).
Example error message output:
```bash
2023-11-09 10:52:50  ⨯ Error: Cannot find module 'next/dist\client\components\static-generation-async-storage.external.js'
2023-11-09 10:52:50 Require stack:
2023-11-09 10:52:50 - /usr/src/app/.next/server/app/_not-found.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/require.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/next-server.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/next.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/server/lib/start-server.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/cli/next-start.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/lib/commands.js
2023-11-09 10:52:50 - /usr/src/app/node_modules/next/dist/bin/next
2023-11-09 10:52:50     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
2023-11-09 10:52:50     at /usr/src/app/node_modules/next/dist/server/require-hook.js:54:36
2023-11-09 10:52:50     at Module._load (node:internal/modules/cjs/loader:901:27)
2023-11-09 10:52:50     at Module.require (node:internal/modules/cjs/loader:1115:19)
2023-11-09 10:52:50     at mod.require (/usr/src/app/node_modules/next/dist/server/require-hook.js:64:28)
2023-11-09 10:52:50     at require (node:internal/modules/helpers:130:18)
2023-11-09 10:52:50     at 5319 (/usr/src/app/.next/server/app/_not-found.js:1:612)
2023-11-09 10:52:50     at t (/usr/src/app/.next/server/webpack-runtime.js:1:127)
2023-11-09 10:52:50     at 2564 (/usr/src/app/.next/server/chunks/349.js:1:117695)
2023-11-09 10:52:50     at t (/usr/src/app/.next/server/webpack-runtime.js:1:127) {
2023-11-09 10:52:50   code: 'MODULE_NOT_FOUND',
2023-11-09 10:52:50   requireStack: [
2023-11-09 10:52:50     '/usr/src/app/.next/server/app/_not-found.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/require.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/next-server.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/next.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/server/lib/start-server.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/cli/next-start.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/lib/commands.js',
2023-11-09 10:52:50     '/usr/src/app/node_modules/next/dist/bin/next'
2023-11-09 10:52:50   ]
2023-11-09 10:52:50 }
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: arm64
  Version: SMP Fri Aug 18 21:57:12 PDT 2023
Binaries:
  Node: 20.8.1
  npm: 10.1.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.0
  react: 18.2.0
  react—don: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Operating System (Windows, MacOS, Linux)

### Additional context

If you look in the discussion forum, you can see that it works in version 13.4.19.
You can also see that people have identified the specific problem that needs to be resolved.
The line:
```js
return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist")}`
```
Has to be replaced with:
```js
return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist").replace(/\\/g, "/")}`
```
In the file "\node_modules\next\dist\build\handle-externals.js", to generate the correct paths.

**Comment by shahkeyur** [comment]
+1, having same issue while deploying to app engine.

**Comment by zamry09** [comment]
***@***.***

Pada Sab, 11 Nov 2023, 12:42 PG Keyur Shah ***@***.***>
menulis:

**Comment by DeanJGrey** [comment]
Same issue when using OpenNext to deploy to AWS.
Rolling back to 13.4.19 has resolved this issue for the time being.

**Comment by mizhousoft** [comment]
+1, having same issue while deploying to app engine.

**Comment by Ryan2018-js** [comment]
+1, having same issue while deploying to app engine.

**Comment by willersonsp** [comment]
+1 here deploying on bohr/aws, using node_modules line with replace works nicely.

**Comment by Enngage** [comment]
+ 1, please fix this so we can safely upgrade to next 14

**Comment by Shdoogii** [comment]
+1, please fix this so we can safely upgrade to next 14

**Comment by kazio0** [comment]
+1

**Comment by vincent-thomas** [comment]
+1 Pleeeease fix this, its so anoying

**Comment by jayanty33** [comment]
return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist")}`

Has to be replaced with:

return `commonjs ${localRes.replace(/.*?next[/\\]dist/, "next/dist").replace(/\\/g, "/")}`  this is working on next14.0.3

**Comment by seyhak** [comment]
issue still occurs
