### ISSUE TITLE
Attempted import error: is not exported @legendapp/state

### ISSUE THREAD

**Issue by Tekutorukushi** [vercel/next.js#58440]
### Link to the code that reproduces this issue

https://github.com/Tekutorukushi/nextjs

### To Reproduce

After updating to version NextJs 14.0.2, I get an error
@legendapp/state": "^2.1.2"

```
Attempted import error: 'observer' is not exported from '@legendapp/state/react' (imported as 'observer').

  1 | import {observer} from "@legendapp/state/react";
  2 |
> 3 | const Custom = observer(() => {
    |                        ^
  4 |     return (
  5 |         <div>
  6 |             custom components
 ⨯ components\Custom\index.jsx (3:24) @ eval
 ⨯ TypeError: (0 , _legendapp_state_react__WEBPACK_IMPORTED_MODULE_1__.observer) is not a function
    at eval (./components/Custom/index.jsx:10:80)
    at (rsc)/./components/Custom/index.jsx (\project\.next\server\app\page.js:205:1)
    at __webpack_require__ (\project\.next\server\webpack-runtime.js:33:42)
    at eval (./app/page.js:11:76)
    at (rsc)/./app/page.js (\project\.next\server\app\page.js:194:1)
    at Function.__webpack_require__ (\project\.next\server\webpack-runtime.js:33:42)
```

### Current vs. Expected behavior

Should be the same as in 14.0.1

Developer response:

>It seems to be caused by [vercel/next.js#57784](https://github.com/vercel/next.js/pull/57784) and some others are reporting the same issue. I'll investigate further, but for now I guess stay on 14.0.1?
>I guess it's not breaking for my tests because we use SSG and it's an SSR specific issue?

https://github.com/LegendApp/legend-state/issues/222

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.18.2
  npm: N/A
  Yarn: v1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.2
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, Package manager (npm, pnpm, Yarn)

### Additional context

I tested my reproduction against different canary releases, and the first one that introduced the bug was 14.0.2

**Comment by jmeistrich** [comment]
This appears to be caused by this PR: https://github.com/vercel/next.js/pull/57784. Others in that thread have reported similar errors in a few other libraries.

Is there something we need to fix in the legend-state package? Or is this a bug in Next?

**Comment by lukasIO** [comment]
probably a duplicate of https://github.com/vercel/next.js/issues/57962, explanation of what's going on is in the issue.

**Comment by rshackleton** [comment]
Still happening on 14.1.0 with `react-hook-form`:

```
web:dev: Attempted import error: 'useFormContext' is not exported from 'react-hook-form' (imported as 'useFormContext').
web:dev:
web:dev: Import trace for requested module:
web:dev: ../../packages/ui/src/molecules/GiftCardPayment/GiftCardPayment.tsx
web:dev: ../../packages/ui/index.tsx
web:dev: ../../packages/ui/src/organisms/ImageTextSection/ImageTextSection.tsx
web:dev: __barrel_optimize__?names=ImageTextSection!=!../../packages/ui/index.tsx
web:dev: ./components/ImageTextSection/ImageTextSection.server.tsx
web:dev: ./components/Block/Block.server.tsx
web:dev: ./templates/ContentfulSignUpPage.tsx
web:dev: ./templates/ContentfulPage.tsx
web:dev: ./app/[lang]/page.tsx
web:dev:  ⚠ ../../packages/ui/src/molecules/GiftCardPayment/GiftCardPayment.tsx
```

Doesn't appear to cause any issues at runtime but it is littering the logs with these false-negatives.

**Comment by zantica** [comment]
hello i think i resolved the issue. I just updated legendapp and set an observable object with the same name function and then observe any change.

**Comment by zantica** [comment]
`import { observe, observable } from "@legendapp/state";

// Create an observable object
const state$ = observable({ settings: { text: "custom components" } });

// Just get and set
state$.settings.otherText.set("another text to show");

// observe re-runs when accessed observables change
observe(() => {
  console.log(state$.settings.otherText.get());
});

const Custom = function Component() {
  const text = state$.settings.text.get();
  const otherText = state$.settings.otherText.get();
  return (
    <div>
      <span>{text}</span>
    </div>
  );
};

export default Custom;
`

**Comment by marcoshernanz** [comment]
Thanks for the report! I reproduced this in 14.0.2 and 14.0.3, but it’s fixed as of 14.0.4 by #58967 and no longer reproduces in current versions.

One note: the reproduction needs `"use client"` for the `observer` component; without it, 14.0.1 also fails.

Closing as fixed. If this still happens on a current version, please open a new issue with an updated reproduction.
