### ISSUE TITLE
Receiving error when there is an RSC (React Server Component) as child 

### ISSUE THREAD

**Issue by sadik-malik** [vercel/next.js#58755]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/lucid-allen-yff639

### To Reproduce

1. Create a component which accepts a children.
```jsx
import PropTypes from "prop-types";

function Box({ children }) {
  return <div>{children}</div>;
}

Box.propTypes = {
  children: PropTypes.node,
};

export default Box;
```
2. import the component and use it is as mentioned below:

```jsx
import Box from "../components/Box";

async function FooBar() {
  return <Box>Foobar</Box>;
}

export default function Page() {
  return (
    <Box>
      <FooBar />
    </Box>
  );
}
```
3. Start the development server using npm run dev. You will encounter the warning:
```zsh
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /project/sandbox/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at /project/sandbox/node_modules/next/dist/server/require-hook.js:110:36
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /project/sandbox/node_modules/next/dist/server/app-render/app-render.js:1025:41
    at /project/sandbox/node_modules/next/dist/server/lib/trace/tracer.js:159:62
    at /project/sandbox/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/project/sandbox/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/project/sandbox/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/project/sandbox/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/project/sandbox/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /project/sandbox/node_modules/next/dist/server/lib/trace/tracer.js:106:107
    at NoopContextManager.with (/project/sandbox/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/project/sandbox/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/project/sandbox/node_modules/next/dist/server/lib/trace/tracer.js:106:32)
    at /project/sandbox/node_modules/next/dist/server/lib/trace/tracer.js:159:31
    at wrappedRender (/project/sandbox/node_modules/next/dist/server/app-render/app-render.js:1072:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  digest: undefined
}
```

4. When you make any changes in the project and hit save or just hit save again. Then, you will get the following error:
```zsh
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <div> in <div>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Component Stack
div
div
Call Stack
throwOnHydrationMismatch
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (6789:0)
tryToClaimNextHydratableInstance
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (6818:0)
updateHostComponent$1
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (15520:0)
beginWork$1
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (17355:0)
HTMLUnknownElement.callCallback
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (19443:0)
Object.invokeGuardedCallbackImpl
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (19492:0)
invokeGuardedCallback
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (19567:0)
beginWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25697:0)
performUnitOfWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24526:0)
workLoopConcurrent
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24512:0)
renderRootConcurrent
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24468:0)
performConcurrentWorkOnRoot
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (23339:0)
workLoop
node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (261:0)
flushWork
node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (230:0)
MessagePort.performWorkUntilDeadline
node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (534:0)
```

### Current vs. Expected behavior

- Current: Receiving two errors while running the project. First, when development server is start and second for hydration when changes are made in any file.
- Expected: If the following pattern of writing an RSC component is supported, then these errors should not come.
```jsx
async function FooBar() {
  return <Box>Foobar</Box>;
}
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.19", newest: "14.0.4-canary.9".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by JesseKoldewijn** [comment]
Have you tested this against the latest canary release as well? Since the info output you provided only shows 13.4.19 and since you're using typescript you could also just use TS types instead of the "prop-types" package.

**Comment by sadik-malik** [comment]
I have tried with latest canary release as well. Updated the [codesandbox](https://codesandbox.io/p/devbox/lucid-allen-yff639) example to reflect the same.

```zsh
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.4-canary.9
  eslint-config-next: 13.4.19
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

Further, my concern is not regarding prop-types package for now.

**Comment by JesseKoldewijn** [comment]
It seems like, for whatever reason the __NEXT_PRIVATE_PREBUNDLED_REACT variable isn't set in these cases. Try setting this variable on your end and check if you still get the error during the SSR process.

**Comment by JesseKoldewijn** [comment]
@shuding sorry for the ping but I believe you made a fix for a related issue earlier this year. This [codesandbox](https://codesandbox.io/p/devbox/vibrant-frost-f4cd2y?file=%2Fpackage.json) fork of @sadik-malik 's reproduction where the error mentioned doesn't show up by adding the missing variable to the dev script.

**Comment by sadik-malik** [comment]
Thank you, @JesseKoldewijn. Adding "__NEXT_PRIVATE_PREBUNDLED_REACT=next" to the dev script worked for me.

```json
{
 "dev": "__NEXT_PRIVATE_PREBUNDLED_REACT=next next dev",
}
```
