### ISSUE TITLE
Production Build Failure after v14.0.2-canary.19

### ISSUE THREAD

**Issue by phibr0** [vercel/next.js#58870]
### Link to the code that reproduces this issue

https://github.com/phibr0/next14-prod-build-failure

### To Reproduce

See [Readme](https://github.com/phibr0/next14-prod-build-failure?tab=readme-ov-file#reproduce) or:

1. `gh repo clone phibr0/next14-prod-build-failure`
2. `cd next14-prod-build-failure`
3. `pnpm compare`

### Current vs. Expected behavior

- The project compiles and typechecks successfully.
- An error occurs during the collection of page data in production builds.

```
TypeError: Cannot read properties of undefined (reading 'api')
    at 3290 (/xxx/.next/server/app/api/route.js:35:50001)
    at t (/xxx/.next/server/webpack-runtime.js:1:128)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.21
  pnpm: 8.10.5
Relevant Packages:
  next: 14.0.4-canary.14
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, SWC transpilation

### Additional context

**CSV containing build results against all recent releases: <https://github.com/phibr0/next14-prod-build-failure/blob/main/results.csv>**

- Development builds function normally.
- Production Builds using Turbopack
  (`next build --experimental-turbopack`) function normally.
- The problem seems related to webpack/swc.

**Comment by phibr0** [comment]
Still present in v14.0.4-canary.33

**Comment by phibr0** [comment]
- Still present in v14.0.5-canary.5

To sum up:

- The latest commit that broke builds: [v14.0.2-canary.19](https://github.com/vercel/next.js/releases/tag/v14.0.2-canary.19)
- The same error occured after [v13.4.20-canary.19](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.19) but it worked again after [v13.5.4-canary.10](https://github.com/vercel/next.js/releases/tag/v13.5.4-canary.10)
- Only webpack builds are broken, even turbopack works without issues

**Comment by rayepps** [comment]
I'm also running into this. Can't use temporal in Next JS actions with the latest version of Next (14.0.2).

**Comment by kdy1** [comment]
The range of swc_core: `v0.86.10` ~ `v0.86.40`

**Comment by phibr0** [comment]
I updated the [results.csv](https://github.com/phibr0/next14-prod-build-failure/blob/main/results.csv) file with the build results of different versions and configurations. 

I tested:

- Default Webpack + SWC
- Webpack + SWC (not minified)
- Webpack + Babel
- Turbopack

I just recently discovered that you can still use babel instead of SWC, and the results show that SWC might not actually be the root cause here. In fact, the results are pretty much the same no matter if SWC or babel was used. 

Interestingly, there were a few versions where the default webpack config works, but once minifying or babel is used it fails again. Turbopack works on all versions.

**Comment by gabrielalmeida** [comment]
Related to https://github.com/vercel/next.js/pull/58573
