### ISSUE TITLE
`pnpm create next-app` build fails

### ISSUE THREAD

**Issue by kirkstrobeck** [vercel/next.js#58890]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 21.2.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.10.5
Relevant Packages:
  next: 14.0.4-canary.16
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

pnpm create next-app

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

`pnpm create next-app && cd my-app && pnpm build` fails

### Expected Behavior

`pnpm create next-app && cd my-app && pnpm build` succeeds

### To Reproduce

```sh
pnpm create next-app

✔ What is your project named? … my-app
✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like to use `src/` directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to customize the default import alias (@/*)? … No / Yes
```

```sh
cd my-app
```

```sh
pnpm build

> my-app@0.1.0 build /Users/username/Desktop/next-bug/my-app
> next build

 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
   ▲ Next.js 14.0.3

 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/5)  [    ]Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at eu (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5482)
    at y (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/350.js:6:1299)
    at renderWithHooks (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5943:7)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at eu (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5482)
    at y (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/350.js:6:1299)
    at renderWithHooks (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5943:7)
Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at eu (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5482)
    at y (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/350.js:6:1299)
    at renderWithHooks (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5943:7)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at eu (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5482)
    at y (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/350.js:6:1299)
    at renderWithHooks (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at finishClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5943:7)
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at h (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:21901)
    at d (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:12210)
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:106189)
    at h (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:21901)
    at d (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:12210)
    at as (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11284
    at aw (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at ak (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at av (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:106189)
    at h (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:21901)
    at d (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:12210)
    at as (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11284
    at aw (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at ak (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at av (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
 ⨯ TypeError: Cannot read properties of null (reading 'useContext')
    at h (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:21901)
    at d (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:12210)
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:106189)
    at h (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:21901)
    at d (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:12210)
    at as (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11284
    at aw (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at ak (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at av (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:106189)
    at h (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:21901)
    at d (/Users/username/Desktop/next-bug/my-app/.next/server/chunks/373.js:1:12210)
    at as (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11284
    at aw (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at ak (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at av (/Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /Users/username/Desktop/next-bug/my-app/node_modules/.pnpm/next@14.0.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
 ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
	/_error: /404
	/_error: /500
	/_not-found
	/page: /
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by sumanth-botlagunta** [comment]
### this might help
next/document was imported in a page outside of pages/_document.js. This can cause unexpected issues in your application.

Following pages might help you checkout them once
[https://nextjs.org/docs/messages/no-document-import-in-page](https://nextjs.org/docs/messages/no-document-import-in-page)
[https://nextjs.org/docs/messages/prerender-error](https://nextjs.org/docs/messages/prerender-error)

**Comment by samcx** [comment]
@kirkstrobeck It is unclear how `create-next-app` with Pages Router is using `<Html>` outside of `_doucment.js`. I suspect that your `next-bug/my-app` is not identical to the `create-next-app` (e.g., different versions from the `next info` output). I was not

I will be closing this issue—please resubmit the issue if you can replicate this issue with `create next app`.
