### ISSUE TITLE
Unexpected token: punc ({)

### ISSUE THREAD

**Issue by lichbt-rk** [vercel/next.js#59046]
### Link to the code that reproduces this issue

https://github.com/lichbt-rk/next-14-minify-error

### To Reproduce

1. create project with npx create-next-app@latest
2. Add a class with static property
3. set swcMinify is false in next.config.js
4. Run npm run build

### Current vs. Expected behavior

Current: got the error
`> build
> next build

 ⚠ Disabling SWC Minifer will not be an option in the next major version. Please report any issues you may be experiencing to https://github.com/vercel/next.js/issues
 ✓ Linting and checking validity of types    
   ▲ Next.js 14.0.4-canary.25

Failed to compile.

../pages/TestClass.js from Terser
Unexpected token: punc ({) [../pages/TestClass.js:174,10]
    at js_error (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:32780)
    at croak (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:43882)
    at token_error (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:43989)
    at unexpected (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:44055)
    at as_property_name (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:68487)
    at concise_method_or_getset (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:64746)
    at class_ (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:64098)
    at statement (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:46908)
    at _embed_tokens_wrapper (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:45013)
    at block_ (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:56881)

../pages/index.js from Terser
Unexpected token: punc ({) [../pages/index.js:197,10]
    at js_error (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:32780)
    at croak (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:43882)
    at token_error (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:43989)
    at unexpected (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:44055)
    at as_property_name (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:68487)
    at concise_method_or_getset (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:64746)
    at class_ (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:64098)
    at statement (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:46908)
    at _embed_tokens_wrapper (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:45013)
    at block_ (/home/lichbt/Projects/next-14-minify-error/node_modules/next/dist/compiled/terser/bundle.min.js:1:56881)

> Build failed because of webpack errors
`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
node: 18.17.1
next: 14.0.3
os: ubuntu 20.04 LTS
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

**Comment by milap1296** [comment]
Same is happening with me as well!

**Comment by m19** [comment]
I believe [my comment](https://github.com/vercel/next.js/issues/58959#issuecomment-1835708983) on another issue is related.

When I set `swcMinify: false` I get `Unexpected token: punc ({` too. This happens on 14.0.3 and not 14.0.1 (the version I was using before this). In 14.0.1 I can set `swcMinify: false` and everything compiles without issue.

**Comment by kdy1** [comment]
I started working on this 😄

**Comment by kdy1** [comment]
Closing as fixed on canary. 
Forked repro: https://github.com/kdy1/repro-next-59046

<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/fed9a2ab-10d3-479a-b38f-db54536e3dc5">
