### ISSUE TITLE
build breaks when mentioning "generateSitemaps" in a comment

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#59698]
### Link to the code that reproduces this issue

https://github.com/stefanprobst/issue-next-sitemap

### To Reproduce

1. clone [repo](https://github.com/stefanprobst/issue-next-sitemap)
2. `pnpm install`
3. `pnpm run build`
4. see error

### Current vs. Expected behavior

with the following comment in [`app/sitemap.ts`](https://github.com/stefanprobst/issue-next-sitemap/blob/main/app/sitemap.ts), the build breaks:

```tsx
import type { MetadataRoute } from "next";

/**
 * If you need more than 50.0000 entries, use `generateSitemaps`.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return []
}
```

error message:

```
   Collecting page data  ...TypeError: p is not a function
    at Object.b [as generateStaticParams] (/data/Development/playground/sitemap/.next/server/app/sitemap/[__metadata_id__]/route.js:1:1145)
    at buildParams (/data/Development/playground/sitemap/node_modules/.pnpm/next@14.0.5-canary.14_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1012:58)
    at /data/Development/playground/sitemap/node_modules/.pnpm/next@14.0.5-canary.14_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1029:39
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/data/Development/playground/sitemap/node_modules/.pnpm/next@14.0.5-canary.14_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:52:24)
    at buildAppStaticPaths (/data/Development/playground/sitemap/node_modules/.pnpm/next@14.0.5-canary.14_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:966:85)
    at /data/Development/playground/sitemap/node_modules/.pnpm/next@14.0.5-canary.14_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1159:120
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/data/Development/playground/sitemap/node_modules/.pnpm/next@14.0.5-canary.14_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:147:20)

> Build error occurred
Error: Failed to collect page data for /sitemap/[__metadata_id__]
    at /data/Development/playground/sitemap/node_modules/.pnpm/next@14.0.5-canary.14_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1245:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  . ELIFECYCLE  Command failed with exit code 1.
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.12.1
Relevant Packages:
  next: 14.0.5-canary.14
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

<sub>[NEXT-2007](https://linear.app/vercel/issue/NEXT-2007/build-breaks-when-mentioning-generatesitemaps-in-a-comment)</sub>

**Comment by adidoes** [comment]
I get the error "Failed to collect page data for" not only on sitemap generation but on other /api endpoints as well, it only happens on 14.0.4+ (I tried 14.0.5 canary as well)
