### ISSUE TITLE
Incomplete module path in with-jest example

### ISSUE THREAD

**Issue by vondersam** [vercel/next.js#60239]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-jest

### Describe the Bug

When running the tests with the example out of the box, two tests fail.
```javascript
 FAIL  __tests__/index.test.tsx
  ● Test suite failed to run

    Cannot find module 'pages/index' from '__tests__/index.test.tsx'

       7 | describe('Home', () => {
       8 |   it('renders a heading', () => {
    >  9 |     render(<Home />)
         |                                                       ^
      10 |
      11 |     const heading = screen.getByRole('heading', {
      12 |       name: /welcome to next\.js!/i,

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (__tests__/index.test.tsx:9:55)
```
And
```javascript
 FAIL  __tests__/snapshot.tsx
  ● Test suite failed to run

    Cannot find module 'pages/index' from '__tests__/snapshot.tsx'

       7 | it('renders homepage unchanged', () => {
       8 |   const { container } = render(<Home />)
    >  9 |   expect(container).toMatchSnapshot()
         |                                                ^
      10 | })
      11 |

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (__tests__/snapshot.tsx:9:55)
```

I we implement these changes in these files, the tests pass:
`/__tests__/index.test.tsx`
```diff
- import Home from '@/pages/index';
+ import Home from '@/pages/home/index';
```
`__tests__/snapshot.tsx``
```diff
- import Home from '@/pages/index';
+ import Home from '@/pages/home/index'

### Expected Behavior

Tests pass when running them after creating the project.

### To Reproduce

```console
npx create-next-app --example with-jest test
npm run test:ci
```

**Comment by samcx** [comment]
<picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> → https://github.com/vercel/next.js/pull/60332
