### ISSUE TITLE
A task panicked: not yet implemented: EcmascriptModuleFacadeModule::content is not implemented

### ISSUE THREAD

**Issue by mrodrigues95** [vercel/next.js#60363]
### Link to the code that reproduces this issue

https://github.com/mrodrigues95/chatse

### To Reproduce

Start the web application server, i.e. `nx serve web` with `turbo: true` set under `apps/web/project.json`

### Current vs. Expected behavior

Running the Next.js dev server with `turbo` enabled seems to crash with the following error.
```
nx run web:serve:development

   ▲ Next.js 14.0.4 (turbo)
   - Local:        http://localhost:3000
 ✓ Ready in 1781ms
 ○ Compiling / ...
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/turbo-df7a549334890fa5/f99cd25/crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs:123:9:
not yet implemented: EcmascriptModuleFacadeModule::content is not implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/turbo-df7a549334890fa5/f99cd25/crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs:123:9:
not yet implemented: EcmascriptModuleFacadeModule::content is not implemented
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/turbo-df7a549334890fa5/f99cd25/crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs:123:9:
not yet implemented: EcmascriptModuleFacadeModule::content is not implemented
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/turbo-df7a549334890fa5/f99cd25/crates/turbopack-ecmascript/src/side_effect_optimization/locals/module.rs:59:9:
not yet implemented: EcmascriptModuleLocalsModule::content is not implemented
 ✓ Compiled / in 15.5s
 ⨯ Error: A task panicked: not yet implemented: EcmascriptModuleFacadeModule::content is not implemented
Debug info:
- Execution of <AppEndpoint as Endpoint>::write_to_disk failed
- Execution of Project::emit_all_output_assets failed
- Execution of VersionedContentMap::insert_output_assets failed
- Execution of all_assets_from_entries failed
- Execution of AppEndpointOutput::output_assets failed
- Execution of AppEndpoint::output failed
- Execution of ClientReferenceGraph::types failed
- Execution of ClientReferenceGraph::new failed
- Execution of primary_referenced_modules failed
- Execution of <ModuleCssAsset as Module>::references failed
- Execution of ModuleCssAsset::module_references failed
- Execution of ModuleCssAsset::classes failed
- Execution of process_css_with_placeholder failed
- Execution of parse_css failed
- Execution of <PostCssTransformedAsset as Asset>::content failed
- Execution of PostCssTransformedAsset::process failed
- Execution of evaluate failed
- Execution of Completions::completed failed
- Execution of Completions::completed failed
- Execution of content_changed failed
- Execution of AssetContent::file_content failed
- A task panicked: not yet implemented: EcmascriptModuleFacadeModule::content is not implemented
    at withErrorCause (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/swc/index.js:414:19)
    at async EndpointImpl.writeToDisk (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/swc/index.js:595:20)
    at async Object.ensurePage (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:1126:83)
    at async DevBundlerService.ensurePage (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:536:9)
    at async Object.ensure (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:165:17)
    at async DevRouteMatcherManager.matchAll (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:94:13)
    at async DevRouteMatcherManager.match (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:222:31)
    at async DevServer.handleRequestImpl (/workspace/chatse/node_modules/.pnpm/next@14.0.4_@babel+core@7.23.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:805:17) {
  [cause]: [Error: A task panicked: not yet implemented: EcmascriptModuleFacadeModule::content is not implemented
  
  Debug info:
  - Execution of <AppEndpoint as Endpoint>::write_to_disk failed
  - Execution of Project::emit_all_output_assets failed
  - Execution of VersionedContentMap::insert_output_assets failed
  - Execution of all_assets_from_entries failed
  - Execution of AppEndpointOutput::output_assets failed
  - Execution of AppEndpoint::output failed
  - Execution of ClientReferenceGraph::types failed
  - Execution of ClientReferenceGraph::new failed
  - Execution of primary_referenced_modules failed
  - Execution of <ModuleCssAsset as Module>::references failed
  - Execution of ModuleCssAsset::module_references failed
  - Execution of ModuleCssAsset::classes failed
  - Execution of process_css_with_placeholder failed
  - Execution of parse_css failed
  - Execution of <PostCssTransformedAsset as Asset>::content failed
  - Execution of PostCssTransformedAsset::process failed
  - Execution of evaluate failed
  - Execution of Completions::completed failed
  - Execution of Completions::completed failed
  - Execution of content_changed failed
  - Execution of AssetContent::file_content failed
  - A task panicked: not yet implemented: EcmascriptModuleFacadeModule::content is not implemented] {
    code: 'GenericFailure'
  }
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 807ms
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #202312122204 SMP PREEMPT_DYNAMIC Tue Dec 12 22:43:56 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.12.1
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I'm currently developing within Gitpod but I am also able to reproduce this issue on my local Windows machine so I don't think it's environment related. I've tried both `next@14.0.4` and the latest `canary` branch, both yielding the same result.

Error seems to stem from https://github.com/vercel/turbo/blob/b33e157810fccf7664b18c1baec024643f5fe379/crates/turbopack-ecmascript/src/side_effect_optimization/facade/module.rs#L123

<sub>[PACK-2242](https://linear.app/vercel/issue/PACK-2242/a-task-panicked-not-yet-implemented)</sub>

**Comment by fatihdogmus** [comment]
Facing the same problem with nx and turbot with everything being latest stable version.

**Comment by wbinnssmith** [comment]
Thanks for reporting this, @mrodrigues95. Can you provide a more minimal example?

**Comment by mrodrigues95** [comment]
@wbinnssmith I think I boiled this down to the `tailwind.config.js` using CJS modules not playing nice within a Nx workspace alongside Turbo. I created a more minimal example at https://github.com/mrodrigues95/nx-nextjs-turbo-bug/tree/master which can be ran via `npx nx serve my-app`.

This was initialized following https://nx.dev/nx-api/next#setting-up-nextjs and https://nx.dev/recipes/react/using-tailwind-css-in-react#automated-setup, i.e:
- `npx create-nx-workspace@latest --preset=next`
- `nx g @nx/react:setup-tailwind --project=<app_name>`
- `npm i next@latest` (since the NX preset installs `next@13.4.4`)
- `npx nx serve <app_name> -- --turbo`


If I change `tailwind.config.js` -> `tailwind.config.ts` and use `import` statements, it seems to work just fine. You may have to remove the `config: join(__dirname, 'tailwind.config.js')` line from `postcss.config.js` when initializing a new workspace since that seems to be causing issues as well.

**Comment by ForsakenHarmony** [comment]
Tried to reproduce this but keep running into weird issues with `nx`
Not sure if it wrapping next is the best thing
