### ISSUE TITLE
Next checks for dynamic imports if they work only in server/client

### ISSUE THREAD

**Issue by LeOndaz** [vercel/next.js#60398]
### Link to the code that reproduces this issue

https://github.com/LeOndaz/nextjs-bug

### To Reproduce

Write a function like this

```
function myFunc() {
    if (typeof window !== "undefined") {
         return import("browser_client");
    }
    return import ("server_client");
}
```

The server_client uses `next/headers` internally, calling `cookies`, but it's not INVOKED till the import myFunc invokes it, which DOES NOT do this on the client, so it's safe to use this without having the same validation rules as top file imports

### Current vs. Expected behavior

You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.13.1
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

Tested on 14.0.3, 14.0.4 and 14.0.5-canary.44

**Comment by LeOndaz** [comment]
Here's a quick fix for folks in the same situtation

instead of 
```
class MyApi {
  async getInstance () {
    if (typeof window === 'undefined') {
      return import("@/serverUtils").then(r => r.myServerFuncForSupabaseInstance());
    }
    
    return import("@/clientUtils").then(r => r.myClientFuncForSupabaseInstance())
  }
}
```

Do:

```
class MyApi {
  async getInstance () {
    let importPath = "@/serverUtils";

    if (typeof window !== 'undefined') {
      importPath = "@/clientUtils"
    }
    
    return import(importPath)
  }
}
```

And rename both exports from `@/clientUtils` and `@/serverUtils` to be the same OR use make both default export the function needed and just use `import(importPath)` as above

**Comment by TmLev** [comment]
Doesn't work for me :(

<details>
<summary>Code</summary>

```ts
async function getCookie(name: string): Promise<string | null | undefined> {
  let importPath = "@/api/rspc/cookies-server";
  if (typeof window !== "undefined") {
    importPath = "@/api/rspc/cookies-client";
  }

  const { default: get } = await import(importPath);
  return get(name);
}
```

</details>

<details>

<summary>Logs</summary>

```logs
> next dev

 ⚠ Port 3000 is in use, trying 3001 instead.
 ⚠ Port 3001 is in use, trying 3002 instead.
   ▲ Next.js 14.0.5-canary.53
   - Local:        http://localhost:3002

 ✓ Ready in 1374ms
 ✓ Compiled /src/middleware in 77ms
 ✓ Compiled (65 modules)
 ○ Compiling / ...
 ⚠ ./src/api/rspc/client.ts
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./src/api/rspc/client.ts
./src/app/client-providers.tsx

./src/api/rspc/client.ts
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./src/api/rspc/client.ts
./src/app/client-providers.tsx

./src/api/rspc/client.ts
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./src/api/rspc/client.ts
./src/app/page.tsx
Error: Cannot find module '@/api/rspc/cookies-server'
    at /.../.next/server/app/page.js:25:11
    at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
    at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module '@/api/rspc/cookies-server'
    at /.../.next/server/app/page.js:25:11
    at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
    at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
  code: 'MODULE_NOT_FOUND'
}
 ⨯ unhandledRejection: Error: Cannot find module '@/api/rspc/cookies-server'
    at /.../.next/server/app/page.js:25:11
    at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
    at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
  code: 'MODULE_NOT_FOUND'
}
 ⨯ unhandledRejection: Error: Cannot find module '@/api/rspc/cookies-server'
    at /.../.next/server/app/page.js:25:11
    at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
    at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
  code: 'MODULE_NOT_FOUND'
}
 ⚠ ./src/api/rspc/client.ts
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./src/api/rspc/client.ts
./src/app/client-providers.tsx

./src/api/rspc/client.ts
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./src/api/rspc/client.ts
./src/app/client-providers.tsx

./src/api/rspc/client.ts
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./src/api/rspc/client.ts
./src/app/page.tsx

```

</details>

**Comment by LeOndaz** [comment]
> > Here's a quick fix for folks in the same situtation
> 
> 
> 
> Doesn't work for me :(
> 
> 
> 
> <details>
> 
> <summary>Code</summary>
> 
> 
> 
> ```ts
> 
> // Main file
> 
> async function getCookie(name: string): Promise<string | null | undefined> {
> 
>   let importPath = "@/api/rspc/cookies-server";
> 
>   if (typeof window !== "undefined") {
> 
>     importPath = "@/api/rspc/cookies-client";
> 
>   }
> 
> 
> 
>   const { default: get } = await import(importPath);
> 
>   return get(name);
> 
> }
> 
> 
> 
> // cookies-client.ts
> 
> import { getCookies as getCookiesClient } from "cookies-next";
> 
> 
> 
> export default function getCookie(name: string) {
> 
>   return getCookiesClient()[name];
> 
> }
> 
> 
> 
> // cookies-server.ts
> 
> import { cookies as getCookiesServer } from "next/headers";
> 
> 
> 
> export default function getCookie(name: string) {
> 
>   return getCookiesServer().get(name)?.value;
> 
> }
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> <details>
> 
> 
> 
> <summary>Logs</summary>
> 
> 
> 
> ```logs
> 
> > next dev
> 
> 
> 
>  ⚠ Port 3000 is in use, trying 3001 instead.
> 
>  ⚠ Port 3001 is in use, trying 3002 instead.
> 
>    ▲ Next.js 14.0.5-canary.53
> 
>    - Local:        http://localhost:3002
> 
> 
> 
>  ✓ Ready in 1374ms
> 
>  ✓ Compiled /src/middleware in 77ms
> 
>  ✓ Compiled (65 modules)
> 
>  ○ Compiling / ...
> 
>  ⚠ ./src/api/rspc/client.ts
> 
> Critical dependency: the request of a dependency is an expression
> 
> 
> 
> Import trace for requested module:
> 
> ./src/api/rspc/client.ts
> 
> ./src/app/client-providers.tsx
> 
> 
> 
> ./src/api/rspc/client.ts
> 
> Critical dependency: the request of a dependency is an expression
> 
> 
> 
> Import trace for requested module:
> 
> ./src/api/rspc/client.ts
> 
> ./src/app/client-providers.tsx
> 
> 
> 
> ./src/api/rspc/client.ts
> 
> Critical dependency: the request of a dependency is an expression
> 
> 
> 
> Import trace for requested module:
> 
> ./src/api/rspc/client.ts
> 
> ./src/app/page.tsx
> 
> Error: Cannot find module '@/api/rspc/cookies-server'
> 
>     at /.../.next/server/app/page.js:25:11
> 
>     at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
> 
>     at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
> 
>   code: 'MODULE_NOT_FOUND'
> 
> }
> 
> Error: Cannot find module '@/api/rspc/cookies-server'
> 
>     at /.../.next/server/app/page.js:25:11
> 
>     at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
> 
>     at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
> 
>   code: 'MODULE_NOT_FOUND'
> 
> }
> 
>  ⨯ unhandledRejection: Error: Cannot find module '@/api/rspc/cookies-server'
> 
>     at /.../.next/server/app/page.js:25:11
> 
>     at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
> 
>     at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
> 
>   code: 'MODULE_NOT_FOUND'
> 
> }
> 
>  ⨯ unhandledRejection: Error: Cannot find module '@/api/rspc/cookies-server'
> 
>     at /.../.next/server/app/page.js:25:11
> 
>     at async getCookie (webpack-internal:///(rsc)/./src/api/rspc/client.ts:14:30)
> 
>     at async exec (webpack-internal:///(rsc)/./src/api/rspc/client.ts:25:41) {
> 
>   code: 'MODULE_NOT_FOUND'
> 
> }
> 
>  ⚠ ./src/api/rspc/client.ts
> 
> Critical dependency: the request of a dependency is an expression
> 
> 
> 
> Import trace for requested module:
> 
> ./src/api/rspc/client.ts
> 
> ./src/app/client-providers.tsx
> 
> 
> 
> ./src/api/rspc/client.ts
> 
> Critical dependency: the request of a dependency is an expression
> 
> 
> 
> Import trace for requested module:
> 
> ./src/api/rspc/client.ts
> 
> ./src/app/client-providers.tsx
> 
> 
> 
> ./src/api/rspc/client.ts
> 
> Critical dependency: the request of a dependency is an expression
> 
> 
> 
> Import trace for requested module:
> 
> ./src/api/rspc/client.ts
> 
> ./src/app/page.tsx
> 
> 
> 
> ```
> 
> 
> 
> </details>

Yeah sorry I forgot to update this, it doesn't work

It did work one time, I assume something was cached, but it gives the same error.

I ended up parametrizing my client
```
Class ApiClient {
   client?: clienType;
  constructor(client) {
      this.client = client
    }
}

and construct the server client on the server and the client's on the client
```

**Comment by RaphaelMechaliPro** [comment]
I'm facing the same issue.

We're implementing a logging system that uses Winston on the server side and defaults to the console on the client side.

While we could avoid logging on the client side, our shared libraries for data fetching need to log when used on the server side. These libraries are quite verbose, so duplicating the code is not feasible.

I was hoping to use dynamic imports to switch the logger instance based on the runtime environment. However, both imports are being executed, leading to the error 'Module not found: Can't resolve 'fs'' when the shared library is used in a client component.

Could you figure out a workaround?

Best regards,

**Comment by marcoshernanz** [comment]
Thanks for the reproduction. I can still reproduce this on `next@16.4.0-canary.7`, but the rejection is expected. A `"use client"` boundary makes literal dynamic imports part of the client module graph. `next/headers` is server-only, so a `typeof window` guard does not make that dependency valid. This matches #49757. Please keep the server and client implementations in separate module graphs or expose the server path through a Server Function. The current Pages Router wording is misleading and should be handled as a separate diagnostic issue. Closing as working as intended.
