### ISSUE TITLE
Build Error: Unexpected token: punc ({)

### ISSUE THREAD

**Issue by bendiy** [vercel/next.js#60837]
### Link to the code that reproduces this issue

https://github.com/kdy1/repro-next-59046/pull/1

### To Reproduce

1. create project with npx create-next-app@latest
2. Add a class with static property
3. set swcMinify is false in next.config.js
4. Run npm run build

### Current vs. Expected behavior

Build throw error when `swcMinify: false,`:
```
λ npm run build

> build
> next build

 ⚠ Disabling SWC Minifer will not be an option in the next major version. Please report any issues you may be experiencing to https://github.com/vercel/next.js/issues
   ▲ Next.js 14.0.5-canary.66

 ✓ Linting and checking validity of types
   Creating an optimized production build ...
Failed to compile.

../pages/index.js from Terser
Unexpected token: punc ({) [../pages/index.js:94,10]
    at js_error (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:32780)
    at croak (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:43882)
    at token_error (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:43989)
    at unexpected (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:44055)
    at as_property_name (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:68487)
    at concise_method_or_getset (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:64746)
    at class_ (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:64098)
    at statement (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:46908)
    at _embed_tokens_wrapper (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:45013)
    at block_ (C:\Users\MyUser\repro-next-59046\node_modules\next\dist\compiled\terser\bundle.min.js:1:56881)


> Build failed because of webpack errors
```

Expect it not to error.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
node: 18.17.1
next: 14.0.5-canary.66
os: Windows 10
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

@kdy1  This issue still exists: https://github.com/vercel/next.js/issues/59046

<sub>[PACK-2285](https://linear.app/vercel/issue/PACK-2285/build-error-unexpected-token-punc)</sub>

**Comment by nirvanka** [comment]
I'm getting the same issue on Next 13.5.6, any chance the fix could be ported over to 13.x?
