### ISSUE TITLE
"error createContext only works in Client Components" still exists

### ISSUE THREAD

**Issue by sheetalsindhu** [vercel/next.js#60877]
### What is the improvement or update you wish to see?

I am getting this error in my project, after updating each and every file with "use client" still exists 
- error createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/shared/lib/router-context.js:13:38)
    at (rsc)/./node_modules/next/dist/shared/lib/router-context.js (/Users/sheetalsindhu/Desktop/code/raftel/.next/server/app/page.js:2356:1)
    at __webpack_require__ (/Users/sheetalsindhu/Desktop/code/raftel/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/client/router.js:36:24)
    at (rsc)/./node_modules/next/dist/client/router.js (/Users/sheetalsindhu/Desktop/code/raftel/.next/server/app/page.js:2004:1)
    at __webpack_require__ (/Users/sheetalsindhu/Desktop/code/raftel/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next/router.js:2:18)
    at (rsc)/./node_modules/next/router.js (/Users/sheetalsindhu/Desktop/code/raftel/.next/server/app/page.js:2741:1)
    at __webpack_require__ (/Users/sheetalsindhu/Desktop/code/raftel/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next-redux-wrapper/lib/index.js:177:16) {
  name: 'TypeError',
  digest: undefined
}

### Is there any context that might help us understand?

 "next": "13.4.13",
 "react": "^18.2.0",
 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/context-in-server-component

**Comment by delbaoliveira** [comment]
Hey @sheetalsindhu, could you please delete your `.next` directory? Wondering if it's a bad cache.

**Comment by bonface221** [comment]
@sheetalsindhu  add "use client" on the component with the create context only.

Then wrap the component in your layout or where you intend to use it

e.g this is a client auth provider 
![image](https://github.com/vercel/next.js/assets/98006412/bd8c5892-97c0-4e11-8424-886a1ecff79d)


wrapped over other components

![image](https://github.com/vercel/next.js/assets/98006412/425788ea-3028-4ce1-bfe3-0a18fbfa6559)

**Comment by asd58584388** [comment]
I got the same error, after moving ```mdx-components.tsx``` to the root of my project, I solved it.

**Comment by cleytonoliveira** [comment]
I got the same error trying to migrate from Pages to App. I put the 'use client' at the beginning of my Context, but it doesn't work.

**Comment by wenzhen-gong** [comment]
> I got the same error trying to migrate from Pages to App. I put the 'use client' at the beginning of my Context, but it doesn't work.

Same here. @emotion/styled works perfectly in Pages but not the case in App

**Comment by Aruseli** [comment]
@wenzhen-gong I had this error when I started adding i18n. There were no problems when adding chakra-ui

**Comment by arburhan** [comment]
i've same problem

**Comment by melodyxpot** [comment]
I faced this issue when I tried to update my next.js version.

![Image](https://github.com/user-attachments/assets/51175dd0-5f3b-47c9-b5b0-be0e8f54c750)

Is there a way to fix it?
I think this is happening in several modules.

**Comment by marcoshernanz** [comment]
Thanks for the report. I reproduced the original stack on Next.js 13.4.13 and traced it to `next-redux-wrapper@8.1.0` importing `next/router` from an App Router server graph. The [package maintainer confirms](https://github.com/kirill-konshin/next-redux-wrapper/issues/494) that it does not support App Router, and the [Redux guide](https://redux.js.org/usage/nextjs) recommends a client `StoreProvider` instead.

A correct client boundary removes the `createContext` error, but using the wrapper still fails because it expects the Pages Router. The wrapper works in a Pages Router control, the recommended provider works in App Router, and the original error does not reproduce on current stable or canary. Closing this as an unsupported upstream integration rather than a Next.js bug.
