### ISSUE TITLE
 Regression: Setting distDir with {output: 'export'} causes error in 14.1.0.

### ISSUE THREAD

**Issue by DarkGuy10** [vercel/next.js#61043]
### Link to the code that reproduces this issue

https://github.com/DarkGuy10/next-bug-repro

### To Reproduce

1. Start the application in development mode (next dev)
2. Visit local url

### Current vs. Expected behavior

Prior to `14.1.0`, the development server worked properly.

After upgrading, here's the errors i get:
```
# Console
    ▲ Next.js 14.1.1-canary.7
   - Local:        http://localhost:3000

 ✓ Ready in 1999ms
 ○ Compiling / ...
 ✓ Compiled / in 1554ms (409 modules)
 ✓ Compiled /not-found in 309ms (414 modules)
 ⨯ Error: Cannot find module 'X:\GitHub\next-bug-repro\build\server\middleware-manifest.json'
Require stack:
- X:\GitHub\next-bug-repro\node_modules\next\dist\server\next-server.js
- X:\GitHub\next-bug-repro\node_modules\next\dist\server\dev\next-dev-server.js
- X:\GitHub\next-bug-repro\node_modules\next\dist\server\next.js
- X:\GitHub\next-bug-repro\node_modules\next\dist\server\lib\start-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at X:\GitHub\next-bug-repro\node_modules\next\dist\server\require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (X:\GitHub\next-bug-repro\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at DevServer.getMiddlewareManifest (X:\GitHub\next-bug-repro\node_modules\next\dist\server\next-server.js:910:26)
    at DevServer.getEdgeFunctionsPages (X:\GitHub\next-bug-repro\node_modules\next\dist\server\next-server.js:926:31)
    at DevServer.renderErrorToResponseImpl (X:\GitHub\next-bug-repro\node_modules\next\dist\server\next-server.js:885:22)
    at async DevServer.pipeImpl (X:\GitHub\next-bug-repro\node_modules\next\dist\server\base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (X:\GitHub\next-bug-repro\node_modules\next\dist\server\next-server.js:230:21)
    at async DevServer.handleRequestImpl (X:\GitHub\next-bug-repro\node_modules\next\dist\server\base-server.js:807:17)
    at async X:\GitHub\next-bug-repro\node_modules\next\dist\server\dev\next-dev-server.js:331:20
    at async Span.traceAsyncFn (X:\GitHub\next-bug-repro\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (X:\GitHub\next-bug-repro\node_modules\next\dist\server\dev\next-dev-server.js:328:24)
    at async invokeRender (X:\GitHub\next-bug-repro\node_modules\next\dist\server\lib\router-server.js:163:21)
    at async handleRequest (X:\GitHub\next-bug-repro\node_modules\next\dist\server\lib\router-server.js:342:24)
    at async requestHandlerImpl (X:\GitHub\next-bug-repro\node_modules\next\dist\server\lib\router-server.js:366:13)
    at async Server.requestListener (X:\GitHub\next-bug-repro\node_modules\next\dist\server\lib\start-server.js:140:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'X:\\GitHub\\next-bug-repro\\node_modules\\next\\dist\\server\\next-server.js',
    'X:\\GitHub\\next-bug-repro\\node_modules\\next\\dist\\server\\dev\\next-dev-server.js',
    'X:\\GitHub\\next-bug-repro\\node_modules\\next\\dist\\server\\next.js',
    'X:\\GitHub\\next-bug-repro\\node_modules\\next\\dist\\server\\lib\\start-server.js'
  ]
}
...
```
_Screenshot from my browser:_
![299085326-cf68af57-5c39-416f-ab69-8bca33e64333](https://github.com/vercel/next.js/assets/62807269/47703060-2497-4e77-a5b3-d5d76e962927)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.7 // Latest available version is detected (14.1.1-canary.7).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Reverting to `14.0.4` fixes the problem.
Also, the error happens only when setting both `{distDir: 'build'}` and `{output: 'export'}` together. Individually, they work just fine.
I've checked the latest canary version (`14.1.1-canary.7`), and the issue still persists.

**Comment by samcx** [comment]
I re-opened the original one → https://github.com/vercel/next.js/issues/61041.
