### ISSUE TITLE
Running next build breaks next dev server

### ISSUE THREAD

**Issue by rustyx** [vercel/next.js#61228]
### Link to the code that reproduces this issue

There is no code -- read on...

### To Reproduce

1. `npx create-next-app@latest mytest --typescript --tailwind --eslint`
   ```none
   Would you like to use `src/` directory? … Yes
   Would you like to use App Router? (recommended) … Yes
   Would you like to customize the default import alias (@/*)? … No
   ```
3. `cd mytest`
4. `next dev`
5. Check in a browser that `http://localhost:3000` is working fine
6. In another shell, run `next build`
7. Go back to the browser, refresh the page

### Current vs. Expected behavior

The page is broken:

```none
Server Error
Error: Cannot find module './638.js'
```

I expected the dev server to either (1) continue working correctly or (2) exit with a message explaining why it can't work.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024
Binaries:
  Node: 20.5.1
  npm: 10.2.5
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Restarting `next dev` "fixes" the issue.

**Comment by gruckion** [comment]
Can we get a better solution for this? Having to stop and restart the dev server every time we do a build is a bit of a pain. I ensure the next build works as a pre check before git push. So this is a bit of a pain in the arse.

**Comment by thSoft** [comment]
With Turbopack, the dev server still fails after running build after changing my configuration as described in https://github.com/vercel/next.js/issues/61228#issuecomment-2002035619.

Error message:

```
 ⨯ Error: ENOENT: no such file or directory, open '/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/.next/server/app/page/app-build-manifest.json'
    at async open (node:internal/fs/promises:636:25)
    at async readFile (node:internal/fs/promises:1246:14)
    at async readPartialManifest (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/turbopack/manifest-loader.js:28:23)
    at async TurbopackManifestLoader.loadAppBuildManifest (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/turbopack/manifest-loader.js:90:91)
    at async handleRouteType (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/turbopack-utils.js:376:17)
    at async Object.ensurePage (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/hot-reloader-turbopack.js:644:17)
    at async DevBundlerService.ensurePage (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:551:9)
    at async Object.ensure (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:169:17)
    at async DevRouteMatcherManager.matchAll (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:96:13)
    at async DevRouteMatcherManager.match (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:228:31)
    at async DevServer.handleRequestImpl (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/thsoft/Honlapok/thsoft.hu/4.0/nextjs-material-ui/.next/server/app/page/app-build-manifest.json'
}
```

next.config.mjs:
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  distDir: process.env.NODE_ENV === "development" ? ".next" : "www",
};

export default nextConfig;
```

package.json:
```
{
  "name": "material-ui-nextjs-ts",
  "version": "5.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbo",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "post-update": "echo \"codesandbox preview only, need an update\" && pnpm update --latest"
  },
  "dependencies": {
    "@emotion/cache": "latest",
    "@emotion/react": "latest",
    "@emotion/styled": "latest",
    "@mui/icons-material": "^5.15.19",
    "@mui/material": "latest",
    "@mui/material-nextjs": "latest",
    "@notionhq/client": "^2.2.15",
    "dangerously-set-html-content": "^1.1.0",
    "next": "^14.2.4",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "eslint": "latest",
    "eslint-config-next": "latest",
    "typescript": "latest"
  }
}
```

**Comment by kristian-nst** [comment]
Thanks @gruckion , worked here :)

**Comment by paradite** [comment]
On Next.js `14.2.18`, using the following config did not work:

```ts
const nextConfig = {
  distDir: process.env.NODE_ENV === "development" ? ".next/dev" : ".next/build",
}
```

Running `next build` would still overwrite the entire `.next` folder with build stuff and break the dev server.

I found a similar walkaround that works by moving the dev server to another folder, while leaving the build folder as it is:

```ts
const nextConfig = {
  distDir: process.env.NODE_ENV === 'development' ? '.next-dev' : '.next',
}
```

Remember to add `.next-dev` to your `gitignore`.

Also note that with this setup, the final build `export` output would still go to `out` folder, instead of `.next`.

**Comment by gianpaj** [comment]
Good news in Next.js 16
https://nextjs.org/blog/next-16

> Dev and build output directories

> `next dev` and `next build` now use separate output directories, enabling concurrent execution

**Comment by marcoshernanz** [comment]
Thanks for the report. This was fixed in Next.js 16 by #83961 and #84561. `next dev` now writes to `.next/dev`, while `next build` writes to `.next`, so the commands can run concurrently without corrupting the dev server. I verified this on Next.js 16.3.4 and the current canary with both Turbopack and webpack. Users on earlier versions should upgrade to Next.js 16 or newer. Closing as resolved.
