### ISSUE TITLE
server action isn't working when invoked from client side

### ISSUE THREAD

**Issue by krishnaacharyaa** [vercel/next.js#61482]
### Link to the code that reproduces this issue

https://github.com/krishnaacharyaa/nextjs-explore

### To Reproduce

1. Start the application 
   a. npm i 
   b. npm run dev

Run the app on localhost:3000
Click on Summary and then click on `mutate the initial data` button
![image](https://github.com/vercel/next.js/assets/116620586/0a80b542-15b6-443c-b08f-0270f7cf9d29)

I get error `Application error: a client-side exception has occurred (see the browser console for more information).`

The browser console error says: 
```
Uncaught Error: Only plain objects, and a few built-ins, can be passed to Server Actions. Classes or null prototypes are not supported.
    at Array.resolveToJSON (react-server-dom-webpack-client.browser.development.js:732:31)
    at JSON.stringify (<anonymous>)
    at processReply (react-server-dom-webpack-client.browser.development.js:803:29)
    at eval (react-server-dom-webpack-client.browser.development.js:1665:17)
    at new Promise (<anonymous>)
    at encodeReply (react-server-dom-webpack-client.browser.development.js:1664:20)
    at fetchServerAction (server-action-reducer.js:30:24)
    at serverActionReducer (server-action-reducer.js:101:36)
    at clientReducer (router-reducer.js:49:69)
    at Object.action (action-queue.js:149:55)
    at runAction (action-queue.js:47:38)
    at dispatchAction (action-queue.js:112:9)
    at Object.dispatch (action-queue.js:144:40)
    at eval (use-reducer-with-devtools.js:130:21)
    at eval (app-router.js:104:13)
    at startTransition (react.development.js:2205:17)
    at eval (app-router.js:103:36)
    at eval (app-call-server.js:18:9)
    at new Promise (<anonymous>)
    at callServer (app-call-server.js:17:12)
    at proxy (react-server-dom-webpack-client.browser.development.js:823:24)
    at HTMLUnknownElement.callCallback (react-dom.development.js:17629:30)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:17667:30)
    at invokeGuardedCallback (react-dom.development.js:17729:39)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:17741:35)
    at executeDispatch (react-dom.development.js:27186:13)
    at processDispatchQueueItemsInOrder (react-dom.development.js:27206:21)
    at processDispatchQueue (react-dom.development.js:27215:17)
    at dispatchEventsForPlugins (react-dom.development.js:27223:13)
    at eval (react-dom.development.js:27378:24)
    at batchedUpdates$1 (react-dom.development.js:21180:24)
    at batchedUpdates (react-dom.development.js:24349:24)
    at dispatchEventForPluginEventSystem (react-dom.development.js:27377:13)
    at dispatchEvent (react-dom.development.js:25416:17)
    at dispatchDiscreteEvent (react-dom.development.js:25392:17)
app-index.js:35 The above error occurred in the <Router> component:

    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:181:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:114:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:161:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:536:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:129:11)
    at RSCComponent
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:145:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:84:9)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundaryHandler.
window.console.error @ app-index.js:35
Show 1 more frame
Show less
```

### Current vs. Expected behavior

I expect the `mutateUserUniverserData` server action to be called. which revalidate the initial data.

Expected behaviour is console.log("I am fetching userUninverseData"); to be logged in server as soon as mutateUserUniverserData is called, because revalidate basically means fetching the data again.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
Binaries:
  Node: 21.0.0
  npm: 10.2.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I expect the right of doing is 
```
export async function getUserUniverseData(userid: number) {
  try {
    const response = await fetch(
      `http://${action_constants.URL}:${action_constants.PORT}/api/usersuniverse/user/${userid}`,
      { next: { tags: ["userData"] } }
    );
    console.log("I am fetching userUninverseData");
    const result = response;
    return result;
  } catch (error: any) {
    console.log("Axios Get Error :(", error);
  }
}

export async function mutateUserUniverserData() {
  try {
    revalidateTag("userData");
  } catch {
    console.log(
      "Tag revalidate not  working properly. Please check your NextJS version and if you have the correct middleware installed."
    );
  }
}
```

And calling mutateuserUniverseData where i need server side or client side. But seems like i am wrong, kindly lead me to the correct path

**Comment by icyJoseph** [comment]
Hi,

In this line: https://github.com/krishnaacharyaa/nextjs-explore/blob/main/components/ThirdColumnComponent/SummaryDocumet.tsx#L23

Could you try:

```tsx
      <button onClick={() => mutateUserUniverserData()}>Mutate the initial data</button>
```

I am a bit busy, but here what's happening is that when you do `onClick={mutateUserUniverserData}`, you are doing this, `onClick={(event) => mutateUserUniverserData(event)}`, and you kind of want to ignore the event, because it is not serializable according Server Actions.

**Comment by krishnaacharyaa** [comment]
Thank you bunch @icyJoseph, 
If you have a little time to spare can you kindly give your opinion on https://github.com/vercel/next.js/issues/61494,
Sorry to bother, a little insight/inputs would be really helpful :)
