### ISSUE TITLE
not_found.tsx module not found error

### ISSUE THREAD

**Issue by TwoBrake** [vercel/next.js#61602]
### Link to the code that reproduces this issue

https://codesandbox.io/p/live/9be5ecdc-7206-4297-84b1-bfde8819969b

### To Reproduce

1. Run the application with `npm run dev`.
2. Use the pages router and TypeScript in the project.
3. Create a `not-found.tsx` file and return an element.
4. Navigate to a non-existent page.

### Current vs. Expected behavior

I am trying to make a custom 404 page in my Next.js project, but for some reason when I create a `not-found.tsx` file and navigate to a non-existent page, it errors the project. Here is the error I am receiving:

```bash
 ⨯ Error: Cannot find module 'C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\.next\server\app\not-found_client-reference-manifest.js'
Require stack:
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\load-components.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\build\utils.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\dev\hot-middleware.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\dev\hot-reloader-webpack.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\lib\router-server.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\lib\start-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at loadClientReferenceManifest (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\load-components.js:43:72)
    at loadComponentsImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\load-components.js:65:29)
    at async DevServer.findPageComponentsImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\next-server.js:671:36)
    at async DevServer.findPageComponents (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\dev\next-dev-server.js:562:20)
    at async DevServer.renderErrorToResponseImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\base-server.js:2009:30)
    at async pipe.req.req (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\base-server.js:1975:30)
    at async DevServer.pipeImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\base-server.js:909:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\load-components.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\build\\utils.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\dev\\hot-middleware.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\dev\\hot-reloader-webpack.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\lib\\router-utils\\setup-dev-bundler.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\lib\\router-server.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\lib\\start-server.js'
  ]
}
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ✓ Compiled /_error in 347ms (589 modules)
 ○ Compiling /favicon.ico ...
 ✓ Compiled /favicon.ico in 1015ms (147 modules)
 ⨯ Error: Cannot find module 'C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\.next\server\app\not-found_client-reference-manifest.js'
Require stack:
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\load-components.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\build\utils.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\dev\hot-middleware.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\dev\hot-reloader-webpack.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\lib\router-server.js
- C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\lib\start-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at loadClientReferenceManifest (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\load-components.js:43:72)
    at loadComponentsImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\load-components.js:65:29)
    at async DevServer.findPageComponentsImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\next-server.js:671:36)
    at async DevServer.findPageComponents (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\dev\next-dev-server.js:562:20)
    at async DevServer.renderErrorToResponseImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\base-server.js:2009:30)
    at async pipe.req.req (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\base-server.js:1975:30)
    at async DevServer.pipeImpl (C:\Users\Lucas\Desktop\React Projects\my-new-portfolio\node_modules\next\dist\server\base-server.js:909:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\load-components.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\build\\utils.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\dev\\hot-middleware.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\dev\\hot-reloader-webpack.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\lib\\router-utils\\setup-dev-bundler.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\lib\\router-server.js',
    'C:\\Users\\Lucas\\Desktop\\React Projects\\my-new-portfolio\\node_modules\\next\\dist\\server\\lib\\start-server.js'
  ]
}
```

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
Binaries:
  Node: 20.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A


warn  - Latest canary version not detected, detected: "14.0.4", newest: "14.1.1-canary.29".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Module resolution (CJS / ESM, module resolving), Routing (next/router, next/navigation, next/link), TypeScript (plugin, built-in types)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by GiorgiTsukhishvili** [comment]
I had similar problem with 13.5.6 version, when I redirected to url that had no corresponding page it was just giving error despite having not-found.tsx, it only worked when calling notFound function from 'next/navigation'. my workaround was to create [...404] folder and inside it to add page.tsx:

![image](https://github.com/vercel/next.js/assets/104715456/7c1d2fee-aa37-4baa-ac0f-db773e2a23e6)

this would catch any route that did not match, working with static and dynamic routes as well. Inside this page.tsx I just called notFound() which renders not-found.tsx:

`import { notFound } from 'next/navigation';

const page = () => {
  return notFound();
};

export default page;
`

**Comment by OleTheDev** [comment]
This worked for, created a [..404] folder and then index.tsx inside.
![Skjermbilde 2024-02-06 kl  16 14 47](https://github.com/vercel/next.js/assets/15962240/36774934-473b-4dff-b7c1-d9d58ea3384e)

**Comment by hongweitang** [comment]
In general the `not-found.tsx` shouldn't be working in the Pages Router because the new error page got introduced for the App Router (at least thats I what I assume from reading through the docs again).

Are you using app and pages router in a mixed setup? Because I had the issue that a custom 404.tsx page in the pages folder didn't work due to the presence of an app folder and so I tried to add a not-found.tsx in the app folder which made the error page work but it wasn't compatible with the rest of the pages router. There was an issue about this too: #58945 

The above idea of using a […404] dynamic catch all route worked in my case too.

**Comment by TwoBrake** [comment]
> In general the `not-found.tsx` shouldn't be working in the Pages Router because the new error page got introduced for the App Router (at least thats I what I assume from reading through the docs again).

That was the issue. Thank you for the solution, I have just moved the `not-found.tsx` file to the app router and it seems to be functional.
