### ISSUE TITLE
Cannot use CommonJS packages in PNPM workspace

### ISSUE THREAD

**Issue by disintegrator** [vercel/next.js#62199]
### Link to the code that reproduces this issue

https://github.com/disintegrator/nextjs-workspace-js

### To Reproduce

1. Clone this repository
2. Run `pnpm install`
3. On the main branch, run `pnpm dev` and go to http://localhost:3000 to see the app working.
4. Stop the development server.
5. Run `git checkout broken`
6. Run `pnpm dev` and go to http://localhost:3000 and the error thrown:
   ```
   ../../packages/monorepo-sdk/index.js
   Module parse failed: Cannot use 'import.meta' outside a module (60:16)
   |                 // still a Refresh Boundary later.
   |                 // @ts-ignore importMeta is replaced in the loader
   >                 import.meta.webpackHot.accept();
   |                 // This field is set when the previous version of this module was a
   |                 // Refresh Boundary, letting us know we need to check for invalidation or
   ```

### Current vs. Expected behavior

On the `main` branch of this repository, the Next.js app uses `@disintegrator/httpbin-client` to generate UUIDs using https://httpbin.org/uuid and everything works as expected.

On the `broken` branch of this repository, the Next.js app uses the workspace package `monorepo-sdk` to generate UUIDs using https://httpbin.org/uuid but it will not render the page and instead throw the error above.

**I expect the Next.js app to treat the workspace package the exact same way as the NPM package and load the page successfully.**

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: arm64
  Version: #104-Ubuntu SMP Tue Jan 9 15:26:57 UTC 2024
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.15.3
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This bug appears to have been introduced in `next@14.0.2-canary.1`

**Comment by disintegrator** [comment]
If you encounter an "fetch failed" error when loading the app then it might be that httpbin.org experienced an intermittent failure. This can happen on the rare occasion. Refresh the page to try again.

**Comment by pwalker** [comment]
I'm running into the same issue. I wonder if this is similar to what's being reported over in https://github.com/vercel/next.js/issues/35110?

**Comment by sergous** [comment]
Same issue with latest 14.2.3
Can't start when updated to 14.2.* version. Latest 14.1.4 work fine

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 21.7.3
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.0.6
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

```$yarn dev```

```○ Compiling /profiles ...
 ⨯ ./node_modules/@mui/icons-material/node_modules/@babel/runtime/helpers/interopRequireDefault.js
Module parse failed: Cannot use 'import.meta' outside a module (40:16)
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or

Import trace for requested module:
./node_modules/@mui/icons-material/node_modules/@babel/runtime/helpers/interopRequireDefault.js
./node_modules/@mui/icons-material/ErrorOutline.js
./src/core/helpers/knownIssuesHelper.ts
 ⨯ ./node_modules/@mui/icons-material/node_modules/@babel/runtime/helpers/interopRequireDefault.js
Module parse failed: Cannot use 'import.meta' outside a module (40:16)
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or

Import trace for requested module:
./node_modules/@mui/icons-material/node_modules/@babel/runtime/helpers/interopRequireDefault.js
./node_modules/@mui/icons-material/OpenInNew.js
./src/desktop/containers/DesktopHeader.tsx
./src/pages/desktop/index.tsx
 ⨯ Error: ENOENT: no such file or directory, open '/Users/sergous/Development/EvolutionLife/evo/evo-app/.next/fallback-build-manifest.json'
    at readFileSync (node:fs:455:20)
    at loadManifest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-manifest.js:35:54)
    at loadManifestWithRetries (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-components.js:40:51)
    at async loadDefaultErrorComponentsImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-default-error-components.js:30:24)
    at async DevServer.getFallbackErrorComponents (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:594:16)
    at async DevServer.renderErrorToResponseImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:2203:40)
    at async DevServer.renderToResponseImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:2019:30)
    at async DevServer.pipeImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/lib/router-server.js:353:24) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/sergous/Development/EvolutionLife/evo/evo-app/.next/fallback-build-manifest.json'
}
Error: ENOENT: no such file or directory, open '/Users/sergous/Development/EvolutionLife/evo/evo-app/.next/fallback-build-manifest.json'
    at readFileSync (node:fs:455:20)
    at loadManifest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-manifest.js:35:54)
    at loadManifestWithRetries (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-components.js:40:51)
    at async loadDefaultErrorComponentsImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-default-error-components.js:30:24)
    at async DevServer.getFallbackErrorComponents (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:594:16)
    at async DevServer.renderErrorToResponseImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:2203:40)
    at async DevServer.renderToResponseImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:2019:30)
    at async DevServer.pipeImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/lib/router-server.js:353:24) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/sergous/Development/EvolutionLife/evo/evo-app/.next/fallback-build-manifest.json'
}
Error: ENOENT: no such file or directory, open '/Users/sergous/Development/EvolutionLife/evo/evo-app/.next/fallback-build-manifest.json'
    at readFileSync (node:fs:455:20)
    at loadManifest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-manifest.js:35:54)
    at loadManifestWithRetries (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-components.js:40:51)
    at async loadDefaultErrorComponentsImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/load-default-error-components.js:30:24)
    at async DevServer.getFallbackErrorComponents (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:594:16)
    at async DevServer.renderErrorToResponseImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:2203:40)
    at async pipe.req.req (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:2056:30)
    at async DevServer.pipeImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/base-server.js:920:25)
    at async /Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async requestHandlerImpl (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/lib/router-server.js:389:24)
    at async Server.requestListener (/Users/sergous/Development/EvolutionLife/evo/evo-app/node_modules/next/dist/server/lib/start-server.js:141:13) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/sergous/Development/EvolutionLife/evo/evo-app/.next/fallback-build-manifest.json'
}
 GET /profiles 500 in 11244ms
 GET /profiles 500 in 235ms```

**Comment by ucheol2** [comment]
same above

**Comment by semoal** [comment]
Same issue here

**Comment by semoal** [comment]
This is still happening on 15.0.3 and 15@canary, it's a bit frustrating because we made Prisma revert some changes to avoid this issue, but this should be fixed on Next.js side.

**Comment by nickretallack** [comment]
It's also broken in `yarn` workspaces.

I created a minimal example for both yarn and pnpm here (check the branches)
https://github.com/nickretallack/nextjs-HMR-bug-report

One thing I noticed, though, is that if you omit the `"type": "commonjs"` line from the `package.json` NextJS does not break, even for large CommonJS packages.  Also, it only breaks if the file importing the CommonJS package has `"use client"`.

Perhaps NextJS is inserting the same hot module replacement code irrespective of whether the module is commonjs or not, and it's just getting lucky that it doesn't get caught if the package type is ambiguous?

The issue affects NextJS 14 and 15 on the latest patches.

This is annoying because it prevents me from using the [mini `package.json` hack to get dual package builds with vanilla `tsc`](https://github.com/azu/tsconfig-to-dual-package#how-it-works).  Since TypeScript doesn't support rewriting import specifiers or outputting two different file extensions for the same source file, the easiest way to make `tsc` produce a working ESM and CJS build is to throw a `package.json` that only contains `{"type":"commonjs"}` into the CJS build.

**Comment by nickretallack** [comment]
Btw it's a shame @semoal's comment was hidden by the "maintainer bot":

> This is still happening on 15.0.3 and 15@canary, it's a bit frustrating because we made Prisma revert some changes to avoid this issue, but this should be fixed on Next.js side.

_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by nickretallack** [comment]
This also affects prisma.

(stupid maintainer bot)

**Comment by nickretallack** [comment]
This is a regression.  It worked in nextjs `14.0.1` but broke in `14.0.2`.  It works in `14.0.2-canary.0` but breaks in `14.0.2-canary.1`.

**Comment by marcoshernanz** [comment]
Thanks for the report. I confirmed this is the same linked workspace package development failure tracked in #35110. Both cases inject import.meta.webpackHot into a CommonJS dependency and fail with the same parser error. Closing as a duplicate so the investigation and fix stay in one place.
