### ISSUE TITLE
`Error: Route did not complete loading` causes page reload

### ISSUE THREAD

**Issue by MistaPidaus** [vercel/next.js#62678]
### Link to the code that reproduces this issue

https://github.com/MistaPidaus/nextjs-routing-issue

### To Reproduce

1. Build the app locally and run production locally
2. Open the Chrome Dev tool and set the network profile to "Slowest 3G" with `250kb` for both download & upload value and `5000` for latency value 
3. On the performance tab, set the CPU performance to `6x slowdown` and make sure the network is the new profile with above setting.
4. Open `http://localhost:3000`
5. Once you see the header section with `Index page` text, spam click it multiple times (it's a button with routing mechanism)
6. Observe the browser console and you'll see `Error: Route did not complete loading` error.

### Current vs. Expected behavior

Current behaviour, as the video attached

https://github.com/vercel/next.js/assets/21690115/ac1fb39a-0317-41a0-81df-4d75ab541c06

Notice when I filled the form and got redirected afterwards due to the logic I've implemented that should run once on the initial visit. 

I'm expecting it won't reload or redirect - in other words, the user should be able to proceed with the flow with no issue.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.6.6
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

We're migrating our web app to the Next.js framework and slowly redirecting traffic to the new Next.js app. After a few days, we noticed a lot of errors (around 1.7k) in our monitoring service, indicating the `Error: Route did not complete loading` issues/errors. 

![Screenshot 2024-02-29 at 6 20 52 PM](https://github.com/vercel/next.js/assets/21690115/64416527-7ebe-4c31-a7bb-947125e8bcd3)

We suspect the user is having a slow network connection and we managed to reproduce the error. The worst thing is the issue causing the page to reload (refer the video attached) so if the user has to fill in their details, they have to restart again. We have a multiple-step form within our flow. So if the user manages to get far and fill most of the form and hit this error, they have to redo it again. We saw a lot of traffic drop-off after getting this error.

**Comment by MistaPidaus** [comment]
Bump. No one looking into this?

**Comment by timneutkens** [comment]
This is an intentional error in Pages Router only, specifically it's there to prevent "hanging" of navigations, for example when JS/CSS/etc fails to load / loads too slow for a client-side navigation. Relevant code here: https://github.com/vercel/next.js/blob/7d4907be156db4240af13bd3c6e9f8ade7910232/packages/next/src/client/route-loader.ts#L13
We could increase the timeout though, currently it's 3.8s.

**Comment by MistaPidaus** [comment]
Hmm. I feel like it won't totally solve the issue. How much will the increase be? Is there anything to look out for to improve this further?

**Comment by Kolahzary** [comment]
We have the same problem if we select "slow 4g network" on chrome's inspect element tool.

**Comment by kevintap** [comment]
We have also seen this (or a similar) issue. The behavior we see is that when a client is using a slow network connection, they never get the page rendered, just a blank page.

In the browser logs, we see this error first:
`Error: Route did not complete loading: /login`
```
    at https://host/_next/static/chunks/main-72cf801a60c05482.js:1:28410
    at i (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:26191)
    at Object.loadRoute (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:28188)
    at d.loadPage (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:19518)
    at V.fetchComponent (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:77213)
    at V.getRouteInfo (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:73597)
    at async V.change (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:67911)
```

The code in the nextjs router here then attempts to do a hard navigate to load the page. When this occurs, we see the following error in the browser logs:
`Error: Invariant: attempted to hard navigate to the same URL /login/`
```
    at q (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:63565)
    at V.handleRouteInfoError (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:71587)
    at V.getRouteInfo (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:74819)
    at async V.change (https://host/_next/static/chunks/main-72cf801a60c05482.js:1:67911)
```

As nextjs refuses to process the hard navigation here, the page never loads for the user, and they just see a blank page with no content.

At a minimum, I would suggest making `MS_MAX_IDLE_DELAY` configurable so that consumers of nextjs can configure this value as appropriate for their network conditions.

However, as @MistaPidaus mentions above, I'm not sure that simply increasing this timeout would solve this issue.

**Comment by marcoshernanz** [comment]
Thanks for the report. I reproduced the original case using the supplied 5 second latency profile. The Pages Router intentionally falls back to a full document navigation when route assets do not load within 3.8 seconds, so this reproduction is working as designed. A related same-URL asset failure has a focused report in #80124, and the Turbopack registration issue is tracked in #93758. Closing this original report to keep those cases separate. A configurable timeout or different recovery policy can be proposed as an enhancement.
