### ISSUE TITLE
'distDir' does not work with 'output: export' in dev mode

### ISSUE THREAD

**Issue by matthewjamesadam** [vercel/next.js#62752]
### Link to the code that reproduces this issue

https://github.com/matthewjamesadam/NextDemo1

### To Reproduce

1. Start the app in developer mode (`npm run dev`)

(Note: this app is nothing more then `create-next-app` with `output` set to `export` and a `distDir` set)

### Current vs. Expected behavior

I expect the app to run in developer mode.  Instead, it issues the following error:

```
matt@Matts-MacBook next-export-test % npm run dev

> next-export-test@0.1.0 dev
> next dev

   ▲ Next.js 14.1.1
   - Local:        http://localhost:3000

 ✓ Ready in 1077ms
 ✓ Compiled / in 266ms (491 modules)
 ✓ Compiled /not-found in 59ms (496 modules)
 ⨯ Error: Cannot find module '/Users/matt/work/next-export-test/dist/server/middleware-manifest.json'
Require stack:
- /Users/matt/work/next-export-test/node_modules/next/dist/server/next-server.js
- /Users/matt/work/next-export-test/node_modules/next/dist/server/dev/next-dev-server.js
- /Users/matt/work/next-export-test/node_modules/next/dist/server/next.js
- /Users/matt/work/next-export-test/node_modules/next/dist/server/lib/start-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at /Users/matt/work/next-export-test/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:928:27)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at mod.require (/Users/matt/work/next-export-test/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:121:18)
    at DevServer.getMiddlewareManifest (/Users/matt/work/next-export-test/node_modules/next/dist/server/next-server.js:899:26)
    at DevServer.getEdgeFunctionsPages (/Users/matt/work/next-export-test/node_modules/next/dist/server/next-server.js:915:31)
    at DevServer.renderErrorToResponseImpl (/Users/matt/work/next-export-test/node_modules/next/dist/server/next-server.js:874:22)
    at async DevServer.pipeImpl (/Users/matt/work/next-export-test/node_modules/next/dist/server/base-server.js:912:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/matt/work/next-export-test/node_modules/next/dist/server/next-server.js:228:21)
    at async DevServer.handleRequestImpl (/Users/matt/work/next-export-test/node_modules/next/dist/server/base-server.js:808:17)
    at async /Users/matt/work/next-export-test/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/Users/matt/work/next-export-test/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/Users/matt/work/next-export-test/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/Users/matt/work/next-export-test/node_modules/next/dist/server/lib/router-server.js:136:21)
    at async handleRequest (/Users/matt/work/next-export-test/node_modules/next/dist/server/lib/router-server.js:315:24)
    at async requestHandlerImpl (/Users/matt/work/next-export-test/node_modules/next/dist/server/lib/router-server.js:339:13)
    at async Server.requestListener (/Users/matt/work/next-export-test/node_modules/next/dist/server/lib/start-server.js:140:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/matt/work/next-export-test/node_modules/next/dist/server/next-server.js',
    '/Users/matt/work/next-export-test/node_modules/next/dist/server/dev/next-dev-server.js',
    '/Users/matt/work/next-export-test/node_modules/next/dist/server/next.js',
    '/Users/matt/work/next-export-test/node_modules/next/dist/server/lib/start-server.js'
  ]
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Binaries:
  Node: 20.0.0
  npm: 9.6.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

App Router, Static HTML Export (output: "export")

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by kasince2k** [comment]
I am facing the same issue, however check this #61134

**Comment by matthewjamesadam** [comment]
Thanks @kasince2k !
