### ISSUE TITLE
ImageResponse does not work in Route Handler (edge) with turbopack

### ISSUE THREAD

**Issue by trpfrog** [vercel/next.js#62783]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/image-response-in-dev-turbo-h4glnf

### To Reproduce

1. Start the application in development **with turbopack** (`next dev --turbo`)
2. Access the path `/image-response`.
3. You will see a large number of error logs that begin with "Error: failed to pipe response" being outputted.

### Current vs. Expected behavior

Following the steps from the previous section, I expected to see an image displaying "Hello, world," but observed that nothing was being sent from the server.

<details><summary>error log</summary>
<p>

```
 ○ Compiling /image-response ...
 ✓ Compiled /image-response in 901ms
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/workspace/node_modules/next/dist/server/pipe-readable.js:126:15)
    at async DevServer.runEdgeFunction (/workspace/node_modules/next/dist/server/next-server.js:1221:13)
    at async NextNodeServer.handleCatchallRenderRequest (/workspace/node_modules/next/dist/server/next-server.js:246:37)
    at async DevServer.handleRequestImpl (/workspace/node_modules/next/dist/server/base-server.js:794:17)
    at async /workspace/node_modules/next/dist/server/dev/next-dev-server.js:336:20
    at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/workspace/node_modules/next/dist/server/dev/next-dev-server.js:333:24)
    at async invokeRender (/workspace/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/workspace/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/workspace/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/workspace/node_modules/next/dist/server/lib/start-server.js:140:13) {
  [cause]: Error: Failed to parse URL from /_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf
      at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:287:38)
      at fetch1 (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_react_1858b1._.js:159:32)
      at doOriginalFetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6528:24)
      at /workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6653:20
      at async globalThis.fetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6324:16)
      at async Object.start (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_@vercel_og_b401e7._.js:25727:34) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:775:36)
        at new Request (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7626:25)
        at _Agent.fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11416:25)
        at fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:13723:40)
        at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:328:22) {
      code: 'ERR_INVALID_URL',
      input: '/_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf'
    }
  }
}
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/workspace/node_modules/next/dist/server/pipe-readable.js:126:15)
    at async DevServer.runEdgeFunction (/workspace/node_modules/next/dist/server/next-server.js:1221:13)
    at async NextNodeServer.handleCatchallRenderRequest (/workspace/node_modules/next/dist/server/next-server.js:246:37)
    at async DevServer.handleRequestImpl (/workspace/node_modules/next/dist/server/base-server.js:794:17)
    at async /workspace/node_modules/next/dist/server/dev/next-dev-server.js:336:20
    at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/workspace/node_modules/next/dist/server/dev/next-dev-server.js:333:24)
    at async invokeRender (/workspace/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/workspace/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/workspace/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/workspace/node_modules/next/dist/server/lib/start-server.js:140:13) {
  [cause]: Error: Failed to parse URL from /_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf
      at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:287:38)
      at fetch1 (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_react_1858b1._.js:159:32)
      at doOriginalFetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6528:24)
      at /workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6653:20
      at async globalThis.fetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6324:16)
      at async Object.start (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_@vercel_og_b401e7._.js:25727:34) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:775:36)
        at new Request (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7626:25)
        at _Agent.fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11416:25)
        at fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:13723:40)
        at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:328:22) {
      code: 'ERR_INVALID_URL',
      input: '/_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf'
    }
  }
}
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/workspace/node_modules/next/dist/server/pipe-readable.js:126:15)
    at async DevServer.runEdgeFunction (/workspace/node_modules/next/dist/server/next-server.js:1221:13)
    at async NextNodeServer.handleCatchallRenderRequest (/workspace/node_modules/next/dist/server/next-server.js:246:37)
    at async DevServer.handleRequestImpl (/workspace/node_modules/next/dist/server/base-server.js:794:17)
    at async /workspace/node_modules/next/dist/server/dev/next-dev-server.js:336:20
    at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/workspace/node_modules/next/dist/server/dev/next-dev-server.js:333:24)
    at async invokeRender (/workspace/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/workspace/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/workspace/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/workspace/node_modules/next/dist/server/lib/start-server.js:140:13) {
  [cause]: Error: Failed to parse URL from /_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf
      at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:287:38)
      at fetch1 (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_react_1858b1._.js:159:32)
      at doOriginalFetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6528:24)
      at /workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6653:20
      at async globalThis.fetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6324:16)
      at async Object.start (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_@vercel_og_b401e7._.js:25727:34) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:775:36)
        at new Request (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7626:25)
        at _Agent.fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11416:25)
        at fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:13723:40)
        at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:328:22) {
      code: 'ERR_INVALID_URL',
      input: '/_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf'
    }
  }
}
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/workspace/node_modules/next/dist/server/pipe-readable.js:126:15)
    at async DevServer.runEdgeFunction (/workspace/node_modules/next/dist/server/next-server.js:1221:13)
    at async NextNodeServer.handleCatchallRenderRequest (/workspace/node_modules/next/dist/server/next-server.js:246:37)
    at async DevServer.handleRequestImpl (/workspace/node_modules/next/dist/server/base-server.js:794:17)
    at async /workspace/node_modules/next/dist/server/dev/next-dev-server.js:336:20
    at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/workspace/node_modules/next/dist/server/dev/next-dev-server.js:333:24)
    at async invokeRender (/workspace/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/workspace/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/workspace/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/workspace/node_modules/next/dist/server/lib/start-server.js:140:13) {
  [cause]: Error: Failed to parse URL from /_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf
      at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:287:38)
      at fetch1 (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_react_1858b1._.js:159:32)
      at doOriginalFetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6528:24)
      at /workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6653:20
      at async globalThis.fetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6324:16)
      at async Object.start (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_@vercel_og_b401e7._.js:25727:34) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:775:36)
        at new Request (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7626:25)
        at _Agent.fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11416:25)
        at fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:13723:40)
        at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:328:22) {
      code: 'ERR_INVALID_URL',
      input: '/_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf'
    }
  }
}
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/workspace/node_modules/next/dist/server/pipe-readable.js:126:15)
    at async DevServer.runEdgeFunction (/workspace/node_modules/next/dist/server/next-server.js:1221:13)
    at async NextNodeServer.handleCatchallRenderRequest (/workspace/node_modules/next/dist/server/next-server.js:246:37)
    at async DevServer.handleRequestImpl (/workspace/node_modules/next/dist/server/base-server.js:794:17)
    at async /workspace/node_modules/next/dist/server/dev/next-dev-server.js:336:20
    at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/workspace/node_modules/next/dist/server/dev/next-dev-server.js:333:24)
    at async invokeRender (/workspace/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/workspace/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/workspace/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/workspace/node_modules/next/dist/server/lib/start-server.js:140:13) {
  [cause]: Error: Failed to parse URL from /_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf
      at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:287:38)
      at fetch1 (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_react_1858b1._.js:159:32)
      at doOriginalFetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6528:24)
      at /workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6653:20
      at async globalThis.fetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6324:16)
      at async Object.start (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_@vercel_og_b401e7._.js:25727:34) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:775:36)
        at new Request (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7626:25)
        at _Agent.fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11416:25)
        at fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:13723:40)
        at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:328:22) {
      code: 'ERR_INVALID_URL',
      input: '/_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf'
    }
  }
}
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/workspace/node_modules/next/dist/server/pipe-readable.js:126:15)
    at async DevServer.runEdgeFunction (/workspace/node_modules/next/dist/server/next-server.js:1221:13)
    at async NextNodeServer.handleCatchallRenderRequest (/workspace/node_modules/next/dist/server/next-server.js:246:37)
    at async DevServer.handleRequestImpl (/workspace/node_modules/next/dist/server/base-server.js:794:17)
    at async /workspace/node_modules/next/dist/server/dev/next-dev-server.js:336:20
    at async Span.traceAsyncFn (/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/workspace/node_modules/next/dist/server/dev/next-dev-server.js:333:24)
    at async invokeRender (/workspace/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/workspace/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/workspace/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/workspace/node_modules/next/dist/server/lib/start-server.js:140:13) {
  [cause]: Error: Failed to parse URL from /_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf
      at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:287:38)
      at fetch1 (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_react_1858b1._.js:159:32)
      at doOriginalFetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6528:24)
      at /workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6653:20
      at async globalThis.fetch (/workspace/.next/server/edge/chunks/node_modules_next_dist_esm_0e0955._.js:6324:16)
      at async Object.start (/workspace/.next/server/edge/chunks/node_modules_next_dist_compiled_@vercel_og_b401e7._.js:25727:34) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:775:36)
        at new Request (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7626:25)
        at _Agent.fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11416:25)
        at fetch (eval at requireWithFakeGlobalScope (/workspace/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:13723:40)
        at context.fetch (/workspace/node_modules/next/dist/server/web/sandbox/context.js:328:22) {
      code: 'ERR_INVALID_URL',
      input: '/_next/static/media/noto-sans-v27-latin-regular.7e1666d1.ttf'
    }
  }
}
```

</p>
</details> 

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.2-canary.2 // Latest available version is detected (14.1.2-canary.2).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime), Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

When trying to use ImageResponse in the edge runtime with turbopack, it's not working right. Instead of showing images, I'm getting a bunch of error messages in server-side console. I'm not sure what these errors mean.

However, it works **fine** in these situations:

- When using ImageResponse with Node.js, it works well. You can see this at `/image-response-node`.
- It also works well if used in `opengraph-image.tsx`, which you can check at `/opengraph-image`.
- It works fine without using Turbopack.
- It also works fine after doing `next start` after building.

<sub>[PACK-2645](https://linear.app/vercel/issue/PACK-2645/imageresponse-does-not-work-in-route-handler-edge-with-turbopack)</sub>

**Comment by timneutkens** [comment]
Verified this is fixed on `next@canary`. The issue was that `new URL('fontpath', import.meta.url)` was not supported yet in edge.
