### ISSUE TITLE
request host header is [::]:3000 in middleware when redirecting in server action

### ISSUE THREAD

**Issue by kevinmitch14** [vercel/next.js#62903]
### Link to the code that reproduces this issue

https://github.com/kevinmitch14/redirects

### To Reproduce

1. Start application npm run build + start
2. Press submit button to trigger redirect
3. View console logs

### Current vs. Expected behavior

Current: request host header is [::]:3000
Expected: request host header is localhost:3000

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.15.1
Relevant Packages:
  next: 14.2.0-canary.0 // Latest available version is detected (14.2.0-canary.0).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

---
Host looks to be okay when deployed to Vercel. However I wasn't able to test this with subdomains.

I've tracked it down to this PR https://github.com/vercel/next.js/pull/62561. Using the canary version before this logs host as localhost:3000.

For context, our app is a multi tenant app, each tenant lives on a subdomain. We use rewrites to handle this. To get the subdomain, we use the request host header.

**Comment by kevinmitch14** [comment]
This was introduced in [v14.1.1](https://github.com/vercel/next.js/releases/tag/v14.1.1) stable release.

**Comment by 4lejandrito** [comment]
Maybe caused by https://github.com/vercel/next.js/pull/62561? I am experiencing a similar issue in `14.1.1-canary.75` but not in `14.1.1-canary.74`.

**Comment by kevinmitch14** [comment]
Yeah, I mentioned that in the issue. I tracked it down to the same PR

**Comment by 4lejandrito** [comment]
The problem here is not only with the hostname but also with the protocol. When running behind an nginx on https:
* Before https://github.com/vercel/next.js/pull/62561 [the protocol](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/action-handler.ts#L182C5-L183C73) is `https` and the hostname `mysite.com`.
* After https://github.com/vercel/next.js/pull/62561 [the protocol](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/action-handler.ts#L182C5-L183C73) is still `https` but the hostname is `0.0.0.0:3000` which listens on http and not on https (this is handled by nginx).

I am debating whether or not to create a separate issue for this, since the root cause is the same one.

**Comment by kevinmitch14** [comment]
Yeah I thought this issue would be picked up quickly as I think it's a pretty fundamental issue/regression. 

It made it off canary and into a stable release so surely other people are going to be affected by this.

**Comment by 4lejandrito** [comment]
I reported a separate issue: https://github.com/vercel/next.js/issues/63114.

**Comment by dawi** [comment]
I am facing a similar issue while running playwright tests against a standalone export in a gitlab build pipeline.

```
uitests:playwright: [WebServer] failed to get redirect response TypeError: fetch failed
uitests:playwright:     at Object.fetch (node:internal/deps/undici/undici:11576:11)
uitests:playwright:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
uitests:playwright:     at async globalThis.fetch (/builds/xxx/xxx/apps/uitest/.next/server/chunks/369.js:1:36492)
uitests:playwright:     at async rp (/builds/xxx/xxx/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:4325)
uitests:playwright:     at async rm (/builds/xxx/xxx/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:741)
uitests:playwright:     at async rq (/builds/xxx/xxx/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1249)
uitests:playwright:     at async doRender (/builds/xxx/xxx/node_modules/next/dist/server/base-server.js:1376:30)
uitests:playwright:     at async cacheEntry.responseCache.get.routeKind (/builds/xxx/xxx/node_modules/next/dist/server/base-server.js:1537:28)
uitests:playwright:     at async NextNodeServer.renderToResponseWithComponentsImpl (/builds/xxx/xxx/node_modules/next/dist/server/base-server.js:1445:28)
uitests:playwright:     at async NextNodeServer.renderPageComponent (/builds/xxx/xxx/node_modules/next/dist/server/base-server.js:1842:24) {
uitests:playwright:   cause: Error: connect EADDRNOTAVAIL :::3000 - Local (:::0)
uitests:playwright:       at internalConnect (node:net:1100:16)
uitests:playwright:       at defaultTriggerAsyncIdScope (node:internal/async_hooks:463:18)
uitests:playwright:       at node:net:1306:9
uitests:playwright:       at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
uitests:playwright:     errno: -99,
uitests:playwright:     code: 'EADDRNOTAVAIL',
uitests:playwright:     syscall: 'connect',
uitests:playwright:     address: '::',
uitests:playwright:     port: 3000
uitests:playwright:   }
uitests:playwright: }
```

**Comment by shuding** [comment]
@kevinmitch14 Hey Kevin, thanks for the info above. Is this specific to multi tenant apps, or it breaks all cases? I think the #63389 fix still doesn't cover these multi tenant cases yet.

The reason that we moved away from request headers (`host` or `x-forwarded-host`) is that the requester side can specify any host via these headers, including malicious ones. And the redirection request to that host happens on the server side which can be risky.

One work around idea might be adding an extra header that specifies the original request host/forwarded-host, to the redirection request. So the middleware can know its original host even if the request itself is just `localhost:3000`. What do you think?

**Comment by kevinmitch14** [comment]
Hey @shuding, here is a barebones version of the middleware. The issue appears when I use `redirect()` because the host passed to `getSubdomain()` no longer has the subdomain. It's just `localhost:3000` instead of `tenant.localhost:3000`

Because tenants live on subdomains, when the host is localhost:3000 I just return `NextResponse.next()`, which results in the "wrong" redirect. Previously the subdomain is extracted and appended to the `pathname` before rewriting.


```tsx
export function middleware(request: NextRequest) {
  const url = request.nextUrl.clone();
  const subdomain = getSubdomain(request.headers.get("host"));
  const path = url.pathname;
  console.log({ subdomain, path });
  if (subdomain === "localhost:3000") {
    return NextResponse.next();
  }
  const destinationUrl = url.clone();
  destinationUrl.pathname = `/${subdomain}${path}`;
  return NextResponse.rewrite(destinationUrl);
}
```


In my use-case, the tenant will always live on a subdomain (`tenant1.example.com`) would equate to `tenant1`. How I know which tenant was making the request was through the host header in middleware, as this is the first entry point into the app. 

A request to `tenant1.example.com/blog` would go through middleware and be rewritten to `/[tenant1]/blog`. In the layout I do a check to see if this is a valid tenant via a DB call, if not, `notFound()` is invoked. 

---

The initial way I find the current tenant is through middleware via the request host header. Is this part dangerous or is it just the redirection aspect that is considered potentially dangerous?

Just to be clear, you recommend something like the following:
- Check if valid tenant in middleware
- Setting a custom header like `x-active-tenant` in the initial middleware response if valid.
- Use this header value to identify the active tenant on subsequent requests. 
```
const subdomain = request.headers.get("x-active-tenant");
```

**Comment by kevinmitch14** [comment]
I think multi-tenant is definitely an area for improvement in docs + education. 

Here is Next.js ["recommended architecture"](https://nextjs.org/docs/app#how-can-i-build-multi-tenant-apps) for Multi-tenant apps: https://github.com/vercel/platforms.

And the middleware specifically, similar to ours, uses the host from the incoming request headers - https://github.com/vercel/platforms/blob/main/middleware.ts

**Comment by dawi** [comment]
Just tried `14.2.0-canary.29`. Everything works in dev mode, but in a standalone export I am now getting a client-side exception. No issues with 14.1.0. But maybe that's a new regression, and has nothing to do wit this issue. :/

> Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by blizzy78** [comment]
> Application error: a client-side exception has occurred (see the browser console for more information).

So is there more info in the browser console you can post here?

**Comment by dawi** [comment]
@blizzy78 All I have is the minified react error, which tells me to use the dev environment for full errors.

However in dev mode everything runs fine. The error only occurs in a production standalone build.

> 7023-678442bb9053eb7a.js:1 Error: Minified React error #130; visit https://react.dev/errors/130?args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>     at iz (fd9d1056-8215d544d1fd3378.js:1:113022)
>     at d (fd9d1056-8215d544d1fd3378.js:1:34851)
>     at fd9d1056-8215d544d1fd3378.js:1:37511
>     at u (fd9d1056-8215d544d1fd3378.js:1:37802)
>     at fd9d1056-8215d544d1fd3378.js:1:38869
>     at lD (fd9d1056-8215d544d1fd3378.js:1:57332)
>     at iZ (fd9d1056-8215d544d1fd3378.js:1:121359)
>     at ia (fd9d1056-8215d544d1fd3378.js:1:95165)
>     at fd9d1056-8215d544d1fd3378.js:1:94987
>     at il (fd9d1056-8215d544d1fd3378.js:1:94994)
>

**Comment by shuding** [comment]
@dawi Would you mind explaining a bit about your set up? In which context did it throw and is your app relying on the host headers somewhere?

**Comment by dawi** [comment]
@shuding I will have a look and provide more details.

**Comment by dawi** [comment]
@shuding Maybe the error i am running into is this one: 62953

**Comment by dawi** [comment]
@shuding I think this issue can be closed again. 

But the client side exception (https://github.com/vercel/next.js/issues/62953) still exists in the latest canary.

**Comment by kevinmitch14** [comment]
> Hey @shuding, here is a barebones version of the middleware. The issue appears when I use `redirect()` because the host passed to `getSubdomain()` no longer has the subdomain. It's just `localhost:3000` instead of `tenant.localhost:3000`
> 
> Because tenants live on subdomains, when the host is localhost:3000 I just return `NextResponse.next()`, which results in the "wrong" redirect. Previously the subdomain is extracted and appended to the `pathname` before rewriting.
> 
> ```tsx
> export function middleware(request: NextRequest) {
>   const url = request.nextUrl.clone();
>   const subdomain = getSubdomain(request.headers.get("host"));
>   const path = url.pathname;
>   console.log({ subdomain, path });
>   if (subdomain === "localhost:3000") {
>     return NextResponse.next();
>   }
>   const destinationUrl = url.clone();
>   destinationUrl.pathname = `/${subdomain}${path}`;
>   return NextResponse.rewrite(destinationUrl);
> }
> ```
> 
> In my use-case, the tenant will always live on a subdomain (`tenant1.example.com`) would equate to `tenant1`. How I know which tenant was making the request was through the host header in middleware, as this is the first entry point into the app.
> 
> A request to `tenant1.example.com/blog` would go through middleware and be rewritten to `/[tenant1]/blog`. In the layout I do a check to see if this is a valid tenant via a DB call, if not, `notFound()` is invoked.
> 
> The initial way I find the current tenant is through middleware via the request host header. Is this part dangerous or is it just the redirection aspect that is considered potentially dangerous?
> 
> Just to be clear, you recommend something like the following: User enters app `tenant1.example.com`
> 
> 1. Middleware invoked - request `x-forwarded-host : tenant1.example.com`.
> 2. Do check if `tenant1` is a valid tenant. (Is it signed up to the product)
> 3. Do auth check if user is valid user of `tenant1`
> 4. If above are all true, respond with rewrite and append header `x-active-tenant : tenant1`
> 5. For each request in middleware, check for presence of `x-active-tenant`
> 6. If present, skip step 2. Otherwise, go through all steps.
> 
> User completes action w/server action redirect:
> 
> 1. Read `x-active-tenant` from headers, it _should_ be present at this stage if the user is in the app.
> 2. If not present, use the `x-forwarded-header` to determine the subdomain and check if valid tenant.
> 3. Middleware will receive this request with `host : example.com`, `x-forwarded-host : tenant1.example.com`
> 4. For security Middleware will read `x-active-tenant` to determine the subdomain to use for rewrite.
> 
> Having a read of some docs [here](https://nextjs.org/blog/security-nextjs-server-components-actions#csrf) I also found this:
> 
> > As an additional protection Server Actions in Next.js 14 also compares the Origin header to the Host header (or X-Forwarded-Host). If they don't match, the Action will be rejected. In other words, Server Actions can only be invoked on the same host as the page that hosts it. Very old unsupported and outdated browsers that don't support the Origin header could be at risk.
> 
> Does this have any relevance? Also a bit confusing, "Host header (or X-Forwarded-Host)", when using a subdomain, the host and forwarded host will be different anyway?

@shuding would be great to know if I understood your original response here!

**Comment by mlynch** [comment]
I'm not sure but I think I'm seeing the same issue (`ERR_SSL_WRONG_VERSION_NUMBER`) when using `redirect` in a server action, specifically when following [this supabase + Next.js auth flow doc](https://supabase.com/docs/guides/auth/server-side/nextjs):

<img width="937" alt="image" src="https://github.com/vercel/next.js/assets/11214/fa161052-c686-4c37-acfa-93ba3b4a3e46">

<img width="1276" alt="image" src="https://github.com/vercel/next.js/assets/11214/a15ef94c-9a45-4a57-93d9-651cb8933800">

**Comment by Gus007-BR** [comment]
Hello. Any updates on this? Did anyone find a good workaround?

I just spent two days trying to figure this out and trying to figure this out. @kevinmitch14 did a good explanation.

I don't understand why a redirect changes the "host" header from "tenant1.localhost:3000" to just "localhost:3000". Someone mentioned security but in my opinion, all authentication and authorization in a multi-tenant solution should come from a verified JWT, not from a header value... In my design, if a client manages to change the host header at any point, it just means that their token validation will fail.

**Comment by chevsky** [comment]
Same issue here.

Multi-tenant website, calling `redirect` in server action. `headers().get('host')` returns unexpected value during target page render. Switching to `x-forwarded-host` solved the issue for me.

The root of the issue lies in this request: [app-render/action-handler.ts#L334](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/action-handler.ts#L334). After detecting a redirect instruction, Next.js server fetches target route to get server component payload to be included in server action response. The thing is that `fetch()` doesn't allow the "Host" header to be overridden, so the passed value gets lost.


@shuding Knowing that, is it possible to make `headers()` return a correct "Host" value in this case? Maybe by ditching the inner request entirely or patching the `headers()` function.

**Comment by jamesjulich** [comment]
I'm also experiencing this issue. I'm running a multitenant app where users get a subdomain on *.app.com. I call headers() from a function named "getTenant". I call "getTenant" in server components.

When I redirect users to the /login page, my "getTenant" function sees localhost:3000 as host. This only happens during a redirect. @chevsky described a pretty similar problem.

Any updates on this? Is this something that the NextJS team is planning on fixing, or is this intended?
