### ISSUE TITLE
Error when redirecting in a server action

### ISSUE THREAD

**Issue by 4lejandrito** [vercel/next.js#63114]
### Link to the code that reproduces this issue

https://github.com/4lejandrito/next-server-action-redirect-issue

### To Reproduce

Follow the steps in https://github.com/4lejandrito/next-server-action-redirect-issue.

### Current vs. Expected behavior

The issue happens when running behind an nginx on https:
* Before https://github.com/vercel/next.js/pull/62561 [the protocol](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/action-handler.ts#L182C5-L183C73) is `https` and the hostname `mysite.com` and the redirects work fine.
* After https://github.com/vercel/next.js/pull/62561 [the protocol](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/action-handler.ts#L182C5-L183C73) is still `https` but the hostname is `0.0.0.0:3000` which listens on http and not on https (this is handled by nginx). This causes the redirects to break with `failed to get redirect response TypeError: fetch failed` + `ERR_SSL_WRONG_VERSION_NUMBER`.

This is the full error:
```
failed to get redirect response TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (/Users/alex/Projects/next-server-action-redirect-issue/.next/server/chunks/22.js:1:123262)
    at async rp (/Users/alex/Projects/next-server-action-redirect-issue/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:4325)
    at async rm (/Users/alex/Projects/next-server-action-redirect-issue/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:741)
    at async rq (/Users/alex/Projects/next-server-action-redirect-issue/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1249)
    at async doRender (/Users/alex/Projects/next-server-action-redirect-issue/node_modules/next/dist/server/base-server.js:1395:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/alex/Projects/next-server-action-redirect-issue/node_modules/next/dist/server/base-server.js:1556:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/Users/alex/Projects/next-server-action-redirect-issue/node_modules/next/dist/server/base-server.js:1464:28)
    at async NextNodeServer.renderPageComponent (/Users/alex/Projects/next-server-action-redirect-issue/node_modules/next/dist/server/base-server.js:1861:24) {
  cause: [Error: 401C53DE01000000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:355:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }
}
```
If the local hostname is used now, the protocol should not be https.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 18.18.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.5.0
Relevant Packages:
  next: 14.2.0-canary.12 // Latest available version is detected (14.2.0-canary.12).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by 4lejandrito** [comment]
Fixed! https://github.com/4lejandrito/next-server-action-redirect-issue/actions/runs/8331861721.
