### ISSUE TITLE
Dynamic import trace in page source

### ISSUE THREAD

**Issue by mertafor** [vercel/next.js#63272]
### Link to the code that reproduces this issue

https://github.com/mertafor/nextjs-dynamic-bailout

### To Reproduce

1 - Start application: pnpm dev
2 - Visit localhost:3000 and view page source
3 - dynamic imports with "ssr:false" leaves a trace in dev mode

### Current vs. Expected behavior

First of all I'm not sure if this is a bug. This only happens in dev mode and cannot be seen in production. 

Terminal and browser console don't show any errors and dynamic imports are being loaded without any problem. However, I noticed that if SSR is set to false in dynamic imports, an error trace is left can be seen in page source :  

```js
const LazyCompNonSSR = dynamic(
  () =>
    import('./LazyImportComponent').then(
      (mod) => mod.LazyImportComponent
    ),
  { ssr: false }
);
```

```html
<template data-dgst="BAILOUT_TO_CLIENT_SIDE_RENDERING" data-msg="Bail out to client-side rendering: next/dynamic" data-stck="
--
  | at BailoutToCSR (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/lazy-dynamic/dynamic-bailout-to-csr.js:13:11)
  | at Suspense
  | at LoadableComponent
  | at div
  | at ClientComp
  | at Lazy
  | at main
  | at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:241:11)
  | at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:72:9)
  | at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:80:11)
  | at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
  | at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
  | at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:338:11)
  | at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:159:11)
  | at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:152:9)
  | at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:227:11)
  | at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
  | at Lazy
  | at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:356:11)
  | at Lazy
  | at body
  | at html
  | at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:72:9)
  | at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:80:11)
  | at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:84:9)
  | at HotReload (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:308:11)
  | at Router (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:177:11)
  | at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:113:9)
  | at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:159:11)
  | at AppRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:517:13)
  | at Lazy
  | at Lazy
  | at rw (/Users/mertdaglaroglu/Documents/WebProjects/Reactive/nextjs-dynamic-bailout/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:15737)
  | at rw (/Users/mertdaglaroglu/Documents/WebProjects/Reactive/nextjs-dynamic-bailout/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:15737)
  | at ServerInsertedHTMLProvider (/Users/mertdaglaroglu/Documents/WebProjects/Reactive/nextjs-dynamic-bailout/node_modules/.pnpm/next@14.1.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:21384)"></template>
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:45:49 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 20.5.1
  npm: 9.8.0
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.21 // Latest available version is detected (14.2.0-canary.21).
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Dynamic imports (next/dynamic)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

We're currently using 14.1.2 in our project but this repo is built with latest canary.

**Comment by iamalvisng** [comment]
I have the same issue here too, when `ssr` option is set to `false`.

**Comment by tkasper** [comment]
Same here. We're using `14.1.3`

**Comment by CollinHerber** [comment]
I am also seeing this with `14.1.4`

**Comment by traktorHex** [comment]
I am also seeing this with 14.1.4

**Comment by huozhi** [comment]
FYI it's an implementation detail that how dynamic with `ssr: false` working is: `next/dynamic` will throw an customized error during server side rendering (SSR), and then caught by a suspense boundary which showing the fallback during SSR and then render the actual client only dynamic loaded component on the client side.

The error trace will only present during dev mode, and it's just a placeholder for production mode. This is how React dealing with the streaming atm that will send the error in the streaming and replace that with the content later. So far you don't need to worry about this and it might get optimized in the future along with React.
