### ISSUE TITLE
Error: Image with src "/logo.svg" is missing required "width" property in with-redux example

### ISSUE THREAD

**Issue by FoSuCloud** [vercel/next.js#63542]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.1
  npm: 10.2.4
  Yarn: 1.22.11
  pnpm: 8.15.1
Relevant Packages:
  next: 14.2.0-canary.34 // Latest available version is detected (14.2.0-canary.34).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-redux

### What browser are you using? (if relevant)

Chrome 122.0.6261.129

### Describe the Bug

when i open the chrome
```javascript
⨯ Internal error: Error: Image with src "/logo.svg" is missing required "width" property.
    at getImgProps (./node_modules/.pnpm/next@14.2.0-canary.34_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/get-img-props.js:267:27)
    at eval (./node_modules/.pnpm/next@14.2.0-canary.34_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/image-component.js:279:82)
    at au (/Users/xielipei/Documents/reactProject/with-redux-app/node_modules/.pnpm/next@14.2.0-canary.34_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
....
```
![截屏2024-03-21 10 09 21](https://github.com/vercel/next.js/assets/49218295/e6d50862-eab4-4fc8-8a4f-0be945165ef9)

### Expected Behavior

Open the page normally

### To Reproduce

pnpm create next-app --example with-redux with-redux-app
pnpm run dev

**Comment by FoSuCloud** [comment]
I want to solve this problem
