### ISSUE TITLE
Github action Build failing with TypeError [ERR_INVALID_URL]: Invalid URL in next 14.1.4

### ISSUE THREAD

**Issue by Kamasah-Dickson** [vercel/next.js#63596]
### Link to the code that reproduces this issue

https://github.com/SATSAT-Ai/SATSAT-Ai/tree/feature

### To Reproduce

clone the repo and run github actions to reproduce the issue.
start the application locally by running npm run dev.

### Current vs. Expected behavior

expecting appication to be build without any error

```javascript
✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at 3639 (/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/server/chunks/166.js:3:3511)
    at Function.t (/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/server/webpack-runtime.js:1:128)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (/home/runner/work/SATSAT-Ai/SATSAT-Ai/node_modules/next/dist/build/utils.js:9[19](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8386300865/job/22966491436#step:5:20):21)
    at async /home/runner/work/SATSAT-Ai/SATSAT-Ai/node_modules/next/dist/build/utils.js:1138:17
    at async Span.traceAsyncFn (/home/runner/work/SATSAT-Ai/SATSAT-Ai/node_modules/next/dist/trace/trace.js:151:[20](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8386300865/job/22966491436#step:5:21)) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}```

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, TypeScript (plugin, built-in types)

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

I am using github actions to build my application and test my cypress end-to-end tests but the build is falling with

expecting appication to be build without any error

```javascript
✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at 3639 (/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/server/chunks/166.js:3:3511)
    at Function.t (/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/server/webpack-runtime.js:1:128)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (/home/runner/work/SATSAT-Ai/SATSAT-Ai/node_modules/next/dist/build/utils.js:9[19](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8386300865/job/22966491436#step:5:20):21)
    at async /home/runner/work/SATSAT-Ai/SATSAT-Ai/node_modules/next/dist/build/utils.js:1138:17
    at async Span.traceAsyncFn (/home/runner/work/SATSAT-Ai/SATSAT-Ai/node_modules/next/dist/trace/trace.js:151:[20](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8386300865/job/22966491436#step:5:21)) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}

> Build error occurred
Error: Failed to collect page data for /_not-found
    at /home/runner/work/SATSAT-Ai/SATSAT-Ai/node_modules/next/dist/build/utils.js:1[25](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8386300865/job/22966491436#step:5:26)8:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
Error: Process completed with exit code 1.
}```

**Comment by Kamasah-Dickson** [comment]
I decided to choose the next js work flow from github and I am able to make some progress but now I have this error. anybody can help me set up this github actions?

``` javascript
/opt/hostedtoolcache/node/20.11.1/x64/bin/npx cypress cache list
┌─────────┬─────────────┐
│ version │ last used   │
├─────────┼─────────────┤
│ 13.6.6  │ a month ago │
└─────────┴─────────────┘
/opt/hostedtoolcache/node/20.11.1/x64/bin/npx cypress verify
[STARTED] Task without title.
[SUCCESS] Task without title.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/SATSAT-Ai/SATSAT-Ai --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~208 MB (218190264 B)
Cache saved successfully
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/SATSAT-Ai/SATSAT-Ai --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~163 MB (1709[57](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:58)328 B)
Cache saved successfully
start server command "npm start"
current working directory "/home/runner/work/SATSAT-Ai/SATSAT-Ai"
waiting on "http://localhost:3000" with timeout of [60](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:61) seconds
/opt/hostedtoolcache/node/20.11.1/x[64](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:65)/bin/npm start
> satsat-ai@0.1.0 start
> next start
   ▲ Next.js 14.1.4
   - Local:        http://localhost:3000
[Error: ENOENT: no such file or directory, open '/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/BUILD_ID'
}
/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^
Error: The process '/opt/hostedtoolcache/node/20.11.1/x64/bin/npm' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3883:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3[77](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:78)7:27)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Node.js v20.8.1
```

**Comment by Kamasah-Dickson** [comment]
> I decided to choose the next js work flow from github and I am able to make some progress but now I have this error. Am I missing something? please can anybody help me set up these github actions?
> 
> ```js
> /opt/hostedtoolcache/node/20.11.1/x64/bin/npx cypress cache list
> ┌─────────┬─────────────┐
> │ version │ last used   │
> ├─────────┼─────────────┤
> │ 13.6.6  │ a month ago │
> └─────────┴─────────────┘
> /opt/hostedtoolcache/node/20.11.1/x64/bin/npx cypress verify
> [STARTED] Task without title.
> [SUCCESS] Task without title.
> /usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/SATSAT-Ai/SATSAT-Ai --files-from manifest.txt --use-compress-program zstdmt
> Cache Size: ~208 MB (218190264 B)
> Cache saved successfully
> /usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/SATSAT-Ai/SATSAT-Ai --files-from manifest.txt --use-compress-program zstdmt
> Cache Size: ~163 MB (1709[57](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:58)328 B)
> Cache saved successfully
> start server command "npm start"
> current working directory "/home/runner/work/SATSAT-Ai/SATSAT-Ai"
> waiting on "http://localhost:3000" with timeout of [60](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:61) seconds
> /opt/hostedtoolcache/node/20.11.1/x[64](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:65)/bin/npm start
> > satsat-ai@0.1.0 start
> > next start
>    ▲ Next.js 14.1.4
>    - Local:        http://localhost:3000
> [Error: ENOENT: no such file or directory, open '/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/BUILD_ID'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/home/runner/work/SATSAT-Ai/SATSAT-Ai/.next/BUILD_ID'
> }
> /home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900
>                 error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
>                         ^
> Error: The process '/opt/hostedtoolcache/node/20.11.1/x64/bin/npm' failed with exit code 1
>     at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3900:25)
>     at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3883:18)
>     at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v6/dist/index.js:3[77](https://github.com/SATSAT-Ai/SATSAT-Ai/actions/runs/8405395360/job/23018073134#step:8:78)7:27)
>     at ChildProcess.emit (node:events:514:28)
>     at maybeClose (node:internal/child_process:1105:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
> Node.js v20.8.1
> ```
