### ISSUE TITLE
generateStaticParams() not detected when using parallel routes / dynamic routes using output: export

### ISSUE THREAD

**Issue by KoenLemmen** [vercel/next.js#63951]
### Link to the code that reproduces this issue

https://github.com/KoenLemmen/nextgramminimal/

### To Reproduce

1. Start application in dev mode (application won't build with the same error)
2. Go to localhost:3000/
3. Click one of the "images"
4. No modal opens
5. Error happens:
```
Error: Page "/@modal/(.)photos/[id]/page" is missing exported function "generateStaticParams()", which is required with "output: export" config.
    at DevServer.renderToResponseWithComponentsImpl (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\base-server.js:1071:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.renderPageComponent (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\base-server.js:1913:24)
    at async DevServer.renderToResponseImpl (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\base-server.js:1951:32)
    at async DevServer.pipeImpl (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\base-server.js:807:17)
    at async C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\koenl\Downloads\april\nextgram\node_modules\next\dist\server\lib\start-server.js:141:13) {
  page: '/(.)photos/1'
```
6. photos/[id] is opened instead of @modal/(.)photos/[id]

As can be seen in @modal/(.)photos/[id] the exported function is present.

### Current vs. Expected behavior

Current behavior:
- Modal path errors and non modal path opens
- generateStaticParams() is not detected and used

Expected behavior:
- Modal path is opened
- Modal path uses generateStaticParams()

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 65463
  Available CPU cores: 24
Binaries:
  Node: 20.8.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.0-canary.51 // Latest available version is detected (14.2.0-canary.51).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps), Static HTML Export (output: "export")

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

Unsure but might be related to: https://github.com/vercel/next.js/issues/52842

<sub>[NEXT-3296](https://linear.app/vercel/issue/NEXT-3296/generatestaticparams-not-detected-when-using-parallel-routes-dynamic)</sub>

**Comment by Syhans** [comment]
Can confirm, I have the same issue for basically the same use case. For what it's worth:

- I checked several Next 14 releases (`14.1.4` (current latest), `14.0.0`, `14.0.1` and `14.0.3`, as well as the current canary `14.2.0-canary.61`) and get this behaviour with all of them.
- The app behaves as expected when not using `output: "export"`. Which, granted, is not very helpful when the goal is to create a static site.

**Comment by NeoPrint3D** [comment]
Any Progress or updates? This issue is super dumb especially if vercel wants to ease people into using nextjs from an old codebase or vite.

**Comment by KoenLemmen** [comment]
Not that I know of. Still broken in 14.2.1-canary.6

**Comment by PArns** [comment]
My page heavily uses parallel routing, which ultimately ends in just having dynamic rendering and no SSR at all.

So adding this feature would be really beneficial -> https://patrick-arns.de

**Comment by KoenLemmen** [comment]
Looks like this issue is wrongfully tagged as pages router. I did say in the post its an app router bug.

**Comment by elmarsto** [comment]
this should be a hi-pri fix, it makes parallel routes useless for a number of important use cases, e.g. an edit modal that takes an id in the path

**Comment by KoenLemmen** [comment]
I agree. Modals in general don't work due to this, the minimal I attached is their own example.

**Comment by BuzzardM** [comment]
Upon having the same issue I stumbled on this issue. Is there a workaround (or even a fix) available for this?

**Comment by KoenLemmen** [comment]
Not yet but I'm hoping https://github.com/vercel/next.js/pull/65348 might also fix this.

**Comment by KoenLemmen** [comment]
Present in 15.0.0-canary.37

**Comment by brense** [comment]
This bug is present regardless of which output mode is used in next 14.2.5.

If you use a catchAll route `[...rest]` in one of the parallel routes, you can work a little bit around it by adding the routes you want to generate in the `getStaticParams` of the root layout (where the parallel routes are used).

**Comment by christiankaseburg** [comment]
Any updates on this issue?

**Comment by christiankaseburg** [comment]
Any updates on resolving this bug? I am experiencing the same build errors related to my parallel intercepting routes with my static application that I build with next.config `output: "export"`.

**Comment by KoenLemmen** [comment]
Updated the minimal to use next-async-request-api and to the latest canary 15.0.1-canary.0.
Unfortunately the issues are still present.

**Comment by eliot-akira** [comment]
Still seeing this on `15.0.1`. I tried the proposed fix in PR #65348 but it didn't solve it. The error message is confusing because there is `export const generateStaticParams` in the referenced route.

For me the error goes away if I comment out `i18n` from the next config. Looking at the docs for [i18n](https://nextjs.org/docs/app/building-your-application/routing/internationalization), I think my setup is not configured correctly, and the error actually means "route not found".

**Comment by hamonCordova** [comment]
Same here. I want a static pages with i18n. The error occurs even if I put the generateStaticParams where is requested.

**Comment by kvin5529** [comment]
Same happened in next `14.2.15`...any update on this issue ?

**Comment by Sardor-M** [comment]
I can confirm i am getting the same  ``app router`` bug being thrown in the ``"next": "^15.0.3",`` version. Below is the error message in detail: 

>  ⨯ Error: Page "/events/upcoming/details/[id]/page" is missing exported function "generateStaticParams()", which is required with "output: export" config.
    at DevServer.renderToResponseWithComponentsImpl (node_modules/next/src/server/base-server.ts:1979:16) {
  page: '/events/upcoming/details/3'
  
  Any workaround or help is appreciated. Thank you  !

**Comment by KoenLemmen** [comment]
Updated the minimal to use 15.1.5.

Things have changed. There's no longer errors when using the dev server and both navigation to a new tab or modal work.
However, unfortunately this does not work for the build yet, the build has no errors but the behaviour described above is not present in the export build.

What I think should happen:
- If url gets loaded directly the photo just opens (this is working properly)
- If the image gets clicked next should capture the event and instead of directing the user to the page, it should run the modal code (this only happens in dev right now, no parity with the export)

I do think this is a step in the right direction. No more errors, functional when running pnpm dev, feels like we're this close to having modals work with static exports.

**Comment by ztanner** [comment]
Hi all, thank you for the report!

Parallel routes should work fine with `output: export`. And indeed, that erroneous build error should no longer be happening in latest versions. However, looking at the reproduction, the problem is specifically with _interception routes_. Interception routes are built on top of parallel routes, but they make use of [rewrites](https://nextjs.org/docs/app/api-reference/config/next-config-js/rewrites) to determine which page component should be rendered during a client navigation.

Rewrites are one of the things that we've documented as not being supported by `output: "export"` ([ref](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#unsupported-features)) as they currently require a server to handle. However, it's an oversight on our part that we do not explicitly document interception routes as being unsupported, and that we aren't erroring when we detect interception route usage in an exported app.

We'd like to support as many features as possible with `output: export`, and have ideas on how to make this work in the future. I'll leave this issue open until we can get proper documentation & feedback in dev that it's not yet supported.

**Comment by KoenLemmen** [comment]
Thanks for your response and explanation ztanner.
I get how generally rewrites can be a complex topic.
But for the case of modals as with this minimal, I do not understand how the client's javascript can't just open the modal.
When the url is opened directly or opened as a new tab it functions accordingly already as these routes are just generated files for the webserver to serve. 
There really only needs to be something in next that recognizes the modal pattern and let the client treat it as such.
Especially since the modal can also be pregenerated or just be a client component, there really is no need for a server in this case.
It's not so much a rewrite as just opening a new component.
No use of headers or redirects. Just open te modal, update url and history, no actual networking actions. 
To me it feels like just sending an error and blaming it on the redirect cases that do not fit these properties is not a real fix.

**Comment by ztanner** [comment]
> Thanks for your response and explanation ztanner. I get how generally rewrites can be a complex topic. But for the case of modals as with this minimal, I do not understand how the client's javascript can't just open the modal. When the url is opened directly or opened as a new tab it functions accordingly already as these routes are just generated files for the webserver to serve. There really only needs to be something in next that recognizes the modal pattern and let the client treat it as such. Especially since the modal can also be pregenerated or just be a client component, there really is no need for a server in this case. It's not so much a rewrite as just opening a new component. No use of headers or redirects. Just open te modal, update url and history, no actual networking actions. To me it feels like just sending an error and blaming it on the redirect cases that do not fit these properties is not a real fix.

If you aren't interested in the interception behavior of modals, then you can implement the modal with a parallel route. Interception routes are only necessary if the goal is to show a _different_ experience when performing a client navigation (eg soft nav) vs landing directly on the page. The former will show the interception route, the latter will show the underlying page component.

If you don't need that behavior, then you're able to implement the modal pattern with parallel routes and `output: export`. However, if you need the deeplinking behavior, that's where there's additional complexity that currently requires a server to determine if, based on a particular request, it should serve Component A or Component B.
