### ISSUE TITLE
ReferenceError: userland is not defined from punicode (deprecated)

### ISSUE THREAD

**Issue by Kamasah-Dickson** [vercel/next.js#64003]
### Link to the code that reproduces this issue

https://github.com/SATSAT-Ai/SATSAT-Ai

### To Reproduce

start the application in dev mode by runing npm run dev

### Current vs. Expected behavior

I am using the --turbo on the nex dev scripts which show the error when i visit a page built with nextra. the error says

```javascript
Server Error
ReferenceError: userland is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///C:/Users/Kamasah%20Dickson/Desktop/satsat-ai/.next/server/chunks/80ec3_next_dist_esm_befffb._.js (102:363)
[project]/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0/node_modules/next/dist/esm/build/templates/pages.js/(INNER_PAGE)/[project]/pages/developers/api/apiVersion.mdx (ecmascript)
file:///C:/Users/Kamasah%20Dickson/Desktop/satsat-ai/.next/server/chunks/80ec3_next_dist_esm_befffb._.js (129:3)
```

in my termical too i get

``` javascript

 ✓ Ready in 24.4s
 ○ Compiling /developers/api/apiVersion ...
 ✓ Compiled /developers/api/apiVersion in 3.5s
 ⨯ ReferenceError: userland is not defined
    at C:\Users\Kamasah Dickson\Desktop\satsat-ai\.next\server\chunks\80ec3_next_dist_esm_befffb._.js:102:363
    at [project]/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0/node_modules/next/dist/esm/build/templates/pages.js/(INNER_PAGE)/[project]/pages/developers/api/apiVersion.mdx (ecmascript) (C:\Users\Kamasah Dickson\Desktop\satsat-ai\.next\server\chunks\80ec3_next_dist_esm_befffb._.js:129:3)
    at instantiateModule (C:\Users\Kamasah Dickson\Desktop\satsat-ai\.next\server\chunks\[turbopack]_runtime.js:488:23)
    at instantiateRuntimeModule (C:\Users\Kamasah Dickson\Desktop\satsat-ai\.next\server\chunks\[turbopack]_runtime.js:547:12)
    at Object.getOrInstantiateRuntimeModule (C:\Users\Kamasah Dickson\Desktop\satsat-ai\.next\server\chunks\[turbopack]_runtime.js:562:12)
    at Object.<anonymous> (C:\Users\Kamasah Dickson\Desktop\satsat-ai\.next\server\pages\developers\api\apiVersion.js:4:26)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requirePage (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\require.js:109:84)
    at C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\load-components.js:98:84
    at async loadComponentsImpl (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\load-components.js:98:26)
    at async DevServer.findPageComponentsImpl (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\next-server.js:664:36)
    at async DevServer.findPageComponents (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\dev\next-dev-server.js:565:20)
    at async DevServer.renderPageComponent (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\base-server.js:1832:24)
    at async DevServer.renderToResponseImpl (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\base-server.js:1882:32)
    at async DevServer.pipeImpl (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\base-server.js:895:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\next-server.js:269:17)
    at async DevServer.handleRequestImpl (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\base-server.js:791:17)
    at async C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\dev\next-dev-server.js:331:20
    at async Span.traceAsyncFn (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\dev\next-dev-server.js:328:24)
    at async invokeRender (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\Kamasah Dickson\Desktop\satsat-ai\node_modules\.pnpm\next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0_sass@1.72.0\node_modules\next\dist\server\lib\start-server.js:140:13) {
  page: '/developers/api/apiVersion'
}
 ✓ Compiled /_error in 407ms

```

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro   
Binaries:
  Node: 20.12.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.5
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, MDX (@next/mdx)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by samcx** [comment]
@Kamasah-Dickson I am getting a type error when starting your project in `next dev`.

![CleanShot 2024-04-17 at 16 30 18@2x](https://github.com/vercel/next.js/assets/28912696/fc7d3b57-7a12-4424-8c94-57acc22d54dd)
