### ISSUE TITLE
Missing webpack dependency when using output standalone + custom server

### ISSUE THREAD

**Issue by maximelebastard** [vercel/next.js#64031]
### Link to the code that reproduces this issue

https://github.com/maximelebastard/nextjs-issue-custom-server

### To Reproduce

The issue is related to using the output: "standalone" with a custom server. See example repository.

1. Clone the reproducing repository
2. Run `npm install` then `npm run build` and `npm run start`
3. When starting the app, an error will be triggered due to a missing webpack file on a webpack require (see the error below)
4. To see the code triggering this issue, see this commit: https://github.com/maximelebastard/nextjs-issue-custom-server/commit/c47de3a03c6694ac760b748ed2fecc28b97bb2e5

### Current vs. Expected behavior

Expected:
1. I create a recent NextJS project (14.1.4) using a recent Node version (v20.12)
2. I want to deploy my app using Docker, therefore I use [the `output: "standalone"` configuration in `next.config.js`](https://nextjs.org/docs/pages/api-reference/next-config-js/output)
3. I want to use some logging middlewares, therefore I use [a custom `server.js`](https://nextjs.org/docs/pages/building-your-application/configuring/custom-server)
5. When I run `npm run build` and copy my custom server code to the build dir, the app is properly built and the file is properly copied
6. When requiring next from `server.js`, all the dependencies are present and the server starts

Actual:
1. 1-4 are the same as expected
5. `.next/standalone/node_modules/next/dist/compiled/webpack/build5.js` does not exists in the built app
7. When requiring next from `server.js`, I'm getting the error below because webpack tries to require `build5.js`

```
> node .next/standalone/custom-server.js

node:internal/modules/cjs/loader:1143
  const err = new Error(message);
              ^

Error: Cannot find module './bundle5'
Require stack:
- /Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/compiled/webpack/webpack.js
- /Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/config-utils.js
- /Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/config.js
- /Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/next.js
- /Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/custom-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at /Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at exports.init (/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/compiled/webpack/webpack.js:24:28)
    at loadWebpackHook (/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/config-utils.js:18:5)
    at loadConfig (/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/config.js:642:46)
    at initialize (/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/lib/router-server.js:55:46) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/compiled/webpack/webpack.js',
    '/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/config-utils.js',
    '/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/config.js',
    '/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/node_modules/next/dist/server/next.js',
    '/Users/maxime/workspace/issue-bundle5-nextjs/.next/standalone/custom-server.js'
  ]
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Standalone mode (output: "standalone")

### Which stage(s) are affected? (Select all that apply)

next start (local)

### Additional context

A workaround I found is to disable standalone output.
That probably disables tree shaking and relies on the complete node_modules directory.
A big drawback is that it makes a heavy docker image.

**Comment by cs-miller** [comment]
I'm seeing the same issue

**Comment by clementzhao** [comment]
I have same issue. And I found the server.js which compiled with standalone can works. So I just copy these 2lines, and my custom server.js also works fine.
```
const nextConfig = {which from compiled server.js}
process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(nextConfig)
```

**Comment by codingbala** [comment]
Here's my code, and while it works successfully, I'm not sure it's going to be a hidden problem

```javascript
import { createServer } from 'node:http';
import { parse } from 'node:url';
import NextServer from 'next/dist/server/next-server';
// @ts-ignore
import { config } from './.next/required-server-files.json';
import { NextConfig } from 'next';

const port = parseInt(process.env.PORT || '9000', 10);
const hostname = '0.0.0.0';
const dev = process.env.NODE_ENV !== 'production';

const app = new NextServer({
  hostname: 'localhost',
  port,
  dir: process.cwd(),
  dev,
  conf: {
    ...(config as NextConfig),
  },
});

const handle = app.getRequestHandler();

app.prepare().then(() => {
  createServer((req, res) => {
    try {
      const parsedUrl = parse(req.url!, true);
     handle(req, res, parsedUrl);
    } catch (err) {
      console.error('Error occurred handling', req.url, err);
      res.statusCode = 500;
      res.end('internal server error');
    }
  })
    .once('error', (err) => {
      logger.error(err);
      process.exit(1);
    })
    .listen(port, () => {
      console.log(
        `> Server listening at http://${hostname}:${port} as ${
          dev ? 'development' : process.env.NODE_ENV
        }`,
      );
    });
});
```

**Comment by hi-zp** [comment]
Here's my code, and while it works successfully, I'm not sure it's going to be a hidden problem

```javascript
import { createServer } from 'node:http';
import { parse } from 'node:url';
import NextServer from 'next/dist/server/next-server';
// @ts-ignore
import { config } from './.next/required-server-files.json';
import { NextConfig } from 'next';

const port = parseInt(process.env.PORT || '9000', 10);
const hostname = '0.0.0.0';
const dev = process.env.NODE_ENV !== 'production';

const app = new NextServer({
  hostname: 'localhost',
  port,
  dir: process.cwd(),
  dev,
  conf: {
    ...(config as NextConfig),
  },
});

const handle = app.getRequestHandler();

app.prepare().then(() => {
  createServer((req, res) => {
    try {
      const parsedUrl = parse(req.url!, true);
     handle(req, res, parsedUrl);
    } catch (err) {
      console.error('Error occurred handling', req.url, err);
      res.statusCode = 500;
      res.end('internal server error');
    }
  })
    .once('error', (err) => {
      logger.error(err);
      process.exit(1);
    })
    .listen(port, () => {
      console.log(
        `> Server listening at http://${hostname}:${port} as ${
          dev ? 'development' : process.env.NODE_ENV
        }`,
      );
    });
});
```

**Comment by wq93** [comment]
I've met, too, frustrating

```js
Node.js v18.20.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ NODE_ENV=production node ./server/main.js
node:internal/modules/cjs/loader:1140
  const err = new Error(message);
              ^

Error: Cannot find module './bundle5'
Require stack:
```

**Comment by yunsii** [comment]
Already 3 months passed, there is still no any progress? 🫠

**Comment by yunsii** [comment]
Even use v14.2.4 still has the same error...

**Comment by nectoscorp** [comment]
I confirmed that this works for me: https://github.com/vercel/next.js/issues/64031#issuecomment-2078708340
So AWS lambda, I am using the following to extract the JSON:
`sed -n 12p .next/standalone/server.js | cut -c 20-`

then put it as an environment variable named `__NEXT_PRIVATE_STANDALONE_CONFIG` to the lambda using `aws update-function-configuration`

**Comment by yunsii** [comment]
> I have same issue. And I found the server.js which compiled with standalone can works. So I just copy these 2lines, and my custom server.js also works fine.
> 
> ```
> const nextConfig = {which from compiled server.js}
> process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(nextConfig)
> ```

Thanks @nectoscorp 

After I tested, it works 😂

**Comment by nectoscorp** [comment]
I the nextConfig json was just saved on a file in like `.next/standalone/next.config.json` so we don't have to resort to these hacks. But obviously, the best is solution is to find out why `bundle5` couldn't be found.

**Comment by Brandawg93** [comment]
Having the same issue. This seems to work well for me to allow for both local dev development and docker deployment: 

```typescript
const dev = process.env.NODE_ENV !== 'production'

if (!dev) {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { config } = require('./.next/required-server-files.json')
  process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(config)
}
```

**Comment by flawnn** [comment]
> Having the same issue. This seems to work well for me to allow for both local dev development and docker deployment:
> 
> ```ts
> const dev = process.env.NODE_ENV !== 'production'
> 
> if (!dev) {
>   // eslint-disable-next-line @typescript-eslint/no-require-imports
>   const { config } = require('./.next/required-server-files.json')
>   process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(config)
> }
> ```

The ES6-conform version:

```
import("./.next/required-server-files.json")
        .then(({ default: { config } }) => {
        process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(config);
        const app = next({ dev });
        return app.prepare().then(() => startServer(app) // startup func);
    })
        .catch((error) => {
        console.error("Failed to load required-server-files.json:", error);
        process.exit(1);
    });
```

**Comment by SujithPriyamRajan** [comment]
I have the same issue but surprisingly in PM2 as local & VM's was working fine 

Can anyone summarize why this issue is ??
```
/** @type {import('next').NextConfig} */

const nextConfig = {
    output: 'standalone',
    typescript: {
        ignoreBuildErrors: true
    },
    images: { unoptimized: true },
    experimental: {
        serverActions: {
            serverActions: true
        },
        missingSuspenseWithCSRBailout: false
    },
    distDir: 'out',
    rewrites: async () => {
        return [
            {
                source: '/_next/static/:path*',
                destination: '/static/:path*'
            }
        ];
    }
};
export default nextConfig;

```

**Comment by aczekajski** [comment]
I found a universal way if adding missing dependencies to standalone output that I guess can also be used for custom server.

You can have a look here:
https://github.com/vercel/next.js/discussions/66327#discussioncomment-10889930

**Comment by MJez29** [comment]
I also ran into this issue and came up with the exact same fix

I put up a PR to fix this in next.js: https://github.com/vercel/next.js/pull/72966

**Comment by oldium** [comment]
I am deploying the generated `server.js` and reading it from my code, so that I do not need to manually copy the line:

```ts
const dev = process.env.NODE_ENV !== 'production';
if (!dev) {
    const serverJs = readFileSync("./server.js").toString("utf-8");
    const lines = serverJs.split(/\r?\n/);
    const index = lines.findIndex((line: string) => line.startsWith("const nextConfig"));
    const start = lines[index].indexOf("{");
    process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = lines[index].substring(start);
}
```

Reading `./.next/required-server-files.json` does not work for me...

**Comment by SollyTheCoder** [comment]
> I have same issue. And I found the server.js which compiled with standalone can works. So I just copy these 2lines, and my custom server.js also works fine.
> 
> ```
> const nextConfig = {which from compiled server.js}
> process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(nextConfig)
> ```

@clementzhao I don't understand, where are you putting these lines? Please could you show your working example?

**Comment by clementzhao** [comment]
> > I have same issue. And I found the server.js which compiled with standalone can works. So I just copy these 2lines, and my custom server.js also works fine.
> > ```
> > const nextConfig = {which from compiled server.js}
> > process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(nextConfig)
> > ```
> 
> [@clementzhao](https://github.com/clementzhao) I don't understand, where are you putting these lines? Please could you show your working example?

in your custom js file, such as server.js.

**Comment by marcoshernanz** [comment]
Thanks for the report. I confirmed the reproduction, but this combines two modes that are not supported together. `output: 'standalone'` traces the generated `.next/standalone/server.js`, not a custom server, as documented in the [custom server guide](https://nextjs.org/docs/app/guides/custom-server). We explored support in #72966, but reverted it in #73003. Please use the generated standalone server, or remove `output: 'standalone'` when using a custom server. Closing as not planned.

**Comment by oldium** [comment]
@marcoshernanz Sorry, maybe I am missing something, please correct me if I am wrong:

1. The [example](https://github.com/vercel/next.js/tree/canary/examples/custom-server) you are linking is very basic and is completely ignoring the production build usable for Docker deployments for example.
2. The `standalone` output is explicitly [recommended](https://nextjs.org/docs/pages/api-reference/config/next-config-js/output#automatically-copying-traced-files) for production deployments.
3. [Best practices](https://nextjs.org/docs/pages/getting-started/deploying#templates-1) for deploying with Docker mention standalone mode as well.
4. The custom server [documentation](https://nextjs.org/docs/app/guides/custom-server) explicitly mentions standalone output mode cannot be used together:
   > When using standalone output mode, it does not trace custom server files. This mode outputs a separate minimal server.js file, instead. These cannot be used together.

I really do not understand the recommendations for the production build. Do you have any example for the production build with custom server, please? Other than copying the whole `.next` directory including all the build caches into production of course, which is a really dumb idea per se...

Update: added best practices link, reworded
