### ISSUE TITLE
Error: Collecting page data for undefined is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout -- 21:32:45.793 | at onRestart #64216

### ISSUE THREAD

**Issue by SH20RAJ** [vercel/next.js#64235]
### Link to the code that reproduces this issue

https://github.com/SH20RAJ/shadev2/tree/dev

### To Reproduce

Error: Collecting page data for undefined is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout -- 21:32:45.793 | at onRestart #64216

### Current vs. Expected behavior

I am deploying my git repo to vercel and seeing this error

My Repo :- https://github.com/SH20RAJ/shadev2/tree/dev

Whats the problem how to fix it and deploy my website online.

PS: My Website is properly working on localhost and GitHub Codespaces

Error: Collecting page data for undefined is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout -- 21:32:45.793 | at onRestart (/vercel/path0/node_modules/next/dist/build/index.js:303:27) 21:32:45.794 | at Worker.isPageStatic (/vercel/path0/node_modules/next/dist/lib/worker.js:95:40) 21:32:45.794 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 21:32:45.794 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:151:20) 21:32:45.794 | at async /vercel/path0/node_modules/next/dist/build/index.js:1047:56 21:32:45.794 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:151:20) 21:32:45.795 | at async Promise.all (index 3) 21:32:45.795 | at async /vercel/path0/node_modules/next/dist/build/index.js:979:17 21:32:45.795 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:151:20)

### Provide environment information

```bash
I'm deploying on vercel
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

I am deploying my git repo to vercel and seeing this error

My Repo :- https://github.com/SH20RAJ/shadev2/tree/dev

Whats the problem how to fix it and deploy my website online.

PS: My Website is properly working on localhost and GitHub Codespaces

Error: Collecting page data for undefined is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout -- 21:32:45.793 | at onRestart (/vercel/path0/node_modules/next/dist/build/index.js:303:27) 21:32:45.794 | at Worker.isPageStatic (/vercel/path0/node_modules/next/dist/lib/worker.js:95:40) 21:32:45.794 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 21:32:45.794 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:151:20) 21:32:45.794 | at async /vercel/path0/node_modules/next/dist/build/index.js:1047:56 21:32:45.794 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:151:20) 21:32:45.795 | at async Promise.all (index 3) 21:32:45.795 | at async /vercel/path0/node_modules/next/dist/build/index.js:979:17 21:32:45.795 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:151:20)

**Comment by SH20RAJ** [comment]
> Build error occurred
Error: Collecting page data for undefined is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
    at onRestart (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:303:27)
    at Worker.isPageStatic (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/lib/worker.js:95:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/trace/trace.js:151:20)
    at async /Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:1047:56
    at async Span.traceAsyncFn (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/trace/trace.js:151:20)
    at async Promise.all (index 14)
    at async /Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:979:17
    at async Span.traceAsyncFn (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/trace/trace.js:151:20)
    at async /Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:916:124
   Collecting page data  .%                                                                                                                                            
shaswatraj@Sh shade %

**Comment by SH20RAJ** [comment]
shaswatraj@Sh shade % npm run build

> shade@0.1.0 build
> npx prisma generate && next build

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.12.1) to ./node_modules/@prisma/client in 88ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

┌────────────────────────────────────────────────────────────────┐
│  Supercharge your Prisma Client with global database caching,  │
│  scalable connection pooling and real-time database events.    │
│  Explore Prisma Accelerate: https://pris.ly/cli/-accelerate    │
│  Explore Prisma Pulse: https://pris.ly/cli/-pulse              │
└────────────────────────────────────────────────────────────────┘

   ▲ Next.js 14.1.4
   - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ⚠ Sending SIGTERM signal to static worker due to timeout of 2 seconds. Subsequent errors may be a result of the worker exiting.
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Restarted collecting page data for undefined because it took more than 2 seconds
 ⚠ Sending SIGTERM signal to static worker due to timeout of 2 seconds. Subsequent errors may be a result of the worker exiting.

> Build error occurred
Error: Collecting page data for undefined is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
    at onRestart (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:303:27)
    at Worker.isPageStatic (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/lib/worker.js:95:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/trace/trace.js:151:20)
    at async /Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:1047:56
    at async Span.traceAsyncFn (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/trace/trace.js:151:20)
    at async Promise.all (index 14)
    at async /Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:979:17
    at async Span.traceAsyncFn (/Users/shaswatraj/Desktop/shade/node_modules/next/dist/trace/trace.js:151:20)
    at async /Users/shaswatraj/Desktop/shade/node_modules/next/dist/build/index.js:916:124
   Collecting page data  .%                                                                                                                                            
shaswatraj@Sh shade %
