### ISSUE TITLE
nextjs 14.2 app-router Cookie not being set after version upgrade from v14.0.4 to 14.2

### ISSUE THREAD

**Issue by manacy-keyvalue** [vercel/next.js#64394]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/naughty-sinoussi-2cz5ks?file=%2Fpages%2Findex.tsx%3A3%2C15

### To Reproduce

1. Run `next dev`
2. Try to login
3. Cookie is not being set correctly in the browser.
4. There is an error in terminal which could be related or not.

### Current vs. Expected behavior

Current behaviour:
Cookie is not being set and not able to proceed further.

Expected behaviour:
Cookie should be set correctly in the browser.
It was working correctly if i revert back to the previous version. v14.0.4

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 20.11.0
  npm: 10.4.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: 14.2.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Running next dev is showing some error: terminal output =>

Something went wrong : Error: Cannot find module './_next.json'
    at /Users/manacy/Desktop/projects/AM-I/crm-web/.next/server/app/[locale]/[...rest]/page.js:34:12
    at async RootLayout (webpack-internal:///(rsc)/./src/app/[locale]/layout.tsx:27:21) {
  code: 'MODULE_NOT_FOUND'
}
Something went wrong : Error: Cannot find module './_next.json'
    at /Users/manacy/Desktop/projects/AM-I/crm-web/.next/server/app/[locale]/[...rest]/page.js:34:12
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async RootLayout (webpack-internal:///(rsc)/./src/app/[locale]/layout.tsx:27:21) {
  code: 'MODULE_NOT_FOUND'
}
Something went wrong : Error: Cannot find module './_next.json'
    at /Users/manacy/Desktop/projects/AM-I/crm-web/.next/server/app/[locale]/[...rest]/page.js:34:12
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async RootLayout (webpack-internal:///(rsc)/./src/app/[locale]/layout.tsx:27:21) {
  code: 'MODULE_NOT_FOUND'
}
 GET /_next/static/css/ReactToastify.css.map 404 in 1902ms
 GET /_next/static/chunks/app/%5Blocale%5D/react-toastify.esm.mjs.map 404 in 1969ms
 GET /_next/static/chunks/app/%5Blocale%5D/(login)/login/react-toastify.esm.mjs.map 404 in 2026ms
 
 
 
 Curl of the login request:
 curl 'http://localhost:3000/login?redirectUrl=http%3A%2F%2Flocalhost%3A3000%2F' \
  -H 'Accept: text/x-component' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  -H 'Cookie: NEXT_LOCALE=en' \
  -H 'Next-Action: 938e94949223fe0e09dbc7285856db0423a615c1' \
  -H 'Next-Router-State-Tree: %5B%22%22%2C%7B%22children%22%3A%5B%5B%22locale%22%2C%22en%22%2C%22d%22%5D%2C%7B%22children%22%3A%5B%22(login)%22%2C%7B%22children%22%3A%5B%22login%22%2C%7B%22children%22%3A%5B%22__PAGE__%3F%7B%5C%22redirectUrl%5C%22%3A%5C%22http%3A%2F%2Flocalhost%3A3000%2F%5C%22%7D%22%2C%7B%7D%2C%22%2Flogin%3FredirectUrl%3Dhttp%253A%252F%252Flocalhost%253A3000%252F%22%2C%22refresh%22%5D%7D%5D%7D%5D%7D%2Cnull%2Cnull%2Ctrue%5D%7D%5D' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/login?redirectUrl=http%3A%2F%2Flocalhost%3A3000%2F' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw $'[{"email":"jdols","password":"DennisDoetMoeilijk\u0021"}]'

**Comment by timneutkens** [comment]
The sandbox shared does not have any additional code in it, please share a full reproduction

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
