### ISSUE TITLE
Next v14.2 cause errors on build

### ISSUE THREAD

**Issue by marijaduvnjak** [vercel/next.js#64403]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/next-v14-2-build-not-work-mnn3z8

### To Reproduce

Start the application for creating build `npm run build`. The build fails with the following errors:
![image](https://github.com/vercel/next.js/assets/100783701/40b1b69a-f4ac-402b-9abb-bb14f5e0c719)

(in codesandbox just open `build` tab to see an error)

### Current vs. Expected behavior

I'm expecting building app without any errors, as it was the case on nextjs v14.1.4

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #202403110203~1711393930~22.04~331756a SMP PREEMPT_DYNAMIC Mon M
  Available memory (MB): 15699
  Available CPU cores: 8
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: 14.2.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Standalone mode (output: "standalone")

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

If I try to run `npm run build` on `nextjs v14.1.4`, it successfully builds the application.

**Comment by coltonehrman** [comment]
@marijaduvnjak You should be able to fix this by using the [serverComponentsExternalPackages](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages). 

Example:
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  poweredByHeader: false,
  output: "standalone",
  experimental: {
    instrumentationHook: true,
    serverComponentsExternalPackages: ["dd-trace"],
  },
  devIndicators: {
    buildActivity: false,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
};
```

**Comment by FahimFBA** [comment]
I was facing the same issue. Came to know from Reddit that a specific PR is waiting to fix this issue.

**Comment by drobannx** [comment]
Coming from a related issue, adding "dd-trace" fixed the issue for me. 

When I run `next dev --turbo`, I get the error even with `dd-trace` added to `serverComponentsExternalPackages`

**Comment by timneutkens** [comment]
Seems something related to how `dd-trace` is now being bundled in `instrumentation.ts`. I haven't worked on that part of Next.js personally but will raise it to the right people 👍

**Comment by FahimFBA** [comment]
It is working now!
![image](https://github.com/vercel/next.js/assets/64195132/cf5e6249-3e6e-4c82-89c0-b3198cb0b2e4)

**Comment by moinulmoin** [comment]
`❯ nr
✔ script to run › build
> project-name@0.1.0 build /path/to/project
> next build
  ▲ Next.js 14.2.1
  - Environments: .env
   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (5/14)  [=   ]Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61599)
    at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
    at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
    at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560)
    at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538) {
  digest: '839973123'
}
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61599)
    at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
    at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
    at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560)
    at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
 ✓ Generating static pages (14/14)
> Export encountered errors on following paths:
        /page: /
 ELIFECYCLE  Command failed with exit code 1.`
 
 getting this error on build in >= v14.2
 
 working fine in < v14.2

**Comment by marijaduvnjak** [comment]
> @marijaduvnjak You should be able to fix this by using the [serverComponentsExternalPackages](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages).
> 
> Example:
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   poweredByHeader: false,
>   output: "standalone",
>   experimental: {
>     instrumentationHook: true,
>     serverComponentsExternalPackages: ["dd-trace"],
>   },
>   devIndicators: {
>     buildActivity: false,
>   },
>   eslint: {
>     ignoreDuringBuilds: true,
>   },
> };
> ```

thanks, it works like a charm! 😃 

just for curiosity: why do we need to add now _dd-trace_ in _serverComponentsExternalPackages_? is there any change from changelogs in v14.2 that pointed out that we need to be aware of doing this change (and I overlooked it somehow 😅)?

**Comment by marijaduvnjak** [comment]
> `❯ nr ✔ script to run › build
> 
> > project-name@0.1.0 build /path/to/project
> > next build
> > ▲ Next.js 14.2.1
> 
> * Environments: .env
>   Creating an optimized production build ...
>   ✓ Compiled successfully
>   ✓ Linting and checking validity of types
>   ✓ Collecting page data
>   Generating static pages (5/14)  [=   ]Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
>   at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61599)
>   at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
>   at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
>   at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
>   at nD (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
>   at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
>   at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
>   at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560)
>   at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
>   at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
>   at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538) {
>   digest: '839973123'
>   }
>   Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
>   Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
>   at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61599)
>   at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
>   at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
>   at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
>   at nD (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
>   at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
>   at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
>   at nM (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560)
>   at nN (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
>   at nB (/path/to/project/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
>   ✓ Generating static pages (14/14)
> 
> > Export encountered errors on following paths:
> > /page: /
> > ELIFECYCLE  Command failed with exit code 1.`
> 
> getting this error on build in >= v14.2
> 
> working fine in < v14.2

maybe it's related to this issue: https://github.com/vercel/next.js/issues/64369#issuecomment-2051915286
