### ISSUE TITLE
14.2.1 turbo fails to compile with tailwindcss plugin (iconify)

### ISSUE THREAD

**Issue by SimHoZebs** [vercel/next.js#64423]
### Link to the code that reproduces this issue

[Codesandbox](https://codesandbox.io/p/devbox/dank-browser-kwxl7w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clux77gug0007356r5a2ql70u%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clux77guf0002356re5tc68qn%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clux77guf0004356rw3m2vzrk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clux77gug0006356rnl506jmb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clux77guf0002356re5tc68qn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clux77guf0001356rex8xu0os%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clux78kwe005a356rou0m7iyl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clux77guf0002356re5tc68qn%2522%252C%2522activeTabId%2522%253A%2522clux78kwe005a356rou0m7iyl%2522%257D%252C%2522clux77gug0006356rnl506jmb%2522%253A%257B%2522id%2522%253A%2522clux77gug0006356rnl506jmb%2522%252C%2522activeTabId%2522%253A%2522clux7p98p00pp356rqbild5yl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clux7p98p00pp356rqbild5yl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clux77guf0004356rw3m2vzrk%2522%253A%257B%2522id%2522%253A%2522clux77guf0004356rw3m2vzrk%2522%252C%2522activeTabId%2522%253A%2522clux7urob018v356rrfosn3w7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clux7kbxp00iq356rid50eamd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clux7kfje000ddkim9ene3rot%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clux7urob018v356rrfosn3w7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

1. Set up tailwind and import its CSS file to `layout.tsx`
2. Install `@iconify/tailwind` as dev dependency
3. Enable the plugin by editing `tailwind.config.ts` as follows:
```ts
import { addDynamicIconSelectors } from "@iconify/tailwind";
import type { Config } from "tailwindcss";

const config: Config = {
	content: [
		"./pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./components/**/*.{js,ts,jsx,tsx,mdx}",
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			backgroundImage: {
				"gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
				"gradient-conic":
					"conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
			},
		},
	},
	plugins: [addDynamicIconSelectors()],
};
export default config;
```
4. run `next dev --turbo`

### Current vs. Expected behavior

Expected: Compiles normally.

Current: Does not compile and outputs the following message:
```
 ✓ Compiled / in 1688ms
 ⨯ ModuleBuildError: ./node_modules/@iconify/tailwind/dist/plugin.js
Module not found


https://nextjs.org/docs/messages/module-not-found


    at processIssues (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\dev\turbopack-utils.js:229:15)
    at handleRouteType (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\dev\turbopack-utils.js:386:17)
    at async Object.ensurePage (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\dev\hot-reloader-turbopack.js:644:17)
    at async DevBundlerService.ensurePage (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\lib\dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\dev\next-dev-server.js:551:9)
    at async Object.ensure (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\dev\next-dev-server.js:169:17)
    at async DevRouteMatcherManager.matchAll (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\future\route-matcher-managers\dev-route-matcher-manager.js:96:13)
    at async DevRouteMatcherManager.match (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\future\route-matcher-managers\default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\next-server.js:228:31)
    at async DevServer.handleRequestImpl (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\base-server.js:811:17)
    at async C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\simho\Projects\iconify-test\node_modules\next\dist\server\lib\start-server.js:141:13)
 ✓ Compiled /_error in 481ms
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The project compiles when not using turbo. Does not have issues running with turbo on 14.1.4.

<sub>[PACK-2952](https://linear.app/vercel/issue/PACK-2952/1421-turbo-fails-to-compile-with-tailwindcss-plugin-iconify)</sub>

**Comment by kkfive** [comment]
same issue
