### ISSUE TITLE
Can't build project - TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by Zweird-958** [vercel/next.js#65413]
### Link to the code that reproduces this issue

https://github.com/Zweird-958/my-wishlist

### To Reproduce

1. Clone this [repo](https://github.com/Zweird-958/my-wishlist)
2. Do a `cd apps/web`
3. Do a `bun run build`

### Current vs. Expected behavior

Should build successfully

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.21
  pnpm: 9.0.6
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### Additional context

I have no error with a `next dev` but `next build` don't work.
I'm using `bun` and also it's a monorepo.
I tried to delete all my pages and get only one `page.tsx` but I have the same error.

Error:

```
 Generating static pages (0/5)  [    ]TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/julien/code/my-wishlist/apps/web/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/julien/code/my-wishlist/apps/web/.next/server/pages/_error.js:1:5995)
    at Wc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/julien/code/my-wishlist/apps/web/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/julien/code/my-wishlist/apps/web/.next/server/pages/_error.js:1:5995)
    at Wc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/julien/code/my-wishlist/apps/web/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/julien/code/my-wishlist/apps/web/.next/server/pages/_error.js:1:5995)
    at Wc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/julien/code/my-wishlist/apps/web/node_modules/react/cjs/react.production.min.js:24:495)
    at h (/Users/julien/code/my-wishlist/apps/web/.next/server/pages/_error.js:1:5995)
    at Wc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/julien/code/my-wishlist/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
 ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
        /_error: /404
        /_error: /500
error: script "build" exited with code 1
```

**Comment by icyJoseph** [comment]
Have you tried removing the toaster from the layout?

**Comment by Zweird-958** [comment]
> Have you tried removing the toaster from the layout?

Yes, I also try to remove all pages, and create one with only `<p>test</p>` and remove all `Providers` and `Toaster` in my `layout.tsx`

**Comment by JoseSanchez54** [comment]
I have the same error, in next 14.1.0 all works but when I upgrade next version to 14.2.3 start the error (Only in vercel and npm run build)

**Comment by Zweird-958** [comment]
> I have the same error, in next 14.1.0 all works but when I upgrade next version to 14.2.3 start the error (Only in vercel and npm run build)

I tried to downgrade to `14.1.0` but I have always the same error.

**Comment by przpl** [comment]
I had a similar error. I fixed it by recreating `package-lock.json` file. Remove `node_modules` directory and `package-lock.json` file and install packages `npm i`.

**Comment by Zweird-958** [comment]
> I had a similar error. I fixed it by recreating `package-lock.json` file. Remove `node_modules` directory and `package-lock.json` file and install packages `npm i`.

I don't know why now it worked whereas I already tried this.
Thank you so much @przpl 🙏
