### ISSUE TITLE
next build throws `Error: <Html> should not be imported outside of _document` after 1 month, and no changes made to the code or build environment

### ISSUE THREAD

**Issue by vemonet** [vercel/next.js#65780]
### Link to the code that reproduces this issue

https://github.com/MaastrichtU-IDS/cohort-explorer

### To Reproduce

```bash
git clone https://github.com/MaastrichtU-IDS/cohort-explorer
cd cohort-explorer
docker compose up
```

### Current vs. Expected behavior

One month ago the exact same build was working. As proof it is deployed here: https://explorer.icare4cvd.eu

We can see the last commit the 12th of april, it was building without issues at this time: https://github.com/MaastrichtU-IDS/cohort-explorer/commits/main/ since the last successful build there was just 1 line changed in the python backend, nothing changed in the nextjs frontend

We use docker for reproducibility, and we commit and use the pnpm lock file also for reproducibility (to avoid this kind of bad surprise)

But now when we try to build the image, even if absolutely no changes has been made since the last successful build we get this error:

```
39.10  ✓ Compiled successfully
39.11    Collecting page data ...
39.46    Generating static pages (0/6) ...
39.56 Error: <Html> should not be imported outside of pages/_document.
39.56 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.56     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.56     at y (/app/.next/server/chunks/319.js:6:1299)
39.56     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.56
39.56 Error occurred prerendering page "/cohorts". Read more: https://nextjs.org/docs/messages/prerender-error
39.56 Error: <Html> should not be imported outside of pages/_document.
39.56 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.56     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.56     at y (/app/.next/server/chunks/319.js:6:1299)
39.56     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
   Generating static pages (1/6)
39.56 Error: <Html> should not be imported outside of pages/_document.
39.56 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.56     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.56     at y (/app/.next/server/chunks/319.js:6:1299)
39.56     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.56
39.56 Error occurred prerendering page "/upload". Read more: https://nextjs.org/docs/messages/prerender-error
39.56 Error: <Html> should not be imported outside of pages/_document.
39.56 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.56     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.56     at y (/app/.next/server/chunks/319.js:6:1299)
39.56     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.56     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.56     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
   Generating static pages (2/6)
39.57 Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
39.57     at p (/app/.next/server/pages/cohorts/[cohortId].js:1:17520)
39.57     at g (/app/.next/server/pages/cohorts/[cohortId].js:1:1016)
39.57     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.57     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.57     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.57     at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
39.57     at bd (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
39.57     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
39.57     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.57     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.57
39.57 Error occurred prerendering page "/cohorts/[cohortId]". Read more: https://nextjs.org/docs/messages/prerender-error
39.57 Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
39.57     at p (/app/.next/server/pages/cohorts/[cohortId].js:1:17520)
39.57     at g (/app/.next/server/pages/cohorts/[cohortId].js:1:1016)
39.57     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.57     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.57     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.57     at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
39.57     at bd (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
39.57     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
39.57     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.57     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63 Error: <Html> should not be imported outside of pages/_document.
39.63 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.63     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.63     at y (/app/.next/server/chunks/319.js:6:1299)
39.63     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63
39.63 Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
39.63 Error: <Html> should not be imported outside of pages/_document.
39.63 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.63     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.63     at y (/app/.next/server/chunks/319.js:6:1299)
39.63     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63 Error: <Html> should not be imported outside of pages/_document.
39.63 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.63     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.63     at y (/app/.next/server/chunks/319.js:6:1299)
39.63     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63
39.63 Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
39.63 Error: <Html> should not be imported outside of pages/_document.
39.63 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.63     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.63     at y (/app/.next/server/chunks/319.js:6:1299)
39.63     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
   Generating static pages (4/6)
39.63 Error: <Html> should not be imported outside of pages/_document.
39.63 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.63     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.63     at y (/app/.next/server/chunks/319.js:6:1299)
39.63     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63
39.63 Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
39.63 Error: <Html> should not be imported outside of pages/_document.
39.63 Read more: https://nextjs.org/docs/messages/no-document-import-in-page
39.63     at ed (/app/node_modules/.pnpm/next@14.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5484)
39.63     at y (/app/.next/server/chunks/319.js:6:1299)
39.63     at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
39.63     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
39.63     at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
 ✓ Generating static pages (6/6)
39.64
39.64 > Export encountered errors on following paths:
39.64 	/
39.64 	/_error: /404
39.64 	/_error: /500
39.64 	/cohorts
39.64 	/cohorts/[cohortId]
39.64 	/upload
39.66  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: process "/bin/sh -c pnpm build" did not complete successfully: exit code: 1
```

When running locally with `pnpm dev` we don't have this error, so it is really hard to debug

It seems it could be related to this issue: https://github.com/vercel/next.js/issues/56481

We are using the **exact same nodejs version, same docker image, same locked npm dependencies**, so it is really surprising and concerning that `next build` is not stable and not reproducible with all this care put into having a reproducible environment

The error thrown `<Html> should not be imported outside of pages/_document.` does not seems to be the actual error since we only use the `<Html>` tag in document. And as said previously, the same code was building, so there is no reason it stops being valid all of a sudden

What are we doing wrong? Why is `next build` not reproducible within the exact same environment with the exact same code after 1 month passed?

### Provide environment information

```bash
I can't run `next info` because it is running inside a docker container. The docker image itself is deployed on a CentOS 7.

We use `node:20-slim` as base image with `pnpm` installed inside

Dockerfile is: https://github.com/MaastrichtU-IDS/cohort-explorer/blob/main/frontend/Dockerfile
```

### Which area(s) are affected? (Select all that apply)

Pages Router

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by vemonet** [comment]
Updating the dependencies with `pnpm up --latest` fixed the issue...

Still puzzling that the exact same dependencies version in the exact same environment fails after few days passed...
