### ISSUE TITLE
testProxy breaks next/font

### ISSUE THREAD

**Issue by jacenre** [vercel/next.js#66238]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/vibrant-cdn-82zfp4

### To Reproduce

1. Add a font like IBM Plex Mono from `next/font` to a component (this works)
2. Set experimental option `testProxy` to true in next.config.js

### Current vs. Expected behavior

The text is supposed to be rendered in IBM Plex Mono. Instead, next/font was unable to load the font from Google due to an "invalid header check".

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.3.0-canary.84 // Latest available version is detected (14.3.0-canary.84).
  eslint-config-next: N/A
  react: 19.0.0-beta-04b058868c-20240508
  react-dom: 19.0.0-beta-04b058868c-20240508
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Font (next/font), Testing

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

It seems to occur ever since the canary version appears where `testProxy` was released in `14.2.0-canary.36`. Before that, it was an command line flag `--experimental-test-proxy` where likely the issue also already occured.

**Comment by peguerosdc** [comment]
Hi! It's also happens to me. I checked you sandbox and we are getting the same error:

```
 ✓ Starting...
 ✓ Ready in 3.5s
 ○ Compiling / ...
 ✓ Compiled / in 1716ms (523 modules)
 GET / 200 in 2149ms
 ✓ Compiled in 281ms (250 modules)
(node:24065) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap: incorrect header check

Retrying 1/3...
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap: incorrect header check

Retrying 2/3...
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap: incorrect header check

Retrying 3/3...
FetchError: Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap: incorrect header check
    at Gunzip.<anonymous> (/Users/user/dev/my-app/node_modules/next/dist/compiled/node-fetch/index.js:1:53082)
    at Gunzip.emit (node:events:532:35)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'Z_DATA_ERROR',
  code: 'Z_DATA_ERROR'
}
 ⨯ Failed to download `Inter` from Google Fonts. Using fallback font instead.
```

I don't know if there is a cache mechanism in NextJS or something like that, but if I remove the `testProxy` flag, I start the server and access the site, then add the `testProxy`  flag again... now the error becomes intermittent.

Moreover, it's affecting the behavior of `display: "swap"` because sometimes the font loads and sometimes it doesn't load if I include it. If I remove it, it always loads. Very weird.

**Comment by Sephster** [comment]
Also can confirm this is affecting my build

**Comment by joafeldmann** [comment]
Same issue here with 14.2.5

```bash
 ▲ Next.js 14.2.5
  - Local:        http://localhost:4000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 2.7s
 ✓ Compiled /src/middleware in 391ms (189 modules)
 ○ Compiling /[locale]/cms/[...slug] ...
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap: incorrect header check

Retrying 1/3...
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap: incorrect header check

Retrying 2/3...
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap: incorrect header check

Retrying 3/3...
FetchError: Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap: incorrect header check
    at Gunzip.<anonymous> (/Users/***/.pnpm/next@14.2.5_@babel+core@7.24.9_@playwright+test@1.45.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/node-fetch/index.js:1:53082)
    at Gunzip.emit (node:events:530:35)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'Z_DATA_ERROR',
  code: 'Z_DATA_ERROR'
}
 ⨯ Failed to download `Open Sans` from Google Fonts. Using fallback font instead.

Failed to fetch `Open Sans` from Google Fonts.}
```

**Comment by 9sako6** [comment]
Same with 14.2.7 and testProxy

**Comment by ngittlen** [comment]
Happening to me too with 14.2.11

**Comment by matthewwyndham** [comment]
I also have an issue connecting to google big query while experimental.testProxy is true, switching to false allows the connection as normal.

**Comment by alivault** [comment]
Same here, on 14.2.3, while `experimental.testProxy` is true, Google Fonts fail to load in the dev server with error `Invalid response body while trying to fetch`

**Comment by moshie** [comment]
Been getting a similar issue as well when using the testProxy & msw in next v15.

I am mocking an axios graphQL query from the server and getting this error:

```
error: {
  "prototype": "AxiosError",
  "message": "incorrect header check",
  "code": "Z_DATA_ERROR",
  "type": "Response",
  "name": "Error",
  "cause": {
    "errno": -3,
    "code": "Z_DATA_ERROR"
  },
  "stack":
      Error: incorrect header check
          at AxiosError.from (file:///Users/.../node_modules/.pnpm/axios@1.7.9/node_modules/axios/lib/core/AxiosError.js:92:14)
          at Unzip.handleStreamError (file:///Users/.../node_modules/.pnpm/axios@1.7.9/node_modules/axios/lib/adapters/http.js:583:29)
          at Unzip.emit (node:events:536:35)
          at emitErrorNT (node:internal/streams/destroy:170:8)
          at emitErrorCloseNT (node:internal/streams/destroy:129:3)
          at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
}
```

Seems like something is going on with the compression?

**Comment by jordisala1991** [comment]
Does someone have a workaround for this issue? At the moment the only one I can think is disabling this for the normal dev env and only enabling it on the e2e tests, but that's not ideal.

**Comment by Sephster** [comment]
> Does someone have a workaround for this issue? At the moment the only one I can think is disabling this for the normal dev env and only enabling it on the e2e tests, but that's not ideal.

I do this:

```
export default (phase, { defaultConfig }) => {
    if (phase === PHASE_DEVELOPMENT_SERVER) {
        return {
            experimental: {
                testProxy: true,
            },
            ...nextConfig,
        }
    }

    return {
        ...nextConfig,
    }
}
```

**Comment by AsfalothDE** [comment]
We are facing the same issue when rewriting a search api path in next.js config. It somehow has to do with the compression.

This is the relevant config part:
```
async rewrites() {
        return [
            {
                source: '/api/search/:path*',
                destination: 'https://www.vodafone.de/api/search/:path*',
            },
        ];
    },
```

Our workaround right now is to add a middleware to rewrite the accept-encoding header:
```javascript
export function middleware(request: NextRequest) {
    if (request.nextUrl.pathname.startsWith('/api/search')) {
        const requestHeaders = new Headers(request.headers);
        requestHeaders.set('accept-encoding', 'identity');

        return NextResponse.next({
            request: {
                headers: requestHeaders,
            },
        });
    }
}

export const config = {
    matcher: '/api/search/:path*',
};
```
This works for us, but it's of course just a workaround (and not a very nice one) and not a solution. It would be great if this could be fixed in the `testProxy` implementation. For us, `testProxy` was the only working solution to mock server-side requests in playwright, so we are dependent on this.

**Comment by marcoshernanz** [comment]
Closing as fixed. I reproduced the `incorrect header check` failure on 15.1.11, but it no longer reproduces on 15.2.0 after #75741 removed the `next/font` `node-fetch` path. I also verified IBM Plex Mono with `experimental.testProxy: true` on 16.4.0-canary.0 using both Turbopack and Webpack. Broader `testProxy` transport issues are tracked separately in #96521 and #82913.
