### ISSUE TITLE
Next Build fails with Turborepo v2 and bun as package manarger

### ISSUE THREAD

**Issue by omarkhatibco** [vercel/next.js#66579]
### Link to the code that reproduces this issue

This repo is based on `create-turbo@latest` without any change.

https://github.com/omarkhatibco/test-turbo

### To Reproduce

Just run `bun run build`

### Current vs. Expected behavior

I'm getting error while building `/500` or `/400`, however I have no error template yet in my app 

here is the log 

```bash
  ▲ Next.js 15.0.0-rc.0
│
│    Creating an optimized production build ...
│  ✓ Compiled successfully
│  ✓ Linting and checking validity of types
│  ✓ Collecting page data
│    Generating static pages (0/5)  [    ]TypeError: Cannot read properties of null (reading 'useRef')
│     at exports.useRef (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/node_modules/react/cjs/react.production.js:520:33)
│     at eF (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:16942)
│     at renderWithHooks (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at finishFunctionComponent (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3968:7)
│
│ Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
│
│ TypeError: Cannot read properties of null (reading 'useRef')
│     at exports.useRef (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/node_modules/react/cjs/react.production.js:520:33)
│     at eF (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:16942)
│     at renderWithHooks (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at finishFunctionComponent (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3968:7)
│ TypeError: Cannot read properties of null (reading 'useRef')
│     at exports.useRef (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/node_modules/react/cjs/react.production.js:520:33)
│     at eF (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:16942)
│     at renderWithHooks (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at finishFunctionComponent (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3968:7)
│
│ Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
│
│ TypeError: Cannot read properties of null (reading 'useRef')
│     at exports.useRef (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/node_modules/react/cjs/react.production.js:520:33)
│     at eF (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:16942)
│     at renderWithHooks (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3927:18)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4086:17)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at renderElement (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4379:11)
│     at renderNodeDestructive (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:4616:16)
│     at finishFunctionComponent (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.js:3968:7)
│
│ > Build error occurred
│ Error: Export encountered an error on /404, exiting due to prerenderEarlyExit: true being set
│     at /Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/export/index.js:481:23
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at async Promise.all (index 0)
│     at async exportAppImpl (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/export/index.js:442:21)
│     at async /Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/export/index.js:625:16
│     at async Span.traceAsyncFn (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/trace/trace.js:157:20)
│     at async /Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/build/index.js:1690:42
│     at async Span.traceAsyncFn (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/trace/trace.js:157:20)
│     at async /Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/build/index.js:1548:17
│     at async Span.traceAsyncFn (/Users/omarkhatib/GitHub/test-turbo/node_modules/next/dist/trace/trace.js:157:20)
│    Generating static pages (0/5)  [    ]error: script "build" exited with code 1
│ command finished with error: command (/Users/omarkhatib/GitHub/test-turbo/apps/web) /Users/omarkhatib/.bun/bin/bun run build exited (1)
```

### Provide environment information

```bash
perating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 12
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.1.1
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 15.0.0-rc.0
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Webpack

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

I tested this on both nextjs v`15.0.0-rc.0` or `14.2.0` with Turborepo v`2` and bun v1.1.12 as a package manager

**Comment by omarkhatibco** [comment]
The error on `v13.2.3` are 


```bash

│    Creating an optimized production build ...
│  ✓ Compiled successfully
│  ✓ Linting and checking validity of types
│  ✓ Collecting page data
│    Generating static pages (0/5)  [    ]Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20
│ key%2C%20ref%2C%20props%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:490)
│     at Xc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:210)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at $c (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
│     at bd (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
│
│ Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
│
│ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%7D for the full
│ message or use the non-minified dev environment for full errors and additional helpful warnings.
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:490)
│     at Xc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:210)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at $c (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
│     at bd (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
│ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%7D for the full
│ message or use the non-minified dev environment for full errors and additional helpful warnings.
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:490)
│     at Xc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:210)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at $c (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
│     at bd (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
│
│ Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
│
│ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%7D for the full
│ message or use the non-minified dev environment for full errors and additional helpful warnings.
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:490)
│     at Xc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:409)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:210)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
│     at $c (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
│     at bd (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
│     at Z (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
│     at Zc (/Users/omarkhatib/GitHub/test-turbo/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
│  ✓ Generating static pages (5/5)
│
│ > Export encountered errors on following paths:
│         /_error: /404
│         /_error: /500
│ error: script "build" exited with code 1
│ command finished with error: command (/Users/omarkhatib/GitHub/test-turbo/apps/docs) /Users/omarkhatib/.bun/bin/bun run build exited (1)```
