### ISSUE TITLE
Getting error During Build

### ISSUE THREAD

**Issue by ravibhanawat** [vercel/next.js#66786]
### Link to the code that reproduces this issue

https://github.com/

### To Reproduce

Getting this error During Build Error: File /home/ravibhanawat/Documents/user/USER/.next/static/ssr/466.b8efe87bd4ec45af-b8efe87bd4ec45af-fed.js does not exist.
    at Job.emitDependency (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/compiled/@vercel/nft/index.js:1:39473)
    at async Promise.all (index 1)
    at async nodeFileTrace (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/compiled/@vercel/nft/index.js:1:35430)
    at async /home/ravibhanawat/Documents/user/USER/node_modules/next/dist/build/collect-build-traces.js:260:28
    at async Span.traceAsyncFn (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/trace/trace.js:105:20)
    at async collectBuildTraces (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/build/collect-build-traces.js:131:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Current vs. Expected behavior

using next 14 works fine and next 13 will getting error in build
Error: File /home/ravibhanawat/Documents/user/USER/.next/static/ssr/466.b8efe87bd4ec45af-b8efe87bd4ec45af-fed.js does not exist.
    at Job.emitDependency (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/compiled/@vercel/nft/index.js:1:39473)
    at async Promise.all (index 1)
    at async nodeFileTrace (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/compiled/@vercel/nft/index.js:1:35430)
    at async /home/ravibhanawat/Documents/user/USER/node_modules/next/dist/build/collect-build-traces.js:260:28
    at async Span.traceAsyncFn (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/trace/trace.js:105:20)
    at async collectBuildTraces (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/build/collect-build-traces.js:131:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
![Screenshot from 2024-06-12 11-12-37](https://github.com/vercel/next.js/assets/86184699/3d26ff11-380b-4b60-afd9-175852f96637)

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #202403110203~1714077665~22.04~4c8e9a0 SMP PREEMPT_DYNAMIC Thu A
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.8.0
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.2
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

Error: File /home/ravibhanawat/Documents/user/USER/.next/static/ssr/466.b8efe87bd4ec45af-b8efe87bd4ec45af-fed.js does not exist.
    at Job.emitDependency (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/compiled/@vercel/nft/index.js:1:39473)
    at async Promise.all (index 1)
    at async nodeFileTrace (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/compiled/@vercel/nft/index.js:1:35430)
    at async /home/ravibhanawat/Documents/user/USER/node_modules/next/dist/build/collect-build-traces.js:260:28
    at async Span.traceAsyncFn (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/trace/trace.js:105:20)
    at async collectBuildTraces (/home/ravibhanawat/Documents/user/USER/node_modules/next/dist/build/collect-build-traces.js:131:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ravibhanawat** [comment]
Issue is resolve using version down in next js

**Comment by ravibhanawat** [comment]
resolved
