### ISSUE TITLE
Suspense always suspend

### ISSUE THREAD

**Issue by jizhi0v0** [vercel/next.js#67374]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
Binaries:
  Node: 22.3.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.4.0
Relevant Packages:
  next: 15.0.0-canary.50 // Latest available version is detected (15.0.0-canary.50).
  eslint-config-next: 15.0.0-canary.44
  react: 19.0.0-rc-fb9a90fa48-20240614
  react-dom: 19.0.0-rc-fb9a90fa48-20240614
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-supabase

### What browser are you using? (if relevant)

Version 126.0.6478.127 (Official Build) (arm64)

### Describe the Bug

Suspense always suspend.

The layout send a promise to a EditorProvider then use "use hook" to reslove the promise.

I redirect to the page use Link component frome another component then i always saw the loading.

it works fine in next@rc

### Expected Behavior

Suspense should be resloved

### To Reproduce

![CleanShot 2024-07-02 at 17 19 10@2x](https://github.com/vercel/next.js/assets/57976101/84f78969-0001-4047-bfa4-f3fef78d7d40)
![CleanShot 2024-07-02 at 17 19 22@2x](https://github.com/vercel/next.js/assets/57976101/8f1a0491-f83a-4ddd-8a96-77a2e0c2d135)

**Comment by jizhi0v0** [comment]
After switch to rc version, there was a new bug.

`
 ⨯ Error: failed to pipe response
    at Z (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:470835)
    at async ee.pipeToNodeResponse (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:472283)
    at async sendRenderResult (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/send-payload.js:118:5)
    at async DevServer.pipeImpl (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/base-server.js:923:13)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/next-server.js:273:17)
    at async DevServer.handleRequestImpl (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/base-server.js:804:17)
    at async /Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/trace/trace.js:157:20)
    at async DevServer.handleRequest (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/lib/router-server.js:175:21)
    at async handleRequest (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/lib/router-server.js:354:24)
    at async requestHandlerImpl (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/lib/router-server.js:378:13)
    at async Server.requestListener (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/server/lib/start-server.js:142:13) {
  [cause]: TypeError: The encoded data was not valid for encoding utf-8
      at TextDecoder.decode (node:internal/encoding:448:14)
      at Object.pull (/Users/bobby/Documents/vscode/jizhi-blog/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:16585) {
    code: 'ERR_ENCODING_INVALID_ENCODED_DATA'
  }
}
`

**Comment by wyattjoh** [comment]
Can you elaborate on what you mean by:

> Suspense always suspend

If the promise is still in a pending state when it's passed down as a prop to the client component, it will suspend when called with `use` causing the fallback state to be shown at the suspense boundary.

**Comment by jizhi0v0** [comment]
[](url)> Can you elaborate on what you mean by:
> 
> > Suspense always suspend
> 
> If the promise is still in a pending state when it's passed down as a prop to the client component, it will suspend when called with `use` causing the fallback state to be shown at the suspense boundary.


https://github.com/vercel/next.js/assets/57976101/159366e3-41d3-4524-b6ed-51c9641f69b7


https://github.com/vercel/next.js/assets/57976101/fa19b93e-4f7b-4501-8d07-06912a48fecd

canary vs rc performance

**Comment by balazsorban44** [comment]
This issue has been automatically closed because it received no activity for a month and had no reproduction to investigate. If you think it was closed by accident, please leave a comment. If you are running into a similar issue, please open a new issue with a reproduction. Thank you.
