### ISSUE TITLE
nextjs panics on __nextFallback query param

### ISSUE THREAD

**Issue by andrei9669** [vercel/next.js#67657]
### Link to the code that reproduces this issue

https://github.com/andrei9669/nextjs-bug-reproduction

### To Reproduce

1. start application in dev mode
2. navigate to http://localhost:3000/ssr?__nextFallback=123

### Current vs. Expected behavior

currently, application returns 500 with following error logged on server side

Error: failed to pipe response
    at pipeToNodeResponse (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/pipe-readable.js:126:15)
    at RenderResult.pipeToNodeResponse (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/render-result.js:143:52)
    ... 11 lines matching cause stack trace ...
    at async Server.requestListener (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/lib/start-server.js:141:13) {
  [cause]: TypeError: Cannot read properties of undefined (reading 'pipeTo')
      at pipeToNodeResponse (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/pipe-readable.js:120:24)
      at RenderResult.pipeToNodeResponse (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/render-result.js:143:52)
      at sendRenderResult (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/send-payload.js:118:18)
      at DevServer.sendRenderResult (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/next-server.js:563:50)
      at DevServer.pipeImpl (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/base-server.js:935:24)
      at async NextNodeServer.handleCatchallRenderRequest (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/next-server.js:272:17)
      at async DevServer.handleRequestImpl (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/base-server.js:816:17)
      at async /Users/user/test_repos/reproduction-app/node_modules/next/dist/server/dev/next-dev-server.js:339:20
      at async Span.traceAsyncFn (/Users/user/test_repos/reproduction-app/node_modules/next/dist/trace/trace.js:154:20)
      at async DevServer.handleRequest (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
      at async invokeRender (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/lib/router-server.js:174:21)
      at async handleRequest (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/lib/router-server.js:353:24)
      at async requestHandlerImpl (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/lib/router-server.js:377:13)
      at async Server.requestListener (/Users/user/test_repos/reproduction-app/node_modules/next/dist/server/lib/start-server.js:141:13)

expected: no errors

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Pages Router, Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Other (Deployed)

### Additional context

went back to as far as next 11.1.4 and the bug is present there as well, not sure how far it goes

**Comment by marcoshernanz** [comment]
Closing as resolved by #74100, released in Next.js 15.2.0. I verified that `?__nextFallback=123` no longer changes Pages Router SSR behavior in 15.2.0, current stable, or canary, in either `next dev` or `next start`. If this still reproduces on a supported version, please open a new issue with an updated reproduction.
