### ISSUE TITLE
create-next-app (canary): Import of *.module.scss in Client Component causes `__webpack_require__.n is not a function` crash

### ISSUE THREAD

**Issue by karlhorky** [vercel/next.js#67783]
### Link to the code that reproduces this issue

https://github.com/karlhorky/repro-next-js-v15-react-rc-0-sass-webpack-require-not-a-function

### To Reproduce

1. Clone the reproduction repo above (see reproduction repo setup steps below)
2. Start the app in development (`next dev`)
3. Click on the link to navigate to the `/non-home` page
4. Observe the error (if the error doesn't appear, it's possible that webpack reloaded the page for you automatically - ` ⚠ Fast Refresh had to perform a full reload due to a runtime error.` warning in the terminal as seen in the video - you may need to repeat step 2 and 3 a few times to see the page-blocking warning):

```
TypeError: __webpack_require__.n is not a function
    at eval (ClientComponent.tsx:7:127)
    at (app-pages-browser)/app/ClientComponent.tsx (http://localhost:3000/_next/static/chunks/app/non-home/page.js:48:1)
    at options.factory (webpack.js?v=1721063046656:701:31)
    at __webpack_require__ (webpack.js?v=1721063046656:37:33)
    at fn (webpack.js?v=1721063046656:357:21)
    at requireAsyncModule (react-server-dom-webpack-client.browser.development.js:143:17)
    at eval (react-server-dom-webpack-client.browser.development.js:198:16)

The above error occurred in the <NotFoundErrorBoundary> component.

React will try to recreate this component tree from scratch using the error boundary you provided, ReactDevOverlay.

    at Lazy
    at NonHome (Server)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:229:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:327:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:139:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:214:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:348:11)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:229:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:327:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:139:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:214:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/layout-router.js:348:11)
    at body
    at html
    at RootLayout (Server)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/dev-root-not-found-boundary.js:33:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:344:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/app-router.js:156:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/components/app-router.js:551:11)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/app-index.js:143:46)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/next@15.0.0-canary.67_react-dom@19.0.0-rc.0_react@19.0.0-rc.0_sass@1.77.8/node_modules/next/dist/client/app-index.js:151:11)
```

![Screenshot 2024-07-15 at 19 16 14](https://github.com/user-attachments/assets/a07dd0d1-305c-4ab6-a29d-cc179d3d1dbf)

https://github.com/user-attachments/assets/d832814f-cc72-4945-911e-ffffeed05a52

#### Reproduction setup steps

How the reproduction repo was created:

1. Use `create-next-app` with TypeScript - adds `react@19.0.0-rc.0` and `react-dom@19.0.0-rc.0`
2. Remove starter content from pages and layout
3. `pnpm add sass`
6. Add a `non-home/page.tsx`
7. Create `ClientComponent.tsx` and `ClientComponent.module.scss` with `'use client'`
8. Import `<ClientComponent>` in `non-home/page.tsx`
9. Link to `/non-home` from `app/page.tsx` using `next/link`

### Current vs. Expected behavior

I expected no error when using `next/link` to navigate to a Client Component with a `*.module.scss` import, but I observed an error

Maybe the `canary` template for `create-next-app` needs to be updated to the `react@19.0.0-rc-6f23540c7d-20240528` and `react-dom@19.0.0-rc-6f23540c7d-20240528` versions

While this demo does not crash with a page-blocking error very often (as seen in the video) more complicated apps crash consistently.

### Provide environment information

```bash
Node.js v20.15.0

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.15.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.5.0
Relevant Packages:
  next: 15.0.0-canary.67 // Latest available version is detected (15.0.0-canary.67).
  eslint-config-next: N/A
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app, Navigation, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Updating to the `react@19.0.0-rc-6f23540c7d-20240528` and `react-dom@19.0.0-rc-6f23540c7d-20240528` versions as are in [the App Router reproduction template](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template)

But most users using `create-next-app@canary` will not know to do this.

**Comment by karlhorky** [comment]
## Workaround

Upgrade to `react@19.0.0-rc-6f23540c7d-20240528` and `react-dom@19.0.0-rc-6f23540c7d-20240528` versions

**Comment by karlhorky** [comment]
Opened a PR to downgrade the App Router reproduction template to `react@19.0.0-rc.0` and `react-dom@19.0.0-rc.0` (even though this causes this problem reported above) because apparently non-`19.0.0-rc.0` versions have production problems:

- https://github.com/vercel/next.js/pull/67788

**Comment by eps1lon** [comment]
Workaround proposed in https://github.com/vercel/next.js/pull/67673

**Comment by karlhorky** [comment]
@eps1lon thanks for the PR https://github.com/vercel/next.js/pull/67673, merge and publish in [`next@15.0.0-canary.77`](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.77)

I've confirmed that this resolves the issue in my reproduction, here's the diff in the branch:

- https://github.com/karlhorky/repro-next-js-v15-react-rc-0-sass-webpack-require-not-a-function/compare/next-15.0.0-canary.77

**Comment by eps1lon** [comment]
Glad to hear. Thank you for confirming!
