### ISSUE TITLE
r is not a function when wrapping API route with a function

### ISSUE THREAD

**Issue by Floriferous** [vercel/next.js#67833]
### Link to the code that reproduces this issue

https://github.com/Floriferous/next-api-bug

### To Reproduce

1. Clone this repo: https://github.com/Floriferous/next-api-bug
2. Run it with `npm run dev`
3. Visit '/' with your browser
4. Notice the error `r is not a function` in the terminal

### Current vs. Expected behavior

I expect to be able to wrap api routes with a higher order function without issues. Currently it throws an obscure error that can't really be debugged.

I've defined 2 files:

```js
// my API route

import { apiRoute } from "../helpers";

export const GET = apiRoute(async () => {
  console.log('wut?');
  
  return new Response({ hello: 'world' });
})
```

```js
// The apiRoute function

export const apiRoute =
  async (handler: any) =>
  async (...args) => {
    logStuff();
    return handler(...args);
  };
```

But it seems like using these together is somehow not allowed, and the error message does not make sense.

Here's the error stack:

```sh
 ⨯ TypeError: r is not a function
    at /Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55044
    at /Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/trace/tracer.js:140:36
    at NoopContextManager.with (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at /Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:47853
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:40244)
    at /Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46429
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:37583)
    at /Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46391
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at ek.execute (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:45838)
    at ek.handle (/Users/flo/dev/next-api-bug/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:56303)
    at doRender (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:1377:60)
    at cacheEntry.responseCache.get.routeKind (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:1599:34)
    at ResponseCache.get (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/response-cache/index.js:49:26)
    at DevServer.renderToResponseWithComponentsImpl (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:1507:53)
    at /Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:1002:121
    at NextTracerImpl.trace (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/trace/tracer.js:105:20)
    at DevServer.renderToResponseWithComponents (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:1002:41)
    at DevServer.renderPageComponent (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:1931:35)
    at async DevServer.renderToResponseImpl (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:1969:32)
    at async DevServer.pipeImpl (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/flo/dev/next-api-bug/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/flo/dev/next-api-bug/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/flo/dev/next-api-bug/node_modules/next/dist/server/lib/start-server.js:141:13)
 GET /api/stuff 500 in 153ms
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 20.11.0
  npm: 10.7.0
  Yarn: 1.21.1
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by icyJoseph** [comment]
And that makes sense, because, you return a promise, not a function:

```js

export const apiRoute =
  async (handler: any) => /* this is a promise now */
```

This would be fine:

```js
export const apiRoute =
  (handler: any) =>
  async (...args) => {
    logStuff();
    return handler(...args);
  };
```

**Comment by Floriferous** [comment]
Ha, it's obvious now that you figured it out! My bad :)

Maybe there's something to be said about the error message that was so cryptic I didn't double check my own code 😅

**Comment by icyJoseph** [comment]
Yeah the error stack can easily lead one astray... but I had used this pattern with next-auth before, so I got quite intrigued... 

Please do close the issue if you are happy with the resolution.
