### ISSUE TITLE
Response.redirect with relative URLs not working for Route Handlers

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#67966]
### Link to the code that reproduces this issue

https://github.com/vercel/redirect-reproduction

## Actual 

1. Navigate to localhost:3000/test
2. See error below

```bash
 ⨯ TypeError: Failed to parse URL from /test
    at Response.redirect (node:internal/deps/undici/undici:4393:17)
    at GET (/Users/leerob/Developer/scratch/repro/.next/server/chunks/[root of the server]__1d2930._.js:31:21)
    ... 38 lines matching cause stack trace ...
    at async Server.requestListener (/Users/leerob/Developer/scratch/repro/node_modules/.pnpm/next@15.0.0-canary.73_react-dom@19.0.0-rc-512b09b2-20240718_react@19.0.0-rc-512b09b2-20240718_kqhq7uzfl3zawjcrarvtpd6ica/node_modules/next/dist/server/lib/start-server.js:142:13) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:797:36)
      at Response.redirect (node:internal/deps/undici/undici:4391:23)
      at GET (/Users/leerob/Developer/scratch/repro/.next/server/chunks/[root of the server]__1d2930._.js:31:21)
      at /Users/leerob/Developer/scratch/repro/node_modules/.pnpm/next@15.0.0-canary.73_react-dom@19.0.0-rc-512b09b2-20240718_react@19.0.0-rc-512b09b2-20240718_kqhq7uzfl3zawjcrarvtpd6ica/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:66499
      at /Users/leerob/Developer/scratch/repro/node_modules/.pnpm/next@15.0.0-canary.73_react-dom@19.0.0-rc-512b09b2-20240718_react@19.0.0-rc-512b09b2-20240718_kqhq7uzfl3zawjcrarvtpd6ica/node_modules/next/dist/server/lib/trace/tracer.js:173:36
      at NoopContextManager.with (/Users/leerob/Developer/scratch/repro/node_modules/.pnpm/next@15.0.0-canary.73_react-dom@19.0.0-rc-512b09b2-20240718_react@19.0.0-rc-512b09b2-20240718_kqhq7uzfl3zawjcrarvtpd6ica/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
```

## Expected

1. Navigate to localhost:3000/test
2. Redirects to localhost:3000

Note that this _does_ work as expected:

```ts
import { redirect } from 'next/navigation';

export async function GET(request: Request) {
  redirect('/test');
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.15.1
  npm: 10.7.0
  Yarn: 1.22.21
  pnpm: 9.4.0
Relevant Packages:
  next: 15.0.0-canary.73 // Latest available version is detected (15.0.0-canary.73).
  eslint-config-next: N/A
  react: 19.0.0-rc-512b09b2-20240718
  react-dom: 19.0.0-rc-512b09b2-20240718
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ztanner** [comment]
Closing this as the error doesn't come from Next.js, it comes from Node.js when using [Response.redirect](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect_static). We also disallow relative redirects in `NextResponse.redirect`.

```
Welcome to Node.js v20.11.1.
Type ".help" for more information.
> Response.redirect('/foo')
Uncaught TypeError: Failed to parse URL from /foo
    at Response.redirect (node:internal/deps/undici/undici:5425:31) {
  cause: TypeError: Invalid URL
  ```
 
 This is also unsupported in `NextResponse`, where we can actually control the error:
 
 ```
 Error: URL is malformed "/test". Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls
 ```
