### ISSUE TITLE
[turbopack] Module is not found when using `bun link`

### ISSUE THREAD

**Issue by wladpaiva** [vercel/next.js#68410]
### Link to the code that reproduces this issue

https://github.com/wladpaiva/facebook-conversions-api

### To Reproduce

1. `bun link` to a package on local machine
2. add `--turbo` on the dev script
3. run dev

or using the repo
1. `bun run build`
2. `cd example && bun install && bun dev`

### Current vs. Expected behavior

Turbopack doesn't find the module if the module was linked with Bun but if you take the `--turbo` out it works fine.

```
./app/facebook.ts:1:1
Module not found: Can't resolve 'next-facebook-tracking'
> 1 | import { FacebookTracking } from "next-facebook-tracking";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | export const facebook = new FacebookTracking({
  4 |   debug: true,



https://nextjs.org/docs/messages/module-not-found


    at processIssues (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/dev/turbopack-utils.js:229:15)
    at handleRouteType (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/dev/turbopack-utils.js:386:17)
    at async Object.ensurePage (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/dev/hot-reloader-turbopack.js:647:17)
    at async DevBundlerService.ensurePage (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/lib/dev-bundler-service.js:18:20)
    at async DevServer.ensurePage (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/dev/next-dev-server.js:551:9)
    at async Object.ensure (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/dev/next-dev-server.js:169:17)
    at async DevRouteMatcherManager.matchAll (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/future/route-matcher-managers/dev-route-matcher-manager.js:96:13)
    at async DevRouteMatcherManager.match (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/future/route-matcher-managers/default-route-matcher-manager.js:155:26)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/next-server.js:228:31)
    at async DevServer.handleRequestImpl (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/base-server.js:816:17)
    at async /Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/wladpaiva/i/next-facebook-tracking/example/node_modules/next/dist/server/lib/start-server.js:141:13)
 GET / 500 in 230ms
 ```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:45:49 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.15.0
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.3.3
Next.js Config:
  output: N/A

next-facebook-tracking
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@wladpaiva Have you also tried with other package managers' link functionality?

- e.g., https://pnpm.io/cli/link

**Comment by wladpaiva** [comment]
nops, only have tried `bun`

**Comment by samcx** [comment]
@wladpaiva Probably a good idea to make sure so you can rule out where this issue is coming from.

**Comment by abusarah-tech** [comment]
I also ran into this exact issue. At the moment, I’ve found two workarounds that might help explain what is going on.
- I removed `--turbopack` from the `dev` script. 
- I added an entry in `turbopack.resolveAlias` to resolve the imported path to the exact JS file

@samcx I am going to try with pnpm and report back.

**Comment by timneutkens** [comment]
The issue in the reproduction steps is that Turbopack does not allow importing outside of the root directory, which is automatically inferred. In this case you'll want to set `turbopack.root` to a directory higher up in order for it to be able to import the code in a separate folder. Documentation: https://nextjs.org/docs/app/api-reference/config/next-config-js/turbopack#root-directory
