### ISSUE TITLE
Problem with tailwindcss

### ISSUE THREAD

**Issue by batazor** [vercel/next.js#68766]
### Link to the code that reproduces this issue

https://github.com/shortlink-org/shortlink/tree/353b796dab3a6e8ae97f02e00cd78e214ded42ad/boundaries/ui-monorepo/packages/landing

### To Reproduce

1. pnpm dev

### Current vs. Expected behavior

success work with css files

### Provide environment information

```bash
Node.js v22.4.1

Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 16
Binaries:
  Node: 22.4.1
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.7.0
Relevant Packages:
  next: 14.2.3 // There is a newer version (14.2.5) available, upgrade recommended! 
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

```
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/user/myprojects/shortlink/boundaries/ui-monorepo/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/processor.js:38:15)
    at new Processor (/Users/user/myprojects/shortlink/boundaries/ui-monorepo/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/processor.js:11:25)
    at postcss (/Users/user/myprojects/shortlink/boundaries/ui-monorepo/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/postcss.js:26:10)
    at /Users/user/myprojects/shortlink/boundaries/ui-monorepo/node_modules/.pnpm/next@15.0.0-canary.111_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-react-compile_aacy6hpta6psvgkqs72fjvpahu/node_modules/next/dist/build/webpack/config/blocks/css/index.js:127:37
    at async /Users/user/myprojects/shortlink/boundaries/ui-monorepo/node_modules/.pnpm/next@15.0.0-canary.111_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-react-compile_aacy6hpta6psvgkqs72fjvpahu/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:86:33
    at async Span.traceAsyncFn (/Users/user/myprojects/shortlink/boundaries/ui-monorepo/node_modules/.pnpm/next@15.0.0-canary.111_@babel+core@7.25.2_@opentelemetry+api@1.9.0_babel-plugin-react-compile_aacy6hpta6psvgkqs72fjvpahu/node_modules/next/dist/trace/trace.js:157:20)
 ⨯ app/layout.tsx
An error occurred in `next/font`.
```

**Comment by batazor** [comment]
- The problem is reproduced with both next v14 and next v15.
- Tried clearing cache and installing dependencies again
