### ISSUE TITLE
npm run build fails even in newly created repo

### ISSUE THREAD

**Issue by ahmetcetin** [vercel/next.js#69245]
### Link to the code that reproduces this issue

https://github.com/ahmetcetin/nextjs-test

### To Reproduce

1. Run npx create-next-app@latest test and accept all default answers to the questions
2. Run npm run build

### Current vs. Expected behavior

I would expect at least the initially created code base to build successfully, but it gives these errors:
 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
  ▲ Next.js 14.2.6

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/5)  [    ]Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/682.js:6:1263)
    at renderWithHooks (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error

Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/682.js:6:1263)
    at renderWithHooks (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)
Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/682.js:6:1263)
    at renderWithHooks (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error

Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/682.js:6:1263)
    at renderWithHooks (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/Users/ahmetcetin/Developer/sides/test/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:21713)
    at h (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:13637)
    at au (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908) {
  digest: '757500255'
}
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:21713)
    at h (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:13637)
    at au (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908) {
  digest: '757500255'
}
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:21713)
    at h (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:13637)
    at au (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:21713)
    at h (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:13637)
    at au (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:21713)
    at h (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:13637)
    at au (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:21713)
    at h (/Users/ahmetcetin/Developer/sides/test/.next/server/chunks/892.js:1:13637)
    at au (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/Users/ahmetcetin/Developer/sides/test/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
 ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
        /_error: /404
        /_error: /500
        /_not-found/page: /_not-found
        /page: /

### Provide environment information

```bash
macOS 14.6.1
Node: 20.12
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by ahmetcetin** [comment]
wrong alert. the issue was actually on top of the errors:
⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env

i had NODE_ENV exported in .zshrc as "development", removed it, opened a new shell, and all looks good now.
