### ISSUE TITLE
__turbopack_resolve_absolute_path__ is not a function

### ISSUE THREAD

**Issue by jacobheric** [vercel/next.js#69254]
### Link to the code that reproduces this issue

https://github.com/stratospark/turbopack-test

### To Reproduce

1. clone repo
2. npm run dev
3. go to localhost, you will see:

```
__turbopack_resolve_absolute_path__ is not a function
    at get url (node_modules_@jitl_quickjs-wasmfile-release-sync_dist_ee4b00._.js:15:26)
    at emscripten-module.browser.mjs:3:33
    at emscripten-module.browser.mjs:40:2
    at [project]/node_modules/@jitl/quickjs-wasmfile-release-sync/dist/emscripten-module.browser.mjs 
```

### Current vs. Expected behavior

Works with `next dev` but not `next dev --turbo`. 

This was reported and fixed here: https://github.com/vercel/next.js/issues/66005. But, don't see that fix in the turbo repo any more. 

### Provide environment information

```bash
Node.js v20.14.0

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.1.1
Relevant Packages:
  next: 14.2.6 // Latest available version is detected (14.2.6).
  eslint-config-next: 14.2.6
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@jacobheric It was fixed and released here → https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.46.

Let us know if you are able to use the latest canary to test this!

**Comment by matmill5** [comment]
@jacobheric thank you for reporting this, and your [work on inngest ](https://github.com/inngest/inngest/pull/1698); have been blocked by this issue for a couple days!

**Comment by jacobheric** [comment]
> @jacobheric It was fixed and released here → https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.46.
> 
> Let us know if you are able to use the latest canary to test this!

I tested against canary and the issue is fixed there. Canary does require react 19 so not sure how soon we can start using that. Any plans to backport the fix?  Thanks @samcx!

**Comment by samcx** [comment]
@jacobheric Added the <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> to our next relevant backport (the next one will be solely related to fix issues with 14.2.7)!

**Comment by jacobheric** [comment]
Thanks much @samcx, I see the back ported fix!
