### ISSUE TITLE
An error occurred in `next/font`. TypeError: Cannot read properties of undefined (reading 'ascent')

### ISSUE THREAD

**Issue by chris-garrett** [vercel/next.js#69748]
### Link to the code that reproduces this issue

https://github.com/chris-garrett/next-font-issue

### To Reproduce

Create a new app and run pnpm dev

```
npx -y create-next-app@latest \
  next-font-issue \
  --yes \
  --typescript \
  --app \
  --eslint \
  --import-alias "@acme/*" \
  --src-dir \
  --use-pnpm \
  --turbo \
  --tailwind
```

### Current vs. Expected behavior

I would expect a new app created with create-next-app and unmodified to run without errors. 

### Provide environment information

```bash
$ npx --no-install next info

Operating System:
  Platform: linux
  Arch: x64
  Version: #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2
  Available memory (MB): 64212
  Available CPU cores: 24
Binaries:
  Node: 21.5.0
  npm: 10.2.4
  Yarn: 1.22.22
  pnpm: 9.8.0
Relevant Packages:
  next: 14.2.8 // Latest available version is detected (14.2.8).
  eslint-config-next: 14.2.8
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

```
An error occurred in `next/font`.

TypeError: Cannot read properties of undefined (reading 'ascent')
    at get ascent [as ascent] (/home/chris/projects/next-font-issue/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@next/font/dist/fontkit/index.js:1:797933)
    at getFallbackMetricsFromFontFile (/home/chris/projects/next-font-issue/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@next/font/dist/local/get-fallback-metrics-from-font-file.js:73:13)
    at nextFontLocalFontLoader (/home/chris/projects/next-font-issue/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/@next/font/dist/local/loader.js:63:114)
    at async Span.traceAsyncFn (/home/chris/projects/next-font-issue/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async /home/chris/projects/next-font-issue/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:76:87
    at async Span.traceAsyncFn (/home/chris/projects/next-font-issue/node_modules/.pnpm/next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
 GET / 500 in 1703ms
```

**Comment by Frexuz** [comment]
Same here

**Comment by Frexuz** [comment]
Looks like it was backported to 14.2.9, but i still have the same error

![image](https://github.com/user-attachments/assets/5c391f40-afd8-4724-be11-f263c413c47c)

![image](https://github.com/user-attachments/assets/95142ff7-2cec-47e7-967e-188a91319269)

I have also tried to remove `./next` folder 🤔 

```

  "dependencies": {
    "next": "14.2.9",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-select": "5.8.0"
  },
  "devDependencies": {
    "@playwright/test": "1.47.0",
    "@storybook/addon-essentials": "8.2.9",
    "@storybook/addon-interactions": "8.2.9",
    "@storybook/addon-links": "8.2.9",
    "@storybook/addon-onboarding": "8.2.9",
    "@storybook/blocks": "8.2.9",
    "@storybook/nextjs": "8.2.9",
    "@storybook/react": "8.2.9",
    "@storybook/test": "8.2.9",
    "@types/node": "22.5.4",
    "@types/react": "18.3.5",
    "@types/react-dom": "18.3.0",
    "eslint": "8.56.0",
    "eslint-config-next": "14.2.9",
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-10x": "1.5.2",
    "eslint-plugin-prettier": "5.2.1",
    "eslint-plugin-simple-import-sort": "12.1.1",
    "eslint-plugin-storybook": "0.8.0",
    "eslint-plugin-typescript-sort-keys": "3.2.0",
    "postcss": "8.4.45",
    "prettier": "3.3.3",
    "storybook": "8.2.9",
    "tailwindcss": "3.4.1",
    "typescript": "5.5.4"
  }
```
