### ISSUE TITLE
Failed to find Server Action - next dev - v14.2.8

### ISSUE THREAD

**Issue by cb1kenobi** [vercel/next.js#69882]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js

### To Reproduce

1. Create an page with a client side component containing a form with an action pointing to a server action
2. Submit form

### Current vs. Expected behavior

Everything was working fine with 14.2.7, but when we upgraded to 14.2.8, all server actions are failing during `next dev`.

So far, we've encountered 2 distinct errors, but they both occur in `next-server`:

```
Error: Failed to find Server Action "27129c0e59a7b09c5797697dcb190a64ccf7bd2e". This request might be from an older or newer deployment. Original error: Cannot read properties of undefined (reading 'workers')
    at r_ (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:1713)
    at /Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:303
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async rk (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
    at async r3 (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1256)
    at async doRender (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1420:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1581:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1489:28)
    at async DevServer.renderPageComponent (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1913:24)
    at async DevServer.renderToResponseImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1951:32)
    at async DevServer.pipeImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:917:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:813:17)
    at async /Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13)
```

and

```
TypeError: Cannot read properties of undefined (reading 'apply')
    at /Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:426
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async rk (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:7978)
    at async r3 (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:41:1256)
    at async doRender (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1420:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1569:40)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1489:28)
    at async DevServer.renderPageComponent (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1913:24)
    at async DevServer.renderToResponseImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1951:32)
    at async DevServer.pipeImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:917:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:813:17)
    at async /Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/Users/me/myproject/node_modules/.pnpm/next@14.2.8_@babel+core@7.24.7_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13)
```

### Provide environment information

```bash
macOS 14.5, Node.js 22.3.0, pnpm 9.6.0, Next.js 14.2.8
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by huozhi** [comment]
Duplicate #69756
