### ISSUE TITLE
Image unknown errors.

### ISSUE THREAD

**Issue by omerman** [vercel/next.js#70129]
### Link to the code that reproduces this issue

https://github.com/omerman/next13-unmounts-reproduction/

### To Reproduce

Not sure.

### Current vs. Expected behavior

[15.09.2024 18:44.03.821] [ERROR]  [31m[1m⨯[22m[39m Error: Invalid accept header
    at s.parse (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\compiled\@hapi\accept\index.js:1:3083)
    at t.selections (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\compiled\@hapi\accept\index.js:1:2564)
    at t.selection (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\compiled\@hapi\accept\index.js:1:2425)
    at t.mediaType (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\compiled\@hapi\accept\index.js:1:2085)
    at getSupportedMimeType (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\image-optimizer.js:179:44)
    at ImageOptimizerCache.validateParams (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\image-optimizer.js:436:26)
    at NextNodeServer.handleNextImageRequest (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\next-server.js:167:58)
    at Server.normalizeAndAttachMetadata (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\base-server.js:292:39)
    at NextNodeServer.handleRequestImpl (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\base-server.js:848:39)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async invokeRender (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\lib\router-server.js:183:21)
    at async handleRequest (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\lib\router-server.js:360:24)
    at async requestHandlerImpl (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\lib\router-server.js:384:13)
    at async Server.requestListener (C:\inetpub\vhosts\nagnu-fe-nx-prod\node_modules\[4m.pnpm[24m\next@15.0.0-canary.155_@babel+core@7.25.2_react-dom@19.0.0-rc-206df66e-20240912_react@19.0.0-_uuc6fd4rdyxfoesthibkjh5nny\node_modules\[4mnext[24m\dist\server\lib\start-server.js:142:13) {
  data: [1mnull[22m,
  isBoom: [33mtrue[39m,
  isServer: [33mfalse[39m,
  output: {
    statusCode: [33m400[39m,
    payload: {
      statusCode: [33m400[39m,
      error: [32m'Bad Request'[39m,
      message: [32m'Invalid accept header'[39m
    },
    headers: {}
  }
}

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.14.1
Relevant Packages:
  next: 15.0.0-canary.155 // There is a newer canary version (15.0.0-canary.156) available, please upgrade! 
  eslint-config-next: 14.2.3
  react: 19.0.0-rc-206df66e-20240912
  react-dom: 19.0.0-rc-206df66e-20240912
  typescript: 5.2.2
Next.js Config:
  output: N/A
 ⚠ There is a newer canary version (15.0.0-canary.156) available, please upgrade! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

**Comment by samcx** [comment]
@omerman Where are you trying to deploy this? Was not able to replicate this on Vercel.

**Comment by omerman** [comment]
@samcx My app is deployed to an IIS server, using reverse proxy. snippet from web.release config:
```
          <rule name="ReverseProxyInboundRule2" stopProcessing="true">
		<match url="^dashboard(/)?(.*)" />
		<action type="Rewrite" url="http://localhost:4000/{R:0}" />
		<serverVariables>
			<set name="HTTP_X_FORWARDED_HOST" value="{HTTP_HOST}" />
		</serverVariables>
	</rule>
```
