### ISSUE TITLE
next config output="export" with appDir doesn't work 

### ISSUE THREAD

**Issue by pivilartisant** [vercel/next.js#70250]
### Link to the code that reproduces this issue

https://github.com/pivilartisant/loot-survivor/tree/main/ui

### To Reproduce

yarn install && yarn build && yarn next export

### Current vs. Expected behavior

**next.config.js:**

```
const withPWA = require("next-pwa");

const nextConfig = {
  experimental: {
    appDir: true,
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    });

    return config;
  },
  output: "export",
  images: { unoptimized: true },
};

module.exports = withPWA({
  dest: "public",
  disable: process.env.NODE_ENV === "development",
  // Add any additional Workbox configuration here
})(nextConfig);
```
**next export fails with the following:** 
```
➜  ui git:(main) ✗ yarn next export
yarn run v1.22.22
$ /home/pivi/Code/loot-survivor/ui/node_modules/.bin/next export
info  - Loaded env from /home/pivi/Code/loot-survivor/ui/.env
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - using build directory: /home/pivi/Code/loot-survivor/ui/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/home/pivi/Code/loot-survivor/ui/next.config.js". Generating map from "./pages"
info  - Launching 15 workers
info  - Copying "public" directory
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /
    at Object.getPagePath (/home/pivi/Code/loot-survivor/ui/node_modules/next/dist/server/require.js:77:15)
    at /home/pivi/Code/loot-survivor/ui/node_modules/next/dist/export/index.js:392:48
    at Array.map (<anonymous>)
    at /home/pivi/Code/loot-survivor/ui/node_modules/next/dist/export/index.js:383:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/home/pivi/Code/loot-survivor/ui/node_modules/next/dist/trace/trace.js:79:20) {
  code: 'ENOENT'
}
error Command failed with exit code 1.
```

expect: yarn next output:"export" to work 

issue present here:https://github.com/vercel/next.js/issues/45507 and https://github.com/vercel/next.js/issues/43417 

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2
    Binaries:
      Node: 20.1.0
      npm: 9.6.7
      Yarn: 1.22.22
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

N/A

**Comment by JesseKoldewijn** [comment]
The first thing I notice is your use of the export command. When having the output config set to export you should get a static output. The export command isn't in use anymore to my knowledge
