### ISSUE TITLE
experimental_ppr with generateMetadata gives revalidation error

### ISSUE THREAD

**Issue by moparlakci** [vercel/next.js#70391]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next info
```

### Which example does this report relate to?

with-styled-components

### Describe the Bug

Error: Invalid revalidate configuration provided: 0 < 1
    at NextNodeServer.renderToResponseWithComponentsImpl (/usr/src/app/node_modules/next/dist/server/base-server.js:1881:27)
    at async NextNodeServer.renderPageComponent (/usr/src/app/node_modules/next/dist/server/base-server.js:2169:24)
    at async NextNodeServer.renderToResponseImpl (/usr/src/app/node_modules/next/dist/server/base-server.js:2207:32)
    at async NextNodeServer.pipeImpl (/usr/src/app/node_modules/next/dist/server/base-server.js:960:25)
    at async NextNodeServer.handleCatchallRenderRequest (/usr/src/app/node_modules/next/dist/server/next-server.js:281:17)
    at async NextNodeServer.handleRequestImpl (/usr/src/app/node_modules/next/dist/server/base-server.js:853:17)
    at async invokeRender (/usr/src/app/node_modules/next/dist/server/lib/router-server.js:183:21)
    at async handleRequest (/usr/src/app/node_modules/next/dist/server/lib/router-server.js:360:24)
    at async requestHandlerImpl (/usr/src/app/node_modules/next/dist/server/lib/router-server.js:384:13)
    at async Server.requestListener (/usr/src/app/node_modules/next/dist/server/lib/start-server.js:142:13)

### Expected Behavior

Generating metadata as stated for given page

### To Reproduce

/products/[slug]/page.tsx

```typescript
export const dynamic = "force-dynamic";
export const experimental_ppr = true;


export async function generateMetadata(
	{ params: { domain } }: { params: { domain: string } },
	parent: ResolvingMetadata,
): Promise<Metadata> {
	// read route params
	const website = await getWebsite(domain); // fetch call with revalidate set to 60

	return {
		robots: {
			index: website.search_engine_indexing,
			follow: true,
			nocache: true,
			googleBot: {
				index: website.search_engine_indexing,
				follow: true,
				noimageindex: true,
				"max-video-preview": -1,
				"max-image-preview": "large",
				"max-snippet": -1,
			},
		},
	};
}


export default async function ProductPage({
	params: { domain, slug },
}: {
....
})
```

**Comment by moparlakci** [comment]
nothing to do with "with-styled-components" example..

**Comment by samcx** [comment]
@moparlakci Please re-open this issue using the correct [issue template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml)!
