### ISSUE TITLE
Next Font: {randomlowercaseletter}.default / {randomlowercaseletter}.{name of a google font} is not a function

### ISSUE THREAD

**Issue by JackatDJL** [vercel/next.js#70580]
### Link to the code that reproduces this issue

https://github.com/JackatDJL/Athenetz-SV/tree/athe-12-next-font-randomlowercaseletterdefault

### To Reproduce

git clone https://github.com/JackatDJL/Athenetz-SV.git
cd Athenetz-SV
git fetch
git checkout athe-12-next-font-randomlowercaseletterdefault
corepack enable
yarn install
yarn build

### Current vs. Expected behavior

Im in Pain ;(

i traced the issue to somewhere in next/font
if i use …/google with a google font like oxanium i get this error (tested on windows, linux and vercel) {}.{fontname}

```
@athenetz-sv/wahlen:build: at 59962 (/vercel/path0/apps/wahlen/.next/server/app/page.js:54:122230)
00:24:41.560@athenetz-sv/wahlen:build: at t (/vercel/path0/apps/wahlen/.next/server/webpack-runtime.js:1:128)
00:24:41.560@athenetz-sv/wahlen:build: at 11215 (/vercel/path0/apps/wahlen/.next/server/app/page.js:54:121166)
00:24:41.560@athenetz-sv/wahlen:build: at t (/vercel/path0/apps/wahlen/.next/server/webpack-runtime.js:1:128)
00:24:41.560@athenetz-sv/wahlen:build: at 26658 (/vercel/path0/apps/wahlen/.next/server/app/page.js:1:3999)
00:24:41.560@athenetz-sv/wahlen:build: at Object.t [as require] (/vercel/path0/apps/wahlen/.next/server/webpack-runtime.js:1:128)
00:24:41.560@athenetz-sv/wahlen:build: at require (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18228)
00:24:41.560@athenetz-sv/wahlen:build: at i (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:88294)
00:24:41.560@athenetz-sv/wahlen:build: at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:98817
00:24:41.560@athenetz-sv/wahlen:build: at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:98904
00:24:41.560@athenetz-sv/wahlen:build: Generating static pages (3/4)
00:24:41.560@athenetz-sv/wahlen:build: ✓ Generating static pages (4/4)
00:24:41.584@athenetz-sv/wahlen:build:
00:24:41.584@athenetz-sv/wahlen:build: > Export encountered errors on following paths:
00:24:41.585@athenetz-sv/wahlen:build: /page: /
00:24:41.677@athenetz-sv/wahlen:build: ERROR: command finished with error: command (/vercel/path0/apps/wahlen) /yarn1/node_modules/yarn/bin/yarn run build exited (1)
00:24:41.677@athenetz-sv/wahlen#build: command (/vercel/path0/apps/wahlen) /yarn1/node_modules/yarn/bin/yarn run build exited (1)
00:24:41.680
00:24:41.680 Tasks: 5 successful, 6 total
00:24:41.680 Cached: 5 cached, 6 total
00:24:41.680 Time: 21.098s
00:24:41.681Summary: /vercel/path0/.turbo/runs/2mfmD52ot720RrLjZ4R4lRNAc7Y.json
00:24:41.681 Failed: @athenetz-sv/wahlen#build
00:24:41.681
```

and if i try to use localfonts instead i get {}.default
```
@athenetz-sv/wahlen:build: TypeError: (0 , r.default) is not a function
01:18:56.873@athenetz-sv/wahlen:build: at 40134 (/vercel/path0/apps/wahlen/.next/server/app/_not-found/page.js:1:6048)
01:18:56.873@athenetz-sv/wahlen:build: at t (/vercel/path0/apps/wahlen/.next/server/webpack-runtime.js:1:128)
01:18:56.873@athenetz-sv/wahlen:build: at 77718 (/vercel/path0/apps/wahlen/.next/server/app/_not-found/page.js:1:3036)
01:18:56.873@athenetz-sv/wahlen:build: at t (/vercel/path0/apps/wahlen/.next/server/webpack-runtime.js:1:128)
01:18:56.873@athenetz-sv/wahlen:build: at 53219 (/vercel/path0/apps/wahlen/.next/server/app/_not-found/page.js:1:645)
01:18:56.873@athenetz-sv/wahlen:build: at t (/vercel/path0/apps/wahlen/.next/server/webpack-runtime.js:1:128)
01:18:56.874@athenetz-sv/wahlen:build: at o (/vercel/path0/apps/wahlen/.next/server/app/_not-found/page.js:1:6651)
01:18:56.874@athenetz-sv/wahlen:build: at /vercel/path0/apps/wahlen/.next/server/app/_not-found/page.js:1:6677
01:18:56.874@athenetz-sv/wahlen:build: at t.X (/vercel/path0/apps/wahlen/.next/server/webpack-runtime.js:1:1196)
01:18:56.874@athenetz-sv/wahlen:build: at /vercel/path0/apps/wahlen/.next/server/app/_not-found/page.js:1:6664
01:18:56.875@athenetz-sv/wahlen:build:
01:18:56.875@athenetz-sv/wahlen:build: > Build error occurred
01:18:56.877@athenetz-sv/wahlen:build: Error: Failed to collect page data for /_not-found
01:18:56.878@athenetz-sv/wahlen:build: at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
01:18:56.878@athenetz-sv/wahlen:build: at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
01:18:56.878@athenetz-sv/wahlen:build: type: 'Error'
01:18:56.878@athenetz-sv/wahlen:build: }
01:18:56.973@athenetz-sv/wahlen:build: ERROR: command finished with error: command (/vercel/path0/apps/wahlen) /yarn1/node_modules/yarn/bin/yarn run build exited (1)
01:18:56.973@athenetz-sv/wahlen#build: command (/vercel/path0/apps/wahlen) /yarn1/node_modules/yarn/bin/yarn run build exited (1)
01:18:56.976
01:18:56.976 Tasks: 5 successful, 6 total
01:18:56.977 Cached: 0 cached, 6 total
01:18:56.977 Time: 1m17.159s
01:18:56.977Summary: /vercel/path0/.turbo/runs/2mfso4wRRMrIX3sJrwMoSfT5u1K.json
01:18:56.977 Failed: @athenetz-sv/wahlen#build
```

These are the outputs from vercel with version 14.2.12
and this is the local output with version 15.0.0-canary.172

```
┌ @athenetz-sv/wahlen#build > cache miss, executing 9f037a7a61ca03e7
│   ▲ Next.js 15.0.0-canary.172
│   - Environments: .env.local
│
│    Creating an optimized production build ...
│  ⚠ Compiled with warnings
│
│ ../../node_modules/framer-motion/dist/cjs/index.js
│ Module not found: Can't resolve '@emotion/is-prop-valid' in 'D:\dev\Athenetz-SV\node_modules\framer-motion\dist\cjs'
│
│ Import trace for requested module:
│ ../../node_modules/framer-motion/dist/cjs/index.js
│ ../../packages/SV-UI/dist/layout/FloatingPanel.js
│ ./src/app/page.tsx
│
│  ✓ Linting and checking validity of types
│    Collecting page data  ..TypeError: (0 , o.default) is not a function
│     at 21459 (D:\dev\Athenetz-SV\apps\wahlen.next\server\app_not-found\page.js:1:5028)
│     at t (D:\dev\Athenetz-SV\apps\wahlen.next\server\webpack-runtime.js:1:128)
│     at D:\dev\Athenetz-SV\apps\wahlen.next\server\app_not-found\page.js:1:3096
│     at t.a (D:\dev\Athenetz-SV\apps\wahlen.next\server\webpack-runtime.js:1:881)
│     at 76560 (D:\dev\Athenetz-SV\apps\wahlen.next\server\app_not-found\page.js:1:2837)
│     at Function.t (D:\dev\Athenetz-SV\apps\wahlen.next\server\webpack-runtime.js:1:128)
│     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
│     at async collectGenerateParams (D:\dev\Athenetz-SV\node_modules\next\dist\build\utils.js:937:21)
│     at async D:\dev\Athenetz-SV\node_modules\next\dist\build\utils.js:1172:17
│     at async Span.traceAsyncFn (D:\dev\Athenetz-SV\node_modules\next\dist\trace\trace.js:157:20)
│
│ > Build error occurred
│ Error: Failed to collect page data for /_not-found
│     at D:\dev\Athenetz-SV\node_modules\next\dist\build\utils.js:1272:15
│     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
│   type: 'Error'
│ }
│    Collecting page data  .
│                           command finished with error: command (D:\dev\Athenetz-SV\apps\wahlen) C:\Users\jackr\AppData\Local\Temp\xfs-cd78823a\yarn.cmd run build ex
│ ited (1)
└────>
```

@athenetz-sv/wahlen#build: command (D:\dev\Athenetz-SV\apps\wahlen) C:\Users\jackr\AppData\Local\Temp\xfs-cd78823a\yarn.cmd run build exited (1)
ty for reading the entire thing ❤

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32760
  Available CPU cores: 12
Binaries:
  Node: 22.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.172
  eslint-config-next: 14.2.13
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Font (next/font)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), Vercel (Deployed)

### Additional context

Original issue with Next.js 14.2.12
Still a issue in Next.js v15.0.0-canary.172
i traced the issue to somewhere in next/font
tested and failed on windows, linux (codepace) and vercel

**Comment by JackatDJL** [comment]
just noticed the first line of error codes is missing
was smth like:
`TypeError: (0 , n.Oxanium) is not a function`

**Comment by JackatDJL** [comment]
Tryed with latest published v14.2.14
```
┌ @athenetz-sv/wahlen#build > cache miss, executing 67c9a89d1fa6c3f8
│   ▲ Next.js 14.2.14
│   - Environments: .env.local
│
│    Creating an optimized production build ...
│  ⚠ Compiled with warnings
│
│ ../../node_modules/framer-motion/dist/cjs/index.js
│ Module not found: Can't resolve '@emotion/is-prop-valid' in 'D:\dev\Athenetz-SV\node_modules\framer-motion\dist\cjs'
│
│ Import trace for requested module:
│ ../../node_modules/framer-motion/dist/cjs/index.js
│ ../../packages/SV-UI/dist/layout/FloatingPanel.js
│ ./src/app/page.tsx
│
│  ✓ Linting and checking validity of types
│    Collecting page data  .TypeError: (0 , r.default) is not a function
│     at 1281 (D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:6001)
│     at t (D:\dev\Athenetz-SV\apps\wahlen\.next\server\webpack-runtime.js:1:127)
│     at 3399 (D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:2995)
│     at t (D:\dev\Athenetz-SV\apps\wahlen\.next\server\webpack-runtime.js:1:127)
│     at 5861 (D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:637)
│     at t (D:\dev\Athenetz-SV\apps\wahlen\.next\server\webpack-runtime.js:1:127)
│     at o (D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:6613)
│     at D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:6640
│     at t.X (D:\dev\Athenetz-SV\apps\wahlen\.next\server\webpack-runtime.js:1:1181)
│     at D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:6626
│
│ > Build error occurred
│ Error: Failed to collect page data for /_not-found
│     at D:\dev\Athenetz-SV\node_modules\next\dist\build\utils.js:1268:15
│     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
│   type: 'Error'
│ }
│    Collecting page data  .
│                           command finished with error: command (D:\dev\Athenetz-SV\apps\wahlen) C:\Users\jackr\AppData\Local\Temp\xfs-4c8b0c06\yarn.cmd run build ex
│ ited (1)
└────>
@athenetz-sv/wahlen#build: command (D:\dev\Athenetz-SV\apps\wahlen) C:\Users\jackr\AppData\Local\Temp\xfs-4c8b0c06\yarn.cmd run build exited (1)

 Tasks:    5 successful, 6 total
Cached:    5 cached, 6 total
  Time:    47.292s
Failed:    @athenetz-sv/wahlen#build

 ERROR  run failed: command  exited (1)
```

**Comment by JackatDJL** [comment]
# Found the Culprit
But i still dont know why

Next Turbo Dev HTML Error out
![image](https://github.com/user-attachments/assets/38307923-4837-4488-b68e-695fb8fe7441)
The Compiled DIST
![image](https://github.com/user-attachments/assets/bb0e2802-221d-4846-b127-a2844f18a77f)

My not Compiled TS File
![image](https://github.com/user-attachments/assets/0d81b96d-4830-4542-961b-ce63d761f50e)

now im even more confused

**Comment by JackatDJL** [comment]
So from what im seeing the {random letter} has smth to do with tsc
Because my dev output (tsc --watch) is `local_1.default`
my build (tsc --build) `r.default`... wait a second
my ui dist still shows `local_1.default`
so it has something to do with the nextjs compiler (while building)
and the turbo compiler (while dev)
so webpack fore some reason renames local_1 to r (and on vercel servers to n)
while turbo dev keeps the name local_1

im confused

**Comment by samcx** [comment]
@JackatDJL

```
➤ YN0000: · Yarn 4.5.0
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @util/eslint-config@workspace:^: Workspace not found (@util/eslint-config@workspace:^)
```

I'm having issues testing the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> — is it possible to simplify this <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> to not use a Yarn workspace?

**Comment by JackatDJL** [comment]
> @JackatDJL
> 
> ```
> ➤ YN0000: · Yarn 4.5.0
> ➤ YN0000: ┌ Resolution step
> ➤ YN0001: │ Error: @util/eslint-config@workspace:^: Workspace not found (@util/eslint-config@workspace:^)
> ```
> 
> I'm having issues testing the <img alt=":repro:" width="20" height="auto" src="https://camo.githubusercontent.com/62704ae9512b86ac1ba3d0b591c9245bf36db7c84940922ae8c92b8e898da36c/68747470733a2f2f656d6f6a692e736c61636b2d656467652e636f6d2f5430434151303054552f726570726f2f356365613533623535333238323562342e706e67"> — is it possible to simplify this <img alt=":repro:" width="20" height="auto" src="https://camo.githubusercontent.com/62704ae9512b86ac1ba3d0b591c9245bf36db7c84940922ae8c92b8e898da36c/68747470733a2f2f656d6f6a692e736c61636b2d656467652e636f6d2f5430434151303054552f726570726f2f356365613533623535333238323562342e706e67"> to not use a Yarn workspace?

on witch branch // commit are you currently on?
i had that error before and fixed it.
try to 
`git checkout athe-12-next-font-randomlowercaseletterdefault`
because these packages are already renamed for some time to `@Athenetz-SV/util-{configname}-config`

**Comment by JackatDJL** [comment]
![image](https://github.com/user-attachments/assets/7d5086b1-3d18-4dc6-83e2-3998978d124d)
found it:
youre working on `main`
pls switch to `athe-12-next-font-randomlowercaseletterdefault`
or 
ill pullreq the current state to main

**Comment by JackatDJL** [comment]
you could use `main`
but before it comes to this error
firebase would be throwing errors because the api key (.env.public = "no api key")
is invalid

**Comment by samcx** [comment]
@JackatDJL I was on the correct branch earlier! Just tried again with the updated branch and was able to finally replicate. <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>

**Comment by JackatDJL** [comment]
Any Updates?

**Comment by JackatDJL** [comment]
```
┌ @athenetz-sv/wahlen#build > cache miss, executing 8ebbf711e66ee32f
│   ▲ Next.js 15.0.0
│   - Environments: .env.local
│
│    Creating an optimized production build ...
│  ⚠ Compiled with warnings
│
│ ../../node_modules/framer-motion/dist/cjs/index.js
│ Module not found: Can't resolve '@emotion/is-prop-valid' in 'D:\dev\Athenetz-SV\node_modules\framer-motion\dist\cjs'
│
│ Import trace for requested module:
│ ../../node_modules/framer-motion/dist/cjs/index.js
│ ../../packages/SV-UI/dist/layout/FloatingPanel.js
│ ./src/app/page.tsx
│
│    Linting and checking validity of types  .. ⨯ ESLint: Invalid Options: - Unknown options: useEslintrc, extensions - 'extensions' has been removed.
│  ✓ Linting and checking validity of types
│    Collecting page data  ...Error: Failed to collect configuration for /_not-found
│     at D:\dev\Athenetz-SV\node_modules\next\dist\build\utils.js:1130:23
│     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
│     at async Span.traceAsyncFn (D:\dev\Athenetz-SV\node_modules\next\dist\trace\trace.js:157:20) {
│   [cause]: TypeError: (0 , o.default) is not a function
│       at 21459 (D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:5021)
│       at t (D:\dev\Athenetz-SV\apps\wahlen\.next\server\webpack-runtime.js:1:128)
│       at D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:3069
│       at t.a (D:\dev\Athenetz-SV\apps\wahlen\.next\server\webpack-runtime.js:1:881)
│       at 76560 (D:\dev\Athenetz-SV\apps\wahlen\.next\server\app\_not-found\page.js:1:2810)
│       at Function.t (D:\dev\Athenetz-SV\apps\wahlen\.next\server\webpack-runtime.js:1:128)
│       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
│       at async getLayoutOrPageModule (D:\dev\Athenetz-SV\node_modules\next\dist\server\lib\app-dir-module.js:33:15)
│       at async collectAppPageSegments (D:\dev\Athenetz-SV\node_modules\next\dist\build\segment-config\app\app-segments.js:50:45)
│       at async D:\dev\Athenetz-SV\node_modules\next\dist\build\utils.js:1128:28
│ }
│
│ > Build error occurred
│ Error: Failed to collect page data for /_not-found
│     at D:\dev\Athenetz-SV\node_modules\next\dist\build\utils.js:1233:15
│     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
│   type: 'Error'
│ }
│    Collecting page data  .
│                           command finished with error: command (D:\dev\Athenetz-SV\apps\wahlen) C:\Users\jackr\AppData\Local\Temp\xfs-2f634292\yarn.cmd run build ex
│ ited (1)
└────>
@athenetz-sv/wahlen#build: command (D:\dev\Athenetz-SV\apps\wahlen) C:\Users\jackr\AppData\Local\Temp\xfs-2f634292\yarn.cmd run build exited (1)

 Tasks:    5 successful, 6 total
Cached:    5 cached, 6 total
  Time:    1m13.233s
Failed:    @athenetz-sv/wahlen#build
```

Tried with the JUST (2mins ago) released Next 15.0.0
No Progress:
`[cause]: TypeError: (0 , o.default) is not a function`

**Comment by JackatDJL** [comment]
Ive given up on next/fonts
I switched to Adobe Fonts / normal css classes
But ill keep this open because the issue isnt fixed yet

Ty

**Comment by samcx** [comment]
@JackatDJL Sorry for not getting to this!

Is there a reason why you need to use place the Font in package → import it from that versus just importing the font itself in your Layout?

**Comment by marcoshernanz** [comment]
Thanks for the report. This is the same underlying issue as #51476. `next/font` relies on a Next.js compiler transform, and calls from a separately built package reach Next after that transform is no longer possible. Defining the font in the Next app avoids the failure. Closing this in favor of #51476.
