### ISSUE TITLE
Docs: Page not jumping properly after google translate

### ISSUE THREAD

**Issue by RainbowXXX** [vercel/next.js#70742]
### What is the documentation issue?

I used google translate in the page and then after clicking on the link in Next Steps, I was redirected to the error page like this:
![image](https://github.com/user-attachments/assets/135664f4-65fb-4a08-b2e8-75eebf2011a0)

### Is there any context that might help us understand?

The error msg in browser console:
```
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at oI (1fe503da-8c7958a59066e455.js:1:86225)
    at o1 (1fe503da-8c7958a59066e455.js:1:95781)
    at o0 (1fe503da-8c7958a59066e455.js:1:92825)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:90403)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:90403)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:90403)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:90403)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:90403)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:90403)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:93584)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:90403)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
    at o0 (1fe503da-8c7958a59066e455.js:1:92817)
    at oZ (1fe503da-8c7958a59066e455.js:1:90281)
```

Browser: Chrome
Chrome version: 129.0.6668.72

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/defining-routes

**Comment by samcx** [comment]
@RainbowXXX Can you be more specific with your steps so we can try to replicate the issue (e.g., what language from and to did you translate)?

**Comment by ElectricCodeGuy** [comment]
Check your nested layout.tsx and add fragments <> </>

**Comment by AirboZH** [comment]
I consistently encounter this issue on the **Next.js official website** with a 100% reproduction rate.

## Steps to Reproduce:

1. Visit any documentation page on the Next.js official website.
2. Enable Google Translate and translate the page into another language.
3. Click to navigate to another page within the documentation.

## Error Image
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/b9f23985-9de9-4588-b538-333de2f570ee" />

```
2116-4e415962e68709f…vYhx6f9otDSgW7V5a:1 NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at o4 (ab8afc1f-9834963d3d3…9otDSgW7V5a:1:90427)
    at o2 (ab8afc1f-9834963d3d3…9otDSgW7V5a:1:89839)
```

**Comment by samcx** [comment]
@RainbowXXX @ATacoo We're currently revamping the Next.js documentation site, and can confirm this issue is not present in it. 🙏🏼

**Comment by dninomiya** [comment]
I have been struggling with this issue for over two years.
Accessing a nested page while the site is in a translated state causes a 100% crash.
This issue occurs not only in the official Next.js documentation but also on many sites built with Next.js.
I appreciate your support!

https://github.com/user-attachments/assets/dd154796-56a6-4f16-badd-f09bc8d46259

**Comment by icyJoseph** [comment]
Here's a good breakdown about this issue: https://martijnhols.nl/blog/everything-about-google-translate-crashing-react

I fixed it in the Next.js site a few months ago, there might be some floating fragment I forgot somewhere. 

I'll go ahead and close this issue, because AFAIK, the Next.js site is safe from this right now.
