### ISSUE TITLE
i18n configuration causes 500 error when certain malformed URLs are visited

### ISSUE THREAD

**Issue by Parker-Echo** [vercel/next.js#71131]
### Link to the code that reproduces this issue

https://github.com/Parker-Echo/nextjs-reproduction-app-bug

### To Reproduce

1. Start the server `next dev`.
2. Run `curl -k http://localhost:3000/\\\\\\%20../%20../%20../%20../%20../%20../foobar`
3. Observe it returns a 500 error and logs the following
```
Failed to handle request for /\\\%20../%20../%20../%20../%20../%20../foobar
TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at parseRelativeUrl (my-app/node_modules/next/dist/shared/lib/router/utils/parse-relative-url.js:16:68)
    at parseUrl (my-app/node_modules/next/dist/shared/lib/router/utils/parse-url.js:15:55)
    at requestHandlerImpl (my-app/node_modules/next/dist/server/lib/router-server.js:115:54)
    at Server.requestListener (my-app/node_modules/next/dist/server/lib/start-server.js:141:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_URL',
  input: '/\\\\\\%20../%20../%20../%20../%20../%20../etc/passwd/',
  base: 'http://n/'
}
```

### Current vs. Expected behavior

Following the steps from the previous section, I expect a redirect or a 404 error.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.183 // Latest available version is detected (15.0.0-canary.183).
  eslint-config-next: N/A
  react: 19.0.0-rc-2d16326d-20240930
  react-dom: 19.0.0-rc-2d16326d-20240930
  typescript: 5.3.3
Next.js Config:
```

### Which area(s) are affected? (Select all that apply)

Not sure, Internationalization (i18n), Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Other (Deployed)

### Additional context

I don't repro if I access the URL via postman or the browser, possibly because of different encodings. I reproduced against 14.2 as well. Only happens with i18n configured. 
Forum post: https://nextjs-forum.com/post/1293815757494288404

**Comment by miazakura01** [comment]
Hi! I'm working on a fix for this issue, picking up where @aurmartin's #71281 left off (closed without the test case requested by @ijjk).

Reproduced on Next.js 16.2.4 (latest stable) and 16.3.0-canary.4. While the HTTP response is a 308 redirect, the server logs are flooded with `TypeError [ERR_INVALID_URL]: Invalid URL` on every malformed request — noisy in production and a potential DoS surface.

Plan:
- Same fix as #71281: use `normalizeRepeatedSlashes` instead of `replace(/^\/+/, '/')` in `router-server.ts`
- Add an e2e test covering the original repro and a few related malformed URL patterns

Will open a draft PR shortly. Credit to @aurmartin for the original investigation and fix.
