### ISSUE TITLE
Codemod upgrade script does not consider the absence of the "dev" script in the package.json

### ISSUE THREAD

**Issue by imprakharshukla** [vercel/next.js#71597]
### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-vewqbk?file=package.json

### To Reproduce

1. Open the repro and run `npx @next/codemod@canary upgrade latest`
2. It should throw 
```bash
npx @next/codemod@canary upgrade latest
  Detected installed versions:
  - React: v18.3.1
  - Next.js: v14.2.9
TypeError: Cannot read properties of undefined (reading 'includes')
    at suggestTurbopack (/Users/prakharshukla/.npm/_npx/6a090669e21b4303/node_modules/@next/codemod/bin/upgrade.js:330:19)
    at runUpgrade (/Users/prakharshukla/.npm/_npx/6a090669e21b4303/node_modules/@next/codemod/bin/upgrade.js:152:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/Users/prakharshukla/.npm/_npx/6a090669e21b4303/node_modules/@next/codemod/bin/next-codemod.js:51:9)
```

### Current vs. Expected behavior

The current behaviour is throwing error if the dev script if not found.
We should check for the nullability of the devScript before trying to run `.includes` on the string.

Code: 
```
async function suggestTurbopack(packageJson: any): Promise<void> {
  const devScript: string = packageJson.scripts['dev']
  if (devScript.includes('--turbo')) return

  const responseTurbopack = await prompts(
    {
      type: 'confirm',
      name: 'enable',
      message: 'Enable Turbopack for next dev?',
      initial: true,
    },
    { onCancel }
  )

```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:31 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 11
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 9.8.0
Relevant Packages:
  next: 14.2.9 // An outdated version detected (latest is 15.0.0), upgrade is highly recommended!
  eslint-config-next: 14.2.15
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: standalone
 ⚠ An outdated version detected (latest is 15.0.0), upgrade is highly recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next dev (local), Other (Deployed)

**Comment by imprakharshukla** [comment]
PR create to fix this issue- #71598
