### ISSUE TITLE
Can’t upgrade project to Next.js 15 when using workspace React package

### ISSUE THREAD

**Issue by niels-bosman** [vercel/next.js#71613]
### Link to the code that reproduces this issue

https://github.com/niels-bosman/next-15-upgrade-issue-reproduction

## Requirements:

- Bun installed (I am on 1.1.32 which is the latest)
- Node installed (I am on 20.11.0)

## Steps to reproduce:

1. Run `bun install` in the root of this project
2. Run `bun run build` in the `./my-app` folder (this builds the package and the next app)

## Expected behavior:

The app should build and run without errors.

## Actual behavior:

The app errors with the following message:

```
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/react/cjs/react.production.js:489:33)
    at StyleRegistry (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/styled-jsx/dist/index/index.js:450:30)
    at Wc (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
Failed to build /_error: /404 after 1 attempts.

> Build error occurred
Error: Export encountered an error on /_error: /404, exiting the build.
    at exportPageWithRetry (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/dist/export/worker.js:289:31)
    at async Promise.all (index 0)
    at async /Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/dist/export/worker.js:319:35
    at async Object.exportPages (/Users/niels/Code/SlideSpeak/next-15-issue-repro/node_modules/next/dist/export/worker.js:314:5) {
  type: 'ExportPageError',
  code: 'NEXT_EXPORT_PAGE_ERROR'
}
   Generating static pages (0/5)  [    ]error: script "build:app" exited with code 1

```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 12
Binaries:
  Node: 20.11.0
  npm: 10.5.0
  Yarn: 1.22.21
  pnpm: 8.15.4
Relevant Packages:
  next: 15.0.0 // Latest available version is detected (15.0.0).
  eslint-config-next: 15.0.0
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module Resolution, Output (export/standalone), Runtime, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

This happens when linking to a package in a monorepo that exports react components. I expect this to all work the same as it did in Next 14.x.

**Comment by niels-bosman** [comment]
This is fixed when using React 19 with the app router. I still think the error message is very unclear and could be improved.

**Comment by niels-bosman** [comment]
Okay false alarm, issue still happening when building.

**Comment by notcharliee** [comment]
i had this same issue. rolling back to the release candidate fixed it for me

**Comment by ArsenyUkrainsky** [comment]
I have a similar problem when upgrading from RC 15 version. Removal.loc and node_modules did not change the situation.

```
TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (D:\work\loyalty\node_modules\styled-jsx\node_modules\react\cjs\react.production.js:489:33)
    at StyleRegistry (D:\work\loyalty\node_modules\styled-jsx\dist\index\index.js:450:30)
    at renderWithHooks (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4184:18)
    at renderElement (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4322:14)
    at retryNode (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4866:16)
    at renderNodeDestructive (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4684:7)
    at renderElement (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4618:11)
    at retryNode (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4866:16)
    at renderNodeDestructive (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4684:7)
    at renderElement (D:\work\loyalty\node_modules\react-dom\cjs\react-dom-server.edge.production.js:4618:11)
Export encountered an error on /_error: /500, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null
error Command failed with exit code 1.
```

Can you tell me how to fix it?

**Comment by niels-bosman** [comment]
@ArsenyUkrainsky For me, I had the wrong react RC versions in my package.json's. Please do `npx create-next-app` and copy over the deps it uses for react and react-dom.

**Comment by ArsenyUkrainsky** [comment]
@niels-bosman 
Thanks for the advice! Unfortunately, this method did not help me, the version was not suitable. However, I used version `19.0.0-rc-fb9a90fa48-20240614,` everything is OK with it.

**Comment by harrisrobin** [comment]
I'm also running into this and unfortunately @ArsenyUkrainsky 's fix did not work for me.

I made sure all my packages are using react19, a little stumped by this one.

**Comment by rharkor** [comment]
Same problem here, I am using npm workspace
