### ISSUE TITLE
Next.js 15 stable codemod has now caused my local font imports to produce hydration errors

### ISSUE THREAD

**Issue by tr1s** [vercel/next.js#71744]
I've updated the repo, simplified it, and created easy steps to reproduce this issue based off @timneutkens feedback. I'm editing the original comment here below to reflect all that.

### Link to the code that reproduces this issue

https://github.com/tr1s/trisanity-test

### To Reproduce

1. `git clone https://github.com/tr1s/trisanity-test.git`
1. `cd trisanity-test`
1. `npm i`
1. `npm run dev`

The hydration errors:

![CleanShot 2024-10-23 at 14 32 29@2x](https://github.com/user-attachments/assets/571924d5-5c4c-4d78-a0b0-651b6fac062a)

### Current vs. Expected behavior

Current behaviour: a working app with hydration errors
Expected behaviour: a working app without hydration errors

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.17.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Font (next/font)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I ran the Next.js 15 codemod and now I have hydration errors on my local font imports. I've tried with and without turbopack, same issues.

There are two ways to remove the hydration error:
1. Remove the default `src/app/layout.tsx`
1. Go to the `src/app/(frontend)/layout.tsx` file and remove the `className` block from the `<html> tag:

```
return (
	<html
		lang="en"
		className={`
        		${GTFAdieu.variable}
        		${GTFAdieu_Slanted.variable}
        		${GTFAdieu_Backslant.variable}
        		${Source_Sans_3.variable}
      		`}
	>
		<body>
			<Nav />
			<main role="main" id="main-content" tabIndex={-1}>
				{children}
			</main>
		</body>
	</html>
);
```

The `src/app/layout.tsx` was left as is so it wouldn't mess up any Sanity Studio UI. Then I created a `src/app/(frontend)/layout.tsx` where the layout for my frontend would live—this is where I imported my fonts. I was following along with [this Sanity tutorial](https://www.sanity.io/learn/course/content-driven-web-application-foundations) in which they did this.

For this setup when using a default layout and a nested (frontend) layout I was not getting any hydration errors until Next.js RC2 and beyond. RC1 was working fine, and that's what this tutorial was based off.

Here's my `fonts.js` that was working previously with Next 15 RC1:

```
import localFont from 'next/font/local';

export const GTFAdieu = localFont({
	variable: '--font-GTFAdieu',
	src: [
		{
			path: '../../public/fonts/GTFAdieuTRIAL-Light.otf',
			weight: '300',
			style: 'normal',
		},
		{
			path: '../../public/fonts/GTFAdieuTRIAL-Regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/fonts/GTFAdieuTRIAL-Bold.otf',
			weight: '700',
			style: 'normal',
		},
	],
});

export const GTFAdieu_Backslant = localFont({
	variable: '--font-GTFAdieu-Backslant',
	src: [
		{
			path: '../../public/fonts/GTFAdieuTRIAL-LightBackslant.otf',
			weight: '300',
			style: 'italic',
		},
		{
			path: '../../public/fonts/GTFAdieuTRIAL-RegularBackslant.otf',
			weight: '400',
			style: 'italic',
		},
		{
			path: '../../public/fonts/GTFAdieuTRIAL-BoldBackslant.otf',
			weight: '700',
			style: 'italic',
		},
	],
});

export const GTFAdieu_Slanted = localFont({
	variable: '--font-GTFAdieu-Slanted',
	src: [
		{
			path: '../../public/fonts/GTFAdieuTRIAL-RegularSlanted.otf',
			weight: '400',
			style: 'italic',
		},
		{
			path: '../../public/fonts/GTFAdieuTRIAL-BoldSlanted.otf',
			weight: '700',
			style: 'italic',
		},
	],
});

export const Source_Sans_3 = localFont({
	variable: '--font-Source-Sans-3',
	src: [
		{
			path: '../../public/fonts/source-sans-3-v4-latin-regular.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/fonts/source-sans-3-v4-latin-700.woff2',
			weight: '700',
			style: 'normal',
		},
	],
});
```

That's about all the context I can provide. Given that, do we know what may be going on here?

**Comment by afkhalid** [comment]
I am facing the same issue unfortunately

**Comment by user97116** [comment]
I am also getting hydration error on default `npx create-next-app@latest`

**Comment by tr1s** [comment]
Interesting.

I'm surprised this wasn't caught and there's no comment about what's going on yet. Hopefully there's a fix in the next update!

**Comment by user97116** [comment]
actually this issues caused by browser extensions @tr1s

**Comment by tr1s** [comment]
Ah okay, different issue for you then. My hydration errors are happening even on incognito with no browser extensions.

**Comment by tr1s** [comment]
Update: The latest Next.js `15.0.2` did not resolve this issue.

**Comment by qasimgit** [comment]
same here, getting this error even on incognito mode, just created a latest nextjs project with turbopack
<img width="1059" alt="Screenshot 2024-10-30 at 7 39 33 PM" src="https://github.com/user-attachments/assets/d6cb5c96-442d-453b-8ef5-f6905fe10075">

**Comment by MasterProvider** [comment]
> Update: The latest Next.js `15.0.2` did not resolve this issue.

yeah still hydration warning occur

**Comment by timneutkens** [comment]
@tr1s I'm unable to run the reproduction repository, seems there's steps missing. During boot it ends up with:

```
Error: Failed to load configuration file "/project/workspace/sanity.config.ts":
Missing environment variable: NEXT_PUBLIC_SANITY_DATASET
    at assertValue (/project/workspace/src/sanity/env.ts:16:11)
    at Object.<anonymous> (/project/workspace/src/sanity/env.ts:4:24)
    at Module._compile (/project/workspace/node_modules/esbuild-register/dist/node.js:2258:26)
    at Object.newLoader (/project/workspace/node_modules/esbuild-register/dist/node.js:2262:9)

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

Can you narrow down the reproduction so that it can run with a default Next.js setup?

@qasimgit you have some browser extension modifying the page

@MasterProvider your comment is not helpful, please provide more details, likely same cause though, chrome extension.

**Comment by XNeyMo** [comment]
> same here, getting this error even on incognito mode, just created a latest nextjs project with turbopack <img alt="Screenshot 2024-10-30 at 7 39 33 PM" width="1059" src="https://private-user-images.githubusercontent.com/55051250/381598179-d6cb5c96-442d-453b-8ef5-f6905fe10075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTc3OTcsIm5iZiI6MTczMDM5NzQ5NywicGF0aCI6Ii81NTA1MTI1MC8zODE1OTgxNzktZDZjYjVjOTYtNDQyZC00NTNiLThlZjUtZjY5MDVmZTEwMDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE3NTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWY2ZTk5YWJjN2M3MTNjOGFjYzFmMGEwZWU0Njc5YzM0MDZhMGU2ZjQ5NGQ1ZjVhZmYzZTE5ZWNmNzM0YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gff5ffr5hhUi9wpAqJiWFLXD8ErycOt-xq15GRqD0n8">

I had the same error, I tried incognito and I didn't get the error (I had all the extensions disabled), so I tried one by one to find out which one was giving me the error, I recommend that you check the browser extensions. In my case, 2 extensions caused the error.

And if I want to be more specific, the extension that gave me your same error was [ColorZilla](https://addons.mozilla.org/en-US/firefox/addon/colorzilla/).

**Comment by tr1s** [comment]
> Can you narrow down the reproduction so that it can run with a default Next.js setup?

@timneutkens I've created a new repo, simplified it, and removed Sanity so you can run it. Here are the new steps:

1. `git clone https://github.com/tr1s/trisanity-test.git`
1. `cd trisanity-test`
1. `npm i`
1. `npm run dev`

I've learned in doing this that the problem lies in the `/src/app/layout.tsx`. Once I remove that file the error goes away.

The `/src/app/layout.tsx` was left as is so it wouldn't mess up any Sanity Studio UI. Then I created a `/src/app/(frontend)/layout.tsx` where the layout for my frontend would live. This is where I imported my fonts. I was following along with [this Sanity tutorial](https://www.sanity.io/learn/course/content-driven-web-application-foundations) in which they did this.

For this setup using a default layout and a nested (frontend) layout I was not getting an hydration errors until the Next.js RC2 and beyond. RC1 was working fine, and that's what this tutorial was based off. 

So the two ways to remove this error is by 1. removing the base default `layout.tsx` or removed the fonts from the nested (fronted) `layout.tsx`.

That's about all the context I can provide. Given that, do you know what may be going on?

**Comment by sakilanwar12** [comment]
I'm also facing this issue. I installed Next.js 15 using the command **npx create-next-app@latest**. However, when I try to run it, the browser shows an error. Interestingly, when I try in incognito mode, there’s no error.

**Comment by qasimgit** [comment]
> @tr1s I'm unable to run the reproduction repository, seems there's steps missing. During boot it ends up with:
> 
> ```
> Error: Failed to load configuration file "/project/workspace/sanity.config.ts":
> Missing environment variable: NEXT_PUBLIC_SANITY_DATASET
>     at assertValue (/project/workspace/src/sanity/env.ts:16:11)
>     at Object.<anonymous> (/project/workspace/src/sanity/env.ts:4:24)
>     at Module._compile (/project/workspace/node_modules/esbuild-register/dist/node.js:2258:26)
>     at Object.newLoader (/project/workspace/node_modules/esbuild-register/dist/node.js:2262:9)
> 
>  *  The terminal process terminated with exit code: 1. 
>  *  Terminal will be reused by tasks, press any key to close it. 
> ```
> 
> Can you narrow down the reproduction so that it can run with a default Next.js setup?
> 
> @qasimgit you have some browser extension modifying the page
> 
> @MasterProvider your comment is not helpful, please provide more details, likely same cause though, chrome extension.

@timneutkens yes, it was colorzilla extension that was causing the issue, but now I am getting similar issue with the poppins font I have added.



here is my layout code

```
import type { Metadata } from "next";

import { Providers } from "./providers";
import { poppins } from "../fonts";
import "../globals.css";

export const metadata: Metadata = {
  title: "Test",
  description: "Test",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
}) {
  const awaitedParams = await params;
  return (
    <html lang={awaitedParams.locale} suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <Providers locale={awaitedParams.locale}>{children}</Providers>
      </body>
    </html>
  );
}

```

and here is my font code

```
import { Poppins } from "next/font/google";

export const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});
```


I have also added fonts in globals.css and tailwind.config.ts

body {
  /* font-family: Arial, Helvetica, sans-serif; */
  font-family: var(--font-poppins);
}

config

  theme: {
    fontFamily: {
      poppins: ["var(--font-poppins)"],
    },

**Comment by tr1s** [comment]
@timneutkens I forgot to link to my new testing repo for simple steps to reproduce so I've now updated my previous comment and the original post with all the new and correct information.

**Comment by AvivHagag** [comment]
i solve it by removing Urban VPN from extensions

**Comment by tr1s** [comment]
So my hydration errors were fixed by removing the extra `<html>` and `<body>` tags in my nested layouts. I had to move my fonts to the main layout, and any components like <Nav> had to be moved to the nested layouts so it wouldn't show up in the Sanity Studio UI.

I'm assuming something changed in the latest update that made these appear as errors. Next.15 is supposed to have more clear hydration errors but in this case that doesn't appear to be true. 

For anyone interested [here's the PR that fixed it](https://github.com/tr1s/trisanity/commit/17ff0d7befb7d2f475a976b3215d56eca11ac632#diff-60f30b12349263a978b99cebf28ed001d6f884d53122bf8175dd09412b4f22c9L36).

**Comment by afatoga** [comment]
I resolved it by adding same classname into html tag of both layouts

`
// app/layout.tsx
import { myFont } from './localFonts'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang='en'
      className={myFont.className}
    >
      {children}
    </html>
  )
}

=====================

// app/(frontend)/layout.tsx
import { myFont } from './localFonts'

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html
      lang='en'
      className={myFont.className}
    >
      <body>
 ...
 </body>
 </html>)
}
`

**Comment by jiandandkl** [comment]
I solve it by removing Trancy from the extensions

**Comment by ahmadyusufcodes** [comment]
All I did was change

`import localFont from "@next/font/local";`

to

`import localFont from "next/font/local";`

and it's working fine now

**Comment by ITC-Jason** [comment]
> turbopack

It's not turbopack issue

**Comment by lazakrisz** [comment]
I've had a similar issue, sometimes I would get a hydration error, other times not, there was a race condition, it turned out to be a Chrome Extension issue, might make sense to check that (in my case it was Robots Exclusion Checker).

**Comment by marcoshernanz** [comment]
Thanks for the report. I can reproduce the warning, but it comes from rendering `<html>` and `<body>` in both the top-level and nested layouts, not from `next/font` or the upgrade codemod. The follow-up confirms that removing the extra document tags fixes it.

Only a root layout should render `<html>` and `<body>`. If you need multiple root layouts, remove the top-level layout and define a root layout in each route group: [docs](https://nextjs.org/docs/app/getting-started/project-structure#creating-multiple-root-layouts). Closing since this is caused by an unsupported layout structure.
