### ISSUE TITLE
Next 15 - Application Error on page routing in local development with Brave Browser when window.localStorage isn't available

### ISSUE THREAD

**Issue by requestmethod** [vercel/next.js#72046]
### Link to the code that reproduces this issue

https://github.com/requestmethod/localstorage-error

### To Reproduce

1. Start application
2. Open Brave Browser (latest) with "Sheids" on set to Block all cookies.
3. Clicking the test link will result in Application Error due to the window.localStorage not being available.

![Screenshot 2024-10-29 at 5 01 27 PM](https://github.com/user-attachments/assets/ec29b899-323d-45da-a8d7-f08109da32a5)

```
app-router.js:52 SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at react-stack-bottom-frame (react-dom-client.development.js:22422:20)
    at runWithFiberInDEV (react-dom-client.development.js:544:16)
    at commitHookEffectListMount (react-dom-client.development.js:10739:29)
    at commitHookPassiveMountEffects (react-dom-client.development.js:10859:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12629:13)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12622:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12622:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12622:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12622:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12622:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12731:11)
    at recursivelyTraversePassiveMountEffects (react-dom-client.development.js:12603:11)
    at commitPassiveMountOnFiber (react-dom-client.development.js:12633:11)
    at flushPassiveEffects (react-dom-client.development.js:15375:13)
    at eval (react-dom-client.development.js:15243:11)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:44:48)

The above error occurred in the <HotReload> component. It was handled by the <ErrorBoundaryHandler> error boundary.
```

### Current vs. Expected behavior

Application should not error when window.localStorage is blocked from use.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 98304
  Available CPU cores: 12
Binaries:
  Node: 23.1.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by icyJoseph** [comment]
I think I have got a fix for this, or at least, I understand the issue, and why one of the local storage accesses is well handled, and the other is not. PR coming up!
