### ISSUE TITLE
Getting Turbopack fatal error  while trying to start and run.

### ISSUE THREAD

**Issue by ozanusug** [vercel/next.js#72196]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/withered-https-go8s7s

### To Reproduce

---------------------------
Panic: panicked at turbopack/crates/turbo-tasks-fs/src/glob.rs:179:25:
not yet implemented: glob char sequences are not implemented yet
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: start_thread
  35: clone

### Current vs. Expected behavior

While i am trying to start next typescript project i am getting fatal turbopack error, FATAL: An unexpected Turbopack error occurred. Please report the content of log.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Debian 5.10.149-1 (2022-10-17)
  Available memory (MB): 24048
  Available CPU cores: 10
Binaries:
  Node: 18.20.4
  npm: 10.9.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by AndreasWintherMoen** [comment]
Getting a very similar error with a nearly clean Next 15 project.

**Comment by timneutkens** [comment]
Hey! We'd love to investigate this but the shared codesandbox does not reproduce the issue, can you share a reproduction?

I.e. when running your sandbox it works: https://codesandbox.io/p/devbox/hardcore-fermat-z4fttc?file=%2Fapp%2Fpage.tsx&workspaceId=062b139a-c054-40fe-bbf5-0210d48b9dd0

**Comment by szwabodev** [comment]
Hello, I had exact same error when trying to run latest stable NextJS15 with tailwind. In my case the issue was related with the `content` config in `tailwind.config.ts` where one line was causing this fatal error:


```
export const content = [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",

    // The line below causes fatal error in turbo mode
    "./src/app/[locale]/**/*.{js,ts,jsx,tsx}",
];
```

Once I removed `[locale]` part from this content config, it built fine with turbo. Maybe it'll help some of you.

**Comment by frdepiaggio** [comment]
Any updates on this? I ran into the same error when an intercepted route with dynamic param is defined -> `(.)[id]`

**Comment by cipriancaba** [comment]
Seeing this in our monorepo too

doesn't seem to be tailwind related, we do have a couple of intercept routes, too many to change, same panic

```
Panic: panicked at turbopack/crates/turbo-tasks-fs/src/glob.rs:180:25:
not yet implemented: glob char sequences are not implemented yet
Backtrace:    0: _napi_register_module_v1
   1: <unknown>
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: _BrotliDecoderVersion
   8: _BrotliDecoderVersion
   9: _BrotliDecoderVersion
  10: _BrotliDecoderVersion

```

**Comment by roelvan** [comment]
> Seeing this in our monorepo too
> 
> doesn't seem to be tailwind related, we do have a couple of intercept routes, too many to change, same panic
> 
> ```
> Panic: panicked at turbopack/crates/turbo-tasks-fs/src/glob.rs:180:25:
> not yet implemented: glob char sequences are not implemented yet
> Backtrace:    0: _napi_register_module_v1
>    1: <unknown>
>    2: _napi_register_module_v1
>    3: _napi_register_module_v1
>    4: _napi_register_module_v1
>    5: _napi_register_module_v1
>    6: _napi_register_module_v1
>    7: _BrotliDecoderVersion
>    8: _BrotliDecoderVersion
>    9: _BrotliDecoderVersion
>   10: _BrotliDecoderVersion
> ```

I get the same "glob char" error after upgrading to tailwind v4 with `npx @tailwindcss/upgrade@next`.

**Comment by cipriancaba** [comment]
@ijjk 🙏 can we get some love on this issue please?

**Comment by cipriancaba** [comment]
> > Seeing this in our monorepo too
> > doesn't seem to be tailwind related, we do have a couple of intercept routes, too many to change, same panic
> > ```
> > Panic: panicked at turbopack/crates/turbo-tasks-fs/src/glob.rs:180:25:
> > not yet implemented: glob char sequences are not implemented yet
> > Backtrace:    0: _napi_register_module_v1
> >    1: <unknown>
> >    2: _napi_register_module_v1
> >    3: _napi_register_module_v1
> >    4: _napi_register_module_v1
> >    5: _napi_register_module_v1
> >    6: _napi_register_module_v1
> >    7: _BrotliDecoderVersion
> >    8: _BrotliDecoderVersion
> >    9: _BrotliDecoderVersion
> >   10: _BrotliDecoderVersion
> > ```
> 
> I get the same "glob char" error after upgrading to tailwind v4 with `npx @tailwindcss/upgrade@next`.

We actually upgraded recently to tailwind v4 as well

**Comment by cipriancaba** [comment]
So basically it works if we remove all the route intercepts, @ijjk 

Pretty sure this should be an easy fix

![Image](https://github.com/user-attachments/assets/df9b689e-f602-47e3-b154-d0d3769c8f07)

**Comment by SebassNoob** [comment]
I ran into this issue when upgrading to tailwind 4.

I can reproduce a more minimal version [here](https://github.com/SebassNoob/next-72196-repro).
Here were the steps used to create this repro:
1. ``npx create-next-app@latest`` with default options but no to tailwindcss.
2. Follow tailwind v3 installation guide https://v3.tailwindcss.com/docs/guides/nextjs (steps 2-6)
3. Update to v4 with ``@tailwindcss/upgrade@next``
4. In the app directory, create ``@test/(.)[test]/page.tsx`` and put a react component in it.
5. Run the server ``npm run dev`` and open it in browser.
6. This issue occurs.

I'm not sure if this is the most minimal reproduction that is possible, but is the closest match to my current situation.

**Comment by timdorr** [comment]
@SebassNoob I was able to fix this by installing the `@tailwindcss/postcss` package in my project.

**Comment by khuezy** [comment]
> [@SebassNoob](https://github.com/SebassNoob) I was able to fix this by installing the `@tailwindcss/postcss` package in my project.

really? I'm still getting the `glob char sequences are not implemented yet` error.

**Comment by ek-kpr** [comment]
Same issue - when Upgrading to tailwind. We also use intercepted route, changing it to (..) did not work. However removing the route / folder
