### ISSUE TITLE
Next15 MDX  setup guide build failed on ubuntu24.04 & node v23.1.0

### ISSUE THREAD

**Issue by guijiangheng** [vercel/next.js#72544]
### Link to the code that reproduces this issue

https://github.com/guijiangheng/next15-node23-build-failed

### To Reproduce

Create a new next project with create-next-app@lastet, fllow the Offcial MDX setup guide, add none custom code. Run pnpm dev success,  and page.mdx renders correctly. However next build exit success but with no output.

Here is the reproduce repo:  [git repo](https://github.com/guijiangheng/next15-node23-build-failed)

```
➜  build-test git:(main) node -v  
v23.1.0
➜  build-test git:(main) npm run build

> build-test@0.1.0 build
> next build

   ▲ Next.js 15.0.3
   - Experiments (use with caution):
     · turbo

   Creating an optimized production build ...
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
➜  build-test git:(main) npm run start

> build-test@0.1.0 start
> next start

   ▲ Next.js 15.0.3
   - Local:        http://localhost:3000

 ✓ Starting...
Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at setupFsCheck (/home/gui/Desktop/build-test/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/server/lib/router-utils/filesystem.js:148:19)
    at async initialize (/home/gui/Desktop/build-test/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/server/lib/router-server.js:65:23)
    at async Server.<anonymous> (/home/gui/Desktop/build-test/node_modules/.pnpm/next@15.0.3_react-dom@19.0.0-rc-66855b96-20241106_react@19.0.0-rc-66855b96-20241106__react@19.0.0-rc-66855b96-20241106/node_modules/next/dist/server/lib/start-server.js:266:36)
➜  build-test git:(main) 
```

### Current vs. Expected behavior

build success

### Provide environment information

```bash
(node:46999) ExperimentalWarning: CommonJS module /home/gui/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /home/gui/.nvm/versions/node/v23.1.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/bin/sh: 1: yarn: not found

Operating System:
  Platform: linux
  Arch: x64
  Version: #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024
  Available memory (MB): 15916
  Available CPU cores: 16
Binaries:
  Node: 23.1.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Markdown (MDX)

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by samcx** [comment]
@guijiangheng Can you make sure the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> is the same as the error shown? In the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> , there is no usage of experimental `turbo` flag the `next.config.ts`.

**Comment by guijiangheng** [comment]
[Screencast from 2024-11-14 13-59-23.webm](https://github.com/user-attachments/assets/f72d59e3-25be-41c7-9bce-c735415acd45)
Hi, I record a capture, it build success on node 22, but faild on node 23. I'm not a node expert, but I think it should also build success on node 23. @samcx

**Comment by redbmk** [comment]
@samcx I don't have that flag either and I'm not running with `--turbo` or `--turbopack`, but it still shows me that when I start up with 15.0.2 or 15.0.3. I was wondering if turbo was opted in by default now or if there's a bug in how it detects it on startup.

**Comment by samcx** [comment]
@redbmk Could be a Node.js issue. Can you try a different Node.js version (e.g., 22.1.0)?

**Comment by redbmk** [comment]
@samcx I'm using 22.10.0, but I actually tracked it down - the `createMDX` function was setting `experimental.turbo` until a commit 3 days ago: https://github.com/vercel/next.js/commit/560bb2668a262f1da129f28c136c8f88872c27f3

A workaround in the meantime would be:

```typescript
const config = withMDX(nextConfig);
config.experimental.turbo = undefined;

export default config;
```

Not sure if that really has anything to do with OP's issue though

**Comment by NessajCN** [comment]
Not sure if I encountered the same issue but I fixed mine with an extra option with webpack 
```ts title="@/next.config.ts"
const nextConfig: NextConfig = {
  // Configure `pageExtensions` to include markdown and MDX files
  pageExtensions: ["js", "jsx", "md", "mdx", "ts", "tsx"],
  /* config options here */
  webpack: (config, options) => {
    config.snapshot.immutablePaths = [/^\/home$/, /^\/$/];
    return config;
  },
};
```
[Reference](https://github.com/webpack/webpack/discussions/16417)

**Comment by samcx** [comment]
@guijiangheng I was not able to replicate this on this version of node v23 and the latest package versions.

![CleanShot 2025-01-08 at 12 06 33@2x](https://github.com/user-attachments/assets/26836c0b-c0e9-425b-9c3a-2918b74967e6)
