### ISSUE TITLE
Parallel Intercepted routes not working when accessed from 404 erorpages

### ISSUE THREAD

**Issue by itsjavi** [vercel/next.js#72541]
### Link to the code that reproduces this issue

https://github.com/itsjavi/nextjs-demos/tree/issue/parallel-intercepted-404

### To Reproduce

1. Add a parallel intercepted route [like in this example](https://github.com/itsjavi/nextjs-demos/tree/main/src/app)
3. Add an error.tsx page to your app
4. Add support for the `@modal` slot in your layout.tsx props.
5. Add a Link in your layout.tsx, linking to the intercepted route
6. Navigate to any non-existing route to trigger a 404 error page
7. Click to the link of the layout that would trigger the intercepted route

#### On `next dev`
When accessing Parallel Intercepted routes from a 404 page, it triggers the following client-side error:

```
UI:

Application error: a client-side exception has occurred (see the browser console for more information).

Console:

app-router.ts:52 TypeError: initialTree is not iterable
    at applyPatch (apply-router-state-patch-to-tree.ts:17:51)
    at applyRouterStatePatchToTree (apply-router-state-patch-to-tree.ts:107:26)
    at navigate-reducer.ts:208:50

The above error occurred in the <Router> component. It was handled by the <ErrorBoundaryHandler> error boundary.
```

#### On `next start`

On `next start`, after build, navigating to the intercepted route from a 404 page works, but calling router.back() will trigger the same error again.

### Expected behavior

- The intercepted route content is shown on 404 pages, when navigating to that route.
- router.back() works as expected in all the above scenarios.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: N/A
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

- Repository to reproduce the issue: https://github.com/itsjavi/nextjs-demos/tree/issue/parallel-intercepted-404
- PR with the problematic changes: https://github.com/itsjavi/nextjs-demos/pull/1/files

**Comment by HM-Suiji** [comment]
I meet the error too. But my error is more strict. When I go into my intercepted route, I can't see anything, but the real dom is existing which can be seen in devtools.

**Comment by flygomel** [comment]
same here 
`"next": "15.1.4"`

**Comment by zerocsss** [comment]
same here
"next": "15.2.3"

**Comment by mikeb1986** [comment]
I am experiencing the same issue.

With slot containing only default.tsx
- navigate to any invalid url to get 404 page. try to navigate to "/" with Link, navigation is fine

With slot containing both default.tsx and page.tsx
- navigate to any invalid url to get 404 page. try to navigate to "/" with Link, error is observed
- Uncaught Error: initialTree is not iterable

**Comment by alexnaish** [comment]
This is still an issue with the latest releases (next@15.3.1).

We were attempting to use this for a feature to pop up a cart overlay upon clicking the "view cart" link but also allowing a hardlink to a cart details page.

As a workaround, we're going to remove the intercept routes and manually update the URL upon the mount of the overlay component. It should achieve the same effect...

**Comment by accountunavaible** [comment]
still has issue on version:     "next": "15.5.5",

but I did this way to temp resolve it. replace Link with normal anchor element. Since it is just 404 page, I feel that's ok 

{/* eslint-disable-next-line @next/next/no-html-link-for-pages */}

`
      <a
        href="/"
        className="text-sm"
      >
         back home
      </a>
`
