### ISSUE TITLE
Error when initializing Next.js project with TypeScript (v14.2.17 and v15)

### ISSUE THREAD

**Issue by francistinao** [vercel/next.js#72563]
### Link to the code that reproduces this issue

https://github.com/GarudaFX/next-init-issue

### To Reproduce

1. Clone repository
2. install dependencies
3. Run "npm run dev"

### Current vs. Expected behavior

I initialized a new project using next's latest version. Once everything was set up, I ran the command npm run dev. However, during the installation of dependencies, It did not recognize tsconfig.json or the typescript library being installed.

```
  ▲ Next.js 15.0.3 (Turbopack)
   - Local:        http://localhost:3000

 ✓ Starting...
It looks like you're trying to use TypeScript but do not have the required package(s) installed.
Installing dependencies

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your app and pages directories).


Installing devDependencies (npm):
- typescript
- @types/node


up to date, audited 29 packages in 3s

found 0 vulnerabilities
```

After that, this error persists:

```
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at endsWith (node_modules\next\src\server\require-hook.ts:60:14)
    at require (node_modules\next\src\lib\verify-typescript-setup.ts:110:6)
    at async verifyTypeScript (node_modules\next\src\server\lib\router-utils\setup-dev-bundler.ts:134:23)
    at async startWatcher (node_modules\next\src\server\lib\router-utils\setup-dev-bundler.ts:162:26)
    at async setupDevBundler (node_modules\next\src\server\lib\router-utils\setup-dev-bundler.ts:1109:17)
    at async Span.traceAsyncFn (node_modules\next\src\trace\trace.ts:143:13)
    at async initialize (node_modules\next\src\server\lib\router-server.ts:135:25)
    at async Server.<anonymous> (node_modules\next\src\server\lib\start-server.ts:316:27)
```
The expected behavior is that the Next.js server should start without issues. However, upon initialization, Next.js incorrectly tries to configure TypeScript even though the configuration has been done during the installation of dependencies. This results in an error preventing the development server from starting.

Expected Behavior:
The Next.js development server should start without errors.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 7931
  Available CPU cores: 8
Binaries:
  Node: 22.11.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 8.6.12
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: N/A
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by abhiya492** [comment]
# Remove existing setup  
rm -rf node_modules package-lock.json  

# Clean reinstall with TypeScript  
npm install next@latest react@latest react-dom@latest typescript @types/node @types/react  

# Restart development server  
npm run dev




try this

**Comment by francistinao** [comment]
Thanks for the response! I also tried your steps and the issue persists. I also updated the version of my node and npm

**Comment by francispham** [comment]
I think I get the same problem:
1. Initializing a new project
2. Run the app and get a 500 Error with this type error in the terminal `TypeError: trace.getSpanContext is not a function`.

![Image](https://github.com/user-attachments/assets/671e6c54-7ec7-4af4-8ab8-0a1bb342593c)

![Image](https://github.com/user-attachments/assets/ac9c3bd3-dabe-426f-be8f-5785e46bb221)

I tried @abhiya492's [suggestion](https://github.com/vercel/next.js/issues/72563#issuecomment-2468343381) but it didn't work!

**Comment by francistinao** [comment]
Hey, @francispham. I solved this problem. What I did was downgrade my node version to 20.18.1 then initialize Next again
