### ISSUE TITLE
Navigating out of "Not Found" page gives error if Parallel routing exists

### ISSUE THREAD

**Issue by XEngine** [vercel/next.js#73362]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/gallant-kalam-2xqmnr?workspaceId=08193210-3c43-4dee-852a-15fcfd6a6e98

### To Reproduce
Fork the sandbox to see error in terminal.

If you have parallel routes defined somewhere in the project and put it inside layout, eventhough it successfully redirects, nextjs throws error when inside notfound page with a link. 

I have tried my best to log what's undefined at 0 index, NextJS gives this :
{ children: [ '/_not-found', { children: [Array] } ] } children
{ children: [ '/_not-found', { children: [Array] } ] } testRoute

it tries to reach parallel route slot name but only has children.

In order to replecate the issue : 
1 - Have a parallel route and a interceptor route inside
2 - ```<Link>``` inside notfound page.
3 - Go to notfound page (force nextjs give not found- go to any route that doesn't exists)
4 - click on the link.

```
 ⨯ next/dist/src/server/app-render/walk-tree-with-flight-router-state.tsx (238:50) @ walkTreeWithFlightRouterState
 ⨯ TypeError: Cannot read properties of undefined (reading '0')
    at async doRender (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/base-server.ts:2660:21)
    at async responseGenerator (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/base-server.ts:3021:21)
    at async DevServer.renderToResponseWithComponentsImpl (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/base-server.ts:3033:23)
    at async DevServer.renderPageComponent (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/base-server.ts:3613:15)
    at async DevServer.renderToResponseImpl (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/base-server.ts:3675:23)
    at async DevServer.pipeImpl (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/base-server.ts:1698:20)
    at async NextNodeServer.handleCatchallRenderRequest (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/next-server.ts:1046:6)
    at async DevServer.handleRequestImpl (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/base-server.ts:1463:8)
    at async (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/dev/next-dev-server.ts:512:13)
    at async Span.traceAsyncFn (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/trace/trace.ts:143:13)
    at async DevServer.handleRequest (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/dev/next-dev-server.ts:510:19)
    at async invokeRender (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/lib/router-server.ts:284:10)
    at async handleRequest (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/lib/router-server.ts:530:15)
    at async requestHandlerImpl (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/lib/router-server.ts:576:6)
    at async Server.requestListener (node_modules/.pnpm/next@15.0.4-canary.31_react-dom@19.0.0-rc-b01722d5-20241114_react@19.0.0-rc-b01722d5-20241114/node_modules/next/src/server/lib/start-server.ts:152:6) {
  page: '/'
}
  236 |         subPath[0] === DEFAULT_SEGMENT_KEY &&
  237 |         flightRouterState &&
> 238 |         !!flightRouterState[1][parallelRouteKey][0] &&
      |                                                  ^
  239 |         flightRouterState[1][parallelRouteKey][3] !== 'refetch'
  240 |       ) {
  241 |         continue
  ```

### Current vs. Expected behavior

Current:
Throws an error. 

Expected:
Should not throw an error

### Provide environment information

```bash
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.4-canary.31 // Latest available version is detected (15.0.4-canary.31).
  eslint-config-next: N/A
  react: 19.0.0-rc-b01722d5-20241114
  react-dom: 19.0.0-rc-b01722d5-20241114
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation, Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Other (Deployed)

### Additional context

We are currently using ^14 in production the issue exists. My sandbox (attached to issue) is ^15 canary.31 still have this issue.

![image](https://github.com/user-attachments/assets/5dfc85fe-7c07-487f-9361-53cc3ded3a93)

**Comment by cbix** [comment]
Facing a similar issue, where I have individual not-found components defined for my main layout and in the slot itself. In situations where the component rendered inside the slot throws a 404 its error component is rendered properly, but navigating away from that throws a client-side error in `useActionQueue`:
```
Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom-client.development.js:6979:17)
    at updateReducer (react-dom-client.development.js:7098:18)
    at updateTransition (react-dom-client.development.js:8106:31)
    at Object.useTransition (react-dom-client.development.js:24197:16)
    at exports.useTransition (react.development.js:1266:34)
    at useAppDevRenderingIndicator (use-app-dev-rendering-indicator.js:14:67)
    at useActionQueue (use-action-queue.js:52:42)
    at Router (app-router.js:167:54)
    at Object.react_stack_bottom_frame (react-dom-client.development.js:23584:20)
    at renderWithHooks (react-dom-client.development.js:6793:22)
    at updateFunctionComponent (react-dom-client.development.js:9247:19)
    at beginWork (react-dom-client.development.js:10858:18)
    at runWithFiberInDEV (react-dom-client.development.js:872:30)
    at performUnitOfWork (react-dom-client.development.js:15727:22)
    at workLoopSync (react-dom-client.development.js:15547:41)
    at renderRootSync (react-dom-client.development.js:15527:11)
    at performWorkOnRoot (react-dom-client.development.js:15034:44)
    at performSyncWorkOnRoot (react-dom-client.development.js:16831:7)
    at flushSyncWorkAcrossRoots_impl (react-dom-client.development.js:16677:21)
    at processRootScheduleInMicrotask (react-dom-client.development.js:16715:9)
    at eval (react-dom-client.development.js:16850:13)
```

**Comment by christopherjohnson3028-stack** [comment]
I am facing a similar problem as well

**Comment by spencerwalsh651-cmyk** [comment]
Hello is there any updates on this?

**Comment by marcoshernanz** [comment]
Thanks for the report. This is the same parallel-route navigation failure from a not-found state tracked in #72541. Leaving the 404 route restores an incompatible parallel-slot tree and causes the navigation error. Closing as a duplicate so the routing investigation stays consolidated.
