### ISSUE TITLE
Cannot enable incremental PPR in a page file that is marked with 'use cache'

### ISSUE THREAD

**Issue by focux** [vercel/next.js#73902]
### Link to the code that reproduces this issue

https://github.com/focux/dynamicio-with-inc-ppr-repro

### To Reproduce

1. Start the app
2. Run `npm run build`

### Current vs. Expected behavior

When you try to build the app, it throws this error:
```
Error:   x Only async functions are allowed to be exported in a "use cache" file.

 | export const experimental_ppr = true;
```

I would expect the `use cache` directive to work with incremental PPR. It currently work when `ppr: true` and not incremental.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.22
  pnpm: 9.15.0
Relevant Packages:
  next: 15.1.1-canary.2 // Latest available version is detected (15.1.1-canary.2).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

dynamicIO, Partial Prerendering (PPR)

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by char-ptr** [comment]
this is also the case if you use `ppr: true` in the next config except the error message is ????
```
Error: Connection closed.
    at E (.next/server/app/[...slug]/page.js:1:12375)
    at y (.next/server/app/[...slug]/page.js:1:11338)
    at m (.next/server/app/[...slug]/page.js:1:10590)
Error while saving cache key: 1:076:["TDsMtf1qt9U-UxjDWi30Z","c0ca2a1aa70b60b1e39f0a96a312c9bb93fff0491b",[{"children":"$T","params":"$@1"},"$undefined"]] Error: Connection closed.
    at E (.next/server/app/[...slug]/page.js:1:12375)
    at y (.next/server/app/[...slug]/page.js:1:11338)
    at m (.next/server/app/[...slug]/page.js:1:10590)
Error occurred prerendering page "/[...slug]". Read more: https://nextjs.org/docs/messages/prerender-error
```
another reprod: https://github.com/char-ptr/next-15-dynio-ppr

**Comment by Xanacas** [comment]
@char-ptr I noticed you're using dynamic routes, which doesn't work for me neither - even though I've ppr not explicitly activated, I get the same error message in the constellation of:
- nextjs@canary.19
- dynamicIO enabled
- "use cache" in dynamic route

my minimal repo to reproduce it:
https://github.com/Xanacas/cache-key-error-on-build

**Comment by marcoshernanz** [comment]
Thanks for the report. I reproduced this on `15.1.1-canary.2`, but the configuration involved has since been removed. In Next.js 16, `cacheComponents: true` enables PPR and `experimental_ppr` is no longer supported. The repro builds on `16.3.1` after migrating the config, removing the route export, and making the cached page async. The dynamic-route cases mentioned in the comments were fixed by #78882 and covered further by #80462. Closing as obsolete.
