### ISSUE TITLE
DYNAMIC_SERVER_USAGE error with parallel and/or intercepted routes

### ISSUE THREAD

**Issue by diamondT** [vercel/next.js#74128]
### Link to the code that reproduces this issue

https://github.com/diamondT/with-modal-app

### To Reproduce

1. build application with `npm run build`
2. start with `npm run start`
3. navigate to `http://localhost:3005`
4. click on the "Create an address" button

### Current behavior
`Application error: a server-side exception has occurred (see the server logs for more information).
Digest: DYNAMIC_SERVER_USAGE`

### Expected Behavior
Clicking the button should navigate to `http://localhost:3005/address/create?type=A` and update the content accordingly

The page in question is using `searchParams`.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu Nov 14 12:54:01 UTC 2024 (099023b)
  Available memory (MB): 31992
  Available CPU cores: 16
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.1.1 // Latest available version is detected (15.1.1).
  eslint-config-next: 15.1.1
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes, Runtime

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

### Additional context

When running the application in dev mode with `npm run dev`, everything works as expected.

Manually marking the page as dynamic with `export const dynamic = 'force-dynamic'` also works as expected.

Since the page is using `searchParams`, it should be marked as a dynamic route. The same page as a regular route is indeed identified as dynamic, however the intercepted route is not. Build output:
```
...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
Error: Static generation failed due to dynamic usage on /address/create, reason: `await searchParams`, `searchParams.then`, or similar
    at m (.next/server/chunks/638.js:1:41139)
    at Object.get (.next/server/chunks/584.js:3:29779)
    at a (.next/server/app/address/create/page.js:1:3367)
    at stringify (<anonymous>)
 ✓ Generating static pages (7/7)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    


Redirects
┌ source: /:path+/
├ destination: /:path+
└ permanent: true


Rewrites
┌ source: /address/create
└ destination: /(.)address/create


Route (app)                              Size     First Load JS
┌ ○ /                                    3.74 kB         109 kB
├ ○ /_not-found                          979 B           106 kB
├ ○ /(.)address/create                   142 B           105 kB
└ ƒ /address/create                      142 B           105 kB
+ First Load JS shared by all            105 kB
  ├ chunks/4bd1b696-92810b4b4ece63ad.js  52.9 kB
  ├ chunks/517-cf90ad66b32a8bbf.js       50.5 kB
  └ other shared chunks (total)          1.88 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand


Process finished with exit code 0
```

**Comment by devsubid** [comment]
i got the same issue
using next@14.2.21, react@19.0.0-rc-66855b96-20241106

![image](https://github.com/user-attachments/assets/10af8ec7-161c-4c29-9124-7aeeca24d410)

**Comment by diamondT** [comment]
@devsubid keep in mind that the exception itself during build is not a problem, it's how dynamic routes are identified. 
the issue is that for intercepted routes there is no exception and the route is marked as static, although it should be dynamic.

**Comment by devsubid** [comment]
thanks

**Comment by Maisaan** [comment]
adding `export const dynamic = "force-dynamic";` to the file fixes this. But would like to know why this is being false flagged as static.

**Comment by diamondT** [comment]
well, this appears to have been fixed as of 15.1.5
thank you, whoever you are, whatever you did  :)


old build with the issue: `ƒ /address/create` route is marked dynamic but the intercepted route (`○ /(.)address/create`) is marked as static
```
> next build --debug

   ▲ Next.js 15.1.4

   Creating an optimized production build ...
(node:9103) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:9190) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
Error: Static generation failed due to dynamic usage on /address/create, reason: `await searchParams`, `searchParams.then`, or similar
    at m (.next/server/chunks/638.js:1:41139)
    at Object.get (.next/server/chunks/584.js:3:29779)
    at a (.next/server/app/address/create/page.js:1:3367)
    at stringify (<anonymous>)
 ✓ Generating static pages (7/7)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    


Redirects
┌ source: /:path+/
├ destination: /:path+
└ permanent: true


Rewrites
┌ source: /address/create
└ destination: /(.)address/create


Route (app)                              Size     First Load JS
┌ ○ /                                    3.74 kB         109 kB
├ ○ /_not-found                          979 B           106 kB
├ ○ /(.)address/create                   142 B           105 kB
└ ƒ /address/create                      142 B           105 kB
+ First Load JS shared by all            105 kB
  ├ chunks/4bd1b696-20882bf820444624.js  52.9 kB
  ├ chunks/517-da775dc7c050d5b8.js       50.5 kB
  └ other shared chunks (total)          1.88 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand
```
new build with proper behavior: both routes are marked dynamic
```
> next build --debug

   ▲ Next.js 15.1.5

   Creating an optimized production build ...
(node:9719) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:9791) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
Error: Static generation failed due to dynamic usage on /address/create, reason: `await searchParams`, `searchParams.then`, or similar
    at m (.next/server/chunks/638.js:1:41139)
    at Object.get (.next/server/chunks/584.js:3:29782)
    at a (.next/server/app/address/create/page.js:1:3367)
    at stringify (<anonymous>)
Error: Static generation failed due to dynamic usage on /(.)address/create, reason: `await searchParams`, `searchParams.then`, or similar
    at m (.next/server/chunks/638.js:1:41139)
    at Object.get (.next/server/chunks/584.js:3:29782)
    at n (.next/server/app/@modal/(.)address/create/page.js:1:4368)
    at stringify (<anonymous>)
 ✓ Generating static pages (7/7)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    


Redirects
┌ source: /:path+/
├ destination: /:path+
└ permanent: true


Rewrites
┌ source: /address/create
└ destination: /(.)address/create


Route (app)                              Size     First Load JS
┌ ○ /                                    3.74 kB         109 kB
├ ○ /_not-found                          979 B           106 kB
├ ƒ /(.)address/create                   142 B           105 kB
└ ƒ /address/create                      142 B           105 kB
+ First Load JS shared by all            105 kB
  ├ chunks/4bd1b696-20882bf820444624.js  52.9 kB
  ├ chunks/517-bef45994ef1b0d26.js       50.5 kB
  └ other shared chunks (total)          1.88 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand
```
