### ISSUE TITLE
Next15 + Turbo dev cause `instantiated because it was required from module but the module factory is not available.It might have been deleted in an HMR update.`

### ISSUE THREAD

**Issue by arvinxx** [vercel/next.js#74167]
### Link to the code that reproduces this issue

https://github.com/arvinxx/antd-next-cssvar

### To Reproduce

just git clone and `npm run dev`. then open `/`.

### Current vs. Expected behavior

if run using `next dev --turbo`, it will case instantiated error.

```
Error: Module [project]/node_modules/.pnpm/next@15.1.1_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/compiled/react/jsx-dev-runtime.js [app-client] (ecmascript) was instantiated because it was required from module [project]/app/Theme.tsx [app-client] (ecmascript), but the module factory is not available. It might have been deleted in an HMR update.
    at instantiateModule (http://localhost:3000/_next/static/chunks/_26785d._.js:650:15)
    at getOrInstantiateModuleFromParent (http://localhost:3000/_next/static/chunks/_26785d._.js:624:12)
    at esmImport (http://localhost:3000/_next/static/chunks/_26785d._.js:142:20)
    at [project]/app/Theme.tsx [app-client] (ecmascript) (http://localhost:3000/_next/static/chunks/app_c03c0b._.js:67:308)
    at http://localhost:3000/_next/static/chunks/_26785d._.js:693:27
    at runModuleExecutionHooks (http://localhost:3000/_next/static/chunks/_26785d._.js:738:9)
    at instantiateModule (http://localhost:3000/_next/static/chunks/_26785d._.js:691:9)
    at getOrInstantiateModuleFromParent (http://localhost:3000/_next/static/chunks/_26785d._.js:624:12)
    at commonJsRequire (http://localhost:3000/_next/static/chunks/_26785d._.js:157:20)
    at requireModule (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_79b2d4._.js:2676:29)
    at initializeModuleChunk (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_79b2d4._.js:3218:25)
    at readChunk (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_79b2d4._.js:3123:17)
    at react-stack-bottom-frame (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:13468:20)
    at beginWork (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:5343:77)
    at runWithFiberInDEV (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:631:20)
    at performUnitOfWork (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:7955:97)
    at workLoopConcurrent (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:7951:58)
    at renderRootConcurrent (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:7933:71)
    at performWorkOnRoot (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:7565:175)
    at performWorkOnRootViaSchedulerTask (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_react-dom_f83a73._.js:8394:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:3000/_next/static/chunks/2a6fd_next_dist_compiled_79b2d4._.js:2353:64)
```

but if this project is run on webpack mode (`next dev`), it will run correctly.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 22.12.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.4.0
Relevant Packages:
  next: 15.1.2 // Latest available version is detected (15.1.2).
  eslint-config-next: 15.1.2
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I have tested 15.1.1-canary.14. It's still failed.

**Comment by timneutkens** [comment]
```
[CODESANDBOX] Preparing devcontainer configuration and overrides

> nextjs@0.1.0 dev /project/antd-next-cssvar
> next dev --turbo

   ▲ Next.js 15.1.7 (Turbopack)
   - Local:        http://localhost:3000
   - Network:      http://172.17.0.2:3000

 ✓ Starting...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

 ✓ Ready in 1551ms
 ○ Compiling / ...
 ✓ Compiled / in 9.3s
 GET / 200 in 10027ms
 GET / 200 in 582ms
 GET / 200 in 146ms
 GET / 200 in 145ms
 GET / 200 in 223ms
```

I'm unable to reproduce this on the provided repository and also checked `next@canary` where it doesn't reproduce either. Here's a sandbox: https://codesandbox.io/p/github/arvinxx/antd-next-cssvar/csb-59dcg5/draft/bold-dubinsky

The only case where we've seen this happen is with dependencies in use that override `require.cache` in some way, which causes modules to be removed or preserved incorrectly. This happens for example with `dd-trace`.

Going to close this issue as it's been open for a while and there haven't been further reproduction steps.
