### ISSUE TITLE
Unable to use MDX with turbopack

### ISSUE THREAD

**Issue by max-degterev** [vercel/next.js#74424]
### Link to the code that reproduces this issue

https://github.com/max-degterev/nextjs-mdx-bugged

### To Reproduce

1. Follow official documentation steps described here https://nextjs.org/docs/pages/building-your-application/configuring/mdx#add-an-mdx-componentstsx-file
2. Attempt to use plugins with turbopack as described here https://nextjs.org/docs/pages/building-your-application/configuring/mdx#using-plugins-with-turbopack

### Current vs. Expected behavior

Next fails with an error:

```
 ⨯ ./src/app/test/page.mdx
Error evaluating Node.js code
TypeError: Expected usable value, not `remark-breaks`
    [at add (file:///Users/max/Repositories/nextjs-mdx-bugged/node_modules/unified/lib/index.js:1100:15)]
    [at addList (file:///Users/max/Repositories/nextjs-mdx-bugged/node_modules/unified/lib/index.js:1134:11)]
    [at Function.use (file:///Users/max/Repositories/nextjs-mdx-bugged/node_modules/unified/lib/index.js:1074:9)]
    [at createProcessor (file:///Users/max/Repositories/nextjs-mdx-bugged/node_modules/@mdx-js/mdx/lib/core.js:209:6)]
    [at split (file:///Users/max/Repositories/nextjs-mdx-bugged/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:85:37)]
    [at process (file:///Users/max/Repositories/nextjs-mdx-bugged/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:62:31)]
    [at Proxy.loader (file:///Users/max/Repositories/nextjs-mdx-bugged/node_modules/@mdx-js/loader/lib/index.js:89:3)]
    [at /Users/max/Repositories/nextjs-mdx-bugged/node_modules/@mdx-js/loader/index.cjs:32:26]
 ```
 
 Using this config:
 
 ```
 const withMDX = createMDX({
  options: {
    remarkPlugins: ['remark-breaks'],
    rehypePlugins: [['rehype-external-links', {
      target: '_blank', rel: ['noopener', 'noreferrer', 'nofollow'],
    }]],
  },
})

```

Which also produces type errors. Is there something I'm missing?

### Provide environment information

```bash
~/Repositories/nextjs-mdx-bugged │ master  npx --no-install next info                                                                                                         ✔
/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 22.12.0
  npm: 10.9.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.1.3 // Latest available version is detected (15.1.3).
  eslint-config-next: 15.1.3
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Markdown (MDX)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Other (Deployed)

**Comment by subproject22** [comment]
This is crazy. I expect huge amount of people dropping Next in favor of Astro/Vite just because of this, and seems like Next team ignore it (the main issue is closed)

**Comment by xianminx** [comment]
@max-degterev 
This was a known issue as https://github.com/vercel/next.js/issues/71819,  but as the PR has been merged, you can now use as you expect with the latest version of next.js and  `@next/mdx`. 

The [latest official documentation](https://nextjs.org/docs/pages/building-your-application/configuring/mdx#using-plugins-with-turbopack) on this: 

> Good to know:
> remark and rehype plugins without serializable options cannot be used yet with [Turbopack](https://nextjs.org/docs/app/api-reference/turbopack), due to [inability to pass JavaScript functions to Rust](https://github.com/vercel/next.js/issues/71819#issuecomment-2461802968)

I have tested with configure: 

```
 remarkPlugins: [['remark-breaks', {}]], 
 rehypePlugins: [['rehype-katex', { strict: true, throwOnError: true }]],
``` 

It worked without any problem. 

**Make sure you updated ` @next/mdx` to the latest version.** 
As I tested, it was 
```json
   "@next/mdx": "^15.1.6",
```

And as a remind, make sure you install the plugin deps `remark-breaks` and `rehype-katex`

For the other plugins you mentioned,  I did not test, but should work as long as the options for the plugin can be serialized as plain json object. 
 
FYI, the comment here is a little bit outdated: https://github.com/vercel/next.js/issues/71819#issuecomment-2461802968)

> MDX plugins are JavaScript functions which can't be transferred into Turbopack (given it's not JS), we'll have to add something like mdx.config.js to the MDX loader (and that flows into @next/mdx) so that these plugins don't have to be passed around like they are currently.
> For now you can remove --turbopack to have it run. The issue has already been triaged, you don't have to post comments saying "it still happens", that's expected when the issue is open 🙂

And if you may encounter any plugin whose options contain js functions, the current workaround is just disable `--turbo` for `next dev`. For `next build`, it does not support `turbopack` yet. 

Another explanation here: https://nextra.site/docs/guide/turbopack

**Comment by max-degterev** [comment]
Thank you!
